### ISSUE TITLE
Sündmuste kalendri toimetamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#1]
Sisu haldaja sisestab sündmuste kohta järgmisel joonisel esitatud Event ja EventCalendarItem andmeobjektide andmed:

![event](https://user-images.githubusercontent.com/24670133/40363864-7401a29e-5dd9-11e8-9902-466da7003500.png)

---
- id - Süsteem peab igale sündmusele omistama unikaalse identifikaatori. Sündmusi toimetav kasutaja näeb seda.
---
- Nimetus - name
---- Kui sündmusel on mitu toimumisaja kirjet, siis nimetuse järel kuvatakse korduva (mitmes osas toimuva) sündmuse ikoon.
- Lühikirjeldus - descroption.summary
- Sündmuse tüüp - type, valik sündmuse tüüpide (EventType) taksonoomiast 
- Sildid - tag,  valik siltide tüüpide (Tag) taksonoomiast, võib olla mitu
- Pilt - picture (suurused täpsustada lähtudes kasutajaliidese disainist)
- Kirjeldus - description.value
- Sündmusega seotud lingid - webPageLink, nimetus ja URL, võib olla mitu (välised lingid)
- Lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu
- Toimumise koha nimetus - location.name 
- Toimumise koha aadress - location.address
- Toimumise koha asukoht kaardil - location.map
- Toimumise koha asukoha veebileht - location.webpadeAddress
- Korraldaja - organizer
- Kontaktisik - contactPerson 
- Kontakttelefon - contactPhone
- Kontakt e-posti aadress - contactEmail
- Sissepääsu liik - entryType (valik: kutsetega, vaba sissepääs, registreerimine nõutud)
- Registreerimise alguse kuupäev - registrationFirstDate
- Registreerimise lõpu kuupäev - registrationLastDate
- Registreerimiste teavitamise e-posti aadress - registrationNotificationEmail
- Registreerimiste kinnitamise e-posti tekst - registrationConfirmationEmailText
- Osalejate maksimaalne arv - maxNumberOfParticipants 
- Osalejatele praktiline info - practicalInformation

Sündmuse toimumise aeg (peab olema vähemalt üks toimumisaeg, võib olla mitu):
- Toimumise kuupäev - eventDate
- Alguse kellaaeg - startTime
- Lõpu kellaaeg - endTime 
*****
**Täiendavad nõuded:**
* Süsteem peab kontrollima, et sündmuse toimumise aja kirjes startTime < endTime
* Süsteem peab kontrollima, et kui sissepääsu liik (entryType) on "registreerimine nõutud", siis on sisestatud registreerimise alguse ja lõpu kuupäev (registrationFirstDate, registrationLastDate).
* Sündmuse kohta tuleb salvestada loomise kuupäev ja kellaaeg, et kalendri kirje väljastamisel (vt https://github.com/hariduspilv/haridusportaal/issues/26) saaks täita dtstamp-i.
*****
Selgitusi:
- Toimumise aja kohta nii kuupäeva, alguse kellaaja kui ka lõpu kellaaja kohustuslik ja korrektne sisestamine on vajalik, et sündmust kalendris korrektselt kuvada.
*****
Sarnaste sündmuste sidumise kohta vt https://github.com/hariduspilv/haridusportaal/issues/109.

**Comment by TanelTromp** [comment]
Drupal sisuhaldus vearaport 

Viga1: Ei luba sisestada ilma "http://" laiendita URL-i. Admini mugavuse mõttes, ikkagi võiks.

<img width="580" alt="http" src="https://user-images.githubusercontent.com/37407917/38543587-9a5d190c-3cad-11e8-8553-60baf8d75426.PNG">

Viga2: ei saa lisada mitut linki. Hetkel ainult ühe lisamise võimalus >"Sündmusega seotud lingid - webPageLink, nimetus ja URL, võib olla mitu"

Viga3: ei saa lisada mitut faili. Hetkel ainult ühe lisamise võimalus>"Lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu".

Viga4: faili(de)le ei saa lisada nime, puudub väli>"Lisatud failid - attachmentFile, nimetus ja fail, võib olla mitu".

Parandus1: eemaldada sekundiväli sündmuste stardi ja lõpuaegades
Parandus2: muuta lisatava(te) faili(de) tüüp: PDF-ks (hetkel .txt). <Andrus

**Comment by TanelTromp** [comment]
@lsoonvald

**Comment by TanelTromp** [comment]
VIga1:  24H kellasüsteem ehk kaks välja vajalikud (hetkel 1):
![pilt](https://user-images.githubusercontent.com/37407917/38612530-a556ec1a-3d8f-11e8-923b-51f9c6f330fc.png)

Viga2: "registration confirmation email text" väli on passiivne (muutub aktiivseks kõikide väljade täitmisel ja salvestamisel):
![pilt](https://user-images.githubusercontent.com/37407917/38612562-c643b430-3d8f-11e8-9662-a8f6156f5602.png)
