### ISSUE TITLE
Sündmuste detailvaate kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#100]
**Üldkirjeldus:**
Portaali kasutajale kuvatakse sündmuse detailvaade, et portaali kasutaja saaks vaadata sündmuse kohta olemas olevat infot.

**Eeltingimused ja käivitamine:**
- Kasutajale on kuvatud sündmuste nimistu (vt https://github.com/hariduspilv/haridusportaal/issues/98). Kasutaja klikkab nimistus kuvatud sündmusel.

**Vastuvõtutingimused:**
* Süsteem kuvab kasutajale sündmuse (andmeobjektide Event ja EventCalendar) andmed:
-- Sündmuse nimetus
-- Kokkuvõtlik kirjeldus
-- Pilt (sh pealkiri)
-- Kirjeldus
-- Lingid, failid
-- Sündmuse tüüp ja sildid
-- Sissepääsu tüüp:
---- Kui sündmuse toimumise kuupäev (mitme toimumiseajaga sündmuse korral kõige viimane) < jooksev kuupäev, siis sissepääsu tüübi asemel kuvatakse "Sündmus on möödunud". 
---- Kui sissepääsu tüüp on "registreerumisega", siis:
------ Kui registreeritud osalejate (EventParticipant) arv >= maxNumberOfParticipants, siis kuvatakse veateade "Kohtade arv on täis".
------ Kui registreeritud registrationLastDate >= jooksev kuupäev), siis kuvatakse veateade "Registreerimine on lõppenud".
------ Muul juhul "registreerumisega" sündmuse korral kuvatakse "registreerimisega alates "registrationFirstDate " kuni " registrationLastDate. Vt registreerimise käivitamise kohta  #2 . 
---- Muul juhul kuvatakse sissepääsu tüüp (nt vaba, kutsetega). Vt vaba sissepääsuga sündmuse enda kalendrisse saatmise kohta #26.
-- Toimumiskoht kaardil (tsentreeritud keskele ja markeeritud, aluskaart on tänavakaart, vaikimisi zoomlevel 13, saab avada googlemap'i veebilehitseja uuel vahelehel)
-- Toimumisajad. Iga toimumisaja kohta nädalapäeva nimetus, kuupäev, alguse kellaaeg ja lõpu kellaaeg. Kui mitu toimumisaega, siis järjestatud kuupäeva ja alguse kellaaja järjekorras.
-- Toimumiskoha nimetus
-- Toimumiskoha aadress
-- Toimumiskoha veebilehe aadress
-- Korraldaja nimetus
-- Kontaktisiku nimi
-- Kontakt e-mail
-- Kontakt telefon
-- Praktiline info

* Toimumiskoha veebileht, kontakti e-posti aadress, telefoninumber(mobiilis) ja lingid peavad olema klikitavad. Failid peavad olema avatavad / alla laaditavad.
* Testimisel kontrollida pildi alt-teksti olemasolu.

* Sündmuste nimistusse liikumine: Süsteem avab sündmuste nimistu (https://github.com/hariduspilv/haridusportaal/issues/98).  
-- Sündmuste nimistu avatakse käesolevaga kuvatud sündmuse kohalt (see on nimistus nähtaval kohal).
-- Kui sündmuse detailvaatesse tuldi sündmuste nimistult ja seal oli rakendanud filtreerimist (toimumise aeg alates, toimumise aeg kuni, nimetuse, sündmuse liigi (liikide) ja/või sildi (siltide) alusel), siis rakendatakse uuesti samu filtreerimise tingimusi.

**Kasutajaliidese eskiis:**
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afeba79e8d73e250f0df398
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afeba7809a18d3d0f2bad4f

**Viited**:
Sündmuse andmete toimetamine https://github.com/hariduspilv/haridusportaal/issues/1.
Alternatiivsed kohad sündmuse detailvaatele jõudmiseks on  
-- kalender (vt https://github.com/hariduspilv/haridusportaal/issues/99)
-- avallehel sündmuste andmed (vt https://github.com/hariduspilv/haridusportaal/issues/3) 
-- sündmuse detailvaates sarnaste sündmuste nimistu (vt https://github.com/hariduspilv/haridusportaal/issues/110)
Muud tegevused sündmuse detailvaates:
-- Sündmusel osalemise registreerimine https://github.com/hariduspilv/haridusportaal/issues/2.
-- Sündmusega sarnaste sündmusega kuvamine https://github.com/hariduspilv/haridusportaal/issues/110.
-- Sündmusel osalejate andmete kuvamine https://github.com/hariduspilv/haridusportaal/issues/112.
-- Sündmuse enda kalendrisse saatmine https://github.com/hariduspilv/haridusportaal/issues/26.

**Comment by TanelTromp** [comment]
@skeefee

Vearaport #100_1

Tegevuse üldine kirjeldus: sündmuste detailvaate kuvamine

Testimise tegevused: funktsionaalsete nõuete testimine, mittefunktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59;
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A5 + Chorme
Windows tablet Thinkpad
Keskkond: http://htm.twn.ee/

Viga 1: mobiilivaates puudu "jaga" ikoon

Viga 2: puudu "korduvust" tähistav ikoon vs proto

![pilt](https://user-images.githubusercontent.com/37407917/39357501-be469322-4a1b-11e8-9fb6-7ec15d5aabab.png)

Viga 3: hooverdamised puudu CTA-lt, kohati on, kohati ei ole. Lisada kõigile vastavalt MD nõuetele

Probleem 1: ei saa testida seotust filtritega (kuna ei ole) ja järgmist vastuvõtutingimust:

 "Kui sündmuse detailvaatesse tuldi sündmuste nimistult ja seal oli rakendanud filtreerimist (toimumise aeg alates, toimumise aeg kuni, nimetuse, sündmuse liigi (liikide) ja/või sildi (siltide) alusel), siis rakendatakse uuesti samu filtreerimise tingimusi."

**Comment by skeefee** [comment]
Kõik korras v.a CTA hover. Selle räägime läbi koosolekul
