### ISSUE TITLE
Õppeasutuste andmete toimetamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#104]
Sisu haldaja saab sisestada õppeasutuse kohta järgmisel joonisel esitatud andmeobjektide andmed:

![educationalinstitution](https://user-images.githubusercontent.com/24670133/38874958-03e4a2a0-4262-11e8-8127-19aa0762520c.png)

***
* id - Süsteem peab igale õppeasutusele omistama unikaalse identifikaatori. Sündmusi toimetav kasutaja näeb seda.
***
* Nimetus - name; kohustuslik
* Registrikood - registrationCode; kohustuslik
* Õppeasutuse tüüp - type;  valik taksonoomiast; saab valida mitu väärtust
* Omandivorm - ownershipType;  valik taksonoomiast; 
* Õppekeel -  teachingLanguage; valik taksonoomiast; saab valida mitu väärtust
* Hariduslikud erivajadused- specialClass
* Õpilaskodu - studentHome
* Asukoha andmed (Location esialgu 1, aga edaspidi võib olla mitu kirjet):
-- Maakond - Location.county; valik taksonoomiast; 
-- Vald või linn - Location.localGoverment; valik taksonoomiast; 
-- Asustusüksus (küla, alevik, alev, linnaosa) - Location.settlementUnit; valik taksonoomiast; 
-- Aadress - Location.address
-- Geograafilised koordinaadid (laius) - Location.geoCoordinatesLat,
-- Geograafilised koordinaadid (pikkus) - Location.geoCoordinatesLong, 
-- Aadressi id aadressregistris - Location.adrId; 
-- Asukoha tüüp - Location.locationType; valik "Juriidiline aadress" (L), "Tegutsemiskoht" (V); kohustuslik
-- EHIS-st asukoha andmete automaatne uuendamine (jah/ei) - updateLocationFromEHIS; kohustuslik
* Kontaktandmed:
-- Telefon - Contacts.contactPhone
-- Epost - Contacts.contactEmail
-- Veebileht - Contacts.webpageAddress
* Õppeasutuse ID EHIS-s - EHIS_id
* EHIS-st andmete automaatne uuendamine (jah/ei) - updateFromEHIS; kohustuslik
* EHIS-st automaatselt lisamise aeg - createdFromEHIS - mittemuudetav
* Avaldamise staatus - published; kohustuslik

Täiendavad tingimused:
* EHIS_id väärtus peab olema unikaalne (süsteem peab seda kontrollima).
* Taksonoomiatest saab valida olemasolevaid väärtusi. Õppeasutuse sisestamise käigus ei saa taksonoomiat muuta, sh ei saa taksonoomiasse uusi väärtusi lisada.

Märkused:
* Geograafilise koordinaadis laiuskraad (Latitude) näitab "kui kaugel põhjas" asub ja peaks olema vahemikus 57 kuni 60 kraadi ning pikkuskraad (Longitude) näitab "kui kaugel idas" asub ja peaks olema vahemikus 21 kuni 29 kraadi.
* Kasutaja võib muuta kõiki andmeid. Juhul, kui on olemas EHISid ja EHIS-st andmete automaatne uuendamine on "jah", siis muudatused kirjutatakse automaatse uuendamisega üle. Seega, kui kasutaja tahab, et muudatusi üle ei kirjutataks, peab ta valima EHIS-st andmete automaatse uuendamise väärtuseks "ei".

**Viited:**
* Taksonoomiad https://github.com/hariduspilv/haridusportaal/issues/131

**Comment by TanelTromp** [comment]
Vearaport sisuhaldus Drupal

Viga 1: need ei ole kohustuslikud andmed ehk tärn eemaldada:  maakond, vald või linn, asustusüksus, aadress, koordinaadid, adrid

Viga 2: muuta "EHIS-st asukoha andmete automaatne uuendamine" checkboxist> bulletpointideks, kus on kuvatud "jah" ja "ei" valikute kastid,mis on mõlemad selekteerimata vaikimisi. See võimaldab selle valiku ka kohustuslikuks muuta nagu nõue on.

Viga 3: muuta "EHIS-st andmete automaatne uuendamine" checkboxist> bulletpointideks, kus on kuvatud "jah" ja "ei" valikute kastid,mis on mõlemad selekteerimata vaikimisi. See võimaldab selle valiku ka kohustuslikuks muuta nagu nõue on.

Viga 4: Muuta "EHIS-st automaatselt lisamise aeg" passiivseks ehk mitte muudetavaks. Hetkel kuupäeva ja kellaaja väljadel võimalik väärtusi muuta, kustutada ja sisestada.  Passiivsust ehk mitte muudetavust saab tähistada heleda halli värviga, lisades selle numbriväärtuste taustavärviks. 

Viga 5: "Avaldamise staatus - published; kohustuslik" - muuta väli vaikimisi mitte selekteerituks ja lisada tärn ehk kohustuslikkust tähistav atribuut.
@lsoonvald

**Comment by TanelTromp** [comment]
@lsoonvald 
viga 5 vol2:  teha "jah" "ei" valik.
![pilt](https://user-images.githubusercontent.com/37407917/39181754-50129888-47c3-11e8-9852-314058f45bb4.png)

Viga 6: ilmselt sama teema, mis uudistega ehk seda valikut ei peaks olema, sest kõik sisestuvad samasse kategooriasse.
![pilt](https://user-images.githubusercontent.com/37407917/39181840-91b667c4-47c3-11e8-9fb5-fe5c2796c6e0.png)
