### ISSUE TITLE
Õppeasutuste andmete uuendamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#105]
**Üldkirjeldus:**
Õppeasutuste andmete automaatne uuendamine EHIS avaandmetest. 

Õppeasutuste andmete uuendamiseks ei kasutata olemasolevast koolikaardi rakendusest saadavaid andmeid (https://www.hm.ee/koolikaart/xml_koolid.php), sest uus lahendus asendab olemasoleva koolikaardi rakenduse. EHIS-st mitte saada olevad andmed sisestatakse käsitsi (https://github.com/hariduspilv/haridusportaal/issues/104).

**Eeltingimused ja käivitamine:**
* Andmete uuendamise protsess käivitatakse automaatselt kord ööpäevas.
* Andmete uuendamise protsessi saab käivitada info haldaja käsitsi.

**Tegevused:**
1. Süsteem loeb EHISe avaandmetest õppeasutuste andmed.
1. Süsteem salvestab EHIS-st loetud õppeasutuste andmed portaali.
1. _Süsteem eemaldab avaldamise märke õppeasutustelt, mida EHIS-st enam ei saadud - eraldi issue https://github.com/hariduspilv/haridusportaal/issues/155._
1. _Süsteem postitab õppeasutuste andmete uuendamise kohta logikirje - eraldi issue https://github.com/hariduspilv/haridusportaal/issues/158._

**Tegevus 1: EHISe avaandmetest õppeasutuste andmete lugemine:**

* Päring tehakse ULR-lt http://enda.ehis.ee/avaandmed/rest/oppeasutused/-/-/-/-/-/-/-/-/-/-/1/JSON. Sealt saadakse kõikide tegutsevate õppeasutuste andmed.

* Kui andmete saamine ei õnnestu, siis postitakse logikirje (type = "EHIS avaandmetest õppeasutuste uuendamine"; severity - "error"; startTime - jooksev aeg; message - "EHIS avaandmete päringu viga", 
requestId - URL millelt päring tehti) ja protsess katkeb.

**Tegevus 2: EHIS-st loetud andmete salvestamine portaali:**

EHIS-st saadud iga _oppeasutus_ kirje kohta:
* Kui portaalis pole EHIS-st saadud kooli id-ga õppeasutuse kirjet (EHIS_id = oppeasutus.koolId), siis lisatakse portaali uus õppeasutuse kirje.

* Kui portaalis on olemas EHIS-st saadud kooli id-ga õppeasutuse kirje (EHIS_id = oppeasutus.koolId) ja õppeasutus on portaalis märgitud uuendatavaks (updateFromEHIS = true), siis portaalis õppeasutuse andmed kirjutatakse üle. Kui õppeasutus on portaalis märgitud mitte uuendatavaks (updateFromEHIS = false), siis õppeasutuse andmete üle kirjutamine jäetakse vahele ja protsessi jätkatakse järgmise õppeasutuse andmetega.

* Lisamise ja üle kirjutamise käigus andmeelementide vastavus:
-- name - EHIS nimetus
-- nameInEnglish - EHIS nimetusInglise
-- registrationCode - EHIS regNr
_-- type, ownershipType, teachingLanguage - eraldi issue https://github.com/hariduspilv/haridusportaal/issues/140_
_-- location - eraldi issue https://github.com/hariduspilv/haridusportaal/issues/129_
-- Contacts.contactPhone - EHIS kontaktAndmed.telefon 
-- Contacts.contactEmail - EHIS kontaktAndmed.epost 
-- Contacts.webpage.Address - EHIS kontaktAndmed.veebileht
_-- specialClass_
_-- studentHome_
-- EHIS_id - EHIS kool_id
-- updateFromEHIS - lisamisel 'true', üle kirjutamisel ei muudeta
-- createdFromEHISDateTime - lisamisel jooksev aeg, üle kirjutamisel ei muudeta
-- published - lisamisel 'true', üle kirjutamisel ei muudeta

**Täiendavad tingimused:**
* Täpsustada, mida tehakse enne kui nenditakse, et andmete saamine ei õnnestu - kui pikk on time-out ooteaeg, kui mitu korda kui suure ajavahega korratakse. 

**Viited:**
* Õppeasutuste andmemudel https://github.com/hariduspilv/haridusportaal/issues/104
* Õppeasutuse asukoha kirjeldamine https://github.com/hariduspilv/haridusportaal/issues/129
* Õppeasutuste taksonoomiatesse liigitamine https://github.com/hariduspilv/haridusportaal/issues/140
* Õppeasutuse avaldamise lõpetamine https://github.com/hariduspilv/haridusportaal/issues/155
* Õppeasutuste uuendamise logimine https://github.com/hariduspilv/haridusportaal/issues/158

**Comment by ruut12** [comment]
Eralasteaed Aarete saar:
mitu telefoninumbrit 2 numbrit omavahel ; eraldatud Importfailis
