### ISSUE TITLE
Siltide alusel teavituste tellimine (ilma sisse logimiseta)

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#106]
**Eesmärk, üldkirjeldus:**
Portaali külastaja saab sildi alusel tellida teavitusi avaldatud uudise ja sündmuse kohta.
Tellimuse saab vormistada portaali avalehelt.

**Eeltingimused ja käivitamine:**
Kasutaja on avanud portaali avalehe.

**Vastuvõtutingimused:**
- [ ] 1. Kasutaja saab valida (märkida) 1 kuni kõik sildid.
- [ ] 2. Kasutaja saab sisestada e-posti aadressi, millele teavitusi soovib saada.
- [ ] 3. Kasutaja saab kinnitada tellimuse.
- [ ] 4. Kasutajale kuvatakse tellimust kinnitavat teadet: _Tänud haridusteemade vastu huvi tundmast! Palume kinnitada uudiskirjaga liitumise soov lingi kaudu, mille edastasime tellimusega seotud e-posti aadressile._ Teate saab sulgeda, kasutaja jääb portaali avalehele.

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kujundus:** #250 
Avaleht_md: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b103a62a80569fd6f0b9533
Avaleht_xs: 
Teade: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1107b1577f6b945fe693cf

**Viited seotud teemadele:**
Siltide toimetamine: #13

Siltide alusel teavituste e-mailile väljastamine #157 ja #14
Siltide alusel teavituse tellimuse lõpetamine (unsubscribe) #108
Siltide alusel teavituse tellimuse muutmine #132
Siltide alusel teavituste tellimuste haldamine #107

**Comment by skeefee** [comment]
@TanelTromp

**Comment by TanelTromp** [comment]
Vastuvõtutingimused:**
- [ ] 1. Kasutaja saab valida (märkida) 1 kuni kõik sildid.
- [ ] 2. Kasutaja saab sisestada e-posti aadressi, millele teavitusi soovib saada.
- [ ] 3. Kasutaja saab kinnitada tellimuse.
- [ ] 4. Kasutajale kuvatakse tellimust kinnitavat teadet: _Tänud haridusteemade vastu huvi tundmast! Palume kinnitada uudiskirjaga liitumise soov lingi kaudu, mille edastasime tellimusega seotud e-posti aadressile._ Teate saab sulgeda, kasutaja jääb portaali avalehele.

**Kujundus:** #250 

- [ ] Avaleht_md: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b103a62a80569fd6f0b9533
- [ ] Avaleht_xs: 
- [ ] Teade: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1107b1577f6b945fe693cf

**Comment by TanelTromp** [comment]
Viga 1: ei tule enam e-kirja. Teekond: siltide valimine>tellimine>e-kirja sisust kinnitamine> avatud aknast (kus näitas liitumise modaali) uuesti siltide valimine>kinnitamine. E-kirja ei tule.

@skeefee

**Comment by skeefee** [comment]
Viga1 : See on Backendi teha @lsoonvald

**Comment by lsoonvald** [comment]
Viga 1: Fixed @TanelTromp
