### ISSUE TITLE
Siltide alusel teavituste tellimuste haldamine 

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#107]
**Eesmärk, üldkirjeldus:**
Sisuhaldur saab vaadata siltidega seotud tellimusi.

**Eeltingimused ja käivitamine:**

- Kasutajal on peakasutaja õigused.
- Kasutaja on peakaksutajana sisse loginud.

Selle töö raames eeltingimusi ei testita.

**Vastuvõtutingimused:**

**NB! Selle töö raames luuakse Drupalis võimalused andmete salvestamiseks.**

Testimisel arvestada, et salvestatud andmeid veel pole! Arendaja märgib, mis osad on selle töö raames realiseeritud.

**Töö eesmärk:**

1. Sisuhaldur näeb tellimuste nimekirja, milles kuvatakse (koos Drupal vaikimisi parameetritega):
- E-posti aadress, millega tellimus on seotud
- E-posti aadressiga seotud siltide nimetused 
- Kuupäev, millal tellimus vormistati
- Checkbox (täitmata, kui tellimus on lõpetatud)

2. Nimekiri kuvatakse esmalt aktiivsete tellimuste alusel tellimuse vormistamise kuupäeva järgi, kõige viimane liitumine esimesena.
Lõpetatud tellimused unscribed kuvatakse nimekirja lõpus (automaatselt ei kustutata süsteemist).

3. Sisuhaldur saab iga tellimuse lõpetada võttes checkbox'st (Published) linnukese ära.

Viited:
Siltide toimetamine: #13
Siltide alusel teavituste tellimine  #106 #157 #160 
Siltide alusel teavituste e-mailile väljastamine #14
Siltide alusel teavituse tellimuse lõpetamine (unsubscribe) #108, muutmine #132

**Comment by TanelTromp** [comment]
1. Sisuhaldur näeb tellimuste nimekirja, milles kuvatakse (koos Drupal vaikimisi parameetritega):
- E-posti aadress, millega tellimus on seotud
- E-posti aadressiga seotud siltide nimetused 
- Kuupäev, millal tellimus vormistati
- Checkbox (täitmata, kui tellimus on lõpetatud)

2. Nimekiri kuvatakse esmalt aktiivsete tellimuste alusel tellimuse vormistamise kuupäeva järgi, kõige viimane liitumine esimesena.
Lõpetatud tellimused unscribed kuvatakse nimekirja lõpus (automaatselt ei kustutata süsteemist).

3. Sisuhaldur saab iga tellimuse lõpetada võttes checkbox'st (Published) linnukese ära.
