### ISSUE TITLE
Siltide alusel teavituse tellimuse lõpetamine (unsubscribe)

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#108]
**Eesmärk, üldkirjeldus:**
Kasutaja soovib tühistada uudiskirja tellimuse.

**Eeltingimused ja käivitamine:**
Kasutaja on tellinud teavituse (pilet nr #106 #157 ja #160 on realiseeritud).
Kasutaja on saanud teavitusega e-kirja (pilet nr #14 on realiseeritud).

**Vastuvõtutingimused:**
1. Kasutaja vajutab e-kirja jaluses linki [unsubscribe link].
- [ ] 2. Kasutajale kuvatakse haridusportaali URL aadressiga lehte teatega:

_Tänud haridusteemade vastu huvi tundmast. Olete loobunud haridusteemalisest uudiskirjast.
Külastage jätkuvalt veebiaadressi [Haridusportaali veebiaadress]._

Kujundus: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1107b0df003d41487aa738

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Viited:**
Siltide toimetamine: #13 
Siltide alusel teavituste tellimine  #106 #157 #160 
Siltide alusel teavituste e-mailile väljastamine #14
Siltide alusel teavituse tellimuse muutmine #132
Siltide alusel teavituste tellimuste haldamine #107

**Comment by skeefee** [comment]
@TanelTromp

**Comment by TanelTromp** [comment]
TEST
  
Kasutajale kuvatakse haridusportaali URL aadressiga lehte teatega:


- [ ] Tänud haridusteemade vastu huvi tundmast. Olete loobunud haridusteemalisest uudiskirjast.
Külastage jätkuvalt veebiaadressi [Haridusportaali veebiaadress].

- [ ] Kujundus: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1107b0df003d41487aa738
