### ISSUE TITLE
Sündmuste kalendri toimetamine - sarnaste sündmuste sidumine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#109]
Sisu haldaja saab omavahel gruppi (EventsGroup) siduda sarnaseid sündmusi (Event). 

Sündmuste andmed peavad olema sisestatud (https://github.com/hariduspilv/haridusportaal/issues/1).

**Sündmuste sidumine gruppi**:
Sündmust saab siduda gruppi siis, kui toimetatav sündmus ei kuulu gruppi.

Sisu haldaja valib grupi, kuhu ta soovib sündmuse panna. Grupp valitakse grupi nime _autocomplete_ sisestusega. Kui sisestatud nimega gruppi pole,  siis luuakse uus grupp.

**Sündmuste grupi kuvamine**:
Kui sündmus kuulub gruppi, siis süsteem kuvab gruppi kuuluvate sündmuste nimistu. Iga sündmuse kohta on nimistu kuvatud id, nimetus...

**Sündmuste grupist eemaldamine**:
Kui sündmus kuulub gruppi, siis saab sündmust sealt eemaldada.

Grupi kustutamiseks kustutatakse grupp gruppide taksonoomiast.

**Comment by MirellKr2** [comment]
Pilet Drupali poolelt testitud. Funktsionaalsus töötab.
