### ISSUE TITLE
Uudise toimetamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#11]
Sisu toimetaja sisestab uudise kohta järgmisel joonisel esitatud News andmeobjekti andmed:
![news](https://user-images.githubusercontent.com/23524151/37966442-288d143a-31d1-11e8-84a7-ac5a71054204.png)

id - Süsteem peab igale uudisele omistama unikaalse identifikaatori. Uudiseid toimetav kasutaja näeb seda.

**Uudise andmekoosseis ja valideerimise tingimused:**
- Pealkiri (title), kohustuslik
- Autor (author), kohustuslik
- Kuupäev (date) automaatselt avaldamise kuupäev, kohustuslik
- Sissejuhatus (shortDescription), kohustuslik
- Avafoto (introductoryPicture), kohustuslik, alternatiivse teksti sisestamine on kohustuslik
- Sisutekst (fullDescription), kohustuslik
- Foto (picture), vabatahtlik, kuni 3-e foto lisamise võimalus, peab eraldi laadima, alternatiivse teksti sisestamine on kohustuslik (üle 3-e foto lisamisel sidumine galeriiga). _NB! kolmandas sprindis ei testita sidumist galeriiga, so eraldi töö galerii teemaga._
- Sildid (Tag), vabatahtlik.
- Lingid (Link), vabatahtlik (Lingi pealkiri ja URL)

**Viited seotud teemadele:**
Uudiste nimekiri: #12 
Uudise detailvaade: #95
Uudised avalehelt: #96

Siltide toimetamine: #13
Uudise e-postile tellimine: #14

**Comment by EgleM-TW** [comment]
Sissejuhatus:
Uudised on Portaali avalehel uudiste rubriigis kuvatavad teated.
Avalehel kuvatakse kahe viimati avaldatud uudise lühisisu
→ "Loe lähemalt" avab uudise täisteksti (uudiste nimekirja alamleht);
→ "Vaata kõiki" avab uudiste nimekirja (uudiste nimekirja leht).
Uudiste kuvamise järjekord tuleneb automaatselt sisu viimasest avaldamise ajast.

Uudise toimetamisel kehtivad sisuhaldamise reeglid.
Eeltingimus: kasutajal on õigus uudist lisada.

Kohustuslikud väljad:
- Pealkiri
- Autor (automaatselt sisestaja, saab käsitsi muuta)
- Kuupäev (automaatselt sisestamise/ avaldamise aeg)
- Sisutekst
Nö vabatahtlikud väljad:
- Foto lisamine
- Lingi lisamine ("Soovitatud artiklid", Kui lingitakse teine uudis, siis lehekülje avaldamisel kuvatakse see uudise lühisisuna (sarnaselt avalehele).
- Tag

Selgitada:
Kas autori andmed sarnaselt HTM lehel olevale: https://www.hm.ee/et/uudised/aasta-parim-eestikeelne-korgkooliopik-statistika
Kas uudiste nimekirja vaade sarnaselt HTM-le: https://www.hm.ee/et/uudised

**Comment by TanelTromp** [comment]
D8 sisuhaldus test

Viga1: eemaldada kellaaeg, mis ei ole vastuvõtutingimustes määratud

Viga2: ei näita õiget kuupäeva (päeva võrra nihkes)

Viga3: hetkel ei ole "Sissejuhatus (shortDescription)" see väli kohustuslik. Lubab salvestada ilma "summary" kasti sisu kandmata.

Viga4: ei luba sisestada "www"-algavat linki:
![pilt](https://user-images.githubusercontent.com/37407917/38920705-8f208d26-42fc-11e8-9216-1c60541a15de.png)

Viga5: tagide sisestamisel kuvab viga ehk ei luba sisestada tage:
![pilt](https://user-images.githubusercontent.com/37407917/38920950-2f7a6f3a-42fd-11e8-8723-0ebb0a8904a8.png)
![pilt](https://user-images.githubusercontent.com/37407917/38920973-3dd57e12-42fd-11e8-97ed-96f18241963f.png)

@lsoonvald

**Comment by TanelTromp** [comment]
Viga 6: kui "Summary" väli on folditud ("hide summary") ja sisust tühi, siis ei anna veateadet "palun täida see väli" - lihstalt ei lase salvestada. Kui väli on avatud staatuses, siis annab veateate.

Viga6 .2: kuna "Sissejuhatus (shortDescription)" tekst on kohustuslik, siis kuvada see väli vaikimisiavatult, mitte suletule nagu hetkel ehk see lahendab ka probleemi "Viga 6".

Viga 7: linke peab saama lisada rohkem kui ühe.
@lsoonvald

**Comment by EgleM-TW** [comment]
23.04.18 groomingul:
Kui kuupäev sisestamata, kuvame vaikimisi tänast kuupäeva.
Sisestatud kuupäeva alusel käivitub avaldamine. Portaalis kuvatakse need uudised, mille avaldamise kuupäev on minevikus. Kontrollimise aeg 00:00.

**Comment by EgleM-TW** [comment]
Sisuosa järel on linkide sisestamine. Lisame nõude: lingi lisamisel peab sisestama lingi pealkirja ja URL aadressi. Uudise kuvamisel võtame lingi pealkirja, millele klikates avaneb URL.

Link:
- title
- webPageAddressUrl

**Comment by TanelTromp** [comment]
@EgleM-TW 
Seda ei saa täielikult kontrollida, sest ei ole front-endis kuvatud veel ehk see tuleks uudiste kuvamise front-endi piletisse lisada:
23.04.18 groomingul:
"Kui kuupäev sisestamata, kuvame vaikimisi tänast kuupäeva.
Sisestatud kuupäeva alusel käivitub avaldamine. Portaalis kuvatakse need uudised, mille avaldamise kuupäev on minevikus. Kontrollimise aeg 00:00."

@lsoonvald 

Viga 8: mitte kuvada "provide a menu linki" ja valikuid, vaid vaikimisi sisestamine seadistada, et kuvab vastavas "uudiste" menüüs kõiki sisestatud uudiseid. Kasutaja ei tohi ja ei pea seda teha saama.

Viga 9: kui sisestada "avaldamise kuupäev" tulevikku, salvestada uudis ja tulla tagasi seda muutma hiljem selleks, et midagi sisestaud ei ole, siis annab veateate. See peaks olema muudetav/parandatav.
![pilt](https://user-images.githubusercontent.com/37407917/39179350-c476e4b0-47bc-11e8-9712-045573a6cb9f.png)

Viga 9-2: kuidas suhestuvad omavahel inglise keelne ja eesti keelse sisulisamises uudise "avaldamise aeg"? St kui ühes muuta ära, kas see muutub ka teises automaatselt? Hetkel ei muutu aga need peavad alati samad olema (Andrus says).

**Comment by lsoonvald** [comment]
Viga 9 on suhteline, kui juba kuupäeva väljad ära kustutada, siis peaks kellaaja väljad ka ära kustutama, hetkel on need jäetud 00:00:00, selle reegli sissetoomine tähendaks suuremat sorti arendust.

Viga 9-2 kohta tuleks teha uus issue, nõuab suuremat arendust, hetke lahendus ei toeta seda. Kui artikli teed ja seal kohe publishing kuupäeva kirja paned, siis läheb see üle ka translationi artiklile kui hakkad seda tegema. Kui on juba varasemalt tehtud mingid artiklid ja ühel keelel vahetada publishing kuupäeva, siis see ei lähe automaatselt teises keeles olevale artiklile.

**Comment by EgleM-TW** [comment]
"...Kui on juba varasemalt tehtud mingid artiklid ja ühel keelel vahetada publishing kuupäeva, siis see ei lähe automaatselt teises keeles olevale artiklile."

Eelnevat olukorda ei käsitleta veana. Hetkel uut piletit selle arenduseks ei loo.

**Comment by Kyllike** [comment]
#11_HTM
Viga 1: uudisele pilte lisades ei kuvata pisipilte korralikult (testitud Google Chrome Versioon 66.0.3359.181): http://test.edu.ee:4200/#/et/uudised/minister-reps-osaleb-jeruusalemmas-konverentsil 
![image](https://user-images.githubusercontent.com/38042389/40617143-0ddd02e4-6296-11e8-959d-6ea4f30798e2.png)

Tähelepanek: kui mitmel uudisel on sama silt, siis sellele klõpsates ei pea veel midagi juhtuma?

@heldiraudsepp

**Comment by ruut12** [comment]
Sellele leidsin mooduli mis probleemi lahendaks.
