### ISSUE TITLE
Sündmusel osalejate andmete kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#112]
**Üldkirjeldus:**
Sündmuse (Event) korraldaja õigust omav kasutaja (EventOrganizerAccess) saab vaadata sündmuse osalejate andmeid (EventParticipant).

**Eeltingimused:**
* Kasutajale on kuvatud sündmuse detailvaade (https://github.com/hariduspilv/haridusportaal/issues/100).
* Kasutaja on portaali sisse loginud. Süsteemil on teada kasutaja isikukood.
* Kasutaja on sündmuse korraldaja õigust omav isik (sündmuse juures on EventOrganizerAccess, kirje kus personalIdCode = kasutaja isikukood).

Kui eelnevalt kirjeldatud tingimused on täidetud, siis kasutaja saab sündmuse detailvaatelt saab avade osalejate nimekirja.

**Andmed:**
* Osalejate nimekirjas kuvatakse iga osaleja kohta jrk nr (kuvamise käigus genereeritav järjekorra number), osaleja eesnimi, osaleja perekonnanimi, ettevõte/asutus, e-posti aadress, telefoni number, registreerimise kuupäev ja kellaaeg, märkused.  
* Osalejate nimikiri on vaikimisi järjestatud registreerimise kuupäeva ja kellaaja järjekorras. 
* Osalejate nimekirja päises kuvatakse registreerunud osalejate arv.

**Tegevused:**
* Kasutaja saab nimekirja järjestada osaleja perekonnanimi+eesnime alusel ja ettevõtte/asutuse alusel.
***
Kuvatud nimekirja faili väljastamise kohta vt https://github.com/hariduspilv/haridusportaal/issues/113.
***
**Kasutajaliidese eskiis:**
axshare link

**Comment by skeefee** [comment]
Viga 1 korras
