### ISSUE TITLE
Sündmusel osalejate andmete väljastamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#113]
**Üldkirjeldus**:
Sündmuse (Event) korraldaja õigust omav kasutaja (EventOrganizerAccess) saab süsteemist eksportida sündmuse osalejate andmeid (EventParticipant).

**Eeltingimused ja käivitamine**:
* Kasutajale on kuvatud sündmusel osalejate andmed (https://github.com/hariduspilv/haridusportaal/issues/112).
* Kasutaja käivitab faili salvestamise.

**Vastuvõtutingimused**:
* Süsteem koostab osalejate andmetest faili. Kasutaja saab faili avada / alla laadida.
* Fail  on CSV formaadis. 
* Eraldajana kasutatakse semikoolonit ( ; ). 
* Andmetes sisalduvad semikoolonid asendatakse komaga.

**Comment by heldiraudsepp** [comment]
BE - 6
FE - 6
Test - 2

**Comment by TanelTromp** [comment]
Vastuvõtutingimused:

- [ ]     Süsteem koostab osalejate andmetest faili. Kasutaja saab faili avada / alla laadida.
- [ ]     Fail on CSV formaadis.
- [ ]     Eraldajana kasutatakse semikoolonit ( ; ).
- [ ]     Andmetes sisalduvad semikoolonid asendatakse komaga.

**Comment by TanelTromp** [comment]
![pilt](https://user-images.githubusercontent.com/37407917/41506773-c7fe2fea-722c-11e8-877e-6ea58f4dcf8a.png)
