### ISSUE TITLE
Uudiste nimekirja vaade

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#12]
**Üldkirjeldus**
Kuvada uudiste (News) nimekiri, milles kuvatakse uudised avaldamise kuupäeva alusel kõige uuem esimesena.

**Eeltingimused ja käivitamine**
Kasutaja jõuab uudiste nimekirja:

1. Avalehelt valides uudise blokist „Vaata kõiki“
2. Uudise detailvaatest valides „Kõik uudised“

**Vastuvõtutingimused:**

1. Uudiste nimekirja lehe pealkiri on „Uudised“
2. Nimekirjas kuvatakse iga uudise kohta:
- avafoto (introductoryPicture) kahandatult
- kuupäev (date)
- autor (autor)
- pealkiri (title)
- sissejuhatus (shortDescription)
- sildid (Tag's)

Kasutaja saab:

1. avada uudise detailvaate
2. uudise detailvaatest navigeerida tagasi uudiste nimekirja vaatesse
3. Paginatsioon: 2-faasiline laadimine (laadi veel funktsioon)

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Kasutajaliidese eskiis:
https://6aofpb.axshare.com/#g=1&p=uudised_list_lg
https://6aofpb.axshare.com/#g=1&p=uudised_list_md
https://6aofpb.axshare.com/#g=1&p=uudised_list_xs

**Kujundus: zpl://screen?sid=5af04a467461125c4114b7b0&pid=5ae9c7f3c560dffb217da75c**

Viited seotud teemadele:
Uudise toimetamine: https://github.com/hariduspilv/haridusportaal/issues/11
Uudise detailvaade: https://github.com/hariduspilv/haridusportaal/issues/95
Uudised avalehelt: https://github.com/hariduspilv/haridusportaal/issues/96

Uudise nimekirja filter: #156

**Comment by EgleM-TW** [comment]
Seos: https://github.com/hariduspilv/haridusportaal/issues/11
Kas uudiste nimekirja vaade sarnaselt HTM-le: https://www.hm.ee/et/uudised

**Comment by EgleM-TW** [comment]
@birgitpulk:
Palun lisa viide kujundatud vaatele. Vajalik nii arendajale kui ka testimiseks. 
Palun lisa nõuded (mõõdud) fotole.

**Comment by MirellKr2** [comment]
Vea raport #12_1
•	Tegevuse üldine kirjeldus: uudiste nimekirja vaate testimine
•	Testimise tegevused: funktsionaalsete nõuete testimine, mittefunktsionaalsete nõuete testimine.
•	Brauserid: Chrome 65
•	Op. süsteem: Windows 10, PC 64bit
•	Keskkond: http://htm.twn.ee/

**Probleem 1**
Uudiste nimekirja vaate/lehe pealkiri on eestikeelne mõlema keele puhul. Pealkiri ei muutu ka keele vahetamisel ehk on nii eesti kui ka inglise keeles sama ("Uudised").

**Probleem 2**
Lehe värksendamisel (F5) ilmub menüü asemel korraks lehe pealkiri ("Uudised") ja lehe osad nihkuvad hetkeks paremale (logo, menüü, sisuosa, kellevalik).

**Muudatus 1**
Kasutaja ei saa avalehelt uudiste blokist uudiste nimekirja liikuda (ei olnud selle sprindi fookuses)

**Comment by skeefee** [comment]
Probleem 1:  Tõlgete tekstid tulevad järgmiste sprintide jooksul
Probleem 2:  See on seetõttu, et lehel ei ole veel loaderit. Tuleviku sprint
Muudatus 1:  Teine ticket.
