### ISSUE TITLE
Keele valik

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#122]

**Comment by skeefee** [comment]
Keelevaliku testimiseks peab korrektselt sisu sisestama kas testija või arendaja poolt

**Comment by TanelTromp** [comment]
@skeefee 
Vearaport #122_1

Tegevuse üldine kirjeldus: keelevaliku testimine 
Testimise tegevused: funktsionaalsete nõuete testimine, mittefunktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Safari 5.1.7
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
iPhone 6 + Safari
Samsung Galaxy A5 + Chrome
Windows tablet Thinkpad + Chrome
Keskkond: http://htm.twn.ee/

Viga 1: muutes keelt sündmuste kategooriast väljas (ehk nt avalehel), muutuvad küll kategooriate nimed (s.h "sündmused">"eventsiks") aga sündmused ise ei muutu inglise keelseks.

**Comment by skeefee** [comment]
1. Backend tõlgete viga
2. See on järgmise sprindi töö

**Comment by skeefee** [comment]
Võid testida

**Comment by TanelTromp** [comment]
@ruut12 
Viga 3: ei vaheta uudiste artikleid inglise keele sisu vastu (adminnis on in k variandid loodud):

https://gyazo.com/90c4ec4166be4039b2906c3a2717f3e1
