### ISSUE TITLE
Menüü mitmetasemelisus

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#123]

**Comment by MirellKr2** [comment]
Käesolev arenduspilet on seotud #81 Menüü kuvamise piletiga.

**Comment by skeefee** [comment]
Viga 1: Lehele on vaja teha loader, et kõik vajalikud tausta asjad saaks laetud ja siis kuvame lehte. See jääb järgmisse sprinti.

Viga 2: Parandatud

Viga 3: Breadcrumbsile määratud max laius. Menüü link oli näide ja reaalselt ei tohiks see nii pikk olla

Viga 4: Parandatud

Viga 5: Panin menüü nupust parema äärega joondu

Viga 6: Need warningud ei ole olulised. HTML on korrektne lihtsalt HTML5 puhul pole type vajalik. Vaatan järgmine sprint mida ma selle Angular configa teha saan, et ta neid ei paneks.
