### ISSUE TITLE
Sündmuste nimekirja filtreerimine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#126]
**Teha veel sprint 8 koodi optimeerimine vt ka #282**

**Üldkirjeldus:**
Filtreerida kuvatud sündmuste nimekirja, et leida huvipakkuvaid sündmusi.

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud sündmuste nimistu (vt https://github.com/hariduspilv/haridusportaal/issues/98).

**Vastuvõtutingimused:** 
* Sündmusi saab filtreerida järgmiste tunnuste alusel:
-- nimetus - süsteem otsib sündmused, mille nimetuses (name) sisaldub sisestatud string, kusjuures võrdlus ei ole tõstutundlik (suur- ja väiketähed loetakse samaväärseks) 
-- toimumise kuupäev alates - süsteem otsib sündmused, mille vähemalt ühe toimumise aja kirjes (EventCalendarItem) olev Toimumise kuupäev (eventDate) >= sisestatud kuupäev
-- toimumise kuupäev kuni - süsteem otsib sündmused, mille vähemalt ühe toimumise aja kirjes (EventCalendarItem) olev Toimumise kuupäev  (eventDate)<= sisestatud kuupäev
---- Kui kasutaja sisestas "toimumise kuupäev kuni" ja ei sisestanud "toimumise kuupäev alates", siis:
------- kui sisestatud "toimumise kuupäev kuni" >= tänane kuupäev, siis süsteem võtab toimumise kuupäev alates vaikeväärtuseks tänase kuupäeva,
------- kui sisestatud "toimumise kuupäev kuni" < tänane kuupäev, siis süsteem vaikimisi järjestab sündmused toimumise aja järgi kahanevas järjekorras (hiljem toimuvad ehk tänasele kuupäevale lähemad ees).
-- sündmuse liik - süsteem otsib sündmused, mille liik (type) sisaldub valitud sündmuse liikide hulgas
-- silt - süsteem otsib sündmused, mille vähemalt üks silt (tag) sisaldub valitud siltide hulgas

* MD vaatel on sündmuse liigi ja sündmuse sildi alusel filtreerimine peidetud "Täpsem otsing" alla. XS vaatel on kogu filter vaikimisi peidetud.

**Kasutajaliidese eskiis:**
- Sündmuse listvaade [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b045be02a9c0c3328ef9330)
- Sündmuse listvaade mobiil [Disaini link: filter kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe907930a5d823224a983e) , [Disaini link: filter lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe90795ad91520379787f9)

**Viited:**
* Sündmuste nimistu  https://github.com/hariduspilv/haridusportaal/issues/98.

**Comment by TanelTromp** [comment]
**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud sündmuste nimistu (vt https://github.com/hariduspilv/haridusportaal/issues/98).

**Vastuvõtutingimused:** 
* Sündmusi saab filtreerida järgmiste tunnuste alusel:
-- nimetus - süsteem otsib sündmused, mille nimetuses (name) sisaldub sisestatud string, kusjuures võrdlus ei ole tõstutundlik (suur- ja väiketähed loetakse samaväärseks) 
-- toimumise kuupäev alates - süsteem otsib sündmused, mille vähemalt ühe toimumise aja kirjes (EventCalendarItem) olev Toimumise kuupäev (eventDate) >= sisestatud kuupäev
-- toimumise kuupäev kuni - süsteem otsib sündmused, mille vähemalt ühe toimumise aja kirjes (EventCalendarItem) olev Toimumise kuupäev  (eventDate)<= sisestatud kuupäev
---- Kui kasutaja sisestas "toimumise kuupäev kuni" ja ei sisestanud "toimumise kuupäev alates", siis:
------- kui sisestatud "toimumise kuupäev kuni" >= tänane kuupäev, siis süsteem võtab toimumise kuupäev alates vaikeväärtuseks tänase kuupäeva,
------- kui sisestatud "toimumise kuupäev kuni" < tänane kuupäev, siis süsteem vaikimisi järjestab sündmused toimumise aja järgi kahanevas järjekorras (hiljem toimuvad ehk tänasele kuupäevale lähemad ees).
-- sündmuse liik - süsteem otsib sündmused, mille liik (type) sisaldub valitud sündmuse liikide hulgas
-- silt - süsteem otsib sündmused, mille vähemalt üks silt (tag) sisaldub valitud siltide hulgas

* MD vaatel on sündmuse liigi ja sündmuse sildi alusel filtreerimine peidetud "Täpsem otsing" alla. XS vaatel on kogu filter vaikimisi peidetud.

**Comment by doomler** [comment]
Viga 1,2: parandatud

**Comment by TanelTromp** [comment]
Viga 3:  kui kasutaja vajutab "ENTER" peab see aktiveerima otsingu. Otsing aktiveeritakse ka "Otsi" nupuga.
Viga 4: URL-il ei kuva otsinguajalugu aga peaks (sama teema ka uudistefiltris tegelikult)
Viga 5: uudiste ja sündmuste filtris kuvab kuupäevi erinevalt:
![pilt](https://user-images.githubusercontent.com/37407917/41049181-fe4bce58-69b8-11e8-850c-fbfaca8224db.png)
![pilt](https://user-images.githubusercontent.com/37407917/41049201-0b1f53d4-69b9-11e8-8d47-481afa371d3b.png)
Peaks sama loogika olema.
@doomler

**Comment by skeefee** [comment]
Viga 3: Korras
Viga 4: Korras
Viga 5: Korras
@TanelTromp

**Comment by TanelTromp** [comment]
TESTRAPORT 2:

Viga 0: See läks madisele aga on siin tingimustes kirjas: _MD vaatel on sündmuse liigi ja sündmuse sildi alusel filtreerimine peidetud "Täpsem otsing" alla. XS vaatel on kogu filter vaikimisi peidetud_

Viga 1: selektsiooniga ei saa välju kustutada (Chrome+backspace):
https://gyazo.com/ab7ea2c54e8d9ee85e241fd395dc538b

Viga 2: Tahan muuta "aeg alates" väärtust peale seda kui olen ära kustutanud "aeg kuni" väärtuse sisu ja ei lase, kuna kuupäeva on passiivsed:
https://gyazo.com/99e9efbeef83e6c5833a768064d80311

Nice2have? 1: võiks kuvada tagasiulatuvalt ainult aastaid alates, kui esimene sündmus on loodud ehk käesolev: 
![pilt](https://user-images.githubusercontent.com/37407917/42323670-98630c88-8069-11e8-8ed0-19649e548ab5.png)

Viga 3: kui kustutada  "aeg kuni" väli, siis URL ei muutu ja ei kuva uuesti "Otsi" vajutades enam tulemust:
URL, mis ei uuene:
http://htm.twn.ee/et/sundmused?title=24%2F7&dateTo=01-07-2018&dateFrom=02-02-2012
Näide:
https://gyazo.com/5923eec5003e84217040f727b187d0c9

**Comment by skeefee** [comment]
KÕik korras @TanelTromp

**Comment by TanelTromp** [comment]
TEST 126_3

_Viga nicetohave1?-ga seoses: kui valida umbluu aasta kalendrist ja siis see valik kinni panna, siis võiks järgmine kord "aeg alates" kalendrit kuvada ikkagi käesoleva kuu ja aastaga._
+
_Nice2have? 1: võiks kuvada tagasiulatuvalt ainult aastaid alates, esimese sündmuse loomisest ehk käesolev aasta_
Ei ole korras.

Viga 2: kalender on inglise keelne

@skeefee

**Comment by skeefee** [comment]
Viga 2 korras

**Comment by TanelTromp** [comment]
Seotud piletiga: #377
