### ISSUE TITLE
Testplaani koostamine ja done kriteeriumi kokkuleppimine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#127]

**Comment by TanelTromp** [comment]
Done kriteerium:

**Comment by TanelTromp** [comment]
Done  kinnitamiseks: https://github.com/hariduspilv/haridusportaal/wiki/Done-list-(arendustulemi-valmisoleku-n%C3%B5uded)

Testplaan kinnitamiseks:

**Comment by MirellKr2** [comment]
Raamlepingu 6.6 nõude osas on kliendiga kokku lepitud järgmist:
Testimist viiakse läbi analüüsi piletite alusel. Erandjuhtudel koostatakse keerulisemate protsesside testimiseks testilood.

**Comment by MirellKr2** [comment]
Link testiplaani lehele: https://github.com/hariduspilv/haridusportaal/wiki/Testiplaan
