### ISSUE TITLE
Artikli sisulehe (alamosadega) toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#128]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada „TypeOneArticlePage“ mallil sisulehte.

**Eeltingimused ja käivitamine** (ei testita, kui õiguste süsteem pole realiseeritud):

- Kasutajal on sisuhalduri õigused.
- Kasutaja on sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
**Sisuhaldur saab**:

- toimetada lehe sisu - WYSIWYG redaktori võimalused - kirjutatud issue-s #15
- vaadata lehe eelvaadet ilma seda lehekülge veebi külastajatele avaldamiseta
- siduda lehte menüüpunktiga
- avaldada lehte

Lehe sisu on "TypeOneArticlePage" mall (vt alloleval joonisel sisuobjekt TypeOneArticlePage):
![typeonearticlepage](https://user-images.githubusercontent.com/23524151/39629060-9c60ffc0-4fb3-11e8-8675-a27573cc8187.png)

Sisulehe põhiosa elemendid (TypeOneArticlePage):
- pealkiri (title), kohustuslik
- sissejuhatav tekst, vabatahtlik
- sisu (content), kohustuslik
- foto (picture), vabatahtlik
- alamlehe pealkiri (accordionSubPageTitle), kohustuslik

Sisulehe almosa elemendid (AccordionSubPage):
- alampunkti pealkiri (paragraphTitle), kohustuslik
- alamlehe jrk (paragraphSecuenceNo), kohustuslik
- alamlehe sisu (paragraphContent), kohustuslik
- alamlehe foto (paragraphPicture), vabatahtlik
- alamlehe link (paragraphLink), vabatahtlik

Parema veeru elemendid on realiseeritud piletis: #138 ja peab saama kasutada ka sellel mallil.

Viited:
Front-end pilet - https://github.com/hariduspilv/haridusportaal/issues/19
parema serva vidinate piletid: #138 ja #139

**Comment by TanelTromp** [comment]
viga 1: puudub foto lisamise võimalus akordion alamlehe sektsioonis. Vt:
"alamlehe foto (paragraphPicture), vabatahtlik"
![pilt](https://user-images.githubusercontent.com/37407917/39622305-55ba6c8c-4f9a-11e8-828b-eb35859e0219.png)

Viga 2: Lingi tekst muuta mittekohustuslikuks

![pilt](https://user-images.githubusercontent.com/37407917/39622364-9ba02ac0-4f9a-11e8-8e3d-1755817ff6f8.png)

**Comment by TanelTromp** [comment]
Viga 3: sisu lisamine ei ole hetkel kohustuslik aga peaks olema:

![pilt](https://user-images.githubusercontent.com/37407917/39743604-156cb938-52aa-11e8-96c8-7fd7906c5593.png)

**Comment by ruut12** [comment]
@TanelTromp 
Viga3 parandatud.

**Comment by EgleM-TW** [comment]
Alamlehe lisamine on vabatahtlik! Muudatus kajastub koos teiste täiendustega uues töös #181. Võimalusel palun rakendada juba selles sprindis.

**Comment by TanelTromp** [comment]
Viimane-lõplik versioon tuleb testimisse siis #181 piletiga.

**Comment by Kyllike** [comment]
#128_HTM

Viga 1 (pildi lisamine akordionile): jätkuv viga, pilti ei saa lisada

@TanelTromp: Täpsustus 1 - Menu ja URL Path settingud on kindlasti vajalikud. Menu settingute kaudu saab määrata lehe paiknemise navigatsoonis; URL path settingutest saab vajadusel lisada alternatiivse tee artiklini. 

Viga 2: Seotud artikli lisamisel ei paku autocomplete juba olemasolevat sisuartiklit "Lasteaed". Käsitsi sisestamisel tuleb veateade, mis edasi ei aita:
![image](https://user-images.githubusercontent.com/38042389/40614412-7868f15a-628b-11e8-8ab6-c67c709c4a49.png)
 
Viga 3: Menüüs õpitee alla määratud sisuartikkel Põhiharidus viib avalikus vaates klõpsates hoopis avalehe sündmuste juurde (testitud Google Chrome Versioon 66.0.3359.181) :
![image](https://user-images.githubusercontent.com/38042389/40615104-16773cc4-628e-11e8-8d3e-737d31217b46.png)
Viga kaob, kui kaotada menüüpunkti nimest täpitäht "õ":
![image](https://user-images.githubusercontent.com/38042389/40615332-005dc100-628f-11e8-8f04-f6eb01574bb1.png)

Viga 4: Akordionile lisatud URLe ei kuvata avalikus vaates (testitud Google Chrome Versioon 66.0.3359.181): 
Adminvaade:
![image](https://user-images.githubusercontent.com/38042389/40615494-a9ee177e-628f-11e8-935c-cf59cfea03a0.png)

Avalik vaade:
![image](https://user-images.githubusercontent.com/38042389/40615608-233c19be-6290-11e8-9662-90bf3870b7e3.png)


Viga 5: Akordioni pealkiri kuvatakse vales kohas:
![image](https://user-images.githubusercontent.com/38042389/40615564-f27edeb0-628f-11e8-9a18-339d8a41e912.png)

Tähelepanek: Kui URLi lisamisel on vahetusse läinud teksti ja URLi väli, siis artikli salvestamine ei õnnestu, ekraani ülaserva (admini peamenüü juurde) ilmub hetkeline veateade:
![image](https://user-images.githubusercontent.com/38042389/40614722-ac9046f8-628c-11e8-9d62-d78a3ed5d55f.png)
Veateade peaks tulema konkreetse välja juurde või olema katkine väli kuidagi indikeeritud. 

@heldiraudsepp

**Comment by ruut12** [comment]
**Viga2**: Autocomplete otsib pealkirja järgi mitte lingi hetkel on Teil ette lisatud / sellepärast ei leita soovitud lehte üles.
**Viga3**: Minul antut viga ei esine.
**Viga4**: Front-endi tegemine @doomler 
**Viga5**: Kujundust pole veel seotud.


**Tähelepanek**: Viga kuvatakse õiges kohas (ülemine nool on suunatud täpselt kasti), Te olete paiknete lehel selliselt, et veateade jääb täpselt tööriistarea taha. Kui kerite selle kasti juurde kus viga on siis näete.

@Kyllike

**Comment by TanelTromp** [comment]
@Kyllike palun Viga 3 veel proovida testida.

**Comment by Kyllike** [comment]
@Tanel ei õnnestu endal ka enam Viga 3 korrata, sellega korras.

**Comment by tanel** [comment]
@TanelTromp eelnev comment oli vist sulle mõeldud :)

**Comment by TanelTromp** [comment]
👍 :)

**Comment by MirellKr2** [comment]
Sisuhaldur saab artiklit muuta, kuid ei saa luua. Täpsemad kasutajaõigused on kirjeldatud siin: https://github.com/hariduspilv/haridusportaal/wiki/Kasutus%C3%B5igused
