### ISSUE TITLE
Siltide (tag) toimetamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#13]
Sisu toimetaja sisestab (kalssifikaatorite haldamisena) sildi (Tag) kohta:
nimi (name), kohustuslik
![taxonomy](https://user-images.githubusercontent.com/23524151/37965361-7ef0ee0e-31cd-11e8-850a-58eeb5585ce1.png)

Silti saab:

1. lisada (create)
2. muuta (edit)
3. kustutada (delete)

Lisainfoks: siltide kasutamine (ei testita selle töö raames)

1. Kui kasutaja salvestab uue sildi, muutub see silt valitavaks (nendel lehtedel kus on siltide valimine lisatud).
2. Kui kasutaja muudab sildi nime, muutub see igal pool, kus on seda silti kasutatud.
3. Kui kasutaja kustutab sildi, kustub see igal pool, kus on seda silti kasutatud.

**Comment by TanelTromp** [comment]
Ei ole hetkel kohustuslik, lubab ürituse salvestada ilma ühtegi tagi lisamata:

![pilt](https://user-images.githubusercontent.com/37407917/38853232-432354c6-4225-11e8-9b52-cdecc6b90e19.png)
@lsoonvald
