### ISSUE TITLE
Õppeasutuste filtreerimine kaardil

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#130]
**Üldkirjeldus:**
Filtreerida nimistuna või kaardil kuvatavaid õppeasutusi, et leida sobivat õppeasutust.

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud õppeasutuste kaart (https://github.com/hariduspilv/haridusportaal/issues/31) või nimistu  (https://github.com/hariduspilv/haridusportaal/issues/268).

**Vastuvõtutingimused:** 
* Õppeasutusi saab filtreerida järgmiste tunnuste alusel:
-- nimi - süsteem otsib õppeasutused, mille nimetuses (name) sisaldub sisestatud string, kusjuures võrdlus ei ole tõstutundlik (suur- ja väiketähed loetakse samaväärseks)
-- õppeasutuse tüüp  - kasutaja valib õppeasutuste tüüpide (EducationalInstitutionType) taksonoomiast; valida saab ülemise taseme tüüpe; süsteem otsib õppeasutused, mille tüüpide (type) hulgast vähemalt üks võrdub valitud õppeasutuse tüübiga
-- õppeasutuse alamtüüp  - kasutaja valib õppeasutuste tüüpide (EducationalInstitutionType) taksonoomiast; eelnevalt peab olema valitud õppeasutuse tüüp; valikus on eelnevalt valitud tüübi alla kuuluvad alamtüübid; süsteem otsib õppeasutused, mille tüüpide (type) hulgast vähemalt üks võrdub valitud õppeasutuse tüübiga
-- õppekeel - kasutaja valib õppekeelte (TeachingLanguage) taksonoomiast; süsteem otsib õppeasutused, mille õppekeelte (teachingLanguage) hulgast vähemalt üks võrdub valitud õppekeelega 
-- asukoht - kasutaja valib asukoha maakondade (County), kohalike omavalitsuste (LocalGovernment) ja  asustusüksuste (SettlementUnit) taksonoomiast autocomplete valikuna (autocomplete hakkab näitama valikut kui on sisestatud vähemalt kaks sümbolit, sisestatud stringi otsitakse nimetusest läbivalt mitte ainult algusest); süsteem otsib õppeasutused, mille vähemalt ühe asukoha maakond (Location.County) võrdub valitud maakonnaga, kohalik omavalitus (Location.localGoverment) võrdub valitud kohaliku omavalitusega või asudtusüksus (Location.SettlementUnit) võrdub valitud asustusüksusega.
-- omandivorm - kasutaja valib omandivormide (OwnershipType) taksonoomiast; süsteem otsib õppeasutused, mille omandivorm (ownershipType) võrdub valitud omandivormiga
-- HEV koolid - kasutaja saab täita märkeruutu; süsteem otsib õppeasutused, milles on hariduslike erivajadustega õppimise klass (specialClass)
-- õpilaskodu  - kasutaja saab täita märkeruutu; süsteem otsib õppeasutused, mille kohta tehtud märge õpilaskodu olemasolu kohta (studentHome)

* Kui filtreerimine toimub kaardi vaates, siis süsteem kuvab kaardi järgmiselt:
-- Kui otsingutunnustele vastavad õppeasutuste asukohti on >1, siis leitud õppeasutuste asukohad jäävad kaardivaate minimaalsesse _boundingbox-i_ (peab jääma ka ääris ehk _margins_, näiteks 5% (täpsustada suurus)). 
-- Kui otsingutunnustele vastavad õppeasutuste asukoht on 1, siis leitud õppeasutuse asukoht on tsentreeritud kaardi keskel ja zoom level on 13.
-- Kui otsingutunnustele ei vasta ühtegi õppeasutust, siis süsteem kuvab teate "Otsingu tingimustele vastavaid õppeasutusi ei leitud" ja kaardivaadet ei muuda.

* Filtri ette andmine URL-s
Tingimused täpsustada.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kasutajaliidese eskiis:**
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b057a6d42f5694e26594723
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b06afd8923fdb282158d3b6
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b0573539da86c2e421ad590

**Viited:**
* Õppeasutuste kuvamine kaardil https://github.com/hariduspilv/haridusportaal/issues/31.

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppeasutuste filtreerimine kaardil
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Edge 16.16299, IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Windows tablet Thinkpad
Keskkond: http://htm.twn.ee/

**Viga 1**: drop-down avaneb välja peal, kasutaja ei näe, millise välja kohta ta filtrid lisab.

![image](https://user-images.githubusercontent.com/37401947/43521082-ad41e1d0-959d-11e8-8ebf-ee4e1bd239e2.png)

**Viga 2**: linnuke on lahtrist väljas.

![image](https://user-images.githubusercontent.com/37401947/43521332-7740a78c-959e-11e8-8dd3-0b42178df890.png)

**Viga 3**: kui otsingutunnustele ei vasta ühtegi õppeasutust, siis süsteem kuvab teate "Otsingu tingimustele vastavaid õppeasutusi ei leitud" ja kaardivaadet ei muuda. Hetkel teadet ei kuvata.

![image](https://user-images.githubusercontent.com/37401947/43521399-bb9660c0-959e-11e8-9343-b786df293ad4.png)

**Viga 4**: portaalis on puudu alamtüübi filtri väli. Alljärgnevalt on kujundusfaili pilt.

![image](https://user-images.githubusercontent.com/37401947/43521429-d7e1b504-959e-11e8-8a48-953c53725125.png)

**Viga 5**: asukoha autocomplete ei toimi, otsing tehakse ka tänava nimest, peaks olema asustusüksus – kas küla, alevik, alev, linnaosa, mitte tänav.

![image](https://user-images.githubusercontent.com/37401947/43521481-0de11c58-959f-11e8-90e9-8d8b2ca9d241.png)

**Viga 6**: filter ei sulgu mobiilis korrektselt.

**Viga 7**: IE brauseris ei näita kaardil markerit (filter -> HEV), listivaates kuvatakse tulemust.

![image](https://user-images.githubusercontent.com/37401947/43521574-520cfa78-959f-11e8-871f-56a659c034ee.png)

![image](https://user-images.githubusercontent.com/37401947/43521608-57d1e194-959f-11e8-8e93-6444d186131a.png)

**Viga 8**: Kui otsingutunnustele vastavad õppeasutuste asukoht on 1, siis leitud õppeasutuse asukoht on tsentreeritud kaardi keskel ja zoom level on 13. -> **Asukohta ei kuvata tsentreeritult, zoom level on paigast ära.**

![image](https://user-images.githubusercontent.com/37401947/43521669-91d1de58-959f-11e8-8a50-a86145102546.png)

**Comment by MirellKr2** [comment]
**Viga 9**: mobiilis õppeasutuste kaardi vaates olevale filtri väljale sisestamisel sulgub filter koheselt, st väljale ei saa trükkimist alustadagi kui filtri osa sulgub.

**Comment by MirellKr2** [comment]
Märkus: kasutada filtri välja "Õpilaskodu/Ühiselamu olemas" asemel lihtsalt "Õpilaskodu", nii on seda kasutatud kujunduses ja õppeasutuse detailvaatel.

@skeefee

**Comment by skeefee** [comment]
Viga 1: See on material designi poolt ette nähtud
Viga 2: 100% kujunduse järgi tehtud
Viga 3: korras
Viga 4: Korras
Voga 5: peabki nii olema
Viga 6: Korras
Vigs 7: Tundub nagu mingi anomaalia. Testi uuesti palun
Viga 8: Korras
Viga 9 : Korras
Märkus: tehtud

@MirellKr2

**Comment by MirellKr2** [comment]
Viga 1: pole viga, kuna lähtub Material-ist. 

Viga 2: pole viga vaid on nii kujunduse pool ette nähtud, vajab ühtlustamist üle portaali (avalehel käitub check-box teisti).

Viga 3: teadet kuvatakse, kuid teate sisu peaks olema vastavalt nõuetes toodule (Otsingu tingimustele vastavaid õppeasutusi ei leitud). Vaadata üle kaart.

Viga 4: alamtüübi filter on olemas. Tuleb üle vaadata, kas otsing tehakse ainult alamtüüpide hulgast.

Viga 5: OK.

Viga 8: korras.

Viga 6 ja 9: Androidil viga eksisteerib, Safaris OK, kuid kui väljale on sisestatud, ei saa otsingunupule vajutada. 

@madispold

**Comment by MirellKr2** [comment]
Viga 3: parandatud ja korras.

Viga 4: korras, st otsitakse ainult neid õppeasutusi, millel on valitud tüüp ja alamtüüp küljes.

Viga 6 ja 9: mobiili vaadete puhul vajab eraldi piletite filtri jaoks. Selle pileti raames jäi kõrvale.
