### ISSUE TITLE
Õppeasutuste taksonoomiate lisamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#131]
Õppeasutuste andmete automaatseks uuendamiseks (https://github.com/hariduspilv/haridusportaal/issues/105) ja käsitsi haldamiseks (https://github.com/hariduspilv/haridusportaal/issues/104) peavad olemas olema järgmised taksonoomiad:

* Maakonnad (County) - lisaks nimetusele on igal maakonnal EHAK kood
* Kohalikud omavalitused (LocalGoverment) - lisaks nimetusele on igal kohalikul omavalitsusel EHAK kood ja seos maakonnaga maakonna EHAK koodi kaudu
* Asutussüksused (SettlementUnit) - lisaks nimetusele on igal asustusüksusel EHAK kood, seos maakonnaga maakonna EHAK koodi kaudu ja kohaliku omavalitusega vastava EHAK koodi kaudu
***
* Õppeasutuse tüübid (EducationalInstitutionType) - kahetasemeline taksonoomia (tüüp ja alamtüüp).
* EHISe õppeasutuste tüübid - taksonoomia kirjet peab saama siduda õppeasutuse tüübiga ja alamtüübiga (EducationalInstitutionType)
* EHISe õppeasutuste alamtüübid -  taksonoomia kirjet peab saama siduda õppeasutuse tüübiga ja alamtüübiga (EducationalInstitutionType)
* EHISe õppeasutuste tegutsemisvormid -  taksonoomia kirjet peab saama siduda õppeasutuse tüübiga ja alamtüübiga (EducationalInstitutionType)

**Realisatsioon:**
* Drupal _back-end_-s on üks kahetasemeline taksonoomia. Nimetame esimest taset tüübiks (type) ja teist alamtüübiks (subtype). Kasutajaliidesel on nende valikuks eraldi _dropdown_'d. 
*  Õppeasutus võib olla taksonoomiasse liigitatud nii tüübi kui ka alamtüübi tasemel. Tüüp on üldjaotus (nt "Lasteaed" alla kuuluvad kõik lasteaiad), mida spetsialiseerib alamtüüp (nt "Lastesõim" alla kuuluvad lasteaiad, milles on lastesõim). 
* Õppeasutus võib olla seotud mitme liigitusega. Näiteks võib samas õppeasutuses olla nii lasteaed kui põhikool.
* Drupal _back-end_-s oleva taksonoomia seosed EHIS-e liigitustega on taksonoomia väljas "EHIS output". Ühel taksonoomia kirjel võib olla mitu "EHIS output" väärtust.
* Drupal _back-end_ tagab, et kui õppeasutus seotakse alamtüübiga, siis seotukse ka vastava tüübiga. 

***
* Omandivormid (OwnershipType)
* EHISe omandivormid -  taksonoomia kirjet peab saama siduda portaalis kasutatava omandivormiga (OwnershipType)
***
* Õppekeeled (TeachingLanguage)
* EHISe õppekeeled - taksonoomia kirjet peab saama siduda portaalis kasutatava õppekeelega (TeachingLanguage)

**Comment by ruut12** [comment]
Eralasteaed Aarete saar:
mitu telefoninumbrit (mida teha?)
