### ISSUE TITLE
GET Isikukaart REST teenus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#135]
GET Isikukaart teenust (https://github.com/hariduspilv/haridusportaal/issues/117) muuta nii, et ei see toimu läbi Kafka, vaid Drupal back-end pöördub otse lõime REST teenuse poole. Logikirjete postitamine jääb toimuma Kafka kaudu.

**Comment by TanelTromp** [comment]
RESTI peal on tehtud päring ja töötab.
