### ISSUE TITLE
Artikli sisulehe parema ääreriba toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#138]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab toimetada „SimpleArticlePage“ mallil sisulehe parema veeru vidinaid.

**Eeltingimused ja käivitamine** (ei testita, kui õiguste süsteem pole realiseeritud):
- Kasutaja on sisuhaldurina sisse loginud
- Kasutajal on sisuhalduri lk muutmise õigused.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
lisada „SimpleArticlePage“ mallil sisulehe parema veeru andmed.

**Parema veeru elemendid:**
![simplearticlepage](https://user-images.githubusercontent.com/23524151/39628942-3f628622-4fb3-11e8-8b6c-16b96d947919.png)

**Sisulehe parema veeru elemendid** - vabatahtlik täita:
**Lisainfo (Note), vabatekst:**
- pealkiri (title25)
- sisu (content150)

**Kontakt (Contact):**
- nimi (person25)
- organisatsioon (organization25)
- telefon (phone)
- e-post (e-mail)

**Leia kiiresti (Link):**
- jrk nr (SecuenceNo)
- Lingi pealkiri (LinkTitle)
- Lingi URL (WebPageAddress)

**Sarnased teemad (RelatedPages):**
- jrk nr (SecuenceNo)
- sisulehe pealkiri (RelatedPageTitle), sh sisulehe link (RelatedPageLink)

Lisainfoks front-end kohta:
- Kui lehe paremal servas on mõni blokk täitamata, siis kuvamisel ei tohi jääda nö auku sisse.
- Kui lehe parema veeru elemente pole lisatud (0), ei jää parem veerg tühjaks, sisuosa võtab selle enda alla.

Viited:
Front-end pilet - #139 

Sisulehe tüüp „SimpleArticlePage“ realiseeritud piletis: #18

**Comment by EgleM-TW** [comment]
03.05 daily otsus: selle töö raames tähemärkide arvu ei kontrollita (testita). Lahendatakse eraldi tööna.

**Comment by EgleM-TW** [comment]
04.05 disaini koosoleku otsused:
1. Lisainfo (Note) ikooni määramine (importance: high, normal) JÄÄB ÄRA!
2. Sarnased teemad (RelatedPages): Pilti ei kuva #139

**Comment by ruut12** [comment]
@TanelTromp 
Täiendused testis

**Comment by TanelTromp** [comment]
Viimane-lõplik versioon tuleb testimisse siis #181 piletiga.
