### ISSUE TITLE
Artikli sisulehe parema ääreriba kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#139]
**Eesmärk, üldtingimused:**
Portaali külastaja saab menüü või mõne muu sisulehe lingi kaudu navigeerida „SimpleArticlePage“ mallil sisulehele ja tutvuda selle sisuga.

**Eeltingimused ja käivitamine:**
- realiseeritud on pilet #138
- kasutaja navigeerib menüüst „SimpleArticlePage" mallil sisulehele

**Vastuvõtutingimused:** 

1. Kasutajale kuvatakse lehekülje sisu (realiseeritud piletis #82)
2. Kasutaja näeb lehe paremal serval (järjest üksteise all):

- Lisainfo (Note) 
- Kontakt (Contact)
- Leia kiiresti (Link)
- Sarnased teemad (RelatedPages)

Reeglid kuvamisel:

- Kui mõni teema või mittekohustuslik väli on sisetsamata siis ei kuvata nö auku, vaid sisestatud teemad kuvatakse järjest.

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Parema serva vidinate kasutajaliidese prototüüp piletis: #19

Viited:
back-end töö #138

**Comment by EgleM-TW** [comment]
@birgitpulk, palun selgita enne arendustööd, milliseid ikoone kasutada. Vt ka siia: #138

**Comment by EgleM-TW** [comment]
04.05 disainikoosoleku otsused ja muudatused:
ikooni valik jäi ära
sarnased sisulehed: pilti ei kuva

**Comment by MirellKr2** [comment]
@skeefee
Vea raport #12_1
•	Tegevuse üldine kirjeldus: uudiste nimekirja vaate testimine
•	Testimise tegevused: funktsionaalsete nõuete testimine, mittefunktsionaalsete nõuete testimine.
•	Brauserid: Chrome 65
•	Op. süsteem: Windows 10, PC 64bit
•	Resolutsioonid: UHD + laptop
•	Seadmed: iPhone 6 + Safari, Samsung Galaxy A5 + Chrome, Windows tablet Thinkpad + Chrome
•	Keskkond: http://htm.twn.ee/

Funktsionaalsus töötab nõuete kohaselt.

**Comment by EgleM-TW** [comment]
11.05 sprindi lõpetamise koosolekul disaini-otsus: Kui parem veerg pole täidetud, siis sisuosa ei muutu (ei pea katma tervet lk). Muudatus uues piletis #191
