### ISSUE TITLE
Siltide alusel teavituste e-mailile väljastamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#14]
**Eesmärk, üldkirjeldus:**
Kui sisuhaldur avaldab uudise või sündmuse, millele on lisatud tellimusega silt, saadab portaal (all määratud reeglite alusel) uudise/ sündmuse kohta teavituse tellimusega seotud e-posti aadressile.

**Eeltingimused ja käivitamine:**
Kasutaja on tellinud teavituse (pilet nr #106 #157 ja #160 on realiseeritud).

**Saatmise reeglid:**

1. Saatmine käivitub 1 kord ööpäevas kell 12:00. _seadistatav._
2. Teavituse saatmise aluseks on viimase 24 tunni jooksul avaldatud (sh uuendatud) uudised ja sündmused, millele on lisatud silt (üks kuni mitu).
3. Kui uudisele/ sündmusele on lisatud mitu silti, mille kohta on tellimus vormistatud samale e-posti aadressile, saadetakse tellijale üks teavitus ning erinevad uudised/ sündmused lisatakse ühe e-kirja sisusse.
4. Süsteem ei edasta teavitust sündmuse kohta, mille alguskuupäev on minevikus.

**E-kirja päis:** _Seadistatav_
From: ?
To: tellimuse e-posti aadress
Subject: _Haridusteemalised uudised_

**E-kirja sisu:**

- [ ] Kui e-kiri sisaldab nii uudiseid kui ka sündmusi, siis need jagatakse eraldi blokkidesse

- [ ] Uudise pealkiri (title), mis on URL ja avab kasutajale selle uudise detailvaate

- [ ] Sündmuse pealkiri (title), mis on URL ja avab kasutajale selle sündmuse detailvaate

**E-kirja jalus:**
_Te saite selle e-kirja, kuna tellisite uudiskirja haridusteemadel. Kui soovite e-kirjast loobuda, siis vajutage seda linki [Siia unsubscribe link]._

Vastuvõtutingimused:
Kasutajale laekub e-kiri eelnevalt kirjeldatud reeglite alusel.

**Viited:**
Siltide alusel teavituste tellimine #106 (Front)
Tellimuse kinnitamiseks e-kirja saatmine ja kaasa räsi #157 (Back)
Tellimuse kinnituse kuvamine #160  (Front)

Siltide alusel teavituste tellimuste haldamine #107
Siltide alusel teavituse tellimuse lõpetamine (unsubscribe) #108
Siltide alusel teavituse tellimuse muutmine #132

**Comment by TanelTromp** [comment]
1. Saatmine käivitub 1 kord ööpäevas kell 12:00. _seadistatav._
2. Teavituse saatmise aluseks on viimase 24 tunni jooksul avaldatud (sh uuendatud) uudised ja sündmused, millele on lisatud silt (üks kuni mitu).
3. Kui uudisele/ sündmusele on lisatud mitu silti, mille kohta on tellimus vormistatud samale e-posti aadressile, saadetakse tellijale üks teavitus ning erinevad uudised/ sündmused lisatakse ühe e-kirja sisusse.
4. Süsteem ei edasta teavitust sündmuse kohta, mille alguskuupäev on minevikus.

**E-kirja päis:** _Seadistatav_
From: ?
To: tellimuse e-posti aadress
Subject: _Haridusteemalised uudised_

**E-kirja sisu:**

- [ ] Kui e-kiri sisaldab nii uudiseid kui ka sündmusi, siis need jagatakse eraldi blokkidesse

- [ ] Uudise pealkiri (title), mis on URL ja avab kasutajale selle uudise detailvaate

- [ ] Sündmuse pealkiri (title), mis on URL ja avab kasutajale selle sündmuse detailvaate

**E-kirja jalus:**
_Te saite selle e-kirja, kuna tellisite uudiskirja haridusteemadel. Kui soovite e-kirjast loobuda, siis vajutage seda linki [Siia unsubscribe link]._

**Comment by lsoonvald** [comment]
Viga 1: Fixed. @TanelTromp
