### ISSUE TITLE
Õppeasutuse andmete uuendamine - õppeasutuste tüübid

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#140]
**Üldkirjeldus:**
Õppeasutuste andmete automatiseeritud uuendamise käigus teisendatakse EHIS-st saadavad taksonoomiad Haridusportaalis kasutatavaks taksonoomiaks.

**Eeltingimused ja käivitamine:**
* On käivitatud õppeasutuse andmete automatiseeritud uuendamise protsess (https://github.com/hariduspilv/haridusportaal/issues/105). Käesolevaga kirjeldatav on õppeasutuse andmete uuendamise protsessi osa.
* EHIS-st on saadud õppeasutuse tüüp (tyyp), alamtüüp (alamtyyp), tegutsemisvormid (tegutsemisvormid.tegutsemisvorm), omandivorm (omandivorm), õppekeeled (oppeKeeled.oppeKeel).

**Tegevused:**
Süsteem määrab õppeasutuse kohta portaalis esitatavad:
1. õppeasutuse tüübid
2. omandivormi
3. õppekeeled

**Tegevus 1: õppeasutuse tüüpide salvestamine**

* EHIS-st saadud andmeelemendi tyyp väärtuse alusel otsida taksonoomia EducationalInstitutionType kirje.
* EHIS-st saadud andmeelemendi alamtyyp väärtuse alusel otsida taksonoomia taksonoomia EducationalInstitutionType kirje.
* EHIS-st saadud andmeelementide tegutsemisvormid.tegutsemisvorm väärtuste alusel otsida taksonoomia EducationalInstitutionType kirjed.

* Saadud taksonoomia kirjetest jäetakse kõrvale korduvad väärtuseks (kasutatakse unikaalsed väärtusi) ja  saadud väärtused omistatakse õppeasutuse andmevälja _type_ väärtus(t)eks.

* Kui EHIS-st saadud andmeelemendi väärtusele vastavat taksonoomia kirjet ei leidu, siis seda ignoreeritakse (selgitus: EHIS-st saadav väärtus ei kuulu portaalis esitamisele).

**Tegevus 2: õppeasutuse omandivormi salvestamine**

* EHIS-st saadud andmeelemendi omandivorm väärtuse alusel otsida taksonoomia OwnershipType  kirje ja omistada see õppeasutuse andmevälja _ownershipType  _ väärtus(t)eks.

* Kui EHIS-st saadud andmeelemendi väärtusele vastavat taksonoomia kirjet ei leidu, siis seda ignoreeritakse (selgitus: EHIS-st saadav väärtus ei kuulu portaalis esitamisele).

**Tegevus 3: õppeasutuse õppekeelte salvestamine**

* EHIS-st saadud andmeelementide oppeKeeled.oppeKeel väärtuste alusel otsida taksonoomia TeachingLanguage kirjed.

* Saadud taksonoomia kirjetest jäetakse kõrvale korduvad väärtuseks (kasutatakse unikaalsed väärtusi) ja  saadud väärtused omistatakse õppeasutuse andmevälja _teachingLanguage_ väärtus(t)eks.

* Kui EHIS-st saadud andmeelemendi väärtusele vastavat taksonoomia kirjet ei leidu, siis seda ignoreeritakse (selgitus: EHIS-st saadav väärtus ei kuulu portaalis esitamisele).

**Comment by TanelTromp** [comment]
Testitud tüüpnäidete peal:
-  "Loksa Gümnaasium" 
- "Tallinna Nõmme Gümnaasium"
-   "Väimela Lasteaed"
