### ISSUE TITLE
Õppeasutuse infoakna kuvamine kaardil

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#142]
**Üldkirjeldus:**
Kuvada kaardil esitatud õppeasutuse kohta infoaken.

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud õppeasutuste kaart (https://github.com/hariduspilv/haridusportaal/issues/31)

**Vastuvõtutingimused:**
* Kasutaja klikib kaardivaatel õppeasutuse asukoha markeril, siis süsteem kuvab õppeasutuse kohta järgmised andmed: 
-- Nimetus, 
-- Juriidiline aadress: Maakond, Vald või linn, Asustusüksus, Aadress  
-- Õppeasutuse tüübid ja alamtüübid, 
-- Kontaktandmed: Telefon, E-Post, Veebileht.

* Kui mingil andmeelemendi väärtus puudub, siis seda andmeelementi ei kuvata (muud andmeelemendid nihkuvad üles, ei jää tühja kohta).

* Õppeasutuse alamtüübid kuvatakse vastava tüübi järel sulgudes. Kui õppeasutusel on mitu alamtüüpi, mis kuuluvad sama tüübi alla, siis kuvatakse tüüp üks kord ja selle alla jäävad alamtüübid üksteisel järel komadega eraldatult, näiteks "lasteaed (lastesõim, erivajadustega lastele, 7 aastastele lastele)".

**Kasutajaliides:**
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b057a6d42f5694e26594723
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b06afd8923fdb282158d3b6

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by skeefee** [comment]
@MirellKr2  palun testida

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppeasutuse infoakna kuvamine kaardil
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Edge 16.16299, IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Keskkond: http://htm.twn.ee/

**Viga 1**: infoaknas olevate andmeväljade järjekord erineb kujunduses esitatud andmeväljade järjekorrast (veebilehe andmeväli peaks olema kuvatud viimasena). Samuti peab e-mail ja veebileht olema kuvatud paksus kirjas.

![image](https://user-images.githubusercontent.com/37401947/43258681-40c1f650-90dc-11e8-9893-d35cd3f3e1eb.png)

**Viga 2**: infoaken kuvatakse poolikult.

![image](https://user-images.githubusercontent.com/37401947/43258702-53650ca2-90dc-11e8-9578-3c954f00bfe5.png)

**Viga 3**: kaardil leidus markereid, millele klikkides ei avanenud infoakent.

![image](https://user-images.githubusercontent.com/37401947/43258730-6e2a5d80-90dc-11e8-94f9-3f40b92ce032.png)

**Viga 4**: tüübid peaksid olema eraldatud komaga, alamtüüp peab olema esitatud sulgudes tüübi järel. Hetkel BE poolne probleem (päring ümber tegemisel).

![image](https://user-images.githubusercontent.com/37401947/43258861-fc6ae998-90dc-11e8-8b74-02cb3c5e449d.png)

**Viga 5**: disainiviga IE brauseris (otsinguvälja alamjoon)

![image](https://user-images.githubusercontent.com/37401947/43258891-1b5096a0-90dd-11e8-893f-41b822f25072.png)

**Viga 6**: IE brauseris ei kuvata kõiki markereid (ei näe koolide markereid).

**Comment by skeefee** [comment]
@MirellKr2

**Comment by MirellKr2** [comment]
Viga 1: korras
Viga 3: probleem koordinaatidega, vajab järgmistes sprintides täiendavat uurimist
Viga 4: nõuete järgi peaks alamtüüp olema kuvatud tüübi järel sulgudes (vt õppeasutuse detailvaadet).

![image](https://user-images.githubusercontent.com/37401947/44205941-c04cef80-a160-11e8-99b3-b76728defdfc.png)

Viga 6: otsides nt Pärnu Koidula Gümnaasium, siis kaardil markerit ei kuva, ehk probleem IE-s endiselt olemas.

@skeefee

**Comment by skeefee** [comment]
Viga 3: korras
Viga 4: BE lahendada see info tuleb 
Viga 6: BE vaatab viga

**Comment by MirellKr2** [comment]
Viga 6: ei saanud üle testida, kuna koolide otsing/vaade ei toimi.

Viga 7: Mitme aadressi puhul kuvame ainult jur. aadressi.

![image](https://user-images.githubusercontent.com/37401947/44254747-699cef80-a20c-11e8-9827-462f33d55a80.png)

**Comment by skeefee** [comment]
Viga 6: Korras
Viga 7: Korras

**Comment by MirellKr2** [comment]
Vead parandatud. 

Aadressi ja õppeasutuse tüübi kuvamine vajab veel parandusi (lisapiletid järgmisesse sprintidesse).

Aadresside kuvamine vajab BE-le lisapiletit, kuna hetkel ei saa FE päringut kätte kujul, mis võimaldaks ainult jur.aadressi välja kuvada.

Koole ei saa IE-s otsida, kui kooli nimetuses on täpitähed.

@skeefee @ruut12 @lsoonvald
