### ISSUE TITLE
Menüü mitmekeelsuse seadistamine Drupalis

### ISSUE THREAD

**Issue by ruut12** [hariduspilv/haridusportaal#143]
*GraphQL'i täiendused mitmekeelsuse toetamiseks (menüü päring)

vastuvõtutingimused:
* Menüü päringus tagastatakse ainult vastava keele menüü lingid.

**Comment by TanelTromp** [comment]
Kõiki sisutüüpe on võimalik duplikeerida teise keelde.

Viga 1: artikkel vaates ei too hetkel lisasisu e.k emaartiklist ing. k üle:

![pilt](https://user-images.githubusercontent.com/37407917/39745728-ccd3246c-52b0-11e8-90ed-94396ae3e755.png)
