### ISSUE TITLE
Õppekavade andmete toimetamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#146]
Sisu haldaja saab sisestada õppekavade kohta järgmisel joonisel esitatud andmeobjektide andmed:

![studyprogramme](https://user-images.githubusercontent.com/24670133/39120850-6f147362-46f8-11e8-9192-f09ec9392dee.png)

***
id - Süsteem omistab igale õppekavale omistama unikaalse identifikaatori. Sündmusi toimetav kasutaja näeb seda.
***
* Õppeasutuse kood EHIS - EHIS_id 
* Nimetus - name; kohustuslik
* Õppeasutus - educationalInstitution; kohustuslik; kasutaja näeb õppeasutuse nime
* Õppekava tüüp - type;  valik taksonoomiast; kohustuslik
* Õppekava tase - level;  valik taksonoomiast
* Omistatav kraad või diplom - degreeOrDiplomaAwarded;  valik taksonoomiast
* Spetsialiseerumine - specialization
* Õppevaldkond- ISCEDFboardField; valik taksonoomiast (ISCED taksonoomia kõige üldisem tase)
* Õppesuund - ISCEDFnarrowField; valik taksonoomiast (ISCED taksonoomia keskmine tase; valida saab eelnevalt valitud õppevaldkonna alla kuuluvaid õppesuunasid)
* Õppekavarühm - ISCEDFdetailedField; valik taksonoomiast (ISCED taksonoomia kõige detailsem tase; valida saab eelnevalt valitud õppesuuna alla kuuluvaid õppekavarühmasid)
* Lühikirjeldus - shortDescription
* Õppekava kirjeldava veebilehe aadress - webPageAddress
* Kutsestandardi identifikaator - qualificationStandardId; saab sisestada mitu väärtust
* Õppekeel -  teachingLanguage; valik taksonoomiast; saab valida mitu väärtust
* Õppekava maht - amount 
* Praktika maht - practicalTrainingAmount
Kuvada selgitus Õppekava mahu ja Praktika mahu ühiku kohta:
-- Kõrghariduse õppekava korral 'EAP' 
-- Kutsehariduse õppekava korral 'EKAP' 
* Nominaalkestus (aastad) - durationYears
* Nominaalkestus (kuud) - durationMonths
* Vastuvõtu olek - admissionStatus
* Akrediteerimise otsus - accreditationStatus
* Akrediteerimise otsuse kehtivuse lõpp - accreditationValidUntil
* EHIS-st andmete automaatne uuendamine (jah/ei) - updateFromEHIS; kohustuslik
* EHIS-st automaatselt lisamise aeg - createdFromEHIS - mittemuudetav
* Avaldamise staatus - published; kohustuslik

Täiendavad tingimused:
* EHIS_id väärtus peab olema unikaalne.
* Taksonoomiatest saab valida olemasolevaid väärtusi. Õppekava sisestamise käigus ei saa taksonoomiat muuta, sh ei saa taksonoomiasse uusi väärtusi lisada.

Märkused:
* Kasutaja võib muuta kõiki andmeid. Juhul, kui on olemas EHISid ja EHIS-st andmete automaatne uuendamine on "jah", siis muudatused kirjutatakse automaatse uuendamisega üle. Seega, kui kasutaja tahab, et muudatusi üle ei kirjutataks, peab ta valima EHIS-st andmete automaatse uuendamise väärtuseks "ei".
Lisanduvad:
* Lisandu ESCO ametite (occupation) alusel liigitamine

**Viited:**
* Taksonoomiad https://github.com/hariduspilv/haridusportaal/issues/144

**Comment by TanelTromp** [comment]
id - Süsteem omistab igale õppekavale omistama unikaalse identifikaatori. Sündmusi toimetav kasutaja näeb seda.

    Õppeasutuse kood EHIS - EHIS_id
    Nimetus - name; kohustuslik
    Õppeasutus - educationalInstitution; kohustuslik; kasutaja näeb õppeasutuse nime
    Õppekava tüüp - type; valik taksonoomiast; kohustuslik
    Õppekava tase - level; valik taksonoomiast
    Omistatav kraad või diplom - degreeOrDiplomaAwarded; valik taksonoomiast
    Spetsialiseerumine - specialization
    Õppevaldkond- ISCEDFboardField; valik taksonoomiast (ISCED taksonoomia kõige üldisem tase)
    Õppesuund - ISCEDFnarrowField; valik taksonoomiast (ISCED taksonoomia keskmine tase; valida saab eelnevalt valitud õppevaldkonna alla kuuluvaid õppesuunasid)
    Õppekavarühm - ISCEDFdetailedField; valik taksonoomiast (ISCED taksonoomia kõige detailsem tase; valida saab eelnevalt valitud õppesuuna alla kuuluvaid õppekavarühmasid)
    Lühikirjeldus - shortDescription
    Õppekava kirjeldava veebilehe aadress - webPageAddress
    Kutsestandardi identifikaator - qualificationStandardId; saab sisestada mitu väärtust
    Õppekeel - teachingLanguage; valik taksonoomiast; saab valida mitu väärtust
    Õppekava maht - amount
    Praktika maht - practicalTrainingAmount
    Õppekava mahu ja praktika mahu ühik:
    -- Kõrghariduse õppekava korral 'EAP'
    -- Kutsehariduse õppekava korral 'EKAP'
    Nominaalkestus (aastad) - durationYears
    Nominaalkestus (kuud) - durationMonths
    Vastuvõtu olek - admissionStatus
    Akrediteerimise otsus - accreditationStatus
    Akrediteerimise otsuse kehtivuse lõpp - accreditationValidUntil
    EHIS-st andmete automaatne uuendamine (jah/ei) - updateFromEHIS; kohustuslik
    EHIS-st automaatselt lisamise aeg - createdFromEHIS - mittemuudetav
    Avaldamise staatus - published; kohustuslik

Täiendavad tingimused:

    EHIS_id väärtus peab olema unikaalne.
    Taksonoomiatest saab valida olemasolevaid väärtusi. Õppekava sisestamise käigus ei saa taksonoomiat muuta, sh ei saa taksonoomiasse uusi väärtusi lisada.

Märkused:

    Kasutaja võib muuta kõiki andmeid. Juhul, kui on olemas EHISid ja EHIS-st andmete automaatne uuendamine on "jah", siis muudatused kirjutatakse automaatse uuendamisega üle. Seega, kui kasutaja tahab, et muudatusi üle ei kirjutataks, peab ta valima EHIS-st andmete automaatse uuendamise väärtuseks "ei".
    Lisanduvad:
    Lisandu ESCO ametite (occupation) alusel liigitamine

**Comment by TanelTromp** [comment]
id - Süsteem omistab igale õppekavale omistama unikaalse identifikaatori. Sündmusi toimetav kasutaja näeb seda.
***
* Õppeasutuse kood EHIS - EHIS_id 
* Nimetus - name; kohustuslik
* Õppeasutus - educationalInstitution; kohustuslik; kasutaja näeb õppeasutuse nime
* Õppekava tüüp - type;  valik taksonoomiast; kohustuslik
* Õppekava tase - level;  valik taksonoomiast
* Omistatav kraad või diplom - degreeOrDiplomaAwarded;  valik taksonoomiast
* Spetsialiseerumine - specialization
* Õppevaldkond- ISCEDFboardField; valik taksonoomiast (ISCED taksonoomia kõige üldisem tase)
* Õppesuund - ISCEDFnarrowField; valik taksonoomiast (ISCED taksonoomia keskmine tase; valida saab eelnevalt valitud õppevaldkonna alla kuuluvaid õppesuunasid)
* Õppekavarühm - ISCEDFdetailedField; valik taksonoomiast (ISCED taksonoomia kõige detailsem tase; valida saab eelnevalt valitud õppesuuna alla kuuluvaid õppekavarühmasid)
* Lühikirjeldus - shortDescription
* Õppekava kirjeldava veebilehe aadress - webPageAddress
* Kutsestandardi identifikaator - qualificationStandardId; saab sisestada mitu väärtust
* Õppekeel -  teachingLanguage; valik taksonoomiast; saab valida mitu väärtust
* Õppekava maht - amount 
* Praktika maht - practicalTrainingAmount
Õppekava mahu ja praktika mahu ühik:
-- Kõrghariduse õppekava korral 'EAP' 
-- Kutsehariduse õppekava korral 'EKAP' 
* Nominaalkestus (aastad) - durationYears
* Nominaalkestus (kuud) - durationMonths
* Vastuvõtu olek - admissionStatus
* Akrediteerimise otsus - accreditationStatus
* Akrediteerimise otsuse kehtivuse lõpp - accreditationValidUntil
* EHIS-st andmete automaatne uuendamine (jah/ei) - updateFromEHIS; kohustuslik
* EHIS-st automaatselt lisamise aeg - createdFromEHIS - mittemuudetav
* Avaldamise staatus - published; kohustuslik

Täiendavad tingimused:
* EHIS_id väärtus peab olema unikaalne.
* Taksonoomiatest saab valida olemasolevaid väärtusi. Õppekava sisestamise käigus ei saa taksonoomiat muuta, sh ei saa taksonoomiasse uusi väärtusi lisada.

Märkused:
* Kasutaja võib muuta kõiki andmeid. Juhul, kui on olemas EHISid ja EHIS-st andmete automaatne uuendamine on "jah", siis muudatused kirjutatakse automaatse uuendamisega üle. Seega, kui kasutaja tahab, et muudatusi üle ei kirjutataks, peab ta valima EHIS-st andmete automaatse uuendamise väärtuseks "ei".
Lisanduvad:
* Lisandu ESCO ametite (occupation) alusel liigitamine

**Comment by lsoonvald** [comment]
Viga 1: Korras.
Viga 2: Ühikut enam taha lisaks ei tule, jääb hoopis selgitav hint tekst.
Viga 3: Korras.
Viga 4: Taksonoomiaid soovitab alles siis kui esimene täht/number sisestatud.
Viga 5: Lisatud taksonoomiad: Humanitaarteaduse bakalaureus, Haridusteaduse bakalaureus. Seega kui EHISest tuleval õppekaval on akadKraadDiplomi väärtuseks üks nendest taksonoomiatest, siis see lisatakse külge antud õppekavale Drupalis.

**Comment by TanelTromp** [comment]
Viga 4: kas "on focus" kuvamist ei saa teha kõigist taksonoomiatest? Hetkel on lahendus väga ebamugav.

Viga 6:  "Õppekeel(t)e" valikul peaks dropdownlistis muu väärtus(t)e valimisel uncheck markima "puudub" välja. Hetkel tuleb seda eraldi teha ja see on segadust tekitav.
![pilt](https://user-images.githubusercontent.com/37407917/40975984-56a1c858-68d5-11e8-8a5c-57f75a8e1849.png)

Viga 7: "Kutsestandardi identifikaatorit" saab lisada ainult ühe aga peab saama lisada mitut

Viga 8:  Suvalisel väljal vajutades "ENTERit" käivitub "Salvestamise" käsk. Seda ei tohiks olla.

Viga 9: "EHIS-st automaatselt lisamise aja" välja ei saa tühjaks jätta, kui "format" nupu all olev hint seda ühe lahendusena pakub.
![pilt](https://user-images.githubusercontent.com/37407917/40976312-72fa0d52-68d6-11e8-875c-2d7d3ea90e47.png)

@lsoonvald

**Comment by lsoonvald** [comment]
Viga 4: Ei saa, sest väljale võib juurde lisada taksonoomiaid, siis peab olema nõnda.
Viga 6: Korras.
Viga 7: Saan lisada mitu, pane komad vahele. :)
Viga 8: PHP feature.
Viga 9: Korras.
