### ISSUE TITLE
Õppekavade nimistu kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#147]
**Üldkirjeldus:**
Kuvada õppekavade (StudyProgramme) nimekiri, et kasutaja saaks leida teda huvitavat õppekava. Vaikimisi kuvatakse kõrg- ja kutsehariduse õppekavad, millele vastuvõtt on avatud.

**Eeltingimused ja käivitamine:**
- Õppekavade nimekirja nägemiseks kasutaja valib menüüribalt "Erialad" (selgitus: portaali kasutaja kasutajaliidesel kasutab "õppekava" asemel terminit "erialad").

**Vastuvõtutingimused:**
* Õppekava peab vastama järgmistele tingimustele:
-- õppekava on märgitud avaldatavaks (published = true)
-- õppekava liik (type) on "Kõrghariduse õppekava" või "Kutsehariduse õppekava" 
Märkus: Õppekava liiki kontrollitakse ka EHIS-st andmete sisse lugemise käigus, kuid siin on otstarbekas seda kontrolli dubleerida, sest edaspidi võidakse hakata sisse lugema ka huvihariduse õppekavasid, aga siin jäädakse kuvama kõrg- ja kutsehariduse õppekavasid.

* Õppekava kohta kuvatakse nimistu:
-- Nimetus (name)
-- Õppekavaga seotud õppeasutuse (EducationalInstitution):
---- Nimetus (name)
---- Asukoht (Location)
------ Kasutatakse juriidilise aadressi andmeid (locationType = "L"). Kui EHIS-s tehakse edasiarendused, siis õppeasutusele võib tekkida rohkem asukohti ja õppekava võidakse hakata siduma konkreetse asukohaga, kus seda õpet läbi viiakse (selle realiseerimine on ei ole käesoleva pileti skoobis). 
------ Maakond (county)
------ Linn või vald (localGovernment)
------ Küla, vald, alevik või linnaosa (settlementUnit)
------ Aadress (address)
-- Õppekava tase (level)
-- Õppekeel(ed) (teachingLanguage)
-- Õppekavarühm (ISCEDFdetailedField)
-- Õppe nominaalkestus aastates ja/või kuudes (durationYears, durationMonths)
-- Kirjeldus (shortDescription)
-- Vastuvõtu olek (admissionStatus)
-- Märge "Kehtiv akreediteering", kui  Akrediteerimise otsus (accreditationStatus) = "Täielikult akrediteeritud" ja Akrediteerimise otsuse kehtivuse lõpp (accreditationValidUntil) >= jooksev kuupäev.

* Õppekavad kuvatakse Nimetuse ja õppeasutuse Nimetuse järjekorras.

* Vaikimisi kuvatakse õppekavad, kuhu vastuvõtt on avatud (Vastuvõtu olek (admissionStatus) = "Avatud").

* Kui mingil andmeelemendi väärtus puudub, siis seda andmeelementi ei kuvata (muud andmeelemendid nihkuvad üles, kõrvuti olevad andmeelementide korral jääb tühi koht).

* **_Nimistus liikumine_**: Kasutaja saab nimistus eelmisi-järgmisi kirjeid vaadata (nimistut kerida).

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Disain:
https://zpl.io/bWR7z91
https://zpl.io/aMmY7nR - mobiil
https://zpl.io/2j8OpeA - filter

**Viited:**
* Õppekavade andmete toimetamine https://github.com/hariduspilv/haridusportaal/issues/146.
* Õppekava nimistu filtreerimine https://github.com/hariduspilv/haridusportaal/issues/148.
* Õppekavade nimistust avatav õppekava detailvaade https://github.com/hariduspilv/haridusportaal/issues/149.
* Õppeasutuse õppekavade nimistu kuvamine https://github.com/hariduspilv/haridusportaal/issues/151

**Comment by heldiraudsepp** [comment]
Testimine 3

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppekavade nimistu kuvamine
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Edge 16.16299, IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Windows tablet Thinkpad
Keskkond: http://htm.twn.ee/

**Viga 1**: kui muudan sisuhalduses nt TLÜ "Aasia uuringud" bakalaueruse eriala mitte avaldatuks, ilmub nähtavale sama eriala magistri õppekava, mida enne portaalis ei kuvatud, st algselt kuvati kaks sama bakalaureuse õppe eriala ja magistri eriala ei kuvatud. Kui muudan eriala mitte avaldatuks, siis kaob sisuhalduses eriala õppekavade nimistust ära.

**Viga 2**: lisasin abiaedniku erialale (Räpina Aianduskool) lühikirjelduse, nimekirjas seda ei kuvatud. Nõuetes on kirjas, et nimistus kuvatakse ka eriala kirjeldus. Nõuded ja kujundus on vastuolus.

**Viga 3**: vaadata üle järgmine nõue -- Märge "Kehtiv akreediteering", kui Akrediteerimise otsus (accreditationStatus) = "Täielikult akrediteeritud" ja Akrediteerimise otsuse kehtivuse lõpp (accreditationValidUntil) >= jooksev kuupäev. Hetkel ei kuvata õppekava akrediteerimise infot nõuete kohaselt.

**Viga 4**: dubleerivad erialad nimistus. Sisuhalduses on antud erialad erineva kestusega, portaalis on kuvatud sama kestusega.

![image](https://user-images.githubusercontent.com/37401947/43512181-0df45320-9583-11e8-8bab-f1762400c10f.png)

![image](https://user-images.githubusercontent.com/37401947/43512189-14a800ea-9583-11e8-8dc0-bfa210866374.png)

![image](https://user-images.githubusercontent.com/37401947/43512201-1a78707c-9583-11e8-9bad-04c81123d675.png)

**Viga 5**: vaadata üle õppekavade järjestus. Nõuete järgi peavad õppekavad olema järjestatud eriala nimetuse JA kooli nimetuse järgi.

![image](https://user-images.githubusercontent.com/37401947/43512221-25b3fa24-9583-11e8-9178-2676219aaabe.png)

**Viga 6**: mobiilis ei kuvata vaadet korrektselt. "Lisa võrdlusesse" teksti kuvatakse osaliselt.

![image](https://user-images.githubusercontent.com/37401947/43512325-7f67b1a0-9583-11e8-8981-deecde27542a.png)

@lsoonvald @RaimoJohanson

**Comment by MirellKr2** [comment]
Õppekavarühm (ISCEDFdetailedField) vajab veel arendamist.

**Comment by MirellKr2** [comment]
Viga 1 on seotud sisuhalduri kasutajaõigustega (sisuhaldurile ei kuvata avaldamata õppekavasid).

**Comment by RaimoJohanson** [comment]
viga 2: (lühikirjeldus)- nõuete vastuolu, ootan selgust
viga 3: (akrediteerimise info)- parandatud
viga 4: (erialade duplikaadid)- offset'iga pärides tulevad duplikaadid @lsoonvald 
viga 5: (järjestus eriala nime ja kooli järgi)- parandatud
viga 6-8:(mobiili vaated) @skeefee

**Comment by MirellKr2** [comment]
Viga 2: lühikirjelduse kuvamine jääb detailvaatele, nimistu vaates seda siiski ei kuva.

**Comment by RaimoJohanson** [comment]
viga 3: Akrediteerimise info parandus on tagasi võetud. Ei kontrollita kehtivuse aega @andrussarv

**Comment by birgitpulk** [comment]
Kujunduse muudatus! @RaimoJohanson 
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1f90721f79c2d772503e13

**Comment by MirellKr2** [comment]
Kuidas see vaade paistab välja nt resoga 1024 (kitsam vaade)? Kuidas need väljad peaksid liikuma? @birgitpulk

**Comment by birgitpulk** [comment]
e-post või telefon+e-post (sõltuvalt laiusest) liiguvad järgmisele reale, vt siin on näide olemas (teine rida): https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b05735509a18d3d0f546cb7
