### ISSUE TITLE
Õppekavade nimistu filtreerimine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#148]
**Üldkirjeldus:**
Filtreerida kuvatud õppekavade nimekirja, et leida huvipakkuv õppekava.

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud õppekavade nimistu (vt https://github.com/hariduspilv/haridusportaal/issues/147).

**Vastuvõtutingimused:** 
* Õppekavasid saab filtreerida järgmiste tunnuste alusel:
--  "Mis mind huvitab" märksõna - süsteem otsib õppekavad, mille korral sisestatud märksõna sisaldub nimetuses (name), lühikirjeldus (shortDescription), omistatavas kraadis või diplomis (degreeOrDiplomaAwarded), spetsialiseerumises (specialization) või õppekavarühma (ISCEDFdetailedField väärtuses). Võrdlused ei ole tõstutundlikud (suur- ja väiketähed loetakse samaväärseks).
-- Õppekava tüüp - Kasutaja valib otsitava tüübi taksonoomiast (StudyProgrammeType). Süsteem otsib õppekavad, mille tüüp (type) võrdub valitud tüübiga.
-- Õppekava tase - Kasutaja valib otsitava taseme taksonoomiast (StudyProgrammeLevel). Süsteem otsib õppekavad, mille tase (level) võrdub valitud tasemega.
-- Õppevaldkond - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF, kõige üldised). Süsteem otsib õppekavad, mille õppevaldkond (ISCEDFbroadField) võrdub valikuga. 
-- Õppesuund - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF keskmine tase; saab valida eelnevalt valitud valdkonna alla kuuluvate suundade hulgast). Süsteem otsib õppekavad, mille suund (ISCEDFnarrowField) võrdub valikuga.
-- Õppekavarühm - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF kõige detailsem tase, ; saab valida eelnevalt valitud suuna alla kuuluvate õppekavarühmade hulgast, multivalik). Süsteem otsib õppekavad, mille õppekavarühm (ISCEDFdetailedField) võrdub valikuga.
-- Õppekeel - Kasutaja valib otsitava õppekeele taksonoomiast (TeachingLanguage). Süsteem otsib õppekavad, mille õppekeelte (teachingLanguage) hulgas sisaldub valitud keel.
-- Õppeasutus - Kasutaja valib mingi nõidusega õppeasutuse (EducationaInstitution). Süsteem otsib õppekavad, mille on seotud selle õppeasutusega.
-- Asukoht - Kasutaja valib asukoha maakondade taksonoomiast (saab teha multivaliku). Süsteem otsib õppekavad, millega seotud õppeasutuse (EducationalInstitution) asukohtade (Location) hulgas vähemalt ühe asukoha maakond (county) sisaldub valitud maakondade hulgas. 
-- Märkeruut "Ainult avatud vastuvõtuga" (vaikimisi on märkeruut täidetud) - Kui märkeruut on täidetud, siis süsteem otsib õppekavad, mille vastuvõtu oleks (admissionStatus) on"Avatud".

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Märkused:
* Lisada märksõna otsingusse ESCO ametite alusel otsing.
* Kui luuakse tüüpide ja tasemete taksonoomia vaheline seos, siis arvestada sellega valikunimistutes.

Disain: https://zpl.io/2j8OpeA

**Viited:**
* Õppekavade nimistu  https://github.com/hariduspilv/haridusportaal/issues/147
* Õppeasutuse õppekavad https://github.com/hariduspilv/haridusportaal/issues/151
* Valdkonna või ameti õppekavad https://github.com/hariduspilv/haridusportaal/issues/152
* Sarnased õppekavad https://github.com/hariduspilv/haridusportaal/issues/154

**Comment by heldiraudsepp** [comment]
Testimine 3h

**Comment by RaimoJohanson** [comment]
#148 täpsema otsingu osas zeplinist disaini ma ei leidnud. aga teeks nii, et 1 veerg õppekava tase, õppekeel, õppeasutus, asukoht; 2 veerg: õppevaldkond, õppesuund, õppekavarühm, ainult avatud vastuvõtuga. disain sarnane siis õppeasutustega https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b0573539da86c2e421ad590 ehk "kitsam otsing" paneb täpsema otsingu kinni

**Comment by RaimoJohanson** [comment]
ISCEDF valikud (õppevaldkond, õppesuund, õppekavarühm) on puudulikud: ootab BE järgi.

**Comment by MirellKr2** [comment]
Ühtlustada õppeasutuste ja erialade listi vaatel detailvaatele liikumist. Erialade vaatelt saab tervele reale klikkides detailvaatele liikuda, õppeaustuste puhul ainult nimetusele klikkides.

**Comment by MirellKr2** [comment]
Testimisest jääb hetkel kõrvale:
- "Mis mind huvitab" märksõna järgi otsing (vaja täpsustada vastuvõtutingimusi)
- Lisada märksõna otsingusse ESCO ametite alusel otsing (vaja täpsustada vastuvõtutingimusi ja üldse seda, millega tegu on ning kust andmed tulevad)
- Kas täiendavaid tingimusi peab võtma vastuvõtukriteeriumitena või on need miskid, millega võiks arvestada?

**Comment by MirellKr2** [comment]
Õppeasutuste väljal võiks toimida autocomplete.
@RaimoJohanson

**Comment by MirellKr2** [comment]
***Parandused:**

**Probleem 1**: õppeasutusi ei pea saama antud pileti raames otsida autocomplete-iga. 

**Probleem 2**: BE poolne järjestamise probleem (sarnane probleem esineb kõikide täpitähtedega). Loodame leida lahenduse.

**Probleem 3**: mobiili vaateid selle pileti raames ei tehta.

**Comment by MirellKr2** [comment]
Parandused üle vaadatud ja kõik korras.

Filtri _disabled_ väljad peaks kujundaja üle vaatame, et mis tekste kuvada nendel väljadel (sarnaselt õppeasutuse filtriga).
