### ISSUE TITLE
Õppekava detailvaate kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#149]
**Üldkirjeldus:**
Portaali kasutajale kuvatakse õppekava detailvaade, et portaali kasutaja detailsemalt tutvuda õppekavaga.

**Eeltingimused ja käivitamine:**
- Kasutajale on kuvatud õppekavade nimistu (vt #147). Kasutaja käivitab detailse kirjelduse vaatamise.

**Vastuvõtutingimused:**
* Süsteem kuvab kasutajale õppekava andmed:
-- Nimetus - name
-- Õppeasutuse nimetus - EducationalInstitution.name
-- Õppekava tase - level;  
-- Omistatav kraad või diplom - degreeOrDiplomaAwarded;  
-- Spetsialiseerumine - specialization
-- Õppevaldkond, õppesuund ja õppekavarühm - ISCEDFbroadField, ISCEDFdetailedField, ISCEDFnarrowField
-- Lühikirjeldus - shortDescription
-- Õppekeel(ed) -  teachingLanguage
-- Õppekava maht - amount 
-- Praktika maht - practicalTrainingAmount 
---- Õppekava mahu ja praktika mahu ühik: kui type = "Kõrghariduse õppekava", siis 'EAP';  kui type = "Kutsehariduse õppekava" siis 'EKAP'
-- Nominaalkestus (aastad, kuud) - durationYears, durationMonths
-- Vastuvõtu olek - admissionStatus
-- Akrediteerimise otsus - accreditationStatus
-- Akrediteerimise otsuse kehtivuse lõpp - accreditationValidUntil
-- Õppekava kirjeldava veebilehe aadress - webPageAddress; esitatakse klikitava lingina "Vaata õppekava kirjeldust õppeasutuse veebilehel"
-- Kutsestandard(id) -  esitatakse kutsestandardite numbrid

* Lingid avanevad veebilehitseja teises tabis.

* Kui mingil andmeelemendi väärtus puudub, siis seda andmeelementi ei kuvata (muud andmeelemendid nihkuvad üles, erandina päiseosas kõrvuti olevad andmeelementide korral jääb tühi koht).

* Õppekavade nimistusse liikumine: Süsteem avab õppekavade nimistu (https://github.com/hariduspilv/haridusportaal/issues/147).  
-- Õppekavade nimistu avatakse käesolevaga kuvatud õppekava kohalt (see on nimistus nähtaval kohal).
-- Kui õppekava detailvaatesse tuldi õppekavade nimistult ja seal oli rakendanud filtreerimist, siis rakendatakse uuesti samu filtreerimise tingimusi.

* Kui õppekava ei ole avaldatud (published = false), siis õppekava ei kuvata (404 error).

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Lisanduvad:
- ESCO ametid (occupation)

Disain:
https://zpl.io/bzWMzZ4
https://zpl.io/bAqv31e - mobiil

**Viited**:
* Õppekava andmete toimetamine https://github.com/hariduspilv/haridusportaal/issues/146.

Muud tegevused õppekava detailvaates:
-- Õppeasutuse kuvamine https://github.com/hariduspilv/haridusportaal/issues/150.
-- Sarnaste õppekavade kuvamine https://github.com/hariduspilv/haridusportaal/issues/154.
-- Õppekavade võrdlus https://github.com/hariduspilv/haridusportaal/issues/153.

**Comment by skeefee** [comment]
@TanelTromp

**Comment by TanelTromp** [comment]
TEST

Testi objekt 1: "Ajakirjandus"
http://192.168.6.209:8005/et/erialad/ajakirjandus

**Comment by EgleM-TW** [comment]
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b266b3d7a17a83d684626e8

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Korras
Viga 3: BE lahendada. Kui BE-l ticketit ei ole siis luua uus ticket
Viga 4: Korras
Viga 5: korras
Viga 6: Korras
Viga 7: Korras
Viga 8: Korras
