### ISSUE TITLE
Õppekava detailvaate kuvamine - õppeasutuse andmed

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#150]
**Üldkirjeldus:**
Portaali kasutajale kuvatakse õppekava detailvaate osana õppeasutuse asukoha andmed, et portaali kasutaja saaks rohkem infot seda õppimisvõimalust pakkuva õppeasutuse kohta.

**Eeltingimused ja käivitamine:**
- Kasutajale on kuvatud õppekava detailvaate (vt https://github.com/hariduspilv/haridusportaal/issues/149). Kasutaja käivitab õppeasutuse andmete kuvamise (esialgu õppeasutuse andmed on ainus andmeplokk ja on vaikimisi nähtaval).

**Vastuvõtutingimused:**
* Süsteem kuvab kasutajale õppekavaga seotud õppeasutuse (EducationalInstitution) andmed:
-- Nimetus (name)
-- Registrikood (registrationCode)
-- Õppeasutuse veebilehe aadress - (webPageAddress); esitatakse klikitava lingina
-- Telefon (contactPhone)
-- E-posti aadress (contactEmail)

* Süsteem kuvab kasutajale õppekavaga seotud õppeasutuse (EducationalInstitution) asukoha või asukohtade (Location) andmed:
---- Maakond (county)
---- Linn või vald (localGovernment)
---- Küla, vald, alevik või linnaosa (settlementUnit)
---- Aadress (address)
Kui tekib > 1 asukohta, siis need on järjestatud esmalt asukoha tüübi (juriidiline aadress 'L' on enne muude asukohtade 'V' aadress) ja seejärel muude asukoha andmete (maakond jne) järjekorras.

* Süsteem kuvab kaardil õppeasutuste asukohad, millel on geograafilised koordinaadid (location.geoCoordinatesLat ja ...Long).
-- Kui õppeasutuste asukohti on 1, siis õppeasutuse asukoht on tsentreeritud kaardi keskele ja zoom level on tänava tasemel (15; täpsustada suurus).
-- Kui õppeasutuse asukohti on >1, siis õppeasutuse asukohad jäävad kaardivaate minimaalsesse boundingbox-i (peab jääma ka ääris ehk margin, näiteks 5% (täpsustada suurus)).
---- Täpsustada eelmises lõigus kirjeldatud asukohtade andmete ja kaardil olevat asukohta markerite seostamine juhul, kui asukohtasid on > 1 (nt iga asukoht tähistada tähega)
- Kasutaja saab kaarti suurendada-vähendada (sisse-välja zuumida).
- Kasutaja saab kaarti nihutada.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kasutajaliidese eskiis:**
- [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b266b3d7a17a83d684626e8), 

**Viited**:
* Õppekava detailvaade (https://github.com/hariduspilv/haridusportaal/issues/149).
* Õppeasutuse õppekavad (https://github.com/hariduspilv/haridusportaal/issues/151).

**Comment by heldiraudsepp** [comment]
Selle pileti raames BE teeb päringu ja hindame ajakulu

**Comment by skeefee** [comment]
Kaardi interaktsioone ei tule - kokkulepe Andrusega

**Comment by skeefee** [comment]
@TanelTromp

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppekava detailvaate kuvamine - õppeasutuse andmed
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Edge 16.16299, IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Keskkond: http://htm.twn.ee/

**Viga 1**: õppeasutuse andmetest on puudu telefoninumber ja e-mail (vt nt Tallinna Tehnikaülikooli detailvaadet ja äriinfotehnoloogia eriala detailvaadet, sh vaata kujundust).

**Viga 2**: zoom tase erineb nõuetest (zoom level on tänava tasemel (15)). 

![image](https://user-images.githubusercontent.com/37401947/44198848-1f076e80-a14b-11e8-9076-4d11f828597b.png)

**Viga 3**: IE-s ei näita kaardil markerit.

![image](https://user-images.githubusercontent.com/37401947/44198292-abb12d00-a149-11e8-9651-eedd7e175af8.png)


**Probleem**: kaardivaade kuvatakse staatiliselt, nõuetes on aga kirjeldatud, et kaarti peab saama nihutada ning suurendada-vähendada. Õppeasutuse detailvaatel on kaart samuti staatiline. Need vaated võiksid olla sarnased ehk ettepanek oleks neid nõuded mitte arvestada.

**Märkus 1**: hetkel päritakse EHIS-est ainult juriidiline aadress. Muude tegevuskohtade/toimumiskohtade loogika veel realiseerimata (testimata need nõuded, mis puudutavad õppeasutuse mitut asukohta).

@skeefee

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Korras
VIga 3: Korras

Probleem: kokkulepe oli analüütikutega selline, et kaarti ei saa nihutada

Märkus 1: Administ saad asukohti ise manuaalselt mingile õppeasutusele juurde lisada vajadusel

**Comment by MirellKr2** [comment]
Korras
