### ISSUE TITLE
Õppeasutuse õppekavade nimistu kuvamine 

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#151]
**Üldkirjeldus:**
Portaali kasutajale kuvatakse õppeasutuse õppekavade nimistu, et portaali kasutaja saaks tutvuda õppeasutuse poolt pakutava õppega.

**Eeltingimused ja käivitamine:**
- Kasutaja on avanud õppeasutuse detailvaate. 

**Vastuvõtutingimused:**
* Süsteem kuvab õppeasutuse õppekavade nimistu. Õppeasutuse õppekavade nimistu kuvamine on samasugune https://github.com/hariduspilv/haridusportaal/issues/147 kirjeldatud õppekavade nimistu kuvamisega, kuid selle täiendusega, et nimistus on ainult kuvatud õppeasutuse õppekavad ja nimistu iga rea juures ei kuvata õppeasutuse andmeid (nimetus ning aadress).

- [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1396ae5c403c452a8f5a30)
- [Mobiil disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b14da160f17ae5b3e60ad16)

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by birgitpulk** [comment]
Kuna meil tekkis ka kooli detailvaade, siis lisasin õppekavad (ehk erialad) kooli detailvaatesse, et info oleks ühes kohas koos.

**Comment by birgitpulk** [comment]
Kujunduse muudatus! @mark-shabalin 
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b0573539da86c2e421ad590

**Comment by MirellKr2** [comment]
Kujunduse muudatuse sisseviimiseks luuakse järgmisesse sprinti uus pilet.

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppeasutuse õppekavade nimistu kuvamine
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Edge 16.16299, IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Keskkond: http://htm.twn.ee/

**Viga 1**: nimistu iga rea juures ei kuvata õppeasutuse andmeid (nimetus ning aadress) -> aadress on kuvatud. 

**Viga 2**: zoom-ides ei peaks tabelile tekkima sellist skrolli (palun vaata eriala detailvaatel olevat tabelit).

**Viga 3**: joondus paigast ära.

![image](https://user-images.githubusercontent.com/37401947/44203003-5596b680-a156-11e8-8a16-346cf5babe84.png)

**Märkus**: õppekavade päring on pisut aeglane (esimesel laadimisel ca 3 sek).

@mark-shabalin

**Comment by MirellKr2** [comment]
Nimistus esinevad vead parandatakse järgmises sprindis uue kujunduse sisseviimisega.
