### ISSUE TITLE
Ametiala sisulehelt õppekavade kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#152]
**NB! Analüüsida vajadust ja võimalusi OSKA edasiarenduste raames #626** 

**Üldkirjeldus:**
Portaali kasutajale kuvatakse ametiga seotud õppekavade nimistu, et portaali kasutaja saaks selle ameti õppimise võimalusi.

**Eeltingimused ja käivitamine:**
* Kasutaja on avanud _ameti mingid andmed mingisugusel erkaanivomril (https://???github.com/hariduspilv/haridusportaal/issues/???)_. Kasutaja käivitab ameti õppimise võimaluse vaatamise. 
 
Vastuvõtutingimused:
* Süsteem avab veebilehitseja uues tab-s ametit õpetavate õppekavade nimistu (ametit õpetavate õppekavade otsingu kohta vaata järgmist lõiku). Ametit õpetavate õppekavade nimistu kuvamine on samasugune https://github.com/hariduspilv/haridusportaal/issues/147 kirjeldatud õppekavade nimistu kuvamisega koos filtriga https://github.com/hariduspilv/haridusportaal/issues/148, kuid selle täiendusega, et nimistus kuvatakse ametit õpetavate õppekavade otsingu tulemusena leitud õppekavad ja "mis mind huvitab" filtri väli on eeltäidetud ameti nimetusega. 

* Ametit õpetavate õppekavade otsing: 
a) Süsteem otsib õppekavad, millel on seos ametiga 
b) Süsteem teeb märksõna järgi otsingu (vt https://github.com/hariduspilv/haridusportaal/issues/148) kasutades märksõnana ameti nimetust. 
-- Õppekavad peavad vastama kuvamise tingimustele (vt https://github.com/hariduspilv/haridusportaal/issues/147 esimene vastuvõtutingimus) 
-- Eespool kuvatakse variandi a) alusel leitud õppekavad.
-- Praegu puudub õppekavade ja ametite vaheline seos. Kui õppekavasid ja ameteid ei hakata omavahel siduma, siis rakendub ainult b) variant.

Kui otsing ei leidnud ühtegi õppekava, siis süsteem kuva teate "Portaalis puuduvad andmed selle ameti õppimise võimaluste kohta."

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by EgleM-TW** [comment]
Ametikoha vaade jääb ilmselt lisatööde etappi, sest seda pole hankes küsitud. Lahtine on, kas sama asi siduda põhikutseala vaatega.

**Comment by RainLeoma** [comment]
Mulle tundub, et meie jaoks lahendab vajaduse ära: Ametiala sisulehelt õppimisvõimalsute siselingi täiendamine #681

Õppekava tasemele me enda tulemustes hetkel ei plaani minna. Ma ei suudaks hoida kasutajate jaoks piisavalt aktuaalsena. 

Või oli siin mingi muu mõte juures? Vaatan, et see on päris vana pilet ja ei mäleta enam täpselt selle loomise tagamaid.

**Comment by EgleM-TW** [comment]
Sulgen pileti, kuna vajadus on realiseeritud õppimisvõimaluste siselingiga #681
