### ISSUE TITLE
Õppekavade võrdlus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#153]
**Üldkirjeldus:**
Portaali kasutaja saab õppekavadest teha võrdlustabeli, et leida talle kõige paremini sobivat eriala õppimise võimalust.

_Täpsustada, kuidas võrdluse lahendus tehniliselt realiseeritakse. Kasutaja ei pea olema sisse logitud. Mingi küpsiste lahendus?_

**Eeltingimused ja käivitamine:**
- Kasutajale on kuvatud õppekava detailvaate (vt https://github.com/hariduspilv/haridusportaal/issues/150). Kasutaja saab käivitada järgmisi tegevusi:
-- Kui kuvatav õppekava pole veel lisatud võrdlusesse, siis lisada võrdlusesse.
-- Kui kuvatav õppekava on juba lisatud võrdlusesse, siis eemaldada õppekava võrdlusest.
-- Kui võrdluses on vähemalt üks õppekava, siis vaadata võrdlust.

**Vastuvõtutingimused:**

_**Õppekava lisamine võrdlusesse**_
* Süsteem lisab õppekava võrdlusesse. Õppekava ekraanivormi võrdlusesse lisamise võimalus asendatakse eemaldamise ja võrdluse vaatamise võimalustega.
* Korraga võrdluses olevate õppekavade arv on piiratud (max 3). Kui see arv on juba täis, siis süsteem kuvab teate "Maksimaalne võrreldavate erialade arv on ületatud."

_**Õppekava eemaldamine võrdlusest**_
* Süsteem eemaldab õppekava võrdlusesse. Õppekava ekraanivormil võrdlusest eemaldamise võimalus asendatakse võrdlusesse lisamise võimalusega.

_**Võrdluse vaatamine**_
* Süsteem kuvab võrdlusesse pandud õppekavade kohta tabeli kujul järgmised andmed:
-- Nimetus - name
-- Õppeasutuse nimetus - EducationalInstitution.name
-- Õppekava tase - level;
-- Omistatav kraad või diplom - degreeOrDiplomaAwarded;
-- Spetsialiseerumine - specialization
-- Õppekeel(ed) - teachingLanguage
-- Õppekava maht - amount 
-- Praktika maht - practicalTrainingAmount
---- õppekava mahu ja praktika mahu ühik: kui type = "Kõrghariduse õppekava", siis 'EAP'; kui type = "Kutsehariduse õppekava" siis 'EKAP')
-- Nominaalkestus (aastad, kuud) - durationYears, durationMonths
-- Vastuvõtu olek - admissionStatus
-- Akrediteerimise otsus - accreditationStatus
-- Akrediteerimise otsuse kehtivuse lõpp - accreditationValidUntil

* Kui andmeelemendi väärtus puudub, siis kuvatakse tabelis selle asemel - .

* Õppekava nimetus kuvatakse lingina, millele klikkimise korral avatakse selle õppekava detailvaade.

* Õppekavasid saab võrdluse vaatamise ekraanivormil võrdlusest eemaldada. Kui kasutaja eemaldab võrdlusest eemaldatakse viimase õppekava (võrdlus jääb tühjaks), siis süsteem kuvab õppekavade nimistu https://github.com/hariduspilv/haridusportaal/issues/147.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kasutajaliidese eskiis:**
- [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26b757c2f9e5b732c25d90)
- [Disaini link mobiil](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26ca58d443767461bc8724)

**Viited:**
* Õppekava detailvaade https://github.com/hariduspilv/haridusportaal/issues/150.
* Õppekavade nimistu https://github.com/hariduspilv/haridusportaal/issues/147.

**Comment by lsoonvald** [comment]
Graphql pihta saab päringut teha sellise näiteurliga: http://test-htm.wiseman.ee:30000/graphql?queryId=studyProgrammeComparison:1&variables={ "lang": "ET", "nidValues": ["48329","46586","47143"] }

**Comment by RaimoJohanson** [comment]
Teeme teate modaalis "Võrdlusesse saab lisada kuni 3 eriala." modaal avaneb >3 ehk neljanda lisamisel. Kui on vähemalt üks võrdluses, siis peaks olema iga õppeakava juures "lisa võrdlusesse" kõrval ka "vaata võrdlust" (uppercase) link

**Comment by RaimoJohanson** [comment]
Pileti raames valmis ka võrdlusesse lisamise komponent, mida on võimalik edaspidi rakendada muude andmete võrdlemiseks

**Comment by madispold** [comment]
Võib uuesti testida @MirellKr2

**Comment by madispold** [comment]
@ruut12 
Tõlked vaja lisada:

button.see_comparison
button.remove_from_comparison
studyProgramme.compare_modal_title
studyProgramme.compare_modal_content
studyProgramme.compare_modal_close
studyProgramme.non_active
time.years
STUDYPROGRAMME.RELATED.LABEL
studyProgramme.related.filter_location
studyProgramme.school
studyProgramme.degree_or_diploma
studyProgramme.specialization
studyProgramme.study_capacity
studyProgramme.internship_capacity
studyProgramme.accreditation_decision
studyProgramme.accreditation_decision_till

**Comment by madispold** [comment]
Uus võrdluse komponent jm testis.

**Comment by madispold** [comment]
@ruut12 Veel tõlkeid:
studyProgramme.added_to_comparison
studyProgramme.compare_modal_content - tühi.
button.add_to_comparison: "Lisa võrdlusesse", mitte "Lisa võrdlusess" nagu praegu

**Comment by TanelTromp** [comment]
Viga 1 mobiil: ei kuva "Vaata võrdlust" valikut peale eriala võrdlusse lisamist, ainult "et on lisatud".

Viga 2: selline vaade

![pilt](https://user-images.githubusercontent.com/37407917/44659813-1eee5500-aa0e-11e8-9289-507293aea016.png)

**Comment by madispold** [comment]
@TanelTromp 
Viga 1: Kuna kuvatakse hetkel tõlke nimetus, mitte tõlge ise, siis tegu pika tühikuteta murdmatu sõnaga, mille tõttu action peitu jääb. Fix tuleb tõlkega.
Viga 2: Parandatud.
Viga 3: Igasugused filtrid üle vaadete on sama loogikaga Nt. http://htm.twn.ee/et/kool?title=test&location=Multi. 
Samas võtmes ka pildil olev http://htm.twn.ee/et/erialad?open_admission=true,  mis tähistab seda, et kuvatud vaid avatud vastuvõtuga erialad.

**Comment by TanelTromp** [comment]
Viga 5: mobiilivaates kuvab ainult kaks äärmist õppekava, keskmine puudu horisontaalsest kerimisest.

**Comment by madispold** [comment]
Viga 5: Ei suuda ise tekitada seda (Iphone 6). Kindel, et sul vaid 2 polnud võrdluses või alt nupust ei eemaldanud ühte?
Viga 6: Mida see tähendab? Kas ülevalt alla scrollbar peab tekkima?

**Comment by TanelTromp** [comment]
Viga 5: oli mingi Ghoslabi anomaalia, sorri. Nüüd korras.
Viga 6: kuidas ma näen tablet vaates võrdlusi? a. kas need on kuvatud kõrvuti välja nagu desktop vaates b. nagu mobiilivaates ja horisontaalse skrolliga (nooled)

Hetkel ei saa midagi teha ja selline vaade nagu panin sulle kuvatõmmise on fikseeritud.

**Comment by madispold** [comment]
Viga 6: Kuvatõmmise alusel ütleks, et võrdluses vaid 1 eriala, kuna pealkiri murdub vaid lõpus ja ei teki scrollimise indikaatoreid.
PILT: ![Screen Shot 2018-08-27 at 16.31.38.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/9d44c086-62fa-4a78-80c2-b3b4b71b4b5f)

3-e puhul isegi mul brauseris simuleerides 768px laiusel ekraanil heal juhul mahutab 3 ilma scrollimiseta.
PILT: ![Screen Shot 2018-08-27 at 16.32.12.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/fb33f76f-3e8f-4e6a-9b1e-b7c82baf16da)

**Comment by TanelTromp** [comment]
Sorri! Tundub, et nii oli! (see on ka Ghostlabi Wi-Fi IP-de kamm ehk ei lae samme kõigisse seadmetesse üles sünkroonis).

Hetkel siis veel üks bugi: tablet vaates kuvab tabelil neid skrollbare, kuigi midagi ei ole kerida:

**Comment by madispold** [comment]
Kas saad täpse tableti öelda?

**Comment by madispold** [comment]
@birgitpulk Kas stiilide osa vaja üle käia või kinni?

**Comment by birgitpulk** [comment]
@andrussarv kas sinu poolt ok kui eriala nimetus oleks link? Hetkel kujunduses ei ole link, aga arendatud on lingiks

**Comment by birgitpulk** [comment]
Minu poolt ok
