### ISSUE TITLE
Sarnaste õppekavade kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#154]
**Üldkirjeldus:**
Portaali kasutajale kuvatakse õppekavaga sarnaste õppekavade nimistu, et portaali kasutajal oleks võimalik leida erinevaid huvipakkuvaid õppimise võimalusi.

**Eeltingimused ja käivitamine:**
- Kasutajale on kuvatud õppekava detailvaate (vt https://github.com/hariduspilv/haridusportaal/issues/150). Kasutaja käivitab sarnaste õppekavade (erialade) otsingu.

**Vastuvõtutingimused:**
* Süsteem kuvab veebilehitseja uues tab-s kuvatud õppekavaga sarnaste õppekavade nimistu (sarnaste õppekavade otsingu kohta vaata järgmist lõiku). Sarnaste õppekavade nimistu on järjestatud sarnasuse määra alusel sarnasemad eespool (sarnasuse määra arvutamise kohta vaata ülejärgmist lõiku). Sarnaste õppekavade nimistu kuvamine on samasugune https://github.com/hariduspilv/haridusportaal/issues/147 kirjeldatud õppekavade nimistu kuvamisega, kuid selle täiendusega, et nimistus kuvatakse ainult sarnaste õppekavade otsingu tulemused.

* Sarnaste õppekavade otsing: süsteem otsib üldistel kuvamise tingimustele (vt https://github.com/hariduspilv/haridusportaal/issues/147 esimene vastuvõtutingimus) vastavad  õppekavad, millel on kuvatud õppekavaga sama:
-- tüüp (type)
-- sama ISCED-F õppekavarühm (ISCEDFdetailedField) või sama nimetus (name) ja
-- vähemalt üks kattuv õppekeel (teachingLanguage)

*  Sarnasuse määra arvutamine: Sarnasus määratakse sarnasuspunktide alusel. Mida rohkem sarnasuspunkte õppekava saab, seda sarnasem see on. 
-- sama omistatav kraadi või diplom (degreeOrDiplomaAwarded) annab 3 punkti
-- iga kattuv kvalifikatsiooni standard (qualificationStandard) annab 3 punkti
-- õppekava maht ka kuidagi siis tuua 
-- sama õppetase (level) annab 2 punkti 
-- iga kattuv amet (ESCO occupation) annab 1 punkti 

 _**NB!** Hinnata, kui suuri jõudlusprobleeme selline otsing ja arvutus põhjustab.  Vajadusel viia arvutuskoormus mujale, näiteks kord ööpäevas õppekavade andmete automaatse uuendamise järel arvutada sarnased õppekavad välja taustal lõimeteenuse komponendis. Selline lahendus hajutaks koormust nii "ruumis" (koormus kandub teise komponenti) kui ka "ajas" (tulemused arvutatakse ette valmis, mitte ei arvutata jooksvalt kasutaja interaktsiooni ajal)._

* Õppekava, millele sarnaseid õppekavu otsitakse, ei kuvata sarnaste õppekavade nimistus.

* Kui ühtegi sarnase õppekava otsing ei leidnud ühtegi õppekava, siis süsteem kuva teate "Sarnased erialad puuduvad."

**Kasutajaliidese disain:**
- [Disaini link: sarnased erialad lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b266b3d3a42947a38b5876d)
- [Disaini link: sarnased erialad lahti mobiil](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b26be764b49720103c8aa72)

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Viited:**
 * Õppekava detailvaade vt https://github.com/hariduspilv/haridusportaal/issues/150.

**Comment by lsoonvald** [comment]
Näitepäring: http://test-htm.wiseman.ee:30000/graphql?queryId=similarStudyProgrammes:1&variables={"nid":47185}

**Comment by madispold** [comment]
Stiilid tehtud @MirellKr2

**Comment by TanelTromp** [comment]
Viga 1: sissesuumides ja akent kokkulükates ei ole "Otsi" kiri enam center-aligned (ei ole brauseri põhine viga):
![pilt](https://user-images.githubusercontent.com/37407917/44252186-0dce6880-a204-11e8-96d0-0a633bdaf5bc.png)

Viga 2: "akrediteering" väli katki:
![pilt](https://user-images.githubusercontent.com/37407917/44252221-2d659100-a204-11e8-8164-a9a527c32f99.png)

Viga 3: vaates on kuvatud ka "kuu", "sarnased õppekavad, vale:
![pilt](https://user-images.githubusercontent.com/37407917/44252423-c399b700-a204-11e8-8a3d-c95566f7ac2e.png)

Õige (nagu õppekavade kuvamises):
![pilt](https://user-images.githubusercontent.com/37407917/44252367-9816cc80-a204-11e8-81c2-4f034d8e306f.png)

**Comment by RaimoJohanson** [comment]
viga 2: parandatud,
viga 3: parandatud

**Comment by madispold** [comment]
Viga 4 parandatud.

**Comment by TanelTromp** [comment]
Back-end testilood:
[154testlood.xlsx](https://github.com/hariduspilv/haridusportaal/files/2300289/154testlood.xlsx)

**Comment by TanelTromp** [comment]
Viga 8: katkine veateade:
![pilt](https://user-images.githubusercontent.com/37407917/44388648-4dad8c80-a531-11e8-979c-674afe96969b.png)

**Comment by lsoonvald** [comment]
Viga 1: Parandatud qualificationStandardId skoorimine, järjekord peaks paigas olema.
@TanelTromp

**Comment by TanelTromp** [comment]
Viga 3: "Test ID 2 eriala" peaks kuvama teisena, kuvab kolmandana. "Test ID 4 eriala" peaks kuvama kolmandana aga kuvab teisena. Need on sisestuselt identsed, v.a "õppekavamaht" ehk see on "Test ID 4 eriala" teine 120. Rohkem punkte annab 160 nagu on "Test ID 2 erialal". Vaata ka testlugusid:
[154testlood.xlsx](https://github.com/hariduspilv/haridusportaal/files/2306175/154testlood.xlsx)
@lsoonvald

**Comment by lsoonvald** [comment]
Viga 3: Parandatud. @TanelTromp

**Comment by birgitpulk** [comment]
Eriala osa:
- [ ] Jaga märk peaks olema sinist tooni (vt kujundust)
- [ ] "Lisa võrdlusesse" teksti toon peaks olema #333333, kas on?
- [ ] "Vaata võrdlust" nupp tekib võrdluskastist vasakule, mitte selle alla. Link suure esitähega (mitte läbiva suurtähega) ning lingi ja checkboxi vahe 32px
- [ ] Checkboxi sees olev nool ei lähe üle ääre (vt avalehte uudiskirja osa)

Sarnased erialad: 
- [ ] Asukoha otsingu kastis mingi jama:
<img width="773" alt="screen shot 2018-08-21 at 19 30 20" src="https://user-images.githubusercontent.com/24669779/44415549-68a3ef00-a579-11e8-9e26-de1676c76e14.png">
- [ ] Vormivälja ja otsi nupu vahe ei ole kujundusele vastav (peaks olema 16px)
- [ ] Otsingu nupu laius peaks olema 133px, ekraani suuruse muutudes muutub vormiväli laiemaks-kitsamaks.

Parempoolne sektsioon: 
- [ ] Sinistel linkidel ei peaks olema parempoolses blokis joont all. Hoveriga peaks joon tekkima. 
- [ ] Kaardi linkidel peaks hoveriga valge joon alt ära kaduma.

PS: CTA nuppudele võiks lehekülje üleselt panna hoveri, mille toon on #454B92. 

@TanelTromp , siin palju FE teemasid, kelle ma peaks FE osas siia külge panema? Kes seda FE osa tegi?

**Comment by madispold** [comment]
Punktid lahendatud.

Üks tähelepanek, et jätsin desktop vaates "Vaata võrdlust" nupu siiski hetkel checkboxi alla, kuna olles kõrvuti lükkab pealkirja väga kitsaks. Variant oleks kas järgmisele reale tõsta (nagu mobiilis) või peab lihtsalt arutama.

**Comment by birgitpulk** [comment]
@madispold , arutasime eile Andrusega seda sama teemat ja tundus jah et jääb juba kitsaks. Kas selline lahendus oleks ka teostatav, et see vaata võrdlust nupp ei tuleks üldse sinna kõrvale/alla vaid ekraani alumisse serva tekiks snackbar, mille sees on info viimati võrdlusesse lisatud eriala kohta ja siis link?
Vt siin: https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b7d17e9987c912edf1838f2

**Comment by TanelTromp** [comment]
@birgitpulk palun siis kontrolli ise Madise debuggimist kujunduse osas ja tõsta, kui "OK" "Donei".
Tänud!

**Comment by birgitpulk** [comment]
ok @TanelTromp

**Comment by madispold** [comment]
Uue kujundusega Erialade/Õppekavade vaated testkeskkonnas

**Comment by madispold** [comment]
@birgitpulk

**Comment by birgitpulk** [comment]
Minu poolt korras!
