### ISSUE TITLE
Uudiste nimekirja filter

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#156]
**Üldkirjeldus**
Kuvada uudiste (News) nimekirja kohal filter, et kasutaja saaks uudiste nimekirjast uudist otsida.

**Eeltingimused ja käivitamine**
Kasutaja jõuab uudiste nimekirja:

- Realiseeritud on uudiste nimekirja vaade - pilet #12
- Avalehelt valides uudise blokist „Vaata kõiki“ 
- Uudise detailvaatest valides „Kõik uudised“

Eeltingimusi selle töö raames ei testita.

**Vastuvõtutingimused**

Kasutaja saab:
otsida uudist/ filtreerida uudiseid:
- uudise pealkirja järgi (Otsi uudist pealkirja järgi) - andmebaasi päring uudise pealkirja väljast, tulemustes kuvatakse kõige uuemad kõige esimesena.
- avaldamise kuupäeva järgi (Vali alguskuupäev/ Vali lõpukuupäev),
   - kui lõpukuupäeva pole määratud siis otsing kuni viimati avaldatud uudiseni;
   - kui alguskuupäeva pole määratud siis alates esimesest uudisest.
- sildi (tag) järgi (Vali uudise silt) - avaneb lingi alt "Täpsem otsing"

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kujundatud vaated**:
https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbef090879ff66168809f5
https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc28a8c384811f0fbb0036
https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbf8f9852cc3f615c79ec3
https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afdd32811c2d1c625783007

NB! @doomler, otsi nupu navigeerimine küsi üle @birgitpulk

**Comment by TanelTromp** [comment]
Vearaport #156_1

Tegevuse üldine kirjeldus: mobiilivaate parema veeru kuva front-end
Testimise tegevused: funktsionaalsete nõuete testimine, mittefunktsionaalsete nõuete testimine

Brauserid: Chrome 66.0; Mozilla 59.0; Internet Explorer 11 + Windows 10, 64b

LG 3840 x 2160 px (UHD)
1920 x 1080 px (Laptop)
Seadmed:
iOS 11.3 iPhone 6s + Safari
Lenovo thinkpad 1366 x 768px + Chrome + Windows 8
Android 7.0 Samsung Galaxy A5 + Chrome

uudise pealkirja järgi (Otsi uudist pealkirja järgi) - andmebaasi päring uudise pealkirja väljast, tulemustes kuvatakse kõige uuemad kõige esimesena.

avaldamise kuupäeva järgi (Vali alguskuupäev/ Vali lõpukuupäev),

    kui lõpukuupäeva pole määratud siis otsing kuni viimati avaldatud uudiseni;
    kui alguskuupäeva pole määratud siis alates esimesest uudisest.

sildi (tag) järgi (Vali uudise silt) - avaneb lingi alt "Täpsem otsin

-----------------
Mitte sellesse piletisse puutuv õiendus mobiili ja tahvlivaates

Kuna parema menüüsisu liigub alla, siis on "vaata kõiki" ja "kõik uudised" sisud? ja funktsioon duplikeeritud. Kui menüü liigub alla, siis "Vaata kõiki" ei pea kuvama?

![2x](https://user-images.githubusercontent.com/37407917/40482865-cf60a79e-5f5e-11e8-8c26-5a33e89a2ce2.png)

**Comment by birgitpulk** [comment]
Millal sellised nupud sinna alla üldse tekivad? Miks ei võiks kõiki filtreeringu tulemusi välja kuvada? Või siis sama loogikaga, et kuvab mingi osa ja siis on nupp "Lae rohkem" nagu on meil uudise listvaates. @TanelTromp @andrussarv

**Comment by TanelTromp** [comment]
@birgitpulk see ei ole otsingu/filtri tulemuste vaade, vaid "uudiste nimekirja vaade" (vt > Mitte sellesse piletisse puutuv õiendus mobiili ja tahvlivaates)

**Comment by birgitpulk** [comment]
Aga siis peaks seal ikkagi olema ainult nupp "Lae rohkem"? @TanelTromp

**Comment by TanelTromp** [comment]
Mina ei paneks, jätaks ainult "kõik uudised". Sest, "mida" ta rohkem laeb? @birgitpulk

**Comment by birgitpulk** [comment]
Samas võiks kasutada sarnaseid nuppe/mustreid üle lehe. @andrussarv  äkki kommenteerib?

**Comment by birgitpulk** [comment]
Viga2: Väljale klikkides peaks avanema kalender (nagu hetkel avaneb) ja kasutajal peab olema ka võimalus trükkida kuupäev, aga kui ta trükib kuupäeva, siis kuupäeva trükkimisel võiks süsteem ise / numbrite vahele panna. 

Viga 6: kui kasutaja vajutab "ENTER" peab see aktiveerima otsingu. Otsing aktiveeritakse ka "Otsi" nupuga. 

Viga 7: Süsteem peaks saama aru sõnadest ka erinevas järjekorras.

@doomler

**Comment by doomler** [comment]
viga 1: fixed
viga 2: waiting for material desighn
viga 3: fixed
viga 4: fixed
viga 6: fixed, now user can submit the form with enter, (user can’t submit the form with enter when reaches the tag input, because of  autocompletion it used enter key too)
viga 7: need to change the logic
viga 8: SEO - need to add url search, WCAG - viga 6,

**Comment by TanelTromp** [comment]
Viga 5: veel üleval, mis juhtub, kui kasutaja nii sisestab. Kuvab veateate ja millise ning kuidas?

**Comment by heldiraudsepp** [comment]
Tehti korda koodi paranduste pileti raames https://github.com/hariduspilv/haridusportaal/issues/282

**Comment by TanelTromp** [comment]
Seotud piletiga: https://github.com/hariduspilv/haridusportaal/issues/377
