### ISSUE TITLE
Teavituse tellimist kinnitav e-kiri

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#157]
**Eesmärk, üldkirjeldus**
Portaali külastaja saab sildi alusel tellida teavitusi uudise ja sündmuse kohta.

**Eeltingimused ja käivitamine**
Realiseeritud on pilet #106 

**Vastuvõtutingimused:**
Kasutaja sisestatud e-posti aadressile laekub tellimuse kinnitamiseks e-kiri (vt all)
Kasutaja saab tellimuse kinnitada (testitakse piletis #160).
Tellimusele lisatakse unikaalne räsi (testitakse piletis #132 ja #108)

**E-kirja päis**
From: ?
To: tellimuse e-posti aadress
Subject: _Uudiskirja tellimuse kinnitamine_

**E-kirja sisu**
_Tere!_
_Tänud haridusteemade vastu huvi tundmast. Aadressile [tellimuses märgitud e-posti aadress] on tellitud teavitused teemadel: [loetelu tellimuses vormistatud siltidest tähestikulises järjestuses A-Z]._

_Tellimuse kinnitamiseks palun vajutage seda linki [kinnita minu tellimus]._

E-kirja jalus:
_Kui Te pole teavitust tellinud või soovite sellest loobuda, siis vajutage seda linki [Siia unsubscribe link]._

Planeerimiselt: Selle töö raames lisada ka "luud", mis eemaldab kinnitamata tellimused.
Kui tellimus pole kinnitatud 30 päeva jooksul, siis süsteem kustutab tellimuse ja kasutaja ei saa saadud e-kirja alusel tellimust kinnitada. "Luua" aeg peab olema seadistatav.

**Viited seotud teemadele:**

Siltide toimetamine: #13
Siltide tellimine: #106 ja #160 
Siltide alusel teavituste e-mailile väljastamine #14
Siltide alusel teavituse tellimuse lõpetamine (unsubscribe) #108
Siltide alusel teavituse tellimuse muutmine #132
Siltide alusel teavituste tellimuste haldamine #107

**Comment by TanelTromp** [comment]
Vastuvõtutingimused:
- [ ] Kasutaja sisestatud e-posti aadressile laekub tellimuse kinnitamiseks e-kiri (vt all)
- [ ] Kasutaja saab tellimuse kinnitada (testitakse piletis #160).
- [ ] Tellimusele lisatakse unikaalne räsi (testitakse piletis #132 ja #108)

- [ ] E-kirja päis
From: ?
To: tellimuse e-posti aadress
Subject: Uudiskirja tellimuse kinnitamine

- [ ] E-kirja sisu
Tere!
Tänud haridusteemade vastu huvi tundmast. Aadressile [tellimuses märgitud e-posti aadress] on tellitud teavitused teemadel: [loetelu tellimuses vormistatud siltidest tähestikulises järjestuses A-Z].

Tellimuse kinnitamiseks palun vajutage seda linki [kinnita minu e-posti aadress].

- [ ] E-kirja jalus:
Kui Te pole teavitust tellinud või soovite sellest loobuda, siis vajutage seda linki [Siia unsubscribe link].

- [ ] Planeerimiselt: Selle töö raames lisada ka "luud", mis eemaldab kinnitamata tellimused.
Kui tellimus pole kinnitatud 30 päeva jooksul, siis süsteem kustutab tellimuse ja kasutaja ei saa saadud e-kirja alusel tellimust kinnitada. "Luua" aeg peab olema seadistatav.

**Comment by lsoonvald** [comment]
Luua kohta loodud eraldi issue:
