### ISSUE TITLE
Tellimuse kinnitamise kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#160]
**Eesmärk, üldkirjeldus**
Teavituse tellija kinnitas tellimuse e-kirja lingi kaudu. Mille tulemusel kuvatakse tellimuse kinnitamise teadet.

**Eeltingimused ja käivitamine**
Realiseeritud on pilet #106 ja #157 
Kasutaja sisestatud e-posti aadressile laekus tellimuse kinnitamiseks e-kiri (pilet #106)
Kasutaja kinnitas tellimuse (pilet #157)

**Vastuvõtutingimused:**
- [ ] Kui kasutaja vajutab tellimuse kinnitamise linki (#157), siis
kasutajale kuvatakse haridusportaali URL aadressiga lehte teatega:

_Tänud haridusteemade vastu huvi tundmast! Olete edukalt liitunud uudiskirjaga._

Kujundus: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1107b1e43bcefd6a6ef400

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Viited seotud teemadele:**

Siltide toimetamine: #13
Siltide tellimine: #106 ja #160
Siltide alusel teavituste e-mailile väljastamine #14
Siltide alusel teavituse tellimuse lõpetamine (unsubscribe) #108
Siltide alusel teavituse tellimuse muutmine #132
Siltide alusel teavituste tellimuste haldamine #107

**Comment by lsoonvald** [comment]
Angulari poolt saata Drupali GraphQL päringu peale emaili hash, millega genereeritakse emailile saadetav link, et aktiveerida tellimus.

**Comment by heldiraudsepp** [comment]
BE - 4
FE - 8
Test - 2
