### ISSUE TITLE
Sündmuste juhend lõppkasutajatele

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#164]

**Comment by TanelTromp** [comment]
[Haridusportaal kasutusjuhend lõppkasutajale.docx](https://github.com/hariduspilv/haridusportaal/files/1969927/Haridusportaal.kasutusjuhend.loppkasutajale.docx)

Kas on vajadus ka WIKIsse kasutusjuhend konvertida?

**Comment by TanelTromp** [comment]
p.s tulevikus siis Material Design adminiipaneel ikka, selle muudame ka ära pärast. Lihtsalt stiilinäiteks
