### ISSUE TITLE
Dokumendivormil teadete kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#172]
- [x] Kuvada body.messages.message_text
- [x] Kuvada step.messages.message_text, mis sisalduvad avatuna olemas sammus.
- [ ] Kuvada teated visuaalselt vastavalt sellele, kas message_type on NOTICE, WARNING või ERROR
- [x] Keele valiku arvestamine: teate tekst kuvada kasutaja valitud keeles. Kui dokumendis pole kasutaja poolt valitud keeles teksti, siis kuvada vaikekeeles (eesti keeles - 'et') tekst.

[Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b3f0fe5527f910aa2354b9f)

**Comment by andrussarv** [comment]
- [ ] "Kuvada step.messages.message_text, mis sisalduvad avatuna olemas sammus.". Praegu kuvab igas sammus sisalduvad message-d.

**Comment by RaimoJohanson** [comment]
Nüüd kuvab üldiseid sõnumeid + sammupõhiseid sõnumeid
