### ISSUE TITLE
Uudise detailvaate muutmine kujunduse alusel

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#176]
Algne uudise detailvaate pilet: https://github.com/hariduspilv/haridusportaal/issues/95

Muuta vastavalt kujundusele: zpl://screen?sid=5af04a45a283fe7a7e65bf89&pid=5ae9c7f3c560dffb217da75c

"Loe veel" asemel on "Viimased uudised"
Kuvatakse:

- foto (picture)    
- pealkiri (title)
- "Loe rohkem", mis avab uudise detailvaate.

**Comment by EgleM-TW** [comment]
Kui ei jõua see sprint, siis liigub järgmisesse.

**Comment by heldiraudsepp** [comment]
#256 on tööd
