### ISSUE TITLE
Uudise sisestamise piirangud

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#179]
Täiendada uudise toimetamist https://github.com/hariduspilv/haridusportaal/issues/11 järgmiste piirangutega: 
* Pealkiri (title), kohustuslik,  **maksimaalne pikkus 50 tähemärki** 
* Autor (author), kohustuslik, **maksimaalne pikkus 25**
* Kuupäev (date) automaatselt avaldamise kuupäev, kohustuslik_
* Sissejuhatus (shortDescription), kohustuslik, **maksimaalne pikkus 500, plain-text**
* Avafoto (introductoryPicture) ja täiendavad fotod (picture):  avafoto on kohustuslik; saab lisada suvalisel arvul täiendavaid fotosid; **iga foto sisaldab osasid: pildifail, pealkiri, alt-tekst;  kõik osad on kohustuslikud, pealkirja maksimaalne pikkus 50, alt-teksti maksimaalne pikkus 500**
* Sisutekst (fullDescription), kohustuslik
* Sildid (Tag), vabatahtlik,valik siltide taksonoomiast, **saab lisada kokku kuni 4 silti**  
* Lingid (Link), vabatahtlik, lingi pealkiri ja URL, **lingile pealkirja sisestamine kohustuslik, pealkirja maksimaalne pikkus 50**

**Comment by ruut12** [comment]
*Piltidele ei saa määrata tiitli ja alteksti maksimaalset tähtedearvu
*Linkide tekstile ei saa määrata maksimaalset tähtedearvu

**Comment by TanelTromp** [comment]
Viga 1: 
![pilt](https://user-images.githubusercontent.com/37407917/40175321-65711bf8-59e0-11e8-92f4-1933d0a81f78.png)

Sisestatud on õigesti, vastavalt näitele:

![pilt](https://user-images.githubusercontent.com/37407917/40175345-78d00c54-59e0-11e8-8c62-35d725d57767.png)

**Comment by ruut12** [comment]
Viga1: Korras
