### ISSUE TITLE
Sündmuse sisestamise piirangud

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#180]
Sündmuse toimetamist https://github.com/hariduspilv/haridusportaal/issues/1 täiendada järgmiste piirangutega:

- Nimetus - name, **kohustuslik, maksimaalne pikkus 50**
- Sündmuse tüüp - type, valik sündmuse tüüpide (EventType) taksonoomiast , **kohustuslik**
- Sildid - tag,  valik siltide tüüpide (Tag) taksonoomiast, **saab lisada kuni 4 silti**
- Lühikirjeldus - descroption.summary, **kohustuslik, maksimaalne pikkus 300, plain-tex**
- Pilt - picture; vabatahtlik; **pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; kõik osad on kohustuslikud**
- Kirjeldus - description.value, **kohustuslik**
- Sündmusega seotud lingid - webPageLink, võib olla mitu, **igal lingil pealkiri ja URL, mis mõlemad on kohustuslikud**
- Lisatud failid - attachmentFile, võib olla mitu, **igal manuse faili pealkiri ja fail, mis mõlemad on kohustuslikud**
- Toimumise koha nimetus - location.name, **maksimaalne pikkus 50**
- Toimumise koha aadress - location.address, **maksimaalne pikkus 50**
- Toimumise koha asukoht kaardil - location.map,
- Toimumise koha asukoha veebileht - location.webpadeAddress,
- Korraldaja - organizer, **maksimaalne pikkus 50**
- Kontaktisik - contactPerson,  **maksimaalne pikkus 50**
- Kontakttelefon - contactPhone, **telefoni formaat**
- Kontakt e-posti aadress - contactEmail, **e-maili formaat**
- Sissepääsu liik - entryType (valik: kutsetega, vaba sissepääs, registreerimine nõutud), **kohustuslik**
- Registreerimise alguse kuupäev - registrationFirstDate, **kohustuslik, kui sissepääsu liik on "registreerimine nõutud"**
- Registreerimise lõpu kuupäev - registrationLastDate, **kohustuslik, kui sissepääsu liik on "registreerimine nõutud"**
- Registreerimiste teavitamise e-posti aadress - registrationNotificationEmail,
- Registreerimiste kinnitamise e-posti tekst - registrationConfirmationEmailText,
- Osalejate maksimaalne arv - maxNumberOfParticipants, 
- Osalejatele praktiline info - practicalInformation, **maksimaalne pikkus 500; sisestamiseks üldised redaktori nõuded https://github.com/hariduspilv/haridusportaal/issues/15, välja arvatud see, et heading pole lubatud**

Sündmuse toimumise aeg (peab olema vähemalt üks toimumisaeg, võib olla mitu):
- Toimumise kuupäev - eventDate, **kohustuslik**
- Alguse kellaaeg - startTime, **kohustuslik**
- Lõpu kellaaeg - endTime, **kohustuslik**

**Comment by ruut12** [comment]
* location.webpadeAddress - lisatud (sündmuse toimetamise ticketis väli puudus)
* Samuti ei saa määrata piiranguid väljadele mis on taskis #179

**Comment by TanelTromp** [comment]
Viga 1: puudu väli:
Registreerimiste teavitamise e-posti aadress - registrationNotificationEmail,

Viga 2: puudu väli: 
Toimumise koha asukoha veebileht - location.webpadeAddress,

**Comment by Kyllike** [comment]
#180_HTM

Viga?: sündmuse kuupäevana lubatakse sisestada mineviku kuupäev:
![image](https://user-images.githubusercontent.com/38042389/40619187-cb1b404a-629c-11e8-8fca-24ba395a5231.png)

Kas siin ei peaks olema kontrolli, et sündmus peab toimuma tulevikus?

@heldiraudsepp

**Comment by heldiraudsepp** [comment]
@Kyllike Analüüsis eraldi sellist nõuet ei ole. Arutasime siin ja pigem ei lisaks seda piirangut, sest võib tekkida olukord, kus soovitakse sisestada ehk ka juba toimunud sündmusi, et need portaali kaudu kättesaadavaks jääksid.

**Comment by Kyllike** [comment]
@Heldi Ok, hakkasin ise ka sinnapoole mõtlema.
