### ISSUE TITLE
Dokumendivormil email tüüpi andmeelement

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#186]
**"email"** tüüpi andmeelemendi esitamine on sarnane "text" andmeelemendi esitamisega (vt #174).

**Comment by andrussarv** [comment]
- [ ] Kui valuie on tühi (ja pole required), siis ei peaks e-maili aadressi formaati kontrollima. Praegu on nii, et tühja välja peale annab "palun sisesta õige e-maili aadress" veateate.

**Comment by RaimoJohanson** [comment]
Viga parandatud
