### ISSUE TITLE
Artikli sisulehe (alamlehtedega) detailvaade 

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#19]
**Sprint 8 debuggimine IE11 vead**

**Eesmärk, üldtingimused:**
Portaali külastaja saab menüü või mõne muu sisulehe lingi kaudu navigeerida „TypeOneArticlePage“ mallil sisulehele ja tutvuda selle sisuga.

**Eeltingimused ja käivitamine:**
- realiseeritud on pilet #128 (sisu toimetamine)
- realiseeritud on piletid #138 ja #139 (parema veeru elemendid)
- kasutaja navigeerib menüüst „TypeOneArticlePage“ mallil sisulehele

**Vastuvõtutingimused:**

1. Kasutajale kuvatakse lehekülje sisu.
2. Kasutaja saab avada-lugeda-sulgeda sisulehe alamlehti (accordion) - näidis lisatud kujunduse vaates.
3. Kasutaja näeb lehe parema serva vidinaid vastavalt reeglitele, mis on piletis #139.

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Kujundus: 
[https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afae7ba6a3720641549739e](https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afae7ba6a3720641549739e
)
Mobiilis: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbfe2e6b31722f05e1c331

Viited:
back-end töö #128 
parema serva vidinad: #139 ja #138

**Comment by TanelTromp** [comment]
Vearaport #19_2

Tegevuse üldine kirjeldus: artikli sisulehe (alamlehtedega) detailvaade FE
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66.0; Mozilla 59.0; Edge 41; IE 11 + Windows 10, 64b

    LG 3840 x 2160 px (UHD)
    1920 x 1080 px (Laptop)
    Seadmed:
    iOS 11.3 iPhone 6s + Safari
    Lenovo thinkpad + Chrome + Windows 8
    Android 7.0 Samsung Galaxy A5 + Chrome


Viga 1: ei kuva akordionis linke

![pilt](https://user-images.githubusercontent.com/37407917/41336385-c9dbbc82-6ef4-11e8-8fb2-55c488928b20.png)

Viga 2: lingid peavad avanema uuel kaardil, mitte samas aknas nagu hetkel. (Kommentaar: FE peab arvestama, kas tegu on inbound või outbound lingiga, sest D8-s on see kirjas)

Viga 3: peapilt ei scalei ennast väikseks koos tekstida, kui zoom-outida brauseris.
![pilt](https://user-images.githubusercontent.com/37407917/41337202-3e00b6c4-6ef7-11e8-9ed6-0714ca664f77.png)

Viga 5: IE 11 vaade on tühi

Viga 6: Edge 41 vaade on bugine:

![pilt](https://user-images.githubusercontent.com/37407917/41338056-b1cd40e8-6ef9-11e8-9814-76a15d55ca56.png)

Viga 4: "täiendavad tingimused" SEO, WCAG linnukesed tegemata.

Täpsustus 1: sildid/tags on kujunduses olemas aga need läksid maha viimase info põhjal?

Õiendus 1: kuigi disainis ei ole mobiilivaates "Kontakt" sektsioonis telefoninumber link, siis palun jätta nagu hetke koodis on ehk see on alates tablet foldist link.

@madispold

**Comment by madispold** [comment]
Viga 1: Lingid lisatud.
Viga 2: Peab sisuhalduse poolelt lisama atribuudi juurde, et väline link.
Viga 3: Nüüd sisu suureneb resolutsiooni suurenemisel.
Viga 4: SEO, WCAG lisandunud.
Viga 5: IE 11 tugi polnud nõue.
Viga 6: Edge ei ole hetkel võimalik testida.

Silte ei tule artikli vaatesse.

**Comment by TanelTromp** [comment]
- [ ] Viga 1: Lingid lisatud.
- [ ] Viga 2: Peab sisuhalduse poolelt lisama atribuudi juurde, et väline link.
- [ ] Viga 3: Nüüd sisu suureneb resolutsiooni suurenemisel.
- [ ] Viga 4: SEO, WCAG lisandunud.
- [ ] Viga 5: IE 11 tugi polnud nõue.
- [ ] Viga 6: Edge ei ole hetkel võimalik testida.

**Comment by TanelTromp** [comment]
Viga 1: IE 11 artikli detailvaade katki:
![pilt](https://user-images.githubusercontent.com/37407917/41731649-90572548-7587-11e8-8101-ee284c6df17b.png)

Viga 2 IE 11: artikli detailvaates ei tööta menüüpuu
https://gyazo.com/8abbbdf18335265ab89a61bd7f535862

Viga 3: EDGE pilt endiselt detailvaates katki

@madispold

**Comment by madispold** [comment]
Edge/IE pildid ja alt text parandatud.
IE menüü parandatud.

**Comment by TanelTromp** [comment]
Viga 6: Edge ja IE-ga akordioni stiilid katki:

![pilt](https://user-images.githubusercontent.com/37407917/41890156-e60c49fe-7916-11e8-9db7-b5d7c2267a89.png)

@madispold

**Comment by madispold** [comment]
@TanelTromp parandatud.

**Comment by TanelTromp** [comment]
OK!
