### ISSUE TITLE
Artikli ja Uudise sisulehe kuvamine: kui parem ääreriba on täitmata siis sisuosa suurus ei muutu.

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#191]
Eesmärk: muudatus piletite #139 ja #95 desktop vaate kuvamisel.

Vastuvõtutingimused:
#139
Kui parema ääreriba elemente pole lisatud, jääb see osa tühjaks ning sisuosa suurus ei muutu (ei kata tervet lehekülge).

#95
Kui "Loe veel" veerg on tühi, siis uudise sisuosa suurus ei muutu.

Täiendavad tingimused:
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by TanelTromp** [comment]
Vearaport #191_1

Tegevuse üldine kirjeldus: ääreriba käitumine eri seadmetega UI-s
Testimise tegevused: funktsionaalsete nõuete testimine, mittefunktsionaalsete nõuete testimine

Brauserid: Chrome 66.0; Mozilla 59.0; Internet Explorer 11 + Windows 10, 64b

LG 3840 x 2160 px (UHD)
1920 x 1080 px (Laptop)
Seadmed:
iOS 11.3 iPhone 6s + Safari
Lenovo thinkpad 1366 x 768px + Chrome + Windows 8
Android 7.0 Samsung Galaxy A5 + Chrome

Viga 1: Linnukesed tegemata:

![pilt](https://user-images.githubusercontent.com/37407917/40052979-472d326a-5848-11e8-80e4-b754dab7d4e8.png)
@doomler
