### ISSUE TITLE
Breadcrumbs kõikidel sisulehtedel

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#194]
**Eesmärk:**
Kõikide sisulehtede tüüpidel ja sellest tulenevalt kõikidel kasutaja poolt loodavatel sisulehtedel on olemas breadcrumbs ehk leivapuru ehk jäljerida, mis indikeerib lõppkasutajale, kus konkreetne leht asub menüüpuus.

**Vastuvõtutingimused:**
1. Kõikidel loodud sisulehtedel (uudis, artikkel…) on olemas breadcrumbs ehk leivapuru ehk jäljerida. 
2. Breadcrumbs ehk leivapuru indikeerib menüüpunkti, kus kasutaja parasjagu asub.
3. Bredcrumbs on klikitav kuni avatud leheküljeni, nt uudise detailvaates Avaleht ja Uudised viivad vastavalt avalehele või uudiste nimekirja vaatesse, aga uudise detailvaade ei ole klikitav.

Täpsustused:
Uudise detailvaade: Avaleht > Uudised > Uudise pealkiri
Uudise nimekiri: Avaleht > Uudised 
Sündmuse detailvaade: Avaleht > Sündmused > Sündmuse pealkiri
Sündmuse nimekiri: Avaleht > Sündmused
Artikli (sisulehe) vaade: Avaleht > Menüüpunkti pealkiri > Artikli pealkiri

**Täiendavad tingimused:**

- [x]  [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x]   [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x]   [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Kasutajaliidese eskiis:

**Comment by Kyllike** [comment]
#194_HTM
Viga 1: Vastavalt kirjeldusele tuleb breadcrumbsis kuvada sisuartikli teekond järgnevalt:
Artikli (sisulehe) vaade: Avaleht > Menüüpunkti pealkiri > Artikli pealkiri

Kuvast on puudu menüüpunkti pealkiri:

![image](https://user-images.githubusercontent.com/38042389/40618468-3dae2ff8-629a-11e8-88d1-f6befda2f6ab.png)

Viga 2:  Vastavalt kirjeldusele tuleb breadcrumbsis kuvada sündmus järgnevalt:Sündmuse detailvaade: Avaleht > Sündmused > Sündmuse pealkiri
Ei kuvata "Sündmused"
![image](https://user-images.githubusercontent.com/38042389/40618598-ac166802-629a-11e8-850e-8f9b526ce5ef.png)

@heldiraudsepp

**Comment by ruut12** [comment]
@Kyllike 
Leivapurus on puudu lingid kuna need ei saa kuskile viidata.
Puudub leht mis viitaks /opitee või /sundmused

**Comment by TanelTromp** [comment]
TEST

Viga 1: breadcrumbsi sisu ei muutu, kui uudiste/sündmuste/erialade detailvaates paremast veerust teine uudis valida:
https://gyazo.com/b692ceb1c8e9b4f49608abc11df589bc

**Comment by skeefee** [comment]
Viga 1: Korras
@TanelTromp
