### ISSUE TITLE
Tekstiredaktori pealkirja stiilid

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#195]
**Eesmärk:**
Kõikides tekstiredaktorites on kasutajal võimalik valida ainult pealkirja stiili H3, mis on 16px (em,rem?) teksti suurusega ning bold. Antud pealkirja stiili saab kasutada teksti sees olevate vahapealkirjade loomiseks (nt artikli, uudise detailvaates).

**Vastuvõtutingimused:**
Kõikides tekstiredaktoriga sisestusväljadel on pealkirjade alt võimalik valida ainult H3 pealkirja (16px bold), millega saab luua vahepealkirju teksti sisse. 

**Täiendavad tingimused:**
UI nõuded, sh Material Design
SEO
WCAG

**Comment by TanelTromp** [comment]
Viga 1: H3 ei ole hetkel 16px, vaid 18.72px
