### ISSUE TITLE
Sündmusel osalemise registreerimine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#2]
**Teha veel koodi optimeerimine #282**

**Üldkirjeldus:**
Portaali kasutaja registreerub sündmusel (Event) osalejaks (EventParticipant).

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud sündmuse detailvaade (https://github.com/hariduspilv/haridusportaal/issues/100), millelt kasutaja käivitab sündmusel osalemise registreerimise. 
* Sündmusele registreemise käivitamine on võimalik (muul juhul pole registreerumise nuppu näha), kui:
-- entryType = "registreerimine nõutud" ja 
-- (registrationFirstDate <= jooksev kuupäev) ja
-- (registrationLastDate >= jooksev kuupäev) ja
-- (registreeritud osalejate (EventParticipant) arv < maxNumberOfParticipants või maxNumberOfParticipants on määramata).

**Vastuvõtutingimused:**
* Sündmuse registreerimise vormil on näha sündmuse pealkiri, alguse kuupäev ja kellaaeg selleks, et kasutaja saaks olla veendunud, kas ta registreerub õigele sündmusele.
* Kasutaja sisestab osaleja andmed:
-- osaleja eesnimi: participantFirstName; kohustuslik,
-- osaleja perekonnanimi: participantLastName; kohustuslik,
-- ettevõte või asutus - participantOrganization,
-- e-posti aadress - participantEmail; kohustuslik,
-- telefoni number - participantPhone,
-- märkused - comment.
* Süsteem loob uue osaleja kirje (EventParticipant) ja salvestab sinna sisestatud andmed ning registreerumise kuupäev ja kellaja (registrationDateTime).  vt ka #259.
* Süsteem kuvab kasutajale registreerimise kinnituse "Täname sündmusele registreerimise eest".
* Kasutaja saab käivitada sündmuse enda kalendrisse saatmise - vt #26.

* **_Katkesta:_** Kasutaja saab registreerumise katkestada. Süsteem sulgeb modaalakna.

**Täiendavad nõuded**:
* Captcha kasutamine.
* Osaleja andmete sisestamise ja salvestamise realiseerimise Drupal-i veebivormina.
* SQL Injection ja Cross-site scripting vältimine.

**Kasutajaliidese eskiis:**
- Registreerimisvorm (sündmusele registreerimine) [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b028772c9c86cdf1eac582d), [Disaini link: error ja edukas protsess](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b0289a4c2fcab5116a619aa), [Disaini link: aitäh](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b045a86d08ed737014f7714)
- Registreerimisvorm (sündmusele registreerimine) mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b028771a7c95c5e217822ed)

**Comment by heldiraudsepp** [comment]
Tuleb juurde teavitusteksti saatmine BE'st

**Comment by heldiraudsepp** [comment]
Loader ja error handling juurde 9ndas sprindis

**Comment by skeefee** [comment]
Saab testida @MirellKr2

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: sündmusel osalemise registreerimine portaali ja Drupali veebivormi kaudu.
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 67; Mozilla 61.0.1; Edge 41; IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Windows tablet Thinkpad
Keskkond: http://htm.twn.ee/

**Viga 1:** pärast korrektset andmete sisestamist registreerumisvormil ja vormi andmete saatmist kuvatakse laadimine kestusega 10 sekundit ning avaneb uuesti täidetud andmetega registreerumisvorm, st ei kuvata registreerumise kinnitust, kuid kinnitus e-mail saadetakse välja. Ei saa testida sündmuse kalendrisse saatmist.

@ruut12 @lsoonvald 

**Viga 2:** registreerumisvormil ei ole realiseeritud Captcha't.

@skeefee 

**Viga 3**: registreerumisvorm kuvatakse mobiilis poolikult, st sündmuse pealkirja ei kuvata täielikult välja, samuti ei kuvata vormi andmete edastamise ja tühistamise nuppusid. Vorm avaneb väikese viitega, sama kehtib vormi avamise kohta Windows tahvlis.

**Viga 4**: ei ole realiseeritud piirangut, mille kohaselt registreeritud osalejate (EventParticipant) arv < maxNumberOfParticipants või maxNumberOfParticipants on määramata. Saab registreerida rohkem osalejaid kui on määratud sündmuse osalejate maksimaalseks arvuks. Kas Drupali veebivormi ja portaali kaudu registreerujaid peaks arvestama? St et arvestatakse mõlema vormi kaudu registreerujate arvu, mis peab olema väiksem sündmuse maksimaalsest osalejate arvust,

**Viga 5**: registreerimisvormi kujundus on IE 11 ja Edge brauserites paigast ära.

![image](https://user-images.githubusercontent.com/37401947/42933577-c38a34b0-8b4d-11e8-81f0-30bffe54d058.png)
_Pilt IE 11_

![image](https://user-images.githubusercontent.com/37401947/42933612-d7601cac-8b4d-11e8-8160-84c43706eb33.png)
_Pilt Edge 41_

**Viga 6**: registreerimise lõpu kuupäev ei saa antud pileti tingimuste järgi olla väiksem tänasest/jooksvast kuupäevast. Samuti ei peaks saama registreeruda, kui sündmuse registreerimise alguskuupäev on tänasest suurem.

**Comment by ruut12** [comment]
BE poolelt lisatud osalejate arv GraphQl'i fieldina. - 2h30m

**Comment by MirellKr2** [comment]
**Viga 1**: korras, kuid registreerumise kinnituse kuvamine võtab aega ca 6 sek (probleem seisneb meiliserveris, vajab edasistes sprintidest paremat lahendust).

**Viga 2**: captcha olemas, kuid selle välimus vajab üle vaatamist (hägune, inglisekeelne, avaneb modaalakna peal (?)). Kuidas see mobiilis peaks töötama? Ei saanud seda testida.

![image](https://user-images.githubusercontent.com/37401947/44206222-cd1e1300-a161-11e8-9469-b6e21dc10d7b.png)

**Viga 3**: iPhone-s kuvab vormi endiselt poolikult.

**Viga 4**: piirangut ei ole FE poolel realiseeritud.

**Viga 5**: registreerimise nuppu ei kuva õigesti

![image](https://user-images.githubusercontent.com/37401947/44207434-eb860d80-a165-11e8-9bb9-7ed26ddeede8.png)

**Viga 8**: sündmuse enda kalendrisse saatmine ei käivitu.

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 1: Korras
Viga 1: Korras
Viga 1: Korras
Viga 1: Korras

**Comment by skeefee** [comment]
Viga 3: Korras @TanelTromp

**Comment by TanelTromp** [comment]
The Return of The Jedi:

Viga 1: registreeru nupp ei tööta (muutsin põhikuupäeva ja registreerumiste kuupäevi):

https://gyazo.com/ad6fb3307d0e80f427d30a4cd1e4fde5

(Võib seotud olla selle big collapsiga, mis uus sündmuse lisamisel hetkel tekkis.)

**Comment by skeefee** [comment]
Korras

**Comment by TanelTromp** [comment]
Viga 2: recaptcha katki:

![pilt](https://user-images.githubusercontent.com/37407917/44780424-934e0300-ab8a-11e8-8bb6-2a7bfa83d037.png)

Viga 2: "F":

![pilt](https://user-images.githubusercontent.com/37407917/44780749-559daa00-ab8b-11e8-9dee-aa9207361a53.png)

Viga 3: lõppemise kuupäev sama, mis alguse (BE-s sisestatud 18:00):

![pilt](https://user-images.githubusercontent.com/37407917/44780825-8a116600-ab8b-11e8-882f-6006b1f5ca9a.png)

Viga 4: "saada nupu" fondivärv on must, peab olema valge sellele liikumisel (nagu Zeplinis):
https://gyazo.com/1abe50cbc4987241c9102e036bef0e04

**Comment by TanelTromp** [comment]
TESTLUGU:

http://htm.twn.ee/et/sundmused/sundmusel-osalemise-registreerimine-2-pilet

Viga 9: kui BE-s on "maxNumberOfParticipants on määramata", siis kuvab "Sündmuse registreerimise kohad on täis". Peaks saama lõpmatult regada.

Viga 10: saab küll modaalilt valida, et "lisa sündmus enda kalenderisse" aga midagi ei juhtu - puudub "ical" kalendrisse saatmise võimalus (pole märget "registreeru all")

_Kasutaja saab käivitada sündmuse enda kalendrisse saatmise - vt #26._

Viga 11: kuigi BE-s on määratud max registeerujate arv (2), siis ilma lehte uuendamata, saab lõputult samas aknas registreeruda.

Viga 12: veateade on eesti keelne: EN keelevalikus "Sündmusele registreerimine on lõppenud"

Viga 13: "tühista" EN keelevalikus:

![pilt](https://user-images.githubusercontent.com/37407917/44795220-de7c0c00-abb2-11e8-9b32-7dc6fb04224c.png)

Viga 14 (kas muusse pilettisse?): kui vahetada keelt (sündmus on loodud mõlemas keeles), siis viskab nimekiri vaatesse, peaks jääma sama sündmuse detailvaatesse.

**Comment by skeefee** [comment]
Viga 9: Korras
Viga 10: Korras
Viga 11: Ootame BE järgi @ruut12 
Viga 12: Frontendis korras. Vaja tõlkida administ
Viga 13: Frontendis korras. Vaja tõlkida administ
Viga 14: Korras

@TanelTromp

**Comment by TanelTromp** [comment]
Viga 14:  https://gyazo.com/e7698c35b344988b7b61e0efa9f5b142

**Comment by TanelTromp** [comment]
Viga 9: olemas EN keelesuunal.

![pilt](https://user-images.githubusercontent.com/37407917/44848732-91ef0a00-ac60-11e8-9cfe-a025cbe72044.png)

**Comment by TanelTromp** [comment]
Viga 15: BE-s näitab valet sündmuse nime - kuigi registreering on tehtud "ENG" versioonist ja keelevahetusest (õige sündmuse nimi on ENG lõpuga):

![pilt](https://user-images.githubusercontent.com/37407917/44854541-7c361080-ac71-11e8-8aec-cd5cc1c33d74.png)

**Comment by TanelTromp** [comment]
Viga 11: _Ootame BE järgi_ BE korras. @skeefee
