### ISSUE TITLE
Uudisele ja „TypeOneArticlePage“ mallil sisulehele video lisamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#204]
Eesmärk: 
Täiendada uudise ja „TypeOneArticlePage“ mallil sisulehe toimetamist video lisamisega.

Vastuvõtutingimused:
- [ ] Uudise sisestamisel saab lisada uudise detailvaates kuvatava video URL-i (0..1)
- [ ] „TypeOneArticlePage“ mallil sisulehele saab lisada sisulehel kuvatava video (0..3)

Testime front-end pileti kaudu #205 

Viited:
uudise toimetamine #11 
„TypeOneArticlePage“ mallil sisulehe toimetamise täiendused #181
Kujundus #275

**Comment by ruut12** [comment]
Hetkel valideeritakse ainult youtube erinevaid linke

**Comment by TanelTromp** [comment]
Vastuvõtutingimused:
- [ ] Uudise sisestamisel saab lisada uudise detailvaates kuvatava video URL-i (0..1)
- [ ] „TypeOneArticlePage“ mallil sisulehele saab lisada sisulehel kuvatava video (0..3)

**Comment by EgleM-TW** [comment]
21.06 lisatud disaini alusel allteksti lisamise võimalus, vabatahtlik.

**Comment by TanelTromp** [comment]
- [x] 21.06 lisatud disaini alusel allteksti lisamise võimalus, vabatahtlik.
