### ISSUE TITLE
Uudisele ja „TypeOneArticlePage“ mallil sisulehele kuvamine koos videoga

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#205]
**Eesmärk, üldkirjeldus:**
Kui sisutoimetaja on Uudisele või „TypeOneArticlePage“ mallil sisulehele lisanud video, siis seda kuvatakse veebi külastajale.

**Eeltingimused ja käivitamine:**
Kasutaja on avanud:
- Uudise detailvaate, millele on lisatud video (0..1)
- „TypeOneArticlePage“ mallil sisulehe, millele on lisatud video (0..3)

**Vastuvõtutingimused:**
- [x] 1. uudise detailvaates kuvatakse video, mille saab käivitada;
- [x] 2. „TypeOneArticlePage“ mallil sisulehel kuvatakse video, mille saab käivitada.

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kujundus:** #275 

**Viited:**
back-end #204

**Comment by heldiraudsepp** [comment]
@skeefee täpsustab mahu peale @erkkijakobson sisendi saamist

**Comment by madispold** [comment]
@TanelTromp testimisse.

**Comment by madispold** [comment]
Viga 1: Täiendatud ja võimalik lisada kuni 3 videot.
Viga 2: D8 poolne n.ö viga - eraldi elemendid ka sisuhalduses ja seal tõlgitavad väljad need. Lisaks kas eri keelte alla ei pandaks ka eri videoid?

**Comment by TanelTromp** [comment]
OK
