### ISSUE TITLE
Tõlked

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#207]
Asendada hardcodetud sildid tõlgetega:
Uudise listvaade
Uudise detailvaade
Artikli detailvaade
Sündmuse list
Sündmuse detailvaade
Avalehele uudiste ja sündmuste komponendid
(testimine: ing, eesti)

**Comment by TanelTromp** [comment]
Asendada hardcodetud sildid tõlgetega:
Uudise listvaade
Uudise detailvaade
Artikli detailvaade
Sündmuse list
Sündmuse detailvaade
Avalehele uudiste ja sündmuste komponendid

**Comment by TanelTromp** [comment]
Töötab, kus hetkel tõlkimata tõlgib sisuhaldur.
