### ISSUE TITLE
Logikirjete salvestamine Redisest (lõime logikirjed)

### ISSUE THREAD

**Issue by ruut12** [hariduspilv/haridusportaal#209]
Library paigaldamine
Isikukaardi logikirjed
Redises olevad logikirjed salvestada failidesse Drupali logikirjete faili

Redisest Drupali kaudu faili lõime logikirjed (redis sink)

**Comment by heldiraudsepp** [comment]
@ruut12 kirjutab sisu vastavaks

**Comment by heldiraudsepp** [comment]
Vaja teha Drupali poolsed täiendused ja üle vaadata lahendus

**Comment by lsoonvald** [comment]
Drupali Watchdogi logid salvestada eraldi failidesse maha
