### ISSUE TITLE
Pilet 15 testimine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#210]
https://github.com/hariduspilv/haridusportaal/issues/15

**Comment by TanelTromp** [comment]
Viga 1: Uudistes on võimalik lisada H1 ja H2, kuigi peaks olema kinni keeratud:
"Formaadid Heading1, Heading2 ja Paragraph (uudistes (News) heading-d pole lubatud)"

Viga 2: lisab hetkel teksti lisatud linkidele serveri eesliite: htm.twn.ee ja ei avane ka uuel vahelehel-kaardil:
"lingid (pealkiri, URL, kas avaneb veebilehitseja uuel või samal vahelehel; vaikimisi uuel vahelehel)"

Viga 3: TAB küll ei tööta taandrea sisestamiseks aga seda saab siiski teha space klahviga hetkel. 

Viga 4: teksti sisse ei saa lisada faili:
"failid (lubatud ainult pdf failid)"

@lsoonvald

**Comment by ruut12** [comment]
Viga1: Editori ei saa seadistada sisutüübi põhiselt.
Viga2: Üle lehe linkide lisamisel välisele lingile tuleb ette lisada kas http või https. Vastasel juhul nii Angulari rakendus kui ka Drupal saavad aru, et tegemist on sisemise viitega.

Viga3: Seda ei ole võimalik kontrollida.

Viga4: Faili üleslaadimine on lisatud editori. Hetkel on lubatud üles laadida ainult Pdf formaadis olevaid faile.
