### ISSUE TITLE
Vajaduspõhise õppetoetuse taotluse eelmisele ekraanivormile tagasi liikumine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#211]
**Üldkirjeldus:**
Kasutaja liigub tagasi taotluse eelnevale sammule. Eelneval sammul sisestatud andme kuvatakse mittemuudetavatena. Kasutaja saab kontrollida, kas ta on andmeid õigesti sisestanud.

Kui kasutaja eelneval sammul sisestatud andmeid ei muuda, siis ta saab enne tagasi liikumist avatuna olnud sisestussammule tagasi liikuda ja jätkata seal pooleli jäänud andmete sisestamist.

Kui kasutaja soovib eelneval sammul sisestatud andmeid muuta, ta peab sellest sammust alates kogu sisestusprotsessi uuesti läbima.

**Eeltingimused ja käivitamine:**
Portaal on kuvanud sisse loginud kasutajale vajaduspõhise õppetoetuse taotluse sissetulekute ekraanivormi (https://github.com/hariduspilv/haridusportaal/issues/171) või kontaktide ekraanivormi ((https://github.com/hariduspilv/haridusportaal/issues/171). Kasutaja valib sammu, kuhu ta soovib tagasi liikuda.

**Vastuvõtutingimused:**

* Kasutaja saab sissetulekute ekraanivormilt liikuda tagasi perekonnaliikmete ekraanivormile.

* Kasutaja saab kontaktide ekraanivormilt liikuda tagasi perekonnaliikmete ekraanivormile ja sissetulekute ekraanivormile.

***

* Portaal kuvab perekonnaliikmete ekraanivormil:
--  veateadete, hoiatuste, infoteadete kirjeldused hetkel kehtiva seisuga ehk viimati toimunud andmevahetuse vastuses saadud hoiatusDto sisu alusel.
-- perekonnaliikmete ekraanivormil kuvatud ja sisestatud perekonnaliikmete andmed, märge eestkoste, asenduskodu või perekonnas hooldamise kohta ja tõendavate failide nimed perekonnaliikmete andmete sisestamise lõpu ehk viimati vtTaotlusSissetulekud sisendisse antud seisuga.

* Kasutaja saab perekonnaliikmete ekraanivormil alustada andmete muutmist:
-- Portaal kuvab dialoogi "Perekonnaliikmete andmete muutmise korral tuleb uuesti sisestada sissetulekute andmed ja panga- ning kontaktandmed. Kas olete kindel, et soovite muuta perekonnaliikmete andmeid"? jah/ ei valik. 
-- Kui kasutaja vastab jaatavalt, siis portaal avab perekonnaliikmete sisestamise erkaanirvormi (vt https://github.com/hariduspilv/haridusportaal/issues/171)

***

* Portaal kuvab sissetulekute ekraanivormil:
--  veateadete, hoiatuste, infoteadete kirjeldused hetkel kehtiva seisuga ehk viimati toimunud andmevahetuse vastuses saadud hoiatusDto sisu alusel.
--  sissetulekute ekraanivormil kuvatud ja sisestatud perekonnaliikmete andmed, sissetulekute summade ja tõendavate failide nimed sissetulekute andmete sisestamise lõpu ehk viimati vtTaotlusKontakt sisendisse antud seisuga.

* Kasutaja saab perekonnaliikmete ekraanivormil alustada andmete muutmist:
-- Portaal avab sissetulekute sisestamise erkaanirvormi (vt https://github.com/hariduspilv/haridusportaal/issues/172)

***

* Kasutaja saab liikuda enne tagasi liikumist sisestamiseks avatud ekraanivormile ja jätkata sisestamist (välja arvatud siis, kui alustas andmete muutmist ekraanivormil, kuhu ta tagasi liikus).

***

**Märkused:**
-- Portaal peab hoidma mälus igal läbitud ekraanivormil kuvatud ja sisestatud andmeid, et neid oleks võimalik tagasi liikumise korral kuvada ilma EHIS-st päringut tegemata.
-- Portaal peab tagasi liikumise korral jätma mällu sisestamiseks avatud ekraanivormil olevad andmed, et neid sellele ekraanivormile uuesti tagasi tulemise korral saaks sisestamist jätkata.
-- Portaal peab tagasi liikumise korral jätma meelde, mis ekraanivorm oli sisestamiseks avatud, et juhtida mis ekraanivormil lubada sisestamist ja mis on suletud (näiteks, kui kasutaja liikus sissetulekute ekraavormilt tagasi perekonnaliikmete erkaanivormile, siis ta saab uuesti tulla sissetulekute erkaanivormle ja jätkata seal sisestamist ning ei saa minna kontaktide ekraanivormile).

**Comment by heldiraudsepp** [comment]
Sai tehtud enne xdzeisonit, ei ole enam aktuaalne pilet
