### ISSUE TITLE
mtsysTegevusload teenus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#212]
**Üldkirjeldus:**
Portaali back-end küsib ettevõtte õppeasutuste tegevuslubade ja tegevusnäitajate andmeid (vt #540). Lõime komponent teeb X-tee päringu EHIS-sse, teisendab saadud vastuse sisu JSON formaati ja kirjutab selle vaheandmebaasi (REDIS-sse) ning annab portaali back-endile.

**Partnersüsteem ja teenus:** 
EHIS mtsysTegevusload teenus, millega EHIS-st küsitakse registrikoodi järgi ettevõttele kuuluvad õppeasutused ning õppeasutuste tegevusload ja majandustegevusteated.

Vastusesse kirjutatavad andmed on kirjeldatud [selles failis](https://github.com/hariduspilv/haridusportaal/blob/master/docs/dokumendivormid/mtsystegevusload.txt).

Vastus kirjutada REDIS-sse (key = ettevõtte registrikood, hashmap = "mtsys")

**Comment by EgleM-TW** [comment]
BE peab saama kooli põhiselt andmeid FE-le edastada.
