### ISSUE TITLE
Lehe/ otsingu lemmikuks lisamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#22]
**Eesmärk:**

Kasutaja soovib salvestada portaali sisulehel sooritatud otsingut või sisulehte ennast.

Süsteem võimaldab sisse loginud kasutajal salvestada töölauale sisulehti ja otsingu parameetreid.  
Selle töö raames luua back-end võimalused lemmikute salvestamiseks.

**Andmekoosseis:**

1. Lemmiku tüüp (Type)
   - sisuleht (SimpleArticlePage , TypeOneArticlePage, News, Event)
   - otsing (õppekohad_otsing, õppekohad_otsing-kalendrivaates, sündmuse_otsing, uudise_otsing)
2. Lemmiku nimi (Title), kohustuslik, maksimaalne pikkus = sisulehe pealkirja (Title) pikkus (50).
3. Lemmiku URL (Address) 

![favorites](https://user-images.githubusercontent.com/23524151/41217390-5a0d53a6-6d60-11e8-9653-82b0c351641e.png)

**Täiendav info:**
Kasutaja saab töölauale salvestada kuni 10 lemmikut.
Kui kasutajal on 10 lemmikut salvestatud ja ta üritab salvestada 11-ndat, siis kuvatakse veateadet.

Kasutaja saab lemmiku salvestamisel:
1. anda otsingule nimetuse
2. muuta sisulehe nimetust
Kasutaja saab töölaualt lemmiku eemaldada (kustutada)

Kasutaja ei saa:
1. muuta töölaual lemmikute järjekorda
2. muuta töölaual lemmiku nimetust

**Viited:**
FE pilet: #285
Töölaua kujundus:

**Comment by heldiraudsepp** [comment]
Kustutamise kohta tuleb eraldi pilet

**Comment by EgleM-TW** [comment]
Kustutamine piletis #332
