### ISSUE TITLE
Õpitee valikute graafiline pilt disain

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#226]
- [ ] Õpitee valikute pilt (https://github.com/hariduspilv/haridusportaal/issues/33)
- [ ] Õpitee valikute pilt mobiilis

BE töö: #35 
FE töö: #34

**Comment by EgleM-TW** [comment]
Jätame selle in Progress, kuna viimased täiendused teeme augustis.

**Comment by heldiraudsepp** [comment]
Jääb ootama HTM'i sisendit

**Comment by EgleM-TW** [comment]
Esimeses etapis disain tehtud, vajab HTM sisendit uue kujunduse tarbeks.
