### ISSUE TITLE
getDocument teenus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#232]
Käivitamine: BE teeb lõimest dokumendi saamiseks REST päringu (BE vastav issue on #392)

Tegevused:
-- Lõime teeb faili päringu infosüsteemist ja väljastab BE-le faili.

VPT teenuse erandid on viidatud VPT analüüsipiletis #183 .
MTSYS teenuse erandid on viidatud MTSYS analüüsipiletis #62 .

**Comment by heldiraudsepp** [comment]
Lahendatud juba teiste piletite raames
