### ISSUE TITLE
postDocument teenus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#233]
Käivitamine: BE saadab dokumendi xDzeisoni lõimele.

Tegevused:
Lõime edastab dokumendi infosüsteemi. 
Kui dokumendis on viited failidele, siis lõime võtab dokumendis olevate identifikaatorite alusel failid REDIS-st.

VPT teenuse erandid on viidatud VPT analüüsipiletis #183 .
MTSYS teenuse erandid on viidatud MTSYS analüüsipiletis #62 .

**Comment by heldiraudsepp** [comment]
Lahendatud juba teiste piletite raames
