### ISSUE TITLE
Dokumendivormide definitsioonid

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#239]
Saab dokumendivormide definitsioone:
-- lisada
-- eemaldada,
-- muuta,
-- valideerida:
- [x] kas definitsioonis olevad elemendid on kas header, body või messages
- [x] kas definitsioonis on 1 header
- [x] kas definitsioonis on 1 body
--
- [x] kas headeris olevad elemendid on kas name, endpoint või number_of_steps
- [x] kas headeris on 1 name
- [x] kas headeris oleva name väärtus on unikaalne (pole teist sama nimega vormi definitsiooni)
- [x] kas headeris on 1 endpoint
- [x] kas headeris on 1 number_of_steps
- [x] kas number_of_steps väärtus on number
--
- [x] kas body-s olevad elemendis on kas title, introduction või steps
- [x] kas body-s on 1 title
- [x] kas titles on 1 "et" element
- [x] kui on introduction, kas seal on 1 "et" element
- [x] kas body-s on 1 steps
- [x] kas body.steps-s sisalduvate elementide (steppide) arvu võrdub number_of_steps väärtusega 

-- Järgnevad kontrollid teha iga steps-s sisalduva elemendi (stepi) kohta:
- [x] kas stepi elemendi nimi on definitsiooni ulatuses unikaalne (pole >1 sama nimega stepi)
- [x] kas stepis olevad elemendid on kas title, introduction või data_elements
- [x] kas stepis on 1 title
- [x] kas titles on 1 "et" element
- [x] kui on introduction, kas seal on 1 "et" element
- [x] kas stepis on 1 data_elements

-- Järgnevad kontrollid teha iga data_elements-s sisalduva elemendi (andmeelemendi) kohta:
- [x] kas andmeelemendi elemendi nimi on definitsiooni ulatuses unikaalne (pole >1 sama nimega andmeelementi)
- [x] kas andmeelemendis on 1 type
- [x] kas type väärtus on heading, helpertext, text, textarea, number, date, checkbox, selectlist, email, file, table või address
- [x] kui andmeelemendis hidden <> true, siis kas andmeelemendis on 1 title
- [x] kas andmeelemendis on title, kas seal on 1 "et" element
- [x] kui andmeelemendis on heading, kas seal on 1 "et" element 
- [x] kui andmeelemendis on helpetext, kas seal on 1 "et" element
- [x] kui andmeelemendis on required, siis kas selle väärtus on true või false
- [x] kui andmeelemendis on hidden, siis kas selle väärtus on true või false
- [x] kui andmeelemendis on readonly, siis kas selle väärtus on true või false
- [x] kui andmeelemendis on width, siis kas selle väärtus on number
- [x] kui andmeelemendis on height, siis kas selle väärtus on number
- [x] kui andmeelemendis on min, siis kas selle väärtus on number
- [x] kui andmeelemendis on max, siis kas selle väärtus on number
- [x] kui andmeelemendis on minlength, siis kas selle väärtus on number
- [x] kui andmeelemendis on maxlength, siis kas selle väärtus on number
- [x] kui andmeelemendis on multiple, siis kas selle väärtus on true või false
- [x] kui andmeelemendi type = heading, siis kas andmeelemendis olevad elemendid on kas type või title
- [x] kui andmeelemendi type = helpertext, siis kas andmeelemendis olevad elemendid on kas type või title
- [x] kui andmeelemendi type = text, siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly, width, maxlength, minlength
- [x] kui andmeelemendi type = textarea, siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly, width, height, maxlength, minlength
- [x] kui andmeelemendi type = number, siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly, max, min 
- [x] kui andmeelemendi type = date, siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly, max, min 
- [x] kui andmeelemendi  type = checkbox, siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly
- [x] kui andmeelemendi type = email, siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly
- [x] kui andmeelemendi type = file , siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly, multiple, acceptable_extensions
- [x] kui andmeelemendi type = address, siis kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly, multiple

-- kui andmeelemendi type = selectlist, siis:
- [x]  kas andmeelemendis olevad elemendid on kas type, title, helpertext, required, hidden, readonly, width, multiple, empty_option või options
- [x] kas andmeelemendis on 1 options
- [x] kas options-i sisalduv iga element on andmeelemendi ulatuses unikaalse nimega
- [x] kas options-i sisalduvas igas elemendis on 1 "et" element

-- kui andmeelemendi type = table, siis:
- [x] kas andmeelemendis olevad elemendid on kas type, title, helpertext, add_del_rows ja tabel_columns
- [x] kui andmeelemendis on add_del_rows, siis kas selle väärtus on true või false

-- Järgnevad kontrollid teha table_columns-s sisalduva iga elemendi (veeru) kohta:
- [x] kas veeru elemendi nimi on tabeli ulatuses unikaalne 
- [x] kas veerus on 1 type
- [x] kas veeru type väärtus on text, number, date, checkbox, selectlist, email, file
- [x] kas veeruss on 1 title 
- [x] kas veeruss title-s on 1 "et" element
- [x] kui veerus type = text, siis kas veerus olevad elemendid on kas type, title, required, hidden, readonly, width, maxlength, minlength, default_value
- [x] kui veeru type = number, siis kas veerus  olevad elemendid on kas type, title, required, hidden, readonly, width, max, min, default_value
- [x] kui veeru type = number ja veerus on default_value, siis kas see on number
- [x]  kui veeru type = date, siis kas veerus olevad elemendid on kas type, title, required, hidden, readonly,  width, max, min, default_value
- [x] kui veeru type = date ja veerus on default_value, siis kas see on kuupev (formaadis YYYY-MM-DD)
- [x] kui veeru  type = checkbox, siis kas veerus olevad elemendid on kas type, title,  required, hidden, readonly,  width, default_value
- [x] kui veeru  type = checkbox ja veerus on default_value, siis kas see on true või false
- [x] kui veeru  type = email, siis kas veerus olevad elemendid on kas type, title, required, hidden, readonly, width, default_value
- [x] kui veeru  type = email ja veerus on default_value, siis kas see on e-maili formaadis
- [x] kui veeru type = file, siis kas veerus olevad elemendid on kas type, title, required, hidden, readonly, multiple, width, acceptable_extensions
- [x] kui veeru type = select_list, siis kas veerus olevad elemendid on kas type, title, required, hidden, readonly, width, default_value, empty_option, options
- [x] kui veeru type = select_list, siis kas veerus on 1 options
- [x] kui veeru type = select_list, siis kas options-i sisalduv iga element on veeru ulatuses unikaalse nimega
- [x] kkui veeru type = select_list, siis kas options-i sisalduvas igas elemendis on 1 "et" element
- [x] kui veeru type = select_list, ja kui on default_value, siis kas selle väärtus võrdub ühe options-i nimega

-- Järgnevad kontrollid teha iga messages sisalduva elemendi (teate) kohta:
- [x] kas teate elemendi nimi on definitsiooni ulatuses unikaalne (pole >1 sama nimega teadet)
- [x] kas teates olevad elemendid on kas message_type või message_text
- [x] kas teates on 1 message_type
- [x] kas message_type väärtus on NOTICE, WARNING, ERROR
- [x] kas teates on 1 message_text
- [x] kas message_text-s on 1 "et" element

**Comment by heldiraudsepp** [comment]
Tükeldada planeerimisel

**Comment by andrussarv** [comment]
- [ ] Textarea-l peab height olema lubatud

**Comment by andrussarv** [comment]
- [ ] "kas definitsioonis olevad elemendid on kas header, body või messages". kui praegu panna mingi muu element, siis praegu veateated ei anna.  kui header ära kaotada (heaader), siis tuleb ka php veateade
