### ISSUE TITLE
Varunduse haldamise lahendus

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#24]
Varundamise lahendus, NodeID versioonihaldus
DBWEB

**Comment by lsoonvald** [comment]
Rääkisin Jay'ga läbi ning jõudsime vastastikusele arusaamisele.

Varundamise protsess:
1. Live baasist dumpi tegemine
2. Liigutamine Prelive serverisse
3. Test DB seisma
4. Vana baasi eemaldamine Prelivest
5. Uue dumpi lahtipakkimine Prelivesse
