### ISSUE TITLE
xsjon päring BE

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#240]
**Üldkirjeldus**
Kasutaja 
- alustas portaalis dokumendi vormi täitmist (#425, #652) või 
- avatud dokumendivormi peal vajutas nuppu, mis käivitas dokumendi saatmise (#171)  või
- töölaud (vt #394) jätkab pooleli jäänud dokumendi sisestamist või 
- töölaualt avaa vaatemiseks esitatud dokumendi.
Portaali FE saadab portaali BE-le päringu, BE edastab päringu lõimeteenusele (#232, #233) ja lõimeteenus edastab päringu infosüsteemile ning vastuseks oleks dokument liigub sama teed pidi FE-sse tagasi.

**Tegevused**
- FE-lt tuleb xsjon päring, mis on:
-- uue dokumendi postitamine: sisendis on form_name
-- sisestamisel oleva dokumendi postitamine: sisendis on xDzesion dokumendivormi sisu
-- pooleli oleva dokumendi päring sisestamise jätkamiseks: sisendis on draft = true, form_name ja identifier
-- valmis dokumendi päring kuvamiseks: sisendis on existing = true, form_name ja identifier
***
Dokumendi postitamine:
- Lisada dokument header-sse kasutaja andmed (agents element)
- Teha lõimest post document päring (#233)
- Kontrollida ja töödelda lõimelt saadud vastus (#241)
- Anda FE-le vastus.

Testimise erandjuhtum #426.

***
Pooleli oleva  või valmis dokumendi päring:
- Teha lõimest get document päring (#232)
- Kontrollida acceptable_activity väärtust:
-- kui draft = true, siis kas acceptable_activity = SAVE, SUBMIT või CONTINUE
-- kui existing = true, siis , kas acceptable_activity = VIEW
-- Kui tingimus ei ole täidetud,  siis asendada dokumendivorm veateate dokumendivormiga 
- Kontrollida ja töödelda lõimelt saadud vastus (#241).
- Anda FE-le vastus.

***
Veateate dokumendivorm:
{
"header" : {
	"form_name" : "ERRORMESSAGE",
	"endpoint": "missing",
	"number_of_steps": 1,
	"acceptable_activity" : [ "VIEW" ],
	"current_step" : "errorstep",
	"identifier" : "missing" 
},
"body" : {
	"title": {
		"et" : "Viga",
		"en" : "Error"
	},
	"steps" : {
		"errorstep" : {
			"title" : {
				"et" : "Viga",
				"en" : "Error "
			},
			"data_elements" : {
			}
		}
	}
}
}

**Comment by ruut12** [comment]
POST /xjson_service?_format=json HTTP/1.1
Content-Type: application/json

{
	"form_name": {$form_name},
	"id" : {$identifier}, // et laadida olemasolevat dokumenti tuleb lisada id ja status on sel juhul required
        "test": true, // kas kasutatakse test lõime infot
	"status": "submitted" // võimalikud sisendid "submitted", "draft"
}
