### ISSUE TITLE
Dokumendi sisu töötlemine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#241]
(vk) – võimalik veakoht. Kuidas vea korral toimida, kuidas nii FE-le kui infosüsteemile anda teada tekkinud veast.

**Infosüsteemist tulnud dokument front-end-le**
(vk) – võimalik veakoht. Kuidas vea korral toimida, kuidas nii FE-le kui infosüsteemile anda teada tekkinud veast.
1.	Header-i töötlemine
1.1.	Kas kohustuslikud elemendid form_name, current_step ja acceptable_activity on olemas? (vk)
1.2.	Kas form_name-s viidatav dokumendivormi definitsioon on olemas?  (vk)
1.3.	Kas current_step-s viidatav step on dokumendivormis olemas? (vk)
1.4.	Kas acceptable_activity väärtus on SAVE, SUBMIT, CONTINUE või VIEW? (vk)
2.	Lugeda dokumendivormi definitsioon.
3.	Teha väljundisse header (kombineerida definitsioonist ja dokumendist)
4.	Teha väljundisse body algus (title, introduction)
5.	Dokumendivormi definitsioonis oleva iga step-i definitsiooni kohta
5.1.	Teha väljundisse stepi algus (title, introduction)
5.2.	Stepi definitsioonis oleva iga andmeelemendi definitsiooni kohta 
5.2.1.	Otsida dokumendist vastav andmeelement. Kui leidus, siis:
5.2.1.1.	Võta dokumendist value väärtus ja lisatunnused 
(kui dokumendis on andmeelement, aga ilma valueta, siis ei ole viga, eksju)?
5.2.1.2.	Kas value sobib definitsioonis oleva andmetüübiga? ?  (vk)
5.2.1.3.	Kas lisatunnused sobivad andmetüübiga?  (vk)
5.2.1.4.	Kas struktuur õige (lisatunnuste väärtused õiged)? ?  (vk)
5.2.1.5.	Kui andmetüüp on select_list, siis kas value väärtusele vastav option on defineeritud dokumendivormi definitsioonis?  (vk)
5.2.1.6.	Kui andmetüüp on file, siis kas struktuur õige (kas on file_name ja file_identifier)? (vk)
5.2.1.7.	Kui andmetüüp on address, siis kas struktuur õige (struktuur on täpsustamisel)? (vk)
5.2.1.8.	Kui on table:
5.2.1.8.1.	add_del_rows tunnus
5.2.1.8.2.	Table iga rea kohta kontrolli reas olevate elementide vastavust tabeli definitsioonile (kas sellise nimega veerg on, kas väärtus vastab definitsioonis olevale andmetüübile)
5.2.1.9.	Teha väljundisse andmeelement:
	definitsioonist title, introduction
	dokumendist value (kui on)
	definitsioonist ja dokumendist lisatunnused kombineerida.
	selectlisti korral definitsioonist option-d
5.2.1.10.	Kui on mitu väärtust (value on array), siis kas lisatunnus multiple on true (vk)
5.2.1.11.	Kui andmeelemendis on message(d), siis
5.2.1.12.	Kas message on defineeritud dokumendis või dokumendivormi definitsioonis? (vk) Teha andmeelemendi juurde väljundisse message.
5.3.	Kui stepis on message(d), siis
5.3.1.	Kas message on defineeritud dokumendis või dokumendivormi definitsioonis? (vk).
5.3.2.	Teha väljundisse message(d).
6.	Kui body-s on message(d), siis
6.1.	Kas message on defineeritud dokumendis või dokumendivormi definitsioonis? (vk)
6.2.	Teha väljundisse message(d).
Töötlemise tsükkel käib mööda dokumendivormi definitsioonis ja otsib vasteid dokumendist. Dokumenti tsükliliselt läbi ei töödelda. Seega, kui dokumendis on mingi step või andmeelement mida definitsioonis pole, siis seda lihtsalt ignoreeritakse.

**Comment by heldiraudsepp** [comment]
Testimiseks kasutab käsitöö jsonit
