### ISSUE TITLE
testsessioonid_kod teenus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#245]
**Üldkirjeldus:**
Päringute üldine loogika on kirjeldatud siin: https://github.com/hariduspilv/haridusportaal/wiki/T%C3%B6%C3%B6laud.
Partnersüsteem: EIS (Eksamite infosüsteem)
Teenuseid kirjeldav WSDL: https://test.ekk.edu.ee/util/eis_v4.wsdl
X-tee kaudu päritav kompleksteenus: „minu_testid – Minu eksamid“ kasutatavad teenused:
1. testsessioonid_kod
2. testid_kod
3. e_tunnistus_kod #248 

Taust: Testsessioonide päring kuvab sessioonide loetelu, mille testidel kasutaja on osalenud. Kasutaja valib sessiooni ning näeb selle sessiooni testide (soorituste) andmeid. Kui sessioonis on väljastatud tunnistus, siis saab ta selle alla laadida.

Lõime teenus lahendada sarnaselt #375 
Portaali back-end küsib EIS-st testsessioone (vt #246 ). Lõime komponent teeb X-tee päringu EIS-i, teisendab saadud vastuse sisu JSON formaati ja kirjutab selle vaheandmebaasi (REDIS-sse) ning annab portaali back-endile.

**Nõuded:**
* Lõime teenuse sisendis on portaali _request_timestamp_ ja _personal_id_ (kasutaja isikukood).  
* EIS-st küsitakse elle isikukoodiga isiku kõik testsessioonid.
* REDIS-sse kirjutatava vastuse key on isikukood ja hash key on "xxx".
* REDIS-sse kirjutatava vastuse value on JSON formaadis.
* REDIS-sse kirjutatava vastuse elemendid on _request_timestap_, _response_timestamp_ ja _response_.
* _Response_ on X-tee päringu vastuse sisu teisendatult JSON formaati.  X-tee päringu vastuses võib olla 0 kuni n testsessiooni. X-tee päringu vastuses oleva testsessiooni kohta tehakse JSON-s etunnistuse element.  JSON elementide nimetused on samad XML-i märgentiga.
* Kui X-tee päringu tegemine ei õnnestu, siis _response_ sisu on "error" : true ja viga kirjutatakse logisse.

1. **testsessioonid_kod (Testsessioonid)**

**Väljund EIS-st:**

Väljastatakse loetelu testsessioonidest, mille testidel päringu sooritaja on osalenud.

Välja nimi | Tüüp | Kordsus | Selgitus | Näide
-- | -- | -- | -- | --
response | testsessioonid_kod_vastus (all) | 1 |   |  
teade | string | 1 |   |  
testsessioonid_kod_jada | sequence | 1 | Testsessiooni testidel osalemine |  
item | testsessioonid_kod_jada_item (all) | 0… |   |  
nimi | string | 1 | Testsessioon | Põhikooli lõpueksamid 2017
oppeaasta | string | 1 | Õppeaasta | 2017
testsessioon_id | integer | 1 | Testsessiooni id |  

2. **testid_kod (Testid)**
Väljastatakse andmed päringu sooritaja osalemise kohta antud testsessiooni testidel.

**Sisend:**

Välja nimi | Tüüp | Kordsus | Selgitus
-- | -- | -- | --
 request | testid_kod_paring (all) | 1 |  
 testsessioon_id | integer | 1 | Testsessiooni id

**Väljund:**

Välja nimi | Tüüp | Kordsus | Selgitus | Näide
-- | -- | -- | -- | --
response | testid_kod_vastus (sequence) | 1 |   |  
teade | string | 1 |   |  
testid_kod_jada | sequence | 1 | Testidel osalemine |  
item | testid_kod_jada_item (sequence) | 0… |   |  
test_nimi | string | 0…1 | Testi nimi | Inglise keel
osa_nimi | string | 0…1 | Testiosa nimi | Kirjutamisosa
osa_kuupaev | date | 0…1 | Testiosa toimumise aeg | 11.05.2018
osa_koht | string | 0…1 | Testiosa toimumise koht | Sütevaka Gümnaasium
osa_aadress | string | 0…1 | Testiosa toimumise koha aadress | Pärnu maakond, Pärnu   linn, Pärnu linn, Metsa tn 21
staatus | string | 1 | Staatus | Tulemus on teada
tulemus | string | 1 | Tulemus | 45p 50-st, 90%
tunnistus_id | integer | 0…1 |   |  

3. **e_tunnistus_kod**(Tunnistus)
Tunnistuse allalaadimine.
**Sisend:**

Välja nimi | Tüüp | Kordsus | Selgitus
-- | -- | -- | --
request | e_tunnistus_kod_paring (all) | 1 |  
tunnistus_id | integer | 1 | E-tunnistuse id

**Väljund:**

Välja nimi | Tüüp | Kordsus | Selgitus | Näide
-- | -- | -- | -- | --
response | e_tunnistus_kod_vastus (sequence) | 1 |   |  
teade | string | 1 |   |  
tunnistusenr | string | 1 | Tunnistuse nr |  
valjastamisaeg | date | 1 | Tunnistuse väljastamise kuupäev |  
kehtiv | t_kehtiv (string) | 1 | Kehtivus   0 – Kehtetu   1 – Kehtiv |  
tunnistus | base64Binary | 1 | E-tunnistus |  

**Vead vastavalt päringute üldisele loogikale:**
* 0 - Tehniline viga.
* 1 - Sellise isikukoodiga isiku kohta andmed puuduvad.

**Täiendavad vastuvõtutingimused:**
* X-tee päringu tegemine logitakse.
* Kui tekkis tehniline viga, siis see kajastub logi kirjes (sisulisi andmevigu ei logita).

**Viited:**
* Drupal back-end: #246 
* Logimine: https://github.com/hariduspilv/haridusportaal/issues/120

***
Tehniline viga on näiteks siis, kui:
* lõimeteenuse sisend ei vasta nõuetele
* EIS-st vastuse ootamisel tekib _time-out_
* EIS-st saadud XML vastus ei ole parsitav

**Comment by EgleM-TW** [comment]
Jason vormis
Kas läbi Kafka? Jah
Vajalik diskussioon - kas töölaua teenused pakis kõik või eraldi. H.Ruut-Indrek-Andrus-Egle
