### ISSUE TITLE
Riigieksamite (EIS testsessioonid) kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#247]
**Üldkirjeldus:**
Kasutaja näeb enda riigieksamite (testsessioonid) andmeid ja saab talle väljastatud tunnistuse alla laadida.

**Eeltingimused ja käivitamine:**
* Kasutaja on portaali sisse loginud. Portaalis on teada kasutaja isikukood.
* Portaal avab töölaua kasutajale pärast sisse logimist.
* Riigieksamite nägemiseks kasutaja valib töölaual "Tunnistused" -> "Riigieksamid"
* Riigikesamite (testsessioonidel osalmise andmete) saamiseks tehakse päring back-end-i kaudu EIS-st, kasutajaliidesele edastab BE andmed kolme päringuga:
   - Esimene päring, kui kasutaja vajutas akordionis "Riigieksamid" (testsessioonid_kod)
   - Teine päring, kui kasutaja valis nimekirjas (vaata lähemalt), et näha ühe aasta eksamite detailandmeid (testid_kod)
   - Kolmas päring, kui kasutaja valis "lae alla" tunnistus (e_tunnistus_kod)

**Tegevused**
- [ ] Esimese päringu tulemusel kuvatakse EIS-st saadud testsessiooni testidel osalemise nimistu. 
- [ ] Kasutaja saab avada nimistust ühe tesstsessiooni testid. Teise päringuga kuvatakse testidel osalemise andmed (detailvaade). Kuvatavad andmed on kirjeldatud allpool.
- [ ] Kui kasutajale on väljastatud tunnistus, siis saab ta selle alla laadida - parem veerg.
- [ ] Breadcrumbi kaudu saab uuesti avada töölaua tunnistuste saki.

**Erijuhud ja täpsustused:**
-  [ ] Kui EIS-st ei saadud ühtegi testsessiooni kirjet, siis kuvatakse teade "Riigieksamitel osalemise andmed puuduvad".
-  [ ] Kui EIS-st saadi mitu testsessioonil osalemist, siis need järjestatakse õppeaasta järgi hilisemad eespool.
-  [ ] Kui on error, siis kuvatakse veateade "Vabandame. Riigieksamite andmete Eksamite infosüsteemist lugemise käigu tekkis tehniline viga. Palun proovige hiljem uuesti."
-  [ ] Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuva (silti ka mitte).
 - [ ] Kui tunnistus puudub, siis  veateade - vt disaini.
****
Disaini lingid: esimene: https://zpl.io/a3lkGZY ja teine: https://zpl.io/VqwZr0m

****
**1. Riigieksamite (testsessioonide) nimistus kuvatavad andmed:**
* Eksami nimetus - nimi 
* Aasta - oppeaasta
* Vaata lähemalt - testsessioon_id

**2. Testidel osalemine (detailandmed):**
* Pealkiri: Eksami nimetus - nimi  (see on ilma sildita, nt Riigieksamid 2007)
* Akordioni pealkiri (kuvatakse, kui akordion suletud):
   - Testi nimi - testi_nimi (silti ei kuva) (nt Matemaatika)
   - Tulemus - tulemus (silti ei kuva) (nt 65p 100-st, 60%)
* Kui akordion avada, kuvatakse:
   - Testi nimi - testi_nimi (nt Ühiskonnaõpetus)
   - Tulemus - tulemus (nt 65p 100-st, 60%)
Testiosa andmed kuvatakse keritavas tabelis, kus silt on tabeli päis - vt disainis
   - Testiosa nimi - osa_nimi
   - Tulemus - tulemus (vajalik osa kohta kuvada)
   - Staatus - staatus (vajalik osa kohta kuvada)
   - Toimumise aeg - osa_kuupaev
   - Toimumise koht - osa_koht
   - Toimumise aadress - osa_aadress

3. Tunnistuse kuvamine ja allalaadimine 
Paremas veerus on blokk "Tunnistuse allalaadimine". Päring teha nupule vajutamisel.
 - Kui on tunnistus, saab seda alla laadida.
 - Kui tunnistust pole, kuvata "teade". Teade on EISi päringu vastuses. 
Kui teadet pole sis kuvame sarnaselt "Lemmikud puuduvad" kompoinendile. Tekst:
_Tunnistus ei ole saadaval faili kujul e-tunnistusena._

**Comment by EgleM-TW** [comment]
Madis, tunnistuse alla laadimise nupule pane palun "Laadi alla" , kontrollisin ÕS-st nii on õige :)

**Comment by madispold** [comment]
Testimisse @TanelTromp 

Tunnistuse puudumisel veateadet EISist ei tule - seetõttu parempoolne plokk viimase puudumisel ei ilmu hetkel.

Veateated on piletis kirjeldatu asemel hoopis EISist vastavalt kokkuleppele.

**Comment by madispold** [comment]
Võib testida @TanelTromp 
Kasutajad:
testija1/testija1
ruut/parool

**Comment by TanelTromp** [comment]
TEST

Kasutaja/parool: testija1/testija1

Viga 1: "eksami nimetus" ja "aasta" on üks ja sama nimekiri vaates:

<img width="514" alt="capture" src="https://user-images.githubusercontent.com/37407917/46672161-60624a80-cbdf-11e8-889a-576a2d01eaa3.PNG">

Viga 2: mobiilivaade sellisel kujul loetamatu @birgitpulk  :

![20181009_162530](https://user-images.githubusercontent.com/37407917/46672542-63116f80-cbe0-11e8-90db-ed0ba13ef91d.jpg)

Viga 3: osadel eksamitultemsute aastatel puudub parem veerg:
http://htm.twn.ee/et/toolaud/tunnistused/15?exams=2004
http://htm.twn.ee/et/toolaud/tunnistused/16?exams=2005

<img width="273" alt="capture" src="https://user-images.githubusercontent.com/37407917/46672926-53465b00-cbe1-11e8-9f1a-bd1dcc64b1a7.PNG">

Viga 4: nõue ei ole täidetud, hetkel on varasemad eespool:_ Kui EIS-st saadi mitu testsessioonil osalemist, siis need järjestatakse õppeaasta järgi hilisemad eespool._

---------------------------------------------------------------------------------

**Tegevused**
- [x] Esimese päringu tulemusel kuvatakse EIS-st saadud testsessiooni testidel osalemise nimistu. 
- [x] Kasutaja saab avada nimistust ühe tesstsessiooni testid. Teise päringuga kuvatakse testidel osalemise andmed (detailvaade). Kuvatavad andmed on kirjeldatud allpool.
- [ ] Kui kasutajale on väljastatud tunnistus, siis saab ta selle alla laadida - parem veerg.
- [x] Breadcrumbi kaudu saab uuesti avada töölaua tunnistuste saki.

**Erijuhud ja täpsustused:**
-  [ ] Kui EIS-st ei saadud ühtegi testsessiooni kirjet, siis kuvatakse teade "Riigieksamitel osalemise andmed puuduvad".
-  [ ] Kui EIS-st saadi mitu testsessioonil osalemist, siis need järjestatakse õppeaasta järgi hilisemad eespool.
-  [ ] Kui on error, siis kuvatakse veateade "Vabandame. Riigieksamite andmete Eksamite infosüsteemist lugemise käigu tekkis tehniline viga. Palun proovige hiljem uuesti."
-  [ ] Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuva (silti ka mitte).
 - [ ] Kui tunnistus puudub, siis  veateade - vt disaini.
****
Disaini lingid: esimene: https://zpl.io/a3lkGZY ja teine: https://zpl.io/VqwZr0m

****
**1. Riigieksamite (testsessioonide) nimistus kuvatavad andmed:**

- [ ] Eksami nimetus - nimi 
- [x] Aasta - oppeaasta
- [x] Vaata lähemalt - testsessioon_id

**2. Testidel osalemine (detailandmed):**

- [ ] Pealkiri: Eksami nimetus - nimi  (see on ilma sildita, nt Riigieksamid 2007)
- [ ] Akordioni pealkiri (kuvatakse, kui akordion suletud):
   - Testi nimi - testi_nimi (silti ei kuva) (nt Matemaatika)
   - Tulemus - tulemus (silti ei kuva) (nt 65p 100-st, 60%)
* Kui akordion avada, kuvatakse:
   - Testi nimi - testi_nimi (nt Ühiskonnaõpetus)
   - Tulemus - tulemus (nt 65p 100-st, 60%)
Testiosa andmed kuvatakse keritavas tabelis, kus silt on tabeli päis - vt disainis
   - Testiosa nimi - osa_nimi
   - Tulemus - tulemus (vajalik osa kohta kuvada)
   - Staatus - staatus (vajalik osa kohta kuvada)
   - Toimumise aeg - osa_kuupaev
   - Toimumise koht - osa_koht
   - Toimumise aadress - osa_aadress

3. Tunnistuse kuvamine ja allalaadimine 
Paremas veerus on blokk "Tunnistuse allalaadimine". Päring teha nupule vajutamisel.
 - Kui on tunnistus, saab seda alla laadida.
 - Kui tunnistust pole, kuvata "teade". Teade on EISi päringu vastuses. 
_Vajadusel täpsustada BE ja analüütikutega :)_

**Comment by madispold** [comment]
Viga 1: Andmetes nimi ja oppeaasta sama väärtusega, aga ei tea kas niiviisi vaid testandmetel.
Viga 2: @birgitpulk 
Viga 3: Lisatud veateade vastavalt Egle täpsustusele.
Viga 4: OK.
Viga 5: OK.
Viga 6: OK.
Viga 7: Piletis kirjeldatud veateated olid sellel tingimusel, et lõimest ei tule teateid. Kuna tulevad lõimest ikkagi, siis kuvame need (Analüütikutega klaaritud).
Viga 8: Birgitiga arutamise tulemusel otsustasime info puudumisel kuvada "-", kuna pika sisuga tabel korral kui vahelt andmeid puudu kuvaks tabel lõppu augu (vaata pilt)
![Screen Shot 2018-10-10 at 14.53.22.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/600c0b99-4930-4b1a-9987-4db1563060d1)
Viga 9: OK.

**Comment by madispold** [comment]
@TanelTromp 
Viga 10: See on Angular Material komponendi sügav element, mida ei ole markup'is enne lehe laadimist seega siin ei ole head lahendust. Material elementide wcag küll natuke segane, aga tugi olemas ja kindlasti läbitavad lehel - arvan, et pole probleemi.

**Comment by birgitpulk** [comment]
- [ ] Tabeli kerimise nool peaks tabeli servast olema 16px, hetkel rohkem
- [ ] Akordion peaks olema mobiilivaates täislaiuses

**Comment by madispold** [comment]
@birgitpulk 
Viimased 2 punkti: OK.
