### ISSUE TITLE
Metatag's mooduli sidumine

### ISSUE THREAD

**Issue by ruut12** [hariduspilv/haridusportaal#249]
Vastuvõtutingimused:
* Drupali sisulehel on seadistatav Metadata
* GraphQl's saab pärida sisulehe kohta antud lehe metadatat

**Comment by ruut12** [comment]
Kokk valideerib kas kõik sobib

**Comment by skeefee** [comment]
Kõik sobib. Tanel võid testida

**Comment by TanelTromp** [comment]
Drupali sisulehel on seadistatav Metadata
 GraphQl's saab pärida sisulehe kohta antud lehe metadatat

**Comment by TanelTromp** [comment]
* Drupali sisulehel on seadistatav Metadata
* GraphQl's saab pärida sisulehe kohta antud lehe metadatat
