### ISSUE TITLE
Sündmuse vaadetele disaini rakendamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#255]
Viia disaniniga kooskõlla järgmised vaated:
- [x] Sündmuse listvaade [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc4340b3d126610f951f74) (https://github.com/hariduspilv/haridusportaal/issues/98, https://github.com/hariduspilv/haridusportaal/issues/126)
- [x] Sündmuse listvaade mobiil [Disaini link: filter kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe907930a5d823224a983e) , [Disaini link: filter lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe90795ad91520379787f9)
- [x] Sündmuse detailvaade [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afeba79e8d73e250f0df398) (https://github.com/hariduspilv/haridusportaal/issues/100, https://github.com/hariduspilv/haridusportaal/issues/110,  https://github.com/hariduspilv/haridusportaal/issues/2, https://github.com/hariduspilv/haridusportaal/issues/26)
- [x] Sündmuse detailvaade mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afeba7809a18d3d0f2bad4f)

**Comment by madispold** [comment]
Lisaks ka kalendri osa, kuigi nüüd näen, et see pole otseselt pileti osa vist?

Võib testida kohe kui testkeskkonnas build tehakse.

**Comment by birgitpulk** [comment]
- [ ] "Täpsem otsing" ei tööta?
- [ ] Kuu nimetus inglisekeelne
- [ ] "Kalender" ikoon vale
- [ ] Kalendrivaates üritusele klikkides võib avanev modaal olla ka suurem (et pealkiri ei läheks kolmerealiseks nt)
- [ ] Kalendrivaates "2 veel" klikkides peaks modaal tekkima konkreetse päeva peale
- [ ] Kalendrivaates "2 veel" klikkides peaks avanema modaal, kus on iga ürituse pikk nimi kuvatud (üritus võib minna mitmerealiseks, järgmine rida hakkab tekstiga ühelt joonelt, mitte kellaajaga)
- [ ] Kalendrivaates avaneva modaali pealkirja reavahe 30px (hetkel 20)
- [ ] Mobiilivaade puudu (kalendrivaadet mobiilis ei ole)

**Comment by madispold** [comment]
Kuu nimetus selline, kuna hetkel pole tõlkimiseks loogikat sinna loodud n.ö. visuaalselt korras ma eeldan?

Konkreetset kalendriikooni ei leidnud materialist, aga sarnase sain.

Kalendrivaates modaal täpselt keskele päeva peale keeruline panna, kuna tabeli suurus samuti suhteline - hetkel jääb päeva peale parema servaga tasa, esimesel kahel nädalapäeval on vasaku servaga tasa, kuna vastasel juhul liigub vaatest välja.

Mobiilivaade puudu on samuti loogika osa, mobiilivaates ta hetkel jääb, kuid vaid siis kui tuled desktopist. Muidu pole ikooni näha mobiilis, ega ei pääse ligi.

**Comment by birgitpulk** [comment]
@madispold  Kõik sobib!
