### ISSUE TITLE
Uudiste vaadetele disaini rakendamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#256]
Viia disainiga vastavusse järgmised vaated:
- [x] Uudise listvaade [Disaini link: filter kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbef090879ff66168809f5) , [Disaini link: filter lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc28a8c384811f0fbb0036)
- [x] Uudise listvaade mobiil [disani link: filter kinni](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbf8f9852cc3f615c79ec3), [disaini link: filter lahti](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbf8f9852cc3f615c79ec3)
- [x] Uudise detailvaade [disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afaeaf6b65b0ccf0469f262)
- [x] Uudise detailvaade mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc2398c384811f0fbab064)

Algne uudise detailvaate pilet: https://github.com/hariduspilv/haridusportaal/issues/95

Muuta vastavalt kujundusele: zpl://screen?sid=5af04a45a283fe7a7e65bf89&pid=5ae9c7f3c560dffb217da75c

"Loe veel" asemel on "Viimased uudised"
Kuvatakse:

- foto (picture)    
- pealkiri (title)

**Comment by madispold** [comment]
Stiilid tehtud v.a siltide sisestusväli, kuna ei ole otsustanud, mis suunas sellega minna. Annan hetkel testi.

**Comment by TanelTromp** [comment]
@birgitpulk

**Comment by birgitpulk** [comment]
Üldine:

- [ ] Vasakmenüü peaks olema lehekülje vasakus servas kinni
- [ ] Vasakmenüüs valitud menüüpunkt bold
- [ ] Ikoonid kandilised, aga peaksid olema ümarad: https://material.io/tools/icons/?style=round
- [ ] Päises otsingukasti vajutades võiks kursor olla luubi ikooni kõrval
- [ ] Vasakmenüüs hoveril on oranz vasak serv ka


Uudiste listvaade:

- [ ] Filtreeringu taustaks olev valge riba peaks olema 100% laiusega
- [ ] Filtreeringu väljad muutusid, vajaksid korrigeerimist (välja sees olev tekst muutub välja sisse klikkides 
- [ ] "Täpsem otsing" vajutades avaneb veel üks filtreeringukast, mis ei ole stiilitud
- [ ] Uudistel puudub hover (hall taust, pealkirjale joon alla)
- [ ] Uudistel võiks olla sissejuhatavat teksti 3 rida  ja viimase rea lõpus 3 punkti
- [ ] Uudise pildi alal võiks olla fikseeritud suhe 16:9 ja ka fikseeritud mõõt, ehk siis et kõik uudise pildid oleksid ühe suurusega alati
- [ ] Lae rohkem nupu teksti suurus peaks olema 16

Uudise detailvaade:

- [ ] Parempoolse tulba pealkiri peaks olema "Loe veel"
- [ ] Parempoolses tulbas peaks olema 3 uudist
- [ ] Parempoolses tulbas ei tohi kuvada konkreetset uudist, mille detailvaates ollakse
- [ ] Parempoolses tulbas hiirega uudise alasse jõudes võiks pealkirjale joon alla tekkida
- [ ] Parempoolses tulbas pealkiri läbiva suurtähega
- [ ] Sinise triibu all olev pealkiri "Uudised" on alati läbiva suurtähega
- [ ] Foto croppimine: uudise sees ja parempoolses sektsioonis ainult landscape fotod. Uudise sees fotole klikkides avaneb see õiges formaadis eraldi modaalis. 
- [ ] Sildid ei tohi olla klikatavad 
- [ ] 890 laiuse peal uudise detailvaate foto ei ole full laiuses

**Comment by birgitpulk** [comment]
1. Ok. Kas ideeliselt saaks seal mõnd teist ikoonifonti ka kasutada muidu?
2. Aga piirame kõrgusega, et 3 rida mahuks ainult ära, mulle sobib selline variant ka. 
3. Sa mõtled kujundust enne arendust? Kas mingit olemasolevat materiali lightbox lahendust (kui selline on olemas) ei saaks lihtsalt kasutada?

**Comment by madispold** [comment]
1. Jah, saaks.
2. BE poolt saab piirata tähemärkideni sisendi.
3. Popup lisatud.

**Comment by birgitpulk** [comment]
Kas võin uuesti üle testida?

**Comment by madispold** [comment]
Jah

**Comment by birgitpulk** [comment]
Üldine:
- [ ] Päises olevas otsingu kastis on puudu sõna "Otsi"

Uudise listvaade: 
- [ ] Siltide filtreeringul ei muutu kast ja labeli tekst siniseks
- [ ] Puudu tag-id
- [ ] Hover võiks töötada kogu uudise alale minnes
- [ ] Osadel uudistel näitab ikka sissejuhtatavat teksti üle 3 rea?
- [ ] Kas laiemas vaates see teksti suurus ei muutu veel eks? Kas peaksime panema paika, et millal ja kui palju muutuma hakkab? Vaatan, et 1440 peal läheb see tekstikast juba liiga laiaks...
- [ ] Mobiilis filter vaikimisi suletud

Uudise detailvaade: 
- [ ] Hover võiks töötada terve uudise alasse jõudes (ka pildi peale jõudes)
- [ ] Fotole klikkides avaneb modaal/lightbox: foto pealkiri võiks olla seal ka näha
- [ ] Kuidas lightboxis galeriid kuvatakse?

**Comment by madispold** [comment]
Nüüd muutub peafont: 
  Üldine: 16px
  1400px ekraan: 20px
  1980px ekraan: 24px
  2580px ekraan: 28px

Galerii lahendust pole tehtud.

Ei saa hoverist terve uudise peal täpsemalt aru. Vaja arutada.

**Comment by birgitpulk** [comment]
Kas font muutub ka pealkirjades jm tekstide puhul ekraani suuruse muutumisel?
Hoveri all pean silmas, et hiirega terve uudise alasse minnes (kahe joone vaheline ala) võiks pealkiri allajoonituks minna.

**Comment by madispold** [comment]
16px kuni 1440 ja reavahe samuti muutujana. Hover lisatud. Võib üle vaadata.

**Comment by birgitpulk** [comment]
- [ ] Üldine: päisesse lisasin X-märgi, millega saab vasakmenüüd kinni panna
- [ ] Kas tag-id on puudu lihtsalt seetõttu, et neid ei ole sisestatud?
- [ ] Filtreering: Enter klahv tühjendab välja, kas peabki nii olema?
- [ ] Listvaates uudistel erineva kõrgusega fotod (kahel uudisel natukene kõrgemad). Millest see tingitud on?
- [ ] Listvaates uudise foto laius 1280px puhul peaks olema 283px, hetkel väiksem. Peaks korraks üle vaatama üldse pilt ja teksti suhte erinevate suuruste peal (väiksema ekraani suuruse puhul jääb pilt sektsiooni paremasse ülanurka)
- [ ] Uudises "Jõuluvana..." pildi pealkiri jookseb kasti seest välja

**Comment by madispold** [comment]
Tagide muutuja nimetus oli muutunud, nüüd taastatud.

Uudiste fotod tulenevalt sisuhaldusest, hakata frontendis neid jõuga sama suureks määrama ei ole hea, peab olema kuvasuhe paigas sisuhaldusesse lisades.

Meil 12 osaga grid, andsin piltidele hetkel 1/3 ja tekstiosale 2/3, varasemalt oli vastavalt 1/4, 3/4.

Kui avad otse mobiili ehk refreshid lehe kitsana, siis on filter suletud.

**Comment by birgitpulk** [comment]
Aga kui fotod tulevad sisuhaldusest, siis kas oskad öelda, miks osad kõrgemad on listvaates? Sisuhalduses saabki minu teada lõigata kindla suhtega pilte. 

Muus osas ok :)

**Comment by madispold** [comment]
Henriga rääkisime.

Crop moodul hetkel annab eri tulemusi, tuleb uurida, kui pilt originaalsuuruses on väiksem kui 1280 siis pole teistele vastav.

**Comment by madispold** [comment]
Liigutan done, vaid BE probleem üleval.

**Comment by madispold** [comment]
Parandatud.
