### ISSUE TITLE
Artiklite vaadete disaini rakendamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#257]
Viia disainiga vastavusse järgmised vaated:
- [x] artikli detailvaade + akordion [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afae7ba6a3720641549739e)
- [x] artikli detailvaade + akordion mobiil [Disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afbfe2e6b31722f05e1c331)

**Comment by birgitpulk** [comment]
Artikli detailvaade: 

- [ ] Vahepealkiri võib olla ainult 16px Medium
- [ ] Lingid teksti sees on Regular fondiga
- [ ] Rõhutatud tekst saab olla ainult Medium, mitte Bold (isegi kui kasutaja valib sisuhalduses Bold, siis kujunduslikult võiks see olla Medium font)
- [ ] Sisuteksti ja akordionite vahe liiga suur
- [ ] Akordioni sees olev kolmnurga ikoon liiga väike
- [ ] Esimene akordion võiks olla vaikimisi lahti
- [ ] Akordioni hover üle akordioni piirjoone
- [ ] Kas akordioni kõrgus on 40px?
- [ ] Akordion paremas servas olev mumm (noolega) on paremast servast liiga kaugel (peaks olema 16px)
- [ ] Puudu tag'id
- [ ] Sarnased teemad sektsioonis mitmerealise lingi teine rida võiks alata vasakust servast esimese reaga sama kaugelt (mitte ikooniga sama kaugelt)

**Comment by EgleM-TW** [comment]
Kujunduses on Tag'd jah, aga tegelikult andmemudeli järgi sisulehetüübil Tage pole.

**Comment by madispold** [comment]
Vahepealkirjana kasutada sisuhalduses H2/H3. H1 määratud peamiseks pealkirjaks 24px sinine.

Sisuteksti ja akordioni vahele tekib ekstra ruumi kui sisuhalduses jätta ekstra välju sisendisse.

Tagid ei käi artikli all.

**Comment by madispold** [comment]
Võib uuesti testida.

**Comment by madispold** [comment]
Kinnise akordioni puhul lõikab ära teksti.

Pealkirjad pole medium fondiga kuna sisuhalduses need lisatud paragraaf (<p>) elementidena. Muutsin 1. tagasi pealkirjaks.

**Comment by madispold** [comment]
Võib üle vaadata.

**Comment by birgitpulk** [comment]
Minu meelest kõik ok! @TanelTromp  Kas võime sulgeda?

**Comment by TanelTromp** [comment]
Hei! Jaah, kui sa kujundust testid, siis ma seda üle ei testi. Sul on enda asjadele parem silm nii või naa.
@birgitpulk
