### ISSUE TITLE
Sündmuse enda kalendrisse saatmine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#26]
**Üldkirjeldus:**
Portaali kasutaja saab süsteemist avada sündmuse (Event) kohta iCal (https://tools.ietf.org/html/rfc5545) formaadis faili, et  sündmus kanda enda kalendrisse. See on võimalik vaba sissepääsuga sündmuse korral või vahetult pärast registreerimist registreerimisega sissepääsuga sündmusele.

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud sündmuse detailvaade (#100) ja sissepääsu tüüp on "vaba" või 
* kasutaja registreerus sündmusel osalejaks (#2) ja 
* kasutaja käivitab kalendrisse lisamise.

**Vastuvõtutingimused:**
* Süsteem loob iCal faili. Kasutaja saab faili avada/alla laadida.
* Failini nimi on calendar_event_ID, kus ID on Event.id 
* Faili laiend on ics (märkus: kasutaja arvutis peaks MS-Outlook või mõni muu kalendriprogramm selle automaatselt avama sõltuvalt kasutatavast kalendriprogrammist ja veebilehitseja seadistustest).

* Faili sisu:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:_täpsustada sõltuvalt sellest, millega iCal faili hakatakse genereerima_
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP: _Event andmeobjekti loomise aeg_
UID: _Event.id+dtstart+'@'+portaali nimetus_
SUMMARY: _Event.name_
DTSTART: _EventCalendarItem.eventdate EventCalendarItem.startTime_ 
DTEND: _EventCalendarItem.eventdate EventCalendarItem.endTime_
LOCATION: _Event.locationName eventLocationAddress_
DESCRIPTION: _Event.shortDescription_
URL: _Viide sündmuse leheküljele portaalis_
END:VEVENT
END:VCALENDAR

* Aegade esitamiseks kasutatakse UTC aega.
* Kui Sündmusel on mitu toimumisaja kirjet(EventCalendarItem), siis iga toimumisaja kohta on failis VEVENT andmeplokk.

**Comment by heldiraudsepp** [comment]
BE - 8h
FE - 1
Test - 2

**Comment by TanelTromp** [comment]
Test #26_1

Vastuvõtutingimused:
   
- [ ]  Süsteem loob iCal faili. Kasutaja saab faili avada/alla laadida.

- [ ]     Failini nimi on calendar_event_ID, kus ID on Event.id
    
- [ ] Faili laiend on ics (märkus: kasutaja arvutis peaks MS-Outlook või mõni muu kalendriprogramm selle automaatselt avama sõltuvalt kasutatavast kalendriprogrammist ja veebilehitseja seadistustest).

- [ ]     Faili sisu:

    BEGIN:VCALENDAR
    VERSION:2.0
    PRODID:täpsustada sõltuvalt sellest, millega iCal faili hakatakse genereerima
    CALSCALE:GREGORIAN
    BEGIN:VEVENT
    DTSTAMP: Event andmeobjekti loomise aeg
    UID: Event.id+dtstart+'@'+portaali nimetus
    SUMMARY: Event.name
    DTSTART: EventCalendarItem.eventdate EventCalendarItem.startTime
    DTEND: EventCalendarItem.eventdate EventCalendarItem.endTime
    LOCATION: Event.locationName eventLocationAddress
    DESCRIPTION: Event.shortDescription
    URL: Viide sündmuse leheküljele portaalis
    END:VEVENT
    END:VCALENDAR
   

- [ ]  Aegade esitamiseks kasutatakse UTC aega.
  
- [ ] Kui Sündmusel on mitu toimumisaja kirjet(EventCalendarItem), siis iga toimumisaja kohta on failis VEVENT andmeplokk.

**Comment by ruut12** [comment]
viga1: Kalendri faili nimeks on nüüd faili enda nimi kus kõik mitte tähed on asendatud "_"'ga.
viga2.1a: Kalendriprogrammi avanemine sõltub kasutaja browserist ja tarkvarast. Pole meie juhitav.
viga4: URL lisatud ics failile

**Comment by skeefee** [comment]
Viga 3 on vaja läbi arutada
