### ISSUE TITLE
Lisada süsteemi taksonoomiad OSKA andmete sisestamiseks

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#263]
OSKA valdkondade, alavaldkondade ja põhikutsealade toimetamiseks peavad süsteemis olema järgmised taksonoomiad:

1. - [ ] OSKA_valdkond (OSKA_Field). Tegemist on süsteemisisese taksonoomiaga, mis on kahe tasemeline. OSKA valdkond võib jaguneda alavaldkondadeks (OSKA_alavaldkond (OSKA_Sub_Field)). 

OSKA valdkonna andmekoosseis:
- Id – süsteemi sisene unikaalne kood, genereeritakse automaatselt
- valdkonna_nimetus (title) – string, kohustuslik
- pilt (picture) – valdkonda iseloomustav pilt
- alavaldkonna nimetus (subField title), 0.. n

2. - [ ] OSKA_põhikutseala (OSKA_mainProfession). Tegemist on süsteemisisese taksonoomiaga.

OSKA põhikutseala (MainProfession) andmekoosseis:
 - Id – süsteemi sisene unikaalne kood, genereeritakse automaatselt
 - põhikutseala nimetus (mainProfession title) – string
 - OSKA valdkonna_nimetus, string, 1..n (vajalik seose loomiseks) 
 - sisu (content) – tekst
 - ISCO ametiala kood (ISCO code), klassifikaator, int, 1.. n
 - ISCO ametiala nimetus (ISCO title), klassifikaator, string, 1.. n, täidetakse automaatselt sisestatud ISCO koodi alusel
 - EMTAK kood (EMTAK code), int, 1.. n (hiljem võib olla tarvidus muuta see väli klassifikaatoriks)
 - ISCED-F 2013 rühmakood (ISCEDFdetailedField), klassifikaator, int, 1.. n, loob seose erialadega
    (studyProgram)
 - õppekava_kood (studuProgramme_code), loome võimaluse siduda otse õppekavaga, 1.. n
 - õppekava_nimetus (studyprogramme_name), koodi sisestamisel, kuvab automaatselt, 1.. n

3. - [ ] ISCO_ametiala (ISCO_occupation). Kasutame põhikutseala kirjeldamisel neljandat taset (Ametite klassifikaator 2008ap).
 - Id – süsteemi sisene unikaalne kood, genereeritakse automaatselt
 - kood  (ISCO code), nelja-kohaline number
 - nimetus, (ISCO title), koodi sisestamisel, kuvab automaatselt, saab muuta

4. - [ ] OSKA infograafika Naitaja (indicator)
 - Id – süsteemi sisene unikaalne kood, genereeritakse automaatselt
 - näitaja nimetus (indicator title) – string

  - [ ] Kasutaja saab eelnevalt loetletud taksonoomiate kohta andmeid sisestada, muuta, kustutada.

Väärtused on leitavad siit: https://github.com/hariduspilv/haridusportaal/tree/master/docs/taksonoomiad

Selgitav andmemudel: https://github.com/hariduspilv/haridusportaal/blob/master/docs/OSKA.svg

**Comment by EgleM-TW** [comment]
18.09 lisasin põhikutseala külge valdkonna seose.

**Comment by EgleM-TW** [comment]
Lisasin põhikutseala taksonoomia väärtused: https://github.com/hariduspilv/haridusportaal/blob/master/docs/taksonoomiad/OSKA_pohikutsealad.xlsx

**Comment by lsoonvald** [comment]
http://test-htm.wiseman.ee:30000/et/admin/structure/taxonomy

Taksonoomiad asuvad siin.

**Comment by TanelTromp** [comment]
- [ ] OSKA_valdkond (OSKA_Field). Tegemist on süsteemisisese taksonoomiaga, mis on kahe tasemeline. OSKA valdkond võib jaguneda alavaldkondadeks (OSKA_alavaldkond (OSKA_Sub_Field)).

OSKA valdkonna andmekoosseis:
- Id – süsteemi sisene unikaalne kood, genereeritakse automaatselt
- valdkonna_nimetus (title) – string, kohustuslik
- pilt (picture) – valdkonda iseloomustav pilt
- alavaldkonna nimetus (subField title), 0.. n

**Comment by lsoonvald** [comment]
Viga 1: Lisasin ISCO Occupation taksonoomia alla ühe termini. Kui mujalt üritan nüüd sisestada seda nimetust, siis kuvab soovitust. Referentsi tekitamine käib läbi taksonoomia nime mitte koodi, läbi koodi soovituse tekitamine on suurem lisatöö.

**Comment by lsoonvald** [comment]
Viga 1: Pole kuskilt automaatselt kuvada seda väärtust.
