### ISSUE TITLE
Pilet 128 parandus - akordionile lisatud URL'e ei kuva avalikus vaates

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#264]
Artikli sisulehe (alamosadega) toimetamise pileti #128 testimisel tuli välja järgmine viga (viidatud piletis viga nr 4):
Akordionile lisatud URLe ei kuvata avalikus vaates (testitud Google Chrome Versioon 66.0.3359.181)
Adminvaade:
![image](https://user-images.githubusercontent.com/38042389/40615494-a9ee177e-628f-11e8-935c-cf59cfea03a0.png)

Avalik vaade:
![image](https://user-images.githubusercontent.com/38042389/40615608-233c19be-6290-11e8-9662-90bf3870b7e3.png)

**Comment by TanelTromp** [comment]
Jah, akordionis puuduvad sisuhalduses lisatud lingid ja lingi pealkirjad:

![pilt](https://user-images.githubusercontent.com/37407917/40774654-d3bfee10-64ce-11e8-9311-e643fc6c2264.png)

**Comment by TanelTromp** [comment]
Bugi 2: kontaktiinfo on "italicus", peaks olema tavaline:

![pilt](https://user-images.githubusercontent.com/37407917/40774750-1836c8f2-64cf-11e8-9434-642dd2020b05.png)
