### ISSUE TITLE
Õppeasutuste detailvaate kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#272]
**Üldkirjeldus:**
Portaali kasutajale kuvatakse õppeasutuse detailvaade, et portaali kasutaja saaks vaadata õppeasutuse kohta olemas olevat infot.

**Eeltingimused ja käivitamine:**
- Kasutajale on kuvatud õppeasutuste nimistu (vt https://github.com/hariduspilv/haridusportaal/issues/268). Kasutaja klikkab nimistus kuvatud õppeasutusel.

**Vastuvõtutingimused:**
* Süsteem kuvab kasutajale õppeasutuse (andmeobjekt EducationalInstitution) andmed:
-- Nimetus, registrikood
-- Õppeasutuse tüübid ja alamtüübid  
-- Omandivormi
-- Õppekeeled
-- Hariduslike erivajaduste märge
-- Õpilaskodu/ühiselamu märge
-- Kontaktandmed: Telefon, E-Post, Veebileht.
-- Juriidiline aadress: Maakond, Vald või linn, Asustusüksus, Aadress, Kaardivaade
-- Tegevuskohtade aadressid: Maakond, Vald või linn, Asustusüksus, Aadress, Kaardivaade 

* Alamtüübid kuvatakse vastava tüübi järel sulgudes. Kui õppeasutusel on mitu alamtüüpi, mis kuuluvad sama tüübi alla, siis kuvatakse tüüp üks kord ja selle alla jäävad alamtüübid üksteisel järel komadega eraldatult, näiteks "lasteaed (lastesõim, erivajadustega lastele, 7 aastastele lastele)".

* Andmete juures näha oleval kaardivaade kuvatakse staatiliselt (suurendamine jms kaardi töövahendid pole vajalikud), õppeasutuse asukoht on tsentreeritud ja zoomlevel = 11. Kaardivaate juures saab avada ("vaata kaardi lähemalt") Google Mapi kaardilehe uues veebilehitseja tabis samade parameetritega.

* Õppeasutuse veebileht, kontakti e-posti aadress ja telefoninumber (mobiilis) olema klikitavad. 

**Kasutajaliidese eskiis:**
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b1396ae5c403c452a8f5a30
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b14da160f17ae5b3e60ad16

**Viited**:
Õppeasutuste andmete toimetamine https://github.com/hariduspilv/haridusportaal/issues/104
Alternatiivsed kohad õppeasutuse detailvaatele jõudmiseks on  
-- õppeasutuste kaardivaatel infoaken (vt https://github.com/hariduspilv/haridusportaal/issues/142)

**Comment by heldiraudsepp** [comment]
Testimine 4h

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppeasutuste detailvaate kuvamine
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Edge 16.16299, IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Windows tablet Thinkpad
Keskkond: http://htm.twn.ee/

**Viga 1**: vastavalt kujundusele peavad kooli andmed olema esitatud paksus kirjas.

![image](https://user-images.githubusercontent.com/37401947/43575207-ed336ce4-964e-11e8-8300-8671ce8a0be2.png)

**Viga 2**: gümnaasium peaks olema põhikooli või gümnaasiumi alamtüübiks ja seega esitatud sulgudes.

![image](https://user-images.githubusercontent.com/37401947/43575242-06ad359c-964f-11e8-86ea-c4f3575988d9.png)

Kujunduses on tüüp ja alamtüüp kuvatud järgmiselt (nii on kirjas ka nõuetes):

![image](https://user-images.githubusercontent.com/37401947/43575266-17453580-964f-11e8-92f1-10f6bb40ac4f.png)

**Viga 3**: rohkem ruumi võiks kontaktandmete vahel olla, liiga üksteise otsas on need hetkel.

![image](https://user-images.githubusercontent.com/37401947/43575345-4c1a8e0e-964f-11e8-9b8d-6c5424154d9a.png)

**Viga 4**: vaadata üle kaardi zoom tase, mis hetkel tundub olevat liiga väikse tasemega. Kujunduse zoom on järgmine (lähtub nõuetest):

![image](https://user-images.githubusercontent.com/37401947/43575409-714d1228-964f-11e8-91a3-f353a979e393.png)

Zoom tase portaalis:
![image](https://user-images.githubusercontent.com/37401947/43575437-833939da-964f-11e8-81d4-4ee982fd0bfa.png)

**Viga 5**: kujunduses on õppeasutuse tabel horisontaalselt skrollitav, mobiilis on hetkel tabel tervenisti välja  kuvatud. Kas peaks olema nii nagu kujunduses?

**Märkus1 **: õppeasutuse tegutsemiskohti hetkel pole. Pole hetkel ka EHIS-s olemas. 

**Märkus 2**: omandivormi väli vajab üle vaatamist. See peaks olema kõikidel koolidel EHIS-s küljes, kuid kui koolil on see määramata sisuhalduses, siis portaalis seda välja ei kuvata. Peaks olema alati välja kuvatud.

**Comment by MirellKr2** [comment]
Viga 7: erialadel ei näidata neid andmevälju, millel andmed puuduvad (vt erialade nimistut).

![image](https://user-images.githubusercontent.com/37401947/43641630-1d4a22e0-972d-11e8-9783-dffde3eebdc2.png)

**Comment by MirellKr2** [comment]
**Viga 5 täpsustus**: õppeasutuse detailvaates muutub tabel keritavaks, kui seal on pikad sõnad ja tabel ei mahu korraga mobiili vaatesse ära. Kui tabelis sisalduv info mahub tabelisse nii, et selle saab korraga välja kuvada, siis ei ole keritav.

@mark-shabalin

**Comment by MirellKr2** [comment]
Viga 5 täpsustuse muudatus: mobiilis kuvame tabeli horisontaalselt keritavana, sealjuures kuvame kerimisel sinist kerimisele viitavat ikooni.

**Comment by MirellKr2** [comment]
**Viga 2**: korras (alamtüüp kuvatakse tüübi järel sulgudes).

**Comment by MirellKr2** [comment]
Horisontaalne kerimine korras. @birgitpulk palun vaata üle.

**Comment by birgitpulk** [comment]
Mina ei näe, et nool tekiks tabeli peale? @MirellKr2 @mark-shabalin

**Comment by MirellKr2** [comment]
**Viga 8**: lingi joon puudu. @mark-shabalin 

![image](https://user-images.githubusercontent.com/37401947/44198925-5c6bfc00-a14b-11e8-826c-ad52b6f4307e.png)

**Comment by madispold** [comment]
Stiilide vead parandatud ja tabel scrollib.

Sarnased erialad on siin vaates samas stiilis kui erialade listvaade, kuigi kujunduses erinev. Kas see on muutunud ja kujunduses on korrektne kuju?

**Comment by birgitpulk** [comment]
@madispold  Kujunduses korrektne jah, eelmisel nädalal enne sprindi lõppu muutusid need vaated

**Comment by madispold** [comment]
@birgitpulk Uuel kujul vaated üleval.

**Comment by birgitpulk** [comment]
- [ ] 16 px teksti puhul peab olema reavahe 22px (nt Juriidiline aadress sektsioonis ja igalpool mujal ka kus 16px sisutekst kasutusel)
- [ ] Tervele kaardile klikkimine võiks viia mapsi lehele  (mitte ainult lingile) 
- [ ] Mis otsus on tabeli kuvamisel? nt kui kool ei ole HEV kool, siis praegu kuvatakse "puudub"… kas see on parim lahendus? @andrussarv Mina teeks nii, et kui infot ei ole, siis seda ei kuvata. 

Õppeasutuse detailvaates ei ole võimalik testida erialade sektsiooni, kuna see on puudu.

**Comment by madispold** [comment]
@birgitpulk 
Terve kaardi pealt eemaldati kogu funktsionaalsus (zoom jm) hetkel kasutajamugavuse nimel (Koka soovitusel). Ma arvan, et vajab arutelu, kas see lisada. Muu lahendatud.

@TanelTromp 

Kuvamine: 4. kontaktelefon ja kontakt e-maili aadress - pole võimalik kuvada, BE poolt ei tule väärtust hetkel.
Viga 4: Õige, kui pole õppetaset, siis ta langeb allapoole nimega kõrvuti.
Viga 6: Vaates polegi lae veel loogikat, kõik kuvatud välja hetkel.

**Comment by TanelTromp** [comment]
Viga 4: ei tohiks, peaks jääma samale levelile kogu aeg - vastasel juhul kujundus "hunnikus" (Birgitiga ka räägitud)
Viga 4_2:  esimesel erialal, mis on kuvatud on puudu "õppekraad":

![pilt](https://user-images.githubusercontent.com/37407917/44658461-95d51f00-aa09-11e8-9e09-530cf3743f03.png)

Viga 7 uus: silt "Eriala ei ole aktiivne" tahaks paddingut saada kokku pressitud vaates üles ja alla:

![pilt](https://user-images.githubusercontent.com/37407917/44658436-7ccc6e00-aa09-11e8-87f7-2e086c1821b9.png)

**Comment by madispold** [comment]
Viga 4, 4_2: See 1. järgne vahe on kujundusest tulenev pealkirja "ERIALAD" järgne padding:
PILT:![Screen Shot 2018-08-27 at 15.02.51.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/284ad180-369f-469a-bc04-ca98a734a3d4)

Muidu kuvab sellisel juhul nõnda:
PILT:![Screen Shot 2018-08-27 at 15.16.52.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/9454c46e-f798-4bd9-ae3d-a4e5782d4dcb)

Viga 5: Scrollbarid kadunud ja tabel keritav vaid "overflow" korral, mis brauseris ei tööta? (Ise vaatasin chrome, edge Windowsil)
Viga 7: Ruumi lisatud.

**Comment by madispold** [comment]
+ ootab 2 tõlget pileti, mis välja toodud pilet #153 all. @TanelTromp

**Comment by TanelTromp** [comment]
Viga 8: peaks kuvama loaderit erialade kuvamiseks - nt aeglasema ühenduse puhul tekivad need jupp aega, siin pühiühenduse näide ja enamvähem:
https://gyazo.com/bc7bc13df3b161fa44235b316894c6ac

**Comment by madispold** [comment]
Viga 8: Nüüd kuvab loaderi.

**Comment by birgitpulk** [comment]
@TanelTromp  anna teada, kui võin selle vaata ka üle käia

**Comment by TanelTromp** [comment]
@birgitpulk palun - lava on teie! Minu poolt ok!

**Comment by TanelTromp** [comment]
Viga 8: läbivad suured tähed tekkinud ja ühes kohas väike, peaks olema suur (õppeastutuse tüüp):
![pilt](https://user-images.githubusercontent.com/37407917/44703758-7d184800-aaa1-11e8-9990-2e4ee0e3f6c5.png)

Viga 9: "Tegutsemise asukoha" kaarti mitte kuvada (Andrus)

**Comment by madispold** [comment]
Viga 8: Korras
Viga 9: Korras
@TanelTromp

**Comment by TanelTromp** [comment]
Viga 8: veel siin suured tähed (kontakt):

![pilt](https://user-images.githubusercontent.com/37407917/44712029-84971b80-aab8-11e8-9619-0a1110992edc.png)

Viga 8.2 "Spetsialiseerumine" väli...kõik peale koma tulevad väärtused peaks olema suure algustähega:

![pilt](https://user-images.githubusercontent.com/37407917/44712104-b0b29c80-aab8-11e8-993e-841381e2bf53.png)

Viga 10: "õppekava maht" EAP, mitte Eap:

![pilt](https://user-images.githubusercontent.com/37407917/44712142-ca53e400-aab8-11e8-80e6-ea7b339023e4.png)

Viga 9.2: ka eriala detailvaates, peaks siis see "Tegutsemise asukoht" kaduma @andrussarv 

![pilt](https://user-images.githubusercontent.com/37407917/44712191-e6f01c00-aab8-11e8-9b45-d54edca24979.png)

**Comment by birgitpulk** [comment]
Minu poolt korras

**Comment by madispold** [comment]
Viga 8: Korras
Viga 8.2: Korras
Viga 9.2: Korras
Viga 10: Korras

10 ning 8.2 sõltuvad küll ka sisendist ehk mis andmed on baasis, aga enam front nende kuju ei muuda v.a suur algustäht.

@TanelTromp
