### ISSUE TITLE
Luua RSS-aadress

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#274]
Eesmärk, üldkirjeldus:
On võimalik kasutada portaali RSS voogu ('RSS voog" on üldtermin, rakendatav spec: Atom 1.0)

Vastuvõtutingimused:
- [ ] On loodud RSS võimalused back-endis. 
- [ ] RSS voog kehtib uudistele ja sündmustele.
- [ ] Kasutaja saab valida sildid, mille kohta RSS-i soovib (täiendus sprindi käigus)

Testime front-end pileti kaudu #273

**Comment by heldiraudsepp** [comment]
vaja juurde teha frondi pilet @EgleM-TW

**Comment by EgleM-TW** [comment]
Frondi pilet on olemas - #273. Vajalik on arendajate ja Birgitiga arutada ja kirjeldada, kuidas lahendada, et saaks valida ka silte.

**Comment by TanelTromp** [comment]
Viga 1: Chromega, vajab extensionit (CNN-i RSS nt töötab kenasti):
![pilt](https://user-images.githubusercontent.com/37407917/44219125-f2bc1400-a183-11e8-8cae-234414d8b82a.png)

Viga 2: mobiiliga ei ava, kas peab mingi plug-in olema?

Viga 3: IE11 näitab author missing kirjet:
![pilt](https://user-images.githubusercontent.com/37407917/44248946-2768b380-a1f6-11e8-9f9b-2aa3979a68fc.png)
