### ISSUE TITLE
Koodi optimeerimine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#282]
## Breadcrumbs
- [x] Breadcrumbsid teha komponendina. Komponendi sisendiks peab olema array <breadcrumbs [input]='breadcrumbsArray'>.
- [x] Sisend array peab sisaldama kõiki vajaminevaid breadcrumbsi osakesi. Väljaarvatud "avaleht" selle paneme {{ 'frontpage' | translate }} stiilis kuna see ei ole muutuv.
- [x] graphql päringud peavad olema breadcrumbsi sees

## Datepicker
- [x] Backspace-ga kuupäeva kustutades peab kaldkriipsu eemaldades ka ühe kuupäeva numbri kustutama. Ehk siis kasutajale on visuaalselt kaldkriips olemas aga kustutades ei tohi talle seda eksisteerida.

## Sündmuste ja Uudiste filter
- [x] Filter peab olema komponendina
- [x] Mõlemas vaates peab olema kasutusel sama komponent.
- [x] Kui filtrites "Otsi vajutada" peab otsingu tulemused queryna aadressiribale panem (/et/sundmused?title=Otsin&dateFrom=xx-xx-xxxx&dateTo=xx-xx-xxxx)
- [x] Kui aadressireal query parameetrid muutuvad peavad need tulemused filtri väljadesse minema
- [x] Filtreeritav tulemus peab olema jagatav teisele kasutajale (url copy paste)
- [x] Filter, Aadressiriba, Filtrite tulemused peavad olema eraldiseisvad ja ei tohi üksteisest sõltuda.
- [x] Filtrite output list peab kuulama pealt aadressi muutmist ja käivitama requesti vastavalt vajadusele.

**Comment by doomler** [comment]
1,2 - 30m
3 - 2h
4,5 - aravan et ei ole vaja, minu jaoks parem teha eraldi komponendina, kui seda ei sobib siis if else ~ 30min
6,7,8,9,10,11 - 5h
