### ISSUE TITLE
lemmikuks lisamine 

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#285]
NB! Realiseerida samas sprindis ka #332 BE töö.

**Üldkirjeldus**

Kasutaja soovib salvestada portaali sisulehte.

Süsteem võimaldab sisse loginud kasutajal salvestada töölauale sisulehti. 

1. Sisse loginud kasutajale kuvatakse sisulehtedel — SimpleArticlePage , TypeOneArticlePage, News, Event — lemmikuks lisamise märki.

**Eeltingimused ja käivitamine**
1. Kasutaja on portaali sisse loginud ja avanud:
 - sisulehe 
 - uudise detailvaate
 - sündmuse detailvaate

**Vastuvõtutingimused**

Kasutajale kuvatakse lemmikuks lisamise märki:
- [x] SimpleArticlePage
- [x] TypeOneArticlePage
- [x] News
- [x] Event
- [x] Kooli_detailvaade
- [x] Õppekava_detailvaade

**Kasutaja saab märgile klikates:**
- [x] salvestada sisulehe töölauale. Lisamisel tekib snackbar tekstiga "Leht lisatud lemmikuks. Lemmikuid näed enda Töölaualt" Link töölauale

**Kasutaja saab:**
- [x] salvestada kuni 10 lemmikut
- [x] **TÄIENDUS!** lemmiku sisulehelt eemaldada (kustutada). Eemaldamisel tekib snackbar tekstiga "Lehekülg on lemmikutest eemaldatud". 
- [x] ** TÄIENDUS** kui kasutajal on 10 lemmikut salvestatud ja ta üritab salvestada 11-ndat, siis süsteem kuvab veateadet modaalis "Portaalis saab salvestada kuni 10 lemmikut. Kustutamiseks eemalda leheküljelt täheke" modaal avaneb >10 ehk 11 lemmiku lisamisel.

**Kasutaja ei saa:**
- [x] muuta töölaual lemmikute järjekorda
- [x] muuta lemmiku nimetust

**Töölaual Lemmikute kuvamise nõuded:**
- [x] Vaikimisi kuvatakse kõiki kasutaja lemmikuid (max 10tk)
- [x] Kui kasutajal Lemmikud puuduvad, kuvatakse blokis . ..vt disaini https://zpl.io/2vWKxNQ

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Lemmiku kuvamise disain sisulehel: https://zpl.io/VQE17vW
Lemmik lisatud disain (snackbar): https://zpl.io/VxlrXwE - **TÄIENDATUD**

**TÄIENDUS!** Tähekesel ja jagamismärgil on tooltip.

Viited:
BE töö: #22
Töölaua parema serva kujundust näeb töölaua piletitest, https://zpl.io/VKlKROP.

**Comment by srautam** [comment]
Sulgemine võiks olla tabiga, lükkasin #404 Kokkale edasi selle

**Comment by TanelTromp** [comment]
Ootaks "töölauda" järele

**Comment by birgitpulk** [comment]
Kui lemmiku ära võtad, siis võiks tekkida snackbar tekstiga "Artikkel on lemmikutest eemaldatud". Tähekesel ja jagamismärgil võiks olla tooltip. 

Snackbari värvi muutus (eduka protessi roheline): https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b87aba7a7323c4e2e82d257

**Comment by TanelTromp** [comment]
Viga 1: lemmikuks lisamise märgi ja sotsiaalmeedia jagamise märgi asukohad on vahetuses. Zeplini järgi on vastupidi (õige järjekord on ainult "erialade" puhul hetkel ehk sotsmeedia paremal, lemmik vasakul).

Viga 2:  linnukesed tegemata

![pilt](https://user-images.githubusercontent.com/37407917/44982106-65e3c980-af7d-11e8-9875-af7a918068e3.png)

**Comment by srautam** [comment]
Viga 1: lemmikuks lisamise märgi ja sotsiaalmeedia jagamise märgi asukohad on vahetuses. Zeplini järgi on vastupidi (õige järjekord on ainult "erialade" puhul hetkel ehk sotsmeedia paremal, lemmik vasakul - Mozilla, Chrome).

Viga 2: linnukesed tegemata

pilt

Viga 3: tingimus ei ole täidetud: "TÄIENDUS! Tähekesel ja jagamismärgil on tooltip."

Viga 4: tõlge puudu "Eemaldamisel tekib snackbar tekstiga "Lehekülg on lemmikutest eemaldatud":

pilt

Viga 5: iPhone 6 vaatel ei ole lemmiku lisamisel snackbaril CTA-d "Vaata oma töölauda" (vajab teise iPhonega kontrollimist - Samsung A5-l nt olemas))

Viga 6: "Minu lemmikute" kujundus töölaual ei vasta zeplini kujundusele (võib olla selle pileti väline ehk töölaua/avalehe pilet):
https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b7ea5971d6b03591e0547e2

Viga 7: modaali tekst ei ole täpne. Peab olema: "Portaalis saab salvestada kuni 10 lemmikut. Kustutamiseks eemalda leheküljelt täheke"

On:
pilt

Viga 8: Edgega/IE-11ga on snackbar katki:

pilt

Viga 9: Edgega/IE 11-ga ikoonid 1teisest kaugel:

pilt

Viga 10: EDGE/IE-11ga on modaal katki:

pilt

Viga 11: sotsiaalmeedia jagamise ja lemmikute ikoonid vales kohas mobiilivaates, õige on:

https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b8d1c2c61d19505667f170d

**Comment by TanelTromp** [comment]
Viga 2: linnukesed tegemata

 Viga 4: tõlge puudu "Eemaldamisel tekib snackbar tekstiga "Lehekülg on lemmikutest eemaldatud":

Viga 5: iPhone 6 vaatel ei ole lemmiku lisamisel snackbaril CTA-d "Vaata oma töölauda" (vajab teise iPhonega kontrollimist - Samsung A5-l nt olemas))

 Viga 7: modaali tekst ei ole täpne. Peab olema: "Portaalis saab salvestada kuni 10 lemmikut. Kustutamiseks eemalda leheküljelt täheke"

Viga 9: endiselt kaugel EDGEga (100% view, full view):

![pilt](https://user-images.githubusercontent.com/37407917/45405868-357ee800-b66d-11e8-8dcc-7562e978cddd.png)

Viga 11:  kujundus katki:

![pilt](https://user-images.githubusercontent.com/37407917/45406058-df5e7480-b66d-11e8-8225-0ccaf9f2a8c3.png)

**Comment by TanelTromp** [comment]
Viga 7: modaali tekst ei ole täpne. Peab olema: "Portaalis saab salvestada kuni 10 lemmikut. Kustutamiseks eemalda leheküljelt täheke"

![pilt](https://user-images.githubusercontent.com/37407917/45468582-febcd680-b72d-11e8-868c-5ccf08ce12b7.png)

Viga 12 (uus): kui liikuda sisult, mis on lemmikuks lisatud sisule, mis ei ole, siis näitab viimase puhul esialgu, et on (st täheke on täidetud):
https://gyazo.com/8586f33c87cad7fbce7ec4d9cee626dd

**Comment by RaimoJohanson** [comment]
Viga 7: (tõlge) @lsoonvald  @ruut12 
viga 12: parandatud

**Comment by lsoonvald** [comment]
Viga 7: parandatud.

**Comment by srautam** [comment]
Snackbar Birksiga läbi räägitud ja korras.

**Comment by birgitpulk** [comment]
- [ ] Lemmiku eemaldamisel on snackbari kujundus vale (ei ole vasakus servas rohelist ala)
- [ ] Lemmiku snackbar ei tõuse piisavalt siiski esile, lisame talle lisaks raamile ka taustavärvi #E6F5EF
- [ ] Lisasin uudise lemmikuks, tekkis kiri, et lemmikuks lisatud ja siis samal ajal ka modaal et lemmikuks saab lisada kuni 10 artiklit vms. Kuidas modaal ja lemmiku kinnituse kast saavad koos tekkida? @TanelTromp palun testi seda ka

**Comment by RaimoJohanson** [comment]
Viga parandatud ("närviline" vajutamine) @TanelTromp

**Comment by TanelTromp** [comment]
@birgitpulk palun vaata üle, kas sinu raporteeritud vead on OK!

**Comment by birgitpulk** [comment]
Minu poolt ok!
