### ISSUE TITLE
Sündmuste avalehel kuvamine 

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#3]
**Üldkirjeldus:**
Portaali kasutajale näidatakse avalehel sündmusi (Event), et juhtida kasutaja tähelepanu haridusvaldkonnas toimuvale.

**Eeldused ja käivitamine:**
_Puuduvad (kohe avalehel näha)._

**Vastuvõtutingimused:**
* Sündmuse kohta kuvatakse nimetus (name), lühikirjeldus (shortDescription, kuni 150 sümbolit), toimumise kuupäev (EventCalendarItem.eventDate), alguse kellaaeg (EventCalendarItem.startTime), toimumise koha nimetus (locationName), toimumise koha aadress (locationAddress
* Kuvatakse kuni 2 järgmisena algavat sündmust. Sündmused on järjestatud alguse aja järjekorras (varem algav eespool).
* Kui sündmusel on mitu toimumisaja (EventCalendarItem) kirjet, siis andmed võetakse kõige varasema toimumise kuupäevaga ja alguse ajaga kirjest.
* Avalehel kuvatud sündmuselt saab minna vaatama sündmuse detailvaadet (https://github.com/hariduspilv/haridusportaal/issues/100).
* Avalehelt saab minna vaatama sündmuste nimistut (https://github.com/hariduspilv/haridusportaal/issues/98).

**Kasutajaliidese prototüüp:**
https://6aofpb.axshare.com/#g=1&p=avaleht_men__ga_lg (vt plokk "Sündmused")

**Comment by Kyllike** [comment]
#3_HTM

Viga?: 
Vastuvõtutingimused ütlevad:
Kuvatakse kuni 2 järgmisena algavat sündmust. Sündmused on järjestatud alguse aja järjekorras (varem algav eespool).

Hetkeolukord: sisestatud on sündmused toimumisajaga 25.05, 05.06 ja 21.10. 
![image](https://user-images.githubusercontent.com/38042389/40783649-c8de65fe-64eb-11e8-807e-5b8c43a82986.png)

Avalehel kuvatakse sündmus toimumisajaga 21.10, ehkki peaks justkui kuvama kas 05.06 toimuvat või nii 05.06 kui 21.10 toimuvat?

![image](https://user-images.githubusercontent.com/38042389/40783722-05cb1778-64ec-11e8-9303-014a31b3c078.png)

**Comment by TanelTromp** [comment]
Jah aga hetkel juba uus avalehe MD disain, kus on kuvatud kolm viimast sündmust ehk selle pileti võiks kinni panna ja vastavalt avalehe teiepoolsele kinnitusele ning tingimustele edasi toimetada vastavalt.
@Kyllike @heldiraudsepp
