### ISSUE TITLE
JUHAN liides

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#302]
Epic - Sündmuste kalender - #4 

**Sissejuhatus**

**Kirjeldavad tööd**
JUHAN koolitused back-end #5 ja ülekanne kalendrisse #27 
Koolituste otsing ja kuvamine #25 

JUHAN-ga liidestuse täiendused - analüüs: #302 
#718 - sisuhalduse täiendused
#719 - import
#720 - nimistu vaate täiendused
#721 - kalendri vaate täiendused
#722 - detailvaate täiendused

**Teenuse kirjeldus**

Väli haridusportaalis | Tüüp | Piirang | Koh | vaste Juhanis
-- | -- | -- | -- | --
Sündmuse   id |   |   | * | ÕK   toimumine: toimumise ID
Sündmuse   nimetus | String | 150 | * |  
Lühikirjeldus | String | 300 | * | ÕK   kirjeldus: Kokkuvõttev lühikirjeldus
Kirjeldus | Text | Piirang   puudub | * | ÕK   kirjeldus: Õpiväljundid
Toimumise   koha nimetus | String | 50 |   | ÕK   toimumine: venueName
Toimumise   koha aadress | String | 50 |   | ÕK   toimumine: venueAddress, venueCity, venueCounty, venueCountry
Toimumise   koha asukoht kaardil |   |   |   |  
Korraldaja   nimi (asutuse nimi) | String | 50 |   | ÕK kirjeldus: Korraldaja
Kontaktisik | String | 50 |   | ÕK kirjeldus:   Kontaktisik
Kontakttelefon | Telephone |   |   | Person: telefon
Kontakt   e-posti aadress | Email |   |   | Person:   e-post
Viide   (url) Juhani lehele |   |   |   | PublicUrl
Osalejatele   praktiline info | String | 500 |   | ÕK toimumine: lisainfo
Toimumise   kuupäev – nii algus kui lõppkuupäev | Date |   | * | ÕK toimumine:

**Comment by EgleM-TW** [comment]
Oli topelt pilet, muutsin teise teema vastu

**Comment by andrussarv** [comment]
**Andmed ja BE:**
- entryType uus väärtus "JUHAN"
- sündmus põhikuupäeva juurde lõpu kuupäev
- sündmus põhikuupäeva juures alguse ja lõpu kellaaeg mittekohustuslikeks
- lisada juhani id (väline ID)

Andmete imoprti liides teha.

**FE**
