### ISSUE TITLE
Menüü kohendused I

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#303]
Lahendada viga: Lehele minnes ei ole tihti vasakmenüüd (Google Chrome 66.0.3359.139, Mozillas ka), peale hard refreshi tuleb tagasi. 
+ Kategooria võimaluse lisamine menüüsse

**Comment by madispold** [comment]
Kategooriate lisamine võimaldatud:

Sisestada peatasemele element pathiga "#category"

**Comment by madispold** [comment]
@TanelTromp
