### ISSUE TITLE
Menüü kohendused II

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#304]
- [x] Vasakmenüü > Noolega menüüpunkt > Selle alt avanev menüüpunkt võiks olla sammuga, mitte teistega samal tasandil (nt 24px paremale). 
- [x] Päis > Logi sisse dropdown stiilimata (Birgit tegi joonise ette). 
- [x] Päis > Logi sisse ikoon võiks ka dropdowni avada (hetkel ei tee midagi). 
- [x] Sisse ja välja logimisel ikoon ja logi link panna ühe elemendi sisse. 
- [x] Päis > "X" võtta maha. 
- [x] Menüüsse  lisada kategooriad. 
- [ ] Menüül scrollbar ära kaotada (praegu Win arvutites miskipärast näitab skrollbaari).

**Comment by madispold** [comment]
Tehtud @birgitpulk @TanelTromp

**Comment by birgitpulk** [comment]
Minu poolt ok, viimane teema @TanelTromp testimiseks

**Comment by TanelTromp** [comment]
Okei! kui piksleid taga ei aja. ("Logi sisse dropdown" on desktopis kõrgemal kui päise sinine äär ja mobiilis samal joonel sellega).
Pilet offtopic: kui ei ole lisatud ühtegi parema veeru elementi artiklisse, siis mobiilivaates (+tahvel) võiks paddingut/õhku rohkem all olla.
Siin maks alla kerimisega vaade:
![pilt](https://user-images.githubusercontent.com/37407917/42327384-3d1c0716-8074-11e8-86d0-ae88df76c5d0.png)

@birgitpulk @madispold

**Comment by madispold** [comment]
Tehtud. @TanelTromp

**Comment by birgitpulk** [comment]
Nõus, et võiks olla rohkem ruumi jaluses, nt 72px

**Comment by madispold** [comment]
Tehtud.
