### ISSUE TITLE
Meedia mittekuvamise veakäsitlus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#305]
Süsteemivälise meedia (kaardi, video) mittekuvamisel on puudu placeholder pilt või joonis, mida kasutajale kuvada, kui kaarti pole või videot pole.

**Comment by ruut12** [comment]
FE töö

**Comment by madispold** [comment]
@TanelTromp @andrussarv

**Comment by EgleM-TW** [comment]
Selle kohta nõuet ei leidnud ja seega realiseeritud lahendus peaks olema piisav. Vajadusel naaseks teema juurde siis kui põhifunktsionaalsused on valmis, lisatööde etapis.

**Comment by madispold** [comment]
Kaardi veateade:
![Screen Shot 2018-07-06 at 11.21.21.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/bc50c91f-4664-4ebd-907a-dfc5c413dfa5)
