### ISSUE TITLE
Uudiste ja teavituste tellimise kohendused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#307]
- [x] Uudiskirja tellimuse õiged kinnitustekstid puudu (kujunduses peaksid olemas olema)
- [x] Uudiste listvaade > Mingis kohas on näha kirbukirjad neljandast reast, ei peaks olema. Ja piltide kõrgused on erinevad (ei võta õiget pilti).  
- [x] Uudiste listvaade > Otsing > Kuupäeva valik > datepickeri avanemisel läheb lehekülje taust tumedaks, ei peaks minema 
- [x]	Süsteemi välised (teksti sees olevad) lingid peaksid avanema uues aknas ja ikoon peab olema küljes kui on väline link. Akordioni osas välised lingid ei avane teises tabis (peaksid avanema). 
- [x] Disaini rakendamine teavituste tellimisele avalehel

**Comment by madispold** [comment]
Testimisse @birgitpulk @TanelTromp

**Comment by birgitpulk** [comment]
@madispold Kas see, et uudiskirja kast on täis laiuses, see veel muutub eks? 

Hetkel sain sellise maili tagasi kui uudiskirjaga liitusin (lingid ei ole klikitavad): 
<img width="1040" alt="screen shot 2018-07-04 at 15 12 08" src="https://user-images.githubusercontent.com/24669779/42276533-ca9e21ba-7f9c-11e8-9f69-ee24a056c627.png">

Peale uudiskirja tellimist on peamenüüs 2 linki valitud: 
<img width="1378" alt="screen shot 2018-07-04 at 15 13 57" src="https://user-images.githubusercontent.com/24669779/42276584-fa0d7a04-7f9c-11e8-86b0-718a76eee55e.png">

**Comment by madispold** [comment]
Kui tuleb esilehe kinnitatud kujundus, siis vastavalt sellele sobitame kasti.

Meili sisuga BE tegeleb hetkel, sellest ka katki, kuid nüüd on vähemalt õiged ja klikitavad need lingid seal.

Menüüs on keelatud link lisatud sisuhaldusest, mida hetkel FE ei kontrolli ega peitu pane. See ei ilmne vaid peale uudiskirja tellimist vaid ongi hetkel esilehel.

**Comment by birgitpulk** [comment]
Ok, siis minu poolt korras! @TanelTromp ?
