### ISSUE TITLE
Õppeasutuste kuvamine kaardil

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#31]
**Üldkirjeldus:**
Kuvada portaali kasutajatele õppeasutuste andmed kaardil, et kasutaja saaks leida teha huvitavas asukohas asuvat õppeasutust. 

Õppeasutuste andmed saadakse EHIS-e avaandmetest, seega sisuliselt  on tegemist EHIS-e avaandmete visualiseerimisega (EHIS-st andmete võtmist kirjeldab https://github.com/hariduspilv/haridusportaal/issues/105).

**Eeltingimused ja käivitamine:**

*  Õppeasutuste kaardi nägemiseks kasutaja valib menüüribalt "Õppeasutused".

**Vastuvõtutingimused:**
* Süsteem kuvab kaardil õppeasutuste asukohad. Kuvatav õppeasutus peab olema märgitud avaldatavaks (publish = 'true') ja asukohal peavad olema geograafilised koordinaadid (location.geoCoordinatesLat ja ...Long).
* Süsteem avab kaardi vaikimisi Eesti ulatuses (täpsustada vaikimisi  _boundigbox-i_ nurkade koordinaadid).
* Süsteem kuvab kaardivaate _boundigbox-i_ sisse jääva õppeasutuste asukohtade kohta asukohamarkerid. 
* Kasutaja saab kaarti suurendada-vähendada (sisse-välja zuumida).
* Kasutaja saab kaarti nihutada.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kasutajaliidese eskiis**:
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b057a6d42f5694e26594723
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b06afd8923fdb282158d3b6

**Viited:**
Õppeasutuste andmete toimetamine https://github.com/hariduspilv/haridusportaal/issues/104.
Õppeasutuste filtreerimine https://github.com/hariduspilv/haridusportaal/issues/130.
Õppeasutuse kohta kaardil infoakna kuvamine https://github.com/hariduspilv/haridusportaal/issues/142.
Õppeasutuste kuvamine nimistuna https://github.com/hariduspilv/haridusportaal/issues/268.

**Comment by heldiraudsepp** [comment]
Jääb testimine kui elasticsearch on tehtud https://github.com/hariduspilv/haridusportaal/issues/343

**Comment by skeefee** [comment]
@MirellKr2  palun testida

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppeasutuste kuvamine kaardil
Testimise tegevused: funktsionaalsete nõuete testimine

Brauserid: Chrome 66; Mozilla 59; Edge 16.16299, IE 11
Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A8 + Chrome
Windows tablet Thinkpad
Keskkond: http://htm.twn.ee/

**Probleem 1**: kaarti ei avata vaikimisi terves ulatuses (nõue - süsteem avab kaardi vaikimisi Eesti ulatuses (täpsustada vaikimisi boundigbox-i nurkade koordinaadid)). Kuidas peaks avama mobiilis? Kas samuti terves ulatuses? 

![image](https://user-images.githubusercontent.com/37401947/43514194-538e42ec-9588-11e8-93bc-a81604fe72e6.png)

**Probleem 2**: kaardil avamisel kuvatakase väga väike hulk asukohamarkereid. Kaardi suurendamisel ilmuvad asukohamarkerid viitega (kuni 10 sekundit). Markerite kuvamine on hetkel aeglane.

![image](https://user-images.githubusercontent.com/37401947/43514388-c81604a6-9588-11e8-9910-3a5fba32d40a.png)

**Probleem 3**: õppeasutuse mitte avaldatuks märkimisel kaob kool ära koolide nimistust (viga sisuhalduses). Kaardil toimib korrektselt (mitte avaldatuks märgitud õppeasutust kaardil ei kuvata).

![image](https://user-images.githubusercontent.com/37401947/43514353-b90922b8-9588-11e8-81f2-f85aa239be0b.png)

**Probleem 4**: kaardil esineb mitmeid mitte-klikitavaid asukohamarkereid.

![image](https://user-images.githubusercontent.com/37401947/43514457-e82e0e46-9588-11e8-9f6c-f964fb00c173.png)

**Probleem 5**: mobiilis testides esines mitmel korral olukordi, kus markerile klikkides kadus see ära.

@lsoonvald @skeefee

**Comment by MirellKr2** [comment]
Asukohamarkerite kuvamise probleemi lahendab elasticsearch, mida rakendatakse järgnevates sprintides.

**Comment by MirellKr2** [comment]
Probleem 3 on seotud sisuhalduri kasutajaõigustega (sisuhaldurile ei kuvata avaldamata õppekavasid).

**Comment by skeefee** [comment]
Viga 1: Korras. Kaart peab ümber markerite olema
Viga 2: Ootame backendi päringute kiirenemiseni
Viga 4: Kui kaardil on identsete koordinaatidega asukohad siis see ka nii käitub. Palun backendilt mingit lahendust
