### ISSUE TITLE
Menüü kohendused III

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#310]
Sündmuse ja uudiste detailvaates olles võiks olla Sündmused / Uudised menüüpunkt indikeeritud

**Comment by madispold** [comment]
Testimisse. @TanelTromp

**Comment by MirellKr2** [comment]
Vearaportis välja toodud viga ei käi antud pileti sisu alla, mistõttu ei kuulu antud viga parandamisele selle sprindi/pileti raames. Menüü sisuks olnud aktiivsete menüüpunktide kuvamine toimis korrektselt ja ootuspäraselt.
