### ISSUE TITLE
Emailide administreerimine I 

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#311]
Emailid adminnitavaks:

- [x] teavituste tellimuse kinnitus (uus), 
- [x] tellimise muudatuse kinnituse, 
- [x] teavitus, 
- [x] sündmusele registreerimise kinnituse, 
- [x] sündmuse korraldajale registreerimise teavitus

Lars - teavitused, Ruut - sündmused

**Comment by TanelTromp** [comment]
TEST

- [x] teavituste tellimuse kinnitus (uus), 
- [x] tellimise muudatuse kinnituse, 
- [x] teavitus, 
- [x] sündmusele registreerimise kinnituse, 
- [x] sündmuse korraldajale registreerimise teavitus
