### ISSUE TITLE
Sisuhalduse testimine

### ISSUE THREAD

**Issue by MirellKr2** [hariduspilv/haridusportaal#315]
### Seotud piletid
Artikli toimetamine: #128, #181, #138 
Sündmuse toimetamine: #1, #180, 
Uudise toimetamine: #11 
WYSIWYG redaktor: #15

**Comment by MirellKr2** [comment]
@lsoonvald @ruut12 

### Uudise toimetamine

**Probleem 1**: vasakpoolne autor on artikli sisestaja nimi. Parempoolne tegelikult ju kasutajaroll (ehk võiks selle asendada sõnaga “Autor” -> “Kasutajanimi/Kasutajaroll”).

![image](https://user-images.githubusercontent.com/37401947/41909579-03499e34-7950-11e8-8ecf-93bb5a6013c4.png)

**Probleem 2**: #179 pileti järgi peaks sissejuhatuse max pikkus olema 500 tähemärki, hetkel on Drupalis pandud piiranguks 300.

**Probleem 3**: kuidas kasutaja peaks teadma, et ta selle kellukese alt peaks veateateid vaatama? Hetkel jääb mulje, et salvestumine justkui õnnestus, kuna erroreid kohe ei ilmunud. Kas seda paremini ei saaks lahendada? Nt oleksid veateated kohe avatud, mitte kasutaja ei pea neid ise avama. Veateadete puhul peab olema selge, millise välja juures probleem tekkis.

![image](https://user-images.githubusercontent.com/37401947/41909662-46d0d690-7950-11e8-9efc-98c6c6238d59.png)

**Probleem 4**: avaldamise ja loomise kuupäev võivad olla erinevad. Loomise kuupäev tekib automaatselt, avaldamise kuupäev tekib siis, kui kasutaja märgib uudise avaldatuks. Eeldan, et avaldamise kuupäev kuvatakse listi vaates pärast uudise salvestamist. Loomise kuupäeva pole analüüsipiletis eraldi kirjeldatud.

![image](https://user-images.githubusercontent.com/37401947/41909725-76473d4c-7950-11e8-986b-7affc9e01c96.png)

**Probleem 5**: miks nupu kõrval olev Upload väli on klikitav?

![image](https://user-images.githubusercontent.com/37401947/41909802-9c20ffee-7950-11e8-9f1d-68559c7b517c.png)

**Probleem 6**: Alt tekstil ja pildi pealkirjal peaks olema pikkuse piirang vastavalt piletile #179.

![image](https://user-images.githubusercontent.com/37401947/41909851-b18bd692-7950-11e8-96ed-27d1371e96d6.png)

**Probleem 7**: ei saa sellest toimingud label-ist aru, paikneb veidral kohal. Mis need toimingud peaksid olema?

![image](https://user-images.githubusercontent.com/37401947/41909912-de428b36-7950-11e8-9c02-3ba0bb57bce9.png)

**Probleem 8**: mida tähendavad negatiivsed kaalud? Kaalud avanevad osaliselt eemalda nupu peal.

![image](https://user-images.githubusercontent.com/37401947/41909947-fdbb4372-7950-11e8-9c8a-c8f44954dc5a.png)

**Probleem 9**: teisel ja kolmandal pildil ei saa kaalusid valida.

![image](https://user-images.githubusercontent.com/37401947/41909989-17230534-7951-11e8-9ba3-d883a2966cfb.png)

**Probleem 10**: mida teeb eemalda valitud nupp? Vaadata üle nuppude nimetused, kuna esimese pildi juures on nupu nimetus "Eemalda". Hoida nuppude ja väljade nimetuste juures ühtlust. 

![image](https://user-images.githubusercontent.com/37401947/41910016-2d3d7b10-7951-11e8-8b83-a5e0a0a498f8.png)

**Probleem 11**: selle koha peal ei peaks ilmuma pildi lisamise nuppu, kolm pilti on eelnevalt lisatud. Kujundus erineb eelmisest pildi lisamise nupust.

![image](https://user-images.githubusercontent.com/37401947/41910081-53ce19f6-7951-11e8-9079-cabfc9e99f8d.png)

**Probleem 12**: checkbox-i taga ei paista olevat funktsionaalsust.

![image](https://user-images.githubusercontent.com/37401947/41910140-7724ff3c-7951-11e8-971f-cd7a7cf80705.png)

**Comment by EgleM-TW** [comment]
Kahe klaviatuuri ja hiirega töö tekitas mõned valed käigud :D

**Comment by EgleM-TW** [comment]
@MirellKr2 

Mõned täpsustused:
1. Peakasutaja saab luua uue lk; sisuhaldur saab ainult muuta ja avaldada - [nõuded ](https://github.com/hariduspilv/haridusportaal/wiki/Kasutus%C3%B5igused)
2. Kui lk ei seota menüüpunktiga siis seda ei kuvata välja. Kuna menüü on hetkel loomata, siis selle teema kirjeldame kasutajajuhendis ja ei pea testima.
3. Lk saab salvestada ilma akordionita (SimpleArticlePage), samas kui kasutaja soovib luua lk koos akordioniga (TypeOneArticlePage), siis akordionis pealkirja (paragraphTitle) väli on kohustuslik täita. Vahepealkirja (accordionSubPageTitle) akordioni osale pole - õige on vastavalt kujundusele ainult (paragraphTitle).
4. Jrk muutmine akordionis - lohistamine ja kaalud on sama tulemusega tegevus.
5. Mitu kasutajat saab samaaegselt ühte lk toimetada, samas vähe tõenäoline olukord. Võiks situatsiooni testida, et kas mingid muudatused lähevad kaotsi. Ja siis otsustame uue töö, kui on tarvis. Täpsemad nõuded siin puuduvad.
6. Artikkel meie maailmas on sisutüüp (avaldamise ja muutmise kp ei oma mingit tähtsust)  ja News on sisutüüp ja siin on avaldamise kp oluline.

**Comment by MirellKr2** [comment]
@ruut12 @lsoonvald 
**Sündmuse toimetamine** 

**Probleem 1**: välja nimetus võiks olla “Sündmuse pealkiri” või lihtsalt “Pealkiri” nagu uudisel.

![image](https://user-images.githubusercontent.com/37401947/42022755-c2f7377e-7ac6-11e8-844f-21f66343151d.png)

**Probleem 2**: välja nimetus peaks olema “Sündmuse tüüp”.

![image](https://user-images.githubusercontent.com/37401947/42023268-1f0588ee-7ac8-11e8-9e9c-8f4a01bcba15.png)

**Probleem 3**: kuna “Sündmuse tüüp” peab olema kohustuslik väli (väli peaks olema tähistatud * märgiga).

![image](https://user-images.githubusercontent.com/37401947/42023294-310d490a-7ac8-11e8-8aac-f92e95487bd0.png)

**Probleem 4**: tervel lehel võiks kasutada samasid väljanimetusi (algul on sündmus ja poole pealt on üritus). Kasutaks igal pool “Sündmus … “.

![image](https://user-images.githubusercontent.com/37401947/42023326-433b520c-7ac8-11e8-93ab-c115434f745e.png)

**Probleem 5**: lingi pealkiri peaks olema kohustuslik. Hetkel saab salvestada ilma pealkirja lisamiseta. Lisaks peaks alumina checkbox olema linnutatud, kuna vaikimisi peaks avama lingi uuel vahelehel (nii on piletis nr 15 kirjas).

![image](https://user-images.githubusercontent.com/37401947/42023365-5993cd54-7ac8-11e8-83f9-e9e9d8b6f9c3.png)

**Probleem 6**: piletis nr 15 on kirjas, et redaktoris peavad olema lubatud heading 1 ja heading 2 (h1, h2) ning paragrahv. Uudise puhul pole headingud lubatud. 

![image](https://user-images.githubusercontent.com/37401947/42023425-6d1cb7dc-7ac8-11e8-9513-53d6b0e945c5.png)

**Probleem 7**: tag-i pikkus võiks olla piiratud. Kas sildid peavad olema kohustuslikud? Piletis 180 pole nii kirjas. Piletis nr 1 on mudelil kirjas, et neid võib olla 0 kuni mitu.

![image](https://user-images.githubusercontent.com/37401947/42023449-835ccb18-7ac8-11e8-9916-aee05e9f79fe.png)

**Probleem 8**: faili kirjeldus peab olema kohustuslik. Pilet 180: Lisatud failid - attachmentFile, võib olla mitu, igal manuse faili pealkiri ja fail, mis mõlemad on kohustuslikud.

![image](https://user-images.githubusercontent.com/37401947/42023472-92111718-7ac8-11e8-863a-256da048fccd.png)

**Probleem 9**: kuhu väljale saan sisestada toimumise koha nimetust - location.name, maksimaalne pikkus 50, ja toimumise koha aadress - location.address, maksimaalne pikkus 50. Miks ma pean kaardi lisama, aga ei saa niisama vabateksti väljale aadressi sisestada? Mille jaoks see laiuskraad ja pikkuskraad üldse vajalik on?

![image](https://user-images.githubusercontent.com/37401947/42023564-d50c9718-7ac8-11e8-98c9-9d3a7a015112.png)

**Probleem 10**: kattuvad väljad.

![image](https://user-images.githubusercontent.com/37401947/42023607-f5513556-7ac8-11e8-988b-83a71fec54d8.png)

Probleem **11:** mille jaoks antud väli vajalik on? Kuidas kasutaja teab, mis id sinna sisestama peab (mis on järgmine id nr)?

![image](https://user-images.githubusercontent.com/37401947/42023641-09586222-7ac9-11e8-898e-2b830e57a2c3.png)

**Probleem 12**: kas registreerimisel ei võiks ka link olla? Nt kui registreerimine toimub mingi välise veebilehe kaudu (nt typeform vms).

![image](https://user-images.githubusercontent.com/37401947/42023668-1aa03e60-7ac9-11e8-9f51-20f3cd5a83fe.png)

**Probleem 13**: millise välja juures tekkis viga?

![image](https://user-images.githubusercontent.com/37401947/42023702-2c878e1c-7ac9-11e8-8ce4-0b54edeea2d1.png)

**Probleem 14**: selle teksti redaktori lubatud pikkus saab olla kuni 500. Kuidas pikkust kontrollitakse või kuidas piirangut rakendatakse? Miks ei võiks kasutada tavalist vabateksti välja?

![image](https://user-images.githubusercontent.com/37401947/42023728-3fdd821e-7ac9-11e8-97e4-7b9f73856089.png)

**Probleem 15**: kellaaega ei saa valida. Eesti kellaaega märgitakse punkti mitte kooloniga. Kui üritus toimub erinevatel kuupäevadel ja mitmes asukohas, kuidas siis kasutaja peaks asukohta märkima – kas peab siis uue identse sündmuse looma ainult erineva asukohaga?

![image](https://user-images.githubusercontent.com/37401947/42023769-570b4200-7ac9-11e8-8641-7eec11b54b32.png)

Probleem 16: sündmust ei peaks ju siduma menüülingiga? Sündmused listitakse kõik sündmuse vaatele.

![image](https://user-images.githubusercontent.com/37401947/42023835-7c6feb04-7ac9-11e8-9b42-5b85262fc42b.png)

**Comment by TanelTromp** [comment]
TEST>TEST

Artikkel

_Probleem 5: see veateade ilmus pärast autorluse juures kuupäeva ja kellaaja muutmist. Mis piiranguga on tegemist? Kas kuskil on kirjeldatud see, et ei saa salvestada, kui teine kasutaja on artiklit muutnud?_

Probleemi ei tuvastanud "wiseadminiga" ega ka "sisuhalduriga" - ilmselt tegemist "headuser" õiguste probleemiga.

_Probleem 7: ma vist tekitasin liiga palju ühesuguseid artikleid. Sisult on need kõik samad. Muutus ainult autorluse kuupäev ja kellaaeg. See ei peaks ju uut artikli kirjet looma? Tekkisid topelt kirjed._

Probleemi ei tuvastanud "wiseadminiga" ega ka "sisuhalduriga" - ilmselt tegemist "headuser" õiguste probleemiga.

_Probleem 9: artikkel peab olema seotud menüülingiga._

Korras!

_Probleem 13: ei ole alamlehe sisu vaid parema veeru lisainfo plokk. Vaadata üle nõuetes kirjas olevad väljade/plokkide nimetused._

Muudetud!

_Probleem 19: miks hüperlinke ja seotud artikleid ei saa ära kustutada, aga lisainfot ja kontakti saab?_

Nüüd korras, akordioni kõrval "Eemalda nupud"


Uudised

_Probleem 9: teisel ja kolmandal pildil ei saa kaalusid valida._

Korras!

_Probleem 10: mida teeb eemalda valitud nupp? Vaadata üle nuppude nimetused, kuna esimese pildi juures on nupu nimetus "Eemalda". Hoida nuppude ja väljade nimetuste juures ühtlust._

Ei suutnud selle nupu kuvamist korrata.


Sündmused

-
