### ISSUE TITLE
Muuta uudise ja sündmuse pealkirja välja pikkust

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#316]
Testimisel selgus, et 50 tähemärki pole piisav, seega muuta:

Sündmuse nimetus - name, kohustuslik, maksimaalne pikkus 100
Uudise pealkiri - title, kohustuslik, maksimaalne pikkus 100

**Comment by TanelTromp** [comment]
TEST

OK!
