### ISSUE TITLE
Registreerimisega sündmuse bugi

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#320]
Viga: kui lisada sündmusele "sissepääsu" väärtuseks "registreerimisega" ja vajutada kohe peale seda "Salvesta", siis kuvab veateate:

The website encountered an unexpected error. Please try again later.
Error: Call to a member function format() on array in test_validate() (line 71 of modules/custom/form_alter_hook/form_alter_hook.module).

test_validate(Array, Object)
call_user_func_array('test_validate', Array) (Line: 83)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 276)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'node_event_form') (Line: 119)
Drupal\Core\Form\FormValidator->validateForm('node_event_form', Array, Object) (Line: 571)
Drupal\Core\Form\FormBuilder->processForm('node_event_form', Array, Object) (Line: 314)
Drupal\Core\Form\FormBuilder->buildForm('node_event_form', Object) (Line: 48)
Drupal\Core\Entity\EntityFormBuilder->getForm(Object) (Line: 113)
Drupal\node\Controller\NodeController->add(Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 41)
Drupal\jsonapi\StackMiddleware\FormatSetter->handle(Object, 1, 1) (Line: 49)
Asm89\Stack\Cors->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 664)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by lsoonvald** [comment]
Fixed @TanelTromp
