### ISSUE TITLE
Avalehe back-end 

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#328]
Üldine: Portaali avaleht on all määratud ulatuses sisuhalduses toimetatav (BE töö: esilehe tekstide sidumine, esilehe sisu loomine).
Eeltingimus: Kasutaja on peakasutaja õigustes.

Vastuvõtukriteeriumid
Blokis "Mis on Eduportaal" saab kasutaja:
- [x] lisada/ muuta bloki pealkirja

- [x] lisada/ muuta teema pealkirja (pilt on paigas, saab lisada/ muuta selle all kuvatavat teksti)
- [x] lisada/ muuta teemale lingi sisulehele (iga teema saab siduda sisulehega, ei ole kohustuslik)

"Super uudis" (St üks uudis on avalehele nö kinnitatud)
- [x] Kasutaja saab määrata/ muuta avalehel "Super uudise" ja selle avaldamise algus- ja lõppkuupäeva koos kellaajaga.

Avalehe kujundus: https://zpl.io/25y6vXn

**Comment by MirellKr2** [comment]
Pilet testitud. Vajalik funktsionaalsus sisuhalduse poolel on realiseeritud. Andmeväljade osas peaks seadma piirangud (mõne tulevase sprindi teema).

**Comment by EgleM-TW** [comment]
Kasutusjuhendi pilet #340

**Comment by EgleM-TW** [comment]
Eemaldatud nõue:
- [x] määrata mitut teemat kuvatakse (max 4 teemat, vähemalt 2 peab olema määratud)
Kasutaja ei saa määrata teemade arvu, sest see rikub kujunduse.
