### ISSUE TITLE
Mobiil-ID autentimine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#330]

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: mobiil-ID päringute testimine Postman API keskkonnas (testimine näidisnumbritega https://github.com/SK-EID/dds-documentation/wiki/Test-number-for-automated-testing-in-DEMO)
Testimise tegevused: funktsionaalsete nõuete testimine

Op. süsteem: Windows 10, PC 64bit
Keskkond: http://test-htm.wiseman.ee:30000/custom/login/mobile_id

Testitud EE numbritega arendaja ja testija poolt. Päringute tulemused olid ootuspärased ja vigu ei tuvastatud.
