### ISSUE TITLE
Avalehe kuvamine 

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#333]
*Note: Kas teeme BE pileti juurde, et avalehel blokis "mis on eduportaal" ja "super uudis" andmeväljadele piirangud seada - lepib planeerimisel kokku!* vt #328 testija kommentaar

**Üldkirjeldus:**
Kuvada portaali avalehte vastavalt kujundusele: https://zpl.io/25y6vXn ja https://zpl.io/VOWgm1Y
Selle töö raames otsing ei pea andma tulemusi, teised funktsionaalsused on realiseeritud:

**Vastuvõtutingimused:**
- [ ] Uudiskirja saab tellida
- [ ] RSS voogu saab tellida
- [ ] Kuvatakse 3 uudist, saab liikuda uudise detailvaatesse, saab avada uudistega lehekülje
- [ ] Kuvatakse 3 sündmust, saab liikude sündmuse detailvaatesse, saab avada sündmuste lehekülje
- [ ] Kui on sisestatud "super uudis" siis kuvatakse seda, kui pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
- [ ] Blokis "Mis on Eduportaal" kuvatakse andmed vastavalt sisestusele, vt BE #328 

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kujundus**:
https://zpl.io/25y6vXn
https://zpl.io/VOWgm1Y

**Viited:**
BE töö #328

**Comment by EgleM-TW** [comment]
Siis kui jõuab - Madis võtab juurde

**Comment by madispold** [comment]
@birgitpulk 
Uus mobiil, tablet ja xxl vaade lisatud, vajab veel paari asja läbi arutamist.

**Comment by madispold** [comment]
@birgitpulk Viimased täiendused tehtud. Läheb testimisse.

**Comment by birgitpulk** [comment]
Üldine:
- [ ] Desktop vaadetes otsing avalehe päisest ära kaotada.
- [ ] Päise sinisel alal võiks olla mingi vari, äkki saame sama tooni jms kasutada mis nuppude puhul? 
- [ ] "Vaata kõiki" hover puudu (lingi alt peaks hoveriga joon kaduma), nii Uudised kui Sündmused kastis
- [ ] Hoverdatav võiks olla terve uudise ala (mitte ainult pealkiri), ehk siis foto jms info ka
- [ ] Uudiskirja checkbox kastidel võiks kasti piirjoon ka siniseks minna kui linnuke on kasti tehtud
- [ ] Uudiskirja e-maili sisestamise kastis peaks olema kiri "Sisesta oma e-posti aadress"
- [ ] Ikoonid igalpool 120X120 laiuse-kõrgusega

**Comment by TanelTromp** [comment]
Viga 1: tõlked puudu

![pilt](https://user-images.githubusercontent.com/37407917/45277080-a936be80-b4ce-11e8-85f2-929239cef492.png)

Viga 2: uudiskirja tellimuse kinnitamine viib error 404 lehele.

Viga 3: "Vaata kõiki" ei ava uudiste juures uudistevaadet (link puudu)

Viga 4: mobiilivaates (iPhone 6) on peale raketti väga suur hulk tühja maad ja siis alles "Sündmused"

**Vastuvõtutingimused:**
- [x] Uudiskirja saab tellida
- [x] RSS voogu saab tellida
- [ ] Kuvatakse 3 uudist, saab liikuda uudise detailvaatesse, saab avada uudistega lehekülje
- [x] Kuvatakse 3 sündmust, saab liikude sündmuse detailvaatesse, saab avada sündmuste lehekülje
- [ ] Kui on sisestatud "super uudis" siis kuvatakse seda, kui pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
- [ ] Blokis "Mis on Eduportaal" kuvatakse andmed vastavalt sisestusele, vt BE #328 (NB! Testimiseks vähemalt kaks teemat peavad olema määratud).

**Comment by madispold** [comment]
@birgitpulk 
Desktop vaadetes otsing avalehe päisest ära kaotada - On @srautam poolt töös pilet #406 raames.
Ülejäänud tehtud koos uue taustade loogikaga.

@TanelTromp 
Viga 1: Tõlked vaja BE poolelt lisada.
Viga 2: Eeldan, et oli seotud mingi päringu läbikukkumisega, ei suuda ise tekitada.
Viga 3: OK
Viga 4: OK
Viga 5: OK
Viga 6: OK

BE poolelt veel superuudise ja Mis on Eduportaal ploki andmete päring tegemisel.

**Comment by madispold** [comment]
@ruut12 Tõlked lisada:
"newsletter.order_to_email": "Telli teemad e-postile",
"button.rss_order": "Telli teemad RSS-iga"

**Comment by TanelTromp** [comment]
@madispold kas need on ka tehtud? Justkui ei muudu midagi, kui BE-s näppisin eelmine nädal:
![pilt](https://user-images.githubusercontent.com/37407917/45345386-dd81ac00-b5ae-11e8-9dd0-244a60b5b433.png)

**Comment by TanelTromp** [comment]
Viga 2: _Eeldan, et oli seotud mingi päringu läbikukkumisega, ei suuda ise tekitada._
Kas proovisid saabunud kinnitamise e-kirjast kinnitada nii:
https://gyazo.com/4b06cae694d73e3df856847c6fbd9aa3

+ uus teema, vahepeal nägin:
<img width="943" alt="1" src="https://user-images.githubusercontent.com/37407917/45346748-c775ea80-b5b2-11e8-8b04-2e5da6cba9d3.PNG">

**Comment by madispold** [comment]
VIGA 2: OK
VIGA 5: Pilved on 2800px laiad, kui vaja katta ka IE 6000px lai vaade, siis on vaja uusi svg pilte :)
Uus teema: Lisatud proovi uuesti nupp kui päring ebaõnnestub.

**Comment by TanelTromp** [comment]
WCAG test @madispold 

Lisa 1: avalehel tabulateerimist alustades peab tekkima "skip to main content" link. Vt nt https://www.starbucks.com/
P.S Birgit teeb veel kujunduse ja mõtleme läbi, et kas teha sarnaselt Starbucksile ehk skip to main content mitu navigeerimis valikut nupus @birgitpulk 

Viga 1: tabulateerides liikudes "vaata kõiki" lingile, peaks ütlema, ka et mille kohta see käib" Nt "uudised vaata kõiki link"

Muidu väga hea töö!

**Comment by birgitpulk** [comment]
Minu leitud vead:
- [ ] Otsingukastis tõlge puudu (hetkel kuvab search.keyword)
- [ ] Otsi nupule vajutades pidi otsingukasti alla kuvama teate (võib olla äkki error teade? ehk siis väi ja teade punased). Äkki teade oleks midagi sellist "Otsingu käivitamiseks sisesta otsitav märksõna" vms, oluline et ei viiks kohe lehelt ära.
- [ ] Uudiste blokis on autor ka link (tekib hoveriga joon alla). Ei peaks olema.

**Comment by birgitpulk** [comment]
@madispold , niiiiii tubli töö nende pilvede ja tähtede jms osas!!!! Aga paar teemat märkasin veel: 

- [ ] Otsingukastis võiks olla sõna "Otsi lehelt", nagu päise otsingukastis on. 
- [ ] Kui punane tekst otsingukasti alla tekib, kas siis saab see otsingukast natukene kõrgemaks minna, praegu see tekst on veidi sinna välja ja kasti vahele pressitud.
- [ ] "Otsi" nupu focus võiks olla tavalise nupu tooni (sinine taust ja valge tekst), praegune lahendus ei tundu ikkagi hea :(. Kas saame äkki kõikidele sinistele nuppudele selle tooni tagasi panna?
- [ ] Mis on Eduportaal? > Kui need ikoonid ja tekstid on lingid, siis võiks neile lisada teksti alla lingi "Vaata lähemalt" (sinine link, font 16px, joon all). Hoveriga läheb lingi alt joon ära, hover võiks toimida terve ikooni ja teksti ala peale hiirega minnes. 
- [ ] Mis on Eduportaal? > Ikoonide all olevad tekstid võiksid alati (igas laiuses) olla kolmerealised (ehk siis pealkiri + 2 rida teksti)

**Comment by madispold** [comment]
@birgitpulk Punktid lahendatud.
@TanelTromp Ei jookse kokku enam avaleht tekstide puudumisel.

**Comment by birgitpulk** [comment]
Minu pole rohkem öelda kui et suurepärane! Tubli, @madispold! 

@TanelTromp vaata palun sina see sisu sisestamine üle. See ka, et need "Mis on Eduportaal" ikoonid+tekstid oleksid kohustuslikuks märgitud sisuhalduses Larsil.

**Comment by TanelTromp** [comment]
Viga 1 uus: pilv pooleks (Mozilla):

![pilt](https://user-images.githubusercontent.com/37407917/45479249-a1854d00-b74e-11e8-841f-609b655a5555.png)

Viga 2 uus: punane, peab olema sinine:

![pilt](https://user-images.githubusercontent.com/37407917/45479290-c24da280-b74e-11e8-8071-fc5e964472f5.png)

**Comment by madispold** [comment]
Viga 1: OK
Viga 2: OK
Viga 3: 4 kohustuslikuks, OK.
Viga 4: 4 kohustuslikuks, OK.
Viga 5: OK.
Viga 6: Vaja valida seotud sisemine link, siis samas aknas, muidu uues välise lingi korral, vt. pilt:
![Screen Shot 2018-09-13 at 14.03.24.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/bf523564-e042-45a8-9c74-1e9144235a89)
Viga 7: OK.
Viga 8: OK.
Viga 9: OK.

**Comment by TanelTromp** [comment]
See ei ole viga, see on palve 1 (vigu ei ole): kui "Superuudist" ei ole valitud, siis siia veitsa rohkem õhku:

![pilt](https://user-images.githubusercontent.com/37407917/45489015-ce942880-b76b-11e8-862c-6fc08d5facbd.png)
