### ISSUE TITLE
 Õppekavade nimistu filtreerimise mobiilivaade

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#354]
Pileti https://github.com/hariduspilv/haridusportaal/issues/148 mobiilivaadete tegemine

**Comment by MirellKr2** [comment]
Pilet #130 vajab mobiili vaatel kohendusi (filtri osas ei toimi korrektselt).

Õppeasutuse nimistus ja infoaknas peab muutma tüübi ja alamtüübi kuvamist. Alamtüüp peab olema kuvatud sulgudes.

**Comment by madispold** [comment]
Testimisse @MirellKr2 

Õppeasutuse detailvaates alamtüübid lisatud sulgudesse. Listivaates kuvatud välja vaid tüübid (alamtüübid peidus).

Tehtud nii, kuna tüüpide seosed tulevad BE'st kõrvalise päringuga hetkel, et seda listivaatele rakendada peaks kõvasti loogikat igal listi elemendil rakendama, pole mõistlik.

**Comment by madispold** [comment]
Ootab veel filtris fondi suuruste ühtlustamist.

**Comment by madispold** [comment]
Nüüd fondi suurused üle sisestusväljade samad desktop ja mobiil @MirellKr2

**Comment by MirellKr2** [comment]
Korras
