### ISSUE TITLE
Õppekavade nimistu mobiilivaade

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#357]
Pileti https://github.com/hariduspilv/haridusportaal/issues/147 mobiilivaade

**Comment by madispold** [comment]
Testimisse @MirellKr2

**Comment by MirellKr2** [comment]
Tegevuse üldine kirjeldus: õppekavade nimistu mobiilivaate testimine
Testimise tegevused: funktsionaalsete nõuete testimine

Samsung Galaxy A8 + Chrome
Keskkond: http://htm.twn.ee/

**Viga 1**: filtri osa peab olema vaikimisi suletud. Vt kujundust alljärgnevalt:

![image](https://user-images.githubusercontent.com/37401947/44019869-bb7d2f80-9ee8-11e8-9817-2c835a9cddd7.png)

**Comment by madispold** [comment]
Parandatud @MirellKr2

**Comment by MirellKr2** [comment]
Korras.
