### ISSUE TITLE
GraphQL Elasticsearchi päring koolikaardi vaatesse

### ISSUE THREAD

**Issue by lsoonvald** [hariduspilv/haridusportaal#358]
Lisada päringule võimalused piirata tulemuste arvu ning erinevad filtrid. Vajadusel kujundada ümber päringu struktuuri, et front-end seda kasutada saaks vaates.

**Comment by skeefee** [comment]
Kõik tundub okei olevat. Kui mingid key-d puudu on siis saame tulevikus lisada

**Comment by lsoonvald** [comment]
Saab proovida urlilt: http://test-htm.wiseman.ee:30000/graphql?queryId=schoolMapQuery:1&variables={%20%22lang%22:%20%22ET%22,%20%22title%22:%20%22%%%22,%20%22location%22:%22%%%22,%20%22locationEnabled%22:%20false,%20%22type%22:%20[%222420%22],%20%22typeEnabled%22:%20false,%20%22language%22:%20[%221294%22,%221295%22,%221296%22],%20%22languageEnabled%22:%20false,%20%22ownership%22:[%22624%22],%20%22ownershipEnabled%22:%20false,%20%22specialClass%22:%20%220%22,%20%22specialClassEnabled%22:%20false,%20%22studentHome%22:%20%220%22,%20%22studentHomeEnabled%22:%20false%20}
