### ISSUE TITLE
FB ja Twitteri integratsioon

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#36]
**Sprint 8 metatagide asi, ei näe täge** 

Üldkirjeldus:
Portaali kasutaja saab uudise detailvaadet, sündmuse detailvaadet ja sisulehte (TypeOneArticlePage) jagada sotsiaalmeedias. Nupp, mille alt avanevad valikud FB ja Twitter.

Eeldused ja käivitamine:
Kasutaja on avanud:
 * sündmuse detailvaate,
 * uudise detailvaate,
 * sisulehe (TypeOneArticlePage).

Vastuvõtutingimused:
Kasutaja saab jagada FB-s ja Twitteris:
- [x] sündmust
- [x] uudist
- [x] sisulehte 

Default seaded. Arendaja lisab, mis väljad kaasa peab võtma.

**Comment by EgleM-TW** [comment]
Portaali külastaja saab portaali sisulehelt jagada lehekülje linki Facebook-is ja Twitter-is.

**Comment by madispold** [comment]
Jagatavad artiklid/uudised/sündmused. Nõutud ka meta tagid sisuhalduses artikli all paremal tulbas. FB jaoks open graph ja Twitteri jaoks twitter cards tüüpi.

http://htm.twn.ee/et/sundmused/meeskonnatoo-tooalased-suhted-tookultuur on tagid lisatud.

**Comment by TanelTromp** [comment]
Vastuvõtutingimused:
Kasutaja saab jagada FB-s ja Twitteris:
- [ ] sündmust
- [ ] uudist
- [ ] sisulehte 
- [ ] Kasutajal peab olema sotsiaalmeedia seadetes lehekülje jagamine lubatud (platform settings enabled)

**Comment by madispold** [comment]
Tehtud, vajab testimist, hetkel iga artikli jms all manuaalne meta tagide lisamine.

Töötav näidis: http://htm.twn.ee/et/sundmused/meeskonnatoo-tooalased-suhted-tookultuur

**Comment by MirellKr2** [comment]
Viga mobiilis kuvamisega. Jagamise ikoon ja jagamise valikud on osaliselt nähtavad. Jagamine FB-s ja Twitteris toimib ootuspäraselt. Info, mida postituses kuvatakse, võiks hõlmata uudise/sündmuse/artikli pealkirja ja lühikirjeldust.

![screenshot_20180803-100015](https://user-images.githubusercontent.com/37401947/43628961-766cfe8e-9704-11e8-8256-9f9ad22b1316.jpg)

![screenshot_20180803-100042](https://user-images.githubusercontent.com/37401947/43628962-76891678-9704-11e8-8347-15350e7e8bb1.jpg)
