### ISSUE TITLE
Toetusprojekti sisutüüp

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#362]
Lisada taksonoomia **Rahastusmeede** (**_InvenstmentMeasure_**), kus on kirjed: 
- "Põhikoolivõrgu korrastamine perioodil 2014–2020", 
- "Gümnaasiumivõrgustiku korrastamine".

Lisada sisutüüp **Toetusprojekt** (**_SubsidyProject_**):
- EHIS_id - õppeasutuse identifikaator EHIS-s
- rahastusmeede (investmentMeasure) - valik Rahastusmeede taksonoomiast
- projekt (investmentProject) - string
- maksimaalne summa (investmentAmount) - number (kuni 8 kohaline täisarv)
- rakendamise tähtaeg (investmentDeadline) - kuupäev
- ehitise ehitisregistri kood (BuildingId) -string

BE viited: #363 ja #364

**Comment by TanelTromp** [comment]
Jääb ootama selle välja vajalikkuse kinnitust:
"ehitise ehitisregistri kood (BuildingId) -string"
