### ISSUE TITLE
Päringud rahastuse andmete esitamiseks

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#364]
Teha päringud toetusprojektide (SubsidyProject) andmete FE-s kuvamise jaoks. 

Toetusprojektid seotakse õppeasutustega (EducationalInstitution) EHIS-id kaudu.

**Kaardi kuvamiseks päringud:**
Päringu sisend:
- õppeasutuse omandivorm (ownerShipType) - valitud taksonoomiast; väljastatakse nende toetusprojektide andmed,  õppeasutuse OwnerShipType võrdub sisendis esitatud tingimusega
- rahastusmeede (investmentMeasure) - valik taksonoomiast; väljastatakse nende toetusprojektide andmed, mille korral investmentMeasure võrdub sisendis esitatud rahastusmeetmega
- rakendamise tähtaja aasta (investmentDeadlineYear) - väljastatakse nende toetusprojektide andmed, mille korral investmentDeadline aasta võrdub sisendis esitatud aastaga
- väljundi detailsus (1 - maakond, 2 - valdlinn, 3 - õppeasutus)

 Väljund maakonna detailsusega (n kirjet):
- õppeasutuste asukoha maakond (county)
- investeeringute maksimaalne summa (investmentAmount) summeeritud maakonna peale kokku

Väljund valdlinn detailsusega (n kirjet):
- õppeasutuste asukoha vald või linn (localGoverment)
- investeeringute maksimaalne summa (investmentAmount) summeeritud valdlinna peale kokku

 Väljund õppeasutuste detailsusega (n kirjet):
- õppeasutuse id
- õppeasutuse asukoha koordinaadid (geoCoordinatesLat, geoCoordinatesLong)
- investeeringute maksimaalne summa (investmentAmount) summeeritud õppeasutuse peale kokku

**Kaardi õppeasutuse sildi kuvamiseks päringud:**
Päringu sisend:
- õppeasutuse id

Väljund:
- õppeasutuse nimetus (name)
- õppeasutuse registrikood (registrationCode)
- õppeasutuse  omandivorm (ownershipType)
- toetusprojektide andmed (1.. n kirjet)
-- rahastusmeede (investmentMeasure) 
-- projekt (investmentProject) 
-- maksimaalne summa (investmentAmount) 
-- rakendamise tähtaeg (investmentDeadline) 

BE viited: #362 ja #363  FE viited: #369 ja #370 
Kõik viited on kirjas siin: #359

**Comment by ruut12** [comment]
Kaardi õppeasutuse sildi kuvamiseks päringud on valmis ja testis

**Comment by lsoonvald** [comment]
Detailsuse level 1:
http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQueryLocation:1&variables={%20"ownershipType":%20[],%20"investmentMeasure":%20[],%20"investmentDeadline":%20[],%20"levelOfDetail":%201%20}
Detailsuse level 2:
http://test-ht:30000/graphql?queryId=subsidyProjectQueryLocation:1&variables={%20"ownershipType":%20[],%20"investmentMeasure":%20[],%20"investmentDeadline":%20[],%20"levelOfDetail":%202%20}

(Filtritesse lähevad väärtused intidena ja array sisse.

**Comment by lsoonvald** [comment]
Detailsuse level 3:
http://localhost:30000/graphql?queryId=subsidyProjectQuerySchool:1&variables={%20%22ownershipType%22:%20[],%20%22investmentMeasure%22:%20[],%20%22investmentDeadline%22:%20[],%20%22levelOfDetail%22:%203%20}

Teine query map, pane tähele, muu on sama.

**Comment by lsoonvald** [comment]
Filtrid:
http://localhost:30000/graphql?queryId=subsidyProjectFilters:1&variables={%22lang%22:%22ET%22}
