### ISSUE TITLE
Kaardi tehnilise lahenduse valik

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#365]
Uurida potentsiaalseid lahendusi, näiteks Google maps, Google graph, Raphaël ja teha valik.
Lahendus peab võimaldama kaardil haldusüksustega (maakond, vald/linn) piiritletud alade toonimist sõltuvalt numbrilisest väärtusest (antud juhul investeeringute summad investmentAmount). Numbriliste väärtuse alusel tuleb arvutada väärtuste vahemikud, kuhu jäävad haldusüksused on kaardil sama tooni. Vahemike arvu võiks saada seadistusparameetriga määrata.

Viited: #359

**Comment by EgleM-TW** [comment]
Meelespea: Valiku tegemisel arvetsame ka OSKA andmete kuvamise sooviga Eesti kaardil.

**Comment by skeefee** [comment]
Meil on valida kahe valiku vahel (mõlemad on testitud).

1. kasutada kaardil ringi kujulisi ja eri värvi/suurusega markereid
2. Asetada kaardile maakondade/valdade alade polügoonid.
Polügoonide lisamine tähendab seda, et kasutaja arvutil on suurem koormus ning server
edastab kasutajale rohkem andmeid. Maakondade puhul ligikaudu 2mb (gzipped) ja valdade puhul ligikaudu 4-5mb (gzipped). Polügoone saame kasutada alles siis kui me suudame maa-ametist koordinaadid õigel kujul välja võluda.
