### ISSUE TITLE
Kaardivaatel haldusüksuste lõikes toetusprojektide summad

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#367]
Kaardil visualiseeritakse toetusprojektid summad:
- maakondade lõikes
- valdade/linnade lõikes

Minimaalse ja maksimaalse toetussumma vahemik jaotatakse 7 võrdseks osaks. Iga osa on erineva värvitooniga (heledamast tumedamaks). Iga haldusüksus kuvatakse selle värvitooniga, kuhu osasse jääb selle haldusüksuse toetusprojektide summa.

Haldusüksuse kohta peab saama näha ka toetusprojektide summa suurust (disaini #361 ja tehnilise lahenduse valiku #365 raames täpsustada, kuidas summasid kuvada).

BE-st andmete päring - #364.
Lisandub filter - #369 

[maakondade lõikes kaardi disaini link](https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b7e7e360551611d08489fee)

**Comment by TanelTromp** [comment]
Viga 1 üldine: kaardil on vaikimisi liiga kange suum (proovitud erinevate brauseritega):

![pilt](https://user-images.githubusercontent.com/37407917/45472812-f8365b00-b73d-11e8-9397-b1f0778791ef.png)

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Korras
Viga 3: Tundub korras. Ma seda viga enam ei näe (ff, chrome, safari)
Viga 4: Korras
Viga 5: Korras

Muudatus 1: Seda veel arutame

**Comment by TanelTromp** [comment]
Viga 6: kui filtreid rakendada, siis menüüs kaob lokatsiooni ära (paneb kinni ja ei ole BOLD):
https://gyazo.com/28bebb7ad57a0bb5a37092f0b12bf860

**Comment by skeefee** [comment]
Viga 6: See läheb Madisele Sidemenu ticketi alla. Las vaatab üle mis jama on. Pole minu poolne vigastus

**Comment by birgitpulk** [comment]
- [ ] Kooli peale klikkides on see kooli infoaken ikka serva taga. 
- [ ] Aasta numbrid lähevad ikkagi maha, ehk siis et kohe kuvatakse kõik toetusprojektid.

**Comment by birgitpulk** [comment]
Otsus 28.09 sprindi lõpetamiselt: jätame esialgu aastaarvud infoaaknasse

**Comment by birgitpulk** [comment]
Küsimus @skeefee ja @TanelTromp : kui oled kaardil sisse zoominud ja vaadanud koole ning siis teostad lehekülje ülaosas  filtreeringu, siis jääb kaardi zoom ja asukoht samaks nagu enne oli. Kas ei võiks refreshida kaardi zoomi ikka defaultiks, et kasutaja saaks aru, et otsing on teostatud ja midagi visuaalselt muutub ta jaoks?
