### ISSUE TITLE
Kaardivaatel õppeasutuste lõikes toetusprojektide summad

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#368]
Kaardil visualiseeritakse toetusprojektidest rahastust saanud õppeasutused (iga toetusprojektist rahastust saanud õppeasutuse kohta kaardil marker).

BE-st andmete päring - #364
Kaardil filter - #369
Infoaken - #370

**Comment by skeefee** [comment]
Viga 1 korras

**Comment by birgitpulk** [comment]
Ainus teema mobiili osas, et kas see tehakse ka selle pileti raames või mitte? @TanelTromp @skeefee 

Muus osas minu poolt üle vaadatud ja korras.
