### ISSUE TITLE
Toetusprojektide kaardivaatel filter

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#369]
Toetusprojektide kaardivaadetel (#367, #368) saab rakendada järgmiseid filtreerimise tingimusi:
* õppeasutuse omandivorm - valik taksonoomiast ownerShipType
* rahastusmeede - valik taksonoomiast investmentMeasure
* rakendamise tähtaja aasta - valik toetusprojektide rakendamise tähtaja aastad

**Comment by TanelTromp** [comment]
Täpsustus 1: "Filtreeri" asemel "Otsi" CTA nimeks (Birgit)

**Comment by skeefee** [comment]
Täpsustus 1: "Korras

Nicetohave 1: Can't have. Nii nagu praegu on tundub loogilisem. 

Viga 1: Korras

**Comment by TanelTromp** [comment]
Viga 2: ENG keelevalikus puuduvad filtritel valikud:

https://gyazo.com/c2e067e779a940d2d008db30790fd395

**Comment by birgitpulk** [comment]
- [ ] Breadcrumbsi ja filtri vahel liiga suur ruum

**Comment by lsoonvald** [comment]
Viga 2: Done.

**Comment by TanelTromp** [comment]
Viga 3: ENG vaade katki:
https://gyazo.com/57cc958485381dc9606a46b4968c827e

**Comment by birgitpulk** [comment]
Mina ei näe filtreeringus ikka tekste? Tõlke küsimus? @lsoonvald

**Comment by skeefee** [comment]
korras @birgitpulk

**Comment by birgitpulk** [comment]
Vaatasin üle, tõlked olemas. Minu poolt ka korras.
