### ISSUE TITLE
 CSV importimise täiendus

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#37]
**Põhikutseala = ametiala, muudatus tehtud.** 

Täiendus tööle #454  

- [ ] Selle töö raames muuta "naitaja" taksonoomiaks. 
Testida, kas saab sisestada taksonoomiat "Näitaja" (indicator)

1. Sisuhaldaja avab faili.
Fail on CSV fail, kus:
- veergude eraldaja on semikoolon ( ; ), 
- failis on päiserida (naitaja;valdkond,alavaldkond;pohikutseala;periood;silt;vaartus) 

2. Faili kontroll:
päirerea kontroll, nii nagu #454 

3. Salvestada failist loetavad OSKA andmed. Faili iga rida salvestada:
- naitaja 
- valdkond
- alavaldkond
- ametiala
- periood
- silt  
- väärtus 

 Testimiseks andmed: https://github.com/hariduspilv/haridusportaal/blob/master/docs/testimiseks.txt

**Comment by EgleM-TW** [comment]
Lahtine, kas lisada occupation kirjeldusele ISCO-kood.

**Comment by TanelTromp** [comment]
Viga 1: kui "näitaja" väli tühjaks jätta või vale väärtus (nt "%") kirjutada, siis ei kuva õiget veateadet, vaid mingi chaose. Peaks kuvama "Puudub naitaja"

**Comment by lsoonvald** [comment]
Viga 1: Parandasin tühja välja lisamise. Sümbolit % saab lisada, see on täiesti legaalne karakter.

**Comment by TanelTromp** [comment]
Viga 2: "Põhikutseala" väli on tühi. Testin selle CSV-ga:

![pilt](https://user-images.githubusercontent.com/37407917/46813966-65aacb00-cd80-11e8-8e36-7073620dfa9e.png)
