### ISSUE TITLE
Toetusprojektide kaardivaatel infoaken

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#370]
Toetusprojektide õppeasutuste lõikes kaardivaatel (#368)  õppeasutuse markerile klikkides avaneb kaardivaatel infoaken (modaal), kus on järgmised andmed:
õppeasutuse nimetus 
õppeasutuse registrikood 
õppeasutuse omandivorm 
toetusprojektide andmed (1 või mitu kirjet)
-- rahastusmeede 
-- projekt
-- maksimaalne summa 
-- rakendamise tähtaeg 

BE-st päring #364 

[infoakna disani link}
(https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b9118175c2a359d0904aecf)

**Comment by TanelTromp** [comment]
Viga/täpsustus 1: kui välja väärtus on väga pikk (st nii on hetkel mitu väärtust), siis sisu modaalis väga kokkupressitud ja halb lugeda. Suurem modaal? @birgitpulk 

![pilt](https://user-images.githubusercontent.com/37407917/45474204-c921e880-b741-11e8-94d3-373cd8a27260.png)

**Comment by skeefee** [comment]
Viga 1: Seda võiub ka laiema modaaliga juhtuda. Tehniliselt korras. Kui Birgit tahab kunagi välimust muuta siis läheb see kujunduse muudatuse ticketi alla
Viga 2: Korras

**Comment by birgitpulk** [comment]
Sain aru, et neid aastaarve ei tule sinna ikkagi, Andrus ütles et see on mõttetu, kuna neid toetuseid ei ole üldse nii palju et peaks need aastate alla panema. @andrussarv Mis teeme?

**Comment by skeefee** [comment]
Aga scrollivat akent me ka ei taha ega ju? @birgitpulk

**Comment by birgitpulk** [comment]
@andrussarv  võiks siin seda vajadust veidi kommenteerida (ka tuleviku kontekstis). Sain aru, et ühel koolil võibki neid toetusprojekte 1-2tk olla, seega ei läheks vist kohe scrollitavaks ju?
