### ISSUE TITLE
Error 404 lehe kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#371]
**Üldkirjeldus:**
Kui kasutaja satub Eduportaali URL'le, mida server ei leia, tagastab süsteem kasutajale disainitud error 404 lehekülje.

**Eeltingimused ja käivitamine:**
Kasutaja sisestab Eduportaali serveri pihta URL-i, mida server ei leia.

**Vastuvõtutingimused:** 
Süsteem vastab disainitud 404 lehekülje kuvamisega.

**Kasutajaliidese eskiis:**
desktop: https://zpl.io/agn176Q
mobiil: https://zpl.io/a7ypDQq

**Comment by madispold** [comment]
Testimisse @TanelTromp.

Vigase urli sisestamisel viskab 404 lehele, kus info ja lingid pealehele, õppeasutused, sündmused, uudised vaatele.

**Comment by TanelTromp** [comment]
TEST

- [x]    Vigase urli sisestamisel viskab 404 lehele, kus info ja lingid pealehele, õppeasutused, sündmused, uudised vaatele.

Zeplini MD (mis need px x px nüüd olid?) vaadet ei näinud ma kuskil oma seadmetes, ka mitte scalemisel. Nii laptopis, kui UHD-ga on planeet alati rohkem pooleks. Kui see on @birgitpulk arvates okei, siis pilet DONE.

Siin foldid:
3840 x 2160 px (UHD):
![pilt](https://user-images.githubusercontent.com/37407917/43885993-1afe46f2-9bc3-11e8-8a20-e5258ceb6174.png)

1920 x 1080 px (Laptop)
![pilt](https://user-images.githubusercontent.com/37407917/43886020-2a91069a-9bc3-11e8-91fc-4653b74f205d.png)

**Comment by birgitpulk** [comment]
Minul näitab sellist pilti @TanelTromp (1440px laiuse peal): 
<img width="1440" alt="screen shot 2018-08-09 at 13 02 00" src="https://user-images.githubusercontent.com/24669779/43892482-ba133ec6-9bd4-11e8-87c5-6eec96db0d9d.png">

**Comment by birgitpulk** [comment]
Õppeasutused link viib inglisekeelsele lehele @TanelTromp

**Comment by madispold** [comment]
Siis viib kui inglise keel on aktiivne või kui tuvastatud asukohaga katkine sisestatud link (e.g /en/events/katki) oli inglise keelse prefixiga. 

Kuna tõlked on hetkel töös, siis 404 leht ise pole ingliskeelsete kirjadega, muidu oleks. Kui saavad uued tõlked lisatud, siis töötab vastavalt. Menüü küll tuleb juba korrektses keeles vastavate menüüpunktidega. @TanelTromp @birgitpulk

**Comment by birgitpulk** [comment]
Minu poolt ok!

**Comment by TanelTromp** [comment]
Viga uus: parema menüü kaudu ei saa veateatest EN keelevalikus välja. Kas see on tõlgetega seotud?
https://gyazo.com/e5ac620ede30e5718d9abe0abd61d1ac
