### ISSUE TITLE
FE ja Twitter jagamine – metatagide sidumine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#372]
FE ja Twittwr jagamine – metatagide sidumine.

Viited: #249, selle täiendus tarvis teha.

**Comment by madispold** [comment]
Done! 

Twitteris pilt ei tööta juhul kui võtad meie saidilt URLi koos pordiga (nt. :30000). Väliste kenade urlidega töötab.

**Comment by TanelTromp** [comment]
*Facebook*

Töötab järgmise loogika järgi (testitud vastavalt nõuetes olevatele seadmetele ja brauseritele) ehk jagatavale lingile lisatud:

pilt
URL
pealkiri
portaalinimi
sissejuhatusest algus (pikkus vastavalt seadmele). Kas siin saab seda pikkust ka määrata erinevate seadmete puhul? Kas on nõuded olemas?

*Twitter*

Ei tea, kuidas peaks töötama. Hetkel ei tiri peale lingi midagi kaasa nagu(sama kala erinevate brauseritega) - pealkiri ka puudu nt:
![pilt](https://user-images.githubusercontent.com/37407917/44036995-e9843288-9f1b-11e8-83c3-afbe56c01a37.png)

Lisaks toon näite akna suurusest ja kuvast, mis võiks ka siin nii optimeeritud olla (kasvõi järgmises sammus):
![pilt](https://user-images.githubusercontent.com/37407917/44037242-862f17a6-9f1c-11e8-855f-8c7cf3e26e0e.png)

@madispold

**Comment by madispold** [comment]
Viga 1 ja Viga 2 parandatud @TanelTromp
