### ISSUE TITLE
Korduva sündmuse kuvamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#374]
Juhul kui tegemist on korduva sündmusega, peab kalendris ja nimekirjas näha olema ainult esimene toimumiskord

**Comment by birgitpulk** [comment]
@TanelTromp Palun aruta Andrusega läbi, aga minu meelest leppisime kokku, et korduva sündmuse juurde ei tule ikooni siiski. Et pole oluline, kas ta on korduv või mitte.

**Comment by skeefee** [comment]
@TanelTromp  korduva sündmuse muudatus tehtud ja kuvab nii nagu peab

**Comment by TanelTromp** [comment]
OK (v.a korduvust tähistava märgi olemasolu desktop vaates).

**Comment by skeefee** [comment]
Selged pildid, võtan selle ikooni listist maha ja uuendan
