### ISSUE TITLE
WCAG - VO testimine: menüüd ja päis

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#376]
TEST NVDA (WCAG nõuded ekraanilugejaga)

Viga 1: Vasakul nurgas olev "Eduportaali" logolt puudu "link" label ning ka kirjeldus, et seda vajutades saab avalehele. (nt> link eduportaal.ee mine avalahele)

Viga 2: Otsingukast peaks olema kirjledavama labeliga: nt "Otsi lehelt"

Viga 3: Erkaanilugejaga ei saa aru kuidas otsingut saab käivitada ning "luup" ei ole button ja selle peale ei saa liikuda, kuigi peaks (see tegelikult issue IMHO ka tavakasutajale - ainult "ENTERiga" otsingu käivitamine ei ole hea - Birgit says: yes).

Viga 4:  Keelvalikus (kolm punktiiri)l puudub label, millega on tegu (ütleb ainult, et: menu button submenu)

Viga 5: "Logi sisse" ütleb" link" aga tegelikult peaks ütlema "button" (minu teada loogika, et link=konkreetselt lehelt välja. Button=mingi tegevus samas levelis)

Viga 6: ekraanilugejaga liikudes (TABulateerides korras) läheb pärast "Logi sisse" valikut Sidebarile ja menüüs alla viimase topicu juurde (konkr. "Ei ole link yo". Peaks alustama aga selle ülevalt ja ütlema ka, et kasutaja liikus "sidebarile" (hetkel ütleb ainult "list").

Probleem 7: Dropdown peab sulguma peale selle sisust välja liikudes. Lisaks peab "esc" selle sulgema.

Viga 8: "Logi sisse" errori peaks lugema ette ka ekraanilugejaga, kui see ilmub (Sisselogimine ebaõnnestus...."

Viga 9: (see võib olla tingitud hetke poolikust lahendusest): ekraanilugejale peaks ütlema, mis EN ja ET on ehk labelid külge.

Viga 10: pärast tellimuse kinnitamise buttoni vajutamist, peaks ettelugema kuvatud teksti:
![pilt](https://user-images.githubusercontent.com/37407917/43829817-8ecf4cea-9b08-11e8-9126-5d55d926b5f5.png)

Viga 11: (see võib olla tingitud hetke poolikust lahendusest) see peaks olema ka suletav ilmselt, et saada taas filtri vaadet?:
![pilt](https://user-images.githubusercontent.com/37407917/43829817-8ecf4cea-9b08-11e8-9126-5d55d926b5f5.png)

Viga 12: html tag language atribuut ei vaheta oma väärtust vastavalt valikule

Viga 13: log-in valik peaks tabulateerides olema enne keelevalikut, nagu visuaalis. Hetkel vastupidi.

Viga 14: headerist ka "skip to main content" puudu

**Comment by srautam** [comment]
VIGA 3 - html/css oleks vaja ringi teha.

**Comment by srautam** [comment]
1. Fixed
2. Fixed
3. Fixed ja Inputi loop redone
4. Fixed
5. Fixed
6. Järgmisse Sprinti. Bug on enamvähem sarnane #380 | viga 13.
7......
8. ok
9. et EN, ET pikeamks muuta, tuleks sellel läheneda Angulari/Backi poolt. HMTL elementide modimisest jääb väheseks.
10. SERVER MAAS
11. Tagasi minek on praegu läbi refreshi, tagasi mineku üles ehitamiseks pöörduda angulari masterite poole <-- Jägmisesse ticketisse
12.......

**Comment by TanelTromp** [comment]
Viga 5: ütleb endiselt "link"
Viga 8: saab küll liikuda veateatele aga selle peaks erkaanilugeja selle ilmumisel kohe ette lugema.
Viga 10: ei loe ette
Viga 15: kui sisestada vale e-kirja aadress, peaks erinevad veateatde ette lugema, nende ilmumisel. Hetkel ei loe:
![pilt](https://user-images.githubusercontent.com/37407917/44308390-95130c00-a3bd-11e8-999a-875d802d575d.png)
![pilt](https://user-images.githubusercontent.com/37407917/44308399-b5db6180-a3bd-11e8-8984-39b8d1d54df0.png)

**Comment by srautam** [comment]
- [ ] Viga 5: ütleb endiselt
- [ ] Viga 8: saab küll liikuda veateatele aga selle peaks erkaanilugeja selle ilmumisel kohe ette lugema.
- [ ] Viga 10: ei loe ette

- [ ] Viga 15: kui sisestada vale e-kirja aadress, peaks erinevad veateatde ette lugema, nende ilmumisel.

**Comment by TanelTromp** [comment]
Viga 5: "link" endiselt
