### ISSUE TITLE
Sündmuste ja uudiste filtrite testimine, lisa

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#377]
**Sündmuste filter:**

Viga 1: shrinkiv label peab olema sama, mis big label (mõlemas keelevalikus). Hetkel ei ole:
https://gyazo.com/a975110c1f651fc2e93a3c07399be6f1

Viga 3: manuaalselt sisestatud väljadel poolikute väärtuste sisestamisel ei tohiks kuvada filtri tulemusi:
https://gyazo.com/89072c00753ac8e3cd76ee5ed69aaf44

Vaid:
a. peaks kuvama kastid punaselt + veateade
b. vastavalt material disainile
c. automaatselt sisestama vaikeväärtuse - nt tänase kuupäeva (kui ajaliselt kõige kiirem, siis võiks selle lahenduse valida . (Hetkel URL nii käitubki enamvähem ehk kui sisestan 1 ja 2, siis võtab väärtusi neid kui käesoleva kuu kuupäevi ja liikudes kalendri vaatesse ja nimekiri vaatesse tagasi, siis :
http://htm.twn.ee/et/sundmused?dateFrom=01-08-2018&dateTo=02-08-2018 )
Birgit says @birgitpulk 

Viga 4: "List" = e.k "Nimekiri" palun muuta "ET"-keelevaliku vaadetes (Andruse&Eglega räägitud)
![pilt](https://user-images.githubusercontent.com/37407917/43719345-20ac3c0a-9996-11e8-9d69-92eb8d2a8ef8.png)

Viga 5: keelevahetuse puhul ET>EN, ei muutu filtri nupud inglise keelseks ("Täpsem otsing", "Kitsam otsing" ja "Otsi")
ja  "Täpsem otsing" avatuna hindid on e.k:
![pilt](https://user-images.githubusercontent.com/37407917/43719561-b6777bc8-9996-11e8-9893-766118be7c81.png)

**Uudiste filter:**

Viga 1: shrinkiv label on mõlemas keeles "Lõppkuupäeva" puhul sassis, näitab "Alguskuupäeva":
https://gyazo.com/15389c2d3c96f2c55c0007c2bbe0a04b

Viga 2: vastavalt kokkulepitule peaks trükitavale väljale kursorit viies kuvama halli tekstina hindi, kuidas st mis järjekorras ja hulgas tuleb sisestada kuupäeva väärus ehk: pp/kk/aaaa ja inglise keeles vastavalt siis: dd/mm/yyyy (hetkel eraldatud väärtused "-"-ga mis vast ei ole ka parim lahendus

Viga 3: keelevahetuse puhul ET>EN, ei muutu filtri nupud inglise keelseks ("Täpsem otsing", "Kitsam otsing" ja "Otsi")
ja  "Täpsem otsing" avatuna hint on ka e.k:
![pilt](https://user-images.githubusercontent.com/37407917/43719653-efee4f30-9996-11e8-9dbe-b7506d525b64.png)

Viga 4: "List" = e.k "Nimekiri" palun muuta "ET"-keelevaliku vaadetes (Andruse&Eglega räägitud)
![pilt](https://user-images.githubusercontent.com/37407917/43719345-20ac3c0a-9996-11e8-9d69-92eb8d2a8ef8.png)

**Comment by TanelTromp** [comment]
Sündmuste filter:

Viga 1: shrinkiv label peab olema sama, mis big label (mõlemas keelevalikus). Hetkel ei ole:
https://gyazo.com/a975110c1f651fc2e93a3c07399be6f1

Viga 2: vastavalt kokkulepitule peaks trükitavale väljale kursorit viies kuvama halli tekstina hindi, kuidas st mis järjekorras ja hulgas tuleb sisestada kuupäeva väärus ehk: pp/kk/aaaa ja inglise keeles vastavalt siis: dd/mm/yyyy (hetkel eraldatud väärtused "-"-ga mis vast ei ole ka parim lahendus. Birgit says @birgitpulk ?

Viga 3: manuaalselt sisestatud väljadel poolikute väärtuste sisestamisel ei tohiks kuvada filtri tulemusi:
https://gyazo.com/89072c00753ac8e3cd76ee5ed69aaf44

Vaid:
a. peaks kuvama kastid punaselt + veateade
b. vastavalt material disainile
c. automaatselt sisestama vaikeväärtuse - nt tänase kuupäeva (kui ajaliselt kõige kiirem, siis võiks selle lahenduse valida . (Hetkel URL nii käitubki enamvähem ehk kui sisestan 1 ja 2, siis võtab väärtusi neid kui käesoleva kuu kuupäevi:
http://htm.twn.ee/et/sundmused?dateFrom=01-08-2018&dateTo=02-08-2018 )
Birgit says @birgitpulk 





b.

**Comment by birgitpulk** [comment]
Sündmuste filter:
Viga 2: ei ole võimalik praeguse lahendusega teha (topelt hintid peaksid tekkima nii), jääb nii nagu on
Viga 3: a või c lahendus sobib mulle. Eelistan pigem a varianti, sest c puhul ei pruugi kasutaja märgata, et pandi tänane kuupäev. Pigem oleks hea talle kuvada teade, et info on puudulik vms.

**Comment by madispold** [comment]
Sündmuste filter:
Viga 1: OK.
Viga 3: OK, panin hetkel punase äärise vigase sisestuse korral, mis töötab ka siis kui esimene kp pole varasem teisest. Täiesti ideaalset lahendust ei saa, kuna material loeb pooltäidetud välja ka õigeks ja kasutab käesolevat kuud.
Viga 4: OK
Viga 5: OK
Uudiste filter:
Viga 1: OK
Viga 2: Ei teinud (birgiti kommentaar pileti all)
Viga 3: OK
Viga 4: OK.

**Comment by madispold** [comment]
@ruut12 tõlked muuta:

school.list: "nimekiri",
event.list: "nimekiri"

**Comment by TanelTromp** [comment]
Viga uus 1: nüüd ainult eesti keeles filtrite väljad sündmustel ja uudistel (keelevahetus ei tööta)

**Comment by madispold** [comment]
Viga uus 1: Inglise keelsed tõlked lisatud.

**Comment by TanelTromp** [comment]
Viga uus 2: mobiilivaates puuduvad väljad "sündmuse liigid" ja "sündmuse sildid" (kas nii pidigi olema? Ei mäleta aga ei ole loogiline)

Täpsustus: Kuhu kuvada veateade ja kuidas, kui kasutaja sisestab valed kalendriväärtused? 

ootab siis @ruut12 tõlkeid  "nimekiri" tekstile.

**Comment by madispold** [comment]
@TanelTromp 
Viga uus 2: Mobiilivaates sündmuse liigid ja sildid nähtaval.
Veateated lisatud (tõlked htm'is veel puudu) ja filtrivaated ühtlustatud + tehtud ruumi veateadetele juurde.

@ruut12 
Lisada 2 tõlget:
button.search_from_page: "Otsi lehelt"
errors.enter_valid_date: "Sisesta korrektne kuupäev"

**Comment by TanelTromp** [comment]
Viga uus 3: "täpne" ja "kitsam" filtri buttonile liikudes, ei teki "lingkäpa" kursorimärki:

https://gyazo.com/643425cae570795cd6e47dc379292f2c

**Comment by TanelTromp** [comment]
Ootab Ruudu tõlkeid, et DONEi kolida.
