### ISSUE TITLE
Kutsetunnistuste päring BE

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#378]
**Üldkirjeldus:**
Kasutaja on portaali kasutajaliidesel avanud töölaua ja soovib vaadata oma kutsetunnistuste andmeid (vt #383). 

**Tegevused:**
* Portaali back-end kontrollib andmete olemasolu vaheandmebaasist (REDIS).
* REDIS-st otsitav key on isikukood ja hash key on "kodanikKutsetunnistus".
* Kui REDIS-s on sellise key-ga kirje ja kirje sisuks ei ole viga (ei ole response.error elementi), siis
-- Portaali back-end edastab REDIS-st loetud response kasutajaliidesele.
* muul juhul :
-- Portaali back-end teeb päringu lõimest (vt #375). Päringu sisendis on timestamp ja kasutaja isikukood. Portaali back-end edastab lõimest saadud vastuse kasutajaliidesele. Lõime kirjutab ka vastuse REDIS-sse, et portaali back-end saaks selle sealt kätte, kui kasutaja tuleb uuesti andmeid vaatama.
 
***
* REDIS seadistada nii, et sealt kustutakse üle 30 minuti vanad kutsetunnistuste kirjed.

**Comment by TanelTromp** [comment]
Tõlkeid vajaka: 
![pilt](https://user-images.githubusercontent.com/37407917/45081467-f1856380-b0ff-11e8-9c48-f006c0da34ed.png)
