### ISSUE TITLE
WCAG - VO testimine: Uudised

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#380]
*UUDISED* nimekiri vaade +filter

Viga 1: jäljereal ei saa liikuda mitteaktiivse rea juurde (konkteerselt > uudised). Peaks

Viga 2: jäljeriea label ja kirjeldus on vale, peaks olema "breadcrumb navigation link  +label+clickable(kui on klikitava sügavusega)"

Viga 3: kui kasutaja on juba mingi alammenüü sisus, siis liikudes (nt TAB-iga), peaks järjekord olema teine, kui avalehel: avalehel Nr1: päis> sidebar > lehesisu. Alammenüüs: päis> filter>lehesisu (uudised) > sidebar

Viga 4: filtrile jõudes, peaks kirjeldama, et sinna on jõutud ja lühidalt võimalikke tegevusi (uudise nimi, kuupäevade sisestamine nt)

Viga 5: kui sisestada uudise nimi ja vajutada "ENTERIT", siis peaks kursor liikuma esimese arikli headingu peale (st jätma ülejäänud kriteeriumid vahele) ja kirjeldama, et otsingutulemuse andis selle ja selle tulemuse. Lisaks, kui kuvatakse, et "Otsingutulemusi ei ole", siis peab selle ka ettelugema

Viga 6: kui on saadud tulemuseks, et "Otsingutulemusei ei ole", siis filtrilt välja liikudes jõuab valesse kohta: brauseri tabile, peaks jõudma sidebarile

Viga 7: kuupäevade väljadele liikudes peaks ütlema, kuidas kuupäeva saab sisestada (NB! ilmselt seotud taskiga, kus palusin "pp/kk/aaaa" hint lisada - selle võiks näiteks ette lugeda)

Viga 8: kui vahetada kuud, siis peaks ütlema, et kuu on vahetatud

Viga 9: sulgemise "x"?

Viga 10: "Täpsem otsing" peaks olema "button" kirjelduses, mitte "link". Lisaks kirjeldus, et on "collapsed" hetkel or smthng ja vastavalt ka "kitsam otsin"

Viga 11: kui avada ja sulgeda "Täpsem otsing", siis peaks ettelugema, mis väljad avanesid ja kui suled, siis  "uncollapsed" or smthng

Viga 12: "uudiste sildid" kastil on label "combo box collapsed"? Puudu üldse "uudiste sildid" label.

Viga 13: sidebar menüüst ei pääse tabulateerides enam välja - jääb loopima sinna.

Viga 14: uudise minekirivaates ütleb tagi kohta "List":
![pilt](https://user-images.githubusercontent.com/37407917/43832343-d0a09c26-9b0f-11e8-9a23-c0d38e9fd791.png)

Viga 15: Lisatud piltide juuresp peaks lugema ainult kirjelduse, mis on BE-s lisatud "alt-tekstiks" ja teisi mitte: 
![pilt](https://user-images.githubusercontent.com/37407917/43832767-2b3faef0-9b11-11e8-9d9c-88672e7a4466.png)
Hetkel loeb muud pudru nagu titled jms juurde.

Viga 16: "lae rohkem" nuppu vajutades võiks öelda, nt "additional content loaded" vms

*Uudised detailvaade*

Viga 1: Autori nimel uudise juures võiks ka label olla, et "author" nt (nice2have)

Viga 2: pildi detailvaate sulgemise nupul label puudu
![pilt](https://user-images.githubusercontent.com/37407917/43834210-fc9e1730-9b15-11e8-84f0-c14026a797c4.png)

Viga 3: ei suuda tabulateerides tabada jagamise buttonit

Viga 4: "Loe veel" sidabarile liikudse svõiks öelda, et see on "sidebar loe veel"

**Comment by srautam** [comment]
News page
1. ok
2. ok
3. Jääb nii nagu on. Kuula Koka ranti, miks see ei ole hea idee.
4. ok
5.  Jääb nii nagu on. Kuula Koka ranti, miks see ei ole hea idee.
6. Selle jaoks oleks vaja broswerit ümber veidi koodima - koka sõnad. Liiga suur töö
7. Kokk Dissagrees
8. Kokk Dissagrees
9. Kokk Dissagrees
10. ok
11. ok 
12. Korda palun ?
13. See on suur viga ja lükata edasi järgmisse Spinti <--
14. Peabki nii olema. Tegmist on listiga, kus võib neid mulle veel olla. 
15. ok. pildile minnes kuvab teksti. selle alla captionile minne mitte.
16. Järgmise sprindi teema. homsel koosolekul arutada <--
Single news page
1. ok
2. ok
3. ok
4. Ei lea

**Comment by TanelTromp** [comment]
Viga 1: nüüd on küll tabulateeritav aga ei saa liikuda ekraanilugejaga. Lisaks ei ütle "ava

**Comment by srautam** [comment]
1. vajab uurimist
2. ok
5. Announe oleks suurem ettevõtmine, tõstada üle koosolekul, suhelda Kokkaga.
11. Veidral põhjusel mul ütleb, kui seda testid kutsu mind

2. On olemas, mul töötab. kui pildi avab kohe focukeesrib sulguri ja announceib
3. ok

**Comment by TanelTromp** [comment]
Debuggingu nrid, ei vasta eelmisele vearaportile. Nt (nr 4, üldse ei ole). EI saa aru, mille kohta käivad. Palun esimesest kommentaarist vigade kirjeldused juurde tuua.

**Comment by srautam** [comment]
- [ ] Viga 2: pildi detailvaate sulgemise nupul label puudu

- [ ] Viga 3: Tegu "korraliku" angulari komponendiga, millele WCAG külge ei hakka. Kokka poole pöörduda selles osas

**Comment by TanelTromp** [comment]
Viga 2: endiselt ei saa selle peale liikuda ega akent sulgeda.

**Comment by TanelTromp** [comment]
Viga 2 lisa: nupp küll selekteeritav ja leitav tabiga aga ainult nimega "Button", ei ütle "close" ja ei ole enteriga suletav.
