### ISSUE TITLE
WCAG -  testimine: sündmused

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#381]
*Sündmused nimekiri vaade*

Viga 0: FILTER > vaadata uudiste vearaportis välja toodud puudusi
Viga 1: „List“ või „Kalender“ ikoonidele liikudes võiks öelda ka, et mis on hetkel „selected“  lisada labelile „view“ või täpsustava labeli, mida see tähendab. (Nt: hetkel kui häälugejaga minna „kalender“ peale, siis ei saa aru, et mis kalender see siis on? Maaja?)
Nice to have 1: kuupäeva ja päeva võiks lugeda korraga maha ühes jorus
Viga 2: korduva sündmuse ikooni,  „alguseaeg“ taga, ekraanilugeja välja ei loe
Viga 3: ekraanilugeja ei loe välja siltide nimetust (tabulateerides on korras): ütleb clickable list cklickable. P.s see võib olla PC kala ja MAC+VO võib töödata
Viga 4: selekteeritav on ainult esimene silt, teiselt(ja kolmandalet jne) libiseb üle kohe järgmise kuu peale (nt August)
Viga 5: „Lae rohkem“ nuppu vajutades võiks õelda, mis juhtus st, mida juurde kuvati
Viga 6:  kui kalender vaade on avatud ja liikudes tagasi TABiga filtrile, enam kalendri vaatele edasi TABiga liikudes ei pääse – viskab brauseri URL-i info nupule.
Täpsustus 1: kas tabulateerides peaks pääsema ka „List“ ja „Kalendervaatele“ ligi? Hetkel ei saa ja ka muidugi seeläbi seal sees ei saa tabulateerida kuupäevadel.
Viga 7: kui avada „Kalender“vaade, siis võiks õelda, et avas kalendri.
Viga 8: avatud kalendris ei saa vahetada kuid, vaid selle asemel loeb maha tähthaaval labeli (A U G U S T).
Viga 9: liikudes kalendris ringi ütleb 1.august kolmapäeva kohta: „Kolmapäev column 3 1“ - see tundub väga segane – mis infot see tulp peaks andma? Aga ma ei ole kindel, et kuidas seda lahendada ja kas peaks. Nt võiks olla ju, et ütlebki „kolmapäev 1.august“ „neljapäev 2. august“ jne?
Viga 10: kui jõuda ekraanilugejaga kuupäevale, kus on ka sündmus(ed), võiks selle koos kuupäevaga ette lugeda. P.S Ei ole kindel, et see on õige 100%.
Viga 11: avatud kalendri vaates loeb ekraanilugeja ära enne kalendrilahtirtesse jõudmist ka kõik nädalapäevade labelid. Neid ei ole vaja. NB! Vt	 ka viga 9.
Viga 12: kui avada kalendrist sündmuse modaali, siis peaks ette lugema avanenud modaali sisu.
Viga 13: avanenud sündmuse kirjelduse modaalilt ei tohiks välja saada liikuda (nn „off focus content“ peab surnud olema)
Viga 14: avanenud sündmuse kirjelduse modaalil ei saa navigeerida „x“ sulgemise nupule (puudu ka „button close“ label sellel). 

*Sündmuse detailvaade*

Viga 1: sotsiaalmeedia jagamise button ei ole ekraanilugejaga tabatav ja avatav.
Viga 2: „Keeltetegu Leedus“ pearlkirja ja sissejuhatava teksti vahel on kaks „graphic clickable elementi“, mis on avamata sotsiaalmeedia jagamise buttoni sisud: Facebook ja Twitter, millele tuleks siis labelid luua.
Viga 3: ekraanilugejaga ei saa valida linke sisutekstist (tabulateerides töötas). P.S see võib olla PC+NVDA kala ja MAC+VO võib töötata
 

Viga 4: Google kaardile liikudes küljeribal, puudu õige label (hetkel ütleb „clickable clickable clickable link“)
Viga 5: „Kontakt“ all peaks lugema telefoninumbrile liikudes ka labeli („telephone“) ja kena oleks, kui ka „e-mail link“> „link“ asemel loeks.
Viga 6: „Registeerimisvormi“ modaalil ei saa liikuda „x“ close nupule (ka label puudu)
Nice to have 2: „registreerimisvormi“ väljade puhul võiks öelda ka, et mis väli on kohustuslik, kui väljale liikuda
Viga 8: „registreerimisvormi“ „Tühista“ nupp peab olema „button“, mitte „link“ labeliga.
Viga 9: „registreerimisvormil“ ekraanilugejaga liikudes loeb sisestusvälja labeli eraldi välja, mida vaja ei ole. Piisaks, kui loeks nt „eesnimi edit has autocomplete“ (hetkel saab „eesnimi“ peale eraldi liikuda ekraanilugejaga).

Viga 10: „Sarnased sündmused“ blokile liikudes võiks öelda ka, et „Sarnased sündmused list with „x“ item“ or stmhng. Hetkel ütleb ainult labeli „Sarnased sündmused“

**Comment by srautam** [comment]
POOLELI !

Sündmused nimekiri vaade

- [ ] Viga 0: FILTER > vaadata uudiste vearaportis välja toodud puudusi

- [ ]  Viga 1: „List“ või „Kalender“ ikoonidele liikudes võiks öelda ka, et mis on hetkel „selected“ lisada labelile „view“ või täpsustava labeli, mida see tähendab. (Nt: hetkel kui häälugejaga minna „kalender“ peale, siis ei saa aru, et mis kalender see siis on? Maaja?)
Nice to have 1: kuupäeva ja päeva võiks lugeda korraga maha ühes jorus
- [ ] Viga 2: korduva sündmuse ikooni, „alguseaeg“ taga, ekraanilugeja välja ei loe
- [ ] Viga 3: ekraanilugeja ei loe välja siltide nimetust (tabulateerides on korras): ütleb clickable list cklickable. P.s see võib olla PC kala ja MAC+VO võib töödata
- [ ] Viga 4: selekteeritav on ainult esimene silt, teiselt(ja kolmandalet jne) libiseb üle kohe järgmise kuu peale (nt August)
- [ ] Viga 5: „Lae rohkem“ nuppu vajutades võiks õelda, mis juhtus st, mida juurde kuvati
- [ ] Viga 6: kui kalender vaade on avatud ja liikudes tagasi TABiga filtrile, enam kalendri vaatele edasi TABiga liikudes ei pääse – viskab brauseri URL-i info nupule.
Täpsustus 1: kas tabulateerides peaks pääsema ka „List“ ja „Kalendervaatele“ ligi? Hetkel ei saa ja ka muidugi seeläbi seal sees ei saa tabulateerida kuupäevadel.
- [ ] Viga 7: kui avada „Kalender“vaade, siis võiks õelda, et avas kalendri.
- [ ] Viga 8: avatud kalendris ei saa vahetada kuid, vaid selle asemel loeb maha tähthaaval labeli (A U G U S T).
- [ ] Viga 9: liikudes kalendris ringi ütleb 1.august kolmapäeva kohta: „Kolmapäev column 3 1“ - see tundub väga segane – mis infot see tulp peaks andma? Aga ma ei ole kindel, et kuidas seda lahendada ja kas peaks. Nt võiks olla ju, et ütlebki „kolmapäev 1.august“ „neljapäev 2. august“ jne?
- [ ] Viga 10: kui jõuda ekraanilugejaga kuupäevale, kus on ka sündmus(ed), võiks selle koos kuupäevaga ette lugeda. P.S Ei ole kindel, et see on õige 100%.
- [ ] Viga 11: avatud kalendri vaates loeb ekraanilugeja ära enne kalendrilahtirtesse jõudmist ka kõik nädalapäevade labelid. Neid ei ole vaja. NB! Vt	ka viga 9.
- [ ] Viga 12: kui avada kalendrist sündmuse modaali, siis peaks ette lugema avanenud modaali sisu.
- [ ] Viga 13: avanenud sündmuse kirjelduse modaalilt ei tohiks välja saada liikuda (nn „off focus content“ peab surnud olema)
- [ ] Viga 14: avanenud sündmuse kirjelduse modaalil ei saa navigeerida „x“ sulgemise nupule (puudu ka „button close“ label sellel).

Sündmuse detailvaade

- [ ] Viga 1: sotsiaalmeedia jagamise button ei ole ekraanilugejaga tabatav ja avatav.
- [ ] Viga 2: „Keeltetegu Leedus“ pearlkirja ja sissejuhatava teksti vahel on kaks „graphic clickable elementi“, mis on avamata sotsiaalmeedia jagamise buttoni sisud: Facebook ja Twitter, millele tuleks siis labelid luua.
- [ ] Viga 3: ekraanilugejaga ei saa valida linke sisutekstist (tabulateerides töötas). P.S see võib olla PC+NVDA kala ja MAC+VO võib töötata

- [ ] Viga 4: Google kaardile liikudes küljeribal, puudu õige label (hetkel ütleb „clickable clickable clickable link“)
- [ ] Viga 5: „Kontakt“ all peaks lugema telefoninumbrile liikudes ka labeli („telephone“) ja kena oleks, kui ka „e-mail link“> „link“ asemel loeks.
- [ ] Viga 6: „Registeerimisvormi“ modaalil ei saa liikuda „x“ close nupule (ka label puudu)
Nice to have 2: „registreerimisvormi“ väljade puhul võiks öelda ka, et mis väli on kohustuslik, kui väljale liikuda
- [ ] Viga 8: „registreerimisvormi“ „Tühista“ nupp peab olema „button“, mitte „link“ labeliga.
- [ ] Viga 9: „registreerimisvormil“ ekraanilugejaga liikudes loeb sisestusvälja labeli eraldi välja, mida vaja ei ole. Piisaks, kui loeks nt „eesnimi edit has autocomplete“ (hetkel saab „eesnimi“ peale eraldi liikuda ekraanilugejaga).

- [ ] Viga 10: „Sarnased sündmused“ blokile liikudes võiks öelda ka, et „Sarnased sündmused list with „x“ item“ or stmhng. Hetkel ütleb ainult labeli „Sarnased sündmused“

**Comment by TanelTromp** [comment]
CHROME+NVDA
Viga 1 uus: sündmuste kalendri vaates ei loe sündmuse nime ette sellele liikudes, vaid ütleb "button". 

Viga 2 uus: sündmuste kalendri vaate modaalil ei ütle sulgemise ("x") nupu nime, vaid lihtsalt "button"
