### ISSUE TITLE
Kutsetunnistuste andmete kuvamine töölaual

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#383]
**Üldkirjeldus:**
Kasutaja näeb enda kutsetunnistuste andmeid.

**Eeltingimused ja käivitamine:**
* Kasutaja on portaali sisse loginud. Portaalis on teada kasutaja isikukood.
* Portaal avab töölaua kasutajale pärast sisse logimist.
* Kutsetunniste nägemiseks kasutaja valib töölaual "Dokumendid" -> "Kutsetunnistused"

**Tegevused**
- [x] Kutsetunnistuste saamiseks tehakse päring back-end-i kaudu Kutseregistrist (vt #378). Kuvatakse Kutseregistrist saadud kutsetunnistuste nimistu. 
- [x] Kasutaja saab avada nimistust kutsetunnistuse. Kuvatakse kutsetunnistuse andmed (detailvaade). Kutsetunnistuse kohta kuvatavad andmed on kirjeldatud allpool.
- [ ] Breadcrumbi kaudu saab uuesti avada töölaua dokumentide ja tunnistuste saki.

**Erijuhud ja täpsustused:**
-  [x] Kui Kutseregistrist ei saadud ühtegi kutsetunnistuse kirjet, siis kuvatakse teade "Kutsetunnistused puuduvad".
-  [x] Kui Kutseregistrist saadi mitu kutsetunnistust, siis need järjestatakse välja andmise aja järgi kuupäevalises järjestuses hilisemad kuupäevad eespool.
-  [x] Kui on error, siis kuvatakse veateade "Vabandame. Kutsetunnistuste andmete Kutseregistrist lugemise käigu tekkis tehniline viga. Palun proovige hiljem uuesti."
-  [x] Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuva (silti ka mitte).

****
Disain:
https://zpl.io/2vWKxNQ - nimekiri
https://zpl.io/b6vjqjm - detailvaade
https://zpl.io/VDn1W6q - kehtetu
https://zpl.io/bAEnW6n - duplikaat

****
**Kutsetunnistuste nimistus kuvatavad andmed:**
* Kutsestandard - standard 
* Välja antud - valjaantud
_/ Võivad muutuda, vaatame mis andmed tegelikult tulevad ja siis vajadusel muudab/ _

**Kutsetunnistuse kohta detailvaatel kuvatavad andmed (ekraanil silt - andmeelement):**
* Tunnistuse number - registrinumber 
* Tunnistusel nimi - nimi
_isikukoodi ja sünniaega ei kuva_
* Tüüp - tyyp
* Kutsestandard - standard 
* EKR tase - ekrtase
* EQF tase - eqftase
* Spetsialiseerumine - spetsialiseerumine
* Osakutse - osakutse
* Valitud kompetentsid - kompetentsid
* Valdkond - valdkond
* Kutseala - kutseala
* Hariduslik kvalifikatsioon - hariduslikkval
* Kutseeksami keel - keel
* Väljastaja - valjastaja
* Välja antud - valjaantud
* Kehtib alates - kehtibalates
* Kehtib kuni - kehtibkuni
* Ametite (ISCO) klassifikaator - isco
* [x] Kui duplikaat väärtus on _true_, siis kuvada "Dublikaat"
* [x] Kui kehtetu väärtus on _true_, siis kuvada "Tunnistus on kehtetu" _(disainis kehtetule selgelt eristuv kujundus)._

**Selle töö raames realiseeritakse töölaual:**

-  [x] breadcrumb
-  [x] päis (töölaud + kasutajanimi; ilma rolli vahetuseta)
-  [x] valikusakid (taoltused, tunnistused, õpingud, õpetan)
-  [x] tunnistuste all kutsetunnistuste osa

**Comment by RaimoJohanson** [comment]
Kokkulepe Andrusega: "Breadcrumbi kaudu saab uuesti avada töölaua dokumentide ja tunnistuste saki." - nõuet pole vajalik täita kutsetunnistuse detailvaates.

**Comment by TanelTromp** [comment]
Viga 1: sisselogides ei avane töölaud >"Portaal avab töölaua kasutajale pärast sisse logimist."

Viga 2: breadcrumbsil peab ees olema ka "Töölaud:" Nagu Zeplini vaates (ehk Töölaud:tunnistused):
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b7ea597e0d83c35a9bbc5c3

Viga 3: kuupäeva vorm ei vasta zeplinile

Viga 4: "Vaata rohkem" joondatud vasakule, Zeplinis on "Vaata lähemalt" ja joondadatud keskele

Viga 5: ikoonid on kõik mustad, zeplinis aga sinised ja valitud ikoon ainsana must.

Viga 6: tingimus täitmata "Kui Kutseregistrist saadi mitu kutsetunnistust, siis need järjestatakse välja andmise aja järgi kuupäevalises järjestuses hilisemad kuupäevad eespool". Hetkel vastupidi, varasemad eespool:

![pilt](https://user-images.githubusercontent.com/37407917/45083618-fbf62c00-b104-11e8-8a3c-18b4663065db.png)

**Comment by RaimoJohanson** [comment]
Viga 3 ja 6 parandatud

**Comment by TanelTromp** [comment]
Viga 7: "Duplikaat" kirje kuvamine ei vasta Zeplini kujundusele

![pilt](https://user-images.githubusercontent.com/37407917/45086983-2946d800-b10d-11e8-84ea-864f9e7d6cf4.png)

**Comment by srautam** [comment]
- [x] Viga 1: sisselogides ei avane töölaud >"Portaal avab töölaua kasutajale pärast sisse logimist."

- [ ] Viga 2: breadcrumbsil peab ees olema ka "Töölaud:" Nagu Zeplini vaates (ehk Töölaud:tunnistused):
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5b7ea597e0d83c35a9bbc5c3

- [x] Viga 3: kuupäevavorm/esitlusviis ei vasta zeplinile

- [ ] Viga 4: "Vaata rohkem" joondatud vasakule, Zeplinis on "Vaata lähemalt" ja joondatud keskele

- [ ] Viga 5: ikoonid on kõik mustad, zeplinis aga sinised ja valitud ikoon ainsana must.

- [x] Viga 6: tingimus täitmata "Kui Kutseregistrist saadi mitu kutsetunnistust, siis need järjestatakse välja andmise aja järgi kuupäevalises järjestuses hilisemad kuupäevad eespool". Hetkel vastupidi, varasemad eespool:

- [ ] Viga 7: "Duplikaat" (ja ka "kehtetu") kirje kuvamine ei vasta Zeplini kujundusele

- [ ] Viga 8: detailvaate kuupäevavormid ei vasta Zeplinile.

- [ ] Viga 9: detailvaate kõik parema tabeli poolsed väärtused peavad hakkama suure algustähega.

- [ ] Viga 10: detailvaates puudub breadcrumbs:

- [ ] Viga 11: kui kutsetunnistuse detailvaatest välja logida, siis jääb "Loader" saagima. Probleem ei esine nimekiri vaates.

**Comment by RaimoJohanson** [comment]
Viga 2: breadcrumbsil peab ees olema ka "Töölaud:" Nagu Zeplini vaates (ehk Töölaud:tunnistused) - @ruut12

**Comment by TanelTromp** [comment]
Viga 4.2: "Vaata lähemalt, mitte "Vaata rohkem":
![pilt](https://user-images.githubusercontent.com/37407917/45345007-c7272080-b5ad-11e8-9794-cd0352600d4d.png)

Viga 9: _detailvaate kõik parema tabeli poolsed väärtused peavad hakkama suure algustähega_. Nüüd algavad aga ka kõik teised sõnad, peab olema ainult esimese sõna algustäht suur, mitte kõigi:

![pilt](https://user-images.githubusercontent.com/37407917/45345133-18371480-b5ae-11e8-9544-a55efa51d3cc.png)

Viga 12: kui keelt vahetada, siis kuvab ERROR lehe:
https://gyazo.com/59148fa925e1f4965a2047ea148af648

**Comment by srautam** [comment]
viga 4.2 korras, aga pole live veel jõudnud
viga 8. korras
viga 12. üleüldine bugi, Ruut tegeleb sellega eraldi.

**Comment by TanelTromp** [comment]
Viga 13: "tagasi töölauale" nupul võiks EST>ENG tõlge olla:

![pilt](https://user-images.githubusercontent.com/37407917/45420385-b0a6c500-b692-11e8-9684-1a67aab346e4.png)

**Comment by RaimoJohanson** [comment]
Viga 13: @ruut12  @lsoonvald

**Comment by lsoonvald** [comment]
Viga 13: Done.
