### ISSUE TITLE
getDocuments teenus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#388]
**Üldkirjeldus**
Portaal back-end küsib töölaual kuvamise jaoks taotluste ja otsuste andmeid (vt #391). Lõime komponent teeb X-tee kaudu infosüsteemidest päringud, teisendab saadud vastuse sisu JSON formaati ja kirjutab vaheandmebaasi (REDIS-sse):
- esitatud/väljastatud dokumendid
- sisestamisel olevad dokumendid (mustandid)
- võimalikud esitatavad või nõutavad dokumentide nimed.

**Tegevused:**
* Lõime teenuse sisendis on 
-- _user_identifier_ : kasutaja isikukood (kohustuslik), 
-- _represented_person_identifier_ : esindatava isiku isikukood (mittekohustuslik) ja 
-- _represented_organization_identifier_ : esindatava ettevõtte registrikood (mittekohustuslik).
* Kui sisendis on _represented_person_identifier_ või _represented_organization_identifier_, siis infosüsteemidest küsitakse selle isiku või organisatsiooni andmed. Muul juhul küsitakse infosüsteemidest andmed  _user_identifier_ alusel. 
* _Kui iga dokument eraldi objektina, siis peaks lisama päringu 0-objekti. Seda kasutaks portaal kontrollimiseks, kas päring on tehtud_
* REDIS-sse kirjutatava vastuse value on JSON formaadis.
* REDIS-sse kirjutatava vastuse elemendid on _request_timestap_, _response_timestamp_ ja _getDocuments_response_ (vt allpool)
* Kui X-tee päringu tegemine ei õnnestu, siis response sisu on "error" : true ja viga kirjutatakse logisse

***

* **Vajaduspõhise õppetoetuse taotluse (VPT) erandeid kirjeldab #389.**

**Comment by heldiraudsepp** [comment]
Tehtud, aga liigutamata jäänud
