### ISSUE TITLE
getDocumentFile BE

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#393]
Käivitamine: Portaali kasutaja klikkis kuvatud faili linki. Portaali FE küsib BE-st faili.

**Tegevused:**
1. Portaali BE teeb getDocumentFile päringu lõimest (#232, #168 ).
2. Portaali BE edastab faili FE-le.

**Comment by heldiraudsepp** [comment]
Testime läbi VPT taotluse
