### ISSUE TITLE
Töölaual parema ääre-riba kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#398]
**Eesmärk, üldtingimused:**
Sisseloginud kasutajale kuvatakse töölaua paremas veerus blokke:
 - Lemmikud
 - Sündmused

**Eeltingimused ja käivitamine:** 
- Kasutaja on portaali sisse loginud. 
- Portaali töölaud avaneb kasutajale pärast sisse logimist.
- Sisse loginud kasutaja saab töölauale navigeerida (vt disaini)

**Vastuvõtutingimused:** 
Sisse loginud kasutajale kuvatakse töölauda, mille paremas veerus kuvatakse blokid:

**1. Lemmikud**
Kuvamine realiseeritud ja testimine piletis #285
Kui kasutajal lemmikud puuduvad - vt kujundust - https://zpl.io/2vWKxNQ.

**2. Sündmused**
- [x] Kuvatakse portaali sisestatud sündmusi (Event)
- [x] Sündmuse kohta kuvatakse nimetus (name), toimumise kuupäev (EventCalendarItem.eventDate), alguse kellaaeg (EventCalendarItem.startTime)  
- [x] Kuvatakse kuni 3 järgmisena algavat sündmust. Sündmused on järjestatud alguse aja järjekorras (varem algav eespool).
- [ ] Kui sündmusel on mitu toimumisaja (EventCalendarItem) kirjet, siis andmed võetakse kõige varasema toimumise kuupäevaga ja alguse ajaga kirjest.
- [x]  Kuvatud sündmuselt saab minna vaatama sündmuse detailvaadet.
- [x]  Saab minna vaatama sündmuste nimistut.

Lisatud 30.10.2018:
Kui sündmused puuduvad siis see osa jääb tühjaks - ei kuva midagi. @madispold 

https://zpl.io/2vWKxNQ

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by madispold** [comment]
Stiilid lisatud @TanelTromp @birgitpulk

**Comment by TanelTromp** [comment]
Viga 1: võiks olla ka aasta märgitud lisaks kuupäevale, kui viimaste sündmuste hulgas on ka järgmise aasta sündmus, siis võib segane tunduda:

![pilt](https://user-images.githubusercontent.com/37407917/47711130-249a2e00-dc3d-11e8-8984-d0aae1972cf7.png)

Viga 2: nõue ei ole täidetud, hetkel võtab kuupäevaks sündmuse põhikuupäeva: _Kui sündmusel on mitu toimumisaja (EventCalendarItem) kirjet, siis andmed võetakse kõige varasema toimumise kuupäevaga ja alguse ajaga kirjest._
Testlugu, kus kõige varasem kuupäev on 12.10 (lisakuupäev) aga kuvatakse 30.10 (põhikuupäev):
http://htm.twn.ee/et/sundmused/mitu-kuupaeva-sundmus

Viga 3: muudatus veel tegemata _Lisatud 30.10.2018:
Kui sündmused puuduvad siis see osa jääb tühjaks - ei kuva midagi. @madispold_

**Comment by madispold** [comment]
Viga 1: Kujunduses hetkel pole aastat, kuid hea idee, @birgitpulk mis sa arvad?
Viga 2: Nõue täitub esmaspäeval räägitud BE piirangu rakendamisel - sündmuse peakuupäev peab olema kõige varasem tuleviku kuupäev võrreldes lisakuupäevadega.
Viga 3: OK.

**Comment by birgitpulk** [comment]
Viga 1: Võiks olla sama loogika nagu sündmuste nimekirja vaate puhul, et käesoleva aasta sündmuse puhul ei kuva aastat, aga kui on nt järgmine aasta, siis lisatakse aasta nr ka. @madispold @TanelTromp

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
Viga 1: punkt ka vast enne aastaaega vahele @birgitpulk 

![pilt](https://user-images.githubusercontent.com/37407917/47773589-3b02c100-dcf3-11e8-81d5-8a13ebdd0ccd.png)

**Comment by birgitpulk** [comment]
Formaat võiks olla jah pp.kk.aaaa
Kas "Kell" ei peaks olema väikse tähega? @TanelTromp

**Comment by TanelTromp** [comment]
jah, sul on õigus! Õige on: "31.10.2019 kell 10.00"

**Comment by madispold** [comment]
Viga 1: OK - vastavalt viimastele kommentaaridele.

**Comment by TanelTromp** [comment]
Viga 4 uus: nõue ei ole täidetud, peaks olema ka kellaja tundlik. Hetkel ainult kuupäeva:
_Kuvatakse kuni 3 järgmisena algavat sündmust. Sündmused on järjestatud alguse aja järjekorras (varem algav eespool)._
![pilt](https://user-images.githubusercontent.com/37407917/47791192-c4c98300-dd21-11e8-8163-d594efdc96cb.png)

**Comment by madispold** [comment]
Viga 4 uus: OK.
Mis "Vaata kõiki" nupuga teeme siis? @birgitpulk

**Comment by TanelTromp** [comment]
Viga 5 uus: kui sündmusi ei ole, siis kas on võimalik ka selle loaderit mitte kuvada? Kasujtajal võib tekkida küsimus, kas sündmused pidid sinna ilmuma aga midagi crashis?
https://gyazo.com/4c2495be04e3aa05f13ceebeddfc398a

Viga 6 uus: loadimisel tekivad Chromega korraks scrollbarid:
https://gyazo.com/4c2495be04e3aa05f13ceebeddfc398a

**Comment by madispold** [comment]
Viga 5 uus: OK.
Viga 6 uus: OK.
Muudatus 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Kuvatakse portaali sisestatud sündmusi (Event)
- [x] Sündmuse kohta kuvatakse nimetus (name), toimumise kuupäev (EventCalendarItem.eventDate), alguse kellaaeg (EventCalendarItem.startTime)
- [x] Kuvatakse kuni 3 järgmisena algavat sündmust. Sündmused on järjestatud alguse aja järjekorras (varem algav eespool).
- [ ] Kui sündmusel on mitu toimumisaja (EventCalendarItem) kirjet, siis andmed võetakse kõige varasema toimumise kuupäevaga ja alguse ajaga kirjest. - **hetkel realiseerimata seoses sellega, et sündmuse lisakuupäeva saab olla varasem, kui põhikuupäev**
- [x] Kuvatud sündmuselt saab minna vaatama sündmuse detailvaadet.
- [x]   Saab minna vaatama sündmuste nimistut.

Lisatud 30.10.2018:
- [x] Kui sündmused puuduvad siis see osa jääb tühjaks - ei kuva midagi.

**Comment by birgitpulk** [comment]
"Vaata kõiki" jääb nii nagu on
Muus osas kujundus korras!
