### ISSUE TITLE
Koormustestid

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#402]
Päringute kaardistamine koormustestide jaoks.
Koormustestide rakenduse leidmine ja käimapanek.
Koormustestid back- ja frontendi cacheta.
Koormustestid back- ja frontendi cachega.

**Comment by markoleppik** [comment]
Etapp1
1. Koormustestide vajavate lehtede nimekirja loomine
2. Koormustestide teostamine vastavalt hanke nõuetele
3. Tulemuste analüüs

Etapp2
1. Cache aktiveerimine FE ja BE poolel.
2. Koormustestide taaskäivitamine
3. Tulemuste analüüs ning kitsas kohtade tuvastamine
4. Tulemuste alusel FE või BE poolel koodi täiendamine
5. Koormustestide taaskäivitamine

**Comment by lsoonvald** [comment]
Päringute cache ei tule Redisest, vaid baasist, uurida, kas on võimalik GraphQL päringute cache Redisesse liigutada.

**Comment by lsoonvald** [comment]
Koormustestid eri tüüpi päringutega erinevatel seadistustel.
[Koormustestid.xlsx](https://github.com/hariduspilv/haridusportaal/files/2327687/Koormustestid.xlsx)
