### ISSUE TITLE
WCAG - VO Angulari poolsed muudatused

### ISSUE THREAD

**Issue by srautam** [hariduspilv/haridusportaal#404]
Task 1: Sidebari Dropdown peab sulguma kui avad uue Dropdowni. Lisaks peab "esc" selle sulgema.

Task 2: Navbari Login Dropdown ja keele Dropdown ja sündmuste vaate kalendri Dropdown, Favourites Dropdown peavad sulguma 'esc'.

Task 3: Keelt vahetades peab ka <html lang="KEEL"> tagi sees keel vahetuma.

Task 4: Navbaris peidetud "Skip to main content" link tööle panna.

Task 5: Sündmuste kalendris avanenud sündmuse kirjelduse modaalilt ei tohiks välja saada liikuda (nn „off focus content“ peab surnud olema)
 
Task 6: Atriklites ja veel müned vaates akkordioni noolelele aria-hidden = true vaja peale panna.

**Comment by TanelTromp** [comment]
CHROME+NVDA
Viga 1 uus: sündmuste kalendri vaates ei loe sündmuse nime ette sellele liikudes, vaid ütleb "button".

Viga 2 uus: sündmuste kalendri vaate modaalil ei ütle sulgemise ("x") nupu nime, vaid lihtsalt "button"

Task 4: _Navbaris peidetud "Skip to main content" link tööle panna_ - ei ole endiselt.

**Comment by madispold** [comment]
Viga 1 uus: OK.
Viga 2 uus: OK.
Task 4: Ok.
