### ISSUE TITLE
WCAG erkaanilugejaga testimine - artikkel

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#407]
Viga 1: ekraanilugeja ei loe välja artikli nime, vaid ütleb ainult „heading level 1 title“. Peaks lugema ka artikli nime.
Viga 2: sotsiaalmeedia jagamise button on puudu (st tabamatu tabulateerides ja ekraanilugejaga liikudes) selles avanevad labelid.
Viga 3: artikli pildile liikudes ei pea enam alttekst eraldi selekteeritav olema.
Viga 4: youtubei videole liikudes palun vaadata üle, mis tabulateerides on valitav hetkel ja tühjad arusaamatud sisud eemaldada. Võiks jääda ainult „watch later“ „share“ ja „play“ ning video alttekst ja video pealkiri.
Viga 5: akordionil on „expand“ noole nupp eraldi selekteerivav ekraanilugejaga ja ei ole valitav (st „ENTER“ ei tööta). Selle võiks üldse ehk ära kaotada ja jätta „button collapsed expand more“ ainult ning järgmine liikumine juba järgmisele akordioni osale. Nagu on hetkel tabulateerides.
Viga 6: „Lisainfo“ paremale tulbale liikudes ütleb: „contlempotary landmark“ – ma ei tea mis see on ja miks ta seda ütleb? Võiks ära jätta.
Viga 7: „Kontakt“ tulbas paremal peaks ette lugema väljad koos labelitega (telephone number:….“, E-mail address….: „
Viga 8: „Leia kiiresti“ ja „Sarnased teemad“ all paremas tulbas peaks välja lugema ka lingi nime, hetkel ei loe:

**Comment by srautam** [comment]
- [x] Viga 1: ekraanilugeja ei loe välja artikli nime, vaid ütleb ainult „heading level 1 title“. Peaks lugema ka artikli nime.

- [x] Viga 2: sotsiaalmeedia jagamise button on puudu (st tabamatu tabulateerides ja ekraanilugejaga liikudes) selles avanevad labelid.
- [x] Viga 3: artikli pildile liikudes ei pea enam alttekst eraldi selekteeritav olema.
- [ ] Viga 4: youtubei videole liikudes palun vaadata üle, mis tabulateerides on valitav hetkel ja tühjad arusaamatud sisud eemaldada. Võiks jääda ainult „watch later“ „share“ ja „play“ ning video alttekst ja video pealkiri.

_Ei leidnud video näidet :(_

- [ ] Viga 5: akordionil on „expand“ noole nupp eraldi selekteerivav ekraanilugejaga ja ei ole valitav (st „ENTER“ ei tööta). Selle võiks üldse ehk ära kaotada ja jätta „button collapsed expand more“ ainult ning järgmine liikumine juba järgmisele akordioni osale. Nagu on hetkel tabulateerides.
- [ ] Viga 6: „Lisainfo“ paremale tulbale liikudes ütleb: „contlempotary landmark“ – ma ei tea mis see on ja miks ta seda ütleb? Võiks ära jätta.

_Ei leidnud Lisainfo näidet :(_

- [x] Viga 7: „Kontakt“ tulbas paremal peaks ette lugema väljad koos labelitega (telephone number:….“, E-mail address….: „
- [x] Viga 8: „Leia kiiresti“ ja „Sarnased teemad“ all paremas tulbas peaks välja lugema ka lingi nime, hetkel ei loe:

**Comment by TanelTromp** [comment]
Videoga artikkel: http://htm.twn.ee/et/artiklid/valisministeeriumi-teadaanne-valisleping
