### ISSUE TITLE
WCAG erkaanilugejaga testimine - erialad

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#408]
Erialad nimekiri vaade

Viga 1: Puudu „H1“ headingud. Pealkirjad peaks olema H1
Viga 2: „Lae rohkem“ buttonit vajutades, peaks ütlema, et mis juhtus -st mida kuvati ja kui palju.
Viga 3: „Eriala tüüp“ filtrit avades, peaks ütlema, mis juhtus (st mida kuvati)
Viga 4: „Eriala tüüp“ filtris ei saa ekraanilugejaga valikuid selekteerida (kui valik tulevikus töötab, siis õelda, ka mis valiti jms)
Viga 5: „Täpsem otsing“ peaks olema „Button“ mitte „link“ labeliga
Viga 6: „Lisa võrdlusesse“ checkboxi järjekord peaks olema peale eriala kuvatud sisu ehk viimane selles lahtris
Viga 7: Ekraanilugejaga „Liva võrdlusse“ peale liikudes, võiks õelda ja teha sama, mis tabulateerides – hetkel saab liikuda checkboxile ja „Lisa võrdlusse“ eraldi ja see tekitab segadust. 

Erialad detailvaade
Viga 1: vasakust sidebar menüüst ei pääse välja – ei ekraanilugejaga ega ka tabulateerides
Viga 2: breadcrumbsile liikudes, peaks ütlema, et tegu on „breadcrumbsiga“ ja kõik sügavused peakvad olema ekraanilugejaga selekteeritavad.
Viga 3: „Erialad“ peale liikudes ütleb, „Out of list erialad“ peaks ütlema „erialad“ vast.
Viga 4: Sotsiaalmeedia share nuppu ei saa avada („enter“) 
Viga 5: Tabel. need „cell“ ja „row“ lugemised võiks ära jätma ja pigem liikudes nt tabeli paremal pool olevale labelile, ka kohe selle väärtuse, mis asub teises tulbas välja lugema. Nt „Registrikood 70004092“. St mitte eraldi. Lisaks loeb alati tulba pealkirja väljasisu ette (konkreetselt „Tartu Kunstikool“ või „Õppeastutuse nimi“ ja siis konkreetne väljaväärtus. Seda ei peaks tegema.
http://htm.twn.ee/et/erialad/3d-modelleerija-visualiseerija
Viga 6: küljeriba vasakul. „Kontakti“ sektsioonis võiks öelda ka labeli sisudele ette (telefon, e-kiri, koduleht)
Viga 7: küljeriba vasakul.  Kaardile liikudes, ei ütle ekraanilugeja ega TAB õiget sisu.
Viga 8: „Vaata sarnaseid erialasid“ CTA-d vajutades, peaks ütlema, mitu vastet kuvati. Hetkel ei ütle, et midagi avanes.
Viga 9: sarnaste erialade headingud puudu pealkirjadel?

**Comment by TanelTromp** [comment]
Erialad nimekiri vaade:

Viga uus 1: kui ma vajutan "lae veel" buttonit ja siis tabi, peaks fookuse viima esimesele erialale, mis juurde tuli. Hetkel viib uuesti "lae veel" buttonile.

Detailvaade:

**Comment by srautam** [comment]
- [ ] Viga uus 1: kui ma vajutan "lae veel" buttonit ja siis tabi, peaks fookuse viima esimesele erialale, mis juurde tuli. Hetkel viib uuesti "lae veel" buttonile.

Detailvaade:

- [x] Viga 7: küljeriba vasakul. Kaardile liikudes, loeb ekraanilugjea mingit läbusisu.
