### ISSUE TITLE
WCAG erkaanilugejaga testimine - õppeasutused

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#409]
Õppeasutused nimekiri vaade
Viga 1: „Filtreeri“ nupp peaks peaks olema „button“, mitte „Link“.
 Viga 2: „Filtreeri“ nuppu vajutades peaks ütlema, et miski avanes või on lahti vms 
Viga 3: „Peale filtris“ valikute tegemist peaks järgmine valik olema „Otsi“ CTA, hetkel hüppab sealt üle nii TAB-iga, kui ka ekraanilugejaga – hetkel üks surnud kahtlane element vahel „void 0 link“ ja siis alles „Otsi“.  
Viga 4: „Lae veel“ nuppu vajutades peaks ütlema, et mitu uut sisu kuvati 

Õppeasutused detailvaade

Viga 1: avanev tabel – samad teemad, mis „erialade“ tabeli puhul
Viga 2: „Kontakt“ parem veerg sama teema, mis mujal ehk võiks öelda: „E-mail:…“ ja „Telephone number:…“
Viga 3: vaata palun kaardirakendust ekraanilugejaga ka.

**Comment by srautam** [comment]
Õppeasutused nimekiri vaade

- [x] Viga 1: „Filtreeri“ nupp peaks peaks olema „button“, mitte „Link“.
- [x] Viga 2: „Filtreeri“ nuppu vajutades peaks ütlema, et miski avanes või on lahti vms
- [x] Viga 3: „Peale filtris“ valikute tegemist peaks järgmine valik olema „Otsi“ CTA, hetkel hüppab sealt - [x] üle nii TAB-iga, kui ka ekraanilugejaga – hetkel üks surnud kahtlane element vahel „void 0 link“ ja siis alles „Otsi“.
- [x] Viga 4: „Lae veel“ nuppu vajutades peaks ütlema, et mitu uut sisu kuvati

Õppeasutused detailvaade

- [x] Viga 1: avanev tabel – samad teemad, mis „erialade“ tabeli puhul
- [x] Viga 2: „Kontakt“ parem veerg sama teema, mis mujal ehk võiks öelda: „E-mail:…“ ja „Telephone number:…“
- [x] Viga 3: vaata palun kaardirakendust ekraanilugejaga ka.

**Comment by TanelTromp** [comment]
Õppeasutused nimekiri vaade:

Viga 2: „Filtreeri“ nuppu vajutades peaks ütlema, et miski avanes või on lahti vms

Viga 1 uus: kui avada "filtreeri", siis peaksjärgmine TABi väli olema "Kooli nimi" >"Asukoht". Hetkel viskab "õppeastutuse tüübi" väljale

Viga 2 uus: kui avanenud filtri erinevatel väljadel liikuda, siis peale viimast s.o "õpilaskodu" peaks liikumga "Otsi" nupule. Hetkel on üks element "button expanded" vahel ja siis alles "otsi"

Viga 3: vaata palun kaardirakendust ekraanilugejaga ka. Ehk kui sellele liigud, siis mis juhtub.

**Comment by srautam** [comment]
- [x] Viga 2: „Filtreeri“ nuppu vajutades peaks ütlema, et miski avanes või on lahti vms

_Läbi räägitud_

- [x] Viga 1 uus: kui avada "filtreeri", siis peaksjärgmine TABi väli olema "Kooli nimi" >"Asukoht". Hetkel viskab "õppeastutuse tüübi" väljale

_Läbi räägitud_

- [x] Viga 2 uus: kui avanenud filtri erinevatel väljadel liikuda, siis peale viimast s.o "õpilaskodu" peaks liikumga "Otsi" nupule. Hetkel on üks element "button expanded" vahel ja siis alles "otsi"

_Läbi räägitud_

- [ ] Viga 3: vaata palun kaardirakendust ekraanilugejaga ka. Ehk kui sellele liigud, siis mis juhtub.
