### ISSUE TITLE
Avalehelt tehtud otsingu tulemuste kuvamine

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#410]
**Üldkirjeldus:**
Portaali kasutajale kuvatakse avalehelt sooritatud otsingu tulemusi uuel leheküljel.

**Eeltingimused ja käivitamine:**
Kasutajale on kuvatud avalehel otsingut. Kasutaja käivitab märksõna otsingu. Kasutajale kuvatakse otsingu tulemustega lehekülge.

Otsingu ulatus:
 - Artiklite otsing
 - Sündmuste otsing
 - Uudiste otsing
 - Koolide otsing
 - Õppekavade otsing

Vt BE töö  #41 ja täiendus #427 

**Vastuvõtutingimused:**
Süsteem kuvab veebilehitseja uues tab-s otsingu tulemusi:
Edukas otsing - https://zpl.io/blPArnX ja mobiil: https://zpl.io/VODnkmY
- [ ] Päises jätkuvalt otsingu "kast" , milles kuvatakse kasutaja sisestatud märksõna (või mitut)
- [ ] Tulemuste nimekirja kohal leitud sisuobjekti tüüpi (chip) (või mitut). Nimekirjas kuvamise järjestuse reeglid kirjeldatud BE piletis.
- [ ] Nimekirjas kuvatakse sisuobjekti tüüp ja pealkiri
- [ ] Tulemuste juurde laadimise võimalus (kui on üle x? arvu)

- [ ] Kasutaja saab eduka otsingu tulemusi filtreerida vajutades nimekirja kohal chip'le
- [ ] Chip'l topelt klikk tühistab filtreeringu

- [ ] Ebaedukas otsing - https://zpl.io/VODnBlQ

Viited:
BE #41 ja täiendus #427 
Disain: #269

**Comment by TanelTromp** [comment]
ja

**Comment by heldiraudsepp** [comment]
Arendus - 8 + test 6

**Comment by lsoonvald** [comment]
Tõlgitud.

**Comment by TanelTromp** [comment]
Viga 1: mobiil (ei tea kuidas klapib järgmise Viga 2-ga aga ma arvan, et mobiilivaates võiks ohverdada, et seal "auku" ei oleks):

![pilt](https://user-images.githubusercontent.com/37407917/45495084-33a34a80-b77b-11e8-9859-962827f48560.png)

Viga 2: nõue ei ole täidetud:

**Comment by madispold** [comment]
Viga 1: OK - viga 2 nõue täidetud ja sellega chipide olemasolu ning järjestus koguaeg muutub.
Viga 2: OK.
Viga 3: OK.
Viga 4: OK.
Täpsustus 1: BE päringu spetsiifika see, siin äkki teised oskavad täpsustada?

WCAG: 
Viga 1: OK - Tulles avalehelt teeb esimese otsingu tulemuse (listi 1. element) aktiivseks.
Viga 2: OK.
Viga 3: OK - staatus vastupidiseks muudetud.
Viga 4: OK.
Viga 5: Siin oli palju lihtsam määrata aktiivseks 1. uuele tulemusele eelnev element, sai nõnda tehtud - ehk esimene tabimine liigub uuele.

**Comment by madispold** [comment]
UUS: Lisatud "Kõik" filter.
Birgiti poolt sisend: "Paneme selle "Kõik" sinna otsingutulemustesse ikkagi ja kui kasutaja lehele tuleb, siis vaikimisi võiks olla see "Kõik" valitud"

Tegin nii, et "Kõik" on aktiivne ka iga olemasoleva filtri aktiivses olekus, kuna siis ju samuti kõik kuvatud - kas õige loogika?

**Comment by madispold** [comment]
@birgitpulk ka kontrollida?

Lisaks 1 punkt see, et praegu ei kuva filtreid, milles otsingu tulemuses pole väärtusi. Alternatiiv oleks ikkagi välja kuvada ja panna järele (0), mis indikeerib tulemuste puudumist. Kuigi sisuliselt see üleliigne - mingit loogikat ei paku ja vajutus ei teeks midagi.

**Comment by TanelTromp** [comment]
WCAG CHROME:

Viga 1: _OK - Tulles avalehelt teeb esimese otsingu tulemuse (listi 1. element) aktiivseks ehk
aktiveerib ka "tavakasutajale" nüüd selle esimese valiku sinise kastikesega, ei peaks+sisule kuhu satub, peaks olema filtreeri tulemusi chipid:

<img width="794" alt="capture" src="https://user-images.githubusercontent.com/37407917/45542066-6b60cf80-b819-11e8-9f1b-806e940307fe.PNG">

Viga 5: _kui vajutada "load more" CTA-d siis peaks järgmine tabulateerimise väli olema esimene uus väärtus mida kuvati (sellest oli mingi teise pileti raames @srautam juttu ja mai mäleta, mis sellest teemast sai)_

sama teema, mis eelmine

**Comment by madispold** [comment]
Viga 1: OK,
Viga 5: OK,
Viga 3: OK.

Viga 1 UUS: OK.

**Comment by birgitpulk** [comment]
Minu poolt ok!
