### ISSUE TITLE
Õppeasutuse ja õppekavade ja sündmuste vaadete täiendused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#412]
- [x]  Õppekava detailvaatest eemaldada akrediteerimise otsus ja akrediteerimise otsuse kehtivuse lõpp
- [x]  Õppekavade nimistutesse (erialade nimistu, sarnaste erialade nimistu, õppeasutuse erialade nimistu) panna tagasi õppe kestus ja õppe keel
- [x] Õppeasutuse erialade nimistust eemaldada õppeasutuse andmed (nimetus, jur aadress, tel, veebileht)
- [x] Õppeasutuse detailvaates mitte näidata andmeelemente HEV ja õpilaskodu kui väärtus puudub.

***

- [x] Sündmuste nimistu vaatest eemaldada korduva sündmuse märge.

**Comment by madispold** [comment]
@TanelTromp Testimisse

**Comment by TanelTromp** [comment]
Viga 1: viia element järgmisele reale teise poolega kokku st mitte poolitada nagu siin:

![pilt](https://user-images.githubusercontent.com/37407917/45287109-2b83aa80-b4f0-11e8-9621-6326317905e6.png)

**Comment by madispold** [comment]
VIGA 1: OK, 
VIGA 2: OK

**Comment by TanelTromp** [comment]
Viga 3: see oli kuskil teises piletis olemas juba vist aga HEV peaks välja kirjutama: Hariduslikud erivajadused
![pilt](https://user-images.githubusercontent.com/37407917/45344343-2e43d580-b5ac-11e8-9c94-9b78852dece8.png)

**Comment by madispold** [comment]
Viga 3: OK.
