### ISSUE TITLE
Regressioontestimine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#420]
Eesmärk: manuaalselt testides teha põhjalikum "suitsutest", et kontrollida kas peamised funktsioonid töötavad.

**Uudised:**
- [x] Kas uudist saab lisada? Sisestada sisuhalduses uudise minimaalne võimalik andmete komplekt (pealkiri, autor, avaldamise kuupäev (tänasest varasem), sissejuhatus, sisutekst). Mitte märkida avalikuks. Kontrollida, kas uudist pole portaalis uudiste nimekirjas näha. 
- [x]  Märkida uudis sisuhalduses avalikuks ja muuta avaldamise kuupäev tänasest hilisemaks. Kontrollida, kas uudist pole uudiste nimekirjas portaalis näha. 
- [x] Kas uudise avaldamine töötab? Muuta sisuhalduses uudise avaldamise kuupäev tänaseks ja jätta avalikuks. Kontrollida, kas uudis on portaalis uudiste nimekirjas näha ja kas detailvaade avaneb.
- [x] Kas uudise kõikide andmete sisestamine töötab? Sisestada sisuhalduses uudise kõikidele andmetele väärtused, sh 2 linki, 2 silti. _Jäta meelde meelde pealkiri, avaldamise kuupäevale ja sildid._
- [x] Kas uudise vaade avaneb? Avada portaalis uudise detailvaade ja vaadata üle, kas kõik andmed on kuvatud korrektselt (kas pole silmatorkavaid vigu) ja lingid klikitavad.

**Sündmused:**
- [x] Kas sündmust saab lisada? Sisestada sisuhalduses sündmuse minimaalne võimalik andmete komplekt (nimetus, liik, lühikirjeldus, kirjeldus, sissepääsu liik, 1 toimumisaeg (kpv, alguskell, lõpu kell). Mitte märkida avalikuks. 
- [x] Kas sündmuse avaldamine töötab? Kontrollida, kas sündmust pole portaalis näha nimekirjas ja kalendris. Märkida sündmus sisuhalduses avalikuks. _Jäta meelde nimetus ja kuupäev_. Kontrollida, kas sündmus on avalikus vaates nimekirjas ja kalendris õige kuupäeva kohal näha ning kas detailvaade avaneb nimekirjast ja kalendrist.
- [x] Kas sündmuse kõikide andmete sisestamine töötab? Sisestada sisuhalduses sündmuse kõikidele andmetele väärtused, sh 2 linki, 2 faili, 2 silti, 2 toimumisaega. _Jäta meelde meelde nimetusele ja kuupäevale lisaks liik ja sildid._
- [x] Kas filtreerimine töötab? Sisestada filtrisse nimetus, kuupäev, liik ja silt ning vaadata, kas sündmus on  nimistus ja kalendrivaates näha. Muuta järjest ühe kaupa filtrit sisestades-valides sinna midagi muud ja vaadata, et sündmus pole näha.
- [x] Kas sündmuse vaade avaneb? Avada portaalis sündmuse detailvaade ja vaadata üle, kas kõik andmed on kuvatud korrektselt (kas pole silmatorkavaid vigu), failid alla laaditavad ja lingid klikitavad.
- **Sündmusele registreerumine**
- [x] Sisestada sisuhalduses tänasest varasem sündmuse toimumise aeg. Kontrollida, kas portaalis detailvaatel on kiri, et sündmuse on möödunud.
- [x] Sisestada sisuhalduses tänasest hilisem sündmuse toimumise aeg, sissepääsu liik "registreerumisega" ja registreerumise alguse ja lõpu aeg tänasest varasema. Kontrollida, kas portaalis on kiri registreerumise lõpu kohta.
- [x] Sisestada sisuhalduses registreerumise alguse ja lõpu aeg ning sisestada osalejate maksimaalseks arvuks 2. Sisestada portaalis 2 osalejat. Pärast seda peab portaalis tulema kiri kohtad täis olemise kohta.
- [x] Määrata sisuhalduses ennast korraldajaks (sisestada korraldaja isikukoodiks enda isikukood). Portaalis vaadata, kas on näha osalejate nimekiri, kus on 2 eelnevalt sisestatud osalejat.

**Sisuleht:**
- [x] Kas sisulehte saab lisada? Sisestada sisuhalduses menüüpunkt ja sisulehe minimaalne võimalik andmete komplekt (pealkiri, sissejuhav tekst, sisu). Märkida avalikuks. 
- [x] Kas sisuleht minimaalse sisuga on korrektne? Vaadata portaalis sisulehte, kas on silmatorkavaid vigu.
- [x] Kas sisulehe kõik osad töötavad? Sisestada sisuhalduses sisulehe kogu võimalik andmekoosseis, sealhulgas 2 alamosa (akordionit), lisainfo, kontakt, link (2 tk), sarnased teemad (2 tk).
- [x] Kas sisuleht minimaalse sisuga on korrektne? Vaadata portaalis sisulehte, kas on silmatorkavaid vigu, sealhulgas kas akordionid on õiges järjekorras ja avanevad/sulguvad, kas lingid on klikitavad ja kas breadcrumb on olemas.

**Õppeasutused:**
- [x] Käivitada sisuhalduses õppeasutuste laadimine
- [x] Kas portaalis õppeasutuste kaart avaneb?
- [x] Kas portaalis õppeasutuste nimekiri avaneb?
- [ ] Kas filter töötab? Otsida nimetuse järgi (nt Tartu Ülikool) ja tüübi järgi (nt Gümnaasium)
- [x] Kas detailvaade avaneb kaardilt (infoakna kaudu) ja nimistust?
- [x] Kas detailvaates on õppeasutuse õppekavade nimistu (avada mõne kõrg- või kutsekooli detailvaade)?

**Õppekavad (erialad)**
- [x] Käivitada sisuhalduses õppekavade laadimine.
- [x] Kas portaalis õppeasutuste (erialade) nimekiri avaneb?
- [x] Kas filter töötab? Otsida nimetuse järgi (nt majandus) ja taseme järgi (nt Bakalaureuseõpe)
- [x] Kas detailvaade avaneb nimistust (kas seal on õppeasutuse andmed koos asukoha kaardiga)?
- [x] Kas detailvaates avaneb  sarnaste erialade nimistu (nt Eesti Merekool, 500-se ja suurema kogumahutavusega laeva vahitüürimees erialal)?
- [x] Kas võrdlus töötab? Lisada nimistust kuni 3 eriala võrdlusesse, avada võrdluse vaade, eemaldada eriala võrdlusest.

**Comment by TanelTromp** [comment]
**Uudised:**

Testlugu/uudis:
http://htm.twn.ee/et/uudised/haridus-ja-teadusminister-mailis-repsi-kooliaasta-alguse-tervitus

Viga 1: kuigi "avaldatud" linnukene on eemaldatud, avaldab ikkagi uudise ja tagasi muutmisele minnes, on "ajatamise seaded" kadunud ning linnukene "avaldatud" kasti tekkinud. Andmed:

![pilt](https://user-images.githubusercontent.com/37407917/45026095-eec63800-b045-11e8-834e-db551ddc6a09.png)

Viga 2: "Avaldatud" linnukese ja "ajatamise seaded" on omavahel konfliktis. a. kui ma muudan avaldamise tänasest hilisemaks, siis kaotab süsteem ise "avaldatud" linnukese ära . b. Kui ma muudan kuupäeva tänaseks ja eemaldan eraldi "avaldatud" linnukese, siis süsteem täidab automaatselt ise "avaldatud" linnukese ja avaldab uudise. Probleem on selles, et sisuhaldur võib soovida siiski otsustada, kas ta avaldab/kuvab uudist või mitte ükskõik, mis tingimustel ja seda teeb ta "avaldatud" linnukese märkimise kaudu, mis võiks olla ülim (vs "ajatamise seaded").

**Comment by madispold** [comment]
FE VEAD

Sisulehe (artikkel) BE/FE? vead
Viga 1: Sisestatud videote id oli kõigil kuidagi sama salvestunud, sisestades uued videod ja veendudes, et erinev ID väärtus, toimib - OK.
Viga 2: Teine video on yutube domeeniga, mida süsteem ei luba - OK.

Uudised. FE vead
Viga 1: OK.

Sündmused FE vead
Viga 1: osasid lisatud silte ei kuva hetkel frondis - Päringust annab vaid 2 silti, kuigi sisestatud 4, peab BE'ga klaarima. 
Viga 2: OK.
Viga 3: OK.
Viga 4: OK.
Viga 5: OK.
Viga/muudatus 1: OK

Sisulehe (artikkel) FE vead
Täpsustus 1: sellisel juhul breadcrumbs ei ole õige (üks sügavus puudu): Breadcrumbs tuleb BE'st, tuleb samuti BE'ga klaarida.

**Comment by madispold** [comment]
@lsoonvald 
FE vigadest tekkis 2 BE viga:

Viga 1: osasid lisatud silte ei kuva hetkel frondis - Päringust annab vaid 2 silti, kuigi sisestatud 4 - vea põhjuseks see, et päringus annab vaid aktiivses keeles sildid: Lahendus näiteks sisuhalduses siltide lisamise autocomplete piirata vaid aktiivses keeles siltidega.


Täpsustus 1: sellisel juhul breadcrumbs ei ole õige (üks sügavus puudu, üleval ka pilt): 

Näiteks asukoht: /et/artiklid/ohikooli-lopueksamite-praegune-kord-ei-taida-eesma, mis on alamkategoorias "Test alamkategooria".

Kuna need alamjaotused ei ole ise lingid vaid lihtsalt grupeerimise eesmärgil loodud, siis ei saa breadcrumbsi lingina neid lisada. Tanel arvas, et oleks mõistlik ikkagi lisada breadcrumbsi teksti kujul.

**Comment by TanelTromp** [comment]
- [x] Viga 1: välja "Pealkiri" ei kuvata kasutajaliideses pildi juures (peab kuvama pildile hiirega liikudes), selle asemel on kuvatud alt-tekst kaks korda.

- [x] Viga 1: kuvab videosid katkisena, kuigi on sisesatud korrektne link

- [x] Viga 2: sisestatud on kolm videolinki aga kuvab ainult kahte

- [x] Viga/muudatus 1: registreerumise modaalil peavad olema kuvatud kõik kuupäevad - ka lisakuupäevad, millal üritus toimub. Hetkel ainult põhikuupäev.

- [x] Viga 5: lisatud failil ei kuva "Kirleldus/pealkiri" sisestatud väärtust. Näitab ikka ainult failienda nime, mitte lisatud kirjeldust/nime. 

- [x] Viga 4: kontakti sektsioonis on kuvatud küll e-kirja aadress lingina aga see ei ole tegelikult ("mailto") link, sest ei ole klikitav ja ei ava kasutaja arvutis e-kirja klienti.

- [x] Viga 2: ei kuva "ürituse lisakuupäevasid". Kuvab ainult "põhikuupäeva".

- [x] Viga 3: ilmselt peab ka see olema outbound link (st avama uues brauseritabis) aga avab põhiakna asemel:

**Comment by lsoonvald** [comment]
Avaleht BE VEAD

Viga 1: Done.

**Comment by lsoonvald** [comment]
Sündmused BE vead

Viga 1: Kord peab olema kohustuslik väli, kord mitte. Muutsin uuesti mittekohustuslikuks.

Viga 2: Avaldatud nupp küljes nüüd.

Viga 3: Ei saa kohustuslikuks muuta seda ning ka pealkirjaks muuta.

**Comment by lsoonvald** [comment]
Viga 1: Nüüd soovitab siltide väljas keelepõhiseid tage.
