### ISSUE TITLE
Koormustestid ja live-keskkonna nõuded

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#422]
Koormustestid: #402 
Kirjeldada ka töö tulemus.
Live-keskkonna nõuded tuleb piletisse kirja panna. Lisada lühikesed selgitused.

**Comment by lsoonvald** [comment]
Koormus paranes kõige paremini kui kasutada Nginx Cache'i. Lahendus on selline, et Drupali containeri ees seisab Nginxi container, mis cacheb Drupali lehti. Kui Nginx leiab enda cachest lehe, kuhu poole pöördutakse, siis tuleb tulemus otse sealt, testitud 100 samaaegse kasutajaga ning päringu keskmine kiirus oli 10ms. Varasemaga võrreldes samal setupil tekkisid juba timeoutid.
