### ISSUE TITLE
EHISe avaandmete laadimise käivitamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#424]
BE-s võimalus käsitsi käivitada:
- õppeasutuste andmete import
- õppekavade andmete import

**Comment by lsoonvald** [comment]
![screenshot from 2018-09-14 12-01-06](https://user-images.githubusercontent.com/11455976/45546137-1460f780-b825-11e8-9064-279409e91ea5.png)
Minna aadressile http://test-htm.wiseman.ee:30000/en/admin/config/system/cron/jobs ning vajutada Import School Data rea peal RUN.
Töö kestab umbes 12 minutit, terve see aeg sama leht laeb. 

Kui töö on tehtud, siis minna lehele http://test-htm.wiseman.ee:30000/en/admin/config/system/queue-ui.
![screenshot from 2018-09-14 13-51-22](https://user-images.githubusercontent.com/11455976/45546194-47a38680-b825-11e8-90eb-55b14f0d4ffd.png)
Import task worker: school import queue reale tekib Number of items tulpa mingi arv, mis viitab imporditavate objektide hulgale. Linnutada see sama rida ning tabeli üleval select boxist valida Batch process. Peale seda vajutada Apply to selected Items.
![screenshot from 2018-09-14 13-53-12](https://user-images.githubusercontent.com/11455976/45546289-905b3f80-b825-11e8-9744-dc566cf14fa2.png)
Avaneb laadimise vaade, mille lõppedes on koolid sisse imporditud EHISest koos asukoha andmetega,
