### ISSUE TITLE
Otsing avalehelt üheks päringuks kokku

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#427]
Otsingu päringuteenus (#41) täiendada nii, et:
- erinevate sisuobjektide (artiklid, sündmused, uudised, koolid, õppekavad) otsing käib ühe päringuga;
- päringu vastuses on ka type (sisuobjekti tüüp) (jäävad ka nid, title, entitypath);
- päringu vastus on elemendid järjestatud score alusel (suurema sobivuse scorega eespool).

**Comment by andrussarv** [comment]
Otsingu päringuteenus (#41) täiendada nii, et:
- erinevate sisuobjektide (artiklid, sündmused, uudised, koolid, õppekavad) otsing käib ühe päringuga;
- päringu vastuses on ka type (sisuobjekti tüüp) (jäävad ka nid, title, entitypath).

**Comment by lsoonvald** [comment]
Uus päring: http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch:1&variables=%7B%22lang%22:%22ET%22,%20%22search_term%22:%22tallinn%22%7D

Üks probleem on ka, nimelt ei saa indekseerida sisutüübi nimetust sõltuvalt keelest, saab ainult selle machine name'i, mis on inglisekeelne.

**Comment by lsoonvald** [comment]
Fixitud sisutüübi nimetus.

**Comment by madispold** [comment]
Korras.
