### ISSUE TITLE
Töölaualt Lemmiku kustutamine ja 404 kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#429]
Täiendada Lemmikute kuvamist:
- [x] Kui salvestatud Lemmiku URL-i server ei leia siis kuvatakse 404 lehekülge.
- [ ] Süsteem kustutab 404 tulemuse andnud lemmiku töölaualt.

03.09: BE #332 lahendab

**Comment by heldiraudsepp** [comment]
Tuleviku arendus
