### ISSUE TITLE
Töölaual õpingute andmete kuvamine (isikukaart)

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#433]
**Üldkirjeldus:**
Kasutaja näeb enda õpingute andmeid EHIS-st. Selle töö raames realiseeritakse töölaual sakk "Õpin"

**Eeltingimused ja käivitamine:**
* Kasutaja on portaali sisse loginud. Portaalis on teada kasutaja isikukood.
* Portaal avab töölaua kasutajale pärast sisse logimist.
* EHIS-st õpingute andmete nägemiseks kasutaja valib töölaual "Õpin" .

**Tegevused**
- [ ] Õpinguandmete saamiseks tehakse päring back-end-i kaudu EHIS-st (vt #423). Kuvatakse EHIS-st saadud õppeasutuste nimistu (Iga kasutajaga seotud õppeasutus on akordionis, mis avab selles koolis õpingu detailvaate, üks silt detailvaates võib jaotuda omakorda mitmele reale).

Akordionis kuvatavad õpingute andmed on kirjeldatud allpool.
- [ ] Akordion on avatav-suletav.
- [ ] Akordionis esimese (või ainukese, kui kasutajal rohkem õpingute andmeid EHIS-s pole) õpingu andmed on vaikimisi avatud.

**Erijuhud ja täpsustused:**
-  [ ] Kui EHIS-st ei saadud ühtegi õpingute kirjet, siis kuvatakse teade "Eesti Hariduse Infosüsteemis õpingute andmed puuduvad".
-  [ ] Kui EHIS-st saadi mitu õpingu kannet, siis need **järjestatakse õppimise alguse kuupäeva järgi hilisemad kuupäevad eespool.** Seega kõige viimati alustatud õping on kõige esimene ja vaikimisi avatud.
-  [ ] Kui on error, siis kuvatakse veateade "Vabandame. Eesti Hariduse Infosüsteemist õpingute andmete lugemise käigus tekkis tehniline viga. Palun proovige hiljem uuesti."
-  [ ] Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuva (silti ka mitte).

****
Disaini link - õpinguandmed  töölaual - https://zpl.io/25rxA68. Disainis kuvatud sildid on illustratiivsed.

**** 
**Saki "Õpin" all õpingute nimistus kuvatavad andmed:**
* Õppeasutus - oppeasutus - see on akordionis pealkiri, kohustuslik, silti ei kuva
* Haridustase - haridustase
* Õppekava - oppekava (n arv) (Õppekava kood - oppekavaKood, Õppekava nimetus - oppekavaNimetus
* Õppekeel - oppekeel
* Õpe/ klass - opeKlass 
* Paralleeli tunnus - opeParallel
* Klassi liik - klassiLiik
* Kooliaste - klassAste
* Õppimise algus - oppAlgus
* Õppimise lõpp - oppLopp
* Staatus - staatus
* Tunnistuse/ Diplomi number - tunnistusDiplom
* Õppevorm - oppevorm (n arv) (Nimetus - nimetus, Alguskuupäev - algusKp, Lõppkuupäev - loppKp)
* Õppekoormus - koormus (n arv) (Nimetus - nimetus, Alguskuupäev - algusKp, Lõppkuupäev - loppKp)
* Õppekava järgne nominaalkestvus - kestus
* Rühma liik - ryhmaLiik
* Rühma nimetus - nimetus
* Osakoha suurus - koht
* Finantseerimise allikas - finAllikas (n arv) (Nimetus - nimetus, Alguskuupäev - algusKp, Lõppkuupäev - loppKp)
* Akadeemiline puhkus - akadPuhkus (n arv) (Nimetus - nimetus, Alguskuupäev - algusKp, Lõppkuupäev - loppKp)
* Ennistamine - ennistamine (n arv) (Nimetus - nimetus, Alguskuupäev - algusKp, Lõppkuupäev - loppKp)
* Põhjuseta puudumised eelmisel õppeveerandil (%) - puudumised
* Kutsealane eelkoolitus - kutseKoolitus (n arv) (Õppeasutus - oppeasutus, Õppima asumise kuupäev - algusKp, Õppekava kood ja nimetus - oppekava)

_Lisainfoks: Millised andmed välja kuvatakse sõltub haridustasemest._

**Comment by madispold** [comment]
@ruut12 
Uued tõlked: 
"frontpage": {
     "studies_data": "Õpingute andmed",
    "teachings_data": "Õpetamiste andmed",
    "oppeasutus": "Õppeasutus",
    "haridustase": "Haridustase",
    "oppekava": "Õppekava",
    "oppekeel": "Õppekeel",
    "opeklass": "Õpe/klass",
    "opeParallel": "Paralleeli tunnus",
    "klassiLiik": "Klassi liik",
    "klassAste": "Kooliaste",
    "oppAlgus": "Õppimise alguse",
    "oppLopp": "Õppimise lõpp",
    "staatus": "Staatus",
    "tunnistusDiplom": "Tunnistuse/Diplomi number",
    "oppevorm": "Õppevorm",
    "koormus": "Õppekoormus",
    "kestus": "Õppekava järgne nominaalkestus",
    "ryhmaLiik": "Rühma liik",
    "ryhmaNimetus": "Rühma nimetus",
    "koht": "Osakoha suurus",
    "finAllikas": "Finantseerimise allikas",
    "akadPuhkus": "Akadeemiline puhkus",
    "ennistamine": "Ennistamine",
    "puudumised": "Põhjuseta puudumised eelmisel õppeveerandil (%)",
    "kutseKoolitus": "Kutsealane eelkoolitus",
    "oppekavaKood": "Õppekava kood",
    "oppekavaNimetus": "Õppekava nimetus",
    "nimetus": "Nimetus",
    "algusKp": "Alguskuupäev",
    "loppKp": "Lõppkuupäev"
}
"errors": {
    "studies_data_request": "Vabandame. Eesti Hariduse Infosüsteemist õpingute andmete lugemise käigus tekkis tehniline viga. Palun proovige hiljem uuesti.",
    "studies_data_missing": "Eesti Hariduse Infosüsteemis õpingute andmed puuduvad."
}

**Comment by TanelTromp** [comment]
Viga 1: skrollbari on kasutajaliideses, kuigi midagi ei ole kerida:

![pilt](https://user-images.githubusercontent.com/37407917/45867908-285caa00-bd8d-11e8-8430-d73e07b9b40d.png)

Viga 2: EHIS-est võiks tulla kohe õige kuupäeva formaat @IndrekVallsalu : 
![pilt](https://user-images.githubusercontent.com/37407917/45867999-5fcb5680-bd8d-11e8-8313-9a7757de9060.png)
Vs vale
![pilt](https://user-images.githubusercontent.com/37407917/45868022-6954be80-bd8d-11e8-8164-060562f7c096.png)

**Comment by madispold** [comment]
@TanelTromp 
Viga 1: OK.
Viga 3: OK.
Viga 4: OK.
Muudatus 1: OK.

@birgitpulk @srautam 
1.  Isiku nimel, mille kaudu modaal avaneb, ei peaks olema joont all - OK, aga tekib küsimus, kas kasutaja üldse kuidagi aru saab, et see link on mille alt modaal avaneb? Joon all vähemalt natukene vihjaks sellele :)
2. Tehtud - kas piirjoon hall vaid avatud olekus?
3. OK.
4. OK.
5. OK.
6. Akordionit sulgedes jääb akordionile peale hover stiil - Mis tähendab? Kas peaks jääma? Kas siin all mõeldud vasakut oranži külge ja punast ikooni?
7. OK.
8. OK.

**Comment by madispold** [comment]
1. Joon tagasi pandud.
2. OK.
3. OK.

@birgitpulk

**Comment by birgitpulk** [comment]
- [ ] Akordion läheb sulgemisel korraks oranžiks, miks?
- [ ] Akordioni sulgemisel jääb fookus akordioni peale ja seega ka hover stiil akordionile peale. Kas võime nii teha, et fookus on alati see sinine kast, mitte hover stiil? 
- [ ] Valitud sakk > noolega peale minnes muutub nool käeks, aga ei peaks muutuma (justkui viitab et seda saab klikkida, aga tegelikult kasutaja on juba selle saki peal)

@madispold  @TanelTromp

**Comment by birgitpulk** [comment]
Minu poolt ok!
