### ISSUE TITLE
Töölaual pedagoogina ja õppejõuna töötamise andmete kuvamine (isikukaart) 

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#439]
**Üldkirjeldus:**
Kasutaja näeb enda pedagoogina ja õppejõuna töötamise andmeid EHIS-st. Selle töö raames realiseeritakse töölaual sakk "Õpetan".

**Eeltingimused ja käivitamine:**
* Kasutaja on portaali sisse loginud. Portaalis on teada kasutaja isikukood.
* Portaal avab töölaua kasutajale pärast sisse logimist.
* EHIS-st pedagoogina ja õppejõuna töötamise ja õpetamisega seotud kvalifikatsioonide ning täiendkoolituste andmete nägemiseks kasutaja valib töölaual "Õpetan" .

**Tegevused**
- [ ] Andmete saamiseks tehakse päring back-end-i kaudu EHIS-st (vt #446 ).
- [ ] Kuvatakse EHIS-st saadud andmed akordionis:
  * Pedagoogina ja õppejõuna töötamine - tootamine
  * Õppejõu kvalifikatsioon - kvalifikatsioon
  * Tasemehariduse kvalifikatsioon - tasemeharidus
  * Täiendkoolitused - taiendkoolitus
Kuvatakse nii mitu eelnevalt nimetatud akordioni rida, kui päring andmeid andis (tühja akordioni rida kasutajale ei kuvata).
- [ ] Akordionis saab kasutaja avada õppeasutuse. Kuvatakse õppeasutusega seotud andmed (detailvaade). Üks silt detailvaates võib jaotuda omakorda mitmele reale. 
Iga teema kohta kuvatavad andmed ja kuvamise järjekord on kirjeldatud allpool.

- [ ] Breadcrumbi kaudu saab uuesti avada töölaua "Õpetan" saki.

Kujundus: https://zpl.io/VxlrwDE ja https://zpl.io/aX4lZnl

- [ ] Akordion on avatav-suletav.
- [ ] Akordionis esimese (või ainukese, kui kasutajal rohkem õpetamise andmeid EHIS-s pole) õpetamise andmed on vaikimisi avatud.

**Erijuhud ja täpsustused:**
-  [ ] Kui EHIS-st ei saadud ühtegi kirjet, siis kuvatakse teade "Eesti Hariduse Infosüsteemis õpetamisega seotud andmed puuduvad".
-  [ ] Kui EHIS-st saadi mitu kannet, siis need **järjestatakse igas blokis nii, et hilisemad kuupäevad on eespool.**
  * Kõige viimati alustatud töötamine (algus kp alusel) on esimene.
  * Omandatud kvalifikatsioon (aasta või lõpetamise kp alusel) on esimene.
  * Viimati omandatud täiendkoolitus (lõpetamise kp alusel) on esimene.

-  [ ] Kui on error, siis kuvatakse veateade "Vabandame. Eesti Hariduse Infosüsteemist õpetamisega seotud andmete lugemise käigus tekkis tehniline viga. Palun proovige hiljem uuesti."
-  [ ] Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuvata (silti ka mitte).

All toodud andmed kuvada nii (vt ka disaini) :
- esimene rida on akordionis pealkiri, nt Pedagoogina ja õppejõuna töötamine
- õppeasutused moodustavad nimekirja (silti ei kuva)
- ning edasi on detailandmed. (N arv näitab andmebloki jaotumist mitmele reale, selle järel on kirjeldatud jaotuvad andmed.)

- [ ] **Pedagoogina ja õppejõuna töötamine - tootamine** - so akordionis pealkiri
* Õppeasutus - oppeasutus  - need moodustavad nimekirja
* Haridustase - liik - siit alates detailandmed
* Ametikoht - ametikoht
* Töötamise algus - ametikohtAlgus
* Töötamise lõpp - ametikohtLopp
* Koormus - ametikohtKoormus (double)
* Kvalifikatsiooninõuetele vastavus - ametikohtKvalVastavus
* Ametikoha täitmise viis - taitmiseViis
* Tööleping - tooleping
* Ametijärk - ametijark
* Õppekava - oppekava (n arv) (Õppekava kood - oppekavaKood, Õppekava nimetus - oppekavaNimetus)
* Õppeaine - oppeaine (n arv)  (Nimetus - oppeaine, Kooliaste - kooliaste, Koormus - maht, Kvalifikatsiooninõuetele vastavus - kvalVastavus)
* Haridustase - haridustase
* Lapsehoolduspuhkusel - lapsehooldusPuhkus (boolean)

- [ ] **Õppejõu kvalifikatsioon - kvalifikatsioon**
* Õppeasutus - oppeasutus 
* Dokument - dokument
* Kvalifikatsiooni/ akadeemilise kraadi nimetus - nimetus
* Vastavus kehtivas raamistikus - vastavus
* Aasta - aasta
* Riik - riik

- [ ] **Tasemehariduse kvalifikatsioon - tasemeharidus**
* Õppeasutus - oppeasutus 
* Kvalifikatsiooni dokument - kvalDokument
* Kvalifikatsioon kehtivas raamistikus - kvalVastavus
* Eriala/ õppekava - erialaOppekava
* Lõpetamise kuupäev - lopetanud
* Dokumendi nr - dokument

- [ ] **Täiendkoolitused - taiendkoolitus**
* Koolitusasutus - oppeasutus 
* Koolituse nimetus - nimetus
* Liik - liik
* Lõpetamise kuupäev - loppKp
* Maht (tundi) - maht

****
Disaini link - https://zpl.io/VxlrwDE.

**Comment by madispold** [comment]
Uued tõlked: 
@ruut12 
frontpage {
    "tootamine": "Pedagoogina ja õppejõuna töötamine",
    "kvalifikatsioon": "Õppejõu kvalifikatsioon",
    "tasemeharidus": "Tasemeharidus kvalifikatsioon",
    "taiendkoolitus": "Täiendkoolitus",
    "lead_title_xxs": "Hoia end<br> haridusinfoga kursis!",
    "lead_title_sm": "Hoia end haridusinfoga kursis!",
    "lead_title": "<b>Eduportaal -</b><br>hoia end haridusinfoga kursis!",
    "ametikoht": "Ametikoht",
    "ametikohtAlgus": "Töötamise algus",
    "ametikohtLopp": "Töötamise lõpp",
    "ametikohtKoormus": "Koormus",
    "ametikohtKvalVastavus": "Kvalifikatsiooninõuetele vastavus",
    "taitmiseViis": "Ametikoha täitmise viis",
    "tooleping": "Tööleping",
    "ametijark": "Ametijärk",
    "oppeaine": "Õppeaine",
    "lapsehooldusPuhkus": "lapsehoolduspuhkusel",
    "dokument": "Dokument",
    "kraadNimetus": "Kvalifikatsiooni/akadeemilise kraadi nimetus",
    "kvalifikatsioonVastavus": "Vastavus kehtivas raamistikus",
    "aasta": "Aasta",
    "riik": "Riik",
    "kvalDokument": "Kvalifikatsiooni dokument",
    "kvalVastavus": "Kvalifikatsioon kehtivas raamistikus",
    "erialaOppekava": "Eriala/õppekava",
    "lopetanud": "Lõpetamise kuupäev",
    "dokumentNr": "Dokumendi nr.",
    "koolitusNimetus": "Koolituse nimetus",
    "liik": "Liik",
    "maht": "Maht"
}

**Comment by madispold** [comment]
@TanelTromp Testimisse.

**Comment by TanelTromp** [comment]
TEST

Logimise andmed:

Kasutaja: õppejõud
Kasutaja 2: pedagoog
Parool: parool

Viga 1: skrollbarid, kuigi midagi skrollida ei ole

Viga 2: "vaata lähemalt" ei ole Zeplini järgi boldis, palun bold eemaldada:

<img width="453" alt="1" src="https://user-images.githubusercontent.com/37407917/45940421-c8127600-bfe1-11e8-9fc9-0a3ff8bc331b.PNG">

Viga/täpsustus 3: Zeplinis on tabeli jaotus ca 2/3 vasakule veerule ja 1/3 paremale veerule. Hetkel kasutajaliideses 1/2 ja 1/2. @birgitpulk palun kinnita või lükka uppi kumb on õige

<img width="827" alt="2" src="https://user-images.githubusercontent.com/37407917/45940476-0b6ce480-bfe2-11e8-920c-72123285ddc3.PNG">





----------------------------------------------------------------------------


    Pedagoogina ja õppejõuna töötamine - tootamine
    Õppejõu kvalifikatsioon - kvalifikatsioon
    Tasemehariduse kvalifikatsioon - tasemeharidus
    Täiendkoolitused - taiendkoolitus
    Kuvatakse nii mitu eelnevalt nimetatud akordioni rida, kui päring andmeid andis (tühja akordioni rida kasutajale ei kuvata).

**Comment by birgitpulk** [comment]
Minu poolest ok, kui kuvab veerud 1/2 + 1/2.

**Comment by birgitpulk** [comment]
Kas muus osas võin ka juba testida? @TanelTromp

**Comment by birgitpulk** [comment]
- [ ] Akordioni piirjoon peaks olema hall (edastatud juba Sandrile)
- [ ] Lemmikute blokis paremal peaks lingi kohal ja lingi all oleva paddingu suurus võrdne (hetkel üleval väiksem)
- [ ] Sakkide loogika vale: kui sakk ei ole valitud, siis peaks olema nii ikoon kui tekst sinised. Sakile hiirega minnes peaks tekst ja ikoon mõlemad muutuma tooni #0F7B8A (ilma halli taustata). 
- [ ] Sakk, millel parasjagu ollakse ehk mis on aktiivne, sellel ei peaks olema hoverit
- [ ] Akordionit sulgedes jääb akordionile peale hover stiil
- [ ] Vaata lähemalt peaks olema Regular fondi paksusega (Tanel juba tõi välja)
- [ ] Tahvelarvuti laiuses võiks sakkidel olla pealkirjad välja toodud sõnaga (ainult mobiilis ikoonid)
Lemmikute kastis olevatel linkidel peaks tulema hoveriga joon alla

**Comment by TanelTromp** [comment]
Viga 6 uus: kui sakkide vahel opereerida, siis kuvab lahti kolmanda akordioni, mitte esimest enam (peaks):
https://gyazo.com/49037fd4cbf95ed3641cf9645c16c9c5

**Comment by madispold** [comment]
Viga 6: OK. Lisaks kuvab lahti kõik akordionid, mis ennist lahti olid, mitte vaid ühe.
Viga 7: OK.
VIga 8: Kuna veateated tulevad juba vaate laadimisega, siis peaks sinna mingi hacki tegema, et neid n.ö alertina ette lugeda WCAG raames. Hetkel ei tee?
