### ISSUE TITLE
Töölaual isikuandmete kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#444]
**Üldkirjeldus:**
Kasutaja näeb enda isikuandmeid EHIS-st. Selle töö raames realiseeritakse töölaual isiku nimele klikates isikuandmete kuvamine.

**Eeltingimused ja käivitamine:**
* Kasutaja on portaali sisse loginud. Portaalis on teada kasutaja isikukood.
* Portaal avab töölaua kasutajale pärast sisse logimist.
* EHIS-st isikuandmete nägemiseks kasutaja klikib töölaual oma nimele.

**Tegevused**
- [ ] isikuandmete saamiseks tehakse päring back-end-i kaudu EHIS-st (vt #445 ). Kuvatakse EHIS-st saadud isikuandmed. 
- [ ] Kasutaja saab andmete vaatamise sulgeda.

**Erijuhud ja täpsustused:**
-  [ ] Kui EHIS-st ei saadud isikuandmete kirjet, siis kuvatakse teade "isikuandmed Eesti Hariduse Infosüsteemis puuduvad".
-  [ ] Kui on error, siis kuvatakse veateade "Vabandame. Eesti Hariduse Infosüsteemist isikuandmete lugemise käigus tekkis tehniline viga. Palun proovige hiljem uuesti."
-  [ ] Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuva (silti ka mitte).

****
Disaini link - isikuandmed töölaual - https://zpl.io/aRPlYZ0

**** 
**Isikuandmetes kuvatavad andmed:**
* Isikukood - isikukood
* Sünniaeg - synniKp
* Elukohamaa - elukohamaa
* Elukoht rahvastikuregistris - rrElukoht
* Kodakondsus - kodakondsus
* Elamisluba - elamisluba
* Õppelaenuõiguslikkus - oppelaenOigus - oigus, Põhjus - pohjus (n põhjust, mis jaotub eraldi ridadele)

**Comment by madispold** [comment]
Uued tõlked:
@ruut12 
"frontpage": {
    "dashboard_tabs_personal_label":"Isikuandmed",
    "isikukood": "Isikukood",
    "synniKp": "Sünniaeg",
    "elukohamaa": "Elukohamaa",
    "rrElukoht": "Elukoht rahvastikuregistris",
    "kodakondsus": "Kodakondsus",
    "elamisluba": "Elamisluba",
    "oppelaenOigus": "Õppelaenuõiguslikkus",
    "reason": "Põhjus"
}
"errors" {
    "personal_data_request": "Vabandame. Eesti Hariduse Infosüsteemist isikuandmete lugemise käigus tekkis tehniline viga. Palun proovige hiljem uuesti.",
    "personal_data_missing": "Isikuandmed Eesti Hariduse Infosüsteemis puuduvad."
}

**Comment by madispold** [comment]
@TanelTromp 

Tehtud, aga ootab BE tõlkeid.

**Comment by TanelTromp** [comment]
Test

Kasutaja: pedagoog
Parool: parool

Kasutaja2: õppejõud
Parool: parool

- [x] isikuandmete saamiseks tehakse päring back-end-i kaudu EHIS-st (vt #445 ). Kuvatakse EHIS-st saadud isikuandmed. 
- [x] Kasutaja saab andmete vaatamise sulgeda.

**Erijuhud ja täpsustused:**
-  [x] Kui EHIS-st ei saadud isikuandmete kirjet, siis kuvatakse teade "isikuandmed Eesti Hariduse Infosüsteemis puuduvad".
-  [ ] Kui on error, siis kuvatakse veateade "Vabandame. Eesti Hariduse Infosüsteemist isikuandmete lugemise käigus tekkis tehniline viga. Palun proovige hiljem uuesti."
-  [x] Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuva (silti ka mitte).

**Isikuandmetes kuvatavad andmed:**

-  [x] Isikukood - isikukood
-  [x] Sünniaeg - synniKp
-  [x] Elukohamaa - elukohamaa
-  [x] Elukoht rahvastikuregistris - rrElukoht
-  [x] Kodakondsus - kodakondsus
-  [x] Elamisluba - elamisluba
-  [x] Õppelaenuõiguslikkus - oppelaenOigus - oigus, Põhjus - pohjus (n põhjust, mis jaotub eraldi ridadele)

**Comment by birgitpulk** [comment]
Minu poolt ok

**Comment by madispold** [comment]
@TanelTromp Täiendatud seda, et kui EHISest tuleb mis iganes veateade, siis kuvatakse: "Vabandame. Eesti Hariduse Infosüsteemist isikuandmete lugemise käigus tekkis tehniline viga. Palun proovige hiljem uuesti.". Kui päringul vastus, aga see tühi - vaid siis kuvab teate "isikuandmed Eesti Hariduse Infosüsteemis puuduvad".
