### ISSUE TITLE
Sisuhalduses saab toimetada "OSKA vahe-avalehte"

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#448]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada „OSKAFrontPage“ mallil sisulehte.

**Eeltingimused ja käivitamine:**
- Kasutajal on OSKA sisuhalduri õigused (https://github.com/hariduspilv/haridusportaal/wiki/Kasutus%C3%B5igused) .
- Kasutaja on OSKA sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- toimetada lehe sisu (vt sisulehe elemendid)
- avaldada sisulehte

**Sisulehe elemendid:**
1. saab lisada/ muuta sisulehe pealkirja, kohustuslik, maksimaalne pikkus 150
2. saab lisada/ muuta kokku 6 linki sisulehtedele, kohustuslikud 

Linkide asukohad ja sisestamise reeglid on järgmised:

1. Pealkirja järel: saab lisada/ muuta lingid sisulehtedele, kohustuslik 3tk:
   - sisulehe lingi pealkiri (LinkTitle), kohustuslik, maksimaalne pikkus 50
   - sisulehe URL link, kohustuslik (front-endis siselingi avamise loogika) (Material ei luba sisuhalduses kõigile kohustuslikkust märkida).
***
Testimise andmed, mis lisatakse toodangukeskkonda: disain: https://zpl.io/am5G6xm
- pealkiri: "OSKA aitab Sul teha õigeid karjäärivalikuid ja õppida õigeid erialasid"
- pealkirja all ingid:
  - "Valdkonnad" - viib valdkonna nimekirjale,
  - "Ametialad" - viib ametialade nimekirjale
  - "Tööjõuprognoos" - viib mõnele sellel sisutüübil loodud lisatud sisulehele.
***
2. Lehe keskel kahes veerus saab tuua esile kahte (2) sisulehte ja mõlema kohta lisada:
- sisulehe URL link, kohustuslik (front-endis siselingi avamise loogika, päringusse läheb valitud sisulehtede pealkiri ja sissejuhatav tekst).

_kasutajaliideses kuvatakse lingitud sisulehelt sisulehe pealkiri ja sissejuhatav tekst kuni neljal real, nupp Vaata lähemalt - avab lisatud sisulehe._

3. Teemaplokk "Päevakajaline" saab tuua esile ühe sisulehe
- sisulehe URL link, kohustuslik (front-endis siselingi avamise loogika, päringusse läheb valitud sisulehe pealkiri ja foto).

_kasutajaliideses kuvatakse lingitud sisulehe-tüübi nimetus (nt Tööjõuprognoos), sisulehe pealkiri ja sisulehele lisatud foto._

Viited:
FE: #449 
disain: https://zpl.io/am5G6xm

**Comment by heldiraudsepp** [comment]
BE - 8
Test - 8

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, hetkel saab lisada ainult kolm sisulehte (kohustuslikud) aga peaks saama kuni 6, millest kolm on kohustuslikud: _saab lisada/ muuta kokku 6 linki sisulehtedele, kohustuslikud_

**Comment by lsoonvald** [comment]
Viga 2: Ei saa minimaalset kohustuslikku arvu määrata.
Viga 3: Korras.

**Comment by TanelTromp** [comment]
Viga 4: "keskmised sisu viited" ja "Päevakajaline" alt ei leia autocompletega samu asju, mis "Sisulehtede lingid" alt - väljad ei ole sama võimekusega. Kui sisud võivad kattuda, siis peaks üle chekkima. Nt ei leia vanemaid uudiseid/sündmuseid:
http://htm.twn.ee/uudised/kalamees-j%C3%A4ttis-%C3%B5nge-koju
http://htm.twn.ee/uudised/haridus-ja-teadusminister-mailis-repsi-kooliaasta-alguse-tervitus
jne

NB! Kui autocomplete stabiilselt ei tööta, siis kaaluda kopi/peist võimalusega asendamist või võimaldada kopi/peist samaaegset funktsionaalsust autocompletega. @EgleM-TW  
Hetkel:
![image](https://user-images.githubusercontent.com/37407917/55632193-77ff4200-57c2-11e9-8065-95c5a3937224.png)

**Comment by lsoonvald** [comment]
Viga 4: Autocomplete'i on pandud ainult OSKA sisulehed, teisi ma ei lisanud. Kui vaja teisi lisada, siis peaks vaatama, kas teistel sisutüüpidel on ka vajalikud väljad olemas, mida välja soovitakse kuvada frondis.

**Comment by TanelTromp** [comment]
TEST  OK



Sisulehe elemendid:

- [x]   saab lisada/ muuta sisulehe pealkirja, kohustuslik, maksimaalne pikkus 150
- [ ]   saab lisada/ muuta kokku 6 linki sisulehtedele, kohustuslikud

**Comment by EgleM-TW** [comment]
OK! vastab nõuetele.
