### ISSUE TITLE
"OSKA vahe-avalehe" kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#449]
**Eesmärk ja üldtingimused**
Portaali külastaja on menüüst või lingi kaudu avanud OSKA avalehe (portaali-sisene teemaploki vaheavaleht). OSKA avaleht lühidalt tutvustab mis on OSKA ja koondab viited teemaga seotud sisulehtedele.
OSKA sisuhaldur lisab sisuhaldusest avalehele pealkirja ja lingid.

**Eeltingimused ja käivitamine**
- realiseeritud on pilet #448  (sisu toimetamine)
- kasutaja navigeerib menüüst „OSKA_FrontPage“ mallil sisulehele.

**Vastuvõtutingimused**
Kasutajale kuvatakse lehekülje sisu vastavalt sisuhladuri sisestatud andmetele järgnevalt:
Vaata disaini: https://zpl.io/am5G6xm; **logod küsida ja nõuded selgitab Birgit**

- sisuhele pealkiri joondub keskele
- esimesed 3 linki kuvatakse pealkirja all - vt ka täpsustusi Zeplinis
- teemaplokis "Viimased valdkonnauuringud" kuvatakse viimati sisestatud (mitte muudetud) valdkonna sisulehed, mille kohta kuvatakse:
   - foto (sarnaselt valdkonna nimistule) ja valdkonna pealkiri. Nii fotol kui ka pealkirjal klikkimine viib valdkonna detailvaatesse.
   - link Vaata kõiki valdkondi avab valdkondade nimistu.
- sisuhaldusest sisestatud neljas ja viies link kuvatakse lehe keskel:
   - pealkiri, mis sisestati sisuhaldusest
   - lingitud sisulehelt sissejuhatav tekst kuni neljal real
   - nupp Vaata lähemalt viib sisulehele
- viimane link kuvatakse omaette teemaplokis:
   - kuvatase sisutüübi nimetus (nt Tööjõuprognoos)
   - pealkiri, mis sisestati sisuhaldusest
   - foto lingitud sisulehelt
- lehe jaluses logod ja lingid (logod ja täpsustused küsida Birgitilt)
- tekst:

Tuleviku tööjõu- ja oskuste vajaduse prognoosisüsteem OSKA koostab aastaks 2020 kõigil elualadel Eestis tuleviku tööjõu ja oskuste prognoosid ning võrdleb neid pakutava koolitusega kutse- ja kõrghariduses ning täiendõppes.

**OSKA uuringuid koostab Kutsekoda Euroopa Sotsiaalfondi vahenditest.**

***
Viited:
BE #448 
disain: https://zpl.io/am5G6xm

**Comment by heldiraudsepp** [comment]
FE - 40h
Test - 8h

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1: kui luua uus "OSKA vahe-avaleht" sisuhaldusest siis paneb kahe peale mingi sigrimigri kokku - võiks olla sama loogika, mis tavapärase avalehe puhul, kus mäletamist mööda kehtis viimasena sisestatud avaleht ja selle andmed

**Comment by madispold** [comment]
Viga 1: @lsoonvald 
Viga 2: Pealkirja väli lisada ka päringusse @lsoonvald
Viga 3: OK.
Täiendus 0: OK.
Viga 4: OK.
Viga 5: OK.
Ux-täiendus 1: OK.
Ux-täiendus 2: Jääb nii nagu on - OK.

**Esimesed kolm linki võiksid olla tahvlis kõrvuti, mobiilis üksteise all. Tahvlis nupud liiga laiad, need võiksid jääda samaks nagu desktopis. Mobiilis võiks nupud olla täislaiuses. Jaluses võiksid logod samuti olla üksteise kõrval.** - Kuna pikema lingi pealkirja korral võib venida päris laiaks vaade pakun välja kompromissi, et kuni 720px vaadetes on 3 kõrvuti ja allapoole seda on üksteise all - selline lahendus ka tehtud.

Viga 1 WCAG: OK.
Viga 2 WCAG: OK.
Viga 3 WCAG: OK.

**Comment by lsoonvald** [comment]
Viga 1: Palun näidet. Sigrimigri ei ütle väga midagi. Hetkel üks vaheavaleht loodud.
Viga 2: Korras.

**Comment by EgleM-TW** [comment]
@lsoonvald  - palun muuda pealkirja väli rich text format väljaks.

**Comment by TanelTromp** [comment]
UX-täiendus 3: ei indikeeri linki, kuigi pilt on link (nagu mujal):

https://gyazo.com/d0c90cc2fd72f735bf876ae9bd0507fd

**Comment by madispold** [comment]
Viga 2: Jääb tõlkena ehk pole muudetav sisutüübi enda alt
UX-täiendus 3: OK.

**Comment by birgitpulk** [comment]
**Desktop:**
- [ ] ESF logo peaks joonduma Uuringute parempoolse fotoga paremast küljest
- [ ] OSKA jutt ja lingid alguses võiksid olla natukene allpool (hetkel tundub et nad jäävad visuaalselt natukene liiga lehekülje ülaserva)
- [ ] Kutsekoja ja OSKA logode ning neile järgneva teksti vahe võiks olla natukene suurem

**Tahvel:** 
- [ ] CTA nupud võiksid jääda sama laiaks nagu nad desktopis on, mitte täislaiusesse minna (täislaiuses ainult mobiilis)
- [ ] Peale Kutsekoja juttu on väga palju valget ruumi, seda võiks vähemaks võtta. 
- [ ] Kutsekoja tekstikast võiks olla sama lai nagu eespool olevad tekstid (hetkel laiem)

**Mobiil:**
- [ ] Lehe alguses olevad täpid võiksid tahvlis ja mobiilis olla värvilised (kuna nad ei ole hoverdatavad). Tekstile jääb joon alla. 
- [ ] Viimased valdkonnauuringud pealkirja reavahe võiks olla 20px
- [ ] Vaata kõiki link võiks joonduda Viimased valdkonnauuringud pealkirja alumise reaga
- [ ] Lehekülje lõpus liiga palju valget ruumi

**Comment by madispold** [comment]
Is okeeey!

**Comment by TanelTromp** [comment]
Viga 1: _Palun näidet. Sigrimigri ei ütle väga midagi. Hetkel üks vaheavaleht loodud._

Vahelehed, viimane neist jrk nriga "2":
http://htm.wiseman.ee:30000/admin/content?title=vahe-avaleht&type=All&status=All&langcode=All

Hetke katkine seis:
http://htm.twn.ee/oska

a.Loodud kaks OSKA vahe-avalehte. Katki nt jalus, kust puudu  "Kutsekoda" ja "OSKA" logod aga on osa teksti. 

b. Ei kuva üldse neid linke, kuigi on sisestatud:
![pilt](https://user-images.githubusercontent.com/37407917/55970421-30782a80-5c88-11e9-9c99-307abd5b06df.png)

**Comment by lsoonvald** [comment]
Viga 1: Bottom fieldi andmed tulevad, aga välja ei kuvata. @madispold

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

- [ ] kasutaja navigeerib menüüst „OSKA_FrontPage“ mallil sisulehele


- [ ] Vastuvõtutingimused

    sisuhele pealkiri joondub keskele
    esimesed 3 linki kuvatakse pealkirja all - vt ka täpsustusi Zeplinis
    teemaplokis "Viimased valdkonnauuringud" kuvatakse viimati sisestatud (mitte muudetud) valdkonna sisulehed, mille kohta kuvatakse:
        foto (sarnaselt valdkonna nimistule) ja valdkonna pealkiri. Nii fotol kui ka pealkirjal klikkimine viib valdkonna detailvaatesse.
        link Vaata kõiki valdkondi avab valdkondade nimistu.
    sisuhaldusest sisestatud neljas ja viies link kuvatakse lehe keskel:
        pealkiri, mis sisestati sisuhaldusest
        lingitud sisulehelt sissejuhatav tekst kuni neljal real
        nupp Vaata lähemalt viib sisulehele
    viimane link kuvatakse omaette teemaplokis:
        kuvatase sisutüübi nimetus (nt Tööjõuprognoos)
        pealkiri, mis sisestati sisuhaldusest
        foto lingitud sisulehelt
    lehe jaluses logod ja lingid (logod ja täpsustused küsida Birgitilt)
    tekst:

Tuleviku tööjõu- ja oskuste vajaduse prognoosisüsteem OSKA koostab aastaks 2020 kõigil elualadel Eestis tuleviku tööjõu ja oskuste prognoosid ning võrdleb neid pakutava koolitusega kutse- ja kõrghariduses ning täiendõppes.

OSKA uuringuid koostab Kutsekoda Euroopa Sotsiaalfondi vahenditest.

-------------------------

![pilt](https://user-images.githubusercontent.com/37407917/56024720-48e45580-5d19-11e9-9840-9f3da2058f4e.png)

**Comment by birgitpulk** [comment]
Kujundus ok
