### ISSUE TITLE
OSKA valdkonna detailvaate kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#451]
**Eesmärk, üldtingimused:**
Portaali külastaja saab menüü või mõne muu sisulehe lingi kaudu navigeerida OSKA valdkonna „FieldPage“  mallil sisulehele ja tutvuda selle sisuga.

**Eeltingimused ja käivitamine:**
- realiseeritud on pilet #450  (sisu toimetamine)
- kasutaja navigeerib menüüst „FieldPage“ mallil sisulehele

**Vastuvõtutingimused:**
- [ ] Kasutajale kuvatakse lehekülje sisu - disain: https://zpl.io/2ZzOYOd ja mobiilis: sarnaselt põhikutseala vaatele - https://zpl.io/V41Wg1M.
- [ ] Kui sisulehele on lisatud akordion siis kasutaja saab avada-sulgeda sisulehe alamlehti (accordion) 
- [See nõue jääb S15 ja sellest piletist välja] Kasutaja saab sisulehekülge jagada sotsiaalmeedias. Nupp, mille alt avanevad valikud FB ja Twitter - vt realiseeritud varem #36 .

Infograafika kuvamine ei ole skoobis, lisame teise piletiga: #498 

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by lsoonvald** [comment]
http://test-htm.wiseman.ee:30000/graphql?queryId=oskaFieldDetailView:1&variables={%22path%22:%22/et/node/48872%22}

**Comment by lsoonvald** [comment]
Uuendatud fieldide nimesid, päring sama.

**Comment by skeefee** [comment]
@TanelTromp Palun testida

**Comment by skeefee** [comment]
http://htm.twn.ee/et/valdkonnad/oska-valdkonna-test

**Comment by TanelTromp** [comment]
Viga 1: mobiilivaatest pildi kirjelduse joondus paigast ära:

![screenshot_20181010-160422](https://user-images.githubusercontent.com/37407917/46738336-9a4a5400-cca6-11e8-9a01-eeeed4fecbb7.png)

Viga 2: autoskroll akordioni avamisel puudu ehk peaks skrollima levelile, et avatud akordion tervenisti näha.

Viga 3: akordinid on kõik sinised, hetkel oranžkass (zeplinis ka)

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Nice to have. Selle võime tulevikus teha kui soovi on
Viga 3: Korras
Viga 4: @Isoonvald
Viga 5: Ma arvan, et ei ole mõtet elementide asukohti loksutada
Viga 6: Korras
Viga 7: Korras
Viga 8: Korras
Viga 9: Seda me muuta ei saa kuna see tuleb youtube.com-st
Viga 10: Korras

**Comment by TanelTromp** [comment]
Viga 11: Viga 2: "alt tekst" ja "pealkiri pildile" väljad vahetuses

**Comment by skeefee** [comment]
Viga 11: See läheb teise ticketi alla

**Comment by birgitpulk** [comment]
- [ ] Sissejuhatav tekst peaks olema Medium
- [ ] Sissejuhatuse ja sisuteksti reavahe paigast ära (vt nt uudises korras)
- [ ] Akordionid peavad mobiilis olema täislaiuses
