### ISSUE TITLE
OSKA ametiala (põhikutseala) detailvaate kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#453]
**NB! põhikutseala = ametiala**

**Eesmärk, üldtingimused:**
Portaali külastaja saab menüü või mõne muu sisulehe lingi kaudu navigeerida „MainProfessionPage“ mallil sisulehele ja tutvuda selle sisuga.

**Eeltingimused ja käivitamine:**
- realiseeritud on pilet #452 (sisu toimetamine)
- kasutaja navigeerib menüüst „MainProfessionPage“ mallil sisulehele

**Vastuvõtutingimused:**
- [ ] Kasutajale kuvatakse lehekülje sisu - disain: https://zpl.io/V41Wg1M ja mobiilis: https://zpl.io/V41Wg1M
- [ ] Kui sisulehele on lisatud akordion siis kasutaja saab avada-sulgeda sisulehe alamlehti (accordion) 
- [See nõue jääb S15 ja sellest piletist välja] Kasutaja saab sisulehekülge jagada sotsiaalmeedias. Nupp, mille alt avanevad valikud FB ja Twitter - vt realiseeritud varem #36 .
- [ ] Kasutaja saab põhikutseala lisada võrdlusesse - kuvada checkbox (lisamist-eemaldamist testida piletis #478 ).

Infograafika kuvamine ei ole skoobis, lisame teise piletiga: #498 

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by lsoonvald** [comment]
http://test-htm.wiseman.ee:30000/graphql?queryId=oskaMainProfessionDetailView:1&variables={%22path%22:%22/et/node/48871%22}

**Comment by lsoonvald** [comment]
Uuendatud päringut, väljadel uued nimed.

**Comment by TanelTromp** [comment]
Viga 1: ei kuva silte
http://htm.twn.ee/et/pohikutsealad/teabe-ja-dokumendihalduse-spetsialistid
vs
http://test-htm.wiseman.ee:30000/et/pohikutsealad/teabe-ja-dokumendihalduse-spetsialistid

Viga 2: "alt tekst" ja "pealkiri pildile" väljad vahetuses

**Comment by birgitpulk** [comment]
Vead üle kontrollitud ja tõstan done'i
