### ISSUE TITLE
OSKA andmete import CSV-st

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#454]
1. Sisuhaldaja avab faili.
Fail on CSV fail, kus:
- veergude eraldaja on semikoolon ( ; ), 
- failis on päiserida (naitaja;valdkond;alavaldkond;pohikutsela;aasta;silt;vaartus)

2. Faili kontroll:
Faili iga rida kontrollida järgmiselt
- kas esimeses veerus on naitaja: kui rida on täidetud mistahes muu väärtusega siis naitaja veerg on kohustuslik täita;
- kas teises veerus on valdkond: kas on olemas taksonoomia OSKA_Field, mille väärtus võrdub failist saadava väärtusega); ei ole kohustuslik
- kas kolmandas veerus on alavaldkond: kas on olemas taksonoomia OSKA_Sub_Field, mille väärtus võrdub failist saadava väärtusega; ei ole kohustuslik
- kas neljandas veerus on põhikutseala: kas on olemas taksonoomia  OSKA_mainProfession, mille väärtus võrdub failist saadava väärtusega; ei ole kohustuslik
- kas viiendas veerus on aasta: kui on väärtus, siis, kas kas on string; ei ole kohustuslik)
- kas kuuendas veerus on silt: kui on väärtus, siis kas on string; ei ole kohustuslik)
- kas seitsmendas veerus on väärtus: kui on väärtus, siis kas on number; ei ole kohustuslik, nt ei tohi olla %)

3. Kui ilmneb viga, siis protsess katkestada ja kuvada faili rea number ja veateade ("Puudub naitaja", "Vale OSKA_Field", "Vale OSKA_Sub_Field", "Vale OSKA_mainProfession", Vales formaadis aasta", "Vales formaadis silt", "Vales formaadis väärtus").

4. Salvestada failist loetavad OSKA andmed. Faili iga rida salvestada:
- Naitaja (indicator) = esimese veeru väärtus
- Valdkond (OSKA_Field) = teise veeru väärtus
- Alavaldkond (OSKA_Sub_Field) = kolmanda veeru väärtus
- Põhikutseala (OSKA_mainProfession)  = neljanda veeru väärtus
- Aasta (year) = viienda veeru väärtus
- Silt (label) = kuuenda veeru väärtus
- Väärtus (value) = seitsmenda veeru väärtus

**Comment by lsoonvald** [comment]
Saab importida siin lehel: http://test-htm.wiseman.ee:30000/et/admin/structure/oska_entity

Github csv faili uploadida ei luba, muuda extension csv peale pärast.
[oska andmed3.txt](https://github.com/hariduspilv/haridusportaal/files/2423045/oska.andmed3.txt)

**Comment by TanelTromp** [comment]
Viga 1: ei näita nime, eeldan, et järgmine punkt tähendab seda:

 Salvestada failist loetavad OSKA andmed. Faili iga rida salvestada:

    Naitaja (indicator) = esimese veeru väärtus
    Valdkond (OSKA_Field) = teise veeru väärtus
    Alavaldkond (OSKA_Sub_Field) = kolmanda veeru väärtus
    Põhikutseala (OSKA_mainProfession) = neljanda veeru väärtus
    Aasta (year) = viienda veeru väärtus
    Silt (label) = kuuenda veeru väärtus
    Väärtus (value) = seitsmenda veeru väärtus

<img width="762" alt="1" src="https://user-images.githubusercontent.com/37407917/46138694-33b04980-c255-11e8-989b-8bf2a7e84ab4.PNG">

**Comment by lsoonvald** [comment]
Viga 1: Parandatud.

**Comment by TanelTromp** [comment]
Muudatus 1: CSV failiandmetel peab olema ka pealkirja lahter, et ei kuvaks imporditud andmete puhul tühja nime välja:

<img width="762" alt="1" src="https://user-images.githubusercontent.com/37407917/46141267-19c63500-c25c-11e8-8627-156a407b3742.PNG">

**Comment by TanelTromp** [comment]
Viga 2: väli puudu/tühi "Oska main profession"

**Comment by EgleM-TW** [comment]
11.11.2018 edukalt imporditud tabel: https://github.com/hariduspilv/haridusportaal/blob/master/docs/testandmed-graafika-1.csv
