### ISSUE TITLE
Tühistamise puhul ei saada süsteem eraldi e-kirja

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#455]
Seda (topelt)kirja ei tohi süsteem väljastada enam:

![pilt.png](https://images.zenhubusercontent.com/5ab8a6294b5806bc2bcc56d1/c1b8559c-ee79-4f3d-b0ff-1d9b0ccc6c8a)

**Comment by lsoonvald** [comment]
Peaks olema korras nüüd. @TanelTromp
