### ISSUE TITLE
OSKA infograafika lahenduse valik

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#456]
Uurida Drupal Charts mooduli võimalusi OSKA infograafika toimetamisel ja kuvamisel. Ja võrrelda seda Google Charts lahendusega. Töö tulemusel on meil valik tehtud. Kliendiga arutelul osalemine kah N 20.09 vahemikus 12-13.

**Comment by heldiraudsepp** [comment]
Easychart on litsentsiga moodul ja ei kasuta
