### ISSUE TITLE
OSKA infograafika lisamine sisuhaldusest

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#468]
Sisuhaldusest peab saama lisada infograafikat. 
Sisutüübid: MainProfessionPage #452 , FieldPage #450 , SurveyPage #474 

Sisuhaldur saab:
-  [ ] valida graafikatüübi 
-  [ ] valida diagrammi nime (naitaja) (1)
-  [ ] valida valdkonna (0.. n)
-  [ ] valida alamvaldkonna (0.. n)
-  [ ] valida põhikutseala (0.. n)
-  [ ] valida peroodi (0.. n)

Graafiku kuvamiseks teeb drupal back-end päringu CSV-st laetud andmetest:
-  [ ] Filtreerib CSV-st laetud andmetest lähtudes kasutaja valikutest (naitaja, valdkond, alamvaldkond, pohikutseala, periood)
-  [ ] Grupeerib sildi (label) alusel ja summeerib väärtused (value).

Graafikatüübid: line, bar, column, pie, doughnut, scatter
gauge - tulevikus eraldi tööna (10.10)

Seotud tööd:
Andmete import ja kontroll CSV-st #37 
Sisutüübid, kus kasutame: #452  ja #450 ja #474

**Comment by lsoonvald** [comment]
Sai loodud field, mida saab sisutüüpidele külge panna. Testida siis, kui on olemas sisutüübid, millele külge panna seda välja.

**Comment by heldiraudsepp** [comment]
Ainult testimine

**Comment by TanelTromp** [comment]
Täpsustus 1: puuduvad perioodi valikus aastad, mis on suuremad kui 2010. Millest see tuleneb.


-------------------------------------------------------------------------------------------------

Sisuhaldur saab:
-  [ ] valida graafikatüübi 
-  [ ] valida diagrammi nime (naitaja) (1)
-  [ ] valida valdkonna (0.. n)
-  [ ] valida alamvaldkonna (0.. n)
-  [ ] valida põhikutseala (0.. n)
-  [ ] valida peroodi (0.. n)

Graafiku kuvamiseks teeb drupal back-end päringu CSV-st laetud andmetest:
-  [ ] Filtreerib CSV-st laetud andmetest lähtudes kasutaja valikutest (naitaja, valdkond, alamvaldkond, pohikutseala, periood)
-  [ ] Grupeerib sildi (label) alusel ja summeerib väärtused (value).

Graafikatüübid: line, bar, column, pie, doughnut, scatter

**Comment by lsoonvald** [comment]
Viga 0: Fixed, kui filtritega ei leitud vasteid, siis läks chart katki, see korras nüüd.
Viga 1: Perioodi valikus olevad aastad sõltuvad sisse imporditud andmetest, hetkel on imporditud sisse sellised andmed (aastad 2001-2010 on esindatud):
naitaja;valdkond;alavaldkond;pohikutseala;aasta;silt;vaartus
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2001;silt1;200
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2002;silt1;200
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2003;silt1;150
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2004;silt1;70
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2005;silt1;80
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2006;silt1;90
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2007;silt1;120
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2008;silt1;300
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2009;silt1;200
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2010;silt1;100
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2001;silt2;150
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2002;silt2;140
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2003;silt2;200
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2004;silt2;120
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2005;silt2;140
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2006;silt2;130
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2007;silt2;110
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2008;silt2;200
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2009;silt2;100
näitaja1;Ehitus;Ehituse alavaldkond;Põhikutseala1;2010;silt2;70
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2001;silt1;150
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2002;silt1;80
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2003;silt1;70
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2004;silt1;40
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2005;silt1;30
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2006;silt1;120
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2007;silt1;140
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2008;silt1;200
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2009;silt1;70
näitaja2;Ehitus;Ehituse alavaldkond;Põhikutseala1;2010;silt1;80

**Comment by TanelTromp** [comment]
Viga 3: akordionisse lisamine ei tööta:
