### ISSUE TITLE
OSKA info-tabeli import sisuhalduses

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#473]
**Eesmärk:**
Sisutüübi „ResultPage“ sisus kuvatakse portaali külastajale tabelit, mille andmeid uuendab sisuhaldur CSV-st. Selle töö raames lahendada CSV-st andmete import ja andmete sidumine „ResultPage“ sisutüübiga.

1. Sisuhaldaja avab faili.
Fail on CSV fail, kus:
- veergude eraldaja on semikoolon ( ; ), 
- failis on päiserida (valdkond;juurprobleem;ettepanek;peavastutaja;staatus;kommentaar) 

2. Faili kontroll:
Kontrollida, kas päiserida vastavb struktuurile.
Kui ilmneb viga, siis protsess katkestada ja kuvada veateadet, kuvades kasutajale, milline peab päiserida olema.

3. Salvestada failist loetavad andmed. Faili iga rida salvestada (portaalis kuvamisel soovime kasutada  kahesõnalisi päise kirjeid):
- Valdkonna nimi
- Probleemi kirjeldus
- Ettepanek
- Peavastutaja
- Ettepaneku staatus
- Eksperdikogu kommentaar

Lisainfo - seos piletiga #500 :
- Valdkonna nimi
- Probleemi kirjeldus (500 tähemärki)
- Ettepanek (500 tähemärki)
- Peavastutaja
- Ettepaneku staatus
- Eksperdikogu kommentaar (500 tähemärki)

**Comment by heldiraudsepp** [comment]
Egle lisab viite CSV'le

**Comment by EgleM-TW** [comment]
https://github.com/hariduspilv/haridusportaal/blob/master/docs/Tulemustetabeli_andmed.csv ja SharePointis.

**Comment by lsoonvald** [comment]
Testida saab csv'ga, mis on siin: https://github.com/hariduspilv/haridusportaal/blob/master/docs/oska%20tabeli%20andmed.csv

**Comment by TanelTromp** [comment]
Viga 1: saab veateate (mõistetamatu sisuga), kuigi päis on korras ja proovib lisatud csv faili importida:

<img width="942" alt="capture" src="https://user-images.githubusercontent.com/37407917/47219104-88f3fc80-d3b6-11e8-9598-512f59d93cc7.PNG">

**Comment by lsoonvald** [comment]
Viga 1: Tegu formaadi veaga, UTF-8 võiks olla, siis on korras. Convertisin ümber ka selle faili.
https://github.com/hariduspilv/haridusportaal/blob/master/docs/tul%20andmed.csv

**Comment by TanelTromp** [comment]
Viga 2: 
![pilt](https://user-images.githubusercontent.com/37407917/47297724-9f9c8c80-d61e-11e8-916a-56aa80b586bb.png)

**Comment by EgleM-TW** [comment]
Teen uue tabeli.

**Comment by TanelTromp** [comment]
-----------------------------------------------------------------------------------------------------


    Sisuhaldaja avab faili.
    Fail on CSV fail, kus:

- [x]   veergude eraldaja on semikoolon ( ; ),
- [ ]   failis on päiserida (valdkond;juurprobleem;ettepanek;peavastutaja;staatus;kommentaar) **Failis on päiserida, kus iga nimetaja on oma lahtris ja ilma semikoolonita**

    Faili kontroll:
- [ ]     Kontrollida, kas päiserida vastab struktuurile. **Failis on päiserida, kus iga nimetaja on oma lahtris ja ilma semikoolonita**
- [x]     Kui ilmneb viga, siis protsess katkestada ja kuvada veateadet, kuvades kasutajale, milline peab päiserida olema.

Salvestada failist loetavad andmed. Faili iga rida salvestada (portaalis kuvamisel soovime kasutada kahesõnalisi päise kirjeid):

- [x]    Valdkonna nimi
- [x]    Probleemi kirjeldus (500 tähemärki)
- [x]    Ettepanek
- [x]    Peavastutaja
- [x]   Ettepaneku staatus
- [x]  Eksperdikogu kommentaar (500 tähemärki)

**Comment by EgleM-TW** [comment]
@TanelTromp importisin edukalt sisse: Sharepoint - HTM Haridusportaal - Abimaterjalid - OSKA - Tabel

**Comment by TanelTromp** [comment]
TEST

Viga 1: "juurprobleemi" väljale sisestasin 499 tähemärgi pikkuse teksti ja annab errorit. 
![pilt](https://user-images.githubusercontent.com/37407917/48534608-3fada480-e8b1-11e8-88be-c2d01cb5541b.png)

Fail:
[Tulemused2.zip](https://github.com/hariduspilv/haridusportaal/files/2583905/Tulemused2.zip)

**Comment by lsoonvald** [comment]
Viga 1: Korras.

**Comment by EgleM-TW** [comment]
Testitud tabeli importi ja loodud lk - http://htm.twn.ee/et/oska-tulemused/lugemiseks-ekspertidele.
