### ISSUE TITLE
OSKA valdkondade koondvaate kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#476]
**Üldkirjeldus:**
Kuvada valdkondade (FieldPage) "nimekiri".
Disain: https://zpl.io/VOkO6B1 ja mobiilis: https://zpl.io/anKRGXr
**Selle töö raames ilma halli modaalita.** Modaali pilet on #507.

**Eeltingimused ja käivitamine:**
Valdkondade nimekirja nägemiseks kasutaja valib menüüst "OSKA valdkonnad".

**Vastuvõtutingimused:**
- [ ] "nimekirjas" kuvatakse valdkonnad („FieldPage“), mis on märgitud avaldatavaks (published = true).
- [ ] vaikimisi kuvatakse valdkonna sisulehe lisamise järjekorras, kõige uuemad kõige ees.
- [ ] valdkonnad on kuvatud  ühel lehel (teisisõnu puudub page loader, selle tõttu, et praktikas sisestatakse neid süsteemi 24, tulevikus võib lisanduda mõni.) 
- [ ] "nimekirja" kuvatakse piltidena - vt disaini

Valdkonna kohta kuvatakse:
- [ ] valdkonna pilt, mis valdkonna toimetamisel on märgitud nimistu pildiks (filed picture)
- [ ] valdkonna nimetus (filed title)

- [ ] saab liikuda valdkonna detailvaatesse:
Kuniks pole modaali, nimetusel ja pildil klikkimine viib detailvaatesse. Hiljem avab modaali.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Seosed:
valdonna kuvaminel: #451 
hall modaal: #507

**Comment by EgleM-TW** [comment]
Kuna poltergeist möllab selle piletiga (ei kuva õiget sisu kohe)
Vastuvõtutingimused:
 "nimekirjas" kuvatakse valdkonnad („FieldPage“), mis on märgitud avaldatavaks (published = true).
 vaikimisi kuvatakse valdkonna sisulehe lisamise järjekorras, kõige uuemad kõige ees.
 valdkonnad on kuvatud ühel lehel (teisisõnu puudub page loader, selle tõttu, et praktikas sisestatakse neid süsteemi 24, tulevikus võib lisanduda mõni.)
"nimekirja" kuvatakse piltidena - vt disaini

Valdkonna kohta kuvatakse:
 valdkonna pilt, mis valdkonna toimetamisel on märgitud nimistu pildiks (filed picture)
    valdkonna nimetus (filed title)
    saab liikuda valdkonna detailvaatesse:
    Kuniks pole modaali, nimetusel ja pildil klikkimine viib detailvaatesse. Hiljem avab modaali.

**Comment by madispold** [comment]
Testimisse @TanelTromp 

Valdkondadele, millel pilt puudu pandud placeholder, eeldan et tulevikus kohustuslik nii v naa?
Kuna vaid Ruudustik ehk listivaade hetkel, siis "Võrdlus" nupp ei tee midagi.

**Comment by birgitpulk** [comment]
Visuaalsed teemad: 
- [ ] Fotodel peal olema peal sinist tooni filter #2E3374 20%
- [ ] Hoveriga peaks kaduma fotolt filter ja valdkonna pealkirja taust muutma värvi (taust muutub #EEEEEE ja tekst #333333)
- [ ] Üherealise valdkonna pealkirja puhul võiks pealkirja taga olev sinine kast sama kõrge kui kaherealise puhul
- [ ] Kuidas oleks hea lahendada väiksemate ekraanisuuruste puhul pealkirjade kuvamine? (vt pilti allpool) Äkki peaks väiksemates suurustes kuvama nt 3tk kõrvuti?

**Comment by birgitpulk** [comment]
<img width="203" alt="screen shot 2018-10-25 at 19 08 28" src="https://user-images.githubusercontent.com/24669779/47514652-99f6af00-d889-11e8-883a-fc23c0be8697.png">

**Comment by TanelTromp** [comment]
TEST

Viga 1: nõue ei ole täidetud - see kalusel ei tohiks puudutada muutmist, vaid ainult lisamist:_vaikimisi kuvatakse valdkonna sisulehe lisamise järjekorras, kõige uuemad kõige ees._

Viga 2: ei kuva kõiki sisuhalduses lisatud/avaldatud valdkondi, vaid ainult 23. 
nt "Põllumajandus" puudu..

**Comment by madispold** [comment]
@birgitpulk disainimuudatused tehtud
Pandud mobiilivaade 2 plokki kõrvuti, keskmine vaade 3 ja suur vaade 4.

@TanelTromp 
Viga 1: OK.
Viga 2: OK. Kui puudu, siis veenduda, et kõik ikkagi õiges keeles lisatud.
Viga 3: OK.
Viga 4: OK.

**Comment by madispold** [comment]
Täiendatud @birgitpulk

**Comment by birgitpulk** [comment]
Ei näe, et hoveriga muutuks pealkiri Mediumiks? @madispold

**Comment by TanelTromp** [comment]
TEST OK

**Vastuvõtutingimused:**

- [x] "nimekirjas" kuvatakse valdkonnad („FieldPage“), mis on märgitud avaldatavaks (published = true).
- [x] vaikimisi kuvatakse valdkonna sisulehe lisamise järjekorras, kõige uuemad kõige ees.
- [x] valdkonnad on kuvatud  ühel lehel (teisisõnu puudub page loader, selle tõttu, et praktikas sisestatakse neid süsteemi 24, tulevikus võib lisanduda mõni.) 
- [x] "nimekirja" kuvatakse piltidena - vt disaini

Valdkonna kohta kuvatakse:
- [x] valdkonna pilt, mis valdkonna toimetamisel on märgitud nimistu pildiks (filed picture)
- [x] valdkonna nimetus (filed title)

- [x] saab liikuda valdkonna detailvaatesse:
Kuniks pole modaali, nimetusel ja pildil klikkimine viib detailvaatesse. Hiljem avab modaali.

**Comment by birgitpulk** [comment]
Hoveriga tekib tooltip, kus näidatakse pildi pealkirja. @TanelTromp, mina võtaks selle maha, mis sa arvad?
