### ISSUE TITLE
OSKA ametialade (põhikutsealade) nimekirja kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#477]
**NB! põhikutseala = ametiala**

**Üldkirjeldus:**
Kuvada põhikutsealade (MainProfession) nimekiri, et kasutaja saaks leida huvipakkuva põhikutseala.
Disaini link: https://zpl.io/bLDo836

**Eeltingimused ja käivitamine:**
Põhikutsealade nimekirja nägemiseks kasutaja valib menüüst "Põhikutselad" .

**Vastuvõtutingimused:**
- [ ] nimekirjas kuvatakse põhikutsealad, mis on märgitud avaldatavaks (published = true).
- [ ] vaikimisi kuvatakse põhikutseala lisamise järjekorras, kõige uuemad kõige ees.
Muudetud: BE annab ja kuvame tähestikulises järjekorras. Teadmiseks: @TanelTromp @lsoonvald @madispold 
- [ ] kasutaja saab nimistus eelmisi-järgmisi kirjeid vaadata (lae veel nupp).

Põhikutseala kohta kuvatakse nimistus:
- [ ] põhikutseala nimetus (mainProfession title)
- [ ] põhikutsealaga seotud valdkond (OSKA_Field title), kuvatakse kuni 3 valdkonna nimetust (taksonoomiast lisatud järjekorra alusel esimesed 3).
- [ ] näitaja (indicator) (kui on lisatud, esimesed 2)
- [ ] võrdlusesse lisamise võimalus

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Seosed:
Otsing/filter nimekirja kohal: #487
Võrdlusesse lisamine: #478

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, hetkel vastupidi (viimasena sisestatud nimekirja lõpus) _vaikimisi kuvatakse põhikutseala uuendamise järjekorras, kõige uuemad kõige ees_

Viga 2: mobiilivaates võiks "fixed labeli" ja pealkirja vahel rohkem õhku olla:

![pilt](https://user-images.githubusercontent.com/37407917/46806289-e2817900-cd6f-11e8-91a7-b1a2cb02bde8.png)

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.
Viga 3: OK.
Viga 4: OK.
Viga 5: OK.
Viga 6: OK.
Viga 7: Kui päringu vastuses täpselt 5 väärtust siis enne uut päringut ei tea kas on rohkem väärtusi, eriti eri filtreid kasutades. Võimalik oleks FE "Lae rohkem" loogika viia ja kogu päring koheselt teha, kuid siis võivad päringud suureks minna tulevikus.

**Comment by EgleM-TW** [comment]
12.10 - lisamise järjekorras

**Comment by TanelTromp** [comment]
Viga 8: snackbar, kus on kirjeldatud eemaldamine puudub:
https://gyazo.com/7b0f036920a2898168e332aea86ee2fa

**Comment by madispold** [comment]
Viga 8: OK - Ei refreshi enam põhjuseta snackbari, snackbar kaob vaid siis, kui võrdlusest kõik eemaldatud.
