### ISSUE TITLE
OSKA ametialade võrdlemise vaade

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#478]
**NB! põhikutseala = ametiala**

**Üldkirjeldus:**
Portaali kasutaja saab ametialadest teha võrdlustabeli. Sarnaselt erialade võrdlusele.

**Eeltingimused ja käivitamine:**
- Kasutajale on kuvatud ametiala detailvaade (#452 ).
- Kasutajale on kuvatud ametitalade nimekirjavaade #477 ).

**Vastuvõtutingimused:**
Kasutaja saab käivitada järgmisi tegevusi:
- [ ] Kui kuvatav ametiala pole lisatud võrdlusesse, siis lisada võrdlusesse.
- [ ] Kui kuvatav ametiala on juba lisatud võrdlusesse, siis eemaldada ametiala võrdlusest.
- [ ] Kui võrdluses on vähemalt üks ametiala, siis vaadata võrdlust.
- [ ] Korraga võrdluses olevate ametialade arv on piiratud (max 3).
**Lisamine:**
Süsteem lisab ametiala võrdlusesse. Ametiala ekraanivormi võrdlusesse lisamise võimalus asendatakse eemaldamise ja võrdluse vaatamise võimalustega.
Kui see arv on juba täis, siis süsteem kuvab teate (sama lahendus, mis erialade võrdlemisel): 
"Ametialade võrdlemine"
Maksimaalne võrreldavate ametialade arv on ületatud.
Võrdlusesse saab lisada kuni 3 ametiala."
**Eemaldamine:**
Süsteem eemaldab ametiala võrdlusest. Ametiala ekraanivormil võrdlusest eemaldamise võimalus asendatakse võrdlusesse lisamise võimalusega.

**Võrdluse vaatamine**
- [ ] Süsteem kuvab võrdlusesse lisatud ametialade kohta tabeli kujul järgmised andmed:
-- Ametiala nimetus - name
-- Valdkonnad - OSKA_field (mitme valdkonna korral kuvada üksteise all)
-- Plussid ja miinused - pros_cons (kuvada üksteise all, nii nagu sisuhalduses on sisestatud)
-- Naitajad - indicator (kuvada üksteise all)

* Kui andmeelemendi väärtus puudub, siis kuvatakse tabelis selle asemel "Info puudub" .
* Ametiala nimetus kuvatakse lingina, millele klikkimise korral avatakse selle ametiala detailvaade.
* Valdkonna nimetus kuvatakse lingina, millele klikkimise korral avatakse selle valdkonna detailvaade.

* Ametialasid saab võrdluse vaatamise ekraanivormil võrdlusest eemaldada. Kui kasutaja eemaldab võrdlusest eemaldatakse viimase ametiala (võrdlus jääb tühjaks), siis süsteem kuvab ametialade nimistu.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Disain:**
detailvaade: https://zpl.io/V41Wg1M
nimistu: https://zpl.io/bLDo836
võrdlemine: disaini pole, võtta aluseks erialade võrdlus ja vajadusel küsida Birgitilt!

**Viited:**
detailvaade: #453 
nimistu: #477

**Comment by EgleM-TW** [comment]
Muutsin piletis sõna põhikutseala ametialaks. Kui kuskil jäi muutmata, siis õige on "ametiala"

**Comment by TanelTromp** [comment]
TEST

Viga 1 iPad: snackbar on liiga suur - ekraanilt väljas ja varjab viimast nimekirja teemat (võiks kasutada sama kujundust, mid desktopil - ruumi on):
![snackbar](https://user-images.githubusercontent.com/37407917/47344102-5563eb80-d6b0-11e8-89dc-f9e0456ad2e2.jpg)

**Comment by madispold** [comment]
Kui andmeelemendi väärtus puudub, siis kuvatakse tabelis selle asemel "Info puudub" - Kuvatakse "-", vastasel juhul oleks ääretult kirju see vaade :)

Testimisse @birgitpulk @TanelTromp

**Comment by madispold** [comment]
Viga 1: OK.
Viga 1.2: OK.
Viga 2: Pigem nice to have, peaks hoidma mitmeid parameetreid mälus ja üle süsteemi siis iga sellise vaate puhul?
Viga 3: Hetkel nupud tabeli keskel. Tuleb mõelda kuidas neid liigutada X suurusega tabelite korral.
Viga 4: Fokuseerib uute laetud elementide ette - OK.
Viga 6: OK.
Viga 7: Materiali elemendil mat-dialog on vastav roll küljes, et loeb kogu dialoogi sisu, uurin veel lähemalt, aga kohe lahendust ei leidnud.

**Comment by TanelTromp** [comment]
Viga 1 iPad: endiselt issue - kui kõik teemad on avatud "Lae rohkem" CTA kaudu, siis viimane teema jääb snackbnari taha peitu

**Comment by madispold** [comment]
Viga 1: OK.
Viga 5: OK.

**Comment by TanelTromp** [comment]
Vastuvõtutingimused:
Kasutaja saab käivitada järgmisi tegevusi:

-[x]  Kui kuvatav ametiala pole lisatud võrdlusesse, siis lisada võrdlusesse.
Kui kuvatav ametiala on juba lisatud võrdlusesse, siis eemaldada ametiala võrdlusest.
Kui võrdluses on vähemalt üks ametiala, siis vaadata võrdlust.
Korraga võrdluses olevate ametialade arv on piiratud (max 3).

Süsteem lisab ametiala võrdlusesse. Ametiala ekraanivormi võrdlusesse lisamise võimalus asendatakse eemaldamise ja võrdluse vaatamise võimalustega.
Kui see arv on juba täis, siis süsteem kuvab teate (sama lahendus, mis erialade võrdlemisel):
    "Ametialade võrdlemine"
    Maksimaalne võrreldavate ametialade arv on ületatud.
    Võrdlusesse saab lisada kuni 3 ametiala."
Eemaldamine:
Süsteem eemaldab ametiala võrdlusest. Ametiala ekraanivormil võrdlusest eemaldamise võimalus asendatakse võrdlusesse lisamise võimalusega.

Võrdluse vaatamine

Süsteem kuvab võrdlusesse lisatud ametialade kohta tabeli kujul järgmised andmed:
    -- Ametiala nimetus - name
    -- Valdkonnad - OSKA_field (mitme valdkonna korral kuvada üksteise all)
    -- Plussid ja miinused - pros_cons (kuvada üksteise all, nii nagu sisuhalduses on sisestatud)
    -- Naitajad - indicator (kuvada üksteise all)

Kui andmeelemendi väärtus puudub, siis kuvatakse tabelis selle asemel "Info puudub" . **Muudatus: kuvatakse "-"
Ametiala nimetus kuvatakse lingina, millele klikkimise korral avatakse selle ametiala detailvaade.
Valdkonna nimetus kuvatakse lingina, millele klikkimise korral avatakse selle valdkonna detailvaade.
Ametialasid saab võrdluse vaatamise ekraanivormil võrdlusest eemaldada. Kui kasutaja eemaldab võrdlusest eemaldatakse viimase ametiala (võrdlus jääb tühjaks), siis süsteem kuvab ametialade nimistu.

**Comment by madispold** [comment]
Mobiilis määratud minimaalne nõutud laius - OK.

**Comment by birgitpulk** [comment]
Mis sellest veast sai, et tabeli nooled jäävad tabeli keskele ja ei liigu kerimisel kaasa? Praegu see häirib küll sellise suure tabeli puhul @madispold @TanelTromp

**Comment by madispold** [comment]
@birgitpulk Scroll nooled OK - jätsin hetkel need allapoole mitte vaate keskele, et nad otse sisu keskel poleks, positsioneering sinu otsustada.

**Comment by birgitpulk** [comment]
Minu poolt kujunduse osas korras!
