### ISSUE TITLE
Lemmatiseerija

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#484]
- [ ] Otsingule  lisada lemmatiseerija funktsionaalsus https://www.riha.ee/api/v1/systems/riigiportaal/files/19e1db44-ab95-8dbc-a63b-82db52e0cc9b

- [ ] Soovitava  (autocomplete) ja automaatse (search-as-you-type) otsingu häälestamine koos lemmatiseerijaga

https://github.com/Filosoft/vabamorf
https://github.com/estnltk/estnltk
juhendid
https://estnltk.github.io/estnltk/1.4.1/tutorials/elasticsearch.html
https://github.com/estnltk/estnltk/tree/version_1.4/estnltk/database

**Comment by lsoonvald** [comment]
Uurisin Estnltk'd ning antud dokumendist ei leidnud väga häid viiteid, mis abistaksid kogu selle süsteemi püstipanemisele.

Mina prooviksin Hunspelli, mille setupimine on Elasticus hästi dokumenteeritud: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-hunspell-tokenfilter.html

Hunspelli jaoks on olemas ka eestikeelne sõnastik: https://github.com/titoBouzout/Dictionaries

**Comment by lsoonvald** [comment]
Saab testida urlil: http://test-htm.wiseman.ee:9200/elasticsearch_index_drupaldb_articles/_analyze?analyzer=default&text=""

Jutumärkide sisse panna testitav tekst, siis näeb, millisteks osadeks ta antud teksti teeb.
