### ISSUE TITLE
Ametialade (Põhikutsealade) nimekirja kohal otsing/filter

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#487]
**NB! põhikutseala = ametiala**

**Üldkirjeldus:**
Kasutaja saab filtreerida kuvatud ametialade nimekirja, et leida huvipakkuv ametiala.
Disaini link: https://zpl.io/2jwB4KA

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud ametialade nimistu (#477 ).

**Vastuvõtutingimused:** 
* Ametialasid saab filtreerida järgmiste tunnuste alusel:
- [ ] "Märksõna" märksõna - süsteem otsib ametialasid, mille korral sisestatud märksõna sisaldub ametiala nimetuses (title);
--- ja näidisameti nimetustes (üle süsteemi kõigist) (job position).
Võrdlused ei ole tõstutundlikud (suur- ja väiketähed loetakse samaväärseks).
Esimeses järjekorras kuvatakse ametiala nimetusest leitud vasted.
- [ ] "Valdkond" - Kasutaja valib otsitava valdkonna taksonoomiast (OSKA_Field).
Süsteem otsib ametialad, millel on seos valitud valdkonnaga.

"Sorteeri näitaja järgi" - eraldi tööna #505 

**Täpsustused (22.10.2018)**
1. "Valdkond"  pole kohustuslik määrata
2. "Valdkond" dropdown kuvada alfabeetiliselt
3. Märksõna otsing - ei pea töötama osalise/ vale terminiga. boolean operaatorid lahendada sarnaselt uudiste ja sündmuste pealkirja otsingule.
Tulemuste kuvamine
4. Kuvada ametiala järgi alfabeetiliselt
5. Kuvamine otsingu all nimekirjas: https://zpl.io/2jwB4KA

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Seosed:
Nimekirja kuvamine: #477

**Comment by madispold** [comment]
@TanelTromp 
Listis ja filtris tulemused veel vaja tähestikulises järjekorras kuvada BE poolelt @lsoonvald 
Lisaks "Sorteeri" filter veel eraldi tööna #505.

**Comment by TanelTromp** [comment]
TEST

Viga 1: kui sisestada otsingusse väärused "eesti" ja "ee", siis süsteem jookseb kokku - loader jääbki saagima.

**Comment by madispold** [comment]
Viga 1: OK.
Viga 1.2: OK.
Viga 2: Kui tegemisse, siis hilhjem, vaja luua loogika, millega jälgida moblas keyboard state'i. Otseselt ei piira ka toiminguid :)
Viga 3: Zoom, kuna input font < 16px. Veel arutelus, mis teeme.
Viga 4: OK.
Viga 5: Material select komponendil tekib scrollbar alles kerides/sellel hoverides: Ütleks, et OK.
https://material.angular.io/components/select/overview
Viga 6: @lsoonvald "näidisameti" nimed ei ole otsitundlikud ehk neid pole päringu tulemustes. Vaja lisada.
Viga 7: @lsoonvald Tähestiku järjekorras kuva aeg ajalt valesti.

**Comment by birgitpulk** [comment]
Visuaalne viga: 
Kui input väljale on sisestatud tekst ja dropdownis on tehtud valik, siis väljadel olevad teksti ja labeli toonid ja paksused ei ole identsed. Sama viga ka teistes filtriga vaadetes. Kas parandame kõik ära või raporteerin teised vaated disainivigade piletisse? @madispold 
<img width="975" alt="screen shot 2018-10-25 at 18 56 06" src="https://user-images.githubusercontent.com/24669779/47513922-ee009400-d887-11e8-9f80-5f00ac3b083c.png">

**Comment by birgitpulk** [comment]
Kujunduse osas korras!

**Comment by lsoonvald** [comment]
Viga 6: Näidisamet tehtud otsitundlikuks.
Viga 7: Tähestiku järjekord peaks korrektne olema.

**Comment by TanelTromp** [comment]
Viga 8: kui valida peamenüüst uuesti "ametialad", siis "Märksõna" ei tühjenda aga otsitulemused ja URL ei ole märksõnaga enam seotud, vist peaks resettima:
https://gyazo.com/605d5d934a80e6a3fa834d606e96f635

**Comment by lsoonvald** [comment]
Viga 6: Peaks korras olema, mingi sügavam cachemise teema. Kui sa kustutad ära sealt selle näidisameti, mis ei toimi ja lisad uue näidisameti, siis toimib.

**Comment by madispold** [comment]
Viga 8: OK.
@TanelTromp

**Comment by TanelTromp** [comment]
Viga 9: annab otsinguvaste ka kui sisestad ühe tähe, numbri. Pigem maha keerata, sest ühetähelisi sõnu Eestis ei ole.

**Comment by madispold** [comment]
Viga 9: Taneliga arutelu tulemus: Vaja suures ringis läbi arutada.

**Comment by heldiraudsepp** [comment]
Tekitame reeglid autocomplete tööde raames

**Comment by TanelTromp** [comment]
TEST OK

**Vastuvõtutingimused:** 
* Ametialasid saab filtreerida järgmiste tunnuste alusel:
- [x] "Märksõna" märksõna - süsteem otsib ametialasid, mille korral sisestatud märksõna sisaldub ametiala nimetuses (title);
- [x] --- ja näidisameti nimetustes (üle süsteemi kõigist) (job position).
- [x] Võrdlused ei ole tõstutundlikud (suur- ja väiketähed loetakse samaväärseks).
- [x] Esimeses järjekorras kuvatakse ametiala nimetusest leitud vasted.

- [x] "Valdkond" - Kasutaja valib otsitava valdkonna taksonoomiast (OSKA_Field).
Süsteem otsib ametialad, millel on seos valitud valdkonnaga.


**Täpsustused (22.10.2018)**
- [x] 1. "Valdkond"  pole kohustuslik määrata
- [x] 2. "Valdkond" dropdown kuvada alfabeetiliselt
- [x] 3. Märksõna otsing - ei pea töötama osalise/ vale terminiga. boolean operaatorid lahendada sarnaselt uudiste ja sündmuste pealkirja otsingule.
Tulemuste kuvamine
- [x] 4. Kuvada ametiala järgi alfabeetiliselt
- [x] 5. Kuvamine otsingu all nimekirjas: https://zpl.io/2jwB4KA
