### ISSUE TITLE
Infograafika täiendus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#492]
Täiendada #468 lahendust (kui see pilet on Done , siis sulgeme 468 pileti).
FE töö infograafika kuvamiseks: #498 

Sisutüübid: MainProfessionPage #452 , FieldPage #450 , SurveyPage #474 

1. Sisuhaldur saab:
-  [ ] valida diagrammi nime (näitaja) (1)
-  [ ] valida filtri väärtused (valdkond;alavaldkond;pohikutseala;periood) (0.. n)
-  [ ] valida x-telje väärtuse (silt) (1) - periood on paigas (_lisatud 10.10)_ - muudatus #537 
-  [ ] valida graafiku tüübi 

Graafiku tüübid:
   - line chart
   - bar chart
   - column chart
   - pie chart
   - doughnut chart
_gauge - tulevikus eraldi tööna (10.10)_

Selleks, et kuvada kombineeritud graafikut (mitme näitajaga)

2. Sisuhaldur saab:
-  [ ] valida teise diagrammi nime (näitaja) (1)
-  [ ] valida graafiku tüübi 
piirangud: 
   - kui valis line chart, saab valida, bar chart 
   - kui valis bar chart, saab valida line chart
   - kui valis column chart, ei saa teist graafikut lisada
   - kui valis gauge chart, ei saa teist graafikut lisada
   - kui valis pie chart, ei saa teist graafikut lisada
   - kui valis doughnut chart, ei saa teist graafikut lisada

Graafiku kuvamiseks teeb drupal back-end päringu CSV-st laetud andmetest:
-  [ ] Filtreerib CSV-st laetud andmetest lähtudes kasutaja valikutest 
-  [ ] Grupeerib sildi (label) alusel ja summeerib väärtused (value).

**Comment by lsoonvald** [comment]
Näitaja valimine käib ühe välja alt, esimene valitud näitaja läheb esimese omaks, teine valitud teise omaks.

**Comment by EgleM-TW** [comment]
Saabus näidisandmestik: 
[OSKA_naidis_andmestik-121018.txt](https://github.com/hariduspilv/haridusportaal/files/2472126/OSKA_naidis_andmestik-121018.txt)
Tuleb ise CSV-sse salvestada.

**Comment by TanelTromp** [comment]
TEST

1. Sisuhaldur saab:
-  [ ] valida diagrammi nime (näitaja) (1)
-  [ ] valida filtri väärtused (valdkond;alavaldkond;pohikutseala;periood) (0.. n)
-  [ ] valida x-telje väärtuse (silt) (1) - periood on paigas (_lisatud 10.10)_
-  [ ] valida graafiku tüübi 

Graafiku tüübid:
   - line chart
   - bar chart
   - column chart
   - pie chart
   - doughnut chart
_gauge - tulevikus eraldi tööna (10.10)_

Selleks, et kuvada kombineeritud graafikut (mitme näitajaga)

2. Sisuhaldur saab:
-  [ ] valida teise diagrammi nime (näitaja) (1)
-  [ ] valida graafiku tüübi 
piirangud: 
   - kui valis line chart, saab valida, bar chart 
   - kui valis bar chart, saab valida line chart
   - kui valis column chart, ei saa teist graafikut lisada
   - kui valis gauge chart, ei saa teist graafikut lisada
   - kui valis pie chart, ei saa teist graafikut lisada
   - kui valis doughnut chart, ei saa teist graafikut lisada

Graafiku kuvamiseks teeb drupal back-end päringu CSV-st laetud andmetest:
-  [ ] Filtreerib CSV-st laetud andmetest lähtudes kasutaja valikutest 
-  [ ] Grupeerib sildi (label) alusel ja summeerib väärtused (value).

**Comment by EgleM-TW** [comment]
Lisandus "ResultPage"
