### ISSUE TITLE
Täiendada e_tunnistus_kod teenuse päringu teisendust

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#493]
Täiendada: e_tunnistus_kod päringu teisendust BE jaoks #245 

Jaotada päringu tulemus BE jaoks nii, et testi staatus ja tulemus on eraldi ja testiosa tulemus ja staatus on järjekorras.

Näide:

test_nimi>Matemaatika (riigieksam 2017)</test_nimi
**staatus>Tulemus on teada</staatus
tulemus>94p 100-st, 94%</tulemus**

osa_nimi>I osa</osa_nimi
osa_kuupaev>2017-05-12</osa_kuupaev
osa_koht>Rocca al Mare Kool</osa_koht
osa_aadress>Harju maakond, Tallinn, Haabersti linnaosa, Vabaõhumuuseumi tee 8</osa_aadress
**staatus>Tulemus on teada</staatus
tulemus>44p 50-st, 88%</tulemus**

osa_nimi>II osa</osa_nimi
osa_kuupaev>2017-05-12</osa_kuupaev
osa_koht>Rocca al Mare Kool</osa_koht
osa_aadress>Harju maakond, Tallinn, Haabersti linnaosa, Vabaõhumuuseumi tee 8</osa_aadress
**staatus>Tulemus on teada</staatus
tulemus>50p 50-st, 100%</tulemus**

**Comment by EgleM-TW** [comment]
Henri, kui sa testid, palun vt FE piletit #247 , kas saame sellise JSON-i pealt andmeid nii kuvada.

**Comment by IndrekVallsalu** [comment]
tulemuste JSON object peaks hakkama välja nägema siis selline ?

{
	"test_nimi": "Vene keel võõrkeelena",
	"staatus": "Tulemus on teada",
	"tulemus": "51p 100-st, 51%",
	"osad": [{
		"osa_nimi": "Kirjutamine",
		"osa_kuupaev": "05.06.2008",
		"osa_koht": "Jõgeva Täiskasvanute Keskkool",
		"osa_aadress": "Jõgeva maakond, Jõgeva vald, Jõgeva linn, Aia tn 34",
		"staatus": "Tulemus on teada",
		"tulemus": "9,5p 20-st, 47,5%"
	},
	{
		"osa_nimi": "Kuulamine",
		"osa_kuupaev": "05.06.2008",
		"osa_koht": "Jõgeva Täiskasvanute Keskkool",
		"osa_aadress": "Jõgeva maakond, Jõgeva vald, Jõgeva linn, Aia tn 34",
		"staatus": "Tulemus on teada",
		"tulemus": "7,5p 20-st, 37,5%"
	},
	{
		"osa_nimi": "Lugemine",
		"osa_kuupaev": "05.06.2008",
		"osa_koht": "Jõgeva Täiskasvanute Keskkool",
		"osa_aadress": "Jõgeva maakond, Jõgeva vald, Jõgeva linn, Aia tn 34",
		"staatus": "Tulemus on teada",
		"tulemus": "7,5p 20-st, 37,5%"
	},
	{
		"osa_nimi": "Keele struktuur",
		"osa_kuupaev": "05.06.2008",
		"osa_koht": "Jõgeva Täiskasvanute Keskkool",
		"osa_aadress": "Jõgeva maakond, Jõgeva vald, Jõgeva linn, Aia tn 34",
		"staatus": "Tulemus on teada",
		"tulemus": "9,5p 20-st, 47,5%"
	},
	{
		"osa_nimi": "Suuline osa",
		"osa_kuupaev": "05.06.2008",
		"osa_koht": "Jõgeva Täiskasvanute Keskkool",
		"osa_aadress": "Jõgeva maakond, Jõgeva vald, Jõgeva linn, Aia tn 34",
		"staatus": "Tulemus on teada",
		"tulemus": "17p 20-st, 85%"
	}]
}
