### ISSUE TITLE
Ametiala (põhikutseala) parema veeru toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#494]
**NB! põhikutseala = ametiala**

**Eesmärk:**
Sisuhalduses saab toimetada põhikutseala „MainProfessionPage“ #452 mallil **sisulehe paremat veergu**.

**Parema veeru elemendid:** 
Disain: - https://zpl.io/V41Wg1M

**Näitajad (indicators):**
Seos tööga #506 
- [ ] Näitajate CSV'd importides seotakse näitajad Põhikutsealaga ära, sisuhaldur ei pea käsitsi siduma.

Plussid ja miinused (pros_cons), **vabatahtlik**
- [ ] saab lisada kuni 5 plussi ja 5 miinust, teksti sisestus kuni 100 tähemärki
- [ ] sisuhalduses eristatada plusside ja miinuste sisestamine (kuvamisel on erinevad ikoonid)

Valdkonnad (OSKA_field), **kohustuslik**
- [ ] saab lisada kuni n arv valdkonda, (sisu OSKA_field)

Õppimisvõimalused (learning opportunities), **vabatahtlik**
- [ ] Eriala otsing - siselink, mis viib erialade filtreeritud otsingusse - saab lisada ühe filtreerimiseks vajaliku parameetri, et kuvada lingi all filtreeritud eriala otsingut:
_Arenduse käigus otsustada, kas sisestab ainult ISCEDFdetailedField või nii nagu all kirjas:_
-- Õppevaldkond - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF, kõige üldisem). 
-- Õppesuund - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF keskmine tase; saab valida eelnevalt valitud valdkonna alla kuuluvate suundade hulgast). 
-- Õppekavarühm - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF kõige detailsem tase, ; saab valida eelnevalt valitud suuna alla kuuluvate õppekavarühmade hulgast, multivalik). 
Lisaks samas blokis:
- [ ] Teksti sisestus kuni 100 tähemärki, **vabatahtlik**

_Arendus arutab, kas ja kuidas õppimisvõimaluste fix filtrit lahendada_

Töövõimalused (job opportunities), **vabatahtlik**
- [ ] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [ ] jrk nr (SecuenceNo)
- [ ] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [ ] Lingi URL (WebPageAddress)

Kutsestandardid (qualificationStandard), **vabatahtlik**
- [ ] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [ ] jrk nr (SecuenceNo)
- [ ] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [ ] Lingi URL (WebPageAddress)

Näidisametid (job), **vabatahtlik**
- [ ] saab lisada kuni n arv nimetusi, maksimaalne pikkus 50
Saab muuta nimetuse lingiks:
- [ ] Lingi URL (WebPageAddress) - vabatahtlik, sest iga ameti kohta pole linki lisada

Leia kiiresti (Link), **vabatahtlik**  _See on mõeldud koolide veebide lisamiseks_
- [ ] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [ ] jrk nr (SecuenceNo)
- [ ] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [ ] Lingi URL (WebPageAddress)

Kontakt (Contact), **vabatahtlik**
- [ ] Paremal ääreribal saab olla üks kontakti osa
- [ ] nimi (person), maksimaalne pikkus 50
- [ ] organisatsioon (organization), maksimaalne pikkus 50
- [ ] telefon (phone), telefoni formaat
- [ ] e-post (e-mail), e-maili formaat

**Comment by TanelTromp** [comment]
Test

Täpsustus/Viga 1: kas välja saab pikemaks venitada? Hetkel pooled teemad peidus ja vaade katki:

<img width="454" alt="capture" src="https://user-images.githubusercontent.com/37407917/46732118-484d0280-cc95-11e8-9d05-cf50233fbbe4.PNG">

Viga 2: lingi pealkirja pikkus ei ole limiteeritud "Töövõimalused" sisus. _Lingi pealkiri (LinkTitle), maksimaalne pikkus 50_

Viga 3: ilmselt see väli üleliigne, KUI URL lisada sest "Ameti nimetus" = juba "lingi tekst" ja nõuetes ka ei ole:

<img width="581" alt="capture" src="https://user-images.githubusercontent.com/37407917/46733851-2904a400-cc9a-11e8-8d9a-b188b031a179.PNG">



----------------------------------------------------------------------------------------
**Näitajad (indicators):**
Seos tööga #506 
- [ ] Näitajate CSV'd importides seotakse näitajad Põhikutsealaga ära, sisuhaldur ei pea käsitsi siduma.

Plussid ja miinused (pros_cons), **vabatahtlik**
- [x] saab lisada kuni 5 plussi ja 5 miinust, teksti sisestus kuni 100 tähemärki
- [x] sisuhalduses eristatada plusside ja miinuste sisestamine (kuvamisel on erinevad ikoonid)

Valdkonnad (OSKA_field), **kohustuslik**
- [x] saab lisada kuni n arv valdkonda, (sisu OSKA_field)

Õppimisvõimalused (learning opportunities), **vabatahtlik**
- [x] Eriala otsing - siselink, mis viib erialade filtreeritud otsingusse - saab lisada ühe filtreerimiseks vajaliku parameetri, et kuvada lingi all filtreeritud eriala otsingut:
_Arenduse käigus otsustada, kas sisestab ainult ISCEDFdetailedField või nii nagu all kirjas:_
-- Õppevaldkond - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF, kõige üldisem). 
-- Õppesuund - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF keskmine tase; saab valida eelnevalt valitud valdkonna alla kuuluvate suundade hulgast). 
-- Õppekavarühm - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF kõige detailsem tase, ; saab valida eelnevalt valitud suuna alla kuuluvate õppekavarühmade hulgast, multivalik). 
Lisaks samas blokis:
- [x] Teksti sisestus kuni 100 tähemärki, **vabatahtlik**

_Arendus arutab, kas ja kuidas õppimisvõimaluste fix filtrit lahendada_

Töövõimalused (job opportunities), **vabatahtlik**
- [x] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [x] jrk nr (SecuenceNo)
- [x] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [x] Lingi URL (WebPageAddress)

Kutsestandardid (qualificationStandard), **vabatahtlik**
- [x] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [x] jrk nr (SecuenceNo)
- [x] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [x] Lingi URL (WebPageAddress)

Näidisametid (job), **vabatahtlik**
- [x] saab lisada kuni n arv nimetusi, maksimaalne pikkus 50
Saab muuta nimetuse lingiks:
- [x] Lingi URL (WebPageAddress) - vabatahtlik, sest iga ameti kohta pole linki lisada

Leia kiiresti (Link), **vabatahtlik**  _See on mõeldud koolide veebide lisamiseks_
- [ ] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [ ] jrk nr (SecuenceNo)
- [ ] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [ ] Lingi URL (WebPageAddress)

Kontakt (Contact), **vabatahtlik**
- [ ] Paremal ääreribal saab olla üks kontakti osa
- [ ] nimi (person), maksimaalne pikkus 50
- [ ] organisatsioon (organization), maksimaalne pikkus 50
- [ ] telefon (phone), telefoni formaat
- [ ] e-post (e-mail), e-maili formaat

**Comment by lsoonvald** [comment]
Täpsustus/Viga 1: kas välja saab pikemaks venitada? Hetkel pooled teemad peidus ja vaade katki:
Peaks Material designi ümber tegema selleks, pole mõtet.

Viga 2: lingi pealkirja pikkus ei ole limiteeritud "Töövõimalused"+ "Leia kiiresti" sisus. Lingi pealkiri
Lingi pealkirja väljadele ei saa limiiti panna kahjuks.

Viga 3: ilmselt see väli üleliigne, KUI URL lisada sest "Ameti nimetus" = juba "lingi tekst" ja nõuetes ka ei ole:
Võtsin maha selle.
