### ISSUE TITLE
Ametiala (Põhikutseala) parema veeru kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#495]
**NB! põhikutseala = ametiala**

**Eesmärk, üldtingimused:**
Portaali külastaja saab menüü või mõne muu sisulehe lingi kaudu navigeerida „MainProfessionPage“ mallil sisulehele ja tutvuda selle parema veeru sisuga.

**Eeltingimused ja käivitamine:**
- kasutaja navigeerib menüüst „MainProfessionPage" mallil sisulehele
- BE toimetamise töö on tehtud #494 

**Vastuvõtutingimused:** 
- [ ] Kasutaja näeb lehe paremal serval (kui on sisuhalduses lisatud):
- Näitajad (indicators päritakse CSV andmetest)
- Plussid ja miinused (pros_cons) 
- Valdkonnad (OSKA_field)
- Õppimisvõimalused (learning opportunities)
- Töövõimalused (job opportunities)
- Kutsestandardid (qualificationStandard)
- Näidisametid (job)
- Leia kiiresti (Link)
- Kontakt (Contact)

Disain: - https://zpl.io/V41Wg1M

- [ ] Kui mõni teema või mittekohustuslik väli on sisestamata siis ei kuvata nö auku, vaid sisestatud teemad kuvatakse järjest.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Viited:
back-end töö #494

**Comment by madispold** [comment]
Testimisse @TanelTromp 

http://htm.twn.ee/et/ametialad/teabe-ja-dokumendihalduse-spetsialistid
http://htm.twn.ee/et/ametialad/uus-koige-esimene-test

**Comment by TanelTromp** [comment]
TEST

Viga 1: "Näidisametid" sektsioonis vale ikoon (outbound), peab olema ankur (inbound) nagu Zeplinis

<img width="179" alt="screenshot_20181024-090249" src="https://user-images.githubusercontent.com/37407917/47414983-fdde8200-d77a-11e8-8c9b-42bd439bf2af.png">

Viga 2 desktop: Akordioni ja "silt" tagi vahel on liiga väike vahe ja ei saa aru, et see silt ei kuulu akordioni juurde. Zeplinis suurem ja parem vahe
Kaaluksin ka nende siltide viimist ülesse muu kraami juurde peale pealkirja. Saan aru, et seal läheb kirjuks aga hetkel väga "lost" need sildid - eriti mobiili ja tableti vaates, kus peale neid tuleb veel parema veeru sisu

<img width="561" alt="12" src="https://user-images.githubusercontent.com/37407917/47415195-86f5b900-d77b-11e8-9f7b-46a7b4e97bd9.PNG">

Üldiselt

**Comment by madispold** [comment]
@TanelTromp 
Viga 1: OK.
Viga 1.2: OK.
Viga 2: OK.
Viga 3: OK.
Viga 4: @lsoonvald päringuga saab vaid eriala ID hetkel, vaja ka entityLabel'it.
Viga 5: OK.
Viga 6: OK.
Viga 7: OK.
Viga 8: OK.
Viga 9: OK.
Viga 10: OK.

**Comment by lsoonvald** [comment]
Viga 4: Korras.

**Comment by EgleM-TW** [comment]
Jääb nii, et kuvame ikooni vastavalt sellele, kas link on sisemine või väline ja vägisi ikooni ei muuda. Näiteks kui sisuhaldur lisabki välise lingi sinna, kus on ettenähtud sisemised, siis kuvame selle välise lingi ees välist ikooni.

Kasutusjuhendis märgime, et kohustuslik on sisestada vastavalt analüüsile.

**Comment by madispold** [comment]
Viga 4: OK.
Ikoonid: OK.

**Comment by birgitpulk** [comment]
Visuaalseid erroreid ei ole, minu poolt ok!
