### ISSUE TITLE
OSKA valdkonna parema veeru toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#496]
**Eesmärk:**
Sisuhalduses saab toimetada põhikutseala „FieldPage“ #450 mallil **sisulehe paremat veergu**.

**Parema veeru elemendid:** 
Disain: - https://zpl.io/2ZzOYOd

Hõivatute arv (number_employed), **vabatahtlik**
- [ ] numbri sisestamise väli, saab sisestada kuni 7-kohalise numbri - muudetud #751 (piirang maas)
- [ ] teksti sisestus kuni 100 tähemärki, **vabatahtlik** - lisaks numbri sisestamisele on vajalik selgitava info kuvamiseks teksti-väli (explanatory text)

Plussid ja miinused (pros_cons), **vabatahtlik**
- [ ] saab lisada kuni 5 plussi ja 5 miinust, teksti sisestus kuni 100 tähemärki
- [ ] sisuhalduses eristatada plusside ja miinuste sisestamine (kuvamisel on erinevad ikoonid)

Ametialad (MainProfession), **kohustuslik**
- [ ] saab lisada kuni n arv põhikutseala, (sisutüüp MainProfessionPage)

Leia kiiresti (Link), **vabatahtlik**  
- [ ] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [ ] jrk nr (SecuenceNo)
- [ ] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [ ] Lingi URL (WebPageAddress)

Sarnased teemad (RelatedPages), **vabatahtlik**
- [ ] saab lisada/ muuta lingid sisulehtedele, vabatahtlik, n arv,
täitmisel on kohustuslik lisada:
   - Sisulehe lingi pealkiri (LinkTitle), maksimaalne pikkus 50
   - Sisulehe lingi viide

Kontakt (Contact), **vabatahtlik**
- [ ] Paremal ääreribal saab olla üks kontakti osa
- [ ] nimi (person), maksimaalne pikkus 50
- [ ] organisatsioon (organization), maksimaalne pikkus 50
- [ ] telefon (phone), telefoni formaat
- [ ] e-post (e-mail), e-maili formaat

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, saab lisada suurema numbri: _Hõivatute arv (number_employed), vabatahtlik numbri sisestamise väli, saab sisestada kuni 7-kohalise numbri_

**Comment by TanelTromp** [comment]
TEST

Korras v.a lingi pealkirja pikkused

Hõivatute arv (number_employed), **vabatahtlik**
- [x] numbri sisestamise väli, saab sisestada kuni 7-kohalise numbri
- [x] teksti sisestus kuni 100 tähemärki, **vabatahtlik** - lisaks numbri sisestamisele on vajalik selgitava info kuvamiseks teksti-väli (explanatory text)

Plussid ja miinused (pros_cons), **vabatahtlik**
- [x] saab lisada kuni 5 plussi ja 5 miinust, teksti sisestus kuni 100 tähemärki
- x ] sisuhalduses eristatada plusside ja miinuste sisestamine (kuvamisel on erinevad ikoonid)

Põhikutsealad (MainProfession), **kohustuslik**
- [x] saab lisada kuni n arv põhikutseala, (sisutüüp MainProfessionPage)

Leia kiiresti (Link), **vabatahtlik**  
- [x] saab lisada kuni n arv välist linki, lisamisel kohustuslik:
- [x] jrk nr (SecuenceNo)
- [ ] Lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [x] Lingi URL (WebPageAddress)

Sarnased teemad (RelatedPages), **vabatahtlik**
- [x] saab lisada/ muuta lingid sisulehtedele, vabatahtlik, n arv,
täitmisel on kohustuslik lisada:
   - Sisulehe lingi pealkiri (LinkTitle), maksimaalne pikkus 50
- [x] - Sisulehe lingi viide

Kontakt (Contact), **vabatahtlik**
- [x] Paremal ääreribal saab olla üks kontakti osa
- [x] nimi (person), maksimaalne pikkus 50
- [x] organisatsioon (organization), maksimaalne pikkus 50
- [x] telefon (phone), telefoni formaat
- [x] e-post (e-mail), e-maili formaat
