### ISSUE TITLE
OSKA valdkonna parema veeru kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#497]
**Eesmärk, üldtingimused:**
Portaali külastaja saab menüü või mõne muu sisulehe lingi kaudu navigeerida „FieldPage“ mallil sisulehele ja tutvuda selle parema veeru sisuga.

**Eeltingimused ja käivitamine:**
- kasutaja navigeerib menüüst „FieldPagae" mallil sisulehele
- BE toimetamise töö on tehtud #496 

**Vastuvõtutingimused:** 
- [ ] Kasutaja näeb lehe paremal serval (kui on sisuhalduses lisatud):
- Plussid ja miinused (pros_cons) 
- Põhikutsealad (MainProfession), üle 5 peita nupu alla (vt disaini)
- Hõivatute arv (number_employed)
- Leia kiiresti (Link), üle 5 peita nupu alla (vt disaini)
- Sarnased teemad (RelatedPages), üle 5 peita nupu alla (vt disaini)
- Kontakt (Contact)

Disain: - https://zpl.io/2ZzOYOd

- [ ] Kui mõni teema või mittekohustuslik väli on sisestamata siis ei kuvata nö auku, vaid sisestatud teemad kuvatakse järjest.

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by madispold** [comment]
Testimisse @TanelTromp 
http://htm.twn.ee/et/valdkonnad/pilet496 on detailvaade andmetega.

**Comment by TanelTromp** [comment]
Viga 1: sotsiaalmeedia nupp ei ole avatav (kõik brauserid)

**Comment by TanelTromp** [comment]
TEST

- [x] Vastuvõtutingimused:

    Kasutaja näeb lehe paremal serval (kui on sisuhalduses lisatud):
    Plussid ja miinused (pros_cons)
    Põhikutsealad (MainProfession), üle 5 peita nupu alla (vt disaini)
    Hõivatute arv (number_employed)
    Leia kiiresti (Link), üle 5 peita nupu alla (vt disaini)
    Sarnased teemad (RelatedPages), üle 5 peita nupu alla (vt disaini)
    Kontakt (Contact)

- [x] Kui mõni teema või mittekohustuslik väli on sisestamata siis ei kuvata nö auku, vaid sisestatud teemad kuvatakse järjest.

**Comment by birgitpulk** [comment]
- [ ] Näita rohkem klikkides võiks alla tekkida "Näita vähem" nupp
- [ ] Põhikutsealad kastis kui link muutub mitmerealiseks, siis võiks järgmine rida hakata esimese rea tekstiga samast kohast (mitte ikooni alt)
- [ ] Kontakti kastis peaks e-mailil mitte olema joon all (hoveriga tuleb joon)

**Comment by madispold** [comment]
Viimased 3 punkti: OK.

**Comment by birgitpulk** [comment]
Teistele linkidele peaks ka hoveriga joon alla tekkima @madispold
