### ISSUE TITLE
infograafika kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#498]
**Eesmärk, üldtingimused:**
„MainProfessionPage“ , FieldPage"  ja Survey ning ResultPage mallil sisulehel saab kasutaja vaadata infograafikat.

**Eeltingimused ja käivitamine:**
- realiseeritud on eelnevalt nimetatud sisutüüpide toimetamine.
- kasutaja navigeerib menüüst „MainProfessionPage“ või FieldPage" või SurveyPage või ResultPage mallil sisulehele.

**Kujundus**
Värvipalett (15tooni): [Disaini link](https://zpl.io/VQEGlN5)
Font ja fondi suurus graafikutel (kui on võimalik muuta): Rubik Light, 14px, #333333
Jooned graafiku all (kui on võimalik muuta): #C7C7C9, 1px

**Vastuvõtutingimused:**
- [ ] Kasutajale kuvatakse lehekülje sisu osana infograafikat - Google charts põhjal
- [ ] Kuvatav (või mitu) diagrammi andmed - #492 

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by EgleM-TW** [comment]
[OSKA_naidis_andmestik-121018.txt](https://github.com/hariduspilv/haridusportaal/files/2472144/OSKA_naidis_andmestik-121018.txt)

**Comment by EgleM-TW** [comment]
Testimiseks:
CSV sisse tõmmata, andmed https://github.com/hariduspilv/haridusportaal/blob/master/docs/testimiseks_infograafika.csv ja Sharepointis.

1. Sisuhaldur saab:
-  [ ] valida diagrammi nime
näitaja = Käive
-  [ ] valida filtri väärtused
valdkond = Personali- ja administratiivtöö ning ärinõustamine
alavaldkond = Juhtimisalane nõustamine
pohikutseala = 0
periood = 0
-  [ ] valida x-telje väärtuse (x-telg valitakse filtritest (valdkond, alamvaldkond, põhikutseala, silt, periood)
X = periood
-  [ ] valida graafiku tüübi 
Graafik = bar chart/ 

Testida ka teiste tüüpidega:
   - line chart
   - bar chart
   - column chart
   - pie chart
   - doughnut chart

Testida ka kombineeritud graafikut:
2. Sisuhaldur saab:
-  [ ] valida teise diagrammi nime
Näitaja = PAÄ valdkonna osakaal ettevõtluse käibest
-  [ ] valida graafiku tüübi 
piirangud: 
   - kui valis line chart, saab valida, bar chart 
   - kui valis bar chart, saab valida line chart
   - kui valis column chart, ei saa teist graafikut lisada
   - kui valis gauge chart, ei saa teist graafikut lisada
   - kui valis pie chart, ei saa teist graafikut lisada
   - kui valis doughnut chart, ei saa teist graafikut lisada

**Comment by skeefee** [comment]
http://htm.twn.ee/et/ametialad/teabe-ja-dokumendihalduse-spetsialistid

**Comment by TanelTromp** [comment]
VIga 1: ei kuva infograafika nime välja:
![pilt](https://user-images.githubusercontent.com/37407917/48257538-700dc280-e41b-11e8-9d01-5f463eee7b42.png)

**Comment by EgleM-TW** [comment]
@TanelTromp uuendasin test case - vt ülal (3 testi)
Infoks, et csv import toimis kenasti (sh lisasin mõne uue valdkonna taksonoomiate alla)
@lsoonvald kontrollib üle, kas csv andmed on ikka salvestatud. Ja 11.11.18 seisuga ei õnnestu sisuhaduses lisada infograafikat (dok haldurite ametiala vaates). Laseb teha ainult esimese valiku (simple, combo, multi) ja edasi ei liigu.

**Comment by TanelTromp** [comment]
Viga 2: väli "silt" puudu infograafika lisamisest

**Comment by lsoonvald** [comment]
Viga 2: Fixed.

**Comment by EgleM-TW** [comment]
Viga 3: x-telje valikus puudub "silt". Nõue piletis #537

**Comment by EgleM-TW** [comment]
BE Viga 4: Silt tõlkida Silt, mitte Nimetus 👎

**Comment by EgleM-TW** [comment]
@skeefee Kui on Combo graafik, siis peab kuvama ka teist telge lähtuvalt teise graafiku andmetest.

**Comment by EgleM-TW** [comment]
@skeefee @lsoonvald 
Graafiku lisamine OSKAFieldPage lehele ei toimi.
Lisasin graafiku uuele valdkonna lehele: http://htm.twn.ee/et/valdkonnad/hariduse-valdkond
Lisasin graafiku olemasolevale valdkonna lehele: http://htm.twn.ee/et/valdkonnad/pollumajandus-ja-toiduainetoostus
Tulemus: graafikut ei kuva.
Oodatav tulemus: kuvab lisatud graafikut.

**Comment by EgleM-TW** [comment]
MainProffessionPage (ametiala) toimis simple graafiku lisamine: test nr 1: http://htm.twn.ee/et/ametialad/operaatorid

**Comment by lsoonvald** [comment]
BE Viga 5: Parandasin järjekorda, nüüd peaks korras olema.

**Comment by skeefee** [comment]
@Egle
“Graafiku lisamine OSKAFieldPage lehele ei toimi.”
- Korras

“Graafiku lisamine OSKAServeyPage lehele ei toimi.”
- Korras

**Comment by skeefee** [comment]
vAxis ja hAxis lisatud

**Comment by EgleM-TW** [comment]
Testisin: http://htm.twn.ee/et/valdkonnad/pollumajandus-ja-toiduainetoostus
Jama - 
![jama](https://user-images.githubusercontent.com/23524151/48865528-87b05800-edd8-11e8-83ad-13834d6ccedd.png)

**Comment by EgleM-TW** [comment]
@skeefee 👎

**Comment by EgleM-TW** [comment]
Seis: teist Y telge kuvada ei õnnestu - võimalik lahendada selles piies: https://google-developers.appspot.com/chart/interactive/docs/gallery/combochart
Seega tuleb csv paremini ettevalmistada, et andmed oleksid samas skaalas.

**Comment by TanelTromp** [comment]
TEST

**Ametiala**

1. test
-  [ ] Valida graafiku tüübi: Simple
-  [ ] Lisada diagrammile nimetuse (title): Mis iganes nimetus
-  [ ] Valida graafiku tüübi 

- [ ]      line
- [ ]      bar
- [ ]     column
- [ ]     pie
- [ ]     doughnut

-  [ ] Valida näitaja: Hariduslik jaotus
-  [ ] Valida x-telje: silt 
-  [ ] valida filtri väärtused: 
-  [ ] Valdkond = Rõiva-, tekstiili- ja nahatööstus
-  [ ] Ametiala = õmblejad (1 valida, aga võib valida ka teisi ametialasid, näieks: rätsepad, operaatorid, tehnikud)
-  [ ] Silt = üldkeskharidus, kutseharidus, rakenduskõrgharidus, bakalaureus ja magistrantuur, doktorantuur

**Comment by TanelTromp** [comment]
TEST

**2. test**
-  [ ] Valida graafiku tüübi: Combo
-  [ ] Lisada diagrammile nimetuse (title): Mis iganes nimetus
-  [ ] Valida graafiku tüübi: bar
-  [ ] Valida näitaja: Käive 
-  [ ] Valida x-telje: Periood
-  [ ] valida filtri väärtused: 
-  [ ] Valdkond = Rõiva-, tekstiili- ja nahatööstus
-  [ ] Alavaldkond = Nahatööstus
-  [ ] Periood = 2005/07, 2006/08, 2007/09, 2008/10

**Comment by TanelTromp** [comment]
TEST

**3.test**

-  [ ] Valida graafiku tüübi: Multi
-  [ ] Lisada diagrammile nimetuse (title): Mis iganes nimetus
Valida graafiku tüübi: 
-  [ ] column
-  [ ] bar
-  [ ] line

-  [ ] Valida näitaja: Keskmine palk
-  [ ] Valida x-telje: periood 
-  [ ] Määrata grupeeringu: valdkond
-  [ ] valida filtri väärtused: 
   - Valdkond = Töötlev tööstus, Põllumajandus
   - periood (2005/07, 2006/08, 2007/09, 2008/10)


**Column**
![pilt](https://user-images.githubusercontent.com/37407917/48937976-7a9a8280-ef18-11e8-9a96-c6377beff878.png)

**Bar**

**Comment by TanelTromp** [comment]
Vearaport (testisin hetkel Ametiala ja http://htm.twn.ee/et/ametialad/operaatorid)

Viga 1: Graafiku tüüp simple: doughnut ja pie näevad samad välja

Viga 2: graafiku tüüp multi: töötab ainult "column" valik. "Pie" ja "Line" ei tööta - jätab Columniks.

**Comment by skeefee** [comment]
Viga 1: Testitud ja täitsa töötavad.  Ühel on auk sees teisel pole
Viga 2: Combot saab ainult bar ja line-ga teha

**Comment by EgleM-TW** [comment]
Viga 2: graafiku tüüp multi: töötab ainult "column" valik. "Pie" ja "Line" ei tööta - jätab Columniks.
Uus pilet #614 , et eemalda multi valikust line tüüp.

**Comment by EgleM-TW** [comment]
Testitud valdkonna sisutüübil: https://i.gyazo.com/c87b13e8129262504e16563cb80f9a5c.png

**Comment by EgleM-TW** [comment]
Testitud valdkonna sisutüübil: https://i.gyazo.com/f12065f655e8a00862b25f96532787d2.png
Sisuhalduses valitud x-teljeks periood ja näitaja keskmine palk. 
Tulemus- viga:  x ja y telg on vahetuses.

**Comment by EgleM-TW** [comment]
Testitud: https://i.gyazo.com/d68fe9a455bc49a5b5a9bd7d8ebf72fa.png

Oluline on CSV importimisel ka perioodi järjekord (nt 2009;2010;2011), kuvatakse vastavalt imporditud andmetele!
