### ISSUE TITLE
OSKA tulemused LK kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#501]
**Eesmärk, üldtingimused:**
Portaali külastaja saab menüü või mõne muu sisulehe lingi kaudu navigeerida „ResultPage“ mallil sisulehele ja tutvuda selle sisuga. Eesti keeles "OSKA tulemused"

Disain: https://zpl.io/VQEgxzm

**Eeltingimused ja käivitamine:**
- realiseeritud on piletid #500  (sisu toimetamine) ja #473 
- kasutaja navigeerib menüüst „ResultPage“ mallil sisulehele

**Vastuvõtutingimused:**
- [ ] Kasutajale kuvatakse lehekülje sisu, sh parem veerg (kui on lisatud).
- [ ] Kasutaja saab sisulehekülge jagada sotsiaalmeedias. Nupp, mille alt avanevad valikud FB ja Twitter - vt realiseeritud varem #36 .
- [ ] Kasutaja saab lk lemmikuks lisada - #285 (võib realiseerida ka #525 raames)
- [ ] Kasutaja saab lisatud faili (MS Excel) alla laadida
- [ ] Kasutaja saab kuvatud tabelit kerida - vt disaini
Infograafika kuvamine testida piletiga: #498 
Tabeli filter on eraldi tööna #510 

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Viited:
BE #500  
Filter #510

**Comment by madispold** [comment]
Testimisse @TanelTromp 
Tabelite veerud ja nende järjestuse võtsin piletist #473, mitte kujundusest. Esineb erinevusi.

**Comment by madispold** [comment]
http://htm.twn.ee/et/oska-tulemused/oska-sisuleht-pilet500-kogu-sisuga-pikk-50-kool-ek

**Comment by TanelTromp** [comment]
TEST

testlugu: http://htm.twn.ee/et/oska-tulemused/oska-sisuleht-pilet-500be-ja-501fe

Viga 1: õhku pealkirja ja sisu vahele (@birgitpulk kinnitab):

![pilt](https://user-images.githubusercontent.com/37407917/48071247-82e98280-e1e2-11e8-8e2a-69f9d6678bcc.png)

Muudatuse ettepanek 1: Exceli allalaadimisnupu välimuse/asukoht loogika muutmine. Hetkel otsisin jupp aega, et kus see on. Lisaksin ise teksti kõrvale, a`la "Lae tabel alla". Tooltip hover oleks ka variant aga see ei päästaks nupu enda leidmist, vaid annaks infot, et "Mida ma nüüd vajutasin"? @birgitpulk 

![pilt](https://user-images.githubusercontent.com/37407917/48071394-e1166580-e1e2-11e8-963b-4bc8663dad70.png)

**Comment by birgitpulk** [comment]
Muudatuse ettepanek 1: Olen nõus, asendame ikooni lingiga "Lae tabel alla" ja paigutame ta tabeli kohal vasakule poole.

**Comment by madispold** [comment]
@TanelTromp 
Viga 0: OK.
Viga 1: "Lisainfo" plokk tehtud valdkonna vaate "Hõivatute arv" ploki põhjal. Viimase leiab nt. siit: htm.twn.ee/et/valdkonnad/pollumajandus-ja-toiduainetoostus - OK.
Muudatuse ettepanek 1: OK.
Viga 2: OK
Viga 3: OK.
Viga 4: Kuna kirjelduse i.e description väli tühi, siis kasutab faili nime välja ja selleks on konkreetsel vaatel "Copy of ....", lisasin ette selgitava "Lae alla: {{nimi}}" - OK.
Viga 5: OK.
Viga 6: OK.
Viga 7: Rohkem kuvades viib fookuse, "Näita vähem" puhul hetkel ei pannud - OK.

**Comment by birgitpulk** [comment]
Miks "Valdkond" on tabelis link? @TanelTromp @madispold 

Muudatuse ettepanek 2: Ei saa, läheb vastuollu WCAG-ga. See noolte teema on mul tuleviku parandustes kirjas, seega ma jätaks selle sinna. @TanelTromp

**Comment by TanelTromp** [comment]
Muudatus 1: jääta sorteerimisel ainult nooled linkideks ja eemaldada labelite alt "link" käitumine. Birgitiga räägitud

Viga 7: ikka valesti: peab viima fookuse esimesele lisatud teemale, mitte viimasele avatud teemale. Ehk: Kui "valla palla" oli peidus ja esimene, mis "Näita rohkem" puhul ilmub, siis peab fookuse viima sellele, mitte "Odio Utinam".
![pilt](https://user-images.githubusercontent.com/37407917/48182408-b38d0180-e333-11e8-8b9c-a9ea8e526431.png)

**Comment by madispold** [comment]
Muudatus 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

**Vastuvõtutingimused:**
- [x] Kasutajale kuvatakse lehekülje sisu, sh parem veerg (kui on lisatud).
- [x] Kasutaja saab sisulehekülge jagada sotsiaalmeedias. Nupp, mille alt avanevad valikud FB ja Twitter - vt realiseeritud varem #36 .
- [x] Kasutaja saab lk lemmikuks lisada - #285 (võib realiseerida ka #525 raames)
- [x] Kasutaja saab lisatud faili (MS Excel) alla laadida
- [x] Kasutaja saab kuvatud tabelit kerida - vt disaini
