### ISSUE TITLE
Täpsustada WYSIWYG redaktoris tabeli lisamise võimalusi

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#504]
Klient soovib sisulehele lisada keerukaid tabeleid, et saaks andmeid grupeeritult kuvada.
Teema tõstatus 01.10 OSKA teemade planeerimisel. Jäi nii, et selgitame, mis võimalusi drupal tabelite lisamisel lubab. 

Näidiseks töölaual tabelite vaated.

WYSIWYG redaktori töö: #15

**Comment by andrussarv** [comment]
Nõuet pole. Basic tabel jääb. Keerukad tabelid vajavad kujundust ja lisaarendust.
