### ISSUE TITLE
Ametialade (põhikutsealade) nimekirja filtreerimine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#505]
**NB! põhikutseala = ametiala**

Jätk tööle #487 
Disaini link: https://zpl.io/2jwB4KA

Vastuvõtutingimused:
- [ ] märkeruudu alusel, fixedLabel - vt disainis

- [ ]  Sorteerimise valikud:
Näitaja nimetus - väiksemast suuremaks
Näitaja nimetus - suuremast väiksemaks

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1: selliste valikute puhul jookseb päring kokku:
https://gyazo.com/ec7abee5dea67d616a06d3316b6a2e0e

Viga 2: kui teha kitsamas otsingus päring, siis kaotab osade väljade nimed ja väljad:
https://gyazo.com/89dcd1f8f95b8b0c87cfafb093129e73
https://gyazo.com/65c8123b16e2c5fa565086c1237e0b27

Täpsustus 1: kui otsing kokku jookseb, siis kuidas kasutaja saab otsingu katkestada mõistlikult?

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.
Täpsustus 1: Nüüd peaks olema loodud olukord, kus ei ole võimalik lehel "laadima" jääda - ideaalis toimiks nõnda.

**Comment by TanelTromp** [comment]
Viga 3: lisada võimalusel autoskroll mobiilivaates filtreerimis tulemustele, et snackbar ei varjaks neid

**Comment by madispold** [comment]
Viga 3: OK.
Lisaks: Jääb hetkel sorteerimine töötama filtrina (Andruse ja Birgitiga kokkulepe).

**Comment by TanelTromp** [comment]
TEST OK


- [x] märkeruudu alusel, fixedLabel - vt disainis

Sorteerimise valikud:

- [x] Näitaja nimetus - väiksemast suuremaks
- [x] Näitaja nimetus - suuremast väiksemaks

**Comment by birgitpulk** [comment]
Kujunduse osas ok!
