### ISSUE TITLE
OSKA ametiala (põhikutseala) näitajate import ja sidumine sisuga

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#506]
**NB! põhikutseala = ametiala**

**Eesmärk:**
Sisutüübi „MainProfessionPage“ paremas veerus kuvatakse portaali külastajale näitajaid, mille andmeid uuendab sisuhaldur CSV-st. Selle töö raames lahendada CSV-st andmete import ja andmete sidumine põhikutseala taksonoomiaga.

Teine töö on parema veeru toimetamiseks sisutüübi sidumine taksonoomiaga #494  osana.

1. Sisuhaldaja avab faili.
Fail on CSV fail, kus:
- veergude eraldaja on semikoolon ( ; ), 
- failis on päiserida (naitaja;pohikutseala;vaartus) 

2. Faili kontroll:

Faili iga rida kontrollida järgmiselt - kui reas on täidetud üks veerg, siis on ka teised veerud kohustuslikud.
- kas esimeses veerus on naitaja, string
- kas teises veerus on põhikutseala: kas on olemas sisu Põhikutseala, mille väärtus
võrdub failist saadava väärtusega
- kas kolmandas veerus on väärtus, string

Kui ilmneb viga, siis protsess katkestada ja kuvada faili rea number ja veateade ("Puudub naitaja", "Puudub põhikutseala", "Puudub vaartus").

3. Salvestada failist loetavad põhikutseala näutajad. Faili iga rida salvestada:
- naitaja 
- pohikutseala
- väärtus

**Comment by lsoonvald** [comment]
http://test-htm.wiseman.ee:30000/et/admin/structure/oska_indicator_entity

**Comment by TanelTromp** [comment]
Viga 1: ei anna õige välja sisuga veateadet, kui "Põhikutseala" veerus on vale väärtus:
https://gyazo.com/1e20654727a2f592e9925c0a073f53c3

**Comment by lsoonvald** [comment]
Viga 1: Täiendasin veateadet veeru nimega.
Viga 1.2: Lisatud kontrolle näitaja ja väärtuse väljale

Viga 2: Sain importida CSV'd sisuga:
naitaja;pohikutseala;vaartus
näitaja2;Põhikutseala koos parema veeruga;200
näitaja3;Põhikutseala koos parema veeruga;300
näitaja1;Oska main profession testimiseks;100
näitaja2;Oska main profession testimiseks;5000
näitaja3;Oska main profession testimiseks;600
