### ISSUE TITLE
OSKA valdkondade kuvamisel hall modaal

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#507]
Jätk tööle: #476 ja #624 

**Üldkirjeldus:**
Kuvada valdkonna nimistus modaali, et kasutaja saaks ülevaatlikult leida huvipakkuva ametiala.
Disain: https://zpl.io/VOkO6B1 ja mobiilis: https://zpl.io/anKRGXr

**Eeltingimused ja käivitamine:**
- Valdkondade nimekirja nägemiseks kasutaja valib menüüst: OSKA → Valdkonnad. 

**Vastuvõtutingimused:**
- Kui kasutaja vajutab "nimekirjas" pildile või valdkonna nimetusele, avaneb modaal.
- Modaali saab sulgeda.
- Saab liikuda valdkonna detailvaatesse või lisatud ametiala sisulehele.
- Saab käivitada video
- Kui videot pole valdkonna lehele lisatud, kuvada video asemel lehele lisatud fotot. Kui kumbagi pole sisestatud kuvada foto palce holder (Hallil taustal nõutava pildi suurus - http://htm.twn.ee/valdkonnad)

Modaalis kuvatakse valdkonna detailvaatest:
- disainis "Valdkonna üldinfo" asemel lihtsalt "Üldinfo" ja allpool "Valdkonna põhikutsealad" asemel lihtsalt "Ametialad"
- valdkonna nimetus (filed title)
- sissejuhatav tekst (introduction) - _Üldinfo_ 
- video (video), kui puudub siis lisatud foto (picture), kui puudub siis foto paldeholder.
- ametialad (MainProfession), kuvame tähestikulises järjekorras, vasakult paremale kohe kolmes tulbas, et ei jääks tühja kahte tulpa, kui neid on vähem.

Seosed:
valdonna kuvamine: #451 ja #624 
nimisitu: #476

**Comment by RainLeoma** [comment]
Sobib!

Küsimus: "ametialad (MainProfession) (sisestatakse parema veeru alla), kuvame sisestuse järjekorras" kas see tähendab lehtede loomise järjekorda? Kas loogilisem poleks tähestiku järjekorras? Meil endal on olemas ka igale valdkonna ametialale sisemine hierarhiline vaade (Juhid->tippspetsialistid->spetsialistid->oskustöötajad->lihttöölised). Mõistan, et selle loomine ja haldamine pole mõistlik, vähemalt mitte praegu. Kasutajale võiks järjekord tunduda kuidagigi loogiline.

**Comment by EgleM-TW** [comment]
@RainLeoma Ametialad on valdkonna sisutüübile lisatud ja sealt neid kuvatakse modaalis. Kui te sisestate ametialad sisemise hierarhia alusel, siis modaalis sisestuse jrk kuvamine peaks olema ok. Aga võime ka tähestikuliselt. Kuidas jääb?

**Comment by heldiraudsepp** [comment]
FE - 24h
Test - 10h

**Comment by TanelTromp** [comment]
Viga 1: kui ei ole täisrida valdkondi ja on alumine rida, siis modaal ei tööta:

https://gyazo.com/cefe76729b6b1796a27fb9fc944f4774

**Comment by EgleM-TW** [comment]
Muudetud nõue: sissejuhatav tekst kuvatakse kogu mahus (kuni 300 tähemärki) ja Loe rohkem nupp jääb ära.

**Comment by heldiraudsepp** [comment]
FE - tuleb juurde lingi muudatus 7h
Test - 5h
Disaini test - 1h

**Comment by skeefee** [comment]
Viga 0: korras
Täpsustus 1: Korras
Täpsustus 2: Korras
Viga 1: Korras
Viga 2: Korras
Viga 3: Korras
Viga 4: Korras
Viga 5: Korras
Viga 6: Korras
Viga 7: Korras
Viga 8: Korras 
Viga 9: Korras
Viga 10: BE kontrollitav
Viga 11: Korras
VIga 12: Korras
UX täiendus: See on okei
Ux täiendus 2: See on okei
WCAG 1: Peaks korras olema
WCAG 2: Korras
WCAG 3: H2 pealkirju võib mitu olla
WCAG 3.1: Korras
WCAG 4: Korras
WCAG 5: Korras

**Comment by lsoonvald** [comment]
Viga 10: Korras.

**Comment by TanelTromp** [comment]
Viga 13 uus: vertikaalsel ja alumisel joonel border 1.5 solid aga ülemisel solid 3px:

![pilt](https://user-images.githubusercontent.com/37407917/55887686-9d22f480-5bb6-11e9-8039-616a43727fa7.png)

**Comment by skeefee** [comment]
Viga 13 uus: alumistele joontele pandud 2px laiust. 1.5px ei ole võimalik panna
Viga 14 uus: Testitud nii maci kui windowsi peal erinevate brauseritega. Palun täpsusta vea tekkimist
Viga 15 uus: Korras
Viga 16 uus: korras
Viga 17 uus: Korras
Viga 18: Ootame Birgiti inputi
WCAG 6: Ei pea lugema pildi alti ette. See grid on linkide nimekiri. Pildi infot saab modaali seest.
WCAG 5: Korras

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Eeltingimused ja käivitamine:
    Valdkondade nimekirja nägemiseks kasutaja valib menüüst: OSKA → Valdkonnad.

Vastuvõtutingimused:

   

- [x] Kui kasutaja vajutab "nimekirjas" pildile või valdkonna nimetusele, avaneb modaal.
- [x]  Modaali saab sulgeda.
- [x] Saab liikuda valdkonna detailvaatesse või lisatud ametiala sisulehele.
- [x] Saab käivitada video
- [x]  Kui videot pole valdkonna lehele lisatud, kuvada video asemel lehele lisatud fotot. Kui kumbagi pole sisestatud kuvada foto palce holder (Hallil taustal nõutava pildi suurus - http://htm.twn.ee/valdkonnad)

Modaalis kuvatakse valdkonna detailvaatest:

- [x]  disainis "Valdkonna üldinfo" asemel lihtsalt "Üldinfo" ja allpool "Valdkonna põhikutsealad" asemel lihtsalt "Ametialad"
- [x]   valdkonna nimetus (filed title)
- [x]   sissejuhatav tekst (introduction) - Üldinfo
- [x]   video (video), kui puudub siis lisatud foto (picture), kui puudub siis foto paldeholder.
- [x]  ametialad (MainProfession), kuvame tähestikulises järjekorras, vasakult paremale kohe kolmes tulbas, et ei jääks tühja kahte tulpa, kui neid on vähem.

**Comment by lsoonvald** [comment]
Viga 0: Korras.
