### ISSUE TITLE
Koolitusel ilmnenud puudused

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#508]
- [x] Pildi üleslaadimisel peale spinner ikooni kadu on puudu teavitus protseduuri ebaõnnestumisest - https://github.com/hariduspilv/haridusportaal/issues/509
- [x] Admin vaate tõlked on puudu: nt _event groups manager, content limited to, set map_ jt - neid tõlkeid ei ole, sest kasutame ametlikult tõlgitud Drupalit, kus need puuduvad veel. Meie poolt on tõlgitud ainult meie poolt juurde loodud sisu
- [x] Artiklite tabelvaates termin 'autor' ei ole korrektne, peab olema 'avaldaja' - _muudetud (Lars)_
- [x] Sündmuse lisamisel väljade kohustuslikkuse tärnid ei vasta tegelikkusele - material design admin teemast tulenev
- [x] Tanel: veateated ei anna täna veel õigeid sõnumeid - info saab kätte kasutusjuhendist
- [x] Sündmusel hover ei kuva nime kalendri vaates kui on lõigatud tekst - parandatud
- [x] Sündmusel ei kuvata paremal pool kuupäeva, kuigi see on küljes: https://test.edu.ee/et/sundmused/eva-hitsa-sundmus - _korras_
- [x] Tekstiredaktoris muuta _Pealkiri 3_ nimetus > _Pealkiri_ (Vajab lisaarendust, ei saa niisama lihtsalt muuta)
- [x] Osa avaldatud sündmuseid on näha ainult nimekirja vaates aga mitte kalendris, nt 4.10 edu koolitus - parandatud
- [x] Lehe avaldatuse staatus (sisse/välja) pole näha ja Salvesta/Eelvaate nupu hetke paigutus halb - _Lisatud **Avaldatud** nupp_, nuppude asukohti ei saa muuta
- [x] Admin liidese overlay ei tööta veel live lehe peal, lisapäis ja muutmise nupp sisu juures puudu - voimalik teha lisatööna
- [x] Eelvaade ei vasta veel tegelikkusele (nt lehe kujundus ja pildid puudu) - https://github.com/hariduspilv/haridusportaal/issues/585 ja https://github.com/hariduspilv/haridusportaal/issues/607
- [x] Drupali malli vormindus / nupud katki eelvate režiimis![image](https://user-images.githubusercontent.com/16906555/46461229-da04cd80-c7c6-11e8-9731-eb4a2c33b614.png) - tuleneb material admin vormist
- [x] Sündmuse eelvaatest tagasiliikumine eelvaate nupu abil ei toimi: 
![image](https://user-images.githubusercontent.com/16906555/46462380-f7876680-c7c9-11e8-8ea7-833b2802bc73.png)
- [x] paljude failide üleslaadimisel vajalik lahendus, kus leht ei koosneks vaikimisi pikast failijorust - lisaarendus
- [x] Video lisamine ei toimi - Video lisamine enam viga ei anna

**Comment by heldiraudsepp** [comment]
@erkkijakobson Palun vaata üle, ootab juba pikemat aega tagasisidet
