### ISSUE TITLE
Veateadete kuvamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#509]
**Eesmärk**
Kui lehel esineb tehniline viga, siis süsteem kuvab snackbari koos inimloetava teatega. 

**Vastuvõtutingimused**
Täiendada http päringuid selliselt, et vigase päringu korral, kuvab süsteem punase snackbari koos teatega "Tehniline viga. Proovi uuesti!"

Dsain: https://zpl.io/adPdKAe

**Comment by birgitpulk** [comment]
Kas selle pileti raames on vaja kujundada ka küpsiste ehk cookie'de teavitus? @heldiraudsepp

**Comment by heldiraudsepp** [comment]
@birgitpulk cookie'de jaoks võiks teha eraldi pileti

**Comment by birgitpulk** [comment]
@erkkijakobson  Palun kinnitust kujundusele: https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5bf415adfbd7ff56b8948495

**Comment by erkkijakobson** [comment]
veateate _snackbar_ sobib

**Comment by birgitpulk** [comment]
@erkkijakobson  Heldi täpsustas, et sai vist kokku lepitud, et jäävad nii nagu nad on

**Comment by heldiraudsepp** [comment]
Kui lehel esineb tehniline viga, nt mingi teenus ei tööta, siis süsteem kuvab punase snackbari koos teatega "Tehniline viga. Proovi uuesti!"

**Comment by priitpu** [comment]
Teavituste süsteemi hetkel kasutatakse isikukaardi päringute veateadeteks ning üldisteks staatus 0 ning staatus 404 päringute veateadeteks. Globaalsete veateadete tekste hetkel palun mitte vaadata väga terava pilguga.

**Comment by TanelTromp** [comment]
Täiendus 1: veateade võiks olla tõlgitud:

![pilt](https://user-images.githubusercontent.com/37407917/54813661-ba8b2f80-4c96-11e9-992f-3fe5d824a8d5.png)

**Comment by birgitpulk** [comment]
Ametiala võrdluse snackbar võiks olla 100% lai

![Screenshot 2019-03-26 at 15.30.47.png](https://images.zenhubusercontent.com/5af048384b5806bc2bd2095b/2cd38bcb-b0f3-40eb-a109-959f089cafb1)

**Comment by priitpu** [comment]
> Viga 1 WCAG: ekraaniluger ei loe ette ilmunud veateadet modaalis ("alert")

Parandatud

> Viga 2: veateade võiks olla tõlgitud

@lsoonvald Saada back-endist staatus, kui on võimalik praegu tuleb inglise keeles tekst.

> Viga 3: veateadete kuvamine liiga hunnikus mobiilis

@birgitpulk

![image](https://user-images.githubusercontent.com/17040443/55333449-0f515600-54a0-11e9-82da-4d475ad75bc9.png)

[] Kaardistada mis teavitusi veel võib olla? Suletavad, mittesuletavad, lingiga jne

**Comment by priitpu** [comment]
@TanelTromp 

Hetkel kasutuses olevad teavitused läbi teavitustemooduli

1. Ühenduse katkemine/puudumine
![image](https://user-images.githubusercontent.com/17040443/55334752-84be2600-54a2-11e9-9125-f15365aaa620.png)

2. Töölaua 'õpin' sakk, kui andmeid ei ole
![image](https://user-images.githubusercontent.com/17040443/55334801-a7e8d580-54a2-11e9-85b0-b63ee1527b4d.png)

3. Töölaua õpetan sakk, kui andmeid pole
![image](https://user-images.githubusercontent.com/17040443/55334857-c18a1d00-54a2-11e9-9ecb-c1bc883e3e28.png)

4. Isikuandmed modaal, kui andmeid pole
![image](https://user-images.githubusercontent.com/17040443/55334894-d4045680-54a2-11e9-9a40-2cdbe39ae37b.png)

Ning üks kuskil @lsoonvald kasutatud ka.

Loodetav lõpptulemus on, et igal pool kasutatakse teavituste moodulit, e. olemasolevad teavitused mis pole tuleks järk-järgult ümber teha ning tulevikus ainult läbi mooduli teavitada

**Comment by lsoonvald** [comment]
Viga 2: Korras.

**Comment by TanelTromp** [comment]
Ootab FE-d ja kujundaja @birgitpulk  tegusid.

**Comment by birgitpulk** [comment]
@priitpu 
**Süsteemi teavituste liigid:** 

'Teavituste liigid: 
1. Kollane: hoiatus
2. Roheline: edukas protsess
3. Sinine: info
4. Punane: hoiatus
5. Hall: cookie teavitus

Teavituste suurused: 
1. 100% laiad teavitused (X-ga ja ilma)
2. Sisuosa laiused teavitused (X-ga ja ilma)

Erijuhus:
3. Küpsiste teavitus (100% lai), sisaldab linki ja nuppu

**Comment by TanelTromp** [comment]
Viga uus 3: ei kuva 500 veateadet, vaid loader jääb saagima:
http://htm.twn.ee/valdkonnad/valdkond-mille-pealkiri-maksimum-pikk-100-t%C3%A4hem%C3%A4rki-pealkiri-maksimum-pikk-100-t%C3%A4hem%C3%A4rki

![pilt](https://user-images.githubusercontent.com/37407917/55790668-82248780-5ac5-11e9-9d4f-e9d6720e2d90.png)
