### ISSUE TITLE
OSKA tulemused leheküljel tabeli filtreerimine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#510]
seotud: #501

**Üldkirjeldus:**
Kasutaja saab filtreerida „ResultPage“  sisulehel kuvatud tabelit.
Disaini link: https://zpl.io/VQEgxzm (väljad illustreerivad, kliendilt saabus info hiljem kui tegime disaini)

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud „ResultPage“  sisulehte #501 

**Vastuvõtutingimused:** 
* tabelit saab filtreerida järgmiste tunnuste alusel:
- [ ] Valdkonna nimi 
- [ ] Peavastutaja
- [ ] Ettepaneku staatus
- [ ] Võimalus filtreerida korraga kõiki kolme tunnust.    

* tabelit saab sorteerida järgmiste tunnuste alusel:
- [ ] Valdkonna nimi 
- [ ] Peavastutaja
- [ ] Ettepaneku staatus
- [ ] Võimalus filtreerida korraga kõiki kolme tunnust.    
- [ ] Vaikimisi on tabel sorteeritud Valdkonna lisamise järgi, uuemad ees. 

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

Seosed:
 #501

**Comment by madispold** [comment]
Testimisse @TanelTromp @birgitpulk 
Sorteeritavate väljade kujundus vaja täpsustada, hetkel tabeli päis link ja pealkirja järel nool kas üles või alla olenevalt staatusest.

Test case: http://htm.twn.ee/et/oska-tulemused/valdkonna-nimi

**Comment by TanelTromp** [comment]
Viga 1: ilmselt peaks ka "Enter" otsingu käivitama. Hetkel ainult "Otsi" nupp teeb seda

**Comment by birgitpulk** [comment]
- [ ] "Otsi" nupp peaks olema kitsam, vt nt Eriala detailvaates Sarnased erialad kasti sees on ka taoline Otsi nupp olemas. Need võiksid olla ühesugused

**Comment by EgleM-TW** [comment]
@madispold Muudatus-täiendus:
Filtri väärtused: valdkond, peavastutaja, staatus - korjame väärtused tabelist ja kuvame kasutajale rippmenüüd.

**Comment by madispold** [comment]
@TanelTromp 
Viga 1: Enam pole tekstiväljad ja multivalikul täidab "Enter" juba teist rolli - OK.
Viga 2: OK.
Otsi nupp ja üldse layout muudatus: OK.
Filtri väärtused: valdkond, peavastutaja, staatus muudatus: OK.

@birgitpulk Muudatuse ettepanek 1: Filtrite tühistamise funktsionaalsuse lisamine.

**Comment by TanelTromp** [comment]
Viga 3: rippmenüüdes peaks valikud algama suure tähega nagu tabelis on (hetkel aga "lars ja "staatus")

Viga 4: väike vahe võiks olla valitud ja uuele valikule liikumise hallide kastide vahel - kuidagi error tekib, et mõlemad võivad olla valitud või on üks valik vms @birgitpulk :
https://gyazo.com/92e992575bd7c0fe76bd0bfe43a049f3

**Comment by madispold** [comment]
Viga 3: OK.
Ettepanek 1: Samasugune käitumine Materialis - Ütleks, et OK.
Viga 4: Filtrite ala ei olnud klikitundlik kuna oli liigutatud valikuid allapoole sisetusvälja võrra, taastasin seisu nagu Materialis - Võis olla kokkulepe Sanderi ja Birgiti vahel nii et viide siin ka @birgitpulk just in case.
Viga 5: Vajab täpsustamist.

Angular Material select (https://material.angular.io/components/select/overview)

**Comment by birgitpulk** [comment]
Ettepanek 1: Olen nõus, võiks sinna vahele jätta valge joone lihtsalt ma arvan.

Viga 4: See avanev dropdown peaks olema välja all, kuna praegu varjab ta osaliselt välja pealkirja ja kasutaja ei pruugi mäletada, mida ta valib. Sander mainis, et see muutmine oli paras jamamine. Seal tekkis veel ka probleem, et kui üks valik dropdownist oli tehtud, siis dropdowni teistkordsel avamisel varjas see ikkagi kasti ja pealkirja ära. @madispold, kui raske see muutmine on? 
Aga see loogika, et väljale klikkimine peaks dropdowni sulgema, sellega olen nõus. Iseasi muidugi, et mis see lõplik lahendus meil siis jääb (kas MD enda komponent või proovime selle dropdowni sinna välja alla saada)

**Comment by madispold** [comment]
Ettepanek 1: OK.
Viga 4: Materiali select määrab selle dropdowni asukoha vastavalt langetatud valiku asutusele dropdowni listis, seda ka tingimusel et on ruumi viewportis - vastasel juhul võib määrata mujale. Kui pole midagi valitud on lihtne kogu dropdown x võrra nihutada sisestusvälja alla, kuid järgnevatel avamistel on seda keerukas teha. Pigem ei ole tehtav, kui jääda MD komponendi juurde. Kuid too on default käitumine.
Angular Material select (https://material.angular.io/components/select/overview)

Lisa 1: Sorteerimisel on lisaks sinisele noolekesele, klikitav terve labeli ala ka - Määratud kogu tabeli kast klikitavaks.

**Comment by TanelTromp** [comment]
Viga 5 uus: IE11 see leht ja URL keelduvad töötamast. Brauser jookseb kokku, filtreerimine katki jms

**Comment by madispold** [comment]
Viga 5: OK.
Viga 7: OK.
Viga 6: Eraldi pileti raames.

**Comment by TanelTromp** [comment]
TEST OK


**Vastuvõtutingimused:** 
* tabelit saab filtreerida järgmiste tunnuste alusel:
- [ ] Valdkonna nimi 
- [ ] Peavastutaja
- [ ] Ettepaneku staatus
- [ ] Võimalus filtreerida korraga kõiki kolme tunnust.    

* tabelit saab sorteerida järgmiste tunnuste alusel:
- [ ] Valdkonna nimi 
- [ ] Peavastutaja
- [ ] Ettepaneku staatus
- [ ] Võimalus filtreerida korraga kõiki kolme tunnust.    
- [ ] Vaikimisi on tabel sorteeritud Valdkonna lisamise järgi, uuemad ees.

**Comment by madispold** [comment]
Viga 8: OK.
Viga 9: OK.

**Comment by TanelTromp** [comment]
TEST OK

**Vastuvõtutingimused:** 
* tabelit saab filtreerida järgmiste tunnuste alusel:
- [ ] Valdkonna nimi 
- [ ] Peavastutaja
- [ ] Ettepaneku staatus
- [ ] Võimalus filtreerida korraga kõiki kolme tunnust.    

* tabelit saab sorteerida järgmiste tunnuste alusel:
- [ ] Valdkonna nimi 
- [ ] Peavastutaja
- [ ] Ettepaneku staatus
- [ ] Võimalus filtreerida korraga kõiki kolme tunnust.    
- [ ] Vaikimisi on tabel sorteeritud Valdkonna lisamise järgi, uuemad ees.
