### ISSUE TITLE
Cookie teavitus

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#512]
A) Portaali külastab uus kasutaja, kelle sirviku seadistuses pole määratud aktiivseks Do Not Track:

nõustumiseni on lehel püsiv sinine snackbar: teenus kasutab küpsised sest..., loe lisa>, [nõus]
nupu [nõus] vajutamisel talletame fakti küpsisena ja aktiveerime analüütika küpsised (GA, Plumbr)
LiveChat nupu avamisel paigalab selle skript ka LC küpsise
B) Portaali külastab uus kasutaja, kelle sirviku header teatab, et kasutaja on aktiveerinud DNT:

lehe esmalaadimisel ühtki küpsist (GA, Plumbr, LiveChat vm) ei paigalda ja teavitust ei spämmi
LiveChat avamisel tuleb sulgetav teavitus, et teenus vajab toimimiseks küpsisefaili paigaldamist
nupu [nõus] vajutamisel talletame fakti küpsisena ja aktiveerime LC küpsisega LiveChat teenuse
Taastulija A nõusolekuga saab kohe analüütika, teavituseta LC laetakse mõlemal juhul nupu vajutusel.

**Comment by birgitpulk** [comment]
Millist infot leht salvestab, et cookie teavituse järgi vajadus on? @erkkijakobson

**Comment by birgitpulk** [comment]
@erkkijakobson 
"ükskõik mis muu navigatsiooniklikk=kinnitus" 
Eksib UX reeglite vastu (dark pattern) ning samuti GDPRi raames paika pandud cookie teavituste reeglite vastu: https://www.itgovernance.eu/blog/en/how-the-gdpr-affects-cookie-policies

"Implied consent is no longer sufficient. Consent must be given through a clear affirmative action, such as clicking an opt-in box or choosing settings or preferences on a settings menu. Simply visiting a site doesn’t count as consent.
‘By using this site, you accept cookies’ messages are also not sufficient for the same reasons. If there is no genuine and free choice, then there is no valid consent. You must make it possible to both accept or reject cookies."

**Comment by erkkijakobson** [comment]
A) Portaali külastab uus kasutaja, kelle sirviku seadistuses pole määratud aktiivseks Do Not Track:
- nõustumiseni on lehel püsiv sinine snackbar: _teenus kasutab küpsised sest..., loe lisa>, [nõus]_
- nupu [nõus] vajutamisel talletame fakti küpsisena ja aktiveerime analüütika küpsised (GA, Plumbr)
- LiveChat nupu avamisel paigalab selle skript ka LC küpsise

B) Portaali külastab uus kasutaja, kelle sirviku header teatab, et kasutaja on aktiveerinud DNT:
- lehe esmalaadimisel ühtki küpsist (GA, Plumbr, LiveChat vm) ei paigalda ja teavitust ei spämmi
- LiveChat avamisel tuleb sulgetav teavitus, et teenus vajab toimimiseks küpsisefaili paigaldamist
- nupu [nõus] vajutamisel talletame fakti küpsisena ja aktiveerime LC küpsisega LiveChat teenuse

Taaskülastus A nõusolekuga saab kohe analüütika, teavituseta LC laetakse mõlemal juhul nupu vajutusel

**Comment by birgitpulk** [comment]
@erkkijakobson 
Kas küpsiste teavitus võiks olla ka neutraalsemat tooni kui sinine? ei tahaks sellele nii palju tähelepanu tõmmata ja olen sama praktikat ka paljudes teistes kohtades näinud. 
Kas B variandis võime ehk kuvada sama cookie teavitust või paneme info modaali sisse?

**Comment by birgitpulk** [comment]
@erkkijakobson kujundused lisatud zeplinisse, palun vaata üle ja anna oma tagasiside. 
[Kujundus](https://app.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5bf415adfbd7ff56b8948495)

**Comment by erkkijakobson** [comment]
Neutraalne toon ok, kuid kuju peaks ühtima teiste _snackbar_ teavitustega: mitte olema suurem ega lehe kasutust blokeerivam - ehk siis hall variant neljast värvilisest.

Kui variant B puhul on kasutajale arusaadav mittekäivituva LiveChat akna asemel standardne küpsisenõusoleku riba avanemine, mille OK peale LC aken avaneb, siis võib sama hall _snackbar_ olla.

**Comment by birgitpulk** [comment]
Lehekülje ülesed teavitused on mõeldud samuti täislaiuses, seega see ei erineks teistest teavitustest. Kitsamat teavitust oleme kasutanud dokumendivormide puhul, kui teavitus kehtib konkreetse vormi sammu kohta ja lehekülje-ülesena võib ta jääda arusaamatuks (ehk siis et mis sammu kohta täpselt konkreetne info kehtib). Teeksin ta jah hallile taustale, et ta nii silmatorkav ei oleks kui teised teavitused. 

B variant: @skeefee kas saame LiveChatis kuidagi viidata ka, et kasutaja peab nõustuma küpsistega enne kui see tööle hakkab?

**Comment by heldiraudsepp** [comment]
@erkkijakobson millisel kujul tulevad kasutustingimused?

**Comment by skeefee** [comment]
@birgitpulk  Me saame livechati seni ära peita kuniks kasutaja pole cookiedega leppinud

**Comment by skeefee** [comment]
@TanelTromp  palun testida

**Comment by TanelTromp** [comment]
Täpsustus/olukorrast 1: Chromega htm.twn.ee avades on olemas variant, ei puudu on nii "chat", kui ka "cookies" teavitus.

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Korras
Viga 3: Korras
Viga 4: Korras
UX-täiendus 1: Korras

**Comment by TanelTromp** [comment]
TEST variant:
**B) Portaali külastab uus kasutaja, kelle sirviku header teatab, et kasutaja on aktiveerinud Do Not Track**

Viga 1: Chromega ei kuva LiveChat nuppu

VIga 2:  tinigmus ei ole täidetud, paigaldatud on cookie Do Not Track režiimis: _lehe esmalaadimisel ühtki küpsist (GA, Plumbr, LiveChat vm) ei paigalda ja teavitust ei spämmi_

![pilt](https://user-images.githubusercontent.com/37407917/51326505-f37d0d00-1a77-11e9-9bce-219ff8614fd6.png)

**Comment by skeefee** [comment]
Viga 5: Korras
Viga 6: Korras
Viga 7: See on paratamatus. @birgitpulk  kas saab sinu inputi siin? Snackbari ei saa kahjuks ülesse tõsta.
Viga 1: Korras (kui sul ei ole siis teeme videokõne et saaksin täpselt näha mis sul mureks)

**Comment by TanelTromp** [comment]
Viga 5: endiselt ei õnnestu (nt CNN-s teavitus olemas sama setinguga): https://gyazo.com/94d54af4471111326bd07b3ae95ecf28

Viga 6: NVDA-ga saab liikuda küll Cookies teavitusele aga "Loe kasutustingimusi" ja "Nõustun" nupp on üks element ja loeb need korraga, ette ning ekraanilugeriga "Nõustun" nupule liikumine on väga painer, kui mitte võimatu + VO-ga Cookies teavitust ei taba(ei loe

Viga 8: Tingimus ei ole täidetud: 

B) Portaali külastab uus kasutaja, kelle sirviku header teatab, et kasutaja on aktiveerinud DNT:
    LiveChat avamisel tuleb sulgetav teavitus, et teenus vajab toimimiseks küpsisefaili paigaldamist

**Comment by skeefee** [comment]
Viga 5: Korras
Viga 6: Korras
Viga 8: Kuna chat töötab ilma cookiedeta siis ei ole seda nõudmist vaja täita. See sai varem juba analüütikutega otsustatud.
Viga 9: Korras
Surr-Murr 1: Korras

**Comment by TanelTromp** [comment]
Viga 10 mobiil/tablet "x" paigast ära:

http://htm.twn.ee/s%C3%BCndmused/noorsoot%C3%B6%C3%B6taja-%E2%80%93-kutse-mitte-amet

**Comment by TanelTromp** [comment]
TEST OK

A) Portaali külastab uus kasutaja, kelle sirviku seadistuses pole määratud aktiivseks Do Not Track:

- [ ]     nõustumiseni on lehel püsiv sinine snackbar: teenus kasutab küpsised sest..., loe lisa>, [nõus]
- [ ]     nupu [nõus] vajutamisel talletame fakti küpsisena ja aktiveerime analüütika küpsised (GA, Plumbr)
- [ ]     LiveChat nupu avamisel paigalab selle skript ka LC küpsise *Arendaja kommentaar: _Kuna chat töötab ilma cookiedeta siis ei ole seda nõudmist vaja täita. See sai varem juba analüütikutega otsustatud_*

B) Portaali külastab uus kasutaja, kelle sirviku header teatab, et kasutaja on aktiveerinud DNT:

- [ ]     lehe esmalaadimisel ühtki küpsist (GA, Plumbr, LiveChat vm) ei paigalda ja teavitust ei spämmi
- [ ]     LiveChat avamisel tuleb sulgetav teavitus, et teenus vajab toimimiseks küpsisefaili paigaldamist. *Arendaja kommentaar: _Kuna chat töötab ilma cookiedeta siis ei ole seda nõudmist vaja täita. See sai varem juba analüütikutega otsustatud_*
- [ ]     nupu [nõus] vajutamisel talletame fakti küpsisena ja aktiveerime LC küpsisega LiveChat teenuse

- [ ] Taastulija A nõusolekuga saab kohe analüütika, teavituseta LC laetakse mõlemal juhul nupu vajutusel.

**Comment by skeefee** [comment]
Viga 10: Korras
