### ISSUE TITLE
Täiendada avalehe otsingu tulemuste kuvamist OSKA sisuobjektidega

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#516]
Täiendada avalehe otsingu tulemuste kuvamist OSKA sisuobjektidega.
Täiendada varasemat tööd: #410

BE töö: #515

**Comment by madispold** [comment]
Testimisse.

**Comment by TanelTromp** [comment]
Viga 1: "Kool" chip ei ole selekteeritud/sinine vastava otsitulemuste puhul (vs nt "oska" otsingutulemused):

![pilt](https://user-images.githubusercontent.com/37407917/47339614-6c044580-d6a4-11e8-9678-32dee08f0490.png)

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.

**Comment by madispold** [comment]
@TanelTromp 
Kuvamine tingitud sellest, et kas mahuvad järjestiku tagid kõrvuti või mitte. Konkreetsel juhul ei mahu Ametialad ja Tööjõuprognoos (365px ja alla). Ma ütleks, et see on oodatud käitumine.

**Comment by TanelTromp** [comment]
TEST

OK

**Comment by madispold** [comment]
@birgitpulk Kui vaja siin veel stiilide osas midagi vaadata, kuigi eelmine sprint sai ka vist üle käidud, visuaalseid täiendusi/muudatusi ei tulnud.

**Comment by birgitpulk** [comment]
Stiilide osas vigu ei tuvastanud ehk siis korras!
