### ISSUE TITLE
Regressioontestimine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#517]
Eesmärk: manuaalselt testides teha põhjalikum "suitsutest", et kontrollida kas peamised funktsioonid töötavad.

**Teavituste tellimine**
Kontrollida avalehelt, kas:
- [x] 1. Kasutaja saab valida (märkida) 1 kuni kõik sildid.
- [x] 2. Kasutaja saab sisestada e-posti aadressi, millele teavitusi soovib saada.
- [x] 3. Kasutaja saab kinnitada tellimuse.
- [x] 4. Kasutajale kuvatakse tellimust kinnitavat teadet.
- [x] 5. Kasutaja saab sisestatud e-postile kinnituse e-kirja.
- [x] 6. Kui kasutaja vajutab tellimuse kinnitamise linki, siis kuvatakse haridusportaali URL aadressiga lehte teatega: _Tänud haridusteemade vastu huvi tundmast! Olete edukalt liitunud uudiskirjaga._
- [x] 7. Kas kasutaja saab tühistada tellimust (unsubscribe).

**Avaleht:**
- [ ] Kas avalehte saab lisada? Sisestada sisuhalduses
 "Mis on Eduportaal" bloki pealkiri, lisada teemad, lisada link sisulehele. Märkida avalikuks. 
- [ ] Kas avaleht on korrektne? Vaadata portaalis avalehte, kas on silmatorkavaid vigu.
- [ ] Tõlgete alt kontrollida, kas uudiskirja blokis sissejuhatav tekst on sisuhalduses redigeeritav: 150 tähemärki.
- [ ] Kas saab määrata "Super uudise" koos avaldamise algus- ja lõppkuupäeva ja kellaajaga.
Testida tänasest hilisema kuupäeva lisamist, kontrollida, et super-uudist ei kuvata.

Veel lisada:
Sisse logimine
Otsing avalehelt

**Comment by TanelTromp** [comment]
plaak

**Comment by TanelTromp** [comment]
viag 2:
vasaa 2:



----------------

Arendaja

Viga 1: done

**Comment by TanelTromp** [comment]
**Test avaleht**

Viga 1: Kui "Superuudis" eemaldada, siis vaade on katki:
<img width="1271" alt="capture" src="https://user-images.githubusercontent.com/37407917/47358736-4e020980-d6d3-11e8-9e71-500c1976729c.PNG">

Viga 2: paremal kuvatud uudise pilt avalehel teeb trikke, kui akent sikutada:
https://gyazo.com/ed0f2ccb96e2eb514fcf3869aba0e4d0

**Comment by srautam** [comment]
- [x] Viga 1: Kui "Superuudis" eemaldada, siis vaade on katki desktop:

- [x] Viga 2: paremal kuvatud uudise pilt avalehel teeb trikke, kui akent sikutada:

_Analüütikutega rääkida sel teemal, koosolek_

- [x] Viga 3: pikemate siltide puhul joondused katki, kui akent kokku lükata:

- [x] Viga 4 BE: sissejuhatav tekst peab olema maksimaalselt 150 tähemärki pikk:

_Lars hommikul koosolekul rääkis. Seda ei ole võimalik teha._

**Comment by TanelTromp** [comment]
Viga 5: laptop ja UHD "Uudised" joondus paigast ära:

<img width="1908" alt="capture" src="https://user-images.githubusercontent.com/37407917/47431640-fe8c0e00-d7a4-11e8-88c1-ea2a1731e5ae.PNG">

**Comment by TanelTromp** [comment]
TEST OK

**Teavituste tellimine**
Kontrollida avalehelt, kas:
- [x] 1. Kasutaja saab valida (märkida) 1 kuni kõik sildid.
- [x] 2. Kasutaja saab sisestada e-posti aadressi, millele teavitusi soovib saada.
- [x] 3. Kasutaja saab kinnitada tellimuse.
- [x] 4. Kasutajale kuvatakse tellimust kinnitavat teadet.
- [x] 5. Kasutaja saab sisestatud e-postile kinnituse e-kirja.
- [x] 6. Kui kasutaja vajutab tellimuse kinnitamise linki, siis kuvatakse haridusportaali URL aadressiga lehte teatega: _Tänud haridusteemade vastu huvi tundmast! Olete edukalt liitunud uudiskirjaga._
- [x] 7. Kas kasutaja saab tühistada tellimust (unsubscribe).

**Avaleht:**
- [x] Kas avalehte saab lisada? Sisestada sisuhalduses
 "Mis on Eduportaal" bloki pealkiri, lisada teemad, lisada link sisulehele. Märkida avalikuks. 
- [x] Kas avaleht on korrektne? Vaadata portaalis avalehte, kas on silmatorkavaid vigu.
- [ ] Tõlgete alt kontrollida, kas uudiskirja blokis sissejuhatav tekst on sisuhalduses redigeeritav: 150 tähemärki. **Ei ole võimalik tõlkemoodulist piirata**
- [x] Kas saab määrata "Super uudise" koos avaldamise algus- ja lõppkuupäeva ja kellaajaga.
Testida tänasest hilisema kuupäeva lisamist, kontrollida, et super-uudist ei kuvata.
