### ISSUE TITLE
Tulevikuideed disainiks

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#519]
- [ ] Väiksemate ekraani laiuste puhul 1030-...px puhul võiks vasakmenüü ikka kinni minna, aga mitte päris tahvel- või mobiiliversiooniks veel, vaid lihtsalt olla avatav-suletav. 
- [ ] Keritavate tabelite noolte redisain
- [ ] "Liigu üles" nupp pikkades vaadetes
- [ ] Sündmuste listvaate desktop parem kujundus
- [ ] Easter eggide lisamine lehele (väikesed illustratsioonid siia-sinna)
- [ ] listivaadetesse võrdluse tabi ikoon sarnaselt oska valdkondalele, nt see vaade http://htm.twn.ee/erialad?open_admission=true
- [ ] Võrdluse snackbarid terve lehe ulatuses
- [ ] Vasakmenüüs aktiivne element paremini esile toodud

**Comment by birgitpulk** [comment]
<img width="296" alt="screen shot 2018-05-08 at 15 58 53" src="https://user-images.githubusercontent.com/24669779/47853110-61555900-dde6-11e8-8d0d-b8dd8d600a2b.png">

**Comment by heldiraudsepp** [comment]
Liikus jirasse https://jira.twn.ee/browse/HP-62
