### ISSUE TITLE
OSKA sisutüüpe saab lemmikuks lisada

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#525]
Oska sisutüüpe:
- [ ] põhikutseala „MainProfessionPage“,
- [ ] valdkonna „FieldPage“,
- [ ] ülduuring  "SurveyPage"
- [ ] #501 sisutüüp kas siin või 501 raames 
saab lisada lemmikuks. Lemmikute lisamine-eemaldamine sarnaselt: #285

**Comment by TanelTromp** [comment]
TEST OK

- [ ] põhikutseala „MainProfessionPage“,
- [ ] valdkonna „FieldPage“,
- [ ] ülduuring  "SurveyPage"
