### ISSUE TITLE
Koodi optimeerimine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#527]

**Comment by ruut12** [comment]
@lsoonvald 
- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch%3A1&variables=%7B%22lang%22%3A%22ET%22%2C%22search_term%22%3A%22kuts%22%7D
Notice: Undefined variable: response in Drupal\htm_custom_graphql_elasticsearch\Plugin\GraphQL\Fields\ElasticQuery\ElasticQuery->getContentTypeLabels() (line 145 of /app/drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/ElasticQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch%3A1&variables=%7B%22lang%22%3A%22ET%22%2C%22search_term%22%3A%22ja%22%7D
Notice: Undefined variable: functions in Drupal\htm_custom_graphql_elasticsearch\Plugin\GraphQL\Fields\ElasticQuery\ElasticQuery->getElasticQuery() (line 237 of /app/drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/ElasticQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch%3A1&variables=%7B%22lang%22%3A%22ET%22%2C%22search_term%22%3A%22ja%22%7D
Warning: Invalid argument supplied for foreach() in Drupal\htm_custom_graphql_elasticsearch\Plugin\GraphQL\Fields\ElasticQuery\ElasticQuery->resolveValues() (line 123 of /app/drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/ElasticQuery.php) 

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch%3A1&variables=%7B%22lang%22%3A%22EN%22%2C%22search_term%22%3A%22tallinn%22%7D
Notice: Undefined variable: response in Drupal\htm_custom_graphql_elasticsearch\Plugin\GraphQL\Fields\ElasticQuery\ElasticQuery->getContentTypeLabels() (line 145 of /app/drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/ElasticQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch%3A1&variables=%7B%22lang%22%3A%22EN%22%2C%22search_term%22%3A%22university%22%7D
Warning: Invalid argument supplied for foreach() in Drupal\htm_custom_graphql_elasticsearch\Plugin\GraphQL\Fields\ElasticQuery\ElasticQuery->resolveValues() (line 123 of /app/drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/ElasticQuery.php)


- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQueryLocation%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A1%7D
Notice: Undefined variable: sums in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->resolveValues() (line 136 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php) 


- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQueryLocation%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A1%7D
Notice: Undefined variable: elastic_must_filters in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->getElasticQuery() (line 196 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php)


- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQueryLocation%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A1%7D
Notice: Undefined variable: elastic_should_filters in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->getElasticQuery() (line 195 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQueryLocation%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A1%7D
Warning: Invalid argument supplied for foreach() in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->getElasticQuery() (line 182 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQuerySchool%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A3%7D
Notice: Undefined index: investmentAmountSum in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->resolveValues() (line 154 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php)


- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQuerySchool%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A3%7D
Notice: Undefined variable: elastic_must_filters in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->getElasticQuery() (line 196 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQuerySchool%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A3%7D
Warning: Invalid argument supplied for foreach() in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->getElasticQuery() (line 182 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=subsidyProjectQueryLocation%3A1&variables=%7B%22ownershipType%22%3A%5B%5D%2C%22investmentMeasure%22%3A%5B%5D%2C%22investmentDeadline%22%3A%5B%5D%2C%22levelOfDetail%22%3A1%7D
Notice: Undefined index: Lääne-Viru maakond in Drupal\htm_custom_subsidy_projects\Plugin\GraphQL\Fields\SubsidyQuery\SubsidyQuery->resolveValues() (line 136 of /app/drupal/web/modules/custom/htm_custom_subsidy_projects/src/Plugin/GraphQL/Fields/SubsidyQuery/SubsidyQuery.php)

- [ ] Notice: Undefined variable: bundleName in Drupal\htm_custom_subscriptions\Plugin\GraphQL\Mutations\CreateTagSubscription->resolve() (line 117 of /app/drupal/web/modules/custom/htm_custom_subscriptions/src/Plugin/GraphQL/Mutations/CreateTagSubscription.php)

- [ ] Deprecated function: Non-static method Drupal\htm_custom_oska\ProcessOskaTableData::checkEntityReference() should not be called statically in Drupal\htm_custom_oska\ProcessOskaTableData::ValidateFile() (line 38 of /app/drupal/web/modules/custom/htm_custom_oska/src/ProcessOskaTableData.php)
- [ ] Notice: Only variables should be passed by reference in Drupal\htm_custom_oska\ProcessOskaTableData::checkEntityReference() (line 149 of /app/drupal/web/modules/custom/htm_custom_oska/src/ProcessOskaTableData.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch%3A1&variables=%7B%22lang%22%3A%22ET%22%2C%22search_term%22%3A%22%20%22%7D
Notice: Undefined variable: response in Drupal\htm_custom_graphql_elasticsearch\Plugin\GraphQL\Fields\ElasticQuery\ElasticQuery->getContentTypeLabels() (line 145 of /app/drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/ElasticQuery.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=homeSearch%3A1&variables=%7B%22lang%22%3A%22ET%22%2C%22search_term%22%3A%22%20%22%7D
Notice: Undefined variable: functions in Drupal\htm_custom_graphql_elasticsearch\Plugin\GraphQL\Fields\ElasticQuery\ElasticQuery->getElasticQuery() (line 237 of /app/drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/ElasticQuery.php)

@ruut12 
- [ ] http://htm.twn.ee/et/toolaud/taotlused/TEST2?test=true
Notice: Undefined index: options in Drupal\htm_custom_xjson_services\xJsonService->Drupal\htm_custom_xjson_services\@closure() (line 291 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php)

- [ ] Notice: Undefined index: 2data_element_selectlist_list in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 172 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php) 

- [ ] Notice: Undefined index: 2data_element_heading in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 172 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php)

- [ ] Notice: Undefined index: 1data_element_helpertext in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 172 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php)

- [ ] Notice: Undefined index: 1data_element_heading in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 172 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php)

- [ ] Notice: Undefined index: 2data_element_multikas_multiple in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 172 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php)

- [ ] Notice: Undefined index: data_elements in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 172 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php)

- [ ] Notice: Undefined index: value in Drupal\htm_custom_xjson_services\xJsonService->validateDataElement() (line 300 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php) 

- [ ] Notice: Undefined index: value in Drupal\htm_custom_xjson_services\xJsonService->validateDataElement() (line 300 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=customFavorites%3A1&variables=%7B%22language%22%3A%22ET%22%7D
Notice: Only variables should be passed by reference in Drupal\htm_custom_favorites\Plugin\GraphQL\Fields\Favorites\CustomFavorites->resolveValues() (line 90 of /app/drupal/web/modules/custom/htm_custom_favorites/src/Plugin/GraphQL/Fields/Favorites/CustomFavorites.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=customFavorites%3A1&variables=%7B%22language%22%3A%22ET%22%7D
Notice: Only variables should be passed by reference in Drupal\htm_custom_favorites\Plugin\GraphQL\Fields\Favorites\CustomFavorites->resolveValues() (line 90 of /app/drupal/web/modules/custom/htm_custom_favorites/src/Plugin/GraphQL/Fields/Favorites/CustomFavorites.php)

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=customFavorites%3A1&variables=%7B%22language%22%3A%22ET%22%7D
Notice: Only variables should be passed by reference in Drupal\htm_custom_favorites\Plugin\GraphQL\Fields\Favorites\CustomFavorites->resolveValues() (line 90 of /app/drupal/web/modules/custom/htm_custom_favorites/src/Plugin/GraphQL/Fields/Favorites/CustomFavorites.php

- [ ] http://htm.twn.ee/et/toolaud/taotlused/VPT_ESITATUD_TAOTLUS?existing=true&identifier=157721
Notice: Undefined index: first in Drupal\htm_custom_xjson_services\xJsonService->validatexJsonHeader() (line 222 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php)

- [ ] http://htm.twn.ee/et/toolaud/taotlused/VPT_ESITATUD_TAOTLUS?existing=true&identifier=157721
Notice: Undefined index: messages in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 196 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php

- [ ] http://htm.twn.ee/et/toolaud/taotlused/VPT_ESITATUD_TAOTLUS?existing=true&identifier=157721
Notice: Undefined index: messages in Drupal\htm_custom_xjson_services\xJsonService->buildFormv2() (line 161 of /app/drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=customFavorites%3A1&variables=%7B%22language%22%3A%22ET%22%7D
Notice: Only variables should be passed by reference in Drupal\htm_custom_favorites\Plugin\GraphQL\Fields\Favorites\CustomFavorites->resolveValues() (line 90 of /app/drupal/web/modules/custom/htm_custom_favorites/src/Plugin/GraphQL/Fields/Favorites/CustomFavorites.php

- [ ] http://test-htm.wiseman.ee:30000/graphql?queryId=customFavorites%3A1&variables=%7B%22language%22%3A%22ET%22%7D
Notice: Only variables should be passed by reference in Drupal\htm_custom_favorites\Plugin\GraphQL\Fields\Favorites\CustomFavorites->resolveValues() (line 90 of /app/drupal/web/modules/custom/htm_custom_favorites/src/Plugin/GraphQL/Fields/Favorites/CustomFavorites.php)

- [ ] http://test-htm.wiseman.ee:30000/dashboard/eeIsikukaart/studies?_format=json
Warning: Invalid argument supplied for foreach() in Drupal\htm_custom_ehis_connector\EhisConnectorService->filterPersonalCard() (line 308 of /app/drupal/web/modules/custom/htm_custom_ehis_connector/src/EhisConnectorService.php)

- [ ] http://test-htm.wiseman.ee:30000/dashboard/eeIsikukaart/studies?_format=json
Notice: Undefined index: value in Drupal\htm_custom_ehis_connector\EhisConnectorService->filterPersonalCard() (line 308 of /app/drupal/web/modules/custom/htm_custom_ehis_connector/src/EhisConnectorService.php

- [ ] http://test-htm.wiseman.ee:30000/dashboard/eeIsikukaart/teachings?_format=json
Notice: Undefined index: value in Drupal\htm_custom_ehis_connector\EhisConnectorService->filterPersonalCard() (line 308 of /app/drupal/web/modules/custom/htm_custom_ehis_connector/src/EhisConnectorService.php

**Comment by ruut12** [comment]
Pilet löödud tükkideks:
#564 
#565

**Comment by ruut12** [comment]
@lsoonvald 
- [ ] Notice: Undefined variable: bundleName in Drupal\htm_custom_subscriptions\Plugin\GraphQL\Mutations\CreateTagSubscription->resolve() (line 117 of /app/drupal/web/modules/custom/htm_custom_subscriptions/src/Plugin/GraphQL/Mutations/CreateTagSubscription.php)
