### ISSUE TITLE
LiveChat integreerimine ja seadistamine lehele

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#528]
**Eesmärk**
Seadistada lehel LiveChat trial versioon (https://www.livechatinc.com/powered-by-livechat) ja vaadata, kas see katab ka tasulise versiooni funktsionaalsused. LiveChati seadistamine on kliendi teha (millistel kellaaegadel avatud, mis andmeid küsitakse), portaali ülesanne on näidata välja vastavalt seadistustele Chati akent, mida saab avada.

**Comment by TanelTromp** [comment]
Viga 1 mobiil: sulgemise ikoon sisu all vaates:

![pilt](https://user-images.githubusercontent.com/37407917/47704050-f90e4800-dc2a-11e8-9de1-df1f4b70169c.png)

Viga 2 mobiil android: modaali alt paistab sisu ("ahh"), mis on lehe üleval, kuigi skroll oli lehe lõppu:

![screenshot_20181030-093320](https://user-images.githubusercontent.com/37407917/47704157-5b674880-dc2b-11e8-9c13-034452b1d575.png)

Viga 3: rohkem õhku "Lae rohkem" ja vestluse ballooni vahele:

![screenshot_20181030-093320](https://user-images.githubusercontent.com/37407917/47704201-7f2a8e80-dc2b-11e8-98f3-b97d88efc2c4.png)

**Comment by skeefee** [comment]
Viga 1: Tundub lihtsalt et on sisu all kuna sulgemise nupu taust on ka valge.
Viga 2: Sellised "vead" ei ole meie hallata vaid pigem chati enda teha.
VIga 3: balloon muutus ringiks

**Comment by birgitpulk** [comment]
Kujundus koos Henriga korrigeeritud, minu poolt korras!
