### ISSUE TITLE
OSKA muudatused

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#530]
Muuta valdkonna lehe paremas veerus #497 bloki pealkiri eesti keeles
* Põhikutsealad → Ametialad

Muuta "MainProfessionPage" sisutüübil:
* lk pealkiri: Põhikutseala → Ametiala
* URL: /et/pohikutsealad → et/ametialad
* nimekirja vaates: Põhikutsealad → Ametialad

Muuta „SurveyPage“ sisutüübil:
* lk pealkiri: Ülduuring → Tööjõuprognoos

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
TEST

- [x] Põhikutsealad → Ametialad

Muuta "MainProfessionPage" sisutüübil:

- [x]     lk pealkiri: Põhikutseala → Ametiala
- [x]     URL: /et/pohikutsealad → et/ametialad
- [x]     nimekirja vaates: Põhikutsealad → Ametialad

Muuta „SurveyPage“ sisutüübil:

- [x]     lk pealkiri: Ülduuring → Tööjõuprognoos
