### ISSUE TITLE
Sotsiaalmeedia jagamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#533]
- [ ] Ei  avane sotsiaalmeedia jagamise nupp

- [ ] FB ja Twitteri ikoonid ei tohi olla tundlikud, kui rippmenüü valik on suletud

@skeefee kirjutab koodi nouded

**Comment by madispold** [comment]
@skeefee @birgitpulk 
Komponent ümber tehtud. Lisaks sellele kohandatud ka terve toimingute rida pealkirja all.

**Comment by TanelTromp** [comment]
Viga 1: tundlik peaks olema ainult jagamise ikooni ala, mitte ka rippmenüü ala. Kasutaja võib tahta selle all olevat teksti nt selekteerida:
https://gyazo.com/d56a5b10b528d3685ef97eee0d5b6ab1

**Comment by birgitpulk** [comment]
@TanelTromp , palun testi antud jagamise lahendust ka mobiilis (funktsionaalsuse muutumine jagast saab kopeeri ja kuidas käib jaga nupu sulgemine). Minu meelest väga arusaamatu loogika mobiilses vaates. 

Lisaks @madispold palun tekitame selle lahtise kolme mummu taha valge ala, et tekst ei kumaks sealt läbi (praegu natukene liiga mürarikas)

**Comment by heldiraudsepp** [comment]
@erkkijakobson Vajame sinu vastust Birgiti esitatud küsimusele, et saaksime selle piletiga edasi tegeleda.

**Comment by erkkijakobson** [comment]
@birgitpulk jagamise mitte sulgumine on bugi, loe selle pileti 2. sõnumi 2. punkt uuesti (kõigi 3 jagamise ikooni valimisel sulgub FAB).

WCAG vastuolu puudub: MD-direktiivile vastavalt on kõik 3 nuppu samaliigiline funktsionaalsus.
Pole tõendeid, et peamisena geneerilise (kopeeri lehe viit jagamiseks kuhuiganses) ja minoorsena spetsiifilisi tegevusi (jaga kahte nimetatud sotsiaalvõrku) pakkuva FAB nupu kasutus  oleks raskesti arusaadav: mobiilis on MD rakendatud Androidi-üleselt alates versioonist 4 st kõik antud ajahetkel aktuaalsed versioonid rakendavad MDd, FAB on väga laias kasutuses (Koosta > a) geneeriline kirjuta, b) kirjuta @birgitpulk c) kirjuta @TanelTromp). Hea arusaadavuse ja toime tõttu on FAB leidunud palju kasutust ka iOS mobiilirakendustes, millel Androidi versioon puudub.

**Comment by birgitpulk** [comment]
MD enda leheküljelt: https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions

"Upon press, the FAB remains visible and emits a stack of related actions. If the FAB is tapped is pressed in this state, it should either initiate its default action or close the speed dial actions."

Ehk siis oma reeglites ja ka videos viitavad nad ka sellele, et fab, mille alt avanevad teised nupud, selle algne fab+ikoon saab jääda kas samaks nagu ta oli enne või muutuda sulgemise ikooniks. JA selliseid lahendusi, et fabi vajutades muutub selle funktsionaalsus, seda ei ole üheski näites välja toodud, sest see on halb UX praktika ning vaegnägijale ja ekraanilugerit kasutavale inimesele asjatu lisainformatsioon. Seega, näide Google Earthist eksib nende enda reegli vastu. 

Veel head infot FABi ja UXi osas: https://uxplanet.org/floating-action-button-in-ux-design-7dd06e49144e

Mõned WCAG vastuolud, millele viitasin: 
"Kui mingi elemendi peal hiirega hõljumine või millegi tab-iga fokusseerimine toob nähtavale lisasisu, siis peab kasutajal olema võimalik seda sisu kinni panna ilma hiirt või fookust liigutamata (nt vajutades ESC klahvi). Tal peab olema ka võimalus liikuda tekkinud sisu peale, ilma et see kinni läheks. Motoorikahäiretega kasutajal võib olla keeruline hoida hiirt ühe koha peal paigal või liigutada seda väga täpset rada pidi. (WCAG 1.4.13)"

"Elementi fokuseerides ei tohi juhtuda midagi ettearvamatut – fookus ei tohi minna mõnele teisele elemendile, vorm ei tohi ennast ise ära saata jne. (WCAG 3.2.1)" Funktsiooni muutus on samuti ettearvamatu muutus!

**Comment by erkkijakobson** [comment]
> **Emit related actions**
> Upon press, the FAB remains visible and emits a stack of related actions. If the FAB is tapped is pressed in this state, it should either initiate its default action or close the speed dial actions.

Ühtki piirangut vaiketegevuse ikoonile see ei sea ehk praegune käitumine on disainiraamistiku järgi korrektne nagu juba eelmises vastuses viidatud. WCAG nõuete täitmist see samuti ei takista. Google on siin aastaid olnud eeskujuks, nt: https://inbox.google.com (TAB avab, FAB ikoon muutub, ESC sulgeb)

**Comment by birgitpulk** [comment]
> Ühtki piirangut vaiketegevuse ikoonile see ei sea ehk praegune käitumine on disainiraamistiku järgi korrektne nagu juba eelmises vastuses viidatud. WCAG nõuete täitmist see samuti ei takista. Google on siin aastaid olnud eeskujuks, nt: https://inbox.google.com (TAB avab, FAB ikoon muutub, ESC sulgeb)

Mina ei ole selle seisukohaga siiski nõus, rääkisin ka meie poolt Hegle Sarapuuga ning ka tema seisukoht oli, et konkreetne lahendus ei ole UX praktikate seisukohast hea. See, et Google seda teinud on, ei tähenda, et on järgitud kõiki UX ja WCAG tavasid ja reegleid. (toon näiteks kasvõi MD dropdown elemendi, mis on samuti UX tavade ja WCAG-ga vastuolus). Aga et mitte seda vaidlust enam jätkata, siis teen ettepaneku sel teemal jääda eriarvamusele ja lahendus jääb nii nagu ta on. 

Mis puudutab jaga nupu asukohta, siis nagu oleme korduvalt rääkinud, siis seda ei saa sinna paremasse ülaserva panna järgmistel põhjustel: 

1. - mobiilis ei jää talle ruumi kui hall pealkiri peaks olema natukenegi pikem (mitmes kohas on)
2. - nii kaua kuni on plaanis siiski teha õpitee vaade, millel on 2 erinevat sakki, siis ei mahuks Jaga nupp sinna ära
3. ei tahaka hoida erinevaid leheküljega tehtavaid funktsioone üksteisest kaugel (ei jää ka visuaalselt hea)

**Comment by madispold** [comment]
Viga 1: Desktopis jäi kliendi soovil Hover state'iga töötama. Moblas käitub nagu dropdown ja avaneb touchil/clickil.
Viga 2: OK.
Viga 3: OK.
Viga 4: OK.
Viga 5: OK.
Viga 6: OK.
Viga 7: OK.
Viga 8: OK.
Viga 9: OK.
Viga 10: Ei nõustu, kui ise üldiselt OSis kopeerid midagi (Word, netis vms), kas tunned vajadust et tahaks mälust tühjendada viimase kopeeringu?
Viga 11: OK.
Viga 12: OK.
Viga 13: OK.

**Comment by TanelTromp** [comment]
Viga 11 IE11 uuel kujul aga olemas nüüf nii:
https://gyazo.com/5cdab746928ebcc57d6a2c4b3856de33

**Comment by erkkijakobson** [comment]
**Viga 16:** IE tõttu teistele sirvikutele bugisid ei tee, ligipääsetavuse raportis nimetame vajadusel IE vead
**Viga 17:** iOS Safari/Firefox peale kopeerimist tekib ja ei kao enam ära tooltip _Jaga lehte_
![image](https://user-images.githubusercontent.com/16906555/49227708-68c24f00-f3f2-11e8-99df-5ca8f1469626.png)
**Viga 18:** Vea 17 pildil on aga korrektne seis kuidas kopeerides hiirt liigutamata desktopil peab jääma
**Viga 19:** peale kopeerimist ikoon tagurpidi - nähtav Taneli 14. vea pildil. Vea 18 parandus teeb korda.
**Viga 20:** WCAG kohaselt ei tohi hover sisu peale avaneda, nõuet 1.4.13 täitev asukoht _Jaga_ nupule:
![image](https://user-images.githubusercontent.com/16906555/48490442-1c8de100-e82e-11e8-951d-638a5f0bbcbe.png)
>Mis puudutab jaga nupu asukohta, siis nagu oleme korduvalt rääkinud, siis seda ei saa sinna paremasse ülaserva panna järgmistel põhjustel:
> 1. mobiilis ei jää talle ruumi kui hall pealkiri peaks olema natukenegi pikem (mitmes kohas on)
> 2. nii kaua kuni on plaanis siiski teha õpitee vaade, millel on 2 erinevat sakki, siis ei mahuks Jaga nupp sinna ära
> 3. ei tahaka hoida erinevaid leheküljega tehtavaid funktsioone üksteisest kaugel (ei jää ka visuaalselt hea)
1. kõige pikema halli pealkirja ja kõige pisema 4" ekraani puhul ruumiprobleemi ei ole
2. eelpool nimetati juba, et õpitee on listvaade nagu kaart, uudised jt - _Jaga_ on ainult detailvaadetes
3. mõnikord esinevatest nuppudest _Jaga_ ei hooli, neile saab vajadusel muu pileti raames koha leida

**Comment by birgitpulk** [comment]
@erkkijakobson 
1. Täna võib-olla ei ole, aga mis saab tulevikus? Kui pealkirjad muutuvad nt venekeelseks või kui tekib pikemaid pealkirju (kui vaadata nt Küllikese tehtud navigatsiooni, siis on seal väga pikkasid pealkirju mis kujunduses oleks seal halli pealkirja kohas kuvatud).
2. Õpitee lehekülge ei ole me ju läbi kujundanud ja analüüsinud, see on veel poolik teema. Visuaalselt kasutajale on ta ju detailvaade mitte listvaade, seega miks seal jagamist ei ole? Miks on osad leheküljed jagatavad ja osad ei ole kasutaja vaatepunktist?
3. Jaga ei pruugi hoolida, aga visuaalselt ei näe see hea välja, kui kõik artikliga seotud funktsionaalsused on üle lehe laiali. 
4. Minu küsimus on selles, et miks on kogu see avatud jaga nupu ala hoverdatav? peaks olema ju ainult jaga ikoon sellisel juhul ei ole teksti kopeerimine ju probleem?

**Comment by erkkijakobson** [comment]
@birgitpulk õpitee kui listvaade on juba täna eraldiseisvate detailvaadetega, mahu tõttu teisiti ei saa. Praegused muud nupud ja sildid on täiesti _random_ koos. Lahendame selles piletis vaid jaga nuppu.

**Viga 21:** Kopeeritud URL ei vasta nõuetele https://github.com/hariduspilv/haridusportaal/issues/535

**Comment by birgitpulk** [comment]
@erkkijakobson  

1. Õpitee kui listvaade on meil tegelikult ju siiani fikseerimata, et milline see tuleb. Sa lubasid et HTM viib läbi kasutatavuse testimised teie poolt pakutud joonisega ja palusin neid tulemeid ka endale vaatamiseks ja analüüsimiseks. Hetkel on meil planeeritud õpitee vaatesse üles paremale sakid ja jaga ikoon sinna komplekti ei sobitu:
<img width="474" alt="screen shot 2018-12-05 at 14 35 20" src="https://user-images.githubusercontent.com/24669779/49513945-39e92480-f89b-11e8-936d-0aeca189ec6e.png">

2. See loogika, et kasutame üleval paremal sakke, see on üle portaali läbivalt samasugune. Ei ole hea seda loogikat lõhkuda ja osadel vaadetel kasutada sakkide asemel jaga nuppu. Kasutaja ei mõista, mis vahe on listvaatel ja detailvaatel, tema jaoks on vahel paremal üleval sakid ja vahel jaga nupp. 

3. Jaga nupp üleval paremal katab osaliselt ka sissejuhatavat teksti. Täna on seal jagamise võimalusi 2tk, aga tulevikus võib neid olla ka rohkem, mis kataks teksti veelgi rohkem. 
<img width="640" alt="screen shot 2018-12-05 at 15 15 18" src="https://user-images.githubusercontent.com/24669779/49515813-a74b8400-f8a0-11e8-9986-dd066cf1a705.png">

4. Jaga nupp ei joondu mitte  ühegi objektiga ning visuaalselt jääb hõljuma vaatesse (ei saa nihutada, kuna hoveriga jääb sinine taust servadele liiga lähedale). 
<img width="626" alt="screen shot 2018-12-05 at 15 17 29" src="https://user-images.githubusercontent.com/24669779/49515929-eb3e8900-f8a0-11e8-9f39-32a18114dd6b.png">

**Comment by erkkijakobson** [comment]
1.-2. Need vaated jaga nuppu ei oma
3.-4. Nupp joondub kõrguses lehetüübi pealkirjaga, antud ekraanidel põhikutsealaga - hoveri lähedus ei sega kuna on parem kui käesolev lahendus, loetavus samuti. Muudame ära.

**Comment by birgitpulk** [comment]
@erkkijakobson 
3-4: Kui pealkiri on pikem, siis ta katab ju pealkirja ära?

**Comment by erkkijakobson** [comment]
Kuna automaatset sõnade poolitust pole, siis olukord, kus pikema pealkirja sõna lõpp tabab täpselt rea viimaseid piksleid esineb väga harva - sõnad liiguvad valdavalt uuele reale jättes rea lõpu tühjaks.
