### ISSUE TITLE
Rahastuse kaardi puudused

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#534]
- [ ] Lisada nõutud viitamine 'Haldusüksuste piirjoonte allikas Maamet, andmed seisuga _kml_dateTime_'
- [ ] https://zpl.io/29yMA7l asemel haldusüksusele _tooltip_, milles üksuse nimi ja ta toetuste summa
- [ ] Imeliku suumi reseti tõttu ei toimi tellitud töövoog: maakond > suum > vald > selle piirkonna koolid
- [ ] Filtrirea väljapikkused 12st: omand col-3;  meede col-5; aasta col-4 ja tõlge > 'Rakendamise aasta'
- [ ] Et joonistuks välja haldusüksuste valged piirid, viia toetust mittesaanud üksuste värvus halliks
- [ ] Klikk ülaserva koolil liigutab kaarti alla, klikk aastal peaks ruumi puudusel ka (alternatiiv tõsta z)
- [ ] Koolil rahastuse aastat lahti klikkides on puudu summa arvu vorming tühikude abil ja rahaühik €
- [ ] Vertikaalse responsiivsuseta läheb kaardi element lubamatult madalaks, lubada kuvasuhe kuni 1:1
![image](https://user-images.githubusercontent.com/16906555/46944247-3f37a900-d07a-11e8-8d4a-adade9a14469.png)

**Comment by skeefee** [comment]
@Tanel palun testida 

* Klikk ülaserva koolil liigutab kaarti alla, klikk aastal peaks ruumi puudusel ka (alternatiiv tõsta z)
Seoses google maps poolt pakutava lahenduse probleemiga ei ole see hetkel võimalik. Vajab täiendavat uurimist. Võimalus kaaluda lisatööna

**Comment by skeefee** [comment]
* https://zpl.io/29yMA7l asemel haldusüksusele tooltip, milles üksuse nimi ja ta toetuste summa
Peale pikka uurimist saime ikka infoakna lahenduse rakendatud.  Seoses halva dokumentatsiooniga tundus algselt et see ei ole tehtav.
