### ISSUE TITLE
Korrektne URL-i vorming

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#535]
Lahenduse URLid viia vastavaks toodangu kujuga - piirangud ja nõuded:
- [x] URL ei tohi ületada 250 tähemärki.
- [x] Korrektne kuju on _www_-ta, st _www_-ga pöördumistelt eemaldadab lahendus enne avamist ise _www_.
- [x] Lahenduses ei tohi olla sissekompileeritud absoluutseid URLe.
- [x] URL kuvab alajaotust ja pealkirja teisendatud kujul: vaid väiketähtedena ja sõnade vahele 1 miinus.
- [x] URL on UTF-8 vormingus, st kuvab aadressireal korrektselt mh emakeelsed väiketähed Õ, Ä, Ö ja Ü.
- [x] URL ei tohi hoida lisa keelekoodi: _edu.ee/et/sundmused_ asemel peab olema _edu.ee/sündmused_
- [x] URL ei tohi lõppeda kaldkriipsu, _.htm_-i, _.html_-i ega taolisega v.a üleslaadimisel lubatud failitüüp.
- [x] Vorminõuded kehtivad lehe üleselt sh üleslaetavatele failidele, nende URIdele, xDzeison teenustele.
- [x] [Jagamise nupp](https://github.com/hariduspilv/haridusportaal/issues/533#issuecomment-429940830) peab väljastama korrektse UTF-8 URL-i lõikepuhvrisse, FBsse ning Twitterisse.

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud _www-ga pöördumistelt eemaldadab lahendus enne avamist ise www._:
https://gyazo.com/9f28685bc816d472ef8573b57b1c7be1

**Comment by skeefee** [comment]
Viga 1. Kuna meil on htm.twn.ee hetkel siis sinna ette ei saa tehniliselt www panna. See ei tööta. Kui meil tuleb edu.ee siis näeb seda töötamas.

Viga 2. @ruut12 
Viga 2.1. IE11 ei kuvagi täpitähti. Sellest rääkisime juba varasemalt koosolekutel.
Viga 3. @ruut12  (frontendi poole peale ei lähe query params arvesse)
Viga 4. Sisu viga. Ilmselt on muudetud sisu pealkirja ja URL jäi vanaks. URL ei muutu kui drupal adminis muudad avaldatud sisu pealkirja. @ruut12  võib seletada sellets rohkem

Viga 5. Tundub okei
Viga 6. cache viga oli. Nüüd meil on endpoindid jälle vana serveri peal kuniks cache on okei.
Viga 7.  Korras
Viga 8. Nii on mõistlikum. EI ole vaja kasutajat eemale suunata. Suunamisel ta ei saa aru mis valesti läks ja mis tema sisestatud urlist sai.
Viga 9. @ruut12

**Comment by ruut12** [comment]
Viga2. See tuleb elasticu indeksist teen täienduse GraphQl
Viga3. Seda ei saa kontrollida. Kontrollitakse tiitli pikkust (250 tähemärki on väga pikk url)
Viga4. Sisulehe loomisel automaatselt pannakse tiitel lingiks, hiljem tuleb seda käsitsi muuta viite tab'ist adminnis
Viga9. .xml lõpp eemaldatud

**Comment by TanelTromp** [comment]
Viga 10: otsinguga leht katki (ei ole "/et" liidet aga ikkagi) "error 404". Lehele sisupuult liikudes kõik korras:

https://gyazo.com/c7c8f6b09371783930d71fa8eeb2f6bb

**Comment by skeefee** [comment]
Viga 10: @ruut12

**Comment by lsoonvald** [comment]
Viga 10: Korras.

**Comment by erkkijakobson** [comment]
Viga 11: lõikepuhvrisse kopeeritav URL pole veel täpitähtedega, kopeerib nt http://htm.twn.ee/uudised/oecd-eksperdid-teaduse-ja-tehnoloogia-m%C3%B5jude-oskuslik-m%C3%B5%C3%B5tmine-toetab-riigi-arengut

**Comment by ruut12** [comment]
Viga12 : Korras @TanelTromp

**Comment by TanelTromp** [comment]
Viga 13: väljalogides viskab ERROR 404 lehele (Chrome + testkasutaja/parool):
https://gyazo.com/72a3a0cb578d0619db1e83e591df0963
'

**Comment by skeefee** [comment]
Viga 11: Korras
Viga 13: Korras

**Comment by skeefee** [comment]
Viga 12: @ruut12 
Viga 14: @ruut12 
Viga 15: @ruut12

**Comment by lsoonvald** [comment]
Viga 15: Korras.

**Comment by TanelTromp** [comment]
TEST

Viga 16: edu.ee domeen on loodud aga tingimus ei ole hetkel veel täidetud: *Korrektne kuju on www-ta, st www-ga pöördumistelt eemaldadab lahendus enne avamist ise www.*

https://gyazo.com/1cc67c300131c3cb120d813eea829e6a

**Comment by skeefee** [comment]
Viga 16: Korras. Lisasin https suunamise toe

**Comment by TanelTromp** [comment]
TEST

- [x] URL ei tohi ületada 250 tähemärki.
- [x] Korrektne kuju on _www_-ta, st _www_-ga pöördumistelt eemaldadab lahendus enne avamist ise _www_.
- [x] Lahenduses ei tohi olla sissekompileeritud absoluutseid URLe.
- [x] URL kuvab alajaotust ja pealkirja teisendatud kujul: vaid väiketähtedena ja sõnade vahele 1 miinus.
- [x] URL on UTF-8 vormingus, st kuvab aadressireal korrektselt mh emakeelsed väiketähed Õ, Ä, Ö ja Ü.
- [x] URL ei tohi hoida lisa keelekoodi: _edu.ee/et/sundmused_ asemel peab olema _edu.ee/sündmused_
- [x] URL ei tohi lõppeda kaldkriipsu, _.htm_-i, _.html_-i ega taolisega v.a üleslaadimisel lubatud failitüüp.
- [x] Vorminõuded kehtivad lehe üleselt sh üleslaetavatele failidele, nende URIdele, xDzeison teenustele.
- [x] [Jagamise nupp](https://github.com/hariduspilv/haridusportaal/issues/533#issuecomment-429940830) peab väljastama korrektse UTF-8 URL-i lõikepuhvrisse, FBsse ning Twitterisse.

**Comment by TanelTromp** [comment]
Viga 17: Twitterisse jagamise URL on küll õige aga ta ei suuda nime URL-i ette kuvada, kui tegemist UTF-8-ga ehk kirjutab pealkirja asemel "Undefined". Kas uus pilet?

![pilt](https://user-images.githubusercontent.com/37407917/51301660-a75ea800-1a38-11e9-9e80-809947e1cc6c.png)
**
