### ISSUE TITLE
Sisendvälja nime animatsioon katki

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#536]
Oodatud tulemus:
Sisendvälja nimi liigub sujuvalt kliki peale antud välja kohale; jättes välja tühjaks, liigub sarnaselt tagasi.

Tuvastatud probleem:
Hetkel on animatsioon mitmes vaates katki läinud: testitud otsingu ja filtrivaadetes Chrome ja Safariga.

Elemendi standard: https://material.io/design/components/text-fields.html#anatomy
Raamistiku elemendid: https://material.angular.io/components/form-field

Lahendus Storybookiga

**Comment by TanelTromp** [comment]
TEST

Chrome 69 +Windows 10
iPad + Safari
Testkeskkond: test.edu.ee

Korras filter: sündmused; uudise; õppeasutused-asukohad; toetusprojektid; erialad; sisselogimine
https://gyazo.com/44df9c28ede2ce35226f2ca381d91e53

Ainus koht, kus hetkel antud MD loogika ei tööta ja, mida ma märkasin on sisulehel olev otsing (täpsustan Birgitiga):
https://gyazo.com/57be0f9205094cc0df924f938fadaf4d

Palun täpsemat kirjeldust, kus sisus ja mis kombinatsiooniga ei töötanud (Mac mudel, opsys ver).
@erkkijakobson
