### ISSUE TITLE
OSKA Infograafika Täiendamine

### ISSUE THREAD

**Issue by lsoonvald** [hariduspilv/haridusportaal#537]
põhikutseala = ametiala

Lisada x-telje valik, x-telg valitakse olemasolevatest filtritest (periood, valdkond, alamvaldkond, põhikutseala, silt)

**Comment by lsoonvald** [comment]
Saab testida survey page sisutüübi alt.

**Comment by TanelTromp** [comment]
TEST

Viga 1 üldine: rippmenüü enda hint võiks valitavast sisust erineda visuaalselt (sama probleem läbivalt tüüüplehtedel, kus ei ole  kohustuslikku valikut rippmenüüs). See tekitab segadust, et justkui valik oleks tehtud, kuigi tegelikult ei ole. Kui MD võimaldab, siis muudaks seda "-select graph v-axis-" kirjapildiga valikuks (ehk väikse tähega ja tekst "-"-de vahele.
https://gyazo.com/396edcece72a9298fc4eb594bda0afb7

Täpsustus 1: millal tõlked tulevad ja vastavad piletile? (periood, valdkond, alamvaldkond, põhikutseala, silt vs hetkel ing. k ja e.k segamini)

**Comment by lsoonvald** [comment]
Viga 1: Asendasin graafiku rippmenüü väljadel esimese valiku "-"'ga

Täpsustus 1: Tõlkisin ära väljad.

**Comment by TanelTromp** [comment]
TEST

korras
