### ISSUE TITLE
Ettevõtja töölaua päring (get applicationsJuridicalPerson)

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#540]
**Üldkirjeldus:**
Kasutaja on tahab näha portaalis ettevõtte töölaual taotluste osa, et sealt kaudu esitada dokumenti (taotlust) või seal vaadata olemasolevate dokumentide (taotluste, otsuste) andmeid. Kasutaja peab olema eelnevalt sisse loginud ja valinud ettevõtte, mille nimel ta portaali kasutab (vt #539). Portaali FE küsib BE-lt töölaua taotluste osale kuvatavaid andmeid. BE teeb lõime kaudu päringu EHIS-st, mille tulemusena saadakse ettevõtte kohta töölaual kuvatavad dokumentide andmed. BE "rikastab" andmeid õppeasutuste andmetega.

**Tegevused:**
1. Lugeda ettevõte, mille nimel kasutaja portaali kasutab (ettevõtte meelde jätmine #539).
2. Portaali BE otsib andmeid vaheandmebaasist (REDIS). REDIS-st otsitav key on registrikood ja hashmap on "mtsys" (hashmap-e lisandub, teha konfiguratsiooni parameeter).
3. Kui REDIS-s pole kirjet, siis portaali back-end teeb päringu lõimest (vt #212, mtsysTegevusload).
4. Portaali BE lisab igasse _acceptable_form_, _draft_ ja _document_ objekti inimloetava nimetuse _title_ võttes selle _form_name_ definitsioonist (_body.title_). Kui _form_name_ definitsioon puudub, siis seda objekti päringu vastuses ei edastata ja viga logitakse.
5. Portaali BE jätab lisaks #539 meelde jäetud ettevõttele ka õppeasutused (_educationalInstitution.id_), mille nimel kasurtaja portaali kasutab. Portaali BE lisab igasse _educationalInstitution_ objekti õppeasutuse üldandmete, aadressi ja kontaktide objektid. Nende objektide saamiseks on BE-l  õppeasutuse päringu teenus #541 (sisendisse õppeasutuse id ja addTitles = true (lisada klassifikaatori koodidele nimetused)).

**Comment by ruut12** [comment]
BE endpoint:
test-htm.wiseman.ee:30000/dashboard/applications/{init}?_format=json
 - [ ] Lisada form_name title
