### ISSUE TITLE
Õppeasutuse lisamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#542]
**Üldkirjeldus:**
Portaali kasutaja on sisestanud lisatava õppeasutuse andmed. Portaali FE edastab õppeasutuse andmed BE-le, BE edastab need lõimesse, et lõime saadaks X-tee kaudu EHIS-sse. 

**Tegevused:**
1. Portaali BE loeb ettevõtte (registrikoodi), mille nimel kasutaja portaali kasutab (see jäetakse meelde #539 raames). Portaali BE lisab ettevõtte registrikoodi FE-st saadud ettevõtte andmetele.
2. Portaali BE edastab ettevõtte andmed lõimele (vt #215).
3. Portaali BE lisab lisatud õppeasutuse id kasutaja poolt esindatavate õppeasutuste hulka, et kasutaja saaks jätkata portaali kasutamist lisatud õppeasutuse nimel (või lugeda kõik töölaua andmed uuesti - #540).

**Comment by ruut12** [comment]
Vormi sisendite päring:
GET: /educational-institution/data

**Comment by ruut12** [comment]
Lisamiseks:
POST: /educational-institution/add

Body:
`{
	"general":{
		"name": "",
    	"nameENG": "",
    	"ownerType":,
    	"ownershipType":,
    	"studyInstitutionType":
	},
	"address": {
		 "seqNo": ,
        "adsId":,
        "adsOid": "",
        "klElukoht":,
        "county": "",
        "localGovernment": "",
        "settlementUnit": "",
        "address": "",
        "addressFull": null,
        "addressHumanReadable": ""
	},
	"contacts":{
		"contactPhone" : "",
		"contactEmail": "",
		"webpageAddress": ""
	}
}`
