### ISSUE TITLE
Õppeasutuse muutmine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#543]
**Üldkirjeldus:**
Portaali kasutaja on muutnud õppeasutuse kontaktandmed. Portaali FE edastab muudetud õppeasutuse andmed (kontaktandmed) BE-le, BE edastab need lõimesse, et lõime saadaks X-tee kaudu EHIS-sse. 

**Tegevused:**
1. Portaali BE loeb ettevõtte (registrikood) ja õppeasutused (id), mille nimel kasutaja portaali kasutab (need jäetakse meelde #539 ja #540 raames). Portaali BE kontrollib, kas kasutajal on õigus muudetava õppeasutuse nimel portaali kasutada.
2. Portaali BE loeb õppeasutuse praegused andmed (#541). Portaali BE paneb kokku ettevõtte registrikoodi, õppeasutused praegused andmed (üldandmed - neid kasutaja ei saa muuta) ja  FE-st saadud aadressi ja kontaktandmed ning edastab andmed lõimele (vt #215).
3. Portaali BE kustutab redisest vana kirje, et #541 väljastaks edaspidi muudetud andmed.

**Comment by ruut12** [comment]
muutmiseks:
POST: /educational-institution/edit
Nõutut body võti on edId (educational institution id)

Body:
`{
	"edId": ,
	"address": {
		"seqNo": ,
        "adsId": ,
        "adsOid": "",
        "klElukoht": ,
        "county": "",
        "localGovernment": "",
        "settlementUnit": "",
        "address": "",
        "addressFull": null,
        "addressHumanReadable": ""
	},
	"contacts":{
		"contactPhone" : "",
		"contactEmail": "",
		"webpageAddress": ""
	}
}`
