### ISSUE TITLE
Sisseloginud kasutaja vasakmenüü muudatus

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#545]
Alles jääb hall pealkiri "TÖÖLAUD"
Antud halli pealkirja alt lähevad maha Taotlused, Tunnistused, Õpingud, Õpetan. Nende asemele tuleb "Minu töölaud" punkt, mis viib kasutaja Töölauale, kus on sakk "Taotlused" valitud.

@andrussarv Kas breadcrumbsis peaks ka muudatused tegema?

**Comment by madispold** [comment]
Testimisse @birgitpulk @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1: kui ei ole sisse loginud, siis "Töölaua" kohal ei tohiks midagi kuvada. Hetkel kuvab "Ligipääsmatu":

![pilt](https://user-images.githubusercontent.com/37407917/47219302-23544000-d3b7-11e8-9a73-855b7ff4e159.png)

**Comment by madispold** [comment]
@ruut12 ligipääsmatu link menüüs.

**Comment by ruut12** [comment]
Lingid menüüs parandatud

**Comment by TanelTromp** [comment]
Viga 1: "surnud breadcrumbsi" link, kui valitud on "taotlused" ehk default:
https://gyazo.com/e1f8bd99222fe34961274690877496ec

Lahendus 1: värskendab lehte sellele klikkides
Lahendus 2: default vaates ei ole see tase valitav ja on passiivne

**Comment by madispold** [comment]
Viga 1: OK - kuna töölaua vaadet ei ole, vaid on alamvaated, siis "Minu töölaud" pole enam link.

**Comment by TanelTromp** [comment]
TEST OK

**Comment by birgitpulk** [comment]
Kujundus korras!
