### ISSUE TITLE
404 lehele ei tohi suunata

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#548]
Kasutaja autendib Eesti IKta (nt TARA eIDAS) > süsteem ei saa töölaua päringuid teostada > 404 Oi oi
https://test.edu.ee/et/kool/iisaku-gumnaasium laeb kooli andmed, järgmise bloki laadimishetkel > 404

Esimesel juhul kuvada dialoogakent, et Eesti haridussüsteemi andmete nägemiseks on vajalik Eesti IK, login nuppe ja soovitust nende abil end IK-d edastava vahendiga taasautentida. Teisel juhul teavitada kasutajat _snackbar_ abil, et tehnilise vea tõttu ei õnnestu kõigi lehe elementide laadimine.

Täiendavad olukorrad lahendada samuti kohase teavitusega. Väga kasutajavaenulik oleks taotlusvormi täitmisel vilgutada ekraan siniseks misiganes põhjusel. 404 eesmärk on valestitipitud URL kinni püüda.

**Comment by heldiraudsepp** [comment]
@erkkijakobson Palun edasta meile sisselogimise protsessi kirjeldus nii nagu 18.10 koosolekul kokku leppisime. Käsitleksime teavitust isikukoodi vajalikkuse kohta sisselogimise pileti raames

**Comment by heldiraudsepp** [comment]
- [ ] Kasutaja  autendib Eesti IKta (nt TARA eIDAS) > süsteem ei saa töölaua päringuid teostada > 404 Oi oi - lahendatakse sisselogimise FE pileti raames 
https://test.edu.ee/et/kool/iisaku-gumnaasium laeb kooli andmed, järgmise bloki laadimishetkel > 404 - lahendatakse veateadete pileti raames https://github.com/hariduspilv/haridusportaal/issues/509
