### ISSUE TITLE
Disain leitud vead/parandused 5

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#549]
- [x] Ametiala võrdluse vaade kollane mumm hallil taustal: piirjoon ümber, 1px, #c7c7c9
- [x] Päises otsingukastis peaks olema kiri "Sisesta märksõna ja vajuta Enter", avalehel otsingukastis tekst "Otsi märksõna järgi"
- [x] xJsoni teavitustele lisada sulgemise "x"
- [x] Akordioni sees bulletid võiksid olla tekstiga samal joonel
- [x] Päise otsingukasti kiri peaks olema Regular fondiga
- [x] Toetusprojekti lehel sakid laevad teistmoodi kui teistel lehtedel (alguses tulevad ikoonid ja siis muu)
- [x] Text area element üle kontrollida üle lehekülje: label peab minema joone peale, kirjutama hakates sisutekst Regular #333333 toonis
- [x] Lisa uus õppeasutus modaalis aadressi riba täislaiuses
- [x] Päises otsingukast sisuosaga sama lai

**Comment by birgitpulk** [comment]
<img width="403" alt="screen shot 2018-10-26 at 14 33 41" src="https://user-images.githubusercontent.com/24669779/47563996-33769d00-d92c-11e8-9a75-31c769724977.png">

**Comment by birgitpulk** [comment]
![screen shot 2018-12-03 at 12 48 32](https://user-images.githubusercontent.com/24669779/49369368-edb2ae80-f6f9-11e8-9b79-bf8f7d51caed.png)

**Comment by heldiraudsepp** [comment]
Lisa uus õppeasutus modaalis aadressi riba täislaiuses @madispold teeb 1h
Birgiti testimine 2h
