### ISSUE TITLE
516 täiendus oska sisutüüpide viimine ühe chipi alla

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#552]
Kliendi tagasiside:
Koondada kõik OSKA lehtede tulemused kokku ühe chipi alla mille nimeks oleks "Tuleviku töövõimalused". 

Selgitus: Meil oli raske leida head nime ametiala ja valdkonna asemele. Samas inimene otsib märksõnaga ei tea me jätkuvalt kuhu ta minna tahab. Kui ta soovib saada teada tööturu võimalustest, siis see üks chip koondakski vastused ühte kohta kokku. Kui inimene just ise ei tee väga laia otsingut mõne üldise sõnaga, ei tohiks tulla ka väga palju vasteid OSKA poolelt. Meie poolt pakutud chipi alla inimene saaks ise otsustada, et kas ta tahab minna edasi ametiala, valdkondike uuringute või mõnda muude vaatesse.

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1 üldine: sõna "ala" peaks andma palju vasetid ka OSKA ametialadest aga hetkel ainus otsingu tulem "Ala Põhikool".

**Comment by madispold** [comment]
Viga 1 üldine: Otsing on hetkel skooripõhine ning täis sõnu matchiv nagu ta esialgu sai loodud. See on standard käitumine.

**Comment by TanelTromp** [comment]
TEST OK
