### ISSUE TITLE
Muuta OSKA andmeväljade piiranguid

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#553]
OSKA valdkonna taksonoomia ja #500 

Valdkonna nimi (50 tähemärki) muuta piirang 100 tähemärki
Peavastutaja (50 tähemärki) muuta piirang 100 tähemärki

seotud tööga #473

**Comment by TanelTromp** [comment]
- [x]   Valdkonna nimi (50 tähemärki) muuta piirang 100 tähemärki
- [x]   Peavastutaja (50 tähemärki) muuta piirang 100 tähemärki
