### ISSUE TITLE
Lehe laadimine kiirendatakse valideeruva Accelerated Mobile Pages (AMP) abil

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#559]
https://www.ampproject.org/docs/guides/pwa-amp

**Comment by skeefee** [comment]
Lähtudes erinevatest faktidest saab järeldada, et HTM puhul ei saa AMPi rakendada kuna seda ei saa Angular 5-ga integreerida.
AMP ja Angular 2+ on kaks täiesti erinevat raamistiku kahe täiesti erineva tulemuse saavutamiseks. 

AMP puhul märkasin mitmeid positiivseid omadusi:
* Kiire lehe laadimine
* “Müra” vaba leht
* Otsingutulemustes tavaliselt kõrgemal kui traditsioonilised lehed
* Google built-in lehe preload

Samas on ka negatiivseid külgi mis kaaluvad positiivsed küljed väga tugevalt üle:
* AMP nõuab, et lehel ei ole väliseid javascripti teeke.
* AMP nõuab, et lehel on CSS lähtekoodi kirjutatud. St. et kasutaja peab iga veebilehel tehtud klikiga uuesti css-i alla laadima
* AMPi ei saa teiste javascripti raamistikega koos töötada
* Täiesti teistsuguse HTML markupiga. Ei ole õrna aimugi kas ekraanilugejad seda toetavad.
* Mõeldud staatiliste (Drupal, Wordpress jne )lehtede mitte dünaamiliste (Angular, Vue, React jne) jaoks
* Eelkõige mõeldud uudiste väljaannete kasutamiseks. Arendajad loodavad, et AMP areneb millekski universaalsemaks, et tulevikus keerulisemaid süsteeme sellega ehitada. Kuid see ei ole kindel kas AMP areneb nii kaugele.
* AMP toimib ainult Webkit brauserite puhul. Firefoxi puhul näiteks on AMPi musternäidis ampbyexample.com meeletult aeglane.


Allikad: 
* http://ampbyexample.com/
* https://ampbyexample.com/introduction/hello_world/
* https://steffanhernandez.com/blog/amp-for-dummies/
* https://www.mainstreethost.com/blog/google-amp-explained/

**Comment by erkkijakobson** [comment]
Järgmiseks tutvuda esimese postituse lingil toodud 3 variandiga, kuidas PWA ja AMP lehti integreerida.
