### ISSUE TITLE
Ametialade ja erialade võrdlemise snackbari muudatus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#562]
Snacbar peab olema sinine ehk informatiivne.
Näidis siin: https://zpl.io/a74MjMp

Teksti muuta: Ametiala(d) on võrdluses.

**Comment by skeefee** [comment]
@TanelTromp Uuendus test lehel üleval

**Comment by TanelTromp** [comment]
TEST OK

**Comment by birgitpulk** [comment]
Kujunduse osas ok

**Comment by TanelTromp** [comment]
TEST OK
