### ISSUE TITLE
Kasutaja saab vahetada rolli

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#563]
**Üldkirjeldus:**
Kasutaja on sisse loginud (natural person) töölaua vaates. Kasutaja käivitab rolli vahetamise.
Disaini lingid:
https://zpl.io/VkEGxGL
https://zpl.io/aM9pqRm
BE pilet #538 

**Eeltingimused ja käivitamine:**
* Kasutajale on kuvatud (natural person) töölaud.
* Kasutaja vajutab "Vaheta rolli".

**Vastuvõtutingimused:** 
- [ ] Avaneb modaal, milles kuvatakse rollivahetuse valikuid:
* Kui Äriregistri päringu tulemusel (#538 ) on ettevõtted (on esindusõigus): https://zpl.io/VkEGxGL
* Kui Ettevõtted puuduvad: https://zpl.io/aM9pqRm
- [ ] Kui kasutajal on ettevõte (kuni n arv), siis saab avada ettevõtte (juridical person) töölaua: selle pileti raames tühi tööalud, kus on sarnaselt natural person töölauale nupp "Vaheta rolli", mis avab samuti rolli vahetamise modaali. Teisisõnu kasutaja saab ettevõtte töölaualt rolli vahetamisega tagasi isiklikule tööalauale või mõne teise ettevõtte töölauale (juhul kui oli mitu ettevõtet).
Modaalis saab kasutaja:
- [ ] tegevuse tühistada (modaal sulgub, rolli ei vahetata)
- [ ] modaali sulgeda (modaal sulgub, rolli ei vahetata)

**Täiendavad tingimused:**
- [ ] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [ ] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [ ] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Comment by madispold** [comment]
Testimisse @TanelTromp 

testkasutaja: kasutaja_37606276521
parool: parool

Rollideta vaadet saab testida iga teise kasutajaga.

**Comment by TanelTromp** [comment]
Viga 1: näitab scrollbari, kuigi midagi ei ole kerida:

![pilt](https://user-images.githubusercontent.com/37407917/48260445-2b3a5980-e424-11e8-8a7a-76631628028c.png)

Täpsustus: "Enter" võiks ilmselt ka lisaks spacele radiobuttoni valiku teha. Hetkel ainult "space".

Viga 2 mobiil:  pikema ettevõtte nime korras on joondus paigast ära, peaks joponduma esimese rea järgi:
![pilt](https://user-images.githubusercontent.com/37407917/48261207-f976c200-e426-11e8-9826-bb1c8da070ac.png)

Viga 3 mobiil: ma pigem kasutaks siin: 1.järgmisele reale osa sisu viimist või 2. kolme punkti, mis on paremad, kui hetke pooliku modaali kuvamine + paremale swipemise lahendus, kui on pikk nimi:

![pilt](https://user-images.githubusercontent.com/37407917/48261308-4f4b6a00-e427-11e8-84a7-2ddaa15ddf43.png)

**Comment by birgitpulk** [comment]
- [ ] Mobiilis peaks isiku nimi olema ka link
- [ ] Mobiilis võiks modaal olla full laiuses ja kõrguses

Viga 3: kui tabeli rida liiga pikk, siis võiks muutuda kaherealiseks? @TanelTromp

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.
Viga 3: OK - muutub mitmerealiseks.
Viga 4: OK.

@birgitpulk 
Mobiilis isiku nimi on link, kuid ettevõtte oma pole, seal pole infot taga - OK.
Nüüd mobiilis modaal full laiuses. Kõrguselt asub keskel - oleneb sisu pikkusest.

**Comment by TanelTromp** [comment]
TEST OK

**Vastuvõtutingimused:** 
- [ ] Avaneb modaal, milles kuvatakse rollivahetuse valikuid:
* Kui Äriregistri päringu tulemusel (#538 ) on ettevõtted (on esindusõigus): https://zpl.io/VkEGxGL
* Kui Ettevõtted puuduvad: https://zpl.io/aM9pqRm
- [ ] Kui kasutajal on ettevõte (kuni n arv), siis saab avada ettevõtte (juridical person) töölaua: selle pileti raames tühi tööalud, kus on sarnaselt natural person töölauale nupp "Vaheta rolli", mis avab samuti rolli vahetamise modaali. Teisisõnu kasutaja saab ettevõtte töölaualt rolli vahetamisega tagasi isiklikule tööalauale või mõne teise ettevõtte töölauale (juhul kui oli mitu ettevõtet).
Modaalis saab kasutaja:
- [ ] tegevuse tühistada (modaal sulgub, rolli ei vahetata)
- [ ] modaali sulgeda (modaal sulgub, rolli ei vahetata)
