### ISSUE TITLE
E-tunnistuse kehtivuse kontroll BE

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#567]
Üldkirjeldus:
Sisselogimata kasutaja on teinud päringu e-tunnistuse kehtivuse kontrollimiseks.
Portaali back-end teeb päringu lõimest #248 .

Viited:
Lõime: #248 
FE: #568 
Disain: #566

**Comment by EgleM-TW** [comment]
@ruut12 Lisasin sprinti, kui peaks tekkima aega. Tingimusi ei kirjutanudki lahti - nagu ikka front küsib ja lõime vahendab. Andmekoosseis lõimest.

**Comment by ruut12** [comment]
tunnistuse kehtivuse päring: 
POST test-htm.wiseman.ee:30000/certificate-public?_format=json
body: {id_code:0, certificate_id:"0"}

Tunnistuse allatõmbamiseks link:
test-htm.wiseman.ee:30000/certificate-public-download/{id_code}/{certificate_id}
