### ISSUE TITLE
Kasutajaliideses e-tunnistuse kehtivuse kontroll 

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#568]
**Üldkirjeldus:**
Sisselogimata kasutaja on avanud menüüst lehekülje, mille sisuks on e-tunnistuse kehtivuse kontrolli teenuse vahendamine. Kasutaja täidab sisendparameetrid ja süsteem edastab päringu back-endile andmete kuvamiseks lõime kaudu. #567 
Kujundus desktop: 
https://zpl.io/brWpGvD
Näide teatest: https://zpl.io/V1z5AQ4
Positiivne tulemus: https://zpl.io/VQKnyQ9
Animeeritud _label_: https://angular-3pzk6b.stackblitz.io

**Vastuvõtutingimused:**
  * Lehekülje pealkiri: _Tunnistuse kehtivuse kontroll_
  * Sissejuhatus: 
_Teenus võimaldab kolmandal osapoolel (sh tööandjal) kontrollida tunnistusel olevate andmete kehtivust ja vajadusel ka tunnistus alla laadida. Sisestades tunnistuse numbri ja omaniku isikukoodi kuvatakse vastuseks isiku nimi ning tunnistuse andmete staatus. Mõlema välja täitmine on kohustuslik.
Elektrooniliselt välja antud tunnistusel on samasugune õiguslik jõud nagu varasematel aastatel väljastatud paberkandjal oleval tunnistusel._

* Sisendparameetrid:
   - Tunnistuse omaniku isikukood
   - Tunnistuse number
   - Google captcha sisestamise kohustus
   - Nupp Otsi

**-> Sisestusvälja pealkiri peab üles liikumisel kuvama korrektset [Angular Material animatsiooni](https://stackblitz.com/edit/angular-3pzk6b)!
-> Vaid numbrilist sisendit nõudvad väljad peavad puuteekraanil vaid numbriklaviatuuri avama!**

* Kui sisendparameetrid, sh captcha EI OLE ok, kuvada teade, mis on on EISi päringu vastuses (näiteks: Vigane isikukood) Vt ülal kujunduse viidet.

* Kui sisendparameetrid, sh captcha on ok ja tunnistus olemas, kuvada (vt andmevälju päringus siit #248 ):
   - Teade (NB! Positiivse vastuse korral üldjuhul tühi string) 
   - Ees- ja perekonnanimi
   - Tunnistuse number
   - Tunnistuse olek
   - Registreeritud riigieksamid
     - Eksami aine
     - Toimumise aeg
     - Staatus (variandid: Tulemus teada/ Puudus eksamilt/ Tulemus tühistatud/ Tulemus ei ole teada)
     - Tulemus
     
* Tunnistuse kuvamine ja allalaadimine
    - Päring teha nupule _Lae alla_ vajutamisel.
    - Kui on tunnistus, saab seda (digidoc) alla laadida.
    - Kui tunnistust pole, kuvata "teade". Teade on EISi päringu vastuses.
    - Kui teadet pole siis kuvame: "Tunnistus ei ole saadaval faili kujul e-tunnistusena."

**Viited:**
BE: #567 
Disain: #566 
Label: https://stackblitz.com/edit/angular-3pzk6b?file=app%2Fform-field-appearance-example.scss

**Comment by madispold** [comment]
Testimisse @TanelTromp @birgitpulk 

http://htm.twn.ee/tunnistuse-kehtivus

Testandmed (Hetkel teada vaid 1):
Isikukood: 41103161417
Tunnistuse id: 212-000036-1

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, otsingust ei tule isu välja _või leidnud otsingut kasutades lehekülje, mille sisuks on e-tunnistuse kehtivuse kontrolli teenuse vahendamine_
https://gyazo.com/67d7cf5cbce3a800d98d62a1fd9fc53e

**Comment by birgitpulk** [comment]
Kujunduslikud teemad: 
- [ ] Vormiväljad ei käitu nii nagu mujal (väljadel ei ole hoverit teistes vaadetes, fookuse puhul on piirjoon paksem kui teistes vaadetes)
- [ ] Vormivälja kõrgus 50px, teistes vaadetes 40px
- [ ] Vormiväljale fokusseerides ei peaks välja sees olema placeholder teksti
- [ ] Väiksemate ekraanisuuruste puhul võiks väljade laius jääda samaks (hetkel lähevad väiksemaks). Väljad ei võiks kunagi olla kitsamad kui captcha
- [ ] Mobiilis peaks captcha olema keskele joondatud

**Comment by birgitpulk** [comment]
@TanelTromp 

UX-täiendus 1: Vigane väli võiks olla punane nagu igalpool mujal. Muster võiks olla lehel läbivalt üks. 

Post scriptum: Ma leian, et funktsionaalsused peaks FE arendaja minuga läbi rääkima, kui testija seda teeb, siis kulub liiga palju aega (juba on asi valmis arendatud ja läheb muutmisele). 

UX-täpsustus 2: Nõus, et URL võiks vastata sisulehe pealkirjale.

Sisu täpsustus 2: Selle võiks Egle otsustada.

**Comment by TanelTromp** [comment]
Viga 5 uus: "Laadi alla" font on Zeplinis 16px, testis 14px

Viga 6: tingimus ei ole (enam) täidetud: _Vaid numbrilist sisendit nõudvad väljad peavad puuteekraanil vaid numbriklaviatuuri avama!_

**Comment by EgleM-TW** [comment]
@TanelTromp eemaldasin nõuetest otsingu kaudu lehele navigeerimise. Ja asukoha navigatsioonis lahendame uue töö raames.

**Comment by TanelTromp** [comment]
TEST

Vastuvõtutingimused:

- [ ] Lehekülje pealkiri: Tunnistuse kehtivuse kontroll

- [ ]  Sissejuhatus:
 
Teenus võimaldab kolmandal osapoolel (sh tööandjal) kontrollida tunnistusel olevate andmete kehtivust ja vajadusel ka tunnistus alla laadida. Sisestades tunnistuse numbri ja omaniku isikukoodi kuvatakse vastuseks isiku nimi ning tunnistuse andmete staatus. Mõlema välja täitmine on kohustuslik.
Elektrooniliselt välja antud tunnistusel on samasugune õiguslik jõud nagu varasematel aastatel väljastatud paberkandjal oleval tunnistusel.

- [ ] Sisendparameetrid:

        Tunnistuse omaniku isikukood
        Tunnistuse number
        Google captcha sisestamise kohustus
        Nupp Otsi

- [ ] Sisestusvälja pealkiri peab üles liikumisel kuvama korrektset Angular Material animatsiooni **eraldi angulari: Angular Material 7 üleminek #736**
- [ ] Vaid numbrilist sisendit nõudvad väljad peavad puuteekraanil vaid numbriklaviatuuri avama **käitub nii vaid esimene väli, teine mitte, arendaja põhjendus all**

- [ ] Kui sisendparameetrid, sh captcha EI OLE ok, kuvada teade, mis on on EISi päringu vastuses (näiteks: Vigane isikukood) Vt ülal kujunduse viidet.

Kui sisendparameetrid, sh captcha on ok ja tunnistus olemas, kuvada (vt andmevälju päringus siit #248):

- [ ]         Teade (NB! Positiivse vastuse korral üldjuhul tühi string)
- [ ]         Ees- ja perekonnanimi
- [ ]         Tunnistuse number
- [ ]         Tunnistuse olek

 Registreeritud riigieksamid
- [ ]        Eksami aine
- [ ]        Toimumise aeg

- [ ]       Staatus (variandid: Tulemus teada/ Puudus eksamilt/ Tulemus tühistatud/ Tulemus ei ole teada) **puuduvad EHIS testandmed, et variante: "Puudus eksamilt/ Tulemus tühistatud/ Tulemus ei ole teada" testida**
- [ ]       Tulemus

Tunnistuse kuvamine ja allalaadimine

- [ ]         Päring teha nupule Lae alla vajutamisel.
- [ ]         Kui on tunnistus, saab seda (digidoc) alla laadida.
- [ ]         Kui tunnistust pole, kuvata "teade". Teade on EISi päringu vastuses. **puuduvad EHIS testandmed**
- [ ]         Kui teadet pole siis kuvame: "Tunnistus ei ole saadaval faili kujul e-tunnistusena."  **puuduvad EHIS testandmed**


-------
Kuvatõmmis

![pilt](https://user-images.githubusercontent.com/37407917/52110070-2ee71200-2608-11e9-9576-2d12f1e6950a.png)
