### ISSUE TITLE
xDzeison definitsioon kontrollide dokumentatsioon wikisse

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#569]
- [ ] Kontrollida, kas piletis kirjeldatud #239 xDzesion definitsiooni kontrollid vastavad realiseeritule.
- [ ] Teha wiki-sse kontrollide dokumentatsiooni leht.

**Comment by ruut12** [comment]
Dok. asub [link](https://github.com/hariduspilv/haridusportaal/wiki/xDzeison-definitsioon-kontrollide-dokumentatsioon)
