### ISSUE TITLE
Muudatus: kui kasutaja sulgeb brauseri, siis logib süsteem kasutaja välja

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#574]
Hetkel välja logimist ei toimu ja isikuandmete tõttu sisaldab see turvariski

**Comment by skeefee** [comment]
Korras. Võib testida

**Comment by TanelTromp** [comment]
TEST

*Testitud hetkel testkeskkonnas töötavate autentimismeetoditega:*

- [ ] TARA+Mobiil-ID
- [ ] TARA+Pangalink
- [ ] TARA+Smart-ID

*Kasutajanime ja parooliga:*

- [ ] Chrome
- [ ] Mozilla
- [ ] Safari
- [ ] IE11
- [ ] Edge
