### ISSUE TITLE
Tagasiside komponent sisulehele

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#575]
1. Kõikide sisulehtede detailvaadetele tekitada tagasiside küsimise komponent, mis koosneb:

- Küsimus "Kas said leheküljelt vajaliku info"
- Vastusevariandid:
    1. Jah, leidsin kõik vajaliku
    2. Ei leidnud vajalikku infot

2. Juhul kui kasutaja valib "Jah, leidsin kõik vajaliku", kuvab süsteem vastuseks "Aitäh tagasiside eest"
3. Juhul kui kasutaja valib "Ei leidnud vajalikku infot" avab süsteem kommentaari lisamise lahtri küsimusega "Kuidas saaksime lehte parandada"

Kujundus: [Disaini link](https://zpl.io/VKomPKX)
Thumbs-up vajutades: [Disaini link](https://zpl.io/Vx1MLwm)
Thumbs-down vajutades: [Disaini link](https://zpl.io/VD45BKg)

BE pilet #609

**Comment by birgitpulk** [comment]
@erkkijakobson 

2 kujundusvarianti: 
1. Kujundus thumbs-up/thumbs-down elementidega
<img width="632" alt="screen shot 2018-11-26 at 15 07 13" src="https://user-images.githubusercontent.com/24669779/49016005-690de080-f18d-11e8-8c05-d0d47503fd2f.png">

2. Kujundus emotikonidega (keskmine ja vasakpoolne käivitaksid tagasisidekasti)
<img width="728" alt="screen shot 2018-11-26 at 15 08 07" src="https://user-images.githubusercontent.com/24669779/49016039-804cce00-f18d-11e8-9be1-d862c894be33.png">

**Comment by birgitpulk** [comment]
Peale positiivse tüki vajutamist tekiks selline info: 
<img width="629" alt="screen shot 2018-11-26 at 15 12 14" src="https://user-images.githubusercontent.com/24669779/49016085-b2f6c680-f18d-11e8-8b2a-91c1f85e6587.png">

Peale negatiivse tüki vajutamist tekiks selline info: 
<img width="621" alt="screen shot 2018-11-26 at 15 12 23" src="https://user-images.githubusercontent.com/24669779/49016107-bee28880-f18d-11e8-8a5f-c42d6e0e9be3.png">

**Comment by heldiraudsepp** [comment]
@erkkijakobson Palun disainile kinnitust

**Comment by birgitpulk** [comment]
Jääb esimene variant (thumbs-up, thumbs-down)

**Comment by TanelTromp** [comment]
UX-täiendus 1: "Kommentaari" väljale fookuse/type ready viimisel peaks hint" "Kommentaar" kaduma.

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: See on IE11 ja angulari vaheline konflikt. Ilmselt tulevases angular versioonis korras.
Ux 1: Erinevad brauserid käituvad placeholderiga erinevalt
UX 2: Me ei sunni inimesele kommentaari peale
UX 3: Korras

**Comment by skeefee** [comment]
UX-täpsustus: BE peaks sessiooni põhiselt kontrollima seda

**Comment by birgitpulk** [comment]
Text area vale kujundusega, läheb piletisse #549. Muus osas kujundus korras.
