### ISSUE TITLE
Infograafika täiendused sisuhalduses

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#576]
31.10.2018 koosolekul räägitu põhjal teha järgmised täiendused sisuhalduses infograafika toimetamisel:

1. Graafiku lisamisel esmalt graafiku tüübi valik:
* Simple Infographic - see on tavapärane realiseeritud variant
* Combo Infographic - see on realiseeritud combo, mille tõstame nö eraldi
* Multi Infographic - see on uus lisanduv töö

Simple- ja Combo Infographic:

2. Graafikule nime (title) lisamine - #561 
3. Graafiku tüübi valik - valikust eemaldada scatter, teised jäävad - line, bar, column, pie, doughnut.
4. Näitaja valik
5. x-telje valik (filtri valikud - #537 )
6. Filtrite valik: valdkod, alavaldkond, ametiala, periood, silt.

Multi Infographic:

2. Graafikule nime (title) lisamine 
3. Graafiku tüübi valik - bar,  column
4. Näitaja valik
5. x-telje valik
6. Grupeeringu valik (tingimus: kui väärtsi pole siis summeerime ikka kokku)
7. Filtrite valik

Lisaks:
Lars uurib, kas õnnestub x-telge anda kuvamiseks tähestikuliselt (ei testi seda selle töö raames)
Lars muudab indikaatorite impordis: põhikutseala = ametiala (seda ka üle ei testi)

**Comment by EgleM-TW** [comment]
@lsoonvald palun lisa arenduse töömaht (estimate) ka, see 5 on testimiseks.

**Comment by EgleM-TW** [comment]
Saadan meeldetuletuse andmetega CSV saamiseks. Testida saab ainult backis infograafika lisamise ülesehitust. Kuvamise töö alles uues sprindis.

**Comment by TanelTromp** [comment]
Viga 1: graafiku nimel ei ole 100 tähemärgi piirangut

Täpsustus/muudatus 1: juba varem märkasin, et perioodi kuvamise valik ja kuvamine FE-s "2010/12" kujul on eskitav - tundub, et peale kaldkriipsu on kuu, mitte aasta. Peaks võimalusel välja kuvama "2011/**20**12" tervikuna @EgleM-TW

**Comment by EgleM-TW** [comment]
Need andmed tulevad nii või naa CSV-st sellisel kujul nagu OSKA tiim nad sisestab. Selline imelik jaotus on kolme aasta libisev keskmine. Kasutavad seda teatud näitajate puhul kus statistika võib-olla kõikuv kui vaadata aastaid eraldi. Eks selle kohta on neil tekstiline selgitus.

**Comment by TanelTromp** [comment]
TEST OK
