### ISSUE TITLE
Infograafika teksti suurus ja värvitoonid

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#578]
Soovid:
- Graafikute pealkirjad peaksid eristuma suurema tekstina praegusest. Birgiti kommentaar: Graafiku pealkirja maksimaalne suurus saab olla sisuteksti suurus, sest teksti sees me ei kasuta suuremaid pealkirju.
- Fondid graafikutel ja muul tekstil võiks olla samad.
- Igal graafikutüübil võiks olla oma kindel värv - line, bar, column, pie, doughnut (31.10.18 koosolek). Birgiti kommentaar: Ei ole teostatav, raske eristada nt jooni graafikul
 
Kirjutada reeglid FE piletisse #677

**Comment by heldiraudsepp** [comment]
@skeefee uurib, milliseid võimalusi soovidest on võimalik realiseerida

**Comment by RainLeoma** [comment]
Sobib

**Comment by EgleM-TW** [comment]
Soovide realiseerimine uue tööga #755
