### ISSUE TITLE
Valdkonna lk kuvamise parendus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#579]
OSKA valdkondade nimekirja vaade - https://zpl.io/VOkO6B1
Eemaldada nii disainist kui ka realiseeritud lahendusest Ruudustik/ Võrdlus valikud.

Jääb ainult Ruudustik. Võrdluse lahendasime infograafika toimetamisega.

@TanelTromp  teadmiseks.

**Comment by madispold** [comment]
@birgitpulk vajab kinnitust. Esialgu eemaldasin vaid valiku ning eraldusjoone jätsin, kas jääb nii?

**Comment by birgitpulk** [comment]
@madispold Mulle meeldib see eraldusjoon seal vahel. Kas saaksime selle joone teistele listvaadetele ka lisada? Siis oleks kõik ühtlasem.

**Comment by madispold** [comment]
@birgitpulk Igal listivaatel eraldusjoon.

**Comment by birgitpulk** [comment]
Kujunduse osas ok!
