### ISSUE TITLE
Ettevõtja töölaua kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#580]
**Üldkirjeldus:**
Kasutajaga seotud ettevõtte töölaual kuvatakse koolide andmeid.
Disain: https://zpl.io/aM9P8po

**Eeltingimused ja käivitamine:**
* Kasutaja on käivitanud rolli vahetamise. Realiseeritud on #563.
* Kasutajal on ettevõte (1..n), mille töölaua ta avab.
* Töölaual koolide andmete kuvamiseks tehakse päring back-endist #540.
* Kasutaja ettevõttel on EHIS's registreeritud kool (1..n) (Kui kooli pole #581 )
* Süsteem avab vaikimisi ettevõtte töölaual "Taotlused".

**Vastuvõtutingimused:** 
* Töölaual kuvatakse valitud ettevõtte nimetust, vt disaini (kui see tuleb lõime #214 päringuga ("owner" : yldandmed/omanik) siis kasutada seda).
* Infoteksti (message) kuvatakse koolide üleselt, vt andmekoosseisu #214 ja disainis esimene infotekst. Kui infotekst puudub siis akordion liigub selle võrra ülespoole.
* Koolid kuvatakse akordionis (ühe kooli andmed ühe akordioni sees).
* Kooli nimetus ja nimetus inglise keeles (name/ nameENG) on akordioni pealkiri.
* Kui kasutajal on 1 kool siis akordion on avatud, 
* Kui kasutajal on üle ühe kooli siis akordion on suletud.
Ühe kooli andmed kuvatakse akordionis mitmes osas:

1. Üldandmed, vt andmekoosseisu #214 ja disaini: https://zpl.io/aM9P8po
* Muuda nupp ulatub nende väljadeni, mida kasutaja saab muuta (#581 ) Disainis lahendatule lisandub aadressi väli),
seega muudetavate andmete sildid on:
   - Telefon - "contactPhone" : kontaktandmed/oppeasutuseYldtelefon,
   - E-post - "contactEmail" : kontaktandmed/oppeasutuseEpost
   - Veebileht - "webpageAddress" : kontaktandmed/koduleheAadress 
   - Aadress - "addressHumanReadable" : aadress/adsAadressHumanReadable 

muuta ei saa:
   - Õppeasutuse liik - "studyInstitutionType" : yldandmed/klOppeasutuseLiik 
   - Omandivorm - "ownershipType" : yldandmed/klOmandivorm
   - Pidaja liik - "ownerType" : yldandmed/klPidajaLiik

2.
Andmekoosseis: https://github.com/hariduspilv/haridusportaal/blob/master/docs/dokumendivormid/mtsystegevusload.txt

Infotekst "message": asutus/oppeasutus/tegevusnaitajad/tninfotekst 

Esitatavad taotlused (_applications_ päringu vastuses objekt _acceptable_forms_):
* Kuvatakse esitatavate taotluste "kaardid"
* Iga esitatava taotluse kohta kuvatakse nimetus (form_name) + (description), kasutaja poolt valitud keeles või kui selles keeles _title_ puudub, siis 'et' keeles. _jätkutöö #235_ 
* Kasutaja saab alustada dokumendivormi sisestamist #425; URL... /xjson/_form_name_)
* Esitatavad taotlused kuvatakse nimetuste (form_name) järjekorras (kaartide järjekord jookseb "ridu pidi" ehk järjekord liigub esmalt vasakult paremale ja teiseks ülalt alla).
* Vaikimisi kuvatakse kuni 4 esitatavat taotlust. Kui esitatavaid taotlusi on rohkem kui 4, siis kuvatakse "näita rohkem (nn)", nn on peidus olevate esitatavate taotluste arv (koguarv - 4). "Näita rohkem" peale klikkides kuvatakse kõik esitatavad taotlused. 
* Kui päringu tulemusena ei saadud ühtegi esitatava taotluse kirjet, siis kuvatakse teade "Praegu ei saa esitada ühtegi taotlust".

3.

Pooleli olevad taotlused (_applications_ päringu vastuses objekt _drafts_):
* Kuvatakse pooleli olevate taotluse tabel
* Iga pooleli oleva taotluse kohta kuvatakse nimetus (form_name) kasutaja pool valitud keeles või kui selles keeles nimetus puudub, siis 'et' keeles; Loomise kuupäev (document_date). 
* Kui päringu vastuses on olemas kirjeldus (description), siis see kuvatakse eelnevalt nimetatud andmete all eraldi real.
* Pooleli taotlused kuvatakse nimetuste järjekorras.
* Kasutaja saab jätkata dokumendivormi sisestamist. 
-- FE teeb dokumendi mustandi saamiseks BE-st xsjon päringu (#540 ) sisenditega: _draft_ = true, _form_name_ ja _identifier_.
-- FE avab dokumendi sisestamise ekraanivormi kasutades päringu vastust.
* Kui _applications_  päringu tulemusena ei saadud ühtegi pooleli oleva taotluse kirjet, siis kuvatakse teade "Pooleli olevaid taotlusi ei ole".

4.

Taotlused ja otsused (_applications_ päringu vastuses objekt _documents_):
* Kuvatakse taotluse ja otsuste tabel
* Taotluse või otsuse kohta kuvatakse nimetus (form_name), kuupäev (document_date) ja staatus (status). Nimetus kuvatakse kasutaja pool valitud keeles või kui selles keeles puudub, siis 'et' keeles
* Kui taotluse või otsuse kohta on olemas kirjeldus (_description_), siis see kuvatakse eelnevalt nimetatud andmete all eraldi real.
* Taotlused ja otsused kuvatakse kuupäevade järjekorras kahanevalt (uuemad eespool).
* Kasutaja saab alustada dokumendi vaatamist. 
-- FE teeb dokumendi saamiseks BE-st xsjon päringu (#xxx) sisenditega: _existing_ = true, _form_name_ ja _identifier_.
-- FE avab dokumendi sisestamise ekraanivormi kasutades päringu vastust (kuna _acceptable_activity_ on "VIEW", siis sisestamise ekraanivorm töötab antud juhul kuvamise ekraanivormina).
* Kui _applications_ päringu (#xxx) tulemusena ei saadud ühtegi taotluse või otsuse kirjet, siis kuvatakse teade "Dokumente ei ole".

Täpsutamised Andrusega.

**Comment by madispold** [comment]
Testimisse @TanelTromp 

Ettevõtja rolli alt x kasutajaga järgnevad 3 test-case'i:
http://htm.twn.ee/et/toolaud/taotlused?version=1
http://htm.twn.ee/et/toolaud/taotlused?version=2
http://htm.twn.ee/et/toolaud/taotlused?version=3

Dokumentide taga ei ole enamuses töötavaid linke kuna pole vastavaid xjson otsi. Toimib aga näiteks MTSYS_TEGEVUSLUBA tüüpi vormide kuvamine.

Mõned kujunduse erinevused analoogsete teiste töölaua sakkide ja isiku rollis "Taotluste" vaatega - hetkel mõnes kohas jätsin samaks varasemaga. Vaja arutada @birgitpulk

**Comment by TanelTromp** [comment]
Viga 1: "Muuda", "Näita rohkem", "Ava", "Jätka täitmist" lingid on väiksema fondiga, kui zeplinis:

![pilt](https://user-images.githubusercontent.com/37407917/48610722-c5068700-e98d-11e8-8dd3-848d0944085f.png)

**Comment by TanelTromp** [comment]
Viga 1: ma näen ikka, et üks on 16px ja teine 14px :
https://gyazo.com/8f073d46ff263a947defa723870a2844

**Comment by madispold** [comment]
Viga 1: Natural person rolli all ei olnud seda muudatust tehtud - nüüd OK.

**Comment by TanelTromp** [comment]
TEST OK

**Testitud "dummy" dataga ja ilma reaalsete lõimete ja päringutega**

**Comment by TanelTromp** [comment]
@birgitpulk

**Comment by birgitpulk** [comment]
- [ ] Ükski sakk ei ole valitud enne rollivahetust
<img width="675" alt="screen shot 2019-01-14 at 13 12 30" src="https://user-images.githubusercontent.com/24669779/51109495-113f3d80-17fe-11e9-8b55-6a861df667b7.png">

- [ ] Akordioni avamisel võiks olla akordioni täis pealkiri näha, hetkel jääb kolme punktiga

**Comment by birgitpulk** [comment]
@madispold

**Comment by madispold** [comment]
- [x] Ükski sakk ei ole valitud enne rollivahetust - kasutades dummy data versioone url'il tõesti pole, muidu on ehk tavakäitumises.
