### ISSUE TITLE
Õppeasutuse lisamine ja muutmine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#581]
**Üldkirjeldus:**
Variant 1: Kasutajaga on seotud ettevõte, kuid sellega pole seotud ühtegi kooli. Kasutaja lisab ettevõttele kooli.
Variant 2: Kasutaja valib töölaual kooli ja muudab selle andmeid.

Kooli lisamise alustamise disain: https://zpl.io/aM9P8po, kui kasutaja vajutab "Lisa uus õppeasutus" avaneb andmete lisamise vorm, vt disain: https://zpl.io/bA4LDqO

Muutmise vorm: https://zpl.io/aM9ejmr

**Eeltingimused ja käivitamine:**
* Kasutaja on käivitanud rolli vahetamise. Realiseeritud on #563.
* Kasutajal on ettevõte (1..n), mille töölaua ta avab.
* Töölaual koolide andmete kuvamiseks tehakse päring back-endist #540.
* Variant 1: kasutaja ettevõttel on EHIS's registreeritud kool (1..n), mille andmeid ta muudab.
* variant 2: kasutaja ettevõttel pole kooli ja ta valib "Lisa uus õppeasutus" .

**Vastuvõtutingimused:** 

Variant 1
* Kasutaja saab muuta:
   - Telefon - "contactPhone" : kontaktandmed/oppeasutuseYldtelefon,
   - E-post - "contactEmail" : kontaktandmed/oppeasutuseEpost
   - Veebileht - "webpageAddress" : kontaktandmed/koduleheAadress 
   - Aadress - "addressHumanReadable" : aadress/adsAadressHumanReadable*
Õppeasutuse andmete muutmine back-endile #543 

Variant 2
* Kasutaja saab lisada:
   - Telefon - "contactPhone" : kontaktandmed/oppeasutuseYldtelefon,
   - E-post - "contactEmail" : kontaktandmed/oppeasutuseEpost
   - Veebileht - "webpageAddress" : kontaktandmed/koduleheAadress 
   - Aadress - "addressHumanReadable" : aadress/adsAadressHumanReadable
   - Õppeasutuse liik - "studyInstitutionType" : yldandmed/klOppeasutuseLiik 
   - Omandivorm - "ownershipType" : yldandmed/klOmandivorm
   - Pidaja liik - "ownerType" : yldandmed/klPidajaLiik

**Aadressiandmete lisamisel/ muutmisel kasutada In-ADS päringut** (täpsustada, kas saab kasutada #231 )
(Kasutajale kuvada vabatekstiväli, mille järgi süsteem otsib)

Klassifikaatori väärtused annab back-end lõimest (#213 ), kuvatakse rippmenüüs.
**Omandivormi klassifikaatori väärtused:**
   - eraomand
   - munitsipaal
   - avalik-õiguslik
   - riigiomandus

**Õppeasutuse liik klassifikaatori väärtused:**
   - noortelaager
   - täienduskoolitusasutus

**Pidaja liik klassifikaatori väärtused:**
   - äriühing
   - kogudus
   - kohalik omavalitsus
   - riik
   - avalik-õiguslik juriidiline isik või tema asutus
   - mittetulundusühing
   - sihtasutus
Õppeasutuse lisamine back-endile #542 

* Kui kasutaja salvestab andmed, kuvatakse infoteksti (message) ja laetakse uuesti töölaud - BE #542 
Kasutajale kuvatakse töölauda uuendatud andmetega.

Teada olevad infotekstid:
'Õppeasutuse andmed lisatud!' , 'Õppeasutuse andmed muudetud!' , 'ID does not exist' ja 'Tehniline viga!'

Kuvamine: https://zpl.io/adPdKAe 
Error: 'ID does not exist' ja 'Tehniline viga!' - kui õnnestub, asendada 'ID does not exist'-- "Tehniline viga!"
Edukas toiming: 'Õppeasutuse andmed lisatud!' , 'Õppeasutuse andmed muudetud!'

**Comment by madispold** [comment]
Testimisse @TanelTromp .

Lisamise nupp on testimise võimaldamiseks alati vaatel. Hetkel ei toimi aadressi muutmine.

**Comment by TanelTromp** [comment]
Viga 1-4: lisamise modaalil:

**Comment by birgitpulk** [comment]
Viga 12.1 mobiil: see modaal peaks olema sulevad ka "Sulge" nupust, mitte ainult "x"-st. Dekstopis joondada keskele, mitte paremasse äärde "Sulge modaal" valik. Mina kasutaks ainult "Sulge" ilma "modaal"-ita seal. @birgitpulk ütleb kuidas tahab

Sündmuse registreerimise juures kasutasime "Sulge aken" ja see võiks jääda visuaalselt akna keskele, paremalt-vasakult samapalju ruumi.

**Comment by madispold** [comment]
@TanelTromp @birgitpulk 
Viga 1: OK
Viga 2: OK.
Viga 3: OK.
Viga 4: OK.
Viga 5: OK.
Viga 6: Lisatud väljadele valideerumise tingimused, mis nüüd selgitavad, lisaks selgitab väljade puudumise korral olukorda infotekst: " * märgitud väljad on kohustuslikud " - OK.
Viga 7: OK.
Viga 8: OK.
Viga 9: Hetkel jätsin nõnda - saab kerida mööda välja, tuleb väljade loogika ümber teha/täiendada et mitmerealiseks teha. - NOT OK.
Viga 10: OK
Viga 11: Korrektse aadressi objekti valideerimine ei luba seda - NOT OK.
Viga 11.2: OK.
Viga 12: OK.
Viga 12.1: OK.
Viga 13: OK.
Viga 14: OK.
Viga 15: Lisamise järjekord vastavalt sellele, kuidas päringust tuleb, variant oleks Indrekuga rääkida - NOT OK, võib ka jääda vast, kui seal tavaliselt pole 30 asutust.
Viga 16: OK.
Viga 17: OK.
Viga 18: OK.
Viga 19: Sõltub materiali komponendi käitumisest ehk nii ta ongi.
Viga 20: Vaata viga 9 - NOT OK.
Viga 21: OK.
Viga 22: OK.
Viga 23: OK.
Viga 24: OK.
Viga 25: OK.
Viga 26: OK.
Viga 27: OK.
Viga 28: OK.
Viga 29: OK.
Viga 30: OK.
Viga 31: Kui avada dropdown, siis ütleb a. la "Item 2 of X" - OK.
Viga 32: OK.
Viga 33: OK.
Viga 34: OK.
Viga 35: OK.
Viga 36: Keerukam loogika, kuna pole teada, mis kõige uuem on, peaks nimega "matchima" vms - NOT OK.
Viga 37: OK
Viga 38: Aadress päringus nõutud hetkel, ehk peab jääma, variant Indrekuga rääkida - NOT OK.
Viga 39: OK.
Viga 40: OK.
Viga 41: OK.
Viga 42: OK.
Viga 43: Akordion on materiali element sügava htmliga, ei saa muuta aria atribuute - NOT OK.
Viga 44: OK.

Birgiti kommentaarid üle käidud - Viga 9 jäi eelmainitud põhjuse tõttu nii nagu ta on.

**Comment by birgitpulk** [comment]
- [ ] Mobiilis töölaual sakkide all peaks olema ka hall joon
- [ ] Mobiilis modaali kerimisel võiks kollane joon modaali külge fikseerituks jääda, hetkel jääb brauseri riba külge
- [ ] Mobiilis ei tööta kerimine kui ühtegi välja ei ole valitud
- [ ] "Salvesta" nupp võiks alati olla aktiivne, nupule vajutamisel võiks ta indikeerida kohustuslikud väljad, mis on täitmata/valimata
- [ ] Dropdowni klikkimisel ja sulgemisel, kui valikut ei ole tehtud, siis võiks dropdown jääda oma tavalisse seisu (tekst ei lähe punaseks). Dropdowni kast läheb punaseks ja sinna alla tekib tekst juhul kui valik on tegemata ja kasutaja on vajutanud "Salvesta"

**Comment by TanelTromp** [comment]
Viga 16: endiselt ei luba kirillitsat sisestada:
![pilt](https://user-images.githubusercontent.com/37407917/49719125-ee50c500-fc64-11e8-9297-3c90ffb48492.png)

Viga 45 uus IE11: täidan kõik väljad, salvestan ja annab veateate aga ei ütle, mis viga on:

![pilt](https://user-images.githubusercontent.com/37407917/49719290-63bc9580-fc65-11e8-9ab8-6cf854edc014.png)

**Comment by madispold** [comment]
Viga 16: Lubab, kuid sul on jäänud pildil üks tühik emaili ette.
Viga 28: Modaali avamisel fokusseerib  esimesena paremal üleval sulgemise nupu ehk esimese CTA. Koheselt ENTERi vajutusel siis ka sulgeb. Kas peaks muutma?
Viga.

ToBeContinued...

**Comment by birgitpulk** [comment]
Nõustun taneliga (vt eelmine kommentaar). Aga kas fookus peaks olema modaali pealkirjal siiski kõigepealt ja siis esimene sisestusväli? @TanelTromp

**Comment by madispold** [comment]
Viga 28: OK vastavalt kommentaaridele. Esmane fookus pealkirjal.
Viga 45: OK.
Viga 46: Kui kerida peale avamist ei liigu kaasa - ei leidnud hetkel kiiret lahendust.
Viga 47: OK.
Viga 48: OK.

@TanelTromp

**Comment by TanelTromp** [comment]
Viga 49 uus WCAG:   "Aadressi" väljal sisestades peab ette lugema vasteid, kui neid tekib (sarnaselt üldotsingu autocompletele).

**Comment by madispold** [comment]
Viga 49: OK.
Lisaks @birgitpulk eelnevad kommentaarid OK.

**Comment by TanelTromp** [comment]
TEST OK

Vastuvõtutingimused:

Variant 1

Kasutaja saab muuta:

- [ ] Telefon - "contactPhone" : kontaktandmed/oppeasutuseYldtelefon,
- [ ] E-post - "contactEmail" : kontaktandmed/oppeasutuseEpost
- [ ] Veebileht - "webpageAddress" : kontaktandmed/koduleheAadress
- [ ] Aadress - "addressHumanReadable" : aadress/adsAadressHumanReadable*
- [ ] Õppeasutuse andmete muutmine back-endile #543

**Comment by EgleM-TW** [comment]
@TanelTromp, lisasin  - Kasutaja saab lisada:
   - Õppeasutuse nimi - "name" : yldandmed/oppeasutuseNimetus,
   - Õppeasutuse nimetus inglise keeles - "nameENG" : yldandmed/oppeasutuseNimetusIngliseKeeles,
