### ISSUE TITLE
Favoriitide päring täiendus

### ISSUE THREAD

**Issue by ruut12** [hariduspilv/haridusportaal#582]
Graphql päringutesse on lisatud võti isFavorite.
See tuleks asendada praeguse loogikaga kus küsitakse BE'st kõik kasutaja favoriidid ja siis kontrollitakse kas on olemas või ei.

**Comment by madispold** [comment]
Tehtud.

**Comment by TanelTromp** [comment]
Viga 1: modaalil ei tööta "Tagasi töölauale" nupp, st ei vii tagasi töölauale, vaid sulgeb modaali ja viib lahti olnud sisulehe detailvaatesse:

https://gyazo.com/51a0c78f78cc86eb2749676ba8d2d66e

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK - scrollbar seetõttu, et sisu puudub ja share komponent ulatub vaate alla. Kokkulepe, et jääb nii, kuna sisuta lehti ei looda.
Viga 3: OK - Mobiilis ära kaotatud.

**Comment by madispold** [comment]
Ekstra päringud ära võetud.
@ruut12 Vaja koos eri listipäringut vaadata. Tundub, et test-htm.wiseman.ee on OK, aga htm.wiseman.ee mitte.

**Comment by TanelTromp** [comment]
Viga 4: kahjuks ei tööta Chromega.

http://htm.twn.ee/artiklid/%C3%B5hikooli-l%C3%B5pueksamite-praegune-kord-ei-t%C3%A4ida-eesm%C3%A4

**Comment by madispold** [comment]
@ruut12

**Comment by TanelTromp** [comment]
Viga 5 iPhone/iPad+safari; android: ei saa lemmikud lisada ega eemaldada

**Comment by TanelTromp** [comment]
TEST OK

Töötab testkasutajaga:

Testkasutajad:
wiseadmin/********
