### ISSUE TITLE
lõimele post document sisendi täiendused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#587]
Lisada post document teenuse sisendisse:
- kasutaja isikukood
- kasutaja nimi
- ettevõtte reg nr (kui esindab ettevõtet)
- ettevõtte nimetus  (kui esindab ettevõtet)
- õppeasutuse id (FE edastab sõltuvalt sellest, mis õppeasutuse alt töölaualt lisamine käivitati)
- õppeasutuse nimetus
- parameters
https://github.com/hariduspilv/haridusportaal/blob/master/docs/dokumendivormid/teenused.json

Kasutatakse näiteks mtsys tegevusloa taotluse raames vaikeväärtuste omistamiseks.

**Comment by IndrekVallsalu** [comment]
{
    "header": {
        "endpoint": "EHIS",
        "form_name": "MTSYS_TEGEVUSLUBA_TAOTLUS",
        "acceptable_activity": [],
        "current_step": null,
        "identifier": null,
        "agents" : [
			{
				"person_id" : "12345678901",
				"person_name": "test isik",
				"role" : "TAOTLEJA",
				"owner_id": 11037064,
				"owner_name" : "test OÜ",
				"educationalInstitutions_id" : 123,
				"educationalInstitutions_name" : "test kool",
			}
		],
		"parameters" : { "aasta" : 2018 }
    }
}
