### ISSUE TITLE
OSKA sisuhaldaja roll tekitada

### ISSUE THREAD

**Issue by lsoonvald** [hariduspilv/haridusportaal#591]
Saab lisada/muuta/kustutada OSKAga seotud sisulehti/csv andmeid.

**Comment by TanelTromp** [comment]
TEST OK

CSV lisamine:
![pilt](https://user-images.githubusercontent.com/37407917/48412667-03156800-e74e-11e8-9722-6092c51f48d9.png)

SISU lisamine:

![pilt](https://user-images.githubusercontent.com/37407917/48412791-6ef7d080-e74e-11e8-994f-bd48b78aac30.png)
