### ISSUE TITLE
Ettevõtja töölaua muudatused ja lisad disain

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#594]
Mis juhtub kui Muuda nupule vajutada?
Mis juhtub Lisa õppeasutus vajutades?
Aadress rida: saab muuta, lisa tabelisse

**Comment by EgleM-TW** [comment]
@birgitpulk Palun kujunda selle pileti raames ka infoteksti kuvamine, kui kasutaja on kas andmed muutnud või lisanud uue õppeasutuse ja saanud tagasi message teate. Teate sisud sellised:
'Õppeasutuse andmed lisatud!' , 'Õppeasutuse andmed muudetud!' , 'ID does not exist' ja 'Tehniline viga!'
NB! Aga kuvame alati ühtemoodi, sest tegelikult me ei tea, milline teade on.
