### ISSUE TITLE
Sisuleht OSKA valdkond tõlked ja kasutusjuhendisse

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#598]
Lars: Kontrollida, et sisuhalduse elemendid vastavad piletis toodud kirjeldustele (tõlked). Kui on korras, siis tõsta testimisse, mis tähendab, et Tanel saab kasutusjuhendisse sisutüübi ära kirjeldada.

**Sisulehe põhiosa elemendid:**
- Pealkiri, kohustuslik, maksimaalne pikkus 100
- Sissejuhatus, vabatahtlik, maksimaalne pikkus 300, plain-text
- OSKA valdkonna video, vabatahtlik, 0..1, URL link ja video kirjeldus
- Sisu, kohustuslik, WYSIWYG redaktori võimalused 
- OSKA valdkonna link, vabatahtlik, 0..n, lingi tekst ja URL
- OSKA valdkonna fail, vabatahtlik 0..n, nimetus ja faili manus
- OSKA valdkonna pilt, vabatahtlik, 0..2, pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud

- Infograafika - vabatahtlik  - kui võimalik tuua lisamine enne akordioni

Järjekord ja tõlked (**sama kehtib ka "OSKA ametiala", "OSKA tulemused" ja "OSKA tööjõuprognoos" sisulehtedele**):

1. Infograafika tüüp 
Simple puhul:
2. Graafiku nimi (title) 
3. Graafiku tüüp  
4. Graafiku x-telg
5. OSKA näitaja
Filtrid:
6. OSKA valdkod
7. OSKA alavaldkond
8. OSKA ametiala
9. OSKA silt
9. Periood

Combo puhul:
2. Graafiku nimi (title) 
3. Graafiku tüüp  
4. Graafiku x-telg
5. OSKA näitaja
Filtrid:
6. OSKA valdkod
7. OSKA alavaldkond
8. OSKA ametiala
9. OSKA silt
9. Periood
10. Teise graafiku tüüp
11. Teise graafiku näitaja

Multi puhul:
2. Graafiku nimi (title) 
3. Graafiku tüüp  
4. Graafiku x-telg
5. Grupeering
5. OSKA näitaja
Filtrid:
6. OSKA valdkod
7. OSKA alavaldkond
8. OSKA ametiala
9. OSKA silt
9. Periood

**Sisulehe alamosa elemendid:**

Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik. Kasutusjuhendisse sama sisu, mis Artikkel sisutüübil.

**Parem veerg:**

**Hõivatute arv** (number_employed), vabatahtlik, numbri sisestamise väli, saab sisestada kuni 7-kohalise numbri.
- teksti sisestus kuni 100 tähemärki, vabatahtlik, see on selgitava info kuvamiseks teksti-väli (explanatory text).

**Plussid ja miinused** (pros_cons), vabatahtlik
- saab lisada kuni 5 plussi ja 5 miinust, teksti sisestus kuni 100 tähemärki

**Ametialad** (MainProfession), kohustuslik
saab lisada kuni n arv ametiala, (sisutüüp MainProfessionPage)
- Järjestus (SecuenceNo) 
- Nimetus

**Leia kiiresti** (Link), vabatahtlik
saab lisada kuni 0..n arv välist linki
- Järjestus (SecuenceNo) 
- Lingi pealkiri (LinkTitle)
- URL (WebPageAddress)

**Sarnased teemad** (RelatedPages), vabatahtlik
saab lisada/ muuta lingid sisulehtedele, vabatahtlik, 0..n arv,
- Järjestus (SecuenceNo) 
- Lingi pealkiri (LinkTitle), 
- URL

**Kontakt** (Contact), vabatahtlik
- Kontaktisik (person), maksimaalne pikkus 50
- Organisatsioon (organization), maksimaalne pikkus 50
- Telefon (phone), telefoni formaat
- E-post (e-mail), e-maili formaat

**Comment by EgleM-TW** [comment]
@TanelTromp Infograafika lisamine juhendisse ühe korra eraldi ptk ja viited sisutüüpide juurest.

**Comment by TanelTromp** [comment]
TEST OK

v.a hetke seisuga kontakti tulbas : "Telefon (phone), telefoni formaat" (veana kirjas teise pileti raames)
