### ISSUE TITLE
Tõlkida impordi-teekonnad

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#599]
Lars:
**1. Palun tõlgi infograafika importimise väljad ja nupud:**
Hetkel nii:
Struktuur → OSKA entity list → nupud: Add OSKA entity ja import OSKA data

Tõlkida nii:
Struktuur → OSKA infograafika nimekiri → nupp: **Lae sisse OSKA infograafika andmed.** 
Käsitsi lisamisel: Lisa OSKA infograafika andmed.

**2. Palun tõlgi näitajate importimise väljad ja nupud:**
Hetkel nii:
Struktuur → OSKA indicator entity list → nupud: Add OSKA indicator entity ja import OSKA indicator data

Tõlkida nii:
Struktuur → OSKA ametiala näitajate nimekiri → nupp: **Lae sisse OSKA ametiala näitajate andmed.** 
Käsitsi lisamisel: Lisa OSKA ametiala näitajate andmed.

See on OK:
Struktuur → OSKA Tabeli sisu nimekiri → nupp: Lae sisse OSKA tabeli andmed. 
Käsitsi lisamisel: Lisa OSKA tabeli sisu.

Kui on tehtud siis testimisse ja Tanel palun lisa nimetatud kolme CSV impordi kohta näited kasutusjuhendisse. See ongi testimise eest.

**Comment by TanelTromp** [comment]
TEST OK


- [x] 1. Palun tõlgi infograafika importimise väljad ja nupud:
Hetkel nii:
Struktuur → OSKA entity list → nupud: Add OSKA entity ja import OSKA data

Tõlkida nii:
Struktuur → OSKA infograafika nimekiri → nupp: Lae sisse OSKA infograafika andmed.
Käsitsi lisamisel: Lisa OSKA infograafika andmed.

- [x] 2. Palun tõlgi näitajate importimise väljad ja nupud:
Hetkel nii:
Struktuur → OSKA indicator entity list → nupud: Add OSKA indicator entity ja import OSKA indicator data

Tõlkida nii:
Struktuur → OSKA ametiala näitajate nimekiri → nupp: Lae sisse OSKA ametiala näitajate andmed.
Käsitsi lisamisel: Lisa OSKA ametiala näitajate andmed.

See on OK:
Struktuur → OSKA Tabeli sisu nimekiri → nupp: Lae sisse OSKA tabeli andmed.
Käsitsi lisamisel: Lisa OSKA tabeli sisu.
