### ISSUE TITLE
Õppeastutuste kaardivaade on katki 

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#600]
Vaikimisi suum vales kohas ja välja suumides avastad ennast.....vaata videot, et teada saada:
https://gyazo.com/9a922f20ef438cb5feed59eb44f9855d

2. Mobiilil ei tööta samuti hetkel "kaardivaade".

**Comment by TanelTromp** [comment]
Täpsustus 1: nii androidiga, kui ka iPhonega on õppeastutuste asukoha kaart veidi lahja suumiga. Kas saab muuta ja tsentraalsemaks teha:

![pilt](https://user-images.githubusercontent.com/37407917/48554769-f9c00300-e8e7-11e8-8de7-1cb2ebf9abfa.png)

![android](https://user-images.githubusercontent.com/37407917/48554779-ffb5e400-e8e7-11e8-91ec-d016f644170d.png)


Täpsustus 2: Zeplinis sama vaade "haldusüksustel" ei ole selline, kui hetkel aga kas saab olla, ei tea:

![haldusuksus](https://user-images.githubusercontent.com/37407917/48554813-18be9500-e8e8-11e8-9941-3853e657a370.png)

vs Zeplin:

![pilt](https://user-images.githubusercontent.com/37407917/48554830-26741a80-e8e8-11e8-9648-78a8fdf2c9ab.png)

**Comment by skeefee** [comment]
Täpsustus 1: Zoom handling on google poolt. me anname koordinaadid ja zoom leveli ette ja google ise mahutab selle sisse
