### ISSUE TITLE
Sisuleht OSKA ametiala tõlked ja kasutusjuhendisse

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#601]
Kontrollida, et sisuhalduse elemendid vastavad piletis toodud kirjeldustele (tõlked). Kui on korras, siis tõsta testimisse, mis tähendab, et Tanel saab sisutüübi kasutusjuhendis kirjeldada.

**Sisulehe põhiosa elemendid:**
- Pealkiri, kohustuslik, maksimaalne pikkus 100
- Fikseeritud silt 
- Sissejuhatus, vabatahtlik, maksimaalne pikkus 300, plain-text
- OSKA ametiala video, vabatahtlik, 0..2, URL link ja video kirjeldus, Järjestus
- Sisu, kohustuslik, WYSIWYG redaktori võimalused 
- OSKA ametiala link, vabatahtlik, 0..n, lingi tekst ja URL, Järjestus
- OSKA ametiala fail, vabatahtlis, 0..n, nimetus ja manus
- OSKA ametiala pilt, vabatahtlik, 1, pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud
- OSKA ametiala silt, vabatahtlik, 0..5 

- Infograafika - vabatahtlik  - kui võimalik tuua lisamine enne akordioni
Järjekord ja tõlked kirjeldatud #598 

**Sisulehe alamosa elemendid:**
Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik. Kasutusjuhendisse sama sisu, mis Artikkel sisutüübil.

**Parem veerg:**

**Näitajad** - kasutusjuhendis viidata, kuidas toimub import ja haldamine
NB! Hetkel kuvatakse välja Üldised näitajad - muuta see lihtsalt **"Näitajad"**

**Plussid ja miinused**, vabatahtlik
saab lisada kuni 5 plussi ja 5 miinust, teksti sisestus kuni 100 tähemärki

**OSKA Valdkond** , kohustuslik
saab lisada kuni n arv valdkonda (nimetus)

**Õppimisvõimalused**, vabatahtlik
Filtreeritud otsingu ISCED-f, NB! Lisada infotekst, et mitme lisamiseks kasutada eraldajana koma.
Õppimisvõimaluste täpsustav tekst, 100 tähemärki

**Töövõimalused**, vabatahtlik
saab lisada 0..n arv välist linki
- URL
- Lingi pealkiri 
- Järjestus

**Kutsestandardid**, vabatahtlik
saab lisada 0..n arv välist linki
- URL
- Lingi pealkiri 
- Järjestus

**Näidisametid**, vabatahtlik
saab lisada 0..n arv 
- Ameti nimetus
- Ameti link (tõlkida ka infotekst)
- Järjestus

**Leia kiiresti**, vabatahtlik
saab lisada kuni 0..n arv välist linki
- URL
- Lingi pealkiri 
- Järjestus

**Kontakt**, vabatahtlik
- Kontaktisik , maksimaalne pikkus 50
- Organisatsioon , maksimaalne pikkus 50
- Telefon, telefoni formaat
- E-post, e-maili formaat

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, ei ole kohustuslik: _OSKA Valdkond , kohustuslik_

![pilt](https://user-images.githubusercontent.com/37407917/48622806-a1a10380-e9b0-11e8-9dbb-499b467d5809.png)


![pilt](https://user-images.githubusercontent.com/37407917/48622792-964dd800-e9b0-11e8-998d-d95ee78e5a74.png)

Viga 2: tingimus ei ole täidetud:

![pilt](https://user-images.githubusercontent.com/37407917/48622906-d90fb000-e9b0-11e8-9be9-acca93118ead.png)

Viga 3: tingmus ei ole täidetud:

![pilt](https://user-images.githubusercontent.com/37407917/48623058-50ddda80-e9b1-11e8-96ea-b0450caf8a4e.png)

Viga 4: "Telefon", mitte "Kontakti telefon"

**Comment by lsoonvald** [comment]
Viga 1: Parandatud.
Viga 2: Parandatud.
Viga 3 ja 4: Pole ise midagi muutnud, see on olemasolev tükk olnud, mis on tehtud aastal 1993.
Viga 5: Parandatud.
Viga 6: Parandatud.

**Comment by TanelTromp** [comment]
Viga 5: näitab topelt tooltippe "Näidisameti" "ameti link" juures "info" sisus
https://gyazo.com/4786998659c37a8874d0eb940ca13ce6

Viga 7 uus: "Valdkonda" mitte valinuna, ei anna veateadet, vaid lihtsalt ei liigu edasi "Salvesta" nupuga

**Comment by lsoonvald** [comment]
Viga 5: Korras.
Viga 7. Korras.

**Comment by TanelTromp** [comment]
TEST

OK
