### ISSUE TITLE
Sisuleht OSKA Tulemused tõlked ja kasutusjuhendisse

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#602]
Kontrollida, et sisuhalduse elemendid vastavad piletis toodud kirjeldustele (tõlked). Kui on korras, siis tõsta testimisse, mis tähendab, et Tanel saab sisutüübi kasutusjuhendis kirjeldada.

**Sisulehe põhiosa elemendid:**
- Pealkiri, kohustuslik, maksimaalne pikkus **100 NB! Teha muudatus, hetkel 50**
- Sissejuhatus, vabatahtlik, maksimaalne pikkus 300, plain-text
- OSKA tulemused pilt, vabatahtlik, 0..2, pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad  kohustuslikud
- Sisu, kohustuslik, WYSIWYG redaktori võimalused 
- OSKA tulemused video, vabatahtlik, 0..1, URL link ja video kirjeldus
- OSKA tulemused link, vabatahtlik, 0..n, lingi tekst ja URL, Järjestus
- OSKA tulemused fail, vabatahtlis, 0..n, nimetus ja manus
- Tabeli fail
NB! kasutusjuhendis viidata, kuidas toimub sisus kuvatava tabeli import ja haldamine.

- Infograafika - vabatahtlik 
Järjekord ja tõlked kirjeldatud #598 

**Parem veerg:**
Viia kooskõlla Artikkel sisulehel lisamisega.
Kasutusjuhendis viidata Artikkel tüüpi sisulehe parema veeru toimetamise kirjeldusele.

**Comment by TanelTromp** [comment]
TEST OK


- [ ]     Pealkiri, kohustuslik, maksimaalne pikkus 100 NB! Teha muudatus, hetkel 50
- [ ]     Sissejuhatus, vabatahtlik, maksimaalne pikkus 300, plain-text

- [ ]     OSKA tulemused pilt, vabatahtlik, 0..2, pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad kohustuslikud
- [ ]     Sisu, kohustuslik, WYSIWYG redaktori võimalused
- [ ]     OSKA tulemused video, vabatahtlik, 0..1, URL link ja video kirjeldus
- [ ]     OSKA tulemused link, vabatahtlik, 0..n, lingi tekst ja URL, Järjestus
- [ ]     OSKA tulemused fail, vabatahtlis, 0..n, nimetus ja manus
- [ ]     Tabeli fail
- [ ]     NB! kasutusjuhendis viidata, kuidas toimub sisus kuvatava tabeli import ja haldamine.
- [ ]     Infograafika - vabatahtlik

- [ ] Parem veerg:
Viia kooskõlla Artikkel sisulehel lisamisega.``
