### ISSUE TITLE
Sisuleht OSKA Tööjõuprognoos tõlked ja kasutusjuhendisse

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#603]
Kontrollida, et sisuhalduse elemendid vastavad piletis toodud kirjeldustele (tõlked). Kui on korras, siis tõsta testimisse, mis tähendab, et Tanel saab sisutüübi kasutusjuhendis kirjeldada.

**Sisulehe põhiosa elemendid:**
- Pealkiri, kohustuslik, maksimaalne pikkus **100 NB! Teha muudatus, hetkel 50**
- Sissejuhatus, vabatahtlik, maksimaalne pikkus 300, plain-text
- OSKA tööjõuprognoos video, vabatahtlik, 0..2, URL link ja video kirjeldus, järjestus
- Sisu, kohustuslik, WYSIWYG redaktori võimalused 
- OSKA tööjõuprognoos link, vabatahtlik, 0..n, lingi tekst ja URL, Järjestus
- OSKA tööjõuprognoos fail, vabatahtlis, 0..n, nimetus ja manus
- OSKA tööjõuprognoos pilt, vabatahtlik, 0..2, pilt sisaldab osasid: pildifail, pealkiri, alt-tekst; pildi lisamisel on kõik osad kohustuslikud

- Infograafika - vabatahtlik, võimalusel tuua lisamine enne alamosa.
Järjekord ja tõlked kirjeldatud #598 

**Sisulehe alamosa elemendid:**
Sarnaselt Artikkel tüüpi lehele. Lisamine on vabatahtlik. Kasutusjuhendisse sama sisu, mis Artikkel sisutüübil.

**Parem veerg:**
Viia kooskõlla Artikkel sisulehel lisamisega.
Kasutusjuhendis viidata Artikkel tüüpi sisulehe parema veeru toimetamise kirjeldusele.

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, endiselt 50: _Pealkiri, kohustuslik, maksimaalne pikkus 100 NB! Teha muudatus, hetkel 50_

Viga 2: video URL-i placeholder/nimi puudu. Palun lisada "URL link":

![pilt](https://user-images.githubusercontent.com/37407917/48620362-9053f900-e9a8-11e8-92f5-25e0c59d015c.png)

Viga 3: muuta välja nimi "Kirjeldus">"Nimetus":

![pilt](https://user-images.githubusercontent.com/37407917/48620471-e9239180-e9a8-11e8-95e1-eca3d6e21260.png)

VIga 4: nupp tõlkida:

![pilt](https://user-images.githubusercontent.com/37407917/48620551-31db4a80-e9a9-11e8-8bbb-c4b38e47c36f.png)

**Comment by lsoonvald** [comment]
Viga 2: Korras.

**Comment by TanelTromp** [comment]
TEST

OK
