### ISSUE TITLE
Frontend poolne komponent vaadete preview jaoks

### ISSUE THREAD

**Issue by skeefee** [hariduspilv/haridusportaal#607]
* Vaja luua uus route ja komponent "preview"
* Komponent saadab päringu serveri ja saab tagasi komponendi tüübi
* Laetakse sisse õige komponent

**Comment by skeefee** [comment]
article
event
news
schools
study-programme
oska-areas
oska-areas
oska-areas
oska-results

**Comment by skeefee** [comment]
article
event
news
school
study_programme
oska_main_profession_page
oska_field_page
oska_survey_page
oska_result_page

**Comment by TanelTromp** [comment]
TEST

- [ ] article
- [ ] event
- [ ] news
- [ ] school
- [ ] study_programme
- [ ] oska_main_profession_page
- [ ] oska_field_page
- [ ] oska_survey_page
- [ ] oska_result_page

**Comment by TanelTromp** [comment]
Test

- [ ] article
- [ ] event
- [ ] news
- [ ] school
- [ ] study_programme
- [ ] oska_main_profession_page
- [ ] oska_field_page
- [ ] oska_survey_page
- [ ] oska_result_page

**Comment by skeefee** [comment]
UX-täiendus 1: Breadcrumbs sai ära võetud kuna preview ei saa õiget URLi kätte sisu puhul. @ruut12  oskab ehk rohkem infot anda?

Viga 2: FE poole pealt korras @ruut12 saab seda lahendada

**Comment by TanelTromp** [comment]
Viga 3: juba varem loodud sisu eelvaade ei tööta:

https://gyazo.com/36d8a76278d75fb3f61fdd48c824a604

Täpsustus: kas sisutüüp "avaleht" eelvaade tuleb eraldi piletina? Hetkel ei tööa.

**Comment by skeefee** [comment]
Viga 3: pead htm.wiseman.ee alt sisse logima mitte test-htm.wiseman.ee:30000
Viga 4: pead htm.wiseman.ee alt sisse logima mitte test-htm.wiseman.ee:30000

**Comment by ruut12** [comment]
@skeefee 
Kui pole entityId siis link Drupalis peaks olema: /node/add/{{entityBundle}}?uuid...

**Comment by skeefee** [comment]
@TanelTromp  ehk testid uuesti. Paistab et töötab ju.

**Comment by TanelTromp** [comment]
Ei tööta endiselt. Palun lugege "Viga 2" kommentaar uuesti ning vaadake lisatud gyazo videot.

**Comment by skeefee** [comment]
Korras.

**Comment by TanelTromp** [comment]
TEST OK

Testitud kasutusjuhendis soovitatud brauseritega.

- [ ]     Vaja luua uus route ja komponent "preview"
- [ ]     Komponent saadab päringu serveri ja saab tagasi komponendi tüübi
- [ ]     Laetakse sisse õige komponent
