### ISSUE TITLE
Tagasiside komponent sisulehele

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#609]
Uurida drupali võimalusi ja kuidas lahendada  - arutada analüütikutega läbi.

Peab saama salvestada FE-st laekuvat tagasisidet 
- leht, millele tagasiside anti
- kuupäev ja kellaaeg, millal tagasiside antu
- tagasiside sisu:
-- sai infot / ei saanud infot ( + / - ) valik
-- kommentaar

Peab olema võimalik tagasisidet näha:
- tervikvaade üle kogu portaali antud tagasiside kohta
-- vaikimisi järjestatud uuemad eespool
-- aja filter
- lehe kohta antud tagasiside kohta

**Comment by ruut12** [comment]
POST: /feedback?_format=json
body:
```
{
	"nid" : {article_id},
	"type" : 1, // 1 - positiivne, 2 - negatiivne
	"message" : "sõnumi sisu"
}
```
