### ISSUE TITLE
Saab sisse logida

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#610]
**Üldkirjeldus**
Kasutaja logib portaali sisse, õnnestunud sisse logimisel kuvatakse kasutajale töölauda.
Selle töö raames ainult funktsionaalsus.

**Käivitamine**
* Kasutaja vajutab menüü-ülalribal "mehikese" ikoonile.

Variant 1 Kasutaja valib "Logi sisse"
* Kasutaja logib sisse TARA vahendusel.
* Sisse logimine viiakse läbi TARA keskkonnas ja sisse logimise õnnestumisel kuvame töölauda.

Variant 2 Kasutaja valib "Logi sisse HarID-ga"
* Kasutaja logib sisse HarID vahendusel, selleks kuvame vahe-modaali:
* Sisse logimine viiakse läbi HarID keskkonnas ja sisse logimise õnnestumisel kuvame töölauda.

Mõlemal juhul salvestada sessiooni-võti.

Kui sisse logimine ei õnnestunud kuvame veateadet vaates, kus kasutaja alustas sisse logimist.
NB! Kui ei õnnestu meelde jätta, kus lehel kasutaja viibis, siis kuvame avalehte. Töö käigus märkida testimiseks kumb variant on realiseeritud.

Veateate disain: Birgitilt, töös. Selles sprindis ilma disainita.

Viited:
BE TARA #485 ja HarID #57

**Comment by skeefee** [comment]
Hetkel on TARA logimine tehtud suunamisega.
Modaali ja iFrame-i ei saa kasutada kuna TARA on selle ära keelanud.
<img width="1197" alt="screenshot 2018-12-05 at 15 33 50" src="https://user-images.githubusercontent.com/13978713/49517484-feebee80-f8a4-11e8-9be5-a6fcb97da416.png">

**Comment by ruut12** [comment]
@skeefee 
Autentimise urlid muutusid pisut nüüd on:
/external-login/{method}
method = tara, harid

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, peale õnnestunud logimist ei kuva töölauda, vaid avalehte. *Kasutaja logib portaali sisse, õnnestunud sisse logimisel kuvatakse kasutajale töölauda.*


**Hetkel ei tööta TARA poolne ID-kaardiga logimine.**

**Comment by skeefee** [comment]
Viga 1: Kuna JWT token oli puudu siis sisse logimine ebaõnnestus. Teated on lisatöö
Viga 2: @ruut12

**Comment by ruut12** [comment]
Viga2: Võiks kontrollida, et kas back-endist on eelnevalt välja logitud, sest muidu läheb rakendus konflikti

**Comment by TanelTromp** [comment]
Viga 1: nagu kirjutasin "Pärast ÕNNESTUNUD" logimist juhtus see kõigi kolme õnnestunud logimise puhul - tekkis töölaud ja roheline mummu ja mehikese juurde ning välja logimise võime (ehk nagu tickitud paar kommi ülevamal pool), mitte kui ebaõnnestus. @skeefee 

Viga 2: olin välja logitud, kontrollisin. Siin ka mis kuidas juhtus:

https://gyazo.com/6cbb2516693e4ec64db22e8342ecbf4e

**Comment by skeefee** [comment]
Viga 1: Mõtlen seda, et kui sa sisse logid AGA sul ei ole lehel õigusi sisselogimiseks. St. teenus logib sind jah sisse ja errorit ei ole aga meie leht ei lase ligi

**Comment by ruut12** [comment]
Viga 2: test.harid.ee sisselogida ja ära kustutada antud õigused ja seejärel uuesti autentides on korras @TanelTromp

**Comment by TanelTromp** [comment]
Viga 3 WCAG: päises olevat "Logi sissse" mehikest/nuppu ei loe ekraanilugeja õigesti maha.

Viga 4: hinttekstid on ing. k: 
![pilt](https://user-images.githubusercontent.com/37407917/51460676-d17bd700-1d64-11e9-9a44-942856f9e9cc.png)

**Comment by EgleM-TW** [comment]
@skeefee, veateadete kuvamine #509  - vajadusel teeme uue pileti, aga planeeritud oli veateate kuvamine ilma disainita. Tõsta kisa, kui on vaja nõudeid täpsustada!

**Comment by skeefee** [comment]
@EgleM-TW  Kas kuvame seal tavalist modaali nagu on uudiskirjaga liitumise kinnitus?

**Comment by EgleM-TW** [comment]
@TanelTromp ja @skeefee see pilet läheb kinni veateateta. Eraldi pilet.

**Comment by skeefee** [comment]
Täpsustus 0, 1,2: kõik veateated tulevad uue pileti raames

**Comment by TanelTromp** [comment]
Viga 5 WCAG: "Logi sisse" ikoonile liikudes peab ekraaniluger  ütlema "button", mitte "Link".

- If clicking on the element will perform an action on the page, use <button>.
- If clicking on the element will navigate the user to a new page (or load new content in a single-page web app) then use <a>.

**Comment by skeefee** [comment]
WCAG korras

**Comment by TanelTromp** [comment]
TEST

TARA testandmetega test (https://tara-demo.herokuapp.com/):

- [ ] ID-kaart **NB! TARA on testimata ID-kaardiga, sest isiklikku kaardi sertifikaatide üleslaadimine ei töötanud ning TEST sertifikaate raha eest ei tellinud**
- [x] Mobiil-ID
- [x] Pangalink
- [x] Smart-ID
- [ ] EU citizen **EU Citizeni testandmetega sisselogides, ei jõua hetkel htm.twn.ee lehele tagasi, vaid jõuab tagasi "Eidastes.eesti.ee" lehele**
