### ISSUE TITLE
Otsing autocomplete

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#613]
Haridusportaali üldine otsing (avalehel, päises) teha otsinguvälja sisu autocomplete.

Päring on realiseeritud #595
Autocomplete käivitub alates kolmandast sisestatud tähest.

**Comment by TanelTromp** [comment]
Madisele WCAG suunised:
https://haltersweb.github.io/Accessibility/autocomplete.html

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1: tingimus ei ole täidetud, mootor ei arvesta "algusega", vaid võtab keskel kolm tähte: _Autocomplete pakub välja ainult neid, mille algus täpselt vastab sisestatule._

![pilt](https://user-images.githubusercontent.com/37407917/49495890-2921ba00-f86d-11e8-9005-3a04fa73fccf.png)

**Comment by madispold** [comment]
Viga 2: OK.
Viga 3: OK.
Viga 1, 4 on BE, kui lähevad tegemisele üldse.

**Comment by TanelTromp** [comment]
Viga 5: autocomplete ei leia otsisõna"psühhodraama" järgi "MTÜ Tartu Psühhodraama Instituut" kooli, kui alustada MTÜ-ga, siis leiab:
https://gyazo.com/1be8ac634c7c61f587dae8e37a750088

**Comment by madispold** [comment]
@TanelTromp 
Viga 5: BE.
Viga 6: BE.
Viga 7: Kuvamise järjestus ei olene filtritest ehk ikkagi peaks olema otsitud täpne match esimese valikuna - BE.
Viga 8: Võib teha, kuid kuna igal filtril on ikkagi URL'ile tüübi lisamise funktsionaalsus ka taga, kas peaks? Kuigi kui vaid 1 filter, siis tulemus ei muuta, aga...
Viga 9: Panin ette lugema "Kõik" filtri sisu - OK.
Viga 10: OK.
Viga 11: OK.

**Comment by TanelTromp** [comment]
Viga 12 uus: ei kuva sidekriipsu autocomplete vastetes + kui sisestada sidekriips, siis midagi enam ei leia - kui teha tavaotsing ilma sidekriipsuta, siis ok:
https://gyazo.com/b1cbeefe0b22433726ac7b8bc17af37d

**Comment by lsoonvald** [comment]
Viga 12 uus: ei kuva sidekriipsu autocomplete vastetes + kui sisestada sidekriips, siis midagi enam ei leia - kui teha tavaotsing ilma sidekriipsuta, siis ok (Seotud ka viga 5-ga ehk kui kopi peistida terve nimi, kus sees sidekriips, siis ei leia midagi). Korras.

Viga 13: Üldiselt kuvan mõistliku pikkusega teksti, uurida Andruselt, kas vajab parandust.

Viga 14: Korjasin mittesobivad sümbolid autocomplete'st ära.

**Comment by madispold** [comment]
Viga 9: OK.
Ux täiendus 1: OK.
Viga 15: OK.
Viga 16: OK.
@TanelTromp

**Comment by TanelTromp** [comment]
UX-täiendus 2: Samsung tableti peal + Chrome horisontaalis ing. keelne hint:

![galaxytablet](https://user-images.githubusercontent.com/37407917/49861511-ae284880-fe04-11e8-9efa-fb2173397145.jpg)

**Comment by lsoonvald** [comment]
Ux täiendus 3: Korras.

**Comment by TanelTromp** [comment]
UX-täiendus 4: sellist käitumist ei ole ka ise varem kohanud, et kuvab otsitavat sõna esimesena ehk tagurpidi tulemus:
https://gyazo.com/f9196f93c5801fee91c0bd83d9ea0ebf
@andrussarv @EgleM-TW otsustada ja DONE-i tõsta.

**Comment by TanelTromp** [comment]
- [ ] Haridusportaali üldine otsing (avalehel, päises) teha otsinguvälja sisu autocomplete.
- [ ] Autocomplete käivitub alates kolmandast sisestatud tähest.
