### ISSUE TITLE
Tõlkida OSKA klassifikaatorid

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#616]
Tõlkida sisuhalduses klassifikaatorid:

1. MainProfession Tags = Ametiala silt
2. OSKA Field = OSKA valdkond ja alavaldkond
3. OSKA Indicator = OSKA infograafika näitaja
4. OSKA MainProfession = OSKA ametiala

**Comment by TanelTromp** [comment]
Viga 1: kui see on sama väli, siis peaks olema "OSKA infograafika näitaja", mitte "OSKA Näitaja"
![pilt](https://user-images.githubusercontent.com/37407917/49220510-1461a400-f3df-11e8-969c-ec28a12fc706.png)

Viga 2: tingimustes on väikse tähega, tõlgitud suure tähega (kui need on ikka samad):

![pilt](https://user-images.githubusercontent.com/37407917/49220609-538ff500-f3df-11e8-9e77-e2350a11ab04.png)

**Comment by lsoonvald** [comment]
@TanelTromp tuleks vaadata tõlkeid siin lehel: http://test-htm.wiseman.ee:30000/et/admin/structure/taxonomy

Antud issue oli nende taksonoomiate pealkirjade kohta.

**Comment by TanelTromp** [comment]
TEST

OK
