### ISSUE TITLE
Test leitud vead 6 - UUS

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#623]
UX-täiendus 1: kui burgermenüüst (mobiil, tablet) vajutada juba lahti oleval menüüpunktil, siis peaks burgermenüü sulgema.

Viga 1: 404 veakood peab olema eesti keelne: “Veakood: 404” mitte hetkel nähtav “Error kood: 404"

UX-täiendus 2 iPad/iPhone + Safari: kui avada ametiala, mis on sisult pikem, kui mahuks vaatesse, siis avab artikli detailvaate imeliku skrolliga sisu keskele. Nt:
http://htm.twn.ee/et/ametialad/teabe-ja-dokumendihalduse-spetsialistid
http://htm.twn.ee/et/ametialad/oska-pohikutseala-pikk-50-tahemarki-eksju-tapselt

Viga 2: otsitulemustes on "õppekava", peaks olema "eriala", chipi nimi ei ühti:

![pilt](https://user-images.githubusercontent.com/37407917/47356970-32483480-d6ce-11e8-8800-bcf5ee3693ea.png)
http://htm.twn.ee/et/otsing?term=tekstiili-%20ja%20r%C3%B5ivat%C3%B6%C3%B6stus&type=%C3%95ppekava

![pilt](https://user-images.githubusercontent.com/37407917/47847582-58f42280-ddd4-11e8-9fc3-3c9bede9f346.png)

UX-täiendus 3: otsingud sisulehtedes - kui vedada lehe laius mobile breakpointi peale, sulgeda filter ja tirida tagasi desktop formaati, siis filtri konteiner kaob ära

UX-täiendus 4: breadcrumbs ilmub ja kaob, väga suure lagiga:

https://gyazo.com/95b082c220e3efaccd358d27ae280f36

UX-täiendus 5: ilma sisuta sisulehtede vaade puudu. Kui content puudub, siis peaks ütlema "Ühtegi seda ja seda ei ole", mitte:
![pilt](https://user-images.githubusercontent.com/37407917/47916682-a85b5100-deaf-11e8-96ea-94d2dcba45ae.png)

UX-täiendus 6: iPhonel ja iPadil ilmub lemmiku toolip, mis on servast väljas. Võiks maha keerata.

UX-täiendus 7: IE11 siltide joondus katki:

![pilt](https://user-images.githubusercontent.com/37407917/50215213-fefeea80-038a-11e9-94f2-62a5de0db631.png)

Viga 3 mobiil android ja iPhone: "Logi välja" ja "keelevahetus" modaal ekraani vasakus servas:

![screenshot_20181113-162418](https://user-images.githubusercontent.com/37407917/48419922-cfdcd400-e761-11e8-81c3-549a5a5fec8e.png)

Viga 4 WCAG: palun kontrollida üle, kas "Link" ja "button" on õigesti määratud. Nt "Otsitulemused" chipid. FIltrite "täpsemad filtrid" "Lae rohkem", "lae vähem" paremas veerus sisutüüpidel jne

    If clicking on the element will perform an action on the page, use <button>.
    If clicking on the element will navigate the user to a new page (or load new content in a single-page web app) then use <a>.

UX-täiendus 8: sisusse sisestaud linkidel ei teki hover:
https://test.edu.ee/et/artiklid/karjaaritee-minu-voimalused
https://gyazo.com/f5e6eaa9f79b0f3d050c85e675084139

Viga 5: "Õppeastutuste" filtrist valikud puudu:

https://gyazo.com/f70d704aed42099f05b89aa7bd8086be

Viga 6 prelive: tekst kastist väljas:

<img width="558" alt="capture" src="https://user-images.githubusercontent.com/37407917/49735151-1523f100-fc8f-11e8-98c4-4b523eafa5c2.PNG">

Viga 7 IE11: vaade katki:

http://htm.twn.ee/et/artiklid/artikkel-mugudest

![pilt](https://user-images.githubusercontent.com/37407917/49862546-0d875800-fe07-11e8-92f3-c1db8ef687fc.png)

UX-täiendus 9: sulgeb menüüpuu:

https://gyazo.com/8827a530b444c36b79a4288a537a8621

Viga 8: vaade katki:
http://htm.twn.ee/kool/tallinna-tehnika%25C3%25BClikool

UX-täiendus 10: välise lingi ikoon ei ole õige ("sarnased teemad" all):

http://htm.twn.ee/artiklid/artikkel-mugudest

Viga 8 BE: näitab pikalt kustutatud sisusid, ka hardrefresh ei tööta:
https://gyazo.com/f87ce7aac3e18ebecb05593879abdaaa

![pilt](https://user-images.githubusercontent.com/37407917/50208330-99563280-0379-11e9-9510-d0962b8b8a13.png)

UX-täiendus 11: all vasakul nurgas näitab lisatud faili asukohta BE-s, võiks näidata ainult dokumendinime:

https://gyazo.com/fc2cf83da647110f288d0bddad5f0eb2

Viga 9: sisseloginuna ei lae "Lemmikute" vaadet üles, jääbki saagima:
https://gyazo.com/b921170f8fedd59fed16a3b676c66bde

Viga 10 WCAG: ei suuda TABiga tabada "täpsem otsing" valikut:

![pilt](https://user-images.githubusercontent.com/37407917/50215060-96b00900-038a-11e9-9def-11fa21309f10.png)

Viga 11: "ametialad" ja "erialad" võrdluses "Tagasi" nupp viib avalehele aga peaks viima: 1.http://htm.twn.ee/ametialad
2.http://htm.twn.ee/erialad?open_admission=true

![pilt](https://user-images.githubusercontent.com/37407917/50228812-88c1ae80-03b1-11e9-9e62-6f52a4049986.png)

Viga 12 prelive: siltide erinevad joonduse probleemid ning sama sisuline silt kaks korda kuvatud:

![pilt](https://user-images.githubusercontent.com/37407917/50330209-0ba64e80-0503-11e9-9cbf-b2f123fa16a9.png)

Viga 13: "Erialade" filtrist "Õppekava tase" valikuid puudu? Nt "Doktoriõpe"? "Õppevaldkond" ka palun üle kontrollida:
https://gyazo.com/4d8751cb8af56123885d1b78d24a1630

Viga 13.2: "Õppekeel" valikus on valik "Test" sees.

Viga 14: ei ava meenüüpuud st menüü on suletud:
https://gyazo.com/bc7cac02d29a7ce74dafa2fec59bcc85

Viga 15: ametiala leht IE11 hangub kohati täiesti ja videote asemel näitab error404:
http://htm.twn.ee/ametialad/oska-p%C3%B5hikutseala-test-05102018

https://gyazo.com/90b5469e07b442910cb4a6df062fd7ec

Viga 16: MAcBook AIR+Safari: puudub peamenüü:
![20190111_092709](https://user-images.githubusercontent.com/37407917/51019394-6d4a5d80-1583-11e9-82fa-42e7ee029ad6.jpg)

UX-täiendus 12: Avalehel avaneb Peaploki teemade juures inbound link ka uues sakis. Võiks sama loogika olla nagu mujal ehk inbound samas aknas/sakis ja outboud uues sakis.

**Comment by madispold** [comment]
UX-täiendus 1: OK, mobiili/tahvli vaates lehe avades.
Viga 1: OK.
UX-täiendus 2: OK.
Viga 2: Ei tea, kas saab muuta BE poolel neid labeleid, aga muidu BE teema @lsoonvald
UX-täiendus 3: Ei tee, varem jälgisime seda, aga filtrid sulgusid muu sisu muutmisel mobiilis/tahvlil - OK.
UX-täiendus 4: OK.
UX-täiendus 5: OK. 
UX-täiendus 6: OK.
UX-täiendus 7: OK.
Viga 3: OK
Viga 4: Otsing ja listivaadete filtrid: OK.
UX-täiendus 8: Sisu sees lingid ümbertegemisel pilet #692 raames.
Viga 5: Valikud puudu, kuna BE annab ka arvu, mitu tulemust filter annaks ning kui count === 0, FE peidab ära filtri. See pikalt tagasi tehtud - eeldan, et oli piletis ka selline nõue... vist OK?
Viga 6: Sisuhalduse viga: "kodulehtedelt" sisestatud &nbsp (non-breaking space) tühikutega ees ja taga, mis muudab viimase koos lingiga üheks katkematuks sõnaks - OK.
Viga 7: ...

**Comment by TanelTromp** [comment]
Viga 1: ikka näeb e.k veakoodi:
![pilt](https://user-images.githubusercontent.com/37407917/51596907-a7601b80-1f02-11e9-8a43-5ec64c5a9326.png)

**Comment by madispold** [comment]
Viga 1: OK.
Viga 4: OK.
Viga 5: OK.
Viga 6: Pole nii tarka süsteemi, aga on sisuhaldusesse loodud preview sellel põhjusel.
Viga 12: Tekitasin ruumi juurde, esialgu testkeskkonnas, OK.

@TanelTromp

**Comment by TanelTromp** [comment]
TEST OK

Viga 5 kohta tehakse uus pilet: https://github.com/hariduspilv/haridusportaal/issues/681#event-2094209486
