### ISSUE TITLE
OSKA valdkonna pildi ja video lisamine/ kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#624]
**Back-end**
Teha muudatus OSKA valdkonna sisulehe toimetamisel:
 - Saab lisada 1 foto ja 1 video. _(Hetkel saab lisada 2 fotot)._

**Front-end**
 - Lisatud fotot kuvada nimekirja-vaates, vt disaini https://zpl.io/VOkO6B1
 - Lisatud videot kuvada detailvaates, vt disaini https://zpl.io/2ZzOYOd _(See video lisandub edasiarendusena ka sinna modaali sisse)_
 - Üksnes juhul kui video puudub, siis kuvada detailvaates lisatud fotot.

_Notes: Egle teeb muudatuse kasutusjuhendis kah, kui on jõudnud testi._

**Comment by lsoonvald** [comment]
Back end done.

**Comment by TanelTromp** [comment]
Viga 1: saab lisada 2 fotot endiselt:

![pilt](https://user-images.githubusercontent.com/37407917/49926934-70d7bf80-fec5-11e8-9c3e-7a1e0db0193f.png)

**Comment by lsoonvald** [comment]
Viga 1: Korras.

**Comment by EgleM-TW** [comment]
BE test: saab lisada: 1 video ja 1 pilt
FE test: @madispold 
lisatud video -  kuvatakse detailvaates. OK
lisatud video ja pilt - **viga 1:** lisatud fotot ei kuvata nimekirjas
lisatud ainult pilt  - **viga 2:** lisatud fotot ei kuvata ei nimekirjas ega detailvaates

**Comment by madispold** [comment]
@EgleM-TW @TanelTromp 
Viga 1: OK.
Viga 2: OK.

**Comment by EgleM-TW** [comment]
Testitud: http://htm.twn.ee/valdkonnad/kommunikatsioon
OK - Lisatud pilt ilma videota: pilt kuvatakse nimekirjas ja detailvaates sissejuhatuse järel ja sisuteksti ees.
NOK - Lisatud video ja pilt: pilt kuvatakse nimekirjas - OK, aga video kuvatakse sisuteksti järel.
@madispold  - vt ka disaini https://zpl.io/2ZzOYOd - Video kuvada siseejuhatuse järel ja sisuteksti ees.

**Comment by madispold** [comment]
NOK - OK.
Lisaks tööjõuprognoosi lisatud õige tüübi pealkiri. Samuti tulemused vaates vahetatud tüübi ja pealkirja asukoht.

**Comment by EgleM-TW** [comment]
Lisatud kasutusjuhendisse.
