### ISSUE TITLE
Hõive andmete ja muutuse kuvamine - disain

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#625]
Märkus: 04.02.2019 koosolekulk muudetud lahendust: tabeli andmed lisasime faktide importi ja kuvamisse ning lisasime ametialade võrdlusele. 

Lisaks muutsime Valdkonna detailvaatel ametialade kuvamist.
***
Algne sisu:
Kasutaja on avanud OSKA valdkonna lehe (FiledPage) - https://zpl.io/2ZzOYOd
Kui selle valdkonna kohta on imporditud andmed, siis neid kuvatakse sisuteksti järel tabelis järgmiselt:
Ametiala; Hõive; Hõive muutus
Vaata rohkem → avab täisvaatega lehekülje, millel kuvatakse:
terve tabel filtreerituna selle valdkonna järgi, kus kasutaja tabelile liikus (siis valdkonna lahtrit ei kuva, aga otsing peaks tabeli kohal olema, kus saab valdkonda valida). Vt sarnane lahendus on disainida #683 
Tabeli andmed:
* Valdkond - 100 tähemärki
* Ametiala - 100 tähemärki
* Hõive - number
* Hõive muutus - see on 5 valikut noole suunaga (kell 12; 13:30; 15; 16:30 ja 18) : )
* Hariduse pakkumine - see lahendada valgusfoorina - vt all kommentaari
* Kommentaar - teksti jupp (kui kommentaari lahter ei mahu ära (jääb lehelt välja), mis on vägagi võimalik, siis jätame selle ära.)

Selle töö raames lahendame ka tabeli lk koos filtriga, filtri väljad: valdkond, ametiala.

***
Vaata all esimest kommentaari - arvestame täistabeliga lehe uueks sisutüübiks, kuhu saab lisada ka infograafika - pigem siis tabeli ette?; või viime infograafikaga ametialade võrdluse veel tabeli lehest eraldi lehele. Arutame, kui asud lahendama.
***

**Comment by RainLeoma** [comment]
Hõive muutus ja hariduspakkumine võiksid olla kõrvuti. Kommentaar viimane lahter. Kui kommentaari lahter ei mahu ära (jääb lehelt välja), mis on vägagi võimalik, siis jätame selle ära. Eesmärk on kasutajale lihtsalt ja kompaktselt näidata valdkondade ametialade hõive muutusi ja hariduspakkumise vastavust.

Hariduspakkumise foori koosneb 4 värvist. 1- Koolitatakse vajadusest rohkem; 2- Koolitatakse piisavalt  3- Koolitatakse vajadusest vähem; 4- Erijuhtum (kirjutame vajadusel tekstis lahti, et mis erijuhtumiga on tegu). Foori puhul pidada silmas, et olukorrad 1 ja 3 on samavõra halvad. Parim olukord on 2.  
Kasutaja võiks kuskilt saada ka värvide selgitused. Näiteks foori peale liikudes hiirega?  
Kas oleks võimalik lahendada foori värvide sisu taksonoomiaga, et oleks võimalik muuta teksti, mida kasutajatele kuvatakse, kui ta liigub foori peale või muul moel saab värvide selgituse?

Eeldan, et CSV-s on hõive muutuse ja hariduse pakkumise tunnused sisestatud arv väärtustena (1-5 ja 1-4), mille veeb muudab nooleks/fooriks?

Tabelit kuvatakse valdkondade lehel (selle valdkonna ametialasid, mille lehte vaadatakse) ja ametialade võrdluse lehel (filtreeritavana valdkondade järgi) 

Ametialade järjestus tabelis on CSV-s olev järjekord

**Comment by EgleM-TW** [comment]
OK, täiendatud, BE pileti lõplik sisu sõltub ka disainist.

**Comment by birgitpulk** [comment]
Kujundus: https://zpl.io/VYGdz6n
