### ISSUE TITLE
Teksti lisamine infograafikute vahele

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#631]
OSKA sisutüüpidel: valdkond, ametiala ja tööjõuprognoos peab saama lisada teksti infograafiku selgitamiseks.
See tähendab, et kasutajale peab saama kuvada teksti, infograafikat, jälle teksti ja infograafikat jne.

Luua sisuhalduses võimalus lisada iga sisestatava infograafika ette tekst. Tekstiväli piiranguga 1500 tähemärki.

@birgitpulk Kas paneme piirangud mahule – kui mitu graafikut-tekstivälja ühele sisulehele saab sisestada? Nt max 5tk. Või kas tähemärkide arv ehk väiksemaks? Planeerimisel palun täpsustame seda.

**Comment by TanelTromp** [comment]
TEST

Väli "Graph info text" Sisuhalduses olemas aga hetkel ei õnnestu graafikuid UI-sse kuvada.

**Comment by EgleM-TW** [comment]
Täpsustus: Selle sprindi raame spidime ainult võimalusi täspsutama, mitte realiseerima. Vt Slack #analüüs.

**Comment by EgleM-TW** [comment]
BE lahendus loodud. Hetkel jätame piirangu ära.
