### ISSUE TITLE
Päringud infograafika numbrite kuvamiseks 

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#632]
Kuvada väärtused täisarvudena ja arvud esitada eestipäraselt. https://developers.google.com/chart/interactive/docs/customizing_axes

Näiteks CSV väärtused teisendada nii:
23,53081094 = 24
24,37956929 = 24
24,95224505 = 25
või
11320,33333 = 11 320
10375,66667 = 10 376
9063,666667 = 9064

Ümardamine back-endis.

**Comment by RainLeoma** [comment]
Suuremate arvude puhul näiteks 1234567,8 peaks olema kuvatud 1 234 568.

Muidu nõus! Palun arvestada ka alumiste mõtetega.

NB! Ümardamisega on see probleem, et kuidas me lahendame % küsimuse? Kui mul on CSV-s 0,38 ja mõeldud protsendina, siis ma tahaks, et seda kuvatakse 38% mitte 1. Kui on arusaam, et me hakkame ka protsente CSV-sse laadima 38 mitte 0,38 siis on üleüldine ümardamine täiesti ok. 

NBB! Palun kontrollida pärast ümarduse sisseviimist, et telgedel ei kuvataks liigseid komakohti. Näiteks, et telgedel poleks kuvatud 100,00 vaid 100. Ma ei tunne google chartsi piisavalt, et olla koheselt veendunud, et seda ei teeks. Tean, et excel kipub panema numbritele kaks komakohtasid järgi kui panna kuvamise formaadiks "number" (tühikutega esitamine) ning see tuleb eraldi ära muuta.

**Comment by EgleM-TW** [comment]
Jah CSV-sse protsendid, eelnevas näites 38 mitte 0,38. Edasiarendusena hiljem ka ühiku lisamine.

**Comment by RainLeoma** [comment]
> Jah CSV-sse protsendid, eelnevas näites 38 mitte 0,38. Edasiarendusena hiljem ka ühiku lisamine.

Sobib

**Comment by EgleM-TW** [comment]
@skeefee sprindi lõpp paistab juba!

**Comment by lsoonvald** [comment]
Tulemused ümardatakse täisarvudeks nüüd.

Aastaarvud on naljakad. 2,004.5 jne:
http://htm.twn.ee/oska-tulemused/tulemused-testimisel

**Comment by heldiraudsepp** [comment]
BE - annab formaadi tüübid lisaks kaasa, max 8h
FE - 5h

**Comment by heldiraudsepp** [comment]
Testitakse koos infograafikaga
