### ISSUE TITLE
Artikkel sisutüübi täiendused, et vältida mahukaid akordione

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#633]
Persoonade töötubade järel vajalik kujundada uus sisutüüp, et lahendada mahukate akordionite loomine.
Analüüs ja disain viia läbi paralleelselt.

Algne kirjeldus ja pakutud lahendus:

**Probleem:** toodangusse mahukate sisulehtede loomisel tekivad liiga suured akordionid.
**Lahendus:** teemapõhiselt osa sisu paigutada paremtulbas olevatesse kastidesse, näide:

Kast 1 pealkirjaga Millised on mu oskused?
* Suhtlemisoskused
* Kuulamine
* Konfliktide lahendamine
* Kontakti loomine
* Emotsioonide juhtimine
* Esinemisoskused

Kast 2 pealkirjaga Mis mind huvitab?
* Kuidas valida hobi?
* Vajadused
* Väärtused
* Uskumused
* Elurollid

**Arendus:** võimaldada artiklite lehemalli paremtulpa lisada linke, mis avavad wysiwygiga kirjutatud sisu MatDialog elemendis, ülanurgas suur X kiireks sulgemiseks

**Comment by EgleM-TW** [comment]
Jäi ära ja seda Jirasseüle üle ei vii. Kui teema endiselt üleval, siis teeme uue pileti.
