### ISSUE TITLE
Rakenduse versiooni kuvamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#634]
Vasakmenüü jalusesse joondatud 'Versioon _semver_number_', kannab endas linki changelog.md failile.

@birgitpulk lisada disaini viide

**Comment by heldiraudsepp** [comment]
Disain 2h
FE 1h
BE 2h
Test 2h

**Comment by madispold** [comment]
Ootab kujundust, muidu olemas!

**Comment by birgitpulk** [comment]
Prooviks nii:

1. 2 joont kirja kohal
2. teksti toon #757575, Light, 14px
3. Kas saaks sellele kirjale ruumi juurde alt, hetkel ei paista ta kohati välja
4. Joondame keskele

**Comment by birgitpulk** [comment]
Kujunduse osas korras

**Comment by TanelTromp** [comment]
TEST

OK
