### ISSUE TITLE
Sündmusele registreerija ja korraldaja e-kirja kinnitused

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#638]
Viga:

![pilt.png](https://images.zenhubusercontent.com/5ab8a6294b5806bc2bcc56d1/34e7aeb9-6e9f-463c-8610-6a8052e1b39e)

**Comment by TanelTromp** [comment]
TEST

Viga 1, vatavalt "Lisakuupäev" muudatustele: "Lisakuupäevaga" sündmuse puhul peaks kõik toimumisajad ära märkima e-kirja kinnituses. Hetkel:
![pilt](https://user-images.githubusercontent.com/37407917/50054873-a68fd900-014f-11e9-898a-d8b87a2b6b9a.png)

http://htm.twn.ee/sundmused/kokkutulek-mehed

Palun vaadata siit tingimusi saadetava e-kirja kinnituse kohta:

https://github.com/hariduspilv/haridusportaal/issues/259

**Comment by ruut12** [comment]
Viga1: korras
Viga2: korras

**Comment by TanelTromp** [comment]
Viga 2: tingimus ei ole täidetud, vastavat teavitamise e-maili ei saabu sisuhalduses sisestatud aadressile:

![pilt](https://user-images.githubusercontent.com/37407917/50290089-495b9680-0473-11e9-9109-e6343b738889.png)

Kui sündmuse andmetes on registreerimistest teavitamise e-posti aadress (registrationNotificationEmail), siis süsteem saadab e-maili:
-- saaja e-posti aadress: registrationNotificationEmail
-- pealkiri (subject): <sündmuse nimetus (name)> + " registreerumine".
-- sisu: "Sündmusele" + <sündmuse nimetus (name)> + < alguse aeg (varaseim EventDate ja StartTime)> " registreerimine." ja sellele järgnevad sisestatud osaleja andmed.
See e-mail saadetakse alati eesti keeles, sest selle saajaks on ürituse korraldaja.

**Comment by ruut12** [comment]
Organiseerija email võetakse nüüd õigest kohast

**Comment by TanelTromp** [comment]
TEST OK

Töötavad mõlemad kinnitused. Näited:

![pilt](https://user-images.githubusercontent.com/37407917/50344987-10382a80-0536-11e9-8028-3e49a41371ff.png)

![pilt](https://user-images.githubusercontent.com/37407917/50345006-1fb77380-0536-11e9-949d-3b65bf229efe.png)
