### ISSUE TITLE
Cachemise testimine ja parandamine

### ISSUE THREAD

**Issue by lsoonvald** [hariduspilv/haridusportaal#639]
TEST's on nüüd peale pandud Nginx + Varnish cache. Drupalis muudetud sisu invalideerib selle sisu osa cache'st. Testida läbi frontendi, kas päringutest saadav sisu muutub dünaamiliselt kui cache'i peaks invalideerima.

Lisaks vaadata üle, mis saab sisselogitud inimese töölaua päringutega.

**Comment by lsoonvald** [comment]
Frondis tuli tihti CORSi viga: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Lisasin Varnishile reegli, et kui seda headerit ei ole objektis, siis cachesse see ei lähe.

**Comment by lsoonvald** [comment]
Cache PURGE päringud pandud executema sisu salvestamise hetkel.

**Comment by lsoonvald** [comment]
Hämm 1: Eemaldasin ka superuudised sisu küljest, päringuga tulevad uued andmed koheselt. Pole back-endi cache teema. Kui viga endiselt üleval, siis uurida front-endi käest.

**Comment by TanelTromp** [comment]
Veel üks tähelepanek: sisuhalduses sisutüüp "uudise" lisamisel ilmub see kohe, "artikkel" aga tahab saada incognitot, et näha UI-s.

**Comment by lsoonvald** [comment]
Frondi poole pealt keelati browseri cache ära, nüüd võib üle testida.

**Comment by TanelTromp** [comment]
Ei tea, mida sa silmas pead "testimise all" (pileti esimene kommentaar arusaamatu) aga minu raporteeritud viimane teema, siis artikkel ilmub nt küll reaalajas aga OSKA tulemus mitte (sisu "CACHE tulemus") on olemas küll autocompletes aga tulemustes kuvab hoopis juba kustutatud artiklit "Test CACHE".

https://gyazo.com/d906c9803616ded951c3e73968e11beb
