### ISSUE TITLE
Sündmused sisutüübi vead

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#640]
**Selles piletis parandada vead 3-6 ja täpsustused 1-2 siis, kui tehtud on #766** 

Täpsustus 1: sama kuupäevaga põhikuupäev+registreerimine kombinatsioonis, ei kuva "registreerimise" nuppu (palun kontrollida mis hetkel jõuab BE sündmuse sisus tehtud muudatud kasutajaliidesesse. See võiks toimuda reaalaajas).

Täpsustus 2: Kui sisuhaldusest muuta sündmuse kuupäeva, siis sündmuste nimekiri vaates kuvab seda ikka vana kuupäevaga aga detailvaates õigega. **(nüüd on korda läinud aga varem ei mõjunud ka hardrefresh ega salarežiim)**: (palun kontrollida mis hetkel jõuab BE sündmuse sisus tehtud muudatud kasutajaliidesesse. See võiks toimuda reaalaajas).
Testlugu: http://htm.twn.ee/et/sundmused/pidu-koos-haridusministriga

https://gyazo.com/1ced55f810be105100c4cf4857d2b2cf

Viga 3: ei kuva "24/7 õpituba" kuupäeva "sarnaste sündmuste" kastis
http://htm.twn.ee/et/sundmused/testsundmus-regamisega

![pilt](https://user-images.githubusercontent.com/37407917/49863169-60154400-fe08-11e8-9e8a-a10aa04b162a.png)

![pilt](https://user-images.githubusercontent.com/37407917/49987686-e357a680-ff7c-11e8-9220-327b9c5b2b85.png)

Viga 4: "kell" ikkagi seljasl numbritel "Toimumisaeg ja -koht" tulbas:

http://htm.twn.ee/s%C3%BCndmused/n%C3%A4ide-hensule

Viga 5: "Töölaual" kuupäev/kellaaeg vaade hunnikus:

![pilt](https://user-images.githubusercontent.com/37407917/52464124-58f98080-2b82-11e9-820a-53e3fe3ec586.png)

Viga 6: "Päeva" asemel "invalid date" kalendrivaates:
https://gyazo.com/d1ab5fd3f60ed6109fb415f34a7ceffa

Viga 7: viskab kuupäeva punaseks, koos veateatega:

https://gyazo.com/366ab4174cace38ebefe0495c9cf77bd

Vigas 8: ei näita kuupäevi "Registreeru XXXX alates XXX kuni" ja URL katki:

![pilt](https://user-images.githubusercontent.com/37407917/55151074-19005400-5156-11e9-9ba8-e44faf27b110.png)

Viga 9: "9 mai":

![pilt](https://user-images.githubusercontent.com/37407917/56131863-51df5c00-5f91-11e9-8554-549eda312f4a.png)

Ux-täiendus 1: kuvada registreerimisvormil ka aastat, lisaks kuupäevale (oluline ka nt siis, kui põhikuupäev detsembris ja lisakuupäev nt jaanuraris):
Egle: reg vormil aasta kuvamine pole vajalik.

![pilt](https://user-images.githubusercontent.com/37407917/50054973-3b470680-0151-11e9-9376-ed02820a86e5.png)

**Comment by heldiraudsepp** [comment]
Teemad lähevad lahendamisele sündmuste uue analüüsi käigus
