### ISSUE TITLE
Sisuhalduses Eemalda nupp infograafikute kustutamiseks

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#642]
Lisada sisuhalduses OSKA sisutüüpidele (valdkond, ametiala, tööjõuprognoos ja tulemused), kus on dünaamilise infograafika lisamise võimalus, nupp "Eemalda", mis võimaldab sisestatud graafiku kustutada.

**Comment by heldiraudsepp** [comment]
BE - vajab täiendavat uurimist. eelduslikult vähemalt paar päeva
Test -

**Comment by EgleM-TW** [comment]
Kuna planeerimisel jäi otsus, et pole oluline teema, sulgen pileti ja vajadusel teeme uue Jiras.
