### ISSUE TITLE
URL-i nimetuse muutmine oska sisutüübil

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#643]
Muuta sisutüübil ServeyPage URL nimetuses ülduuring tööjõuprognoosiks - 
Näide: http://htm.twn.ee/ülduuringud/urli-test

**Comment by madispold** [comment]
URL muudetud.

**Comment by madispold** [comment]
http://htm.twn.ee/t%C3%B6%C3%B6j%C3%B5uprognoos/urli-test

**Comment by TanelTromp** [comment]
TEST OK

Testlugu:
http://htm.twn.ee/t%C3%B6%C3%B6j%C3%B5uprognoos/%C3%B6%C3%B6%C3%B6rli-test-s%C3%A4%C3%A4%C3%A4p%C3%BCr

**Comment by lsoonvald** [comment]
Täpsustus 1: Peaks nüüd korras olema. @TanelTromp

**Comment by TanelTromp** [comment]
TEST

Kõik vanad sisud uue URL-i peal ja uued loodud sisud samuti.
