### ISSUE TITLE
OSKA ametiala lehte ei saa salvestada

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#648]
Keskkond: prelive/live
Sirvik: Chrome/Safari

Salvesta nupp ei tee midagi

**Comment by TanelTromp** [comment]
Kas sisestasite kõik kohutsutlikud väljad ja kasutusjuhendi järgi? Kas sisestasite ka "OSKA valdkond" väljale väärtuse?

![pilt](https://user-images.githubusercontent.com/37407917/50628464-e5d86b00-0f40-11e9-907a-2fa37b1da044.png)

**Comment by erkkijakobson** [comment]
Puuduv kohustuslikkuse tärn ja veateade oligi kasutajal probleemiks.

**Comment by heldiraudsepp** [comment]
Kohustuslikkuse nõue läheb maha #655
