### ISSUE TITLE
Oska valdkonna lehel ametialade lisamine vabatahtlikuks.

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#655]
1. Muuta sisutüübil OSKA valdkond (FieldPage) ametialade lisamine vabatahtlikuks. Probleemi kirjeldus siin #648 . Ametiala lisamisel peab valdkonna lk olema salvestatud.

Tanel, palun muuda kasutusjuhendis ka ära.

**Comment by heldiraudsepp** [comment]
@TanelTromp muudab ka kasutusjuhendit

**Comment by TanelTromp** [comment]
UX-täiendus: eemaldada "puudu" valik rippmenüüst üldse või muuta see passiivseks pärast valiku(te) tegemist sellest. Hetkel valikuid tehes jääb see vaikimisi valituks, mis tekitab segadust.

https://gyazo.com/420cff7a8748fc8a015e7266fad82a7b

**Comment by lsoonvald** [comment]
Ei ole lihtsasti muudetav asi, vajab lisaarendust.

**Comment by TanelTromp** [comment]
TEST OK
