### ISSUE TITLE
Dokumendivormi tabeli täiendamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#658]
- [ ] Tabeli tüüpi ("type" : "table") elementi saab peita ehk kasutada "hidden" lisatunnust.
- [ ] Tabelisse veergudes ("table_columns") saab kasutada aadressi tüüpi ("type" : "address") elementi, mille korral on võimalikud hidden, required ja readonly lisatunnused.

- [ ] BE-s täiendada definitsiooni kontrolle, et eelnevale vastava definitsiooni salvestamine oleks võimalik.

**Comment by heldiraudsepp** [comment]
BE - 4h
FE - 10h
Andrus - 2h
