### ISSUE TITLE
OSKA vahe-avalehe disain (uus)

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#663]
Hetkel selline disain - https://zpl.io/2vWENwj
Kliendilt saadud info on lisatud BE #448  ja FE #449 piletitesse. Palun tutvu esmalt nende sisudega.

Lühidalt muus osas pisi-täiendused, aga ära jääb Põhikutsealade kolmene blokk - selle asemele nuputaks, kas õnnestub ühe sisulehe Üldprognoos" esiletoomine, aga ilma fotota. Halvemal juhul 1 infograafika, aga pigem mitte. Arutame seda.

**Comment by EgleM-TW** [comment]
Hilisem töö, ei ole esimene prioriteet.
