### ISSUE TITLE
OSKA ametiala sisulehel fikseeritud sildi muudatus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#674]
Eesmärk: Tuleviku ala tag´i pealkirja on vaja muuta sisuhalduri poolt muudetavaks ja võimalus kasutada rohkem kui ühte tag-i. 

Olev lahendus:
OSKA ametiala sisulehel on fikseeritud silt (fixedLabel) „Tuleviku ala!“, mille lisamine on vabatahtlik. Silti kuvatakse ametialade nimekirjas ning selle alusel saab ametialasid filtreerida.

Uus lahendus:
Ühele ametiala sisulehele lisatavaid silte (fixedLabel) on 1, lisamine on vabatahtlik (radio button), vaikimisi on valimata.
Sildid on hallatavad (taksonoomiate alt): saab luua uusi silte/ muuta sildi nimetust - pikkus kuni 50 tähemärki.
Siltide alusel peab saama ametialasid filtreerida #675

**Comment by EgleM-TW** [comment]
Ei ole esimene prioriteet.

**Comment by heldiraudsepp** [comment]
BE - 6h
Test - 2h

**Comment by TanelTromp** [comment]
Viga 1: kuvab "Puudub" valikut:

![pilt](https://user-images.githubusercontent.com/37407917/53088280-ef7a5a00-3511-11e9-908c-9d093dfc3422.png)


Viga/täiendus 2: kuna pikkus on limiteeritud, siis võiks olla termini lsiamisel "Nime" väljal 50 counter

**Comment by lsoonvald** [comment]
Viga 1: Korras.

Täiendus 1: Material adminiga tuleb see, ei tee ümber.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Ühele ametiala sisulehele lisatavaid silte (fixedLabel) on 1, lisamine on vabatahtlik (radio button), vaikimisi on valimata.

- [x] Sildid on hallatavad (taksonoomiate alt): saab luua uusi silte/ muuta sildi nimetust - pikkus kuni 50 tähemärki.

------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/53094639-5f451080-3523-11e9-8bda-750d8b434603.png)

![pilt](https://user-images.githubusercontent.com/37407917/53094543-0ffee000-3523-11e9-8d0c-9494b6ee740e.png)

![pilt](https://user-images.githubusercontent.com/37407917/53094583-36bd1680-3523-11e9-8822-c9160ff90411.png)
