### ISSUE TITLE
Otsingu muutmine mitmese valikuks - ametialad

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#675]
**Eesmärk:**
Ametiala detailvaates kuvatakse lisatud silti ja nimekirjas saab ametialasid sildi alusel filtreerida.
See töö on seotud filtrite ühtlustamisega - mitmese valiku lisamine.

**Eeltingimused ja käivitamine:**
Kasutaja on avanud ametialade nimekirja. Realiseeritud on BE töö #674 

Disaini näide valitud siltidega: https://zpl.io/aNp6ZZD

**Täpsustused:**
- Mitmene valik kuvada rippmenüü valikna, kus valiku tegemiseks ja eemaldamiseks on märkeruut.
- Kui valikuid pole tehtud kuvatakse nimekiri tähestikuliselt.
- Valiku tegemisel ja rippmenüü sulegmisel, kuvatakse kasutaja valikud, kus eraldajaks on koma (disaini näide).
- Kui valikud on tehtud ja kasutaja sulgeb--avab rippmenüü uuesti, kuvatakse eespool varem tehtud valikud (tähestikuliselt) ja siis ülejäänud valikud tähestikuliselt.

**Vastuvõtutingimused:**
Otsingu väljade muudatused - **loe kõik läbi, enne kui arendad!**:
1. Eemaldada märkeruut _Näita "Tuleviku ala!" ametialasid_
2. Lisada mitmsese valikuga otsing siltide alusel: väli "Ametialade sildid" kõige alumise väljana (üks pikk väli).
3. Lisada mitmese valiku võimalus väljale Valdkond (OSKAFiled).
4. Muuta väli Sorteeri lühemaks ja paigutada Valdkond otsingu alla samas mõõdus.
5. Lisada Märkõna otsingu alla samas mõõdus mitmese valikuga otsingu väli "Konkurents tööturul" (mitmene valik)
Valikus kuvada ametialadega seotud "Konkurents tööturul" filling bar väärtusi (vt #698):
- kerge
- üsna kerge
- keskmine
- üsna raske
- raske
Kuvada filtris kõik filling bar väärtused. 
Kui otsing ei anna tulemust, kuvada "Otsingutulemused puuduvad"

**Sarnased tööd:**
1. uudiste otsing: #759
2. erialade otsing: #682
3. sündmuste otsing: #769
4. õppeasutused: #677

**Comment by heldiraudsepp** [comment]
FE - 14h
Test - 8h

**Comment by heldiraudsepp** [comment]
FE - 17h
Test - 8h
Disaini test - 1h

**Comment by TanelTromp** [comment]
Viga 1: puudub "Punane nooleke" välja paremas ääres, mis indikeerib rippmenüüd - vastavalt siis eemaldada "x" valiku tühjaks tegemisel, sest muud sarnased filtri valikud on teistsugused @birgitpulk 

![pilt](https://user-images.githubusercontent.com/37407917/55872705-502f2600-5b96-11e9-8f02-7d5f99965386.png)

Viga 2: kui eemaldada "Valdkond" valikust valik ja rippmenüü uuesti avada, siis ei taasta tähestiku järjekorda, vaid viimane valik jääb esimeseks

Viga 3: "Konkurents tööturul" nimetused ei klapi nõudes kirjeldatuga (NB! Peaks hakka suure algustähega ka muidugi):

kerge
üsna kerge
keskmine
üsna raske
raske

Täpsustus 1: kontrollida üle tehtud valikute fondi värv, raksus jms väljal - Zeplinis on paremini loetav versioon IMHO @birgitpulk 

Lisatöö 1: Ühtlustada uudiste filtrirga disain  @EgleM-TW kas kirjas või teine pilet juba olemas?
http://htm.twn.ee/uudised

**Comment by EgleM-TW** [comment]
Viga nr 3 läheb maha, https://github.com/hariduspilv/haridusportaal/issues/694 järgi väärtuste nimetused pikemad kui nõuetes on OK.

**Comment by EgleM-TW** [comment]
https://github.com/hariduspilv/haridusportaal/issues/694 järgi Konkurents tööturul väärtuste nimetused pikemad kui nõuetes on OK.

**Comment by EgleM-TW** [comment]
https://github.com/hariduspilv/haridusportaal/issues/694 järgi Konkurents tööturul väärtuste nimetused pikemad kui nõuetes on OK.

**Comment by priitpu** [comment]
> Viga 1: puudub "Punane nooleke" välja paremas ääres, mis indikeerib rippmenüüd - vastavalt siis eemaldada "x" valiku tühjaks tegemisel, sest muud sarnased filtri valikud on teistsugused ja lisaks ei klapi Zepliniga @birgitpulk

Parandatud

> Täpsustus 1: kontrollida üle tehtud valikute fondi värv, raskus jms väljal - Zeplinis on paremini loetav versioon IMHO ja kui oleks font-weight "300!important" maha keeratud stiilidest

Mulle tundub ka font-weight normal etem
![image](https://user-images.githubusercontent.com/17040443/55955322-c3559c80-5c69-11e9-9064-ac55ea90fc9c.png)

> UX-täiendus 2 mobiilivaade: kui minna "/ametialad" url-le, siis skroll ei ole TOP of the page, vaid veidi alla ja foldist jääb välja "filtreeri" nupp - kasutaja ei pruugi seda nii märgata

Parandatud

> Viga WCAG 1: (see võib juba ammust ajast rukkis olla aga): checkoboxe peaks saama valida SPACE-ga, mitte ENTERiga.

Ilma sisendita selecte saab valida nii space kui ka enteriga.
Sisendiga, nagu on **Ametialade sildid** peab space olema sisendi kirjutamiseks vaba

**Comment by TanelTromp** [comment]
Viga 3 sürrus: tahvelvaates (iPad) on filtrites ainult "Märksõna" ja "Valkond" valikud. Teised puuduvad.

**Comment by priitpu** [comment]
> UX-täiendus 1 mobiilivaade: placeholderid ei ole joondatud keskele, vaid veidi üles

Jäi eelmisesse kommentaari panemata, sorri. Parandatud.

> Viga 3 sürrus: tahvelvaates (iPad) on filtrites ainult "Märksõna" ja "Valkond" valikud. Teised puuduvad:

Parandatud

**Comment by TanelTromp** [comment]
UX-täiendus x: kas mobiilivaates saab "ametialade sildid" juures maha keerata "type" väljatüübi? Viskab klaveri ette ja midagi enam teha ei mahu.

**Comment by birgitpulk** [comment]
Ux-täiendus x: pigem ei teeks seda, kokkulepe kliendiga, et silte ei tule nii palju

**Comment by TanelTromp** [comment]
TEST OK

**Täpsustused:**

- [x] Mitmene valik kuvada rippmenüü valikna, kus valiku tegemiseks ja eemaldamiseks on märkeruut.
- [x] Kui valikuid pole tehtud kuvatakse nimekiri tähestikuliselt.
- [x] Valiku tegemisel ja rippmenüü sulegmisel, kuvatakse kasutaja valikud, kus eraldajaks on koma (disaini näide).
- [x] Kui valikud on tehtud ja kasutaja sulgeb--avab rippmenüü uuesti, kuvatakse eespool varem tehtud valikud (tähestikuliselt) ja siis ülejäänud valikud tähestikuliselt.

**Vastuvõtu tingimused**

- [ ] Eemaldada märkeruut Näita "Tuleviku ala!" ametialasid
- [ ] Lisada mitmsese valikuga otsing siltide alusel: väli "Ametialade sildid" kõige alumise väljana (üks pikk väli).
- [ ] Lisada mitmese valiku võimalus väljale Valdkond (OSKAFiled).
- [ ] Muuta väli Sorteeri lühemaks ja paigutada Valdkond otsingu alla samas mõõdus.
- [ ] Lisada Märkõna otsingu alla samas mõõdus mitmese valikuga otsingu väli "Konkurents tööturul" (mitmene valik)
- [ ] Valikus kuvada ametialadega seotud "Konkurents tööturul" filling bar väärtusi 

-------------
Kuvatõmmised
