### ISSUE TITLE
Valdkonna ja ametiala sisutüübi paremas veerus muudatused

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#679]
OK - võib arendada!

**Üldinfo**

OSKAFieldPage (valdkond) ja OSKAMainProfessionPage (ametiala) paremas veerus kuvatakse blokki "Tasub teada", mille sisu sisestab OSKA sisuhaldur. Selle tööga lisanduvad neutraalsed faktid ja muutuvad kuvatavad ikoonid.

Disain: https://zpl.io/V41Wg1M või https://zpl.io/2ZzOYOd

**BE**
Valdkonna ja ametiala sisutüübi paremas veerus:
- Bloki "Tasub teada" sisuks on plussid, neutraalsed faktid ja miinused.
Sisuhalduses lisada "Plussid" ja "Miinused" vahele "Neutraalsed faktid" , kuhu sarnaselt plussidele ja miinustele saba lisada kuni 5 fakti, kus teksti sisestus kuni 100 tähemärki.

Testimiseks info: ükski väli pole kohustuslik täita, võib olla lisatud ainult plussid, ainult miinused, ainult neutraalsed aspketid jne. Fikseeritud on ainult max arv igas jaos - 5tk.

- Ametiala sisutüübi paremas veerus bloki Näidiametid bloki pealkirjaks muuta "Ametid"

**FE**
Valdkonna ja ametiala sisutüübi paremas veerus:

- Bloki _Plussid ja miinused_ pealkiri kuvada → "Tasub teada"
- Kuvada uued ikoonid (jaotub kolmeks: plussid, neutraalsed faktid, miinused, sh on see kuvamise järjekord) 
- Kui andmeid pole sisestatud, siis midagi ei kuvata (tühja "Tasub teada" blokki ei kuvata, vaid järgmine blokk liigub üles) Tühja ikooni ei kuvata ehk näiteks kui plusse pole sisestatud  siis neutraalsed faktid kuvatakse esimesena. 
- Kuvada "Näidisametid" asemel "Ametid"

**Comment by heldiraudsepp** [comment]
BE - 1
FE - 3
Test - 5

**Comment by lsoonvald** [comment]
BE poole pealt tehtud, päring uuendatud ning vastav väli lisatud.

**Comment by madispold** [comment]
Testimisse @TanelTromp @birgitpulk

**Comment by TanelTromp** [comment]
Viga 1 WCAG: VO ütleb plusside kohta "pluss", miinuste kohta "miinus" ja neutraalse kohta "sidebar neutral". Võiks siis selle loogika järgi öelda: "neutraalne"

**Comment by RainLeoma** [comment]
Sobib

**Comment by birgitpulk** [comment]
Kujundus korras

**Comment by TanelTromp** [comment]
TEST OK

BE
- [ ] Sisuhalduses lisada "Plussid" ja "Miinused" vahele "Neutraalsed faktid" , kuhu sarnaselt plussidele ja miinustele saba lisada kuni 5 fakti, kus teksti sisestus kuni 100 tähemärki.
- [ ] Testimiseks info: ükski väli pole kohustuslik täita, võib olla lisatud ainult plussid, ainult miinused, ainult neutraalsed aspketid jne
- [ ] Ametiala sisutüübi paremas veerus bloki Näidiametid bloki pealkirjaks muuta "Ametid"

FE

- [ ] Bloki _Plussid ja miinused_ pealkiri kuvada → "Tasub teada"
- [ ] Kuvada uued ikoonid (jaotub kolmeks: plussid, neutraalsed faktid, miinused, sh on see kuvamise järjekord)
- [ ] Kui andmeid pole sisestatud, siis midagi ei kuvata (tühja "Tasub teada" blokki ei kuvata, vaid järgmine blokk liigub üles) Tühja ikooni ei kuvata ehk näiteks kui plusse pole sisestatud  siis neutraalsed faktid kuvatakse esimesena.
- [ ] Kuvada "Näidisametid" asemel "Ametid"
-------------------

Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/53016076-57b73600-3455-11e9-9542-133b3b9dc88b.png)

![pilt](https://user-images.githubusercontent.com/37407917/53016112-77e6f500-3455-11e9-8bdd-504859e546af.png)
