### ISSUE TITLE
Muuta ametialade võrdluses kuvatavaid elemente

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#680]
**Üldinfo**
Portaali külastaja saab ametialasid võrrelda. Selle tööga muudame #478 realiseeritud ametialade võrdluses kuvatavaid elemente. #478 kirjeldatud tegevuste käivitamise, lisamise ja eemaldamise nõudeid ei muudeta.

Disain: https://zpl.io/Vkw3pgq

**Võrdluse vaatamine**
Süsteem kuvab võrdlusesse lisatud ametialade kohta tabeli kujul järgmised andmed:
* Ametiala nimetus 
Ametiala nimetus kuvatakse lingina, millele klikkimisel avatakse selle ametiala detailvaade.
* Silt 
* Valdkonnad (kui on mitu siis üksteise all)
* Konkurents tööturul (nii nagu filling bar detailvaates)

* Faktid (vahepealkirjata)
   - Hõivatute arv (ikoonita)
   - Hõive muutus (ikoon ja tekst)
   - Brutopalk (ikoonita, väärtus ja euro märk)
   - Töökohtade ja lõpetajate arvu võrdlus (ikoon ja tekst)

* Tasub teada (ikoon ja tekst)

**Comment by RainLeoma** [comment]
Sobib.

**Comment by EgleM-TW** [comment]
FE: 16
test: 8

**Comment by madispold** [comment]
Testimisse @TanelTromp 

Hetkel võrdluse tabelile ei pannud fikseeritud võrdset laiuse jaotust nagu kujunduses, kuna kohati ühel ametialal palju infot ja järgmisel vähe. Kas jätta ruumi sinna rohkem kus seda reaalselt kasutuse või fikseeridal? @TanelTromp  @birgitpulk

**Comment by TanelTromp** [comment]
TEST

_Hetkel võrdluse tabelile ei pannud fikseeritud võrdset laiuse jaotust nagu kujunduses, kuna kohati ühel ametialal palju infot ja järgmisel vähe. Kas jätta ruumi sinna rohkem kus seda reaalselt kasutuse või fikseeridal? @TanelTromp @birgitpulk_

Täpsustus 1: võiks olla alati 33/33/33 plokkide laius nagu Zeplinis, sõltumata sisust @birgitpulk 

Viga 1: "Eemalda võrdlusest" Zeplinis joondatud kesekele, testis vasakule joondatud

Viga 2: "Hõive muutus" labelit kaks korda:

![pilt](https://user-images.githubusercontent.com/37407917/53430164-abe28d00-39f6-11e9-99a0-16b2e15c1462.png)

**Comment by madispold** [comment]
Täpsustus 1: OK.
Viga 1: OK. Mobiilis (alla 720px), täidab ruumi vastavalt sisule, kuna keritav sisu.
Viga 2: OK.
Viga 3: OK.
Viga 4: OK.
Viga 4.1: OK ja nii tabel töötab.
Viga 5: Nii tabelid töötavadki, siin võib segadust tekitada asjaolu, et pole veergude eraldusjooni. Kui kõrvalveerg venib kõrgemaks, siis esimene lühem veerg jääb sellisena, hetkel vertikaalselt ka joondatud keskele - saaks selle joondusega mängida vajadusel - OK.
Viga 6: OK.
Viga 7: OK.
Viga 8: OK.
UX-täiendus 0: OK.
UX-täiendus 1: OK.
UX-täiendus 2: Checkboxide väärtuste muutmist jälgib süsteem hetkel ja seeläbi veendub lisamise alustamisel kas on juba 3 võrdlusesse lisatud. Selle käitumise muutmiseks peaks ka loogikat muutma - määrata checkbox disabled või teistmoodi kontroll teha - ehk ei hakkaks sellise pisiasja tõttu tegema siinkohal midagi: OK.

**Comment by TanelTromp** [comment]
Viga 9 uus: (sama kala, mis paremal "Raske" kuvades - veidi väiksemaks võiks teha neid elemente ma arvan):

![pilt](https://user-images.githubusercontent.com/37407917/53566798-f20a2e80-3b65-11e9-9d3c-cf8b2ed37f7a.png)

**Comment by madispold** [comment]
Täpsustus 1: OK, alla 720px ei ole fixed.
Viga 9 uus: OK.
Viga 10 uus: OK.
Viga 11 uus: OK.

**Comment by TanelTromp** [comment]
Viga 12 uus: tekst ja nool katki:

![pilt](https://user-images.githubusercontent.com/37407917/53625315-6cd95500-3c0b-11e9-8099-83a0d6327851.png)

**Comment by madispold** [comment]
Viga 12: OK.
Viga 13: OK.

**Comment by TanelTromp** [comment]
TEST OK

Süsteem kuvab võrdlusesse lisatud ametialade kohta tabeli kujul järgmised andmed:

- [ ] Ametiala nimetus
- [ ] Ametiala nimetus kuvatakse lingina, millele klikkimisel avatakse selle ametiala detailvaade.
- [ ] Silt
- [ ] Valdkonnad (kui on mitu siis üksteise all)
- [ ] Konkurents tööturul (nii nagu filling bar detailvaates)
- [ ] Faktid (vahepealkirjata)
- [ ] Hõivatute arv (ikoonita)
- [ ] Hõive muutus (ikoon ja tekst)
- [ ] Brutopalk (ikoonita, väärtus ja euro märk)
- [ ] Töökohtade ja lõpetajate arvu võrdlus (ikoon ja tekst)
- [ ] Tasub teada (ikoon ja tekst)


----------------

Kuvatõmmised

Desktop

![pilt](https://user-images.githubusercontent.com/37407917/54206328-c3367580-44e0-11e9-8ecd-57b0a8412310.png)
