### ISSUE TITLE
Ametiala sisulehelt õppimisvõimaluste siselingi täiendamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#681]
Eesmärk:
Ametiala sisuhlehel blokis Õppimisvõimalused lingile vajutades avaneb filtreeritud õppekavade (erlaade) nimistu vaade. Sisuhalduses saab lisada mitu õppekavarühma ja õppekava taset.

Sisuhalduses:
Teha ümber Ametiala sisutüübi paremas veerus õppimisvõimaluste lisamine:
- Vabatekstiväli maha.
- Saab sisestada mitu õppekavarühma ja õppekava taset.

Kasutajaliideses
Eeltingimused ja käivitamine

- Sisuhaldur on lisanud ametiala paremas veerus õppimisvõimalusteks mitu õppekavarühma ja õppekava taset
- Kasutaja on ametiala sisulehel vajutanud õppimisvõimaluste lingile, mille tulemusel kuvatakse erialade nimistu, kus otsingus on filtreeritud mitme õppekavarühmaga seotud õppekavad.

Selle pileti raames ei testi erialade filtris multi-select kuvamist, selleks on eraldi töö: #682 

Disaini tõmmis piletis #748

**Comment by RainLeoma** [comment]
Sobib!

**Comment by lsoonvald** [comment]
Sisutüüpi uuendatud, saab nüüd sisestada Õppekava taset ka, päringus ka uued andmed olemas

**Comment by EgleM-TW** [comment]
@skeefee Saab teha frontendi.

**Comment by EgleM-TW** [comment]
@TanelTromp Testimisel las BE lisab ka infomulli, et mitme lisamisel eraldajaks koma.

**Comment by madispold** [comment]
Lahendus üleval, lingi visuaal veel lahtine @EgleM-TW

**Comment by madispold** [comment]
OK vastavalt #748'le.

**Comment by TanelTromp** [comment]
Viga 1 BE: tingimus ei ole täidetud: _Testimisel las BE lisab ka infomulli, et mitme lisamisel eraldajaks koma._

Täiendus 1: "Õppekavarühm", mitte "Õppekava rühm":
![pilt](https://user-images.githubusercontent.com/37407917/52693120-7f4a6200-2f6e-11e9-91e2-41d4794d6944.png)

Täpsustus 1 BE! _Vabatekstiväli maha. Saab sisestada mitu õppekavarühma._ Kas siin on silmas peetud rippmenüüga asendamist? Hetkel endiselt "vabatestkiväli" @EgleM-TW

**Comment by madispold** [comment]
Viga 1, Täiendus 1: @lsoonvald 
Viga 2: Oska infograafikast tulenev viga, ei lahendaks selle pileti all? @TanelTromp

**Comment by lsoonvald** [comment]
Viga 1, Täiendus 1: Done.

**Comment by TanelTromp** [comment]
TEST OK

Sisuhalduses:

- [ ] Teha ümber Ametiala sisutüübi paremas veerus õppimisvõimaluste lisamine:

    * Vabatekstiväli maha.

    * Saab sisestada mitu õppekavarühma ja õppekava taset.


Kasutajaliideses:

- [ ] Eeltingimused ja käivitamine

    * Sisuhaldur on lisanud ametiala paremas veerus õppimisvõimalusteks mitu õppekavarühma ja õppekava taset

    * Kasutaja on ametiala sisulehel vajutanud õppimisvõimaluste lingile, mille tulemusel kuvatakse erialade nimistu, kus otsingus on filtreeritud mitme õppekavarühmaga seotud õppekavad.

--------------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/52775658-d91f5a80-3048-11e9-97d9-7f395d281257.png)

![pilt](https://user-images.githubusercontent.com/37407917/52775689-eb999400-3048-11e9-8e25-e66a807ae2bf.png)

Video:
https://gyazo.com/3c82c0f64896ea442d22a3fec105f3b1
