### ISSUE TITLE
Otsingu muutmine mitmese valikuks - erialad

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#682]
**Eesmärk**
Portaali kasutajal on otsingutes võimalik valida mitut väärtust korraga (multi select).
***
Disaini näide valitud siltidega: https://zpl.io/aNp6ZZD

**Nõuded:**
- Mitmene valik kuvada rippmenüü valikna, kus valiku tegemiseks ja eemaldamiseks on märkeruut.
- Kui valikuid pole tehtud kuvatakse nimekiri tähestikuliselt.
- Valiku tegemisel ja rippmenüü sulegmisel, kuvatakse kasutaja valikud, kus eraldajaks on koma (disaini näide).
- Kui valikud on tehtud ja kasutaja sulgeb--avab rippmenüü uuesti, kuvatakse eespool varem tehtud valikud (tähestikuliselt) ja siis ülejäänud valikud tähestikuliselt.
***
**Vastuvõtutingimused:**
Selle tööga realiseerida erialade otsingu vastamine eelnevalt kirjedatud mitmese valiku tegemise reeglitele: http://htm.twn.ee/erialad?open_admission=true
Mitmene valik lisada väljadele:
- Eriala tüüp (StudyProgrammeType)
- Õppekava tase (StudyProgrammeLevel)
- Õppevaldkond (ISCEDFbroadField)
   -  Õppesuund (ISCEDFnarrowField)
   -  Õppekavarühm (ISCEDFdetailedField)
- Õppekeel (TeachingLanguage)
Filtreerimise üldised tingimused on realiseeritud tööga #148 
***
**Sarnased tööd:**
1. uudiste otsing:  #759 
2. sündmuste otsing: #769 
3. õppeasutused: #677 
4. ametialad: #675

**Comment by heldiraudsepp** [comment]
Kui valmis, siis vaja kohe live'i liigutada

**Comment by TanelTromp** [comment]
**erialade otsing: http://htm.twn.ee/erialad?open_admission=true**

Viga 1: tinigmus ei ole täidetud "Õppekava tase" valiku puhul _Kui valikuid pole tehtud kuvatakse nimekiri tähestikuliselt._

**Comment by EgleM-TW** [comment]
Filtrite tühistamise teeme kunagi hiljem uue tööna.

**Comment by priitpu** [comment]
> Viga 1: tinigmus ei ole täidetud "Õppekava tase" valiku puhul Kui valikuid pole tehtud kuvatakse nimekiri tähestikuliselt.

Parandatud

> Viga 2: tinigmus ei ole täidetud "Õppevaldkond" valiku puhul Kui valikuid pole tehtud kuvatakse nimekiri tähestikuliselt.

Parandatud

> Viga 3: tinigmus ei ole täidetud "Õppekavarühm" valiku puhul Kui valikuid pole tehtud kuvatakse nimekiri tähestikuliselt.

Parandatud

> Viga 4: kontrollida, kas placeholderi (kus puudub rippmenüü) CSS vastab Zeplini stiilile 1:1:

Parandatud. Muutused peaks olema üle lehe.

> UX-täiendus 1: kui eemaldada "Õppesuund" valikust valik, siis peaks "Õppekavarühm" valik taas passiivseks muutuma - hetkel jääb aktiivseks, kuigi ühtegi valikut seal ei ole. Täpselt sama loogika "õppevaldkond" vs "Õppesuund" puhul.

Parandatud

> UX-täiendus 2 mobiilivaade (täiendus, kuna puudub Zeplinis mobiilivaade): filtrite järjekord mobiilivaates paigast ära. Kaaluda järjekorda, et esimene tulp ja siis teine tulp vastavalt desktopist.

Nõustun.
Parim mis hetkel teha saab on selline
![image](https://user-images.githubusercontent.com/17040443/56348396-01edd880-61cf-11e9-97fb-9a0a3e337f48.png)
See on juba kordades parem UXi mõttes, kuid liialt HTMLi väänamist/koodi dubleerimist et täielikult blokid ära eraldada

**Comment by TanelTromp** [comment]
UX-täiendus 3: laeb ühe elemendi eraldi teistest filtri elementide plokist ja hiljem ("eriala tüüp") - iseäranis hakkab silma, kui aeglasema ühendusega testida:
https://gyazo.com/1b6b66284037dd55791b957fbdbc369b

UX-täiendus 4: hoveriga võiks kuvada täispikkuses nime - kui on pikemad nimed ja sarnase algusega, siis ei saa aru, mida valid väiksemas resos. NB! Kui ei ole Material designi rippmenüü funktsioon, siis jätame ära:
https://gyazo.com/55675cdf0f6e40b659fb5720854ad562

**Comment by priitpu** [comment]
> UX-täiendus 3: laeb ühe elemendi eraldi teistest filtri elementide plokist ja hiljem ("eriala tüüp") - iseäranis hakkab silma, kui aeglasema ühendusega testida:

OK

> UX-täiendus 4: hoveriga võiks kuvada täispikkuses nime - kui on pikemad nimed ja sarnase algusega, siis ei saa aru, mida valid väiksemas resos. NB! Kui ei ole Material designi rippmenüü funktsioon, siis jätame ära

Teoorias saaks tooltipina või kuidagi näidata, ent see on juba natukene rätseplahendus ning ma arvan et arvatavasti tahaks natukene disainerit saada.

[Tooltip komponent - Material](https://material.angular.io/components/tooltip/overview)

**Comment by TanelTromp** [comment]
Ootab kujundaja checkki.

**Comment by birgitpulk** [comment]
Kujundus ok

**Comment by TanelTromp** [comment]
TEST OK

- [x] Vastuvõtutingimused:

Selle tööga realiseerida erialade otsingu vastamine eelnevalt kirjedatud mitmese valiku tegemise reeglitele: http://htm.twn.ee/erialad?open_admission=true
Mitmene valik lisada väljadele:

Eriala tüüp (StudyProgrammeType)
Õppekava tase (StudyProgrammeLevel)
Õppevaldkond (ISCEDFbroadField)
Õppesuund (ISCEDFnarrowField)
Õppekavarühm (ISCEDFdetailedField)
Õppekeel (TeachingLanguage)

------------
Video:
https://gyazo.com/f0e734937d690ad3cc84ba669aa3ec5d
