### ISSUE TITLE
Seos OSKA Valdkond ja Tulemused sisulehel - disain

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#683]
1. Sisutüüp OSKA valdkond paremas veerus uus blokk: Uuringu ettepanekud → see on ainult link, mis viib sisulehele Tulemused, kus tabel on filtreeritud selle valdkonna järgi, kus kasutaja linki vajutas. 

2. Selle töö raames kujundada ümber ka Tulemused sisulehel kuvatav tabel.
Kui kasutaja navigeerib tabeli vaatesse valdkonna lehelt, siis on tabelis korraga kuvatud ainult ühe valdkonna andmed (filtreeritud). Ühe valdkonna vaatamisel ei kuva tabelis lahtrit Valdkond. 

_Samas kui kasutaja valib filtrist kõik valdkonnad, või satub Tulemused sisulehele otse (mitte läbi valdkonna lehe) siis tuleb tabelis kuvada ka valdkond veergu._
Tabeli päis:
_Valdkond (siis kui valitud Kõik)_; Ettepanek; Peavastutaja; Staatus (ikoonina taheti) ja siia infomull mille sees Eksperdikogu kommentaar.
Ettepaneku staatused:
 1.Töös
 2.Tegemata
 3. Tehtud

Tööga alsutades vaata ka esimest Raini kommentaari ja arutame, kuidas lahendada tabeli vaade, kui kasutaja satub lehele otse - _kaldkirjas osad._

Vaata ka #625  - sarnaselt vaja lahendada tabeli disain

**Comment by RainLeoma** [comment]
Sobib!

Võibolla ikkagi teeks sisu lihtsamaks, et tulemuste tabelis saab korraga vaadata ainult ühte valdkonda. See jätaks ära valdkonna kuvamise, kui valida kõik valdkonnad. Kui kasutaja tahab vaadata kõiki valdkondasid, siis ta laeb alla Exceli. Veebi lahendus on mõeldud kiire ülevaate saamiseks, mitte tulemuste võrreldavaks analüüsiks. Kui kasutaja satub tulemuste lehele otse, siis kuvatakse talle vali valdkond filtrit. Valdkonna valides kuvatakse tabelit ja muid filtreid. Kui see lahendus on liiga keeruline, siis võib-kuvada ühte (esimest) valdkonda, kuid filtris peab kohe olema arusaadaval kohal, et mis valdkonda kuvatakse.

**Comment by EgleM-TW** [comment]
OK, arutame disaini tegemise käigus.

**Comment by birgitpulk** [comment]
Disain: 
Tulemuste vaade: https://zpl.io/VQEgxzm
Tulemuste tabel: https://zpl.io/aMP5nPz
