### ISSUE TITLE
Lisada OSKA Valdkonna lehele link Tulemuste tabelile - filtreeritud

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#684]
**Eesmärk**
OSKA valdkonna sisuleht (FieldPage) on lingitud tabeliga, mis asub sisutüübil OSKA tulemused (ResultPage). Selle töö raames muudetakse Tulemused sisutüübil tabeli kuvamist, mis uuendusena avaneb eraldi vaatena.

**Käivitamine ja vastuvõtutingimused**

**1. Tabeli avamine valdkonna vaatest**
Valdkonna sisutüübi paremas veerus blokkide "Hõivatute arv" ja "Tasub teada" järel (kui eelnevaid pole sisestatud siis esimesena) kuvada blokki "Tulemused" koos lingiga, millele vajutades avaneb sisemine link ResultPage tabelile. Tabel avaneb selle valdkonna järgi filtreeritult, kus kasutaja linki vajutas.

_Näide: Kommunikatsiooni valdkonna sisulehelt viib link tabelisse, mis on filtreeritud kommunikatsiooni valdkonna järgi._

Lingi tekst: Vaata uuringu ettepanekute elluviimist
Lingi disain valdkonna vaates:
![image](https://user-images.githubusercontent.com/23524151/53168637-cb874900-35e3-11e9-908c-96f36afe075a.png)

Kui Tulemused sisutüübile lisatud tabelis puudub valdkonna kohta info, siis valdkonna vaates Tulemused blokki ei kuvata.

**2. Tabeli avamine sisutüübilt ResultPage**
Sisulehe lõpus kuvatakse linki Vaata ettepanekute elluviimist
Disain: https://zpl.io/VQEgxzm

Lingile vajutades avaneb tabel täismahus (filtreerimata).

**Tabeli disain:**  
Tabeli esmane vaade: https://zpl.io/aMP5nPz
Tabelis kommentaari lahter avatult: https://zpl.io/bzNWZzA
Tabelis kommnetaari lahti avanemisel navigeemrimist on kommentaaritud Zeplini failis.
Ettepaneku lahtris alates 5ndast reast, ilmub link Vaata rohkem

Tabeli pealkiri: Ettepanekute elluviimine
Tabeli kohal kuvada sisuhaldusest lisatud "Tabeli fail" - vt disainist; kui pole lisatud, siis ei kuva midagi.

Tabeli päises on filter/otsing, mille nõudeid ei muutu.

**Comment by RainLeoma** [comment]
Pakun välja lahenduse: 

Kui kasutaja satub tulemuste lehele otse, siis kuvatakse talle vali valdkond filtrit. Valdkonna valides kuvatakse tabelit ja muid filtreid. Kui see lahendus on liiga keeruline, siis võib-kuvada ühte (esimest) valdkonda, kuid filtris peab kohe olema arusaadaval kohal, et mis valdkonda kuvatakse. See hoiab ära vajaduse kuvada valdkonna tulpa.

**Comment by birgitpulk** [comment]
Järjekord paremal: 
<img width="210" alt="screenshot 2019-02-22 at 11 17 56" src="https://user-images.githubusercontent.com/24669779/53232333-91758000-3693-11e9-813b-9da083220f40.png">

**Comment by heldiraudsepp** [comment]
FE - 32h
Test - 8h
Disaini test - 3h

**Comment by RainLeoma** [comment]
Sobib!

**Comment by madispold** [comment]
Testimisse @tanelTromp, @birgitpulk

**Comment by TanelTromp** [comment]
TEST

Viga 1: CTA label ei ole elemendi keskele joondatud:
![pilt](https://user-images.githubusercontent.com/37407917/54918157-317a2f80-4f06-11e9-8a49-7343fe719f6f.png)

**Comment by birgitpulk** [comment]
Viga 7: "Laadi tabel alla (.xlsx)
UX-täiendus 1: Olen Taneliga nõus, et see CTA võiks olla samal kõrgusel
UX-täiendus 2: Tagasi üles nupp tuleb kunagi hiljem kõikidesse vaadetesse, see on kirjas Disaini tulevikuideed piletis (#519)
UX-täiendus 4: Nõus Taneliga, et terve riba võiks olla klikitav

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.
Viga 3: OK... vist?
Viga 4: Kommentaari avamisel lisatud nool kui jääb serva alla - OK.
Viga 5: OK.
Viga 6: OK.
Viga 7: OK.
Viga 8: Valdkond ei tea kas tema kohta on tulemuste all kirjeid... Mingi häkk lahenduse saaks teha valdkonna detailvaates kus kogu tabel pärida ja sealt kõik esindatud valdkonnad kokku koguda, aga ei ole eriti mõistlik. @birgitpulk @EgleM-TW Kuidas toimida?
UX-täiendus 1: OK.
UX-täiendus 2: OK.
UX-täiendus 3: OK.
UX-täiendus 4: OK.

**Comment by TanelTromp** [comment]
Viga 7 kodruv: NOK, ikka "Lae tabel alla(.xlsx) desktopis. Peab olema igal pool: "Laadi tabel alla (.xlsx)"
Viga 9 uus: edasi-tagasi liikudes läheb leht kakti  mingi hetk (korduvalt juba näinud): al 19sek
https://gyazo.com/c477cafad9896483833de832039a3ca7

**Comment by madispold** [comment]
Viga 7: OK.
Viga 9 uus: Seotud graafikutega, hetkel jätsin nõnda.
Viga 10 uus: OK.
Viga 11: OK.
Viga 12: OK.
UX-täiendus 5: OK.

**Comment by TanelTromp** [comment]
Viga 13: filtriga URL; ei filtreeri tulemusi (näitab kogu tabelit):
http://htm.twn.ee/oska-tulemused/ettepanekute-elluviimine?field=Majutus,%20toitlustus,%20turism

**Comment by birgitpulk** [comment]
Minu tähelepanekud/mõtted: 

1. Ettepanekute elluviimise tabel on üks alammenüü punkt, aga seda pole päris nii ette nähtud, kas see on taotluslik?
2. "Vaata rohkem" vajutades võiks sellest saada "Vaata vähem" nupp. Paneks sinna ka ikoonid +/- nagu on parempoolses tulbas, kui seal ridade arv väga suureks läheb
3. Kommentaari lahter võiks mobiilis olla sellise laiusega, et seda lahtrit ei pea kerima

**Comment by madispold** [comment]
Viga 13: OK.

@birgitpulk 
1. Arvan, et see on hetkel testimise eesmärgil nii.
2. Oleks tublisti tööd juures (kuni 4h) @heldiraudsepp kas läheb siinkohal tegemisse?
3. OK.

**Comment by TanelTromp** [comment]
Viga 1 WCAG: nii sorteerimisel, kui ka "Kommentaari"tulba avamisel / actioni käivitamisel peab ekraaniluger ütlema, et "state" muutus.

Viga 2 WCAG NVDA: kui tabeli päisest liikudes jõuda "Kommentaari" tulbale, siis ütleb: "column 6 button ava". Aga ei ütle. et see on "Kommentaarid". Ma arvan, et kui järgmise ringiga mööda rida tulla, siis võiks öelda: "plaaplaaa ja ava kommentaar button" vms

**Comment by madispold** [comment]
Viga 1 WCAG: OK.
Viga 2 WCAG: OK.

**Comment by TanelTromp** [comment]
Viga 13 uus: kui eemaldada sisuhaldusest exceli tulemuste fail, siis läheb sisu katki:
![pilt](https://user-images.githubusercontent.com/37407917/55214662-fc205b00-51ff-11e9-86d9-7ee324b710c3.png)
Siin saab näha:
http://htm.wiseman.ee:30000/node/48983/edit?destination=/admin/content%3Ftitle%3D%26type%3Doska_result_page%26status%3DAll%26langcode%3DAll

**Comment by madispold** [comment]
Viga 8: OK.
Viga 13: OK.

**Comment by TanelTromp** [comment]
Viga 14 uus mobiilivaade:vaikimis peab avatud olema tabeli vasak osa. Hetkel avab tabeli parema poole avatuna + nool liikumiseks vastakule. Peaks avama ikka vasaku poole esimesena ja noole paremale. hetkel nii:
![1](https://user-images.githubusercontent.com/37407917/55222097-b1a8d980-5213-11e9-81b8-632efe388ed7.jpg)

**Comment by madispold** [comment]
Viga 14: OK.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Valdkonna sisutüübi paremas veerus blokkide "Hõivatute arv" ja "Tasub teada" järel (kui eelnevaid pole sisestatud siis esimesena) kuvada blokki "Tulemused" koos lingiga, millele vajutades avaneb sisemine link ResultPage tabelile. Tabel avaneb selle valdkonna järgi filtreeritult, kus kasutaja linki vajutas.

- [ ] Kui Tulemused sisutüübile lisatud tabelis puudub valdkonna kohta info, siis valdkonna vaates Tulemused blokki ei kuvata. **Otsus Eglelt: Kui valdkonda ei ole tabelis, siis avada alati terve tabel, mitte veateade, et ei ole ja kuvada ikkagi link valdkonna juures.**

Tabeli avamine sisutüübilt ResultPage

- [x] Lingile vajutades avaneb tabel täismahus (filtreerimata).

------------------
Kuvatõmmised
![image](https://user-images.githubusercontent.com/37407917/55223872-d56e1e80-5217-11e9-880c-675818264151.png)

![1](https://user-images.githubusercontent.com/37407917/55223914-f33b8380-5217-11e9-8721-40ee574c1c42.jpg)

![image](https://user-images.githubusercontent.com/37407917/55223963-1403d900-5218-11e9-89d3-9d16ee178a1c.png)

![image](https://user-images.githubusercontent.com/37407917/55224003-2a119980-5218-11e9-9103-1b7be7a07784.png)
