### ISSUE TITLE
Muuta Tulemused sisulehele tabeli importi

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#685]
Sisutüübi „ResultPage“ sisus kuvatakse portaali külastajale tabelit, mille andmeid uuendab sisuhaldur CSV-st. Selle töö raames uuendada CSV importi (eelnev töö #473 )

Senine nõue:
    * failis on päiserida (valdkond;juurprobleem;ettepanek;peavastutaja;staatus;kommentaar)

Uus nõue:
* failis on päiserida (valdkond;ettepanek;peavastutaja;staatus;kommentaar)

* Salvestada failist loetavad andmed. Faili iga rida salvestada:
    * Valdkond
    * Ettepanek
    * Peavastutaja
    * Staatus
    * Kommentaar

Muid nõudeid ei muudeta.

CSV asukoht: sharepoint → abimaterjalid → OSKA → CSV-d

**Comment by heldiraudsepp** [comment]
BE - 2h
Test - 2h

**Comment by TanelTromp** [comment]
TEST OK

- [ ] failis on päiserida (valdkond;juurprobleem;ettepanek;peavastutaja;staatus;kommentaar) 

- [ ] Valdkond **On: OSKA Valdkond**
- [ ] Ettepanek
- [ ] Peavastutaja
- [ ] Staatus  **On: Ettepaneku Valdkond**
- [ ] Kommentaar **On Eksperdikogu kommentaar**

------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/53093210-7c77e000-351f-11e9-8f7d-1df6b1225fc7.png)

**Comment by EgleM-TW** [comment]
@lsoonvald Front-end peab kuvama andmeid nii nagu piletis:
* Valdkond
* Ettepanek
* Peavastutaja
* Staatus
* Kommentaar
Vajadusel muuta sisuhalduses.

**Comment by lsoonvald** [comment]
Muudetud päiste väärtuseid.
