### ISSUE TITLE
Uurida kuidas lahendada sisulehel sisutekst-infograafika vaheldumisi sisetamine-kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#686]
Drupal võimaluste ja töömahu hindamiseks:

Vajalik lahendada kliendi soovid:

1. Sisuteksti ja infograafika vaheldumisi sisetamine.

**Comment by Kyllike** [comment]
Samas kontekstis võiks mõelda ka sisulehe tabeli paremale kujundusele, praegune vaade: 
![image](https://user-images.githubusercontent.com/38042389/51115947-566d6a80-1812-11e9-8b59-845ba1924b4f.png)

Tabeli read / veerud võiksid olla eristatavad, midagi analoogset?
![image](https://user-images.githubusercontent.com/38042389/51115980-700eb200-1812-11e9-8a6a-a00d3d90b42b.png)

**Comment by heldiraudsepp** [comment]
Tehtud
