### ISSUE TITLE
Sündmused sisutüübi vead ja muutmissoovid

### ISSUE THREAD

**Issue by Kyllike** [hariduspilv/haridusportaal#689]
Soovitud muutused:
1) Sündmuse pea- ja lisakuupäevade alguse- ja lõpukellaaja sisestamine mittekohustuslikuks: peab saama sisestada sündmusi, millest on teada ainult toimumisaeg, ajakava täpsustamisel;
2) Sündmuse sissepääsu tüüp "registreerimisega" ei tohi olla seotud portaalisisese registreerimisvormiga: peab saama sisestada ka selliseid registreerimisega sündmusi, mille peakorraldajaks ei ole HTM ja allasutused ja kuhu registreerumine toimub mujal kui HTM+ allasutused.

**Comment by heldiraudsepp** [comment]
1. punkti tegemine 18h
2.punkti tegemine  10h

**Comment by heldiraudsepp** [comment]
Ainult testimine

**Comment by TanelTromp** [comment]
- [x] Sündmuse pea- ja lisakuupäevade alguse- ja lõpukellaaja sisestamine mittekohustuslikuks: peab saama sisestada sündmusi, millest on teada ainult toimumisaeg, ajakava täpsustamisel

**Kuna see muudatus on tehtud, siis kasutajaliidese nüüd vead**:

Viga 1. Kuigi sündmus toimub käesoleval päeval, siis näitab, et on möödunud (kellaaegasid ei ole määratud):
http://htm.wiseman.ee:30000/node/50833/edit?destination=/admin/content

Viga 2: kuvab ürituse lisakuupäeva kellaaja asemele NaN:

http://htm.twn.ee/s%C3%BCndmused/test-pilet689

![pilt](https://user-images.githubusercontent.com/37407917/52959173-43fcc880-339e-11e9-9050-31698f8cb9c2.png)


- [ ] Sündmuse sissepääsu tüüp "registreerimisega" ei tohi olla seotud portaalisisese registreerimisvormiga: peab saama sisestada ka selliseid registreerimisega sündmusi, mille peakorraldajaks ei ole HTM ja allasutused ja kuhu registreerumine toimub mujal kui HTM+ allasutused.

**Comment by EgleM-TW** [comment]
Sulgen selle pileti, analüüsi järgselt loodud uus pilet: #766
