### ISSUE TITLE
Uudised sisutüübi vead ja muutmissoovid

### ISSUE THREAD

**Issue by Kyllike** [hariduspilv/haridusportaal#690]
Muutmissoov 1: suurendada uudise avaldaja välja tähemärkide arvu 50ni (praegu ei mahu sinna ära Haridus- ja Teadusministeerium :)).

Muutmissoov 2: suurendada sissejuhatuse tähemärkide arvu 500ni.

**Comment by TanelTromp** [comment]
TEST 

- [ ] Muutmissoov 1: suurendada uudise avaldaja välja tähemärkide arvu 50ni (praegu ei mahu sinna ära Haridus- ja Teadusministeerium.

- [ ] Muutmissoov

 2: suurendada sissejuhatuse tähemärkide arvu 500ni.
