### ISSUE TITLE
MTSYS teenuste täiendused xDzeisonis

### ISSUE THREAD

**Issue by ruut12** [hariduspilv/haridusportaal#691]
BE:
Agents header parameetrisse lisada juurde MTSYS puhul ettevõtte reg kood ja kooli id.
Täiendada Lõime teenuste URL'id

FE:
/xjson_service endpointile POST data lisada MTSYS puhul: "educationalInstitutions_id" parameeter

**Comment by ruut12** [comment]
täiendavate parameetrite lisamiseks on võti: additional_parameters

**Comment by madispold** [comment]
Lisatud koolide korral MTSYS "educationalInstitutions_id".
