### ISSUE TITLE
Välisviidete kuvamise täiendus

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#692]
Välisviidete kuvamise ebaühtlus. All näide samast viitest samal sisulehel. Ühel juhul indikeerib ikoon, et tegemist välisviitega, teisel juhul mitte: http://edu.ee/artiklid/keskharidus.

![image](https://user-images.githubusercontent.com/37112899/51234606-e4159b00-1975-11e9-9b39-db204f27b7ae.png)

![image](https://user-images.githubusercontent.com/37112899/51234621-ef68c680-1975-11e9-9595-274ae69af75e.png)

Muutmisettepanek: kõik välisviited (sh lingid, mida saab lisada eraldi iga akordioni juurde) peaksid avanema vaikimisi uuel vahelehel.

Nõuded:

- Ikoon liigub paremale ja ainult välislingil. 
- Joon alt läheb maha

**Comment by madispold** [comment]
Tehtud.

TESTLOOD

Artikkel:
http://htm.twn.ee/artiklid/eksamid-ja-tasemet%C3%B6%C3%B6d
Uudis:
http://htm.twn.ee/uudised/haridus-ja-teadusminister-mailis-repsi-kooliaasta-alguse-tervitus
Oska ametiala:
http://htm.twn.ee/ametialad/ajakirjanik

TBC...

**Comment by madispold** [comment]
UX-täiendus 1: OK
UX-täiendus 2: Puhtalt sisuhaldusest tingitud. Kui kirjavahemärk on lingi sisse jäetud, siis nõnda ka kuvab. Lingi järele lisandub automaatselt ikoon, Front-end ei tea mis lingi sisu - OK.
UX-täiendus 3: OK.
Viga 1: @ruut12 Artikli päringus on vaid url "path" väli, tüüp puudu.
Viga 2: OK.
Viga 3: Sisestuse viga, peavad olema http või https protokolliga lingid, front ei tea sellest sisust midagi, ei ole kontrollitav. BE poolelt on vajadusel kontrollitav, kuid pigem peaks juhendis olema või lihtsalt sisuhaldur õigelt toimima.

**Comment by ruut12** [comment]
Viga1: uus queryId jagatud Madisele @madispold 
Viga3: See on default browseri käitumine kui lisatakse link mis ei hakka http või https'iga eeldatakse, et tegemist on sisemise lingiga. @TanelTromp

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
Viga 4: kuigi tegemist on ibound lingiga, indikeerib ikooniga, kui välist linki akordionis:

![pilt](https://user-images.githubusercontent.com/37407917/51685988-25521e80-1ff8-11e9-82e2-9ed0034b4714.png)

**Comment by madispold** [comment]
Viga 4: Täpsem rippmenüü all "Ava uues aknas" on linnuke, seetõttu ka käitub nii.![Screen Shot 2019-01-24 at 16.57.27.png](https://images.zenhubusercontent.com/5af419e14b5806bc2bd29b50/e03ef34a-505c-4b97-8ec5-a03373c0dad6)

**Comment by TanelTromp** [comment]
TEST

- [ ] Muutmisettepanek: kõik välisviited (sh lingid, mida saab lisada eraldi iga akordioni juurde) peaksid avanema vaikimisi uuel vahelehel.

Nõuded:

- [ ]     Ikoon liigub paremale ja ainult välislingil.
- [ ]     Joon alt läheb maha. **See käbi ainult välislingi kohta. Kui on siselink, siis joon on, sest vastasel juhul link ei paista üldse teksti sees silma (siemisel lingi ei ole ju seda "Ikooni")**
