### ISSUE TITLE
Muuta ametialade nimekirja vaadet

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#694]
Muuta ametialade (MainProfessionPage) nimekirja vaadet:
Disaini link: https://zpl.io/bLDo836 - NB! Nõuded on selles piletis, disain näitab paigutust eraldi ridadele.

1. Valdkonna kuvamine

Varasem nõue:
Nimekirjas kuvatakse ametialaga seotud valdkond (OSKA_Field title), kuvatakse kuni 3 valdkonna nimetust (taksonoomiast lisatud järjekorra alusel esimesed 3).

UUS nõue:
Nimekirjas kuvatakse ametiala (MainProfessionPage) sisutüübi paremasse veergu lisatud valdkond (FieldPage), kuvada kuni 2 juhuslikult valitud nimetust.

2. Näitajate kuvamine

Varasem nõue:
Kui on lisatud, siis kuvada näitaja(d) (indicator), esimesed 2.

UUS nõue:
Kuvada näitajad valdkonna nimetustest eraldi real. Kuvada 3 järgmist näitajat (kui all nimetatud näitajat pole lisatud, ei kuva puuduva näitja kohta midagi):
- Kuvada esimesena bloki "Konkurents tööturul" väärtus, mis teisendada järgmiselt (vt viimane veerg):

CSV   väärtus | Filling bar kuvatav väärtus | Nimekirjas kuvatav väärtus
-- | -- | --
1 | kerge | Kerge leida tööd
2 | üsna kerge | Üsna kerge leida tööd
3 | keskmine | Keskmised töö leidmise   võimalused
4 | üsna raske | Üsna raske leida tööd
5 | raske | Raske leida tööd

- Kuvada blokist "Faktid"
   - Hõivatute arv, id 1 (ikoonita)
   - Brutopalk, id 3 (euro märk kuvada numbri järel)

**Comment by RainLeoma** [comment]
Sobib!

Tabeli täisvaadet vaadates võiks kasutaja liikuda ametialade infograafika võrdluse lehele (mida pole, seda võiks arutada, et kas on vaja luua), kus tabel oleks avatud filtreerituna õigest kohast.

**Comment by EgleM-TW** [comment]
Ok, võtame töösse siis kui #625 on valmis.

**Comment by EgleM-TW** [comment]
Muutsime lahendust 04.02.2019 koosolekul.

**Comment by EgleM-TW** [comment]
FE: 4
TEST: 5

**Comment by madispold** [comment]
Testimisse @TanelTromp 
Euro märgi kuvamine pileti alusel ehk numbri järel hetkel, kujunduses teistmoodi.

**Comment by TanelTromp** [comment]
TEST

Testfail: 
[faktide_importPISIKENEcsv.xlsx](https://github.com/hariduspilv/haridusportaal/files/2883579/faktide_importPISIKENEcsv.xlsx)

Viga 1: Vorming vahe puudu töötasu arvul (vs Zeplin ehk 2 500; 25 000; 100 000):

![pilt](https://user-images.githubusercontent.com/37407917/53075672-6b66a900-34f6-11e9-9183-03acdf240a32.png)

Viga 2: kui ei järgne fakti, siis halli kriipsu ei kuva:

![pilt](https://user-images.githubusercontent.com/37407917/53075882-eb8d0e80-34f6-11e9-96d7-517e26ccd551.png)

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.
Viga 3: OK.
Viga 4: OK listivaates.
Viga 5 WCAG, VIGA 6 WCAG: Seotud inline elementidega, loetakse ühes jorus paratamatult, just NVDA korral - OK.
Viga 7 VO: OK.

**Comment by TanelTromp** [comment]
Viga 4: kaob küll nüüd tekst ise aga joondab valesti + hall joon, mis peaks kaudma:

![pilt](https://user-images.githubusercontent.com/37407917/53093898-594e3000-3521-11e9-9c53-a590064e29ca.png)

**Comment by madispold** [comment]
Viga 1 jätk: Kuna detailvaate kujunduses on mõlemal sama formaat, siis jätsin hetkel nii nagu on, vajab kinnitust, vajadusel muutmine küll vaid minuti töö. @birgitpulk 
Viga 4 jätk: OK.

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Nimekirjas kuvatakse ametiala (MainProfessionPage) sisutüübi paremasse veergu lisatud valdkond (FieldPage), kuvada kuni 2 juhuslikult valitud nimetust.

- [ ] Kuvada näitajad valdkonna nimetustest eraldi real. Kuvada 3 järgmist näitajat (kui all nimetatud näitajat pole lisatud, ei kuva puuduva näitja kohta midagi).

--------------

Kuvatõmmis

![pilt](https://user-images.githubusercontent.com/37407917/53149462-68cb8880-35b6-11e9-863c-50c2d75c5a92.png)

**Comment by birgitpulk** [comment]
Kujunduse osas ok
