### ISSUE TITLE
Ametiala sisutüübil Faktide kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#695]
**Eesmärk:**
Sisutüübi OSKA ametiala „MainProfessionPage“ paremas veerus kuvatakse portaali külastajale fakte (näitajaid), mille andmeid uuendab sisuhaldur CSV-st. Iga ametiala kohta imporditakse kuni 4 näitajat, mille kuvamisel lisatakse ikoon näitaja id ja ikooni id alusel.
Kui mõni näitaja puudub, siis selle kohta midagi ei kuvata ja tühja auku ei jää.

Näitajad on:
* Hõivatute arv
* Hõive muutus
* Brutopalk
* Hariduse pakkumine

_CSV-st ikooniga sobivate näitajate ja nende väärtuste sisulist kontrolli portaalis ei toimu, sobivate andmete lisamine saab olema kirjeldatud kasutusjuhendis #752 ._

**Disaini link:** paigutus lehel: https://zpl.io/V41Wg1M ja variandid: https://zpl.io/VYGdz6n 
NB! Disainis kuvatavad tekstid pole õiged (vt all piletis).

Ülevaade andmetest:

id | näitaja | ikooni id
-- | -- | --
1 | Hõivatute arv | vahemikus 1 kuni 11
2 | Hõive muutus | vahemikus 1 kuni 5
3 | Brutopalk |  vahemikus 1 kuni 20
4 | Töökohtade ja lõpetajate arvu võrdlus |  vahemikus 1 kuni 5

**Vastuvõtutingimused**

Ikooni (ja teksti) kuvamise reeglid:
1. Hõivatute arv, id 1

ikooni id | värvitud ikoone
-- | --
1 | 1
2 | 2
3 | 3
4 | 4
5 | 5
6 | 6
7 | 7
8 | 8
9 | 9
10 | 10
11 | 11

2. Hõive muutus

ikooni id | Ikoonil noole värv ja suund | Kuvatav tekst
-- | -- | --
1 | Rohekas nool otse üles | Suur   kasv
2 | Rohekas nool paremale viltu üles | Väike kasv
3 | Oranž nool horisontaalselt   paremale | Jääb samaks
4 | Punakas nool viltu alla | Väike   kahanemine
5 | Punakas nool otse alla | Suur   kahanemine

3. Töötasu 
Esimesena värvida alumine münt.

ikooni id | värvitud ikoone ühe mündi kaupa
-- | --
1 | 1
2 | 2
3 | 3
4 | 4
5 | 5
6 | 6
7 | 7
8 | 8
9 | 9
10 | 10
11 | 11
12 | 12
13 | 13
14 | 14
15 | 15
16 | 16
17 | 17
18 | 18
19 | 19
20 | 20

4. Töökohtade ja lõpetajate arvu võrdlus

ikooni id | Ikoonil hallil taustal kuvatav värv | Kuvatav tekst
-- | -- | --
1 | Punakas | Eriala lõpetajaid rohkem kui   tulevikus töökohti
2 | Punakas | Eriala lõpetajaid vähem kui   tulevikus töökohti
3 | Rohekas | Eriala lõpetajaid piisavalt   tuleviku töökohtade täitmiseks
4 | Kollakas | Lõpetajad ei lähe erialasele   tööle
5 | Hall | Eestis kutse- või kõrgkoolides   eriala õppida ei saa

**Comment by RainLeoma** [comment]
Paarisarvuliste müntide puhul alati värviga näidata esimesena alumist münti.

Muidu sobib!

**Comment by EgleM-TW** [comment]
FE: 24
test: 8

**Comment by TanelTromp** [comment]
Viga 1: kui määrata sisuhalduses "Filling bar" väärtuseks suurem, kui lubatud (1-5), siis vaade katki. Võiks panna tingimuse, et 5+ none kuva ja väiksem kui 1 sama teema
https://gyazo.com/df455343d034840c3589ca06e48bf5b0

**Comment by madispold** [comment]
Viga 1 jm OK.
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1: refreshimisel kuvab enne ikoone mingit läbu (chrome):
https://gyazo.com/a0a3899b3b5c333d6467479a1f102749

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.
Viga 3 WCAG: OK.
Viga 4 WCAG: OK.
Viga 5 WCAG: OK.

**Comment by TanelTromp** [comment]
Viga 2: "in progress" - Birgitiga fixida
Viga 6 WCAG: "Brutopalk" peaks ütlema ka peale numbri ühikus ehk "€"

**Comment by madispold** [comment]
Viga 2: OK - Tahvel kuni mobiili vahemik lisatud 2 murdepunkti kus ikoone suurendatud.
Viga 6 WCAG: OK.

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Kui mõni näitaja puudub, siis selle kohta midagi ei kuvata ja tühja auku ei jää

- [ ] Näitajad on:

    * Hõivatute arv
    * Hõive muutus
    * Brutopalk
    * Hariduse pakkumine

-----------------

Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/53428512-9b7ce300-39f3-11e9-8888-76f902e38ab7.png)

![pilt](https://user-images.githubusercontent.com/37407917/53429018-7a68c200-39f4-11e9-934f-2f57e7907fbe.png)

**Comment by birgitpulk** [comment]
Kujundus ok
