### ISSUE TITLE
Tabelite sisestamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#696]
Küllikeselt tulnud soov: Mõelda ka sisulehe tabeli paremale kujundusele, praegune vaade: 
![image](https://user-images.githubusercontent.com/37112899/51234957-ee846480-1976-11e9-9ba5-dac449b42373.png)

Tabeli read / veerud võiksid olla eristatavad, midagi analoogset?
![image](https://user-images.githubusercontent.com/37112899/51235005-0eb42380-1977-11e9-8f2f-10560730617c.png)

**Comment by TanelTromp** [comment]
TEST

Hetkel siis võimalik teha lihtsalt selliseid tabeleid, pnain siia kaks versiooni - klassikalist:

http://htm.twn.ee/artiklid/artikkel-mugudest
