### ISSUE TITLE
Ametiala sisulehe paremas veerus filling bar kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#698]
Sõltub disainist #697  - Täiendus teksti sõnastuses #754 

Eesmärk:

Ametiala sisutüübi „MainProfessionPage“ paremas veerus kuvatakse blokki "Konkurents tööturul", mille andmeid uuendab sisuhaldur CSV-st. Selle töö raames realiseerida imporditud andmete kuvamine _filling bar_'na.

Vastuvõtutingimused:
**bloki pealkiri**: _Konkurents tööturul_
**pealkirja all kuvatav tekst**: _Kui raske on leida sellel ametialal tööd järgmise 5–10 aasta vältel?_ 
**filling bar väärtuste kuvamine**:
1 = kerge
2 = üsna kerge
3 = keskmine
4 = üsna raske
5 = raske
Kuvamise nõuded siin: https://zpl.io/aBykAwm

Disaini näide siin: https://zpl.io/V41Wg1M

Viited: Väärtused impordib sisuhaldur CSV-st #699

**Comment by madispold** [comment]
Testimisse, andmed olemas hetkel näiteks "Ajakirjanik" ametiala all.
@TanelTromp @birgitpulk

**Comment by TanelTromp** [comment]
Testlood:
http://htm.twn.ee/ametialad/ajakirjanik
http://htm.twn.ee/ametialad/r%C3%A4tsepad
http://htm.twn.ee/ametialad/keemik-%C3%B5hkaja-pikem-nimetus-eks-eks-eks-eks-eks-ek
http://htm.twn.ee/ametialad/beeta-ametiala-pikk-50-t%C3%A4hem%C3%A4rki-eksju
http://htm.twn.ee/ametialad/operaatorid


Viga 1: ei kuva "Kunkurent tööturul" kasti, kui mitte ühtegi parema veeru elementi ei ole varem sisuhaldusest sisestatud. Peaks kuvama.
http://htm.twn.ee/ametialad/beeta-ametiala-pikk-50-t%C3%A4hem%C3%A4rki-eksju

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2 WCAG: OK.

**Comment by birgitpulk** [comment]
Kujunduse osas korras

**Comment by TanelTromp** [comment]
TEST OK

Vastuvõtutingimused:

- [ ] **bloki pealkiri**: _Konkurents tööturul_
- [ ] **pealkirja all kuvatav tekst**: _Kui raske on leida sellel ametialal tööd järgmise 5–10 aasta vältel?_
- [ ] **filling bar väärtuste kuvamine**:

1 = kerge
2 = üsna kerge
3 = keskmine
4 = üsna raske
5 = raske

----------------------------

Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/52415936-1a67b580-2af1-11e9-86c4-47887252f943.png)

![pilt](https://user-images.githubusercontent.com/37407917/52415986-35d2c080-2af1-11e9-8e09-4a0178e649d2.png)
