### ISSUE TITLE
Ametiala sisulehe paremasse veergu filling bar lisamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#699]
FE #698  ja disain #697 

**Eesmärk:**
Ametiala sisutüübi „MainProfessionPage“ paremas veerus kuvatakse blokki "Konkurents tööturul", mille andmeid uuendab sisuhaldur CSV-st. Selle töö raames lahendada CSV-st andmete import ja andmete sidumine ametiala taksonoomiaga. Töö tulemusel saab alustada FE tööga #698 

1. Sisuhaldaja avab faili.
Fail on CSV fail, kus:
- veergude eraldaja on semikoolon ( ; ), 
- failis on päiserida (ametiala;vaartus) 

2. Faili kontroll:

Faili iga rida kontrollida järgmiselt:
- kui reas on täidetud üks veerg, siis on ka teine veerg kohustuslik.
- kas esimeses veerus on ametiala, tekst (võib koosneda mitmest sõnast)
- kas teises veerus on väärtus, number vahemikus 1-5 (1 ja 5 sealhulgas).

Kui ilmneb viga, siis protsess katkestada ja kuvada faili rea number ja veateade ("Puudub ametiala", "Puudub vaartus"). Veateated võivad olla inglise keeles, kuna kõiki teateid ei võimalda süsteem tõlkida.

3. Salvestada failist loetavad ametiala konkurentsi näitajad. Faili iga rida salvestada:
- rea nr
- ametiala 
- väärtus 

Näidisandmed MS Excelis SharePointi kaustas "Abimaterjalid" - "Oska" - OSKA_fillingbar.xlsx
Testida seda tööd koos FE tööga #698 ; iseseisev testimine pole otstarbekas.

**Comment by TanelTromp** [comment]
Viga 1 / täiendus: kui CSV laadimine ei õnnestu, võiks vanu sees olevaid andmeid eelmisest õnnestunud CSV laadimisest, mitte kustutada. Hetkel kustutab kõik andmed enaõnnestunud CSV laadimisega

**Comment by EgleM-TW** [comment]
Täiendus nr 2 läheb uude piletisse võimaliku lisatööna  - sh muude csv-de puhul ühine lahendus

**Comment by EgleM-TW** [comment]
Viga 1 / täiendus: läheb uude piletisse võimaliku lisatööna - sh muude csv-de puhul ühine lahendus
