### ISSUE TITLE
OSKA sisutüüpidele saab lisada interaktiivset infograafikat (perioodi-põhised)

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#709]
**Eesmärk**
OSKA sisutüüpidel — valdkond, ametiala, tööjõuprognoos ja tulemused — kuvatakse interaktiivset infograafikat. Sisutoimetaja lisab sisulehele infograafika, selleks ta:
1.	määrab kõik valikud, mida portaali külastaja saab graafikule valida (st, milliste valikutega saab muuta vaikimisi vaadet)
2.	määrab graafiku vaikimisi väärtused (see graafik, mida kasutajale lehel esmalt kuvatakse).

**Perioodi-põhised graafikud**

1.	graafiku pealkiri (kuni 100 tähemärki)
2.	x-teljel kuvatavad perioodi valikud (csv-st valikud)
3.	graafikule kuvatavad näitajad (csv-st valikud)
4.	UI-s valitavad filtrid (valikus: valdkond, alavaldkond, ametiala, silt), saab määrata mitu
5.	ühe (simple) graafiku tüüp (valikus: line, bar, column)
6.	mitme (multi) graafiku tüüp (valik sõltub eelnevast)
        - kui on line, siis valikut pole vaja teha, automaatselt multi-line
        - kui on bar, siis valikus on clustered bar, stacked bar 
        - kui on column, siis valikus on clustered column, stacked column 
7.	combo graafiku näitaja (valik csv-st) – kui on määramata, ei kuvata, alati on line tüüpi. Saab määrata ainult column, clustered column, stacked column valikule.
8.	combo graafiku y telje ühik (valikus: summa, %, euro) 

9.	min väärtus (vaikimisi 0, on muudetav vaikimisi võetavaks andmetest ja saab sisestada käsitsi). (max tuleb andmetest); 
10.  kui on combo lisatud, siis saab min väärtuse mõlemale y teljele määrata.

***
vaikimisi default vaade kirjeldatud FE-s

***

11. Lisaks eelnevalt kirjeldatule saab sisestada sisulise kirjelduse tekstiväljale, mida kuvatakse sisulehel enne graafikut.

_Infograafikatest näited on SharePointi OSKA kaustas._

**Testimiseks näide (csv või selle aluseks olev MS Exceli fail on Sharepointis):**
1.	Pealkiri: Haridusnäitajad
2.	X-telg periood: 2015; 2016; 2017; 2018 
3.	Näitajad:
•	Sisseastumised
•	Lõpetamised
4.	Filtrid:
•	Valdkond: rõiva- tekstiili ja nahatööstus
•	Alavaldkond: rõivatööstus; nahatööstus
•	Ametiala: disainerid; rätsepad
•	Silt: Bakalaureus, Magister, Doktor
5.	Ühe valikuga graafik: column
6.	Mitme valikuga graafik: stacked column
7.	Combo graafiku näitaja: (line tüüp)
•	Katkestamise määr
8.	Combo Y telje ühik: %

9.	Y min = 10; combo Y = 0

FE töö #710  
Seotud BE töö #711

**Comment by RainLeoma** [comment]
Kas punkt 4. UI-st valitavad filtrid teevad ,seda et ma saan määrata, mis valdkonna andmeid kuvatakse? Näiteks piiritleda ära, et kuvatakse kasutajale ainult ühe valdkonna andmeid valitud tingimuste järgi?

Kas punktis 9. nimetatud filtreid kuvatakse ainult siis, kui ma olen teinud need kasutajale kättesaadavaks? Näiteks kui on majandusstatistika tabel, siis pole ametialade filtriga midagi teha.

Punkt 10. Min värtus teljel on 0, mis on muudetav defaultiks või mõneks muuks numbriks. Max väärtus tuleb andmetest. **NB!** Combo chartidel kus on 2 Y-telge on võimalik valida "Ühtlusta telgede väärtused", mis muudab mõlema Y-telje väärtused sama suureks. Miinimumi puhul madalaimaks miinimukiks ja maksimumi puhul suurimaks maksimumiks.

Ma pole IT arendustega niipalju kokku puutundu, et mõista unepealt, et kuidas see hakkav päriselus väljanägema, aga mulle tundub, et see on see mida me soovime! Aitäh Egle :)

**Comment by EgleM-TW** [comment]
Ok,
nr 4 - Jah nii on mõeldud.
nr 9 - Jah, nii on mõeldud, näis, mida google lubab.
nr 10 - täiendatud.

**Comment by EgleM-TW** [comment]
Vaikimisi vaade lisatud FE piletisse.
