### ISSUE TITLE
Sisuhalduse kasutajarollid ja õigused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#71]
Epic - Õiguste haldamine - #23 

Sisuhalduse kasutamiseks on õiguste kirjeldus siin: https://github.com/hariduspilv/haridusportaal/wiki/Kasutus%C3%B5igused

Kirjeldav töö: #97

**Comment by EgleM-TW** [comment]
Küllike palun vaata üle ja tõsta done.
Infoks, et rolle saab sisuhalduses ise juurde luua.
