### ISSUE TITLE
Perioodi-põhiste graafikute kuvamine 

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#710]
Eesmärk 
OSKA sisutüüpidel — valdkond, ametiala, tööjõuprognoos ja tulemused — kuvatakse interaktiivset infograafikat. Kasutaja saab muuta vaikimisi graafiku vaadet.

Vastuvõtutingimused ja selgitused vastavalt BE tööle ja näitele #709 :
1.	Pealkiri: kuvatakse nii nagu sisestati
2.	Periood: kuvada alati väiksemast suuremaks
3.	Näitajad: kuvatakse vaikimisi valitud näitajat (default vaade on sisuhalduses esimenena valitud näitaja), juhul kui on lisatud mitu näitajat saab kasutaja näitajaid lisada/ eemaldada.
4.	Filtrid: vaikimisi kuvatakse kõiki lisatud valdkondi, mitme valdkonna korral saab kasutaja eemaldada / tagasi lisada.
Selgitus! Korraga saab valida kas mitu näitajat ja igas filtris ühe väärtuse; või üks näitaja ja ainult ühest filtrist mitu väärtust. Näiteks 2 näitajat "Sisseastumised" ja "Lõpetamised" ning 1 alavaldkond; või 1 näitaja "Sisseastumised" ja 2 alavaldkonda.
5.	– 
6.	–
7.	Line tüüp kuvatakse nö pehme joonena.
8.	Ühiku kuvamise võimalus: selgitada google võimalusi – kas väärtuse järel või ühe väljana
9.	Y väärtused kuvatakse alates määratud min väärtusest.
10.  Kui on lisatud, kuvatakse combo graafikut.

**Comment by RainLeoma** [comment]
Sobib

**Comment by EgleM-TW** [comment]
Täpsustatud default vaate kuvamine vastavalt planeerimisele 04.02.

**Comment by EgleM-TW** [comment]
Lisasin: Perioodil on alati mitme valik (multiselect).

**Comment by EgleM-TW** [comment]
@lsoonvald #709 jäi puudu:
* combo graafiku y telje ühik (valikus: summa, %, euro)
* min väärtus (vaikimisi 0, on muudetav vaikimisi võetavaks andmetest ja saab sisestada käsitsi) (max tuleb andmetest);

**Comment by lsoonvald** [comment]
Parandatud @EgleM-TW

**Comment by heldiraudsepp** [comment]
23ndas sprindis 41h
