### ISSUE TITLE
OSKA sisutüüpidele saab lisada interaktiivset infograafikat (Stacked 100% tüüpi)

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#711]
**Eesmärk**
OSKA sisutüüpidel — valdkond, ametiala, tööjõuprognoos ja tulemused — kuvatakse interaktiivset infograafikat. Sisutoimetaja lisab sisulehele infograafika, selleks ta:
1.	määrab kõik valikud, mida portaali külastaja saab graafikule valida (st, milliste valikutega saab muuta vaikimisi vaadet)
2.	määrab graafiku vaikimisi väärtused (see graafik, mida kasutajale lehel esmalt kuvatakse).

**Stacked 100% tüüpi graafikud**

0.     graafiku tüüp: stacked bar 100% või stacked column 100%
1.	graafiku pealkiri (kuni 100 tähemärki)
2.	graafikule kuvatavad näitajad (csv-st valikud)
3.	periood (csv-st valikud, filtreerimiseks selle alusel)
4.	x-telje filtrid (csv-st sildi valikud – võimalusel kitsendatult eelnevalt valitud näitaja andmetest)
5.	UI-s valitavad filtrid (valikus: valdkond, alavaldkond, ametiala, periood), saab valida mitu erinevat.

***
Vaikimisi vaade FE-s on sisuhalduses esimenena valitud näitaja ja kõik valitud valdkonnad.

***

7. Lisaks eelnevalt kirjeldatule saab sisestada sisulise kirjelduse tekstiväljale, mida kuvatakse sisulehel enne graafikut.

FE #712 
Perioodi-põhine tüüp #709 

_Infograafikatest näited on SharePointi OSKA kaustas._
**Testimiseks näide:**

0.     Tüüp: stacked bar 100%
1.	Pealkiri: Haridusnäitajad
2.	Näitajad: Omandatud haridus; Sugu
3.	Periood: 2015, 2016; 2017; 2018
4.	X-telje filtrid (sildid): Bakalaureus ja Magister, Doktor, mehed, naised – NB! kuvatakse välja näitaja järgi
5.	Filtrid:
•	Valdkond: rõiva- tekstiili ja nahatööstus
•	Alavaldkond: -
•	Ametiala: disainerid, insenerid, konstruktorid, operaatorid
•	Periood: 2014, 2015, 2016, 2017, 2018 – korraga saab kasutaja vaadata ühe aasta andmeid

**Comment by RainLeoma** [comment]
NB! Ma ei tea kas Goole chartsil on sama probleem, mis on excelil, aga excel kipub teinekord X-telje tegema pikemaks kui on 100%. 100% stacked graafikutel peab jälgima, et X telje pikkus on 100%. 

Sobib
