### ISSUE TITLE
Stacked 100% interaktiivsete graafikute kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#712]
Eesmärk 
OSKA sisutüüpidel — valdkond, ametiala, tööjõuprognoos ja tulemused — kuvatakse interaktiivset infograafikat — stacked bar 100% või stacked column 100%. Kasutaja saab muuta vaikimisi graafiku vaadet.

Vastuvõtutingimused vastavalt BE tööle ja näitele #711 :

* graafiku tüüp: stacked bar 100% või stacked column 100%,
vt näidet https://i.gyazo.com/a4147b96cc32361892a2e01ffabab8b3.png
* graafiku pealkiri: kuvatakse nii nagu sisestati
* näitajad: kuvatakse vaikimisi valitud näitajat (default vaade on sisuhalduses esimenena valitud näitaja); juhul kui on lisatud mitu näitajat saab kasutaja näitajaid lisada/ eemaldada.
* filtrid: vaikimisi kuvatakse kõiki lisatud valdkondi, mitme valdkonna korral saab kasutaja eemaldada / tagasi lisada.

**Comment by RainLeoma** [comment]
Sobib
