### ISSUE TITLE
Siltideta uudiskirja tellimine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#713]
Kujundame uudiskirja tellimise bloki selliselt, et vaikimisi on teemade (max 24) kuvamine peidus.
Selle käigus lahendada ka olukord, kus kasutajale tekib võimalus valida kõik teemad korraga - vt all ettepanekut.
Kõik = kõik nüüd ja tulevikus lisanduvad teemad. 
Uudiskirja blokk on avalehel muust aktuaalsest sisust allpool.
***
Kui ühtegi silti pole valitud siis saab täna juba tellida XML uudisvoogu.

- [ ] Kui ühtegi silti pole valitud, siis lubada tellida ka uudiseid emailile.
- [ ] Sellise (vaikimisi) olekus kuvada nupul tõlget "Telli **kõik** teemad e-postile"

**Comment by birgitpulk** [comment]
@erkkijakobson 
Uudiskirja blokk on avalehel muust aktuaalsest sisust allpool. > Mis sa sellega silmas pead? Kus ta asetsema peaks?

Kui peidame kõik teemad nupu alla, siis see sektsioon läheb väga pisikeseks ja ei pruugi muu sisu vahelt välja paista, eriti kui ta täiesti lõppu paneme

"Telli kõik teemad e-postile" > Kas algselt on siis nupu tekst midagi muud? Ma ei tahaks väga nupu teksti muuta, see ei ole kasutatavuse osas parim praktika. Pigem võiks olla linnukeste juures valik, et "Vali kõik", aga nupp võiks alati samaks jääda
