### ISSUE TITLE
Piirata unikaalsete siltide koguarv süsteemis 24-ni

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#714]
Uudiskirja tellimisel valitavad sildid
- Sisu alt uut silti lisada ei saa. Saab ainult valida.
- Taksonoomiate alt peakasutaja lisab silte. Maksimaalselt 24
- Kuvatakse tähestiku järjekorras 
**Täpsustus:**

Selleks, et uudiskirja tellimisel oleks valitavate siltide arvuks 24, tuleb piirata järgmiste taksonoomiate lisamist süsteemi:
  - Uudise silt (tag)
  - Sündmuse silt (tag)
  - Sündmuse tüüp (EventType)

Kokku saab luua 24.

**Comment by lsoonvald** [comment]
Viga 1: Tegin backi poole pealt päringu ümber, @madispold peab enda poolt täiendama.

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
Viga 2: silldi maksimaalne pikkus võib olla 50 tähemärki:

![pilt](https://user-images.githubusercontent.com/37407917/53226498-d691b600-3683-11e9-91df-44dc2b42b424.png)

**Comment by lsoonvald** [comment]
Viga 2: Can't reproduce, sain kirjutada sinna teksti: "Sildi pikkus Haridusministeeriummmmmm 51 tähemärki" mille pikkus on 50 tähemärki. Täpsustust palun vea esinemisel.

**Comment by TanelTromp** [comment]
Viga 3: eesti terminite all (http://htm.wiseman.ee:30000/admin/structure/taxonomy/manage/tags/overview) saab sisestada silte 19, mitte 20 (e.k on lisaks 4 ürituse tüüpi ehk hetkel 19+4=23) (veateade: You can only have 24 tags per language).

**Comment by lsoonvald** [comment]
Viga 3: Korras nüüd, mingi vana nähtamatu fantoomtag oli kuhugi õhku rippuma jäänud, kustutasin ära selle.

**Comment by TanelTromp** [comment]
TEST OK

Uudiskirja tellimisel valitavad sildid

- [x] Sisu alt uut silti lisada ei saa. Saab ainult valida.
- [ ] Taksonoomiate alt peakasutaja lisab silte. Maksimaalselt 24
- [ ] Kuvatakse tähestiku järjekorras

      **Täpsustus:**


- [ ] Selleks, et uudiskirja tellimisel oleks valitavate siltide arvuks 24, tuleb piirata järgmiste taksonoomiate lisamist süsteemi:

    * Uudise silt (tag)

    * Sündmuse silt (tag)

    * Sündmuse tüüp (EventType)

- [ ] Kokku saab luua 24.

**Comment by TanelTromp** [comment]
Viga 1: tühjad sisud URL-lt: http://htm.wiseman.ee:30000/xjson-csv-list
