### ISSUE TITLE
Sisuhalduse täiendused

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#715]
Selles piletis on koondatud nö pisitäiendused sisuhalduses.

1. Muuta sisuhalduses lisatava foto maksimaalset mahtu senise 2MB asemel 5MB. 
Muudatus teha järgmistel sisutüüpidel:
* Artikkel (ArticlePage)
* Uudis (News)
* Sündmus (Event)
* OSKA valdkond (FieldPage)
* OSKA ametiala (MainProfessionPage)
* OSKA tööjõuprognoos (SurveyPage)
* OSKA tulemused (ResultPage)
Miinimumi nõuded 1208x680 pikslit ei muutu.

**Comment by TanelTromp** [comment]
TEST OK


- [ ] Muuta sisuhalduses lisatava foto maksimaalset mahtu senise 2MB asemel 5MB.
- [ ] Miinimumi nõuded 1208x680 pikslit ei muutu.


    Artikkel (ArticlePage)
    Uudis (News)
    Sündmus (Event)
    OSKA valdkond (FieldPage)
    OSKA ametiala (MainProfessionPage)
    OSKA tööjõuprognoos (SurveyPage)
    OSKA tulemused (ResultPage)

**Comment by lsoonvald** [comment]
Täiendus 1: Tegelt isegi tekib teavitus selle suuruse kohta, aga see tekib sinna üles mulli sisse, sama ka vale pildi suuruse puhul.
