### ISSUE TITLE
JUHAN koolitused - koolituste andmete import

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#719]
JUHAN-st andmete koolituste andmete lugemine ja Haridusportaali salvestamine. Perioodiliselt kord ööpäevas käivitatav protsess. JUHAN teenusest loetakse kõik koolituste andmed. Andmeid töödeldakse järgmiselt:
- [ ] kui JUHAN-st saadi uus koolituse objekt (Haridusportaalis ei ole sündmust, mille väline identifikaator externalID võrdub JUHAN-st saadud id-ga), siis Haridusportaali lisatakse uus sündmus (on Haridusportaalis avaldatud)
- [ ] kui JUHAN-st saadi muudetud koolituse objekt (Haridusportaalis on sündmus, mille väline identifikaator externalID võrdub JUHAN-st saadud id-ga), siis Haridusportaalis muudetakse sündmus (on Haridusportaalis avaldatud)
- [ ] kui JUHAN-st ei saadud Haridusportaalis olevat sündmuse (Haridusportaalis on sündmus, mille väline identifikaator externalID ei sisaldu JUHAN-st saadud koolituste id hulgas), siis Haridusportaalis muudetakse sündmus mitte avaldatavaks.

JUHAN teenuse dokumentatsioon: https://testkoolitus.hitsa.ee/api/doc#get--api-public-trainings

FE issued #720, #721, #722

Haridusportaali ja JUHAN andmete vastavus
- id = omistab Haridusportaal, ei saada JUHAN-st
- Väline identifikaator - extrnalID = id
- Nimetus - name = trainingName
- Lühikirjeldus - description.summary = lead
- Sündmuse tüüp - type = "Koolitus"
- Kirjeldus - description.value = courseDescription.fullDescription
- Sündmusega seotud lingid - webPageLink, nimetus = "Täpsem info täienduskoolituste infosüsteemis" URL = publicURL
- Registreerumise URL (registrationURL)  = publicURL
- Toimumise koha nimetus - location.name  = venueName
- Toimumise koha aadress - location.address = venueFullAddress
- Korraldaja - organizer = institution.name
- Kontaktisik - contactPerson = projectManager.projectManagerFullName
- Kontakttelefon - contactPhone = projectManager.phone
- Kontakt e-posti aadress - contactEmail = = projectManager.email
- Sissepääsu liik (registreerimise liik) - entryType = "JUHAN" 
- Osalejatele praktiline info - practicalInformation = venueInfo
- Toimumise algusaeg = startingDate
- Toimumise lõpuaeg = endingDate

**Comment by TanelTromp** [comment]
TEST

- [ ] kui JUHAN-st saadi uus koolituse objekt (Haridusportaalis ei ole sündmust, mille väline identifikaator externalID võrdub JUHAN-st saadud id-ga), siis Haridusportaali lisatakse uus sündmus (on Haridusportaalis avaldatud)
- [ ] kui JUHAN-st saadi muudetud koolituse objekt (Haridusportaalis on sündmus, mille väline identifikaator externalID võrdub JUHAN-st saadud id-ga), siis Haridusportaalis muudetakse sündmus (on Haridusportaalis avaldatud)
- [ ] kui JUHAN-st ei saadud Haridusportaalis olevat sündmuse (Haridusportaalis on sündmus, mille väline identifikaator externalID ei sisaldu JUHAN-st saadud koolituste id hulgas), siis Haridusportaalis muudetakse sündmus mitte avaldatavaks.

Haridusportaali ja JUHAN andmete vastavus

- [ ] - id = omistab Haridusportaal, ei saada JUHAN-st
- [ ] - Väline identifikaator - extrnalID = id
- [ ] - Nimetus - name = trainingName
- [ ] - Lühikirjeldus - description.summary = lead
- [ ] - Sündmuse tüüp - type = "Koolitus"
- [ ] - Kirjeldus - description.value = courseDescription.fullDescription
- [ ] - Sündmusega seotud lingid - webPageLink, nimetus = "Täpsem info täienduskoolituste infosüsteemis" URL = publicURL
- [ ] - Registreerumise URL (registrationURL)  = publicURL
- [ ] - Toimumise koha nimetus - location.name  = venueName
- [ ] - Toimumise koha aadress - location.address = venueFullAddress
- [ ] - Toimumise koha asukoht kaardil - location.map
- [ ] - Korraldaja - organizer = institution.name
- [ ] - Kontaktisik - contactPerson = projectManager.projectManagerFullName
- [ ] - Kontakttelefon - contactPhone = projectManager.phone
- [ ] - Kontakt e-posti aadress - contactEmail = = projectManager.email
- [ ] - Sissepääsu liik (registreerimise liik) - entryType = "JUHAN" 
- [ ] - Osalejatele praktiline info - practicalInformation = venueInfo
- [ ] - Toimumise algusaeg = startingDate
- [ ] - Toimumise lõpuaeg = endingDate
