### ISSUE TITLE
JUHAN koolitused - nimistu vaate muudatused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#720]
- [ ] Kui sündmusel ei ole alguse kellaaega, siis kuvada kellaaja väärtuse asemel - . ("Algusaeg: -")

**Comment by TanelTromp** [comment]
TEST

Dekstop:
![pilt](https://user-images.githubusercontent.com/37407917/52045659-ab68ea80-254d-11e9-9e1c-e1664dfd59ee.png)

Mobiil:

Tahvel:
