### ISSUE TITLE
JUHAN koolitused - kalendri vaate täiendused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#721]
- [ ] Kui sündmusel ei ole alguse kellaega, siis alguse kellaaega ei kuva (pealkiri nihkub vasakule, tühja kohta ei jää)

***
Kui sissepääsu tüüp (entryType) on "JUHAN", siis kalendris sündmuse peal klikkides avanevas modaalis:
- [ ]  kuupäeva ja alguse aja asemel kuvada "Toimimisaeg:" pp.kk.aaaa - pp.kk.aaaa  ( alguse kuupäev + kui on lõpu kuupäev ja see erineb alguse kuupäevast, siis ' - ' +  lõpu kuupäev )
- [ ] sissepääsu liiki ei kuva

***

- [ ] Parandada üldist viga, et kuu nimed algavad praegu suure tähega (peavad olema väikse tähega)

**Comment by TanelTromp** [comment]
VIga 1: a. "space" puudu, kui on kellaaeg b. Kui ei ole, siis punkt ka seljas, võiks tühik vahel olla:

![pilt](https://user-images.githubusercontent.com/37407917/52050950-cee66200-255a-11e9-8ca1-e6f8b77fd7a7.png)

![pilt](https://user-images.githubusercontent.com/37407917/52050990-eaea0380-255a-11e9-867f-4890090af4f5.png)

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Korras
Viga 3: Korras

**Comment by TanelTromp** [comment]
Viga 4: Nan:Nan "veel" valikus:
https://gyazo.com/b6219a9a67bbb902ab7327cb87340e6e

**Comment by skeefee** [comment]
Viga 4: Korras

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Kui sündmusel ei ole alguse kellaega, siis alguse kellaaega ei kuva (pealkiri nihkub vasakule, tühja kohta ei jää)
Kui sissepääsu tüüp (entryType) on "JUHAN", siis kalendris sündmuse peal klikkides avanevas modaalis:
- [ ]  kuupäeva ja alguse aja asemel kuvada "Toimimisaeg:" pp.kk.aaaa - pp.kk.aaaa  ( alguse kuupäev + kui on lõpu kuupäev ja see erineb alguse kuupäevast, siis ' - ' +  lõpu kuupäev )
- [ ] sissepääsu liiki ei kuva
- [ ] Parandada üldist viga, et kuu nimed algavad praegu suure tähega (peavad olema väikse tähega)

Kuvatõmmised:

![pilt](https://user-images.githubusercontent.com/37407917/52063468-678cda00-257b-11e9-8bea-62a337ab403b.png)

![pilt](https://user-images.githubusercontent.com/37407917/52063494-76738c80-257b-11e9-97b2-1814a59e42ad.png)

![pilt](https://user-images.githubusercontent.com/37407917/52063524-825f4e80-257b-11e9-9f25-7554b4da9e24.png)
