### ISSUE TITLE
JUHAN koolitused - detailvaate täiendused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#722]
Kui entrytype = "JUHAN", siis
- [ ] Toimumisaeg ja -koht plokis nädalapäeva, kuupäeva ja kellaaegade asemel kuvada pp.kk.aaaa - pp.kk.aaaa  ( alguse kuupäev + kui on lõpu kuupäev, siis ' - ' +  lõpu kuupäev )
- [ ] Sissepääs plokis näidata outbound linki "Registreerumine täiendkoolituste infosüsteemis", millele klikkimine avab veebilehitseja uuel vahelehel registreerimise URL-ga (registrationURL) viidatud lehe.
- [ ] Sissepääs plokis enda kalendrisse edastamise võimalust ei ole.

***
- [ ] Sissepääs plokk nimetada ümber "Registreerumine" (see muudatus on üldiselt sõltumata entryType-st).

**Comment by skeefee** [comment]
Korras

**Comment by TanelTromp** [comment]
Viga 1: poolitus või järgmisele reale sling:
![pilt](https://user-images.githubusercontent.com/37407917/52059858-9acb6b00-2573-11e9-8bcb-4f6b495331f2.png)

**Comment by skeefee** [comment]
Viga 1: Korras
Täpsustus 1: Ei tea

**Comment by skeefee** [comment]
UX-täiendus 1: Ei saa kahjuks. Seda peavad nad ise tegema

**Comment by TanelTromp** [comment]
TEST OK

Kui entrytype = "JUHAN", siis:
- [ ] Toimumisaeg ja -koht plokis nädalapäeva, kuupäeva ja kellaaegade asemel kuvada pp.kk.aaaa - pp.kk.aaaa  ( alguse kuupäev + kui on lõpu kuupäev, siis ' - ' +  lõpu kuupäev )
- [ ] Sissepääs plokis näidata outbound linki "Registreerumine täiendkoolituste infosüsteemis", millele klikkimine avab veebilehitseja uuel vahelehel registreerimise URL-ga (registrationURL) viidatud lehe.
- [ ] Sissepääs plokis enda kalendrisse edastamise võimalust ei ole.
- [ ] Sissepääs plokk nimetada ümber "Registreerumine" (see muudatus on üldiselt sõltumata entryType-st).
