### ISSUE TITLE
Disain täiendused

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#733]
### Läbivad vead
* Vasakmenüü paremas servas peab olema 1px hall piirjoon, hetkel tundub topelt
* Siltidel ei tohi olla ühtegi klikk või hover stiili (hetkel muutub silt klikkimisel halliks)
* Võrdluse vaadete ühtlustamine (ametialade võrdluse vaate alusel)
* thumbsup/thumbs down ikoon muuta (halli taustaga nagu oska vaadetes ikoonid)
* Päises oleva otsingukasti placeholder teksti opacity võiks olla 60%
* Listvaadete korrastamine (vastavalt ametiala listvaatele)
* Nummerdatud list peaks olema vasakult sama kaugel kui bullet list
* Tabeli read vajavad natuke rohkem paddingut, hetkel kõik read natuke liiga kokkusurutud (hetkel vist 8px, muudame 12 peale, kas saab?)
* Vasakmenüü dropdown nooleke peaks olema suunaga alla kui alammenüü on kinni ja liikuma suunaga üles, kui menüü on lahti
* Teksti sees olevale välise lingi ikoonile ei tohi tekkida alljoont (hover effekt)
* Tabelite veergude pealkirjal (hallil taustal) ei tohi olla alumist piirjoont
* Akrodioni sees on väline link nihkes (nt http://htm.twn.ee/artiklid/v%C3%A4lisministeeriumi-teadaanne-v%C3%A4lisleping)
* Cookie vorm > Tablet > nupp võiks olla mitte täis laiuses, äkki mahuvad nupp ja link kõrvuti?
* Cookie teavituse kast võiks olla kandiliste nurkadega ja 100% lai alati sõltumata ekraani laiusest (nupud ja tekst võiksid jääda muu leheülje sisuga sama laiaks, laieneb ainult hall taustakast)
* Parempoolses tulbas olevad lingid, mis lähevad kaherealiseks, teine rida võiks alata esimese rea sõnaga samalt kauguselt (hetkel hakkab ikooniga samalt kauguselt)
* Kui siseneda (eriala, ametiala, valdkonna vms) detailvaatesse ning seejärel liikuda tagasi nimekirja vaatesse, siis tahaks näha samasugust vaadet (nt kui olen lisanud filtreid või laadinud palju ridu), hetkel laetakse uuesti vaikimisi vaade ning kõik mu filtrid jms on kadunud, pean otsast peale alustama
* Sildid/Multiselect dropdown muuta läbivalt selliseks nagu Ametialade siltide valik (nt uudiste vaates vaja kohendada jne)

### Tunnistuste kontroll
* Tunnistusete kontroll: veateade vormiväljade kohale
* TUNNISTUSTE KONTROLL pealkirja ja lehekülje pealkirja vahel võiks olla joon (nagu nt Uudised või Sündmused vaadetes)

### Töölaud
* Isikuandmete modaal > Pealkirja ja isikukoodi vaheline ruum liiga suur (peaks olema 16px)
* Isikuandmete modaali max laiuseks võiks olla 700px
* Isikuandmete modaal > veateate ja ISIKUANDMED pealkirja vahe võiks olla 24px
* Sakid töölaual: hoveriga peaks muutuma rohekaks nagu teised sakid (hetkel läheb hoveriga halliks)
* Töölaud > Minu lemmikud > lemmikute kastile ruumi juurde alla (kui lemmikuid ei ole lisatud)

### Uudised
* Kui uudisele pole silti külge pandud, siis tekst võiks kohe kuupäeva reale järgneda (hetkel jääb sinna suur vahe) 

### Uudise detailvaade
* Parempaani uudiste heading tase vale (peaks olema väiksem, 20px)
* Parempaani pealkiri peab olema “Loe veel” 

### Õppeasutused > Asukohad
* Nimekirja vaates viimasel real ei tohiks alumist piirjoont olla
* Kaardivaates avaneval õppeasutuse infoaknal puudub piirjoon nime ja detailinfo vahel
* Infoakna detailinfo ridade vahel liiga palju ruumi (line height peaks olema 20px) 

### OSKA > Ametialad
* Ametiala konkurentsi tulbas teksti ja graafiku vahe suuremaks (ttekst ja "üsna kerge" vahe)
* Lehekülje lõpus oleva video ja siltide vahel on liiga palju õhku (nt siin: http://htm.twn.ee/ametialad/tehnikud)
* Joonise filtri nimetus vigane (http://htm.twn.ee/ametialad/operaatorid)
* Joonis ei lae ära (?): http://htm.twn.ee/ametialad/beeta-ametiala-pikk-50-t%C3%A4hem%C3%A4rki-eksju 

### OSKA > Ametialad > Ametialade võrdlus
* Võrdluse snackbaris tekib Vaata võrdlust nuppu hoverdades hall taust talle, seda ei tohiks olla
* Tabeli päis võiks ühtida teiste tabeli päistega (taust #eeeeee), järgmise reaga vajadusel valge 1px joon vahele jätta
* Valdkondade nimetuste reavahe liiga suur

### OSKA > Valdkonnad
* Valdkonna avatud infoaknas peaks pikk üldinfo olema lühendatud ning lingiga "Loe edasi"
* Valdkonna nimetusele klikkides on aktiivne outline (sinine) imeliku suurusega
* Valdkonna pealkiri võiks olla link (sinine+joon all), mille kaudu saab detailvaatesse
* Avatud infoaknas vertikaalne eraldusjoon ning üldinfole järgnev eraldusjoon peavad olema kitsamad (1px)
* Valdkonna gridvaade: hoveriga ei tohiks muutuda font weight, ainult joon kaob alt ära

### OSKA > Valdkonnad > Valdkonna detailvaade
* Faktid paneelil on brutopalga suurusjärgu joonis katki, olenemata summast on joonis alati sama
* Faktid paneelil peavad eraldusjooned olema 1px
* Faktid paneelil peab hõive muutuse juures olema ka protsent
* Valdkonnad paneelil peab olema link "Näita rohkem", hetkel on seal "Näita vähem" (kuigi osad valdkonnad on peidus) nt siin: http://htm.twn.ee/valdkonnad/metsandus-ja-puidut%C3%B6%C3%B6stus 

### OSKA > Tulemused
* Nupu "Vaata ettepanekute elluviimist" kohal on liiga palju vaba ruumi (nt: http://htm.twn.ee/oska-tulemused/tulemused-testimisel)
* Nupu "Vaata ettepanekute elluviimist" tekst ei ole joondatud ülevalt-alt keskele 

### OSKA > Ettepanekute elluviimine
* Pikad tekstilõigud peaksid olema lühendatud (osa teksti peidus) ning lingiga "Vaata rohkem" 

### Erialad
* Vasakmenüüs ei ole "Erialad" menüüpunkt aktiivne 

### Erialade võrdlus
* Pealkiri "Erialade võrdlemine" vaja muuta > "Erialade võrdlus"
* Link "Tagasi" vaja muuta > "Tagasi erialade nimekirja vaatesse" 

### Eriala detailvaade
* "Sarnased erialad" akordionis peab detailinfo liikuma kahele (või enamale) reale, kui infot palju 

### Otsingu tulemused
* "Otsingutulemusi ei leitud" vaates ei vasta UI kujundusele, tekst peab olema keskele joondatud ning Medium (font-weight)

### Sündmused
* Nimekirja vaates pole tänane päev kujundusega eristatud, kuupäev ja piirjoon peaksid olema punast värvi
* Nimekirja vaates on igal sündmusel üleval/all natuke liiga palju õhku
* Kalendervaates peab kuu nimetus olema suure algustähega
* Kalendervaates avaneval “2 veel” sündmuste infoaknal puudub piirjoon pealkirja ja sündmuste nimekirja vahel
* Sündmuste infoakna kuu nimetuse algustäht muuta väikseks

### Sündmuse detailvaade
* Parempaani pealkirjade heading tase vale (peaks olema väiksem)
* Sildid on üksteise küljes kinni (hetkel puudub kahe sildi vahel vaba ruum)
* “Toimumisaeg- ja koht” paanil muuta sõna Kell väikese algustähega

### Sündmuse registreerimisvorm modaal
* Kõikide väljade vahel peab olema võrdselt ruumi (hetkel eposti ja telefoni väljadel ülal-all liiga palju õhku)
“* Märgitud väljad…” muuta väikese algustähega > “* märgitud väljad…”
* Aktiveerides Märkused välja, peaks välja nimetus liikuma ülemise piirjoone peale, nagu kõigil teistel väljadel (hetkel kaob välja nimetus ära)

**Comment by birgitpulk** [comment]
![Screenshot 2019-03-06 at 17.20.51.png](https://images.zenhubusercontent.com/5af048384b5806bc2bd2095b/9f78b986-a427-40ae-908a-3279a30ad57b)

**Comment by Johhanna** [comment]
Läbivad vead
- Sisubloki valgel taustal peab kõigis nurkades border radius olema (hetkel nägin Uudised ja Sündmused vaadetes)
- Vasakmenüü paremas servas peab olema 1px hall piirjoon, hetkel tundub topelt
- Siltidel ei tohi olla ühtegi klikk või hover stiili (hetkel muutub silt klikkimise halliks)
- Jagamise ikoon detailvaates peab olema pealkirjaga samal kõrgusel ning paremasse serva joondatud (?)

Uudised
- Filrite kalendriikoon vale
- Kui uudisele pole silti külge pandud, siis tekst võiks kohe kuupäeva reale järgneda (hetkel jääb sinna suur vahe)

Uudise detailvaade
- Parempaani uudiste heading tase vale (peaks olema väiksem)
- Parempaani pealkiri peab olema “Loe veel”

Sündmused
- Nimekirja vaates pole tänane päev kujundusega eristatud, kuupäev ja piirjoon peaksid olema punast värvi
- Nimekirja vaates on igal sündmusel üleval/all natuke liiga palju õhku
- Kalendervaates peab kuu nimetus olema suure algustähega
- Kalendervaates avaneval “2 veel” sündmuste infoaknal puudub piirjoon pealkirja ja sündmuste nimekirja vahel
- Sündmuste infoakna kuu nimetuse algustäht muuta väikseks

Sündmuse detailvaade
- Parempaani pealkirjade heading tase vale (peaks olema väiksem)
- Sildid on üksteise küljes kinni (hetkel puudub kahe sildi vahel vaba ruum)
- “Toimumisaeg- ja koht” paanil muuta sõna Kell väikese algustähega

Sündmuse registreerimisvorm modaal
- Kõikide väljade vahel peab olema võrdselt ruumi (hetkel eposti ja telefoni väljadel ülal-all liiga palju õhku)
- “* Märgitud väljad…” muuta väikese algustähega > “* märgitud väljad…”
- Aktiveerides Märkused välja, peaks välja nimetus liikuma ülemise piirjoone peale, nagu kõigil teistel väljadel (hetkel kaob välja nimetus ära)

Õppeasutused > Asukohad
- Nimekirja vaates viimasel real ei tohiks alumist piirjoont olla
- Kaardivaates avaneval õppeasutuse infoaknal puudub piirjoon nime ja detailinfo vahel
- Infoakna detailinfo ridade vahel liiga palju ruumi

**Comment by Johhanna** [comment]
## Mobiil ja tablet

### Läbivad vead
- Burger ikoon katkine

### Sisselogimine modaal
- Sisselogimise modaali ei saa kerida (kerib hoopis taustal lehte)
- Modaal peab olema full-width ning päis peab jääma nähtavaks

### Uudised
- Pealkirja "UUDISED" all ei tohi olla piirjoont
- Pealkirja "UUDISED" all on liiga palju õhku

### Sündmused listvaade
- Pealkirja "SÜNDMUSED" all ei tohi olla piirjoont
- Päeva viimase sündmuse all on liiga palju õhku
- Kuupäev peab olema suurema kirjatüübiga
- Filtrites olevad kuupäevade väljad peavad olema kõrvuti, mitte üksteise all

### Sündmuse detailvaade
- Siltide vasakpoolne joondus on nihkes
- Registreerumismodaal peab olema full-width/height

### Õppeasutused 
- Nimekirja saki alumine oranž piirjoon katki
- 320px laiuses ei mahu sakid ära, parempoolne jääb veidi peitu
- Filtrite dropdownide placeholder tekst veidi nihkes
- Kui filtrites valida "Tüüp" alt "Põhikool või gümnaasium", siis "Õppeasutuse alamtase" peaks muutuma visulaalselt aktiivseks. Hetkel jääb disabled, kuid klikkida saab.
- Haldusüksuste kaardil võiks selgem olla, et kaardi all olev legend on keritav. Hetkel ei ole sellest alati aru saada.
- Kaardi vaates ei mahu infoaken ekraanile ära, osa jääb peitu
- Kui kaardil infoaken avada, siis fookus ei liigu korralikult aknale. Praegu avaneb infoaken nii, et osa jääb peitu ning pean ise kaardil navigeerima, et seda näha. Toetusprojektide kaardil see töötab korralikult.
- Kaarti ei saa sõrmedega zoomida (tervet vaadet zoomitakse)
- Kaart võiks kohanduda ekraani suurusega? Praegu veidi ebamugav kasutada, peab palju edasi-tagasi kerima ja sisse-välja zoomima. Võiks äkki uuesti läbi mõelda lahenduse.

### Toetusprojektid
- Kaart on väga väike, infoakna avamisel on kõik elemendid üksteise peal ja infoaken on osaliselt peidus

### Ametiala detailvaade
- Silt "Tuleviku ala!" vajab natuke rohkem paddingut üles/alla
- "Konkurent tööturul" mull on katki
- 320px laiuses on joonised-diagrammid üsna kokkusurutud, vasakul-paremal liiga palju vaba ruumi
Valdkonnad
- Valdkonna infoakent avades keritakse leht allapoole, kuid see ei ole hetkel väga mugav, see valdkonna kastike mille peale klikkisin, võiks nähtavale jääda ning kerimisel võiks mingi transition/efekt ka olla, praegu lihtsalt järsk hüpe kuskile.
- Valdkonna detailvaade ei lae hetkel ära, ei saa testida...

### Erialad
- Pealkirja "ERIALAD" all ei tohi olla piirjoont

### Töölaud
- "Õpingute andmed" ning "Õpetamiste andmed" sakkidel on pealkirjad, kuid tunnistustel pole. Võiks ehk lisada?
- Isikuandmete modaal on keeruline kerida, kuna põhiosa vaatest on tabel, mida saab kerida ainult paremale-vasakule.

## Tablet teemad

- Nupud on hetkel lehelaiused
- Akordionid võiks olla vasakut-paremalt paddinguga?

**Comment by birgitpulk** [comment]
Valdkonna hall modaal: üks link maha, teine siniseks

**Comment by heldiraudsepp** [comment]
Pilet realiseeritud jiras https://jira.twn.ee/browse/HP-38
