### ISSUE TITLE
Tunnistuse kehtivuse kontrolli täiendused

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#740]
Täiendada #568

- Pealkirjaks: Riigieksami tunnistuse kehtivuse kontroll
@birgitpulk Lisa palun uuendatud kujunduse viide.

- Kui kasutaja on sisse loginud siis recapcha nõue puudub.

- Pealkirja _Tunnistuse andmed_ järel koolon maha (üldjuhul mujal pole tabeli ees rakendatud)

**Comment by madispold** [comment]
Pileti sisu OK, kuid...

@ruut12 @lsoonvald olles sisse loginud ei leia tunnistusi
"The used authentication method is not allowed on this route."

**Comment by TanelTromp** [comment]
Täiendus 1: Mozillas on nooled ka tagasi, mis vahepeal oli fixitud:

![pilt](https://user-images.githubusercontent.com/37407917/52563801-17c7d180-2e0b-11e9-85fd-da2b44260a4f.png)

**Comment by madispold** [comment]
Täiendus 1: OK.

**Comment by ruut12** [comment]
Sisselogitud kasutaja õigused parandatud @TanelTromp

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Pealkirjaks: Riigieksami tunnistuse kehtivuse kontroll
- [ ] Kui kasutaja on sisse loginud siis recapcha nõue puudub.
- [ ] Pealkirja _Tunnistuse andmed_ järel koolon maha (üldjuhul mujal pole tabeli ees rakendatud)

--------------

Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/52776791-08cf6200-304b-11e9-8168-4636f30a9496.png)

![pilt](https://user-images.githubusercontent.com/37407917/52776812-1389f700-304b-11e9-8273-40d15d25593d.png)
