### ISSUE TITLE
Sündmuste vaate laiendus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#741]
- [ ] Laiendada helesiniste mummude kuva sündmuse juures taksonoomiapõhiste värvidega
- [ ] Lisada värvide kohta kasutajale abistav legend
- [ ] Kuvada kaardil suurematel murdepunktidel (lg ja xl aga võibolla ka md) nädala numbreid

Värvilist mummut kuvada kalendrivaates, sobivusel ka listivaates ja detailvaates.

**Comment by heldiraudsepp** [comment]
Tegeletakse uue sündmuste lahenduse käigus
