### ISSUE TITLE
Uudiskirja ei saa tellida ning tühi teavituse e-kiri sisu tellimisel

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#744]
Viga 1: udiskirja ei saa tellida:
https://gyazo.com/993d71d0ebdd438ea39dbd73283b59c2

Viga 2: tühi tellitud siltide teavitus:

![pilt.png](https://images.zenhubusercontent.com/5ab8a6294b5806bc2bcc56d1/65fbff1e-5627-44c1-b6bf-cd08e85cbeb6)

**Comment by lsoonvald** [comment]
Ei suutnud vigu korrata, ilmselt oli meiliserveriga midagi valesti tol hetkel.

**Comment by heldiraudsepp** [comment]
Läheb sprinti ainult testimise tööna 1h

**Comment by TanelTromp** [comment]
TEST

Sündmused teavitus OK

![pilt](https://user-images.githubusercontent.com/37407917/52912784-fd846c80-32be-11e9-812f-66418a32b701.png)
