### ISSUE TITLE
Teha ümber näitajate (faktid) csv import

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#745]
**Eesmärk:**
Sisutüübi „MainProfessionPage“ paremas veerus kuvatakse portaali külastajale fakte (näitajaid), mille andmeid uuendab sisuhaldur CSV-st. Selle töö raames uuendada CSV-st andmete importi #506 

**failis on päiserida (id;naitaja;ametiala;vaartus;ikoon)**

1. Faili kontroll:

Faili iga rida kontrollida järgmiselt:
- kui reas on täidetud üks veerg, siis on ka teised veerud kohustuslikud.
- kas esimeses veerus on id, number
- kas teises veerus on naitaja, tekst
- kas kolmandas veerus on ametiala: kas on olemas sisutüüp ametiala („MainProfessionPage“ ), mille väärtus võrdub failist saadava väärtusega.
- kas neljandas veerus on vaartus, number
- kas viiendas veerus on väärtus (ikooni nr), number
_Näitajad ja nende väärtusi me ei kontrolli, õigete näitajate ja neile vastavate väärtustega csv koostamine jääb sisuhalduri vastutuseks. Täiendused lisame kasutusjuhendisse #752_ 

Kui ilmneb viga, siis protsess katkestada ja kuvada faili rea number ja veateade ("Puudub id", Puudub naitaja", "Puudub ametiala", "Puudub vaartus", "Puudub ikooni nr"). Veateated võivad olla inglise keeles, kui kõiki teateid ei võimalda süsteem tõlkida.

NB! Kui mõnda ametiala ei eksisteeri, mis CSV'st tuleb, siis jäetakse see CSV rida vahele.

2. Salvestada failist loetavad ametiala näitajad. Faili iga rida salvestada:

* id
* naitaja
* ametiala
* vaartus
* ikoon

Näidisandmed MS Excelis SharePointi kaustas "Abimaterjalid" - "Oska" - faktide_import.xlsx

Viited: 
FE #695 
Front-endis ikooni lisamisel on vajalik näitaja id ja ikooni väärtus.

**Comment by heldiraudsepp** [comment]
Egle - 1h
BE - 5h

**Comment by EgleM-TW** [comment]
Nõuete lisandusmisega seoses tagasi to-do ja hindame uuesti.

**Comment by RainLeoma** [comment]
"naitaja" on ilma Ä-ta aga "väärtus" on ä-ga. See peaks ka olema "vaartus"

Muidu sobib!

**Comment by heldiraudsepp** [comment]
BE - 8h
Test - 2h

**Comment by lsoonvald** [comment]
Teen impordi ümber, hetkel valideerimine teeb puudulike andmete puhul impordi katki.

Kui mõnda ametiala ei eksisteeri, mis CSV'st tuleb, siis jäetakse see CSV rida vahele.

**Comment by TanelTromp** [comment]
Viga 1: vale veateade, peaks ütlema, et "Missing vaartus":

![pilt](https://user-images.githubusercontent.com/37407917/53019935-8dace800-345e-11e9-8cfb-10c91c6c66b7.png)

**Comment by lsoonvald** [comment]
Viga 1 ja 1.2 korras

**Comment by TanelTromp** [comment]
Täpsustus 1: kas süsteem kahte viga korraga ei suuda raporteerida?

![pilt](https://user-images.githubusercontent.com/37407917/53072490-ea0b1880-34ed-11e9-8ffc-4048421246df.png)

**Comment by EgleM-TW** [comment]
Piisab, kui on raporteeritud 1 viga rea kohta.

**Comment by TanelTromp** [comment]
TEST OK

kui reas on täidetud üks veerg, siis on ka teised veerud kohustuslikud:

- [ ] kas esimeses veerus on id, number
- [ ] kas teises veerus on naitaja, tekst
- [ ] kas kolmandas veerus on ametiala: kas on olemas sisutüüp ametiala („MainProfessionPage“ ), mille väärtus võrdub failist saadava väärtusega. _NB! Kui mõnda ametiala ei eksisteeri, mis CSV'st tuleb, siis jäetakse see CSV rida vahele_ **Kuna see klausel on täpsustuseks, siis võib olla "Ametiala" veerg ka tühi väärtus**
- [ ] kas neljandas veerus on vaartus, number
- [ ] kas viiendas veerus on väärtus (ikooni nr), number


Salvestada failist loetavad ametiala näitajad. Faili iga rida salvestada:

- [ ] id
- [ ] naitaja
- [ ] ametiala
- [ ] vaartus
- [ ] ikoon
