### ISSUE TITLE
Muutujate haldamine sisuhalduses

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#746]
Selle töö raames realiseeritakse sisuhalduses üldine lahendus, mis võimaldab portaalis kuvatavate skaalaga väärtuste puhul määrata miinimum ja maksimum väärtusi.

Testimine:
Backendi poole pealt lisatud uus leht, kus saab muutujate jaoks key'sid ja väärtuseid lisada.
https://htm.wiseman.ee/admin/config/htm_custom_variables/variable

Frontend saab muutujad vastavalt key'le kätte ning siis saab neid erinevate väärtuste jaoks kasutada, kus vaja, sarnaselt nagu translations päring.

Key'd väärtustega tulevad siit endpoindist JSON'na: https://htm.wiseman.ee/variables?_format=json

**Comment by heldiraudsepp** [comment]
BE - 6
FE - confitava teenuse tegemine 8

**Comment by EgleM-TW** [comment]
@lsoonvald Kui see on realiseeritud, palun lisada lühike kommentaar-viide testimiseks.

**Comment by lsoonvald** [comment]
Backendi poole pealt lisatud uus leht, kus saab muutujate jaoks key'sid ja väärtuseid lisada.
https://htm.wiseman.ee/admin/config/htm_custom_variables/variable

Frontend saab muutujad vastavalt key'le kätte ning siis saab neid erinevate väärtuste jaoks kasutada, kus vaja, sarnaselt nagu translations päring.

Key'd väärtustega tulevad siit endpoindist JSON'na: https://htm.wiseman.ee/variables?_format=json

**Comment by skeefee** [comment]
FE pool saab testida: http://htm.twn.ee/variables

**Comment by TanelTromp** [comment]
Viga 1: kuvab ainult esimese tähe välja muutujast @lsoonvald

**Comment by lsoonvald** [comment]
Viga 1: Parandatud.

**Comment by TanelTromp** [comment]
TEST OK

![pilt](https://user-images.githubusercontent.com/37407917/52782037-bac05b80-3056-11e9-95d5-fbec073ca776.png)

p.s "Tõeline testimine" tulevikus kasutajaliidese pileti raames
