### ISSUE TITLE
kujundada õppimisvõimaluste lingi kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#748]
Vajalik asap kujundus sellele tööle: #681

http://htm.twn.ee/ametialad/ajakirjanik, õppimisvõimaluste blokis kuvame:
õppekavarühma ei kuva välja - selle asemel link, et vaata erialasid

**Comment by birgitpulk** [comment]
Jääb tavapärase sisemise lingina, mis viib filtreeritud erialade vaatesse. 
![Screenshot 2019-02-12 at 18.28.42.png](https://images.zenhubusercontent.com/5af048384b5806bc2bd2095b/e51f13c8-53ae-4b73-9087-7316cf980b26)
