### ISSUE TITLE
OSKA ametialade nimekirjas FE täiendused

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#750]
Viga 1: nimekirjast puudu ametialasid, mis tulevad välja aga otsinguga (saab võrrelda vastu sisuhaldust).
Viga 2: "Lae rohkem" nuppu ei tohiks kuvada, kui midagi rohkem laadida ei ole - mäletamist mööda sai see parandatud - see lahendatakse piletis #802 
Viga 3: katkine ja tühi "ametiala"
Kõik vead kirjeldatud siin:
https://gyazo.com/12b35550590a80c18fc9bc1f1f6ac9e7

**Comment by EgleM-TW** [comment]
Lahendatud teistes piletites.
