### ISSUE TITLE
OSKA valdkonna sisutüübil hõivatute arvu kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#751]
**Üldinfo**
Sisutüübi OSKAField (valdkond) paremas veerus kuvatakse esimeses blokis hõivatute arvu, mille andmed sisestab oska sisuhaldur. 

FE
Disain: https://zpl.io/2ZzOYOd

**Kuvamine:**
 - Pealkiri _Hõivatute arv_ ja selle järel sisuhalduses sisestatud väärtus
 - Kui on sisestatud tekst väljale "Hõivatute arvu tekst" Kuvada tekst enne ikooni. (Seda välja ei planeerita hetkel täita, aga ei eemalda sisuhaldusest).
- Kui numbrilist väärtust pole sisestatud, siis andmeid välja ei kuva.
 - Ikooni kuvamine:
Ikoonil värvitud "mehikeste" arv tuleneb sisestatud hõivatute arv väärtusest.

hõivatute arv | värvitud ikoone
-- | --
kuni 9 999 | 1
10 000-14 999 | 2
15 000-19 999 | 3
20 000-24 999 | 4
25 000-29 999 | 5
30 000-34 999 | 6
35 000-44 999 | 7
45 000-54 999 | 8
55 000-64 999 | 9
65 000-74 999 | 10
alates 75 000 | 11

**Comment by RainLeoma** [comment]
Sobib!

**Comment by EgleM-TW** [comment]
Hinnatud 08.02:
FE: 8h
Test: 5h

**Comment by madispold** [comment]
@birgitpulk Oleks vaja täidetud ja täitmata mehikese ikooni/pilti.

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1: kui sisestada väärtus "Hõivatute arv" alla paremasse veergu, ilma et muid väärtusi seal oleks, siis kuvab kasutajaliideses ka tühja "ametiala" kastikest:

![pilt](https://user-images.githubusercontent.com/37407917/52713946-57282680-2fa1-11e9-9473-35c8b51c0126.png)

**Comment by madispold** [comment]
Viga 1: OK.
Viga 2: OK.
Viga 3: OK.

**Comment by TanelTromp** [comment]
Viga 4 WCAG: NVDA ekraanilugeriga ei saa enam "hõivatute arv 19 999" edasi välja liikuda (kui muud sisu paremas veerus ei ole, peale "hõiavtute arvu"), vaid jääb loopima. VO-ga korras ja alustab n.ö uuetl ringilt, kui sellelt elemendilt edasi liikuda.

http://htm.twn.ee/valdkonnad/toiduainet%C3%B6%C3%B6stus

**Comment by madispold** [comment]
Viga 4: NVDA standard käitumine üle lehe hetkel, liigub kuni viimase elemendini (kui pole snackbari või chat'i siis tavaliselt külgtulbaga sisu lõppeb). OK või suurem probleem ja mujale viia.
Viga 5: OK.

**Comment by birgitpulk** [comment]
Kujnduslikult võiks need mehikesed alati selle parempoolse kasti ära täita (vahed lähevad siis kas suuremaks või väiksemaks)
<img width="396" alt="screenshot 2019-02-14 at 11 34 51" src="https://user-images.githubusercontent.com/24669779/52777483-995a7200-304c-11e9-9623-4ca095bab538.png">

**Comment by madispold** [comment]
@birgitpulk mehikesed täies laiuses

**Comment by birgitpulk** [comment]
Kujundus korras

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Pealkiri _Hõivatute arv_ ja selle järel sisuhalduses sisestatud väärtus
- [ ] Kui on sisestatud tekst väljale "Hõivatute arvu tekst" Kuvada tekst enne ikooni. (Seda välja ei planeerita hetkel täita, aga ei eemalda sisuhaldusest).
- [ ] Kui numbrilist väärtust pole sisestatud, siis andmeid välja ei kuva.
- [ ] Ikooni kuvamine: ikoonil värvitud "mehikeste" arv tuleneb sisestatud hõivatute arv väärtusest.

----------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/52840215-3b3b9680-3101-11e9-832b-3f6cfe5fc1bd.png)

![pilt](https://user-images.githubusercontent.com/37407917/52840419-e1879c00-3101-11e9-9353-909c19fe79a3.png)
