### ISSUE TITLE
Valdkonna lehel ametialade kuvamise muudatus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#753]
**Eesmärk**
OSKA valdkonna sisutüübil (FiledPage) kuvatakse ametialasid (MainProffessionPage) nimekirjana.

**Vastuvõtutingimused**
BE
Muuta valdkonna sisutüübi toimetamist ja päringut ametialade kuvamiseks:
* Eemaldada valdkonna sisutüübi toimetamisel blokk **Ametialad** (MainProfession).

* Uuendada päringut (ametialade kuvamiseks valdkonna lehel) front-endile (sisestus ametiala lehelt).

FE
Kuvada valdkonna sisutüübil ametialad (MainProfessionPage). 
_Taust: Seos valdkonnaga luuakse ametiala sisulehe loomisel (valdkonna leht peab olema eelnevalt sisestatud ja ametiala sisulehe loomisel lisatakse viide valdkonnale (kohustulik)._

Disain: https://zpl.io/2ZzOYOd

1. Kuvada (vt sarnast tööd #694 ):
* ametiala sisutüübi nimetus,  so link, mis viib ametiala detailvaatesse
* kuvada 3 järgmist näitajat (kui all nimetatud näitajat pole lisatud, ei kuva puuduva näitja kohta midagi):
- Kuvada esimesena bloki "Konkurents tööturul" väärtus, mis teisendada järgmiselt (vt viimane veerg):

CSV   väärtus | Filling bar kuvatav väärtus | Nimekirjas kuvatav väärtus
-- | -- | --
1 | kerge | Kerge leida tööd
2 | üsna kerge | Üsna kerge leida tööd
3 | keskmine | Keskmised töö leidmise   võimalused
4 | üsna raske | Üsna raske leida tööd
5 | raske | Raske leida tööd

- Kuvada blokist "Faktid"
   - Hõivatute arv, id 1 (ikoonita)
   - Brutopalk, id 3 (euro märk kuvada numbri järel)

2. Ametialade nimistu kuvatakse valdkonna lehel akordionis (esimesena), sisuhaldusest saab lisada alanevaid akordioni osi. Vaikimisi on akordion suletud.

3. Ametialad kuvada tähestikulises järjekorras.

4. Ametialasid saab lisada võrdlusesse (võrdlusesse lisamisega seotud nõudeid ei muudeta)

**Comment by heldiraudsepp** [comment]
FE - 12h
Test - 6h
Disaini test - 2h

**Comment by RainLeoma** [comment]
Sobib!

**Comment by heldiraudsepp** [comment]
BE tehtud, ainult @madispold

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
UX-täiendus 1: kui kasutaja läheb ametialade võrdlusesse Valdkonna alt, siis võiks võrdlusest tagasi nupp viia samuti sinna, kust alustati ehk valdkonna detailvaatesse, mitte ametilade nimekiri vaatesse (tekst samuti teine siis):
![pilt](https://user-images.githubusercontent.com/37407917/55057476-f8f76480-5071-11e9-9cd0-e51909f9926f.png)

**Comment by birgitpulk** [comment]
UX-täiendus 1: otsustasime, et eemaldame selle "Tagasi..." nupu üldse ära. Kuna seda on vaja teha ka teistest võrdluse vaadetes, siis selle kohta tuleb eraldi pilet.

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

http://htm.twn.ee/valdkonnad/haridus-ja-teadus

BE

- [ ] Eemaldada valdkonna sisutüübi toimetamisel blokk Ametialad (MainProfession).
- [ ] Uuendada päringut (ametialade kuvamiseks valdkonna lehel) front-endile (sisestus ametiala lehelt

FE

- [ ] ametiala sisutüübi nimetus, so link, mis viib ametiala detailvaatesse
- [ ] kuvada 3 järgmist näitajat (kui all nimetatud näitajat pole lisatud, ei kuva puuduva näitja kohta midagi)
- [ ] Kuvada esimesena bloki "Konkurents tööturul" väärtus

- [ ] Kuvada blokist "Faktid"
    Hõivatute arv, id 1 (ikoonita)
    Brutopalk, id 3 (euro märk kuvada numbri järel)


- [ ] Ametialade nimistu kuvatakse valdkonna lehel akordionis (esimesena), sisuhaldusest saab lisada alanevaid akordioni osi. Vaikimisi on akordion suletud.
- [ ] Ametialad kuvada tähestikulises järjekorras.
- [ ] Ametialasid saab lisada võrdlusesse (võrdlusesse lisamisega seotud nõudeid ei muudeta)

-----------------
Kuvatõmmised:

![pilt](https://user-images.githubusercontent.com/37407917/55069902-b93e7600-508d-11e9-9467-42359cc05d2f.png)

![pilt](https://user-images.githubusercontent.com/37407917/55069937-cd827300-508d-11e9-94ca-3c6e5fdad0fa.png)

![pilt](https://user-images.githubusercontent.com/37407917/55070005-fe62a800-508d-11e9-85a1-8ca54b42ad7e.png)

![pilt](https://user-images.githubusercontent.com/37407917/55070085-29e59280-508e-11e9-9b6d-38e65f04614f.png)
