### ISSUE TITLE
Täiendada filling bar kuvamist

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#754]
Täiendada filling bar kuvamist #698 järgmiselt (muuta pealkirja all kuvatavat teksti):

Pealkirja all kuvatav tekst: 
Kui raske on leida sellel ametialal tööd järgmisel 5–10 aastal? 

Disainis kajastub muudatus ka: https://zpl.io/V41Wg1M

**Comment by madispold** [comment]
OK.

**Comment by TanelTromp** [comment]
UX-täiendus 1 EDGE/IE11: UHD vaates poolitab kummaliselt - võiks "5-10 aastal" lugeda üheks elemendiks ja murda koos

**Comment by madispold** [comment]
UX-täiendus 1 EDGE/IE11: OK.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Pealkirja all kuvatav tekst: Kui raske on leida sellel ametialal tööd järgmisel 5–10 aastal?

-----------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/52712779-4629e600-2f9e-11e9-802b-0fc2a77effd6.png)

![pilt](https://user-images.githubusercontent.com/37407917/52712858-8b4e1800-2f9e-11e9-8ae7-2b562660da6c.png)
