### ISSUE TITLE
Infograafika filtrite kujundus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#755]
Kujundada infograafika filtrite kuvamine.

Selle raames lahendame ka #578 

Pidepunktid:

Kas graafikutele jääb grid?
Pealkirja stiil ja asukoht
Legend alati graafiku alla
Graafiku ette kujundada teksti osa (sisestatakse koos graafikuga ja siia lisame ka WYSIWYG redaktori)

**Comment by birgitpulk** [comment]
1. Graafiku font on Rubik
2. Legendi teksti suurus on 14
3. Pealkirja teksti suurus on 16, Rubik, Medium
4. Teksti toonid #333333
5. Gridi väärtuste tekst Rubik, 14, Light, #757575
6. Parempoolsete väärtuste grid välja lülitada?
7. Legend graafiku alla
8. Legend joondub 0-väärtusega vasakule
9. Joonel on üks toon

@skeefee
