### ISSUE TITLE
Sisutüüp Artikkel koos alamlehtede (akordion) ja parema ääreribaga

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#76]
Epic - Sisulehed - #9 

**Sissejuhatus**

Sisutüübile Artikkel on võimalik luua portaali sisulehti koos alamosadega (akordion) ja ilma akordionit lisamata. Samuti saab lisada lehele parema ääreriba, kuid võib jätta lehe ka selleta.

Dokumentatsioonis kasutatud mõisted:

- SimpleArticlePage - ilma akordioni ja parempoolse veeruta sisuleht
- ArticlePage - koos akordioni ja parema veeruga sisuleht

**Kirjeldavad tööd**

1. SimpleArticlePage toimetamine: #18 
2. SimpleArticlePage kuvamine: #82 
3. ArticlePage ehk alamosadega (akordion) sisulehe toimetamine: #128 lõplikud piirangud #181 
4. ArticlePage ehk akordioniga sisulehe kuvamine #19 
5. ArticlePage parema ääreriba toimetamine #138 
6. ArticlePage parema ääreriba kuvamine #139 
7. Video lisamine: #204 
8. Video kuvamine: #205 ja disain #275
9. WYSIWYG redaktor #15

**Comment by EgleM-TW** [comment]
05.04.2018 seisuga on prototüübi vaade mobiilile vajalik juurde luua ja vajadusel täiendada ka eelanalüüsi vaadet.
