### ISSUE TITLE
Infograafika testimine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#760]
**Eesmärk**
Testida kasutusjuhendi järgi:
1. kas sisuhalduses on võimalik luua dünaamilist infograafikat;
2. kas sisuhalduses lisatud graafikud kuvatakse portaalis;
3. kas portaalis kuvatud graafikud on dünaamilised (portaali külastaja saab neid "näppida").

Selle testimise raames saab dünaamilist infograafikat lisada OSKA ametiala sisutüübile (hiljem lisanduvad teised oska sisutüübid).

Testitakse töid: #709 #711 #710 #711 ja #632 
_CSV asukoht: Sharepoint - Abimaterjalid - OSKA - CSV-d ja Infograafika-1_

**Näidised:** http://htm.twn.ee/ametialad/taneli-isiklik-ametiala

**Nr 1 Eksport - alavaldkondade võrdlemine**
Sama näitaja piires saab võrrelda ühe valdkonna alavaldkondasid.
* Line graafik
* Ühik: summa
* Metsamajandus ja puidutööstus alavaldkonnad: 
•	Metsamajandus
•	Puidutööstus
•	Saagimine

**Nr 2 Combo**
Saab lisada eemaldada näitajaid (4)
•	Näitaja: Eksport näitaja ja Käive näitaja – stacked column
•	Periood: 2015–2018
•	Combo näitaja: Ettevõtlus kokku ja Teine näitaja
•	Valdkond: Rõiva-, tekstiili- ja nahatööstus
•	Ühik: euro

**Nr 3 Combo** (Sama mis nr 2, aga clustered column ja ühik summa)
Saab lisada eemaldada näitajaid (4)
•	Näitaja: Eksport näitaja ja Käive näitaja – stacked column
•	Periood: 2015–2018
•	Combo näitaja: Ettevõtlus kokku ja Teine näitaja
•	Valdkond: Rõiva-, tekstiili- ja nahatööstus
•	Ühik: summa

**Nr 4 Lõpetajad/ sisseastujad**
Saab ühe näitaja piires võrrelda erinevaid (selle graafikul 2) ametialasid 
•	Näitaja: lõpetamine/ sisseastumine – stacked column100% graafik
•	Silt: bakalaureus, rakenduskõrgharidus, doktorantuur 
•	Ametialad: Tööstusseadmete ja -masinate mehaanikud ja Konstruktorid

**Nr 5 Vanus ametialadel**
Saab ühe näitaja piires võrrelda erinevaid ametialasid 
•	Näitaja: vanus – stacked bar100% graafik
•	Silt: alla 30, 30-39, 40-59, üle 60 (järjekord pole oluline, see tuleb csv-st ja seal hetkel suvaliselt)
•	Ametialad: Aednikud, Agronoom, ...

Muud testimse graafikud, mille kohta on juhised ja näiteid kasutusjuhendisse:

- http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine
- http://htm.twn.ee/ametialad/xcombo-graafikud
- http://htm.twn.ee/ametialad/kaamen (siin on vigadega summeerimisel ja selle tõttu combo graafikud tuleb teha kasutusjuhendi järgi)

**Comment by EgleM-TW** [comment]
Testimine:
BE parendused:
FE parendused:

**Comment by EgleM-TW** [comment]
@skeefee 
Lisatud multi-line graafik: http://htm.twn.ee/ametialad/taneli-isiklik-ametiala
Lisatud 2 valdkonda ja nende valdkondade alavaldkonnad.

Viga nr 1. Vaikimisi vaade on vale, kuvab ka neid valdkondi, mida sisuhaldusest pole üldse lisatud:
https://i.gyazo.com/3e0a4c8b723f5caa4c6fe4bd66810f6a.png

Viga nr 2. Kui filtrist valida 1 valdkond, siis alavaldkonna filtris peaks kuvama ainult valitud valdkonna alavaldkondi. Hetkel kuvab mõlema valdkonna omi.

**Comment by EgleM-TW** [comment]
@lsoonvald 
Lisatud multi-line graafik: http://htm.twn.ee/ametialad/taneli-isiklik-ametiala
Lisatud 2 valdkonda ja nende valdkondade alavaldkonnad.

Viga nr 3. Hetkel summerib valdkonna väärtuseks kõik valdkonnaga seotud read, selles näites:
Eksport, Metalli- ja masinatööstus 2015 - 213 (so summa: alavaldkondade read; valdkonna rida).
Peaks kuvama ainult valdkonna kohta käivat rida (väärtus 63).

Teha summeerimisel muudatus:
CSV rea väärtus kehtib kõige väiksema üksuse kohta, st et:
* kui reas on täidetud valdkond, alavaldkond, ametiala, siis väärtus kehtib ametiala kohta
* kui reas on täidetud valdkond, alavaldkond, siis väärtus kehtib alavaldkonna kohta
* kui reas on täidetud valdkond, siis väärtus kehtib valdkonna kohta. Ja valdkonna väärtuse kuvamisel me ei summeeri alavalkondade ja ametialade väärtusi, mis on selle valdkonnaga seotud.

**Comment by EgleM-TW** [comment]
@lsoonvald
Lisatud combo graafik (nr 2): http://htm.twn.ee/ametialad/taneli-isiklik-ametiala
Probleem: Kuna vaikimisi kuvatakse esimesena valitud näitajat, siis combo graafiku puhul on see alati line tüüpi näitaja, mis ei ole õige, kuna combo graafikul line on täiendav näitaja (nt osakaal).
Tuleks sisuhalduses ikkagi tõsta nii ümber, et esmalt lisad põhigraafiku (esimesena valid põhigraafiku näitaja) ja alles siis combo (line tüüpi).

**Comment by EgleM-TW** [comment]
@lsoonvald @skeefee 
Lisatud combo graafik (nr 2): http://htm.twn.ee/ametialad/taneli-isiklik-ametiala
- Lisatud 2 valdkonda
- 2 line tüüpi näitajat (osakaal ettevõtlusest ja osakaal töötlevast tööstusest - need on nö teised näitajad, mida kuvatakse põhinäitajaga graafikule lisaks)
- 1 column tüüpi näitaja (investeeringud)

**Viga nr 4.** Line ja column näitajad kuvatakse vastupidi sisuhalduses sisestatule. Ettepanek, et Lars muudab ikkagi sisuhalduses järjekorda - esmalt sisetsan põhigraafiku (column vm) ja teisena line tüüpi koos selle näitajaga.

Viga nr 5. Näitaja filtris ei kuva kõiki siestatud näitajaid (investeeringud on puudu).

**Comment by EgleM-TW** [comment]
@lsoonvald 
Lisatud combo graafik (nr 3): http://htm.twn.ee/ametialad/taneli-isiklik-ametiala

Viga nr 6. Soov oli lisada põhigraafikuks stacked, milllel näidata alavaldkondi (investeeringud) ja combona line tüüpi graafik (osakaal ettevõtlusest).
Sisuhalduses on esmalt line tüüpi graafiku kirjeldamine, kus ma ei taha lisada näitajaks investeeringud, aga siis ei saa lisada alavaldkondi. Teise näitaja lisamisel, ikka ei teki valikusse alavaldkondi (ainult siis tekivad, kui lisan selle näitaja line tüüpi graafikule (mis on vale). 

Lahendame sisuhalduses nii nagu viga nr 4 kirjas.

**Comment by EgleM-TW** [comment]
@lsoonvald ja @skeefee 
Lisatud stacked100% graafik (nr 4): http://htm.twn.ee/ametialad/taneli-isiklik-ametiala

Viga nr 8. Stacked100% ei kuva y telge päris ootuspäraselt. Võimalik, et vajab sisuhalduses muutmist, või tuleb frondis päringu andmetega teisiti toimetada. Igal juhul oodatav tulemus on siin:
https://i.gyazo.com/7dc344be4fb7be81567276841325214e.png
Sisuhalduses lisatud andmetes grupeering on sildi järgi ja jaotama peaks ametiala järgi. Jaotuse võks teha x-telje määrangu alusel.

**Comment by EgleM-TW** [comment]
UUS test:
@skeefee 
http://htm.twn.ee/ametialad/kaamen
Nr 1 graafik
1. Vaikimisi kuvab kõiki näitajaga seotud valdkondi. Lisada päringusse üksnes see valdkond, mis on graafikule määratud (selles näites ainul 1). Muuta see filtris automaatselt märgituks.

2. Sellel graafikul on oodatud tulemus, et kui valin mitu näitajat siis kuvatakse need eraldi line. @lsoonvald, mis loogika on kui valin mitu näitjat ühe valdkonna kohta - summeerib? Peaks näitama eraldi joontel. Mitut näitajat saab korraga kuvada ainult siis, kui on üks valdkond/alavaldkond/ ametiala.

Nr 2 graafik
@skeefee 
1. Tuleb seada piirangud - kui on lisatud mitu valdkonda/ alavaldkonda/ametiala - siis korraga saab vaadata ühte näitajat - radiobutton.

**Comment by EgleM-TW** [comment]
@skeefee 
Graafik nr on combo
1. Tuleb lisada eraldi filter näitajatele: indicator ja secondaryGraphIndicator.
2. Sama nagu nr 1 graafikul - valitud on 1 valdkond, ja see tuleb anda päringusse.
3. Graafiku tüübid on seotud näitajaga - hetkel mõlemad line, kuigi esimene (indicator) kohta peaks olema column.

**Comment by TanelTromp** [comment]
TEST vead seoses infograafika ajatamisega ja CSV muutmisega #773 

Viga 1: kui ajatamise vahel laadida üles CSV, kus ajatatud sisul varem infograafika valitud näitajaid enam ei ole, siis ei tohiks infograafikat välja kuvada. Hetkel kuvab välja valikuid, mis ei ole enam relevantsed ja ei vasta sisestusele. 
Pärast uut CSV-d teeb need väljad sisuhalduses tühjaks ja kuvab siis astmelt ülespoole näitajad, mis ei olnud tegelikult graafikukuva mõte:
![pilt](https://user-images.githubusercontent.com/37407917/53886638-2465d100-4029-11e9-90ce-2111060b0366.png)

Kuvab:
https://gyazo.com/654d99ad46c45a7e704ab91bcc76fa7c

Viga 2: kui laadida sisse uus CSV, millel puuduvad sisestatud väärtused, mis infograafikal varem olid valitud, siis kuvab neid valikuid ikkagi rippmenüüdes ja graafik läheb katki. Peaks uuenema reaalajas vastavalt CSV-le ja kui vastavaid väärtusi enam ei ole CSV-s, siis graafikut mitte kuvama (nt: "Metalli- ja masinatööstus" valdkondadest ja alavaldkondadest "Traktorite valmistamine"
https://gyazo.com/2b6f9145b772b19e4ec5000f7f66c04f

**Comment by EgleM-TW** [comment]
http://htm.twn.ee/ametialad/taneli-isiklik-ametiala
Graafik nr 1 - legendil väärtused kuvada kõik välja (htekel, mis ei mahu lähevad noole taha peitu)

**Comment by EgleM-TW** [comment]
Use case 1: http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine
Lisatud 2 erinevat graafikut, kus kasutaja saab valdkonde üleselt näitajaid võrrelda.
OK clustered bar ja line diagrammidel. Tuleks testida ka ülejäänud tüüpidega @TanelTromp. Samas peab arvestama, et CSV testandmed ei pruugi sobida kõikidele diagrammidele (samas vaja näha, kas ja kuidas välja kuvab).

**Comment by EgleM-TW** [comment]
Use case 2: http://htm.twn.ee/ametialad/ametialade-graafikud
Lisatud 2 varianti stacked100% graafikutest.

**Comment by EgleM-TW** [comment]
@lsoonvald 
Sisuhalduses on Graph Y unit väli pärast combo graafiku tüübi valikut. Kuna Line tüüpi graafikul combo graafikut teha ei saa (ja vastavad väljad ka puuduvad) siis koos nende väljadega kaob ka Graph Y unit väli ning line graafikul ei saa määrata ühikut. Palun tõsta see Graph Y unit väli ette poole, et väli oleks määratav ka ilma combo graafikuta.

**Comment by EgleM-TW** [comment]
@skeefee 
sisuhalduses saab määrata Y telgede min väärtused: väljad MinimumY ja secondaryMinimumY - kasutajaliideses neid valikuid ei ole arvestatud. Näide nr 9 graafik: http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine

**Comment by EgleM-TW** [comment]
@skeefee 
Graafikutel tooltipi sees on numbrite kuvamine ameerika-päraselt. Oodatav tulemus - väärtused kuvatakse eesti-päraselt, vt #632 

Kui on lahendatud palun märkida selle kohta info siia sama kommentaari sisse.

**Comment by EgleM-TW** [comment]
@skeefee 
Raporteeritud Skypes 25.03: Graafikutel nr 6 ja 8 http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine kuvatakse väärtusi valesti - võrreldud CSV andmetega, kus näitaja Ekspordiosakaal valdkonnas Metsamajandus ja puidutööstus aasta 2017 = 40, aga kuvab 10 (vahetuses 2018 väärtusega).

Lahendatud: 26.03

**Comment by EgleM-TW** [comment]
Raporteeritud skypes 25.03: http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine Kui sisuhalduses määrata ühikuks % siis chart korrutab täiskohalise vääruse 100-ga; kui määrata arv 0,** siis BE poolel toimub ümardamine vastavalt piletile #632 .

**Comment by EgleM-TW** [comment]
23.02 raporteeritud smmeerimise vea lahendus:
Teha summeerimisel muudatus:
CSV rea väärtus kehtib kõige väiksema üksuse kohta, st et:
- kui reas on täidetud valdkond, alavaldkond, ametiala, siis väärtus kehtib ametiala kohta
- kui reas on täidetud valdkond, alavaldkond, siis väärtus kehtib alavaldkonna kohta
- kui reas on täidetud valdkond, siis väärtus kehtib valdkonna kohta. Ja valdkonna väärtuse kuvamisel me ei summeeri alavalkondade ja ametialade väärtusi, mis on selle valdkonnaga seotud.

Summeerimise viga graafikul nr 6 http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine, kuna x-teljel on valdkond, siis summeerimine seda ei arvestanud ja liitis valdkonnad+alavaldkonnad kokku. 

Lahendatud: 25.03 ja 26.03 Summeerimisel kontrollitakse lisaks grupeeringule ka x-teljel valdkonna/alavaldkonna andmeid ja lähtutakse eelnevalt kirjeldatust.

**Comment by EgleM-TW** [comment]
@skeefee 
http://htm.twn.ee/ametialad/kaamen esimesel graafikul (line tüüpi) y telje väärtused ameerika-pärased. Varasemalt sama probleem lahendatud column/ bar tüüpi graafikutel.

**Comment by EgleM-TW** [comment]
http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine
Nr 4 graafik. Kui filtrist eemaldada kõik valdkonnad (peaks jääma tühi graafik), aga kuvab kõiki valikuid (ehk vaikimsi kõik valdkonnad). Kasutajale on see pisut eksitav, sest ta on kõik valikud just eemaldanud. Samas tühja graafiku kuvamine pole ka hea lahendus. Probleem siin fikseeritud ja hetkel jääme olemasoleva lahenduse juurde.

**Comment by EgleM-TW** [comment]
http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine
Nr 1 ja 2 graafikul näitajad Käive ja Palk
CSV-st laetud sisse uued andmed, mida frondis ei kuvata. Samas andmed on päringus olemas. 
Tühjendatud drupali cache ja probleem lahenes.

**Comment by skeefee** [comment]
* Sisuhalduses saab määrata Y telgede min väärtused: väljad MinimumY ja secondaryMinimumY - kasutajaliideses neid valikuid ei ole arvestatud. Näide nr 9 graafik: http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine
- Y telje min väärtust saab ainult vasakule poole panna. Paremale poole hetkel ei ole võimalik panna. Peame angular google chart uuendust ootama.

* Graafikutel tooltipi sees on numbrite kuvamine ameerika-päraselt. Oodatav tulemus - väärtused kuvatakse eesti-päraselt, vt #632
- See eeldaks andmestrukuuri muudatust kas siis BE või FE poole pealt. Jätame hilisemaks

* http://htm.twn.ee/ametialad/kaamen esimesel graafikul (line tüüpi) y telje väärtused ameerika-pärased. Varasemalt sama probleem lahendatud column/ bar tüüpi graafikutel.
- Korras

**Comment by EgleM-TW** [comment]
http://htm.twn.ee/ametialad/xcombo-graafikud
Summeerimise probleem, kui valdkond/alavaldkond/ametiala ei ole grupeeringus ega x-teljel, siis süsteem summeerib kõik read. Näiteks valdkonna kohta kaasab ka alavaldkonna read. Lisada summeerimise lahendusele reeglid, et valdkond/alavaldkond/ametiala filtrid arvesse võtta ja sh mittemääratud väljad välja jätta.
