### ISSUE TITLE
Sündmuse lisamise ja kuvamise täiendused

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#766]
**Eesmärk**
Realiseerida sisutüüp Sündmus lisamise ja kuvamisega seotud täiendused #689 ja entryType JUHAN tüübi lisandumisest tulenevad muudatused päringutes - selle töö järgselt parandada vead piletis #640 .

**BE:**
Lisada uus sündmuse sissepääsu tüüp (entryType) „välise registreerimisega“, mille valimisel on kohustuslik täita URL väli (sisuhaldur lisab välise süsteemi lingi). URL lisada FE-le pakutavatesse teenustesse.

**FE:**
**Muuta sündmuse registreerumise bloki päringut järgnevalt:**
Juhul kui sündmuse sissepääsu tüüp (entryType) = välise registreerimisega, kuvada blokis „Registreerumine“ sisuhalduses lisatud  outbound linki tekstina „Registreerumine teises infosüsteemis“. Lingile klikkimine avab veebilehitseja uuel vahelehel sisuhalduses lisatud URL’ga. 

**Kellaaegade puudumisega seotud täiendused:**
Muuta sündmuse kuupäevade kuvamist ja sellega seotud päringuid:
- Kui sisuhalduses pole lisatud sündmuse põhi- või lisakuupäevaga seotud kellaaegu (põhikuupäeva startTime, endTime; lisakuupäeva startTime, endTime) siis:
   * kellaaja infot ei kuvata (ei kuvata mingit asendusteksti)
   * Kui entryType = registreerumisega, siis sündmusele registreerumise käivitamine on võimalik ka juhul kui registreerumise alguse kuupäev (registrationFirstDate) = jooksev kuupäev.
   * Kui entryType = vaba sissepääs või kutsetega ja toimumise kuupäev on >= jooksev kuupäev siis blokis „Sissepääs“ ei tohi kuvada „Sündmus on möödunud“.

**Comment by heldiraudsepp** [comment]
BE - 1h
FE - 4h
Test - 10h

**Comment by TanelTromp** [comment]
Viga 1: Vale nimi valikul, peab olema: "välise registreerimisega", mitte "väline registreerimisega"

Muudatus 1 BE: Vale "hint" ilmub "Registreerumise URL-i" infomullikese alt (autocomplete loogika tekst).

**Comment by skeefee** [comment]
Viga 1 FE: Korras
Viga 2 FE: Korras

**Comment by TanelTromp** [comment]
TEST

Viga 1 WCAG: Peale "kaardi elementi" ei liigu ekraaniluger heading "Toimumisege ja -koht" peale, vaid kohe kuupäeva reale, mis seal plokis sees on.

**Comment by heldiraudsepp** [comment]
FE - 4h
Test - 4h

**Comment by lsoonvald** [comment]
Viga 1 BE: Korras
Viga 2 BE: Korras
Muudatus 1 BE: Korras
Muudatus 2 BE: Ei saa aru muudatusest
Muudatus 3 BE: Korras

**Comment by TanelTromp** [comment]
FE-le-

**Comment by TanelTromp** [comment]
Muudatus 1 BE korduv: _vale "hint" ilmub "Registreerumise URL-i" infomullikese alt (autocomplete loogika tekst)>_. Tegemist on kopi/peist outbound lingi väljaga ehk peaks siin keerama autocomplete kinni, sest ma ei usu, et ükski välise sündmuse registreerumise URL asub selles serveris.

![pilt](https://user-images.githubusercontent.com/37407917/56558325-02a7b580-65a7-11e9-8264-9dde6f693974.png)

**Comment by lsoonvald** [comment]
Muudatus 1: Korras.
Muudatus 4: Korras. Kustutasin vana välja ära ja tekitasin uue samasuguse, vanad määratud kuupäevad ilmselt kadunud nüüd, vaja uuesti tekitada.

**Comment by TanelTromp** [comment]
Viga 3 BE uus: ei lase lisakuupäeva valida ja annab errori:

https://gyazo.com/7734be7428951baf51f83cc5ff951d2b

![pilt](https://user-images.githubusercontent.com/37407917/56579128-0b64af80-65d8-11e9-8a38-89f90ada6ef0.png)

Muudatus 4 muudatus: lisakuupäeva väli võiks olla sama loogikaga kuvatud, kui teised ehk kuupäeva valik ja siis kellaajad:

![pilt](https://user-images.githubusercontent.com/37407917/56579034-c5a7e700-65d7-11e9-8ab5-5d3fd2bdd1cd.png)

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Korras

WCAG 1: Korras
WCAG 2: Korras

**Comment by TanelTromp** [comment]
Ootab BE töid.

**Comment by lsoonvald** [comment]
Viga 3: Korras.
Viga 4: Ei saa korda teha, backendist on väli pandud mittekohustuslikuks, kuid on kohustuslik.
Muudatus 4: Korras.
Muudatus 5: Ei suutnud taastekitada.

**Comment by TanelTromp** [comment]
Viga 2 korduv: on valitud tänane kuupäev ja ütleb, et "Sündmus on möödunud". Peaks kuvama sissepääsutüübi? Testlugu: @skeefee 
http://htm.twn.ee/s%C3%BCndmused/%C3%BCks-tore-s%C3%BCndmus
http://htm.wiseman.ee:30000/node/52317/edit?destination=/admin/content

**Comment by heldiraudsepp** [comment]
Veel teha:
FE - 8h
Test - 1h

**Comment by skeefee** [comment]
Viga 2: @lsoonvald tundub, et BE-s on mingi kotermann sees. Ainult sellel konkreetsel sündmusel on kuupäeva sisestades väärtused 'null'.  
![Annotation 2019-05-03 092210](https://user-images.githubusercontent.com/13978713/57122260-21673280-6d85-11e9-952c-617e1cd510f3.png)

viga x: korras
ux täiendus: korras

**Comment by lsoonvald** [comment]
Viga 2: Ei saa korda teha, tegu on bugiga, mis on seotud sellega kui väljade kuvamine on teise väljaga seoses. Selline olukord tekib ainult siis kui varem registreerimise tüübiga üritus muuta mingiks teiseks tüübiks. @skeefee @heldiraudsepp @TanelTromp
