### ISSUE TITLE
WYSIWYG redaktor graafiku infoteksti väjale

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#768]
Eesmärk
Infograafiku tekstiväli (GraphInfoText) võimaldab sisestada teksti sarnaselt väljale Sisu (content).

Nõuded:
Teksti lisamisel on sisuhalduses teksti kujunamiseks WYSIWYG redaktori all kirjeldatud võimalused:

* bold, italic
* bullet ja number listid
* formaadid Heading3 ja Paragraph 
* spetsiaalsümbolid
* tabelid
Lisatud juurde:
* link
* fail

Tekst on vaikimisi joondatud vasakule. Muud joondused ja taandread pole lubatud.

WYSIWYG redaktoris on tekstiga töötamiseks järgmised võimalused:
* undo, redo
* cut, copy, paste, paste puhastatult (saab Wordist lõigatud teksti kleepida)

**Comment by heldiraudsepp** [comment]
BE - 3h
Test - 6h

**Comment by EgleM-TW** [comment]
Testimiseks saab hetkel kasutada sisutüüpi ametiala, kus on lisatud dünaamiline infograafik (või luua ise uus graafik).

**Comment by TanelTromp** [comment]
Täpsustus 1: nõuetes ei ole loetletud "Link" ja "File" võimalusi. redaktoris on need hetkel olemas. Kas saab maha keerata?

![pilt](https://user-images.githubusercontent.com/37407917/53866808-19944780-3ffb-11e9-961a-040c39b760e7.png)

**Comment by EgleM-TW** [comment]
Lisasin @skeefee , et frondis saaks vead kohe parandatud. Hiljem lisame FE tunnid piletile juurde.

**Comment by EgleM-TW** [comment]
Täspsustus 1 loendite vasakule joondamine on ka sisutekstiväljal nii, seega selle töö raames jääb nii. 
Täpsustus 2 linkide lisamine (GraphInfoText) väljal on ebakorrektne (testitud: http://htm.twn.ee/ametialad/kaamen). Kui sisuhalduses on link määratud avanema uues aknas siis peab kuvama välise lingina, kus ikoon on lingi järel ja joon lingi alla tekib alles hiirega lingile liikudes.

Lisaks ei vasta ootustele sisutekstiväljal sisemise lingi lisamine - peaks kuvama sisemise lingina (joon all ja ikooni pole).

Linkide korda tegemine (GraphInfoText) väljal ja sisutekstiväljal kõikidel OSKA sisutüüpidel piletiga 801. Teised sisutüübid jäävad piletisse #747

**Comment by TanelTromp** [comment]
TEST OK, BE


Teksti lisamisel on sisuhalduses teksti kujunamiseks WYSIWYG redaktori all kirjeldatud võimalused:

- [ ]     bold, italic
- [ ]     bullet ja number listid
- [ ]     formaadid Heading3 ja Paragraph
- [ ]     spetsiaalsümbolid
- [ ]     tabelid
- [ ]     Lisatud juurde:
- [ ]     link
- [ ]     fail

- [ ] Tekst on vaikimisi joondatud vasakule. Muud joondused ja taandread pole lubatud. **Hetkel töötab v.a bullet ja number listid. Kirjeldatud üleval ja realiseeritakse FE pileti raames**

WYSIWYG redaktoris on tekstiga töötamiseks järgmised võimalused:

   - [ ]  undo, redo
- [ ]     cut, copy, paste, paste puhastatult (saab Wordist lõigatud teksti kleepida)
