### ISSUE TITLE
Numbrite kuvamise täiendused

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#771]
Muuta numbrite kuvamist järgmiste reeglite alusel:
* neljakohalised või väiksemad araabia numbritega kirjutatud arvud kuvada kokku, nt 25, 250, 2500
* alates viiekohalistest arvudest rühmitada numbreid kolmekaupa lõpust, nt 25 000, 250 000, 2 500 000
* rühmitusmärgiks on tühik

Muuta numbrite kuvamist eelnevalt kirjeldatud reeglite alusel järgmistel vaadetel:
* OSKA ametiala (MainProfessionPage) - Faktide kuvamine #695 
* OSKA valdkond (FiledPage) - Hõivatute arvu kuvamine #751

**Comment by heldiraudsepp** [comment]
FE - 4h
Test - 2h

**Comment by EgleM-TW** [comment]
Planeerimisel otsustatud, et jääb locale seadistus.
