### ISSUE TITLE
OSKA valdkonna ja ametiala sisutüübi avaldamise ajatamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#773]
Sisuhaldur saab luua sisulehest  (OskaFiledPage ja MainProfessionPage) versiooni ja määrata kuupäeva ning kellaaja, mis hetkel sisuleht muutub portaalis avaldatuks.

Kui kellaaega ei valita, siis automaatselt määrab süsteem kellaajaks 00:00.

Lahenduses arvestada, et sisulehed (OskaFiledPage ja MainProfessionPage) on seotud CSV importidega (faktid, infograafika), mille uuendamine tehakse käsitsi kas vahetult enne või pärast lehe ajatatud avaldamist. Ajatatud sisulehe avaldamisel peab kuvama viimast versiooni CSV-st.

**Comment by heldiraudsepp** [comment]
BE - 1h
Test - 4h

**Comment by TanelTromp** [comment]
Täpsustus 1: kellaaeg peab samuti olema kohustuslik, kui ajatamine toimub ehk kuupäev tulevikku valitakse (Egla says). Vaadata üle ka muude sisude ajatamine sama loogika alusel.

Viga 1: tektiab mitu sisu sisuhaldusesse, kui ajatan, saven, ajatan saven:

![pilt](https://user-images.githubusercontent.com/37407917/53802048-7a634780-3f49-11e9-97b9-5085f31c04a9.png)

**Comment by lsoonvald** [comment]
Täpsustus 1: Kui kellaaega ei valita, siis läheb kellaajaks 00:00. Varem pole see ka kuskil kohustuslik olnud, aga kui on vaja lisaarendada, siis teeb ära. @EgleM-TW 

Viga 1: Ei oska korrata.
Viga 2: Korras.
Viga 3: Kui sa paned ajatamise aja tulevikku, siis ongi ta nii kaua avaldamata või mis siin veana silmas peetud on?

**Comment by TanelTromp** [comment]
Viga 3: ajatatud uudis ei avaldu määratud kellaajal samal päeval, mis uudist lood proovi nt 5 minutit tulevikku ajatada "today" kuupäeval (st jääb "avaldamata" staatus 4ever)

(hetkel tagasi debugimisse ja testin edasi, kui see viga parandatud)
.

**Comment by lsoonvald** [comment]
Viga 3: Ei suuda korrata. Panin sisul Beeta ametiala pikk 50 tähemärki eksju avaldamise ajaks 13:25. Tegin seda kell 13:24. Kell 13:25 on sisu avaldatud seisus.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Sisuhaldur saab luua sisulehest (OskaFiledPage ja MainProfessionPage) versiooni ja määrata kuupäeva ning kellaaja, mis hetkel sisuleht muutub portaalis avaldatuks.

- [x] Kui kellaaega ei valita, siis automaatselt määrab süsteem kellaajaks 00:00.

- [x] Lahenduses arvestada, et sisulehed (OskaFiledPage ja MainProfessionPage) on seotud CSV importidega (faktid, infograafika), mille uuendamine tehakse käsitsi kas vahetult enne või pärast lehe ajatatud avaldamist. Ajatatud sisulehe avaldamisel peab kuvama viimast versiooni CSV-st. **Eeldab, et sisestatakse  uus CSV, mille andmed klapivad vanaga. St ei tohi ridu, mis on sisestatud infograafikasse, puudu olla. Vead kirjeldatud #760 piletis**
