### ISSUE TITLE
Vormi päise disain

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#775]
Kavandada lehe muudatused:
- URL ja breadcrumb (vormid/"vorminimi“)
- üldpealkiri (mis oleks "Taotlused" asemel?)
- tabid "Dokument" ja "Seotud dokument" on tingimuslikult (on siis, kui dokumendis on „references“ või „acceptable_forms“ element) 
- sisse logimata kasutajale sisse logimise nõutavuse kohta veateate kuvamine siis, kui kasutaja pole sisse loginud, aga vormi täitmiseks peab olema sisse logitud.
- esitamise nupu juurde paigutada recaptcha

 Vaadata üle kogu vorm  ja teha parandusettepanekud. Näiteks, kas elementide pealkirjade pikad tekstid on probleemiks. Kuna ei tea, mis probleeme või tekkida ja ei oska ette näha kõiki parandusettepanekuid, siis siit võib tekkida täiendavaid töid - probleemide lahendused kirjeldada edasiste tööde ettepanekutena.

**Comment by EgleM-TW** [comment]
https://jira.twn.ee/browse/EHIS2-88
