### ISSUE TITLE
Vormi täitmine sisse logimata

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#776]
Tuleb muuta süsteemi nii, et dokumendivormi saaks täita ilma sisse logimata.  Dokumendi definitsiooni päisesse "header" lisatakse tunnus "auth_not_required". Kui  "auth_not_required" väärtus on _true_ , siis vormi saab täita ilma sisse logimata.

- [ ] Täiendada definitsiooni kontrolli nii, et päises oleks lubatud element "auth_not_required" ja selle väärtus peab olema tõeväärtus (true / false)
- [ ] Kui "auth_not_required" on _true_, siis saab vormi täita ka sisse logimata. 
- [ ] Kui  "auth_not_required" on _false_ või puudub, siis on vormi täitmiseks vaja sisse logida.
- [ ] Kui kasutaja on sisse logimata ja vormi täitmiseks peab olema sisse logitud, siis süsteem kuvab veateate "Seda vormi saab täita ainult sisse logitud kasutaja. Palun logige sisse."
- [ ] Kui dokumendivormi täidab mitte sisse loginud kasutaja, siis esitamise (submit) jaoks peab olema läbi tehtud recaptcha.

**Comment by lsoonvald** [comment]
BE tehtud

**Comment by TanelTromp** [comment]
TEST


- [ ] Täiendada definitsiooni kontrolli nii, et päises oleks lubatud element "auth_not_required" ja selle väärtus peab olema tõeväärtus (true / false)
- [ ] Kui "auth_not_required" on _true_, siis saab vormi täita ka sisse logimata. 
- [ ] Kui  "auth_not_required" on _false_ või puudub, siis on vormi täitmiseks vaja sisse logida.
- [ ] Kui kasutaja on sisse logimata ja vormi täitmiseks peab olema sisse logitud, siis süsteem kuvab veateate "Seda vormi saab täita ainult sisse logitud kasutaja. Palun logige sisse."
- [ ] Kui dokumendivormi täidab mitte sisse loginud kasutaja, siis esitamise (submit) jaoks peab olema läbi tehtud recaptcha.

**Comment by lsoonvald** [comment]
Viga: xcsrfTokeni peab ära ootama enne kui leht laeb. @madispold

**Comment by madispold** [comment]
Viga xcsrfTokeni ootamine: OK. @TanelTromp

**Comment by TanelTromp** [comment]
TEST OK


- [ ] Täiendada definitsiooni kontrolli nii, et päises oleks lubatud element "auth_not_required" ja selle väärtus peab olema tõeväärtus (true / false)
- [ ] Kui "auth_not_required" on _true_, siis saab vormi täita ka sisse logimata. 
- [ ] Kui  "auth_not_required" on _false_ või puudub, siis on vormi täitmiseks vaja sisse logida.
- [ ] Kui kasutaja on sisse logimata ja vormi täitmiseks peab olema sisse logitud, siis süsteem kuvab veateate "Seda vormi saab täita ainult sisse logitud kasutaja. Palun logige sisse."
- [ ] Kui dokumendivormi täidab mitte sisse loginud kasutaja, siis esitamise (submit) jaoks peab olema läbi tehtud recaptcha.

-----------------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/56208614-39874400-605a-11e9-84f8-b25c7f9b4f6e.png)

![pilt](https://user-images.githubusercontent.com/37407917/56208658-51f75e80-605a-11e9-9fa8-a78f7f1b3dc6.png)
