### ISSUE TITLE
Vormi täiendused

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#777]
Täiendada dokumendi sisestamise vormi vastavalt #775 tulemustele:
- [ ] URL-i muudatused 
- [ ] breadcrumb muudatused
- [ ] lehe pealkirja muutus
- [ ] tabide "Dokument" ja "Seotud dokument" tingimuslik kuvamine (kui dokumendis on „references“ või „acceptable_forms“ element, siis kuvataks need tabid ja muidu on ilma tab-e kuvamata kuvatud ainult dokumendi osa)

**Comment by EgleM-TW** [comment]
https://jira.twn.ee/browse/EHIS2-89
