### ISSUE TITLE
Vormi salvestamine portaali

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#778]
Portaali BE-s hakatakse juhtima, mis juhul pöörduda edasi lõime kaudu mõnda teise infosüsteemi ja mis juhul salvestada vormi sisu portaali. Vormi sisu salvestatakse portaali CSV failina. Iga erineva nimetusega vormi ("form_name") jaoks on eraldi CSV. Iga vormi esitamise korral lisatakse CSV-sse üks rida. Siin peab arvestama, et kui vormi on juba esitatud, siis andmeelemente ei saa lisada ega eemaldada (õigemini saab, aga CSV-s "veerud" lähevad paigast ära).

---
Kui FE küsib dokumendi algväärtuseid (FE annab BE-le sisendiks "tühja" dokumendi, kus on ainult "form_name") ja päises ("header") elemendi „endpoint“ väärtus on „HP“, siis 
- [x] BE tagastab täidetava dokumendivormi. Selleks BE võtab dokumendivormi definitsiooni, mille nimi võrdub "form_name" väärtusega ja lisab päisesse ("header") elemendid "identifier" : "0", "current_step" : 1, "acceptable_activity" : "SUBMIT". 
-----
Kui FE edastab esitatud dokumendi (annab post dokument sisendis dokumendi, kus elemendi "activity" väärtus on "SUBMIT" ) ja päises ("header") elemendi „endpoint“ väärtus on „HP“, siis BE salvestab andmed CSV-sse:
- [x] Uue CSV tegemine: Kui on uus vorm (CSV on tühi), siis süsteem esmalt kirjutab CVS-sse päise rea. Päise ritta kirjutatakse dokumendivormi definitsiooni iga andmeelemendi kohta üks veeru pealkiri (veeru pealkiri on json andmeelemendi nimetus).
- [x] CSV-sse andmete kirjutamine: Süsteem lisab CSV-sse uue rea. Dokumendivormi definitsiooni iga andmeelemendi kohta süsteem otsib dokumendivormist value ja kirjutab CSV-sse. Kui value-t pole, siis kirjutab CSV-sse tühja elemendi.
- [x] Tagasiside andmine: 
- Süsteem muudab päises "acceptable_activity" : "VIEW"
- Kui CSV-sse kirjutamine õnnestus, siis süsteem lisab sõnumi kehasse ("body") elemendi "message" : "success_message".
- Kui CSV-sse kirjutamine ebaõnnestus, siis süsteem lisab sõnumi kehasse ("body") elemendi "message" : "error_message".
----
- [ ] BE kasutaja peab saama CSV faili BE-st alla laadida (sh lisada vastav kasutusõigus, mis võimaldab CSV-d alla laadida ilma vormi definitsiooni muutmise õiguseta).
----
- [x] Kuna CSV-sse ei saa salvestada tabeli ja faili tüüpi andmeelementide ja korduvate väärtustega andmeelementide väärtuseid, siis tuleb lisada vormi definitsiooni kontroll: kui elemendi „endpoint“ väärtus on „HP“, siis table ja file elemendi tüübid ei ole lubatud ja multiple : true ei ole lubatud. 
- [x] Kuna portaali BE-s ei ole mitme etapilist andmete töötlemist, siis saab dokumendivormil olla ainult üks samm ehk tuleb lisada vormi definitsiooni kontroll: kui elemendi „endpoint“ väärtus on „HP“, siis "number_of_steps" väärtus peab olema 1.
----

Testimiseks teha üks vormi definitsiooni fail.

**Comment by lsoonvald** [comment]
Vormi CSV allalaadimine realiseeritakse #805 raames.

**Comment by heldiraudsepp** [comment]
Ainult testimine

**Comment by andrussarv** [comment]
- [ ] Kuupäeva formaat peab olema "YYYY-DD-MM".
- [ ] Praegu ei rakendu kontroll, et kui elemendi „endpoint“ väärtus on „HP“, siis number_of_steps väärtus peab olema 1.
- [ ] Praegu ei rakendu kontroll, et kui elemendi „endpoint“ väärtus on „HP“, siis file elemendi tüüp ei ole lubatud. 
- [ ] Kontrollida üle, et kui elemendi „endpoint“ väärtus on „HP", siis ei oleks lubatud andmetüüp "table" ja lisatunnus multiple : true ei oleks lubatud. Lisada piirang, et ka "address" andmetüüp ei oleks lubatud.
- [ ] Lisada kontroll, et kui elemendi „endpoint“ väärtus on „HP", siis oleks vormi definitsiooni lõpus olemas messages.success_message ja messages.error_message objektid.

**Comment by lsoonvald** [comment]
Vanad kontrollid ei rakendu korrektselt, saab lisada property'na keysid, mis ei tohiks saada.

**Comment by TanelTromp** [comment]
Viga selline hetkel: http://htm.wiseman.ee:30000/xjson-csv-list

![pilt](https://user-images.githubusercontent.com/37407917/55399128-efc73580-5552-11e9-94a9-510a1ab3eeca.png)

**Comment by TanelTromp** [comment]
Viga 1: http://htm.wiseman.ee:30000/xjson-csv-list ei näita allalaetud CSV-s lisatud väärtusi (on ainults päis ja e-maili value)
https://gyazo.com/53ebb65e6f3eccdc84b056f1209c44b9

**Comment by lsoonvald** [comment]
Viga 1: Korras.
Viga 2: Korras
Mida teha/kas teha 1: Korras.
Täpsustus 0: Korras.
Täiendus 1: Jääb id'ga, vajalik süsteemi seostes.
Täiendus 2: Kui valitud pole, jääb tühi, kui on valitud, siis true.
Täiendus 3: Ei saa frondist sisestada midagi muud peale numbri, õpeta, kuidas said.

**Comment by TanelTromp** [comment]
Täiendus 2 korduv: ei ole "true", vaid "1" endiselt:

![pilt](https://user-images.githubusercontent.com/37407917/55780634-1506f700-5ab1-11e9-99be-cc6d3afa5824.png)

Täiendus 3 korduv: Mozilla

**Comment by lsoonvald** [comment]
Täiendus 2: Korras.
Täiendus 3: Korras.

**Comment by TanelTromp** [comment]
Viga 3: kui sisestada kohustuslikule e-kirja väljale väärtus, siis see eemaldada ja vajutada "Esita", siis süsteem ei saa enam aru, mis toimub ja viskab uknown errori üles:

https://gyazo.com/ea6b325689d5e2d08291775da10ed62d

**Comment by lsoonvald** [comment]
Viga 3: Korras.

**Comment by TanelTromp** [comment]
Viga 4: IE11 kuvab random rea juures valet errorit
https://gyazo.com/14e5804aaf31c46669ef833806b24796

**Comment by lsoonvald** [comment]
Viga 4: Korras.

**Comment by TanelTromp** [comment]
TEST

- [x] BE tagastab täidetava dokumendivormi. Selleks BE võtab dokumendivormi definitsiooni, mille nimi võrdub "form_name" väärtusega ja lisab päisesse ("header") elemendid "identifier" : "0", "current_step" : 1, "acceptable_activity" : "SUBMIT".
![image](https://user-images.githubusercontent.com/37407917/55965522-6d8bef00-5c7f-11e9-87a4-f12ffd81b3d0.png)

- [x] Uue CSV tegemine: Kui on uus vorm (CSV on tühi), siis süsteem esmalt kirjutab CVS-sse päise rea. Päise ritta kirjutatakse dokumendivormi definitsiooni iga andmeelemendi kohta üks veeru pealkiri (veeru pealkiri on json andmeelemendi nimetus). _Testija kommentaar: seejuures kirjutatakse CSV-sse ka päiserida, mille andmeelemendil on väärtus "hidden: true"._
