### ISSUE TITLE
Vormi alusel e-maili saatmine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#779]
Dokumendivormi sisestatud e-posti aadressidele saab saata teateid. Teade kirjeldatakse dokumendivormi definitsioonis. Dokumendivormi definitsioonis saab #email" tüüpi andmeelemendi juures esitada lisatunnused:
- sendEmail - näitab, kas saate eposti teade
- emailSubject - saadetava eposti teate pealkiri
- emailBody - saadetava e-posti teate sisu 
---
- [ ] Dokumendivormi definitsiooni kontrollidesse lisada reeglid:
- kui päise "header" elemendi  „endpoint“  väärtus on  „HP“ ja andmeelemendi kirjelduses elemendi "type" väärtus on "email", siis võib andmeelemendil olla lisatunnus sendEmail
- sendEmail väärtus peab olema boolean (true või false),
- kui "sendEmail" : true, siis peavad andmeelemendil olema ka lisatunnused emailSubject ja emailBody
--- 
- [ ] Realiseerida emaili saatmine pärast dokumendist saadavate andmete salvestamist (#778): kui "sendEmail" väärtus on true, siis saata "value"-st saadavale aadressile email, mille teemarida on dokumendivormi definitsioonist saadav emailSubject ja sisu on dokumendivormi definitsioonist saadav emailBody.

**Comment by TanelTromp** [comment]
TEST OK

- [ ] kui päise "header" elemendi „endpoint“ väärtus on „HP“ ja andmeelemendi kirjelduses elemendi "type" väärtus on "email", siis võib andmeelemendil olla lisatunnus sendEmail

- [ ] sendEmail väärtus peab olema boolean (true või false),

- [ ] kui "sendEmail" : true, siis peavad andmeelemendil olema ka lisatunnused emailSubject ja emailBody

- [ ] Realiseerida emaili saatmine pärast dokumendist saadavate andmete salvestamist (#778): kui "sendEmail" väärtus on true, siis saata "value"-st saadavale aadressile email, mille teemarida on dokumendivormi definitsioonist saadav emailSubject ja sisu on dokumendivormi definitsioonist saadav emailBody.
