### ISSUE TITLE
Autentimise variantide seadistamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#786]
- [ ] Portaalis BE-s saab seadistada, mis autentimise vahenditega on võimalik autentida.

----

- Disain: kujundada mobii-ID autentimine (Disaini pilet: #661)
- BE: seadistus (tara, harid, mobiil-id kohta märked, kas seda meetodit saab või ei saa kasutada)
- BE: autentimise seadistuse päring, et FE saaks küsida autentimise seadistused 
- BE: autentimise käigus autentimise seadistuse alusel kontroll 
- FE: sisse logimisel küsida BE-st autentimise seadistused ja pakkuda autentimise võimalusi vastavalt seadistustele (kui ükski autentimise meetod pole lubatud, siis veateade "Praegu pole sisse logimine võimalik. Proovige hiljem uuesti").
- FE: mobiil-ID autentimise vorm vastavalt disainile

**Comment by heldiraudsepp** [comment]
BE - 4h
FE - 20h
Test - 4h
Disaini test - 1h

**Comment by lsoonvald** [comment]
Endpoint, kus saab kätte, kas autentimismeetod on enabled või ei. 1 = jah, 0 = ei

http://test-htm.wiseman.ee:30000/auth_methods?_format=json

**Comment by lsoonvald** [comment]
Testijale:
Struktuur -> Authentication settings form

**Comment by TanelTromp** [comment]
TEST BE OK

https://gyazo.com/4341f5c695d628167ee711c98bf0d90d

**Comment by heldiraudsepp** [comment]
FE - 8h
Test - 4h
Disaini test - 1h

**Comment by priitpu** [comment]
Mobiili päise disain tegemata, kuna skoop suurem kui ainult see pilet.
Peaks tegema eraldi pileti päise mobiilivariandi arenduseks.

**Comment by TanelTromp** [comment]
TEST

Viga 1: IE11-ga puudub sisselogimise ikoon

Kuvatõmmised @birgitpulk 

UHD:
![pilt](https://user-images.githubusercontent.com/37407917/54811306-10f56f80-4c91-11e9-8b31-4f7fe2e15b13.png)

![pilt](https://user-images.githubusercontent.com/37407917/54811606-c0cadd00-4c91-11e9-8ec1-eebe5da8a1b0.png)


Poolik aken, x reso:

![pilt](https://user-images.githubusercontent.com/37407917/54811659-e0620580-4c91-11e9-9657-d4140016593e.png)

**Comment by birgitpulk** [comment]
**Üldine:**
- [ ] Nupud ja vormiväljad võiksid olla samasuguse laiusega
- [ ] Mobiil-ID juures olev "Sisene" nupp võiks olla vormiväljaga sama lai
- [ ] Modaali ülemise riba värvitoon peaks olema #fd8208
- [ ] Sisene Mobiil-ID-ga pealkirja ja input välja vahe peaks olema 16px
- [ ] Tabelt/Mobiil: Esimese nupu ja Sisene kirja vahel võiks olla rohkem ruumi (24px)
- [ ] Tabelt/Mobiil: "Või" jooned ja nupud võiksid alati olla sama laiad ning sisukasti servadest alati 24px paremalt-vasakult

**HariID+Tara+Mobiil-ID_desktop**
- [ ] Telefoni numbri input väli ja Sisene TARA-ga nupp ei joondu ülemisest servast

**Comment by priitpu** [comment]
> Viga 1: IE11-ga puudub sisselogimise ikoon
Parandatud
> Viga 2: tingimus ei ole täidetud:(kui ükski autentimise meetod pole lubatud, siis veateade "Praegu pole sisse logimine võimalik. Proovige hiljem uuesti")
Parandatud

> Viga 3 WCAG: modaalil loeb "x" >"button". Peaks lugema korraga "button close".
Parandatud

**Comment by TanelTromp** [comment]
TEST OK


- [ ] Disain: kujundada mobii-ID autentimine (Disaini pilet: #661)
![pilt](https://user-images.githubusercontent.com/37407917/54987627-92b10a00-4fbd-11e9-8437-544771339df8.png)

- [ ] BE: seadistus (tara, harid, mobiil-id kohta märked, kas seda meetodit saab või ei saa kasutada)
- [ ] BE: autentimise seadistuse päring, et FE saaks küsida autentimise seadistused
- [ ] BE: autentimise käigus autentimise seadistuse alusel kontroll
- [ ] FE: sisse logimisel küsida BE-st autentimise seadistused ja pakkuda autentimise võimalusi vastavalt seadistustele (kui ükski autentimise meetod pole lubatud, siis veateade "Praegu pole sisse logimine võimalik. Proovige hiljem uuesti").
- [ ] FE:mobiil-ID autentimise vorm vastavalt disainile
-------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/54987568-7e6d0d00-4fbd-11e9-9a65-12128c03f775.png)

**Comment by birgitpulk** [comment]
Kujunduse osas korras.
