### ISSUE TITLE
Rolli valiku ära võtmine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#787]
- [ ]  Töölaualt eemaldada rolli valik (selgitus: esialgu saab  hakata portaali kasutama ainult füüsilise isikuna, hiljem pannakse rolli valik tagasi).

**Comment by heldiraudsepp** [comment]
FE - 1h
Test - 1h

**Comment by TanelTromp** [comment]
TEST OK

Mobiiliga testimata, sest ei saa sisselogida parooli ja kasutajanimega.
p.s Vead kirjeldatud https://github.com/hariduspilv/haridusportaal/issues/788
