### ISSUE TITLE
Taotluste tabi ära võtmine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#788]
- [ ] Töölaualt eemaldada "Taotlused" tab (selgitus: esialgu saab hakata portaali kasutama ainult päringute tegemiseks, hiljem pannakse taotluste osa tagasi).
---

- Disain: Kujundada alles jäävate tabide asukohad (päringud, õpin, õpetan)

**Comment by heldiraudsepp** [comment]
FE - 2h
Disain+ disaini test - 1h
Test - 2h

**Comment by TanelTromp** [comment]
TEST

Viga 1: kui liikuda URL-lt "/tunnistused" välja ja minna menüüpunkti kaudu tagasi, siis on vale URL (seda ei peaks olemas olema: "http://htm.twn.ee/töölaud") ning kuva katki:

https://gyazo.com/c9505170ae80f4806096e46f81006150

**Comment by priitpu** [comment]
Sürr1: Peab Kokkiga läbi arutama kogu 404 loogika.

**Comment by birgitpulk** [comment]
Kujundus korras

**Comment by TanelTromp** [comment]
TEST OK

- [x] Töölaualt eemaldada "Taotlused" tab (selgitus: esialgu saab hakata portaali kasutama ainult päringute tegemiseks, hiljem pannakse taotluste osa tagasi).
-------------
Kuvatõmmised:

![pilt](https://user-images.githubusercontent.com/37407917/54187924-4347e580-44b7-11e9-8db4-bef245295acf.png)
