### ISSUE TITLE
Akordionite täiendus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#789]
- [ ] Muuta akordioni kujundust, et kui akordion on avatud ja fookuses, siis päise raamijoone ja sisu vahele jääks ruumi.

---

- Disain: Teha avatud akordioni uus kujundus
- FE: Realiseerida kujundus

**Comment by heldiraudsepp** [comment]
Birgit teeb disaini ja siis hindame

**Comment by Johhanna** [comment]
Täiendatud kujundused:
[https://zpl.io/2GQZ8v3](url)
[https://zpl.io/2vWKxNQ](url)
[https://zpl.io/a3lkGZY](url)

**Comment by heldiraudsepp** [comment]
https://jira.twn.ee/browse/HP-74
