### ISSUE TITLE
Riigieksamite tulemuste kuvamise täiendus

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#790]
- [ ] Testi osad kuvada tabeli asemel üksteise all andmeplokkidena (sh lisada alampealkiri "Testi osad")

---

- Disain: Teha testi osade kuvamise kujundus (https://zpl.io/VqwZr0m)
- FE: Realiseerida kujundus

**Comment by heldiraudsepp** [comment]
Birgit - 3h
FE - 4h
Test - 6h

**Comment by priitpu** [comment]
Mockitud mitmeosalise eksamiga:
![image](https://user-images.githubusercontent.com/17040443/55789862-d6c70300-5ac3-11e9-9562-c7f7a3fb3e38.png)

**Comment by priitpu** [comment]
> Viga/täpsustada kujundajaga 1: avatud akordioni headeri värv ei klapi Zepiga @birgitpulk 

Parandatud

> UI-täiendus mobiilivaade 1: kas tekstid võiks olla joondatud samale joonele @birgitpulk

Parandatud

> Viga 1 WCAG: tulba headeris (column), millel ei ole sisu, võiks ekraaniluger vahele jätta ja hüpata kohe järgmisele reale ehk konktreetsel juhul "2012":

Parandatud

> Viga 2 WCAG: kui avada "vaata lähemalt" lingi alt eksamitulemus, siis peaks fookuse viskama autom. avanenud sisu headingule ( nt "Esakmitulemsued 2012") või lugema ette, et ilmus uus sisu or smthng

Parandatud

> Viga 2: tunnistust ei saa alla laadida:

@EgleM-TW Kasutaja andmestik võis olla vigane, kuid enam pole kasutajaid, kus oleks eksameid küljes, ei saa testida

> UI-täiendus tablet iPad 2: tablet breakpointil on piisavalt ruumi, et "Tagasi töölauale" nupp paigutada a`la desktop ehk Eksamitulemused 2004 kõrvale @birgitpulk :

@birgitpulk

**Comment by EgleM-TW** [comment]
Ootab Birgiti tagasisidet;
Reedel 26.04 täpsustame tunnistuse alla laadimise testimist.

**Comment by heldiraudsepp** [comment]
Uued testisikud:
43304147956
30704027168
40307137664
42208117373
40303289210
43701217089
32012086675
42409176831
31411267701

**Comment by TanelTromp** [comment]
Viga 1: päring kookseb kokku, kui selle isikuga "Kutsetunnistusi" või "Eksameid hageda:

43304147956 (kasutaja EIS_43304147956, parool)

**Comment by TanelTromp** [comment]
TEST OK 
kujundajale teada antud, et saab testida 02.05.2019 kell 12:50 Skypes

Testandmed/testlugu:43304147956 (kasutaja EIS_43304147956, parool)

------------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/57068022-3ab2a500-6cd9-11e9-9b32-42680f5475fd.png)

**Comment by EgleM-TW** [comment]
Täpsustus x: jääb nii nagu väärtused meile antakse.

**Comment by priitpu** [comment]
> Viga 3: kui "%" tulemusel ei ole, siis välja mitte kuvada (alates koma kõiki maha):

See tuleb juba andmetest niimoodi. Eeldan et testandmete probleem. Ma ütleks et pole mõtet seda stringi frondis eraldi masseerima hakata. @EgleM-TW 

![image](https://user-images.githubusercontent.com/17040443/57355859-ada79a00-7177-11e9-8a52-ac6367372e40.png)

> Viga 4: päring failib: "Riigieksamid 2019" >"Vaata lähemalt"

Tehniline viga. Siia oleks vist teavitust pigem vaja. @EgleM-TW 
![image](https://user-images.githubusercontent.com/17040443/57356248-a3d26680-7178-11e9-9b40-1fc8c876ddf1.png)

**Comment by priitpu** [comment]
> Viga 4: päring failib: "Riigieksamid 2019" >"Vaata lähemalt"

Lisatud veateavitus

**Comment by Johhanna** [comment]
https://jira.twn.ee/browse/HP-83
