### ISSUE TITLE
Riigieksami tulemuste kuvamise vead

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#791]
- [ ] Riigieksami tulemuste juures "Tagasi töölauale" klikkimisel tuleb praegu oi-oi-oi (404).

Kasutaja: testija1/testija1 41103161417

**Comment by heldiraudsepp** [comment]
FE -1
Test - 1

**Comment by TanelTromp** [comment]
TEST OK

https://gyazo.com/ccb7c7fe5e477e1fdf3dadb4b819db97
