### ISSUE TITLE
Kutsetunnistuste kuvamise vead

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#792]
- [ ] Kutsetunnistuste nimistu juures tunnistuse real "vaata lähemalt" klikkides tuleb praegu oi-oi-oi (404).

Testimiseks kasutaja 39505090897; ruut/parool

**Comment by heldiraudsepp** [comment]
FE - 1
Test - 1

**Comment by TanelTromp** [comment]
TEST OK

https://gyazo.com/ca8001ae0501169b7df584b677b66d0d
