### ISSUE TITLE
Isikukaardi päringute vead

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#793]
Kõik EHIS isikukaardi päringuga seotud kohtades (isikuandmed, õpin, õpetan) tuleb praegu tehniline viga.

- [ ] Kui isikuandmed, õpin, õpetan päringu vastuses on message, siis kuvada kasutajale message välja

Testimiseks kasutaja: 47108249296; pedagoog/parool ja 35412139896 õppejõud/parool

**Comment by heldiraudsepp** [comment]
FE -1
Test - 1

**Comment by TanelTromp** [comment]
TEST OK

error: {message_type: "ERROR", message_text: {et: "Isiku kohta andmeid ei leitud."}}

![pilt](https://user-images.githubusercontent.com/37407917/54805349-5f9a0e00-4c7f-11e9-8aad-03230fae4c2f.png)

![pilt](https://user-images.githubusercontent.com/37407917/54805366-6cb6fd00-4c7f-11e9-8b98-fe788627fc02.png)

![pilt](https://user-images.githubusercontent.com/37407917/54805377-7476a180-4c7f-11e9-8344-9e0c8d4633f4.png)

![pilt](https://user-images.githubusercontent.com/37407917/54805416-8fe1ac80-4c7f-11e9-9898-fabc677f6967.png)
