### ISSUE TITLE
Mobiil-id sisselogimine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#794]
**Üldkirjeldus**
Kasutaja logib Mobiil-id abil portaali sisse, õnnestunud sisse logimisel kuvatakse kasutajale töölauda.

**Eeltingimused ja käivitamine**
* Mobiil-id on seadistatud #786
* Kasutaja vajutab menüü-ülalribal "mehikese" ikoonile.
* Kasutaja valib "Sisene Mobiil ID-ga".
* Kasutaja sisestab mobiiltelefoni numbri (Vt all vahesammud).
* Sisse logimise õnnestumisel kuvame töölauda.
* Ebaõnnestunud sisselogimisel (tehniline viga) kuvame veateadet, aga selle realiseerimine ja testimine #509 raames.

Salvestada sessiooni-võti.

**Viited:**
Disain: https://zpl.io/bzNjL0X  ja mobiilis: https://zpl.io/bLPn31Q Märkus: ik puudub autentimisel
Siin on kõik variandid märgitud (vt #786 ). Kui mõni autentimise variant on sisuhalduses märkimata siis seda ei kuvata, kui määratud on 2 varianti siis kuvada need kõrvuti. Ühe variandi kuvamisel paigutada keskele.

Vahesammud: https://zpl.io/aR17kre ja mobiilis: https://zpl.io/a7OB3yj

**Back-end töö:** #330
**Seadistamine:** #786

**Meelespea:**
username/ password sisselogimise variant peab alles jääma arenduskeskkonda, seda on tarvis testimiseks.

**Comment by TanelTromp** [comment]
Viga 1 IE 11: ei kuva logimise ikooni:

![pilt](https://user-images.githubusercontent.com/37407917/54019356-ad008080-4193-11e9-81d1-e5848e376c0a.png)

**Comment by priitpu** [comment]
> Viga/vaja täpsustada 2: vahemodaal ei vasta kujundusele (ridade vahed; bold state; tekstid jmv):

Parandatud

> Viga 3: kui kasutaja on sisseloginud, peab jääma "roheline plönn" indikeerima, et kasutaja on sisse loginud

Parandatud, kuid IEs on asukoht veidi nihu.

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Kasutaja logib Mobiil-id abil portaali sisse, õnnestunud sisse logimisel kuvatakse kasutajale töölauda
- [ ] Mobiil-id on seadistatud #786
- [ ] Kasutaja vajutab menüü-ülalribal "mehikese" ikoonile.
- [ ] Kasutaja valib "Sisene Mobiil ID-ga".
- [ ] Kasutaja sisestab mobiiltelefoni numbri (Vt all vahesammud).
- [ ] Sisse logimise õnnestumisel kuvame töölauda.

https://gyazo.com/aebf18e12ae107deb70e3b78abd45799
