### ISSUE TITLE
Erialade võrdluses kuvatavate andmete muudatus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#796]
**Eesmärk**
Seoses muudatusega eriala detailandmete kuvamisel #412, muuta ka erialade võrdlust.

**Vastuvõtutingimused**
Eemaldada võrdlusest andmeelemendid:
-- Akrediteerimise otsus - accreditationStatus
-- Akrediteerimise otsuse kehtivuse lõpp - accreditationValidUntil
Eelnev töö: võrdluse kuvamisel #153

**Comment by madispold** [comment]
Testimisse

**Comment by TanelTromp** [comment]
TEST OK

![pilt](https://user-images.githubusercontent.com/37407917/56723008-ce6ff880-6750-11e9-9ea7-2e5c57392fb3.png)

![pilt](https://user-images.githubusercontent.com/37407917/56723085-f65f5c00-6750-11e9-82b5-cea2a3cb87b5.png)
