### ISSUE TITLE
"Sarnaste erialade" kuvamine katki eriala detailvaates

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#799]
Ei kuva "sarnaseid erialasid".

https://gyazo.com/2bddb81418ec82b3b71a1531d929af00

**Comment by lsoonvald** [comment]
Too mõni näide ka, milline õppekava peaks sobima sarnaseks.
http://htm.twn.ee/erialad/ajakirjandus
http://htm.twn.ee/erialad/ajakirjandus-0
Ei ole nt sarnased kui vaatad sarnasuse arvutamise osa siin: https://github.com/hariduspilv/haridusportaal/issues/154

Sarnasuse määra arvutamine: Sarnasus määratakse sarnasuspunktide alusel. Mida rohkem sarnasuspunkte õppekava saab, seda sarnasem see on.
-- sama omistatav kraadi või diplom (degreeOrDiplomaAwarded) annab 3 punkti
-- iga kattuv kvalifikatsiooni standard (qualificationStandard) annab 3 punkti
-- õppekava maht ka kuidagi siis tuua
-- sama õppetase (level) annab 2 punkti
-- iga kattuv amet (ESCO occupation) annab 1 punkti

**Comment by TanelTromp** [comment]
Viga 1: sarnaste erialade puudumisel ei käitu süsteem ühtselt. "Ajakirjandus" eriala juures, ei kuva teksti, et "Sarnased erialad puuduvad":

Ok näide:
https://gyazo.com/f0f642166cabbaeec99cff8586dcee55

NOK näide:
https://gyazo.com/2bddb81418ec82b3b71a1531d929af00

**Comment by andrussarv** [comment]
Vastavalt #154-le kuvatakse sarnaste hulgas need, millel on sama:
-- tüüp (type)
-- sama ISCED-F õppekavarühm (ISCEDFdetailedField) või sama nimetus (name) ja
-- vähemalt üks kattuv õppekeel (teachingLanguage)

Punktide alusel arvutatav sarnasuse määr peab mõjutama ainult seda, millises järjekorras kuvatakse eelnevate tunnuste alusel valitud sarnaseid.

**Comment by TanelTromp** [comment]
Viga 1 korduv: Endilset ei ku kuvata teavitust, et "Sarnased erialad puuduvad":

NOK näide:
http://htm.twn.ee/erialad/3d-modelleerija-visualiseerija?displayRelated=true
https://gyazo.com/f56b15601bd01e6d1f340ed2c891eb27

Ok näide:
https://gyazo.com/f0f642166cabbaeec99cff8586dcee55

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
Viga 1: ei tööta sarnased erialad mudel leidmine vastavalt #154 , kui eriala on "CAPS LOCKis". Testlood:
http://htm.twn.ee/erialad/autodiagnostik-0?displayRelated=true
http://htm.twn.ee/erialad/abikokk-15?displayRelated=true
http://htm.twn.ee/erialad/autotehnik-autoelektroonika-spetsialist?displayRelated=true
etc
@lsoonvald

**Comment by lsoonvald** [comment]
Viga 1: Korras.

**Comment by TanelTromp** [comment]
TEST OK

v.a erijuhtum, kus nimetuse järgi leiab väga imelikke "sarnaseid" erialasid:
http://htm.twn.ee/erialad/autotehnik-autoelektroonika-spetsialist?displayRelated=true
