### ISSUE TITLE
Arhitektuuridokumendi valideerimine ja täiendamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#80]
- Täiendada arhitektuuridokumenti vastavalt 14.03 koosolekule
- Lahtised küsimused: Kafka ja Docker

**Comment by EgleM-TW** [comment]
21.03 arhitektuuri-koosolekul otsustati jätkata esialgse arhitektuurilise lahendusega. 
Arhitektuuridokument vormistatakse Wikis pakkumuses käsitletud ulatuses ja täiendatakse detailanalüüsi ja arendustööde käigus. https://github.com/hariduspilv/haridusportaal/wiki#arhitektuur
1. Rajadokumendi (liidesed) täiendamiseks tuleb iga liidese raliseerimisel see dokumenteerida ka Wikis järgmises ulatuses:
Lühikirjeldus: ...
Tüüp: X-tee teenus/ sünkroonne/ asünkronne
Vastaspool: ...
Kasutatud protokoll: ...
Liidese dokumentatsioon: link

2. Komponentide üle vaatamine ja täpsustamine tuleb planeerida II ja IV etapi analüüsitöödes.
