### ISSUE TITLE
Linkide kuvamine GraphInfoText väljal

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#801]
Linkide kuvamine (GraphInfoText) väljal:
Testitud näide: http://htm.twn.ee/ametialad/kaamen. Selles näites sisutekstiväljal on lingid korrektsed, kuid graafikuga seotud tekstiväljal mitte - mõlemal juhul esimene tekstisisene link on sisemine ja teine väline.

Kui sisuhalduses on link määratud avanema uues aknas siis peab kuvama välise lingina, kus ikoon on lingi järel ja joon lingi alla tekib alles hiirega lingile liikudes.

**Comment by heldiraudsepp** [comment]
FE - 
Test - 2h

**Comment by TanelTromp** [comment]
TEST

VÕiks teha selle pileti raames 1: UTF-8, täpitähti ei kuva õigesti:
![pilt](https://user-images.githubusercontent.com/37407917/54980152-ac4a5580-4fad-11e9-8f8d-1223d9a61bd6.png)
http://htm.twn.ee/ametialad/beeta-ametiala-pikk-50-t%C3%A4hem%C3%A4rki-eksju

**Comment by priitpu** [comment]
See on sisuhaldusega seotud, sest kui ise panna õiged täpitähed, siis ka FE-s kõik õige

![image](https://user-images.githubusercontent.com/17040443/55087890-798a8500-50b3-11e9-9467-81fdea24f685.png)

**Comment by TanelTromp** [comment]
Viga täpsustus: kui sisuhalduses lingile nime ei anna, siis täpitähtedega link on katki:

https://gyazo.com/10a3cd3c68ea225a06205fe06293da31

Fe says @lsoonvald

**Comment by lsoonvald** [comment]
Drupali Core, ei ole soovitatav ümber kirjutama hakata. @TanelTromp

**Comment by TanelTromp** [comment]
TEST OK

Paneme kasutsujuhendisse eraldi kirja, et soovitatav on nimetus anda, kui tegemist on täpitähtdega, siis iseäranis.
