### ISSUE TITLE
Nimekirja vaates kuvatavate objektide arv ja Lae rohkem

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#802]
Eesmärk:
Portaalis esitatud nimekirja vaadetes kuvatakse vaikimisi 24 objekti ning nupp Lae rohkem kuvatakse üksnes siis kui objektide arv on üle 24 (Kui ei ole rohkem laadida, siis CTA-d ei kuva). Lae rohkem avab kasutajale järgmised 24 objekti.

Vastuvõtutingimused:
Muuta all loetletud nimekirja vaadetes vaikimisi kuvatavate objektide arv 24-le (hetkel 5)
Muuta Lae rohkem nupust avatav loend 24-le (hetkel 5).

Nimekirja vaated:

- Uudised
- Sündmused (nimekiri)
- Õppeasutused (asukohad)
- Õppeasutuse vaates selle õppeasutusega seotud erialade nimistu
- OSKA ametialad
- Erialad

**Comment by heldiraudsepp** [comment]
FE - 3h
Test - 3h

**Comment by TanelTromp** [comment]
Viga 1: tellija soov oli, et kui naased mistahes detailvaatest, siis viib kasutaja skrolliga samasse kohta/kõrgusele, kust ta nimekiri vaatest detailvaaatesse lahkus.

**Comment by skeefee** [comment]
Viga 1: Korras
Viga 2: Kindlasti korras!
UX t'iendus 2: Korras

**Comment by TanelTromp** [comment]
TEST OK

Muuta Lae rohkem nupust avatav loend 24-le (hetkel 5).

Nimekirja vaated:

- [ ]     Uudised
- [ ]     Sündmused (nimekiri)
- [ ]     Õppeasutused (asukohad)
- [ ]     Õppeasutuse vaates selle õppeasutusega seotud erialade nimistu
- [ ]     OSKA ametialad
- [ ]     Erialad
