### ISSUE TITLE
Isikuaart "Õpin","Õpetan", "Isikuandmed"; "Kutsetunnistused" testimine uute saadud andmetega

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#803]
Seotud piletid:
https://github.com/hariduspilv/haridusportaal/issues/439 - "Õpetan" sakk
https://github.com/hariduspilv/haridusportaal/issues/433 - "Õpin" sakk
https://github.com/hariduspilv/haridusportaal/issues/444 - "Isikuandmed"
#383 - "kutsetunnistused"

Testandmed login:
taneltromp
parool

Viga 1: „Tagasi töölauale“ link katki:

https://gyazo.com/3d29fedcb6f3a0994608bc6013135f79

Viga 4: „Vaata lähemalt“ font on liiga väike ja ei vasta Zeplinile:

![pilt.png](https://images.zenhubusercontent.com/5ab8a6294b5806bc2bcc56d1/2c93bd23-b6ef-4be9-8ff5-280d59d53073)

Viga 5: kõik lahtrid peavad olemas 50/50 jaotusega (eelmises testide raames kokku lepitud ja Birgit proofinud), hetkel 66/33; 50/50 ja erinevaid ning „Vaata lähemalt“ peaks ka olema keskele joondatud. 

![pilt.png](https://images.zenhubusercontent.com/5ab8a6294b5806bc2bcc56d1/c9c833ed-6d27-4d91-835b-b1e20b64528b)

Viga 6: poolikus aknas vaade katki:

![pilt](https://user-images.githubusercontent.com/37407917/54373316-b3a46180-4685-11e9-80b3-f920208d157c.png)

Viga 7: sildid ei ole konverditud ja osa andmeid on puudu.

![pilt](https://user-images.githubusercontent.com/37407917/54414315-67970280-4701-11e9-8630-f7503716c90c.png)

![pilt](https://user-images.githubusercontent.com/37407917/54694474-f5735300-4b30-11e9-8b5e-66c52481a2eb.png)

<img width="1637" alt="Capture" src="https://user-images.githubusercontent.com/37407917/54414497-0459a000-4702-11e9-9c48-8cdccc0923ab.PNG">

Viga 8: "Kutsetunnistused" all sama teema, mis "viga 4" ja viga 5":

![pilt](https://user-images.githubusercontent.com/37407917/54687424-32851880-4b24-11e9-9bbe-4664633d02a0.png)

Viga 9: puudu "Sulge" nupp modaalilt

![pilt](https://user-images.githubusercontent.com/37407917/54825462-4c566500-4cb6-11e9-97d2-1b0c05948116.png)

**Comment by erkkijakobson** [comment]
_Täiendkoolituse_ asemele läbivalt korrektne termin **Täienduskoolitus**

**Comment by priitpu** [comment]
> Viga 1: „Tagasi töölauale“ link katki:

Tagasi töölauale linke detailvaates enam ei kuvata. OK

> Viga 5: kõik lahtrid peavad olemas 50/50 jaotusega (eelmises testide raames kokku lepitud ja Birgit proofinud), hetkel 66/33; 50/50 ja erinevaid ning „Vaata lähemalt“ peaks ka olema keskele joondatud.

OK

> Viga 6: poolikus aknas vaade katki

Tagasi töölauale linke enam ei kuvata. OK

> Viga 7: sildid ei ole konverditud ja osa andmeid on puudu.

Sildid konverditud. OK
Puuduolevad andmed: #444 "Kui mingil andmeelemendil pole väärtust, siis detailvaatel seda andmeelementi ei kuva (silti ka mitte)."

> Viga 8: "Kutsetunnistused" all sama teema, mis "viga 4" ja viga 5":

OK

> Viga 9: puudu "Sulge" nupp modaalilt

OK

**Comment by TanelTromp** [comment]
Viga 10 uus: ei lae enam "sündmuste" plokki üles ja element katki, juhul:
https://gyazo.com/f239e4a5fa73be1505ed18d09a7f1eed
