### ISSUE TITLE
Ametiala ja valdkonna paremas-veerus link nimistule

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#811]
Eesmärk:
1. Ametiala sisutüübil (MainProfessionPage) kuvatakse paremas veerus alati blokki "Leia kiiresti", kus automaatselt on lisatud lingid:
- ametialade nimistu lehele
- ametialade graafilise võrdluse sisulehele (nimistu teine vaheleht "Andmed")

2. Valdkonna sisutüübil (FieldPage) kuvatakse paremas veerus alati blokki "Leia kiiresti", kus automaatselt on lisatud lingid:
- valdkondade nimistu lehele
- valdkondade graafilise võrdluse sisulehele (nimistu teine vaheleht "Andmed")

Eeltingimused:
- loodud on valdkondade graafilise võrdluse sisuleht #821 ja #822 
- loodud on ametialade graafilise võrdluse sisuleht #828 ja #829 
_Me ei testi olukorda, kus neid sisulehti pole loodud ja link viib 404 lehele._

Vastuvõtutingimused:

Ametiala sisutüübil (MainProfessionPage) ja valdkonna sisutüübil (FieldPage) kuvatakse alati paremas veerus blokki "Leia kiiresti", kus esimesena (enne sisuhalduri käsitisi lisatud linke) kuvatakse automaatselt linke, mis avavad vastava sisulehele vahelehe:
- ametiala sisutüübil (MainProfessionPage):
→ link ametialade nimistule, lingi tekst "Kõik ametialad"
→ link ametialade graafilise võrdluse sisulehele, lingi tekst "Ametialade andmed"

_Esimene link avab ametialade nimistu vahelehe ja teine võrdluse vahelehe._

- valdkonna sisutüübil (FieldPage)
→ link valdkondade nimistule, lingi tekst "Kõik valdkonnad"
→ link valdkondade graafilisele võrdlusele, lingi tekst "Valdkondade andmed"

_Esimene link avab valdkondade ruudustiku vahelehe ja teine andmete vahelehe._
_Kõikidel linkidel siselingi loogika._

Lisaks:
- Ametialade võrdluse lehel (siis kui kasutaja on lisanud ametialasid võrdlusesse - kas ametialade nimistu lehel, ametiala detailvaatest või valdkonna lehelt), eemaldada link "Tagasi ametialade nimekirja vaatesse"

**Comment by RainLeoma** [comment]
Sobib:

Ma lisasin #822 juures kommentaari, et valdkondade lehtedel peaks olema link, mis automaatselt viib võrdluse lehele.

**Comment by TanelTromp** [comment]
uus pilet EHIS2-99
