### ISSUE TITLE
Õppekavade filtreerimise päringud

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#812]
**Seoses taksonoomiate ja impordi uuendamisega on vajalik front-endis täiendada õppekavade filtreerimise päringuid, nõuded samad, mis #148 :** 
-- Õppevaldkond - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF, kõige üldised). Süsteem otsib õppekavad, mille õppevaldkond (ISCEDFbroadField) võrdub valikuga.
-- Õppesuund - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF keskmine tase; saab valida eelnevalt valitud valdkonna alla kuuluvate suundade hulgast). Süsteem otsib õppekavad, mille suund (ISCEDFnarrowField) võrdub valikuga.
-- Õppekavarühm - Kasutaja valib otsitava taseme taksonoomiast (ISCEDF kõige detailsem tase, ; saab valida eelnevalt valitud suuna alla kuuluvate õppekavarühmade hulgast, multivalik). Süsteem otsib õppekavad, mille õppekavarühm (ISCEDFdetailedField) võrdub valikuga.

BE töö #798

**Comment by heldiraudsepp** [comment]
Kui valmis, sii skohe live liigutada

**Comment by EgleM-TW** [comment]
Testitud ikkagi CSV vastu - OK.
