### ISSUE TITLE
Isikukaardi päringu väärtuste teisendamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#816]
Eesmärk: Sisseloginud kasutaja töölaual kuvatavate väärtuste kasutajasõbralikumaks muutmine.

Isikukaart

1. Täiendada andmete kuvamist töölaua isikuandmetes (algne töö #444 ).
Kui EHIS päringu vastuses on ehis:kood väärtus, siis teisendada see alltoodud ehis:nimetus väärtuseks:

* Õppelaenuõiguslikkus - oppelaenOigus - oigus, Põhjus - pohjus (n põhjust, mis jaotub eraldi ridadele)
Õigus kuvatakse alati välja (nt kui õigus = "jah" ning põhjuse väli on tühi, siis see õiguse "Jah" kuvatakse välja.

            <ehis:kood>OPPELAEN_OIGUS_PUUDUB_EESTI_KODAKONDSUS</ehis:kood>
            <ehis:nimetus>* Puudub Eesti kodakondsus või pikaajaline elamisluba</ehis:nimetus>
      
            <ehis:kood>OPPELAEN_OIGUS_OPPEKAVA_NOMINAALKESTVUS_9</ehis:kood>
            <ehis:nimetus>* Õppekava nominaalkestus peab olema vähemalt 9 kuud</ehis:nimetus>
      
            <ehis:kood>OPPELAEN_OIGUS_AKADEEMILINE_PUHKUS</ehis:kood>
            <ehis:nimetus>* Akadeemilisel puhkusel ei ole õppelaenu taotlemise
                õigust
          
            <ehis:kood>OPPELAEN_OIGUS_OPPELAEN</ehis:kood>
            <ehis:nimetus>* Õppelaenu võtmise korrad on kasutatud</ehis:nimetus>
        
            <ehis:kood>OPPELAEN_OIGUS_OSAKOORMUS</ehis:kood>
            <ehis:nimetus>* Õppimine osakoormusega või eksternina</ehis:nimetus>
       
            <ehis:kood>OPPELAEN_OIGUS_MUU</ehis:kood>
            <ehis:nimetus>* Muu põhjus. Küsi täpsemalt ehis.tugi@hm.ee</ehis:nimetus>

2. Täiendada andmete kuvamist töölaua "Õpin" sakis (algne töö #433).
Kui EHIS päringu vastuses on ehis:kood väärtus, siis teisendada see alltoodud ehis:nimetus väärtuseks:

* Akadeemiline puhkus - akadPuhkus (n arv) (Nimetus - nimetus, Alguskuupäev - algusKp, Lõppkuupäev - loppKp)

            <ehis:kood>AKAD_PUHKUS_OMAL_SOOVIL</ehis:kood>
            <ehis:nimetus>Omal soovil</ehis:nimetus>
       
            <ehis:kood>AKAD_PUHKUS_TERVIS</ehis:kood>
            <ehis:nimetus>Tervislikel põhjustel</ehis:nimetus>
        
            <ehis:kood>AKAD_PUHKUS_KAITSEVAE</ehis:kood>
            <ehis:nimetus>Kaitseväeteenistuse puhul</ehis:nimetus>
        
            <ehis:kood>AKAD_PUHKUS_LAPSEHOOLDUS</ehis:kood>
            <ehis:nimetus>Lapse hooldamiseks</ehis:nimetus>
        
* Staatus - staatus  
       
            <ehis:kood>OPIB_HETKEL</ehis:kood>
           <ehis:nimetus>Õpib hetkel</ehis:nimetus>
        
            <ehis:kood>LOPETANUD</ehis:kood>
            <ehis:nimetus>Lõpetanud</ehis:nimetus>
      
            <ehis:kood>VALJA_ARVATUD</ehis:kood>
            <ehis:nimetus>Välja arvatud</ehis:nimetus>
      
            <ehis:kood>REORGANISEERIMINE</ehis:kood>
            <ehis:nimetus>Õppeasutuse ümberkorraldamine või reorganiseerimine</ehis:nimetus>
      
            <ehis:kood>KATKESTANUD</ehis:kood>
            <ehis:nimetus>Katkestanud</ehis:nimetus>

* Ennistamine - ennistamine (n arv) (Nimetus - nimetus, Alguskuupäev - algusKp, Lõppkuupäev - loppKp)
        
            <ehis:kood>ENNISTAMINE</ehis:kood>
            <ehis:nimetus>Ennistamine</ehis:nimetus>
       
            <ehis:kood>KATKESTAMINE</ehis:kood>
            <ehis:nimetus>Katkestamine</ehis:nimetus>

* Boolean väärtuste teisendused:
  
            <ehis:kood>0</ehis:kood>
            <ehis:nimetus>Ei</ehis:nimetus>
 
            <ehis:kood>1</ehis:kood>
            <ehis:nimetus>Jah</ehis:nimetus>
 
* Haridustase - haridustase
      
            <ehis:kood>YLIKOOL</ehis:kood>
            <ehis:nimetus>Kõrgharidus</ehis:nimetus>
       
            <ehis:kood>KUTSEKOOL</ehis:kood>
            <ehis:nimetus>Kutseharidus</ehis:nimetus>
       
            <ehis:kood>POHIKOOL</ehis:kood>
            <ehis:nimetus>Üldharidus</ehis:nimetus>
        
            <ehis:kood>ALUSKOOL</ehis:kood>
            <ehis:nimetus>Alusharidus</ehis:nimetus>
       
            <ehis:kood>HUVIKOOL</ehis:kood>
            <ehis:nimetus>Huviharidus</ehis:nimetus>

* Õpetan sakis akordion Täiendkoolitus muuta "Täienduskoolitus".
        
Kutsetunnistused

Kui päringu vastuses on väljal  "Ametite (ISCO) klassifikaator - isco" mitu vastet, siis alates numbrist kuvada eraldi real üksteise all - vt all testimise näide.
_Valdkond väli jääb nii nagu register andmed väljastab._

![pilt](https://user-images.githubusercontent.com/37407917/54688838-19319b80-4b27-11e9-8c24-8dae844250d7.png)

![pilt](https://user-images.githubusercontent.com/37407917/54688990-5bf37380-4b27-11e9-92fd-af11621cc1a3.png)

**Comment by heldiraudsepp** [comment]
FE - Sprint 27 3h
Test - 2h

**Comment by priitpu** [comment]
> Täiendada andmete kuvamist töölaua isikuandmetes

> Täiendada andmete kuvamist töölaua "Õpin" sakis 

Puuduolevad andmed on asendatud lootusega. Vajab testimist pärisandmetega.

> Kui päringu vastuses on väljal "Ametite (ISCO) klassifikaator - isco" mitu vastet, siis alates numbrist kuvada eraldi real üksteise all 

Tehtud

**Comment by TanelTromp** [comment]
TEST

- [x] Õppelaenuõiguslikkus - oppelaenOigus - oigus, Põhjus - pohjus (n põhjust, mis jaotub eraldi ridadele)
Õigus kuvatakse alati välja (nt kui õigus = "jah" ning põhjuse väli on tühi, siis see õiguse "Jah" kuvatakse välja. **Olemas andmed ainult "Jah" versioonis.**

![pilt](https://user-images.githubusercontent.com/37407917/55389007-124e5400-553d-11e9-863c-d44cf89617eb.png)
