### ISSUE TITLE
Sisulehe "artikkel" kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#82]
**Üldkirjeldus:**
Kuvada "artikli" mallile vastav sisuleht

**Eeltingimused:**
Tehtud sisulehe toimetamine https://github.com/hariduspilv/haridusportaal/issues/18

**Vastuvõtutingimused/põhiprotsessid?:**
- Lingile "Avaleht" järgnevad menüüs sisuleheni viivate menüüpunktide nimed  - MenuItem.title
- Artikli pealkiri, sissejuhatus, pilt (võib puududa), sisu - SimpleArticlePage

**Täiendavad tingimused:**
- Link jäljereal "Avaleht" - viib portaali avalehele.

**Kasutajaliidese eskiis:**
https://6aofpb.axshare.com/#g=1&p=artikkel_lg (NB! pildi suurus lg ja md murdepunktidel)

**Comment by erkkijakobson** [comment]
Eskiisilehtede nimedes kasutada numbriliste väärtuste asemel murdepunkte: xs, sm, md, lg, xl
https://github.com/angular/flex-layout/wiki/Responsive-API#mediaqueries-and-aliases
