### ISSUE TITLE
Valdkondade võrdluse sisutüübi toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#821]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada OSKA valdkondade võrdlemise „FieldComaprisonPage“ mallil sisulehte.

Seda sisulehte luuaks üks ja sellel on kindel asukoht (ei ole leitav menüüst), seda kuvatakse valdkondade nimistu vaatest võrdluse vahelehel - vt disaini siit: https://zpl.io/VOkO6B1.

**Eeltingimused ja käivitamine:**
- Kasutajal on OSKA sisuhalduri õigused.
- Kasutaja on OSKA sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- toimetada lehe sisu (vt sisulehe elemendid)
- avaldada sisulehte

**Sisulehe elemendid:**
- pealkiri (title), kohustuslik, maksimaalne pikkus 100
- sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- dünaamiline infograafika (n arv), vabatahtlik, Dünaamiline infograafika sisaldab kõiki graafiku tüüpe ja infoteksti (GraphInfoText) välja koos WYSIWYG redaktoriga.

_Parema veeru elemente lehele ei lisata ja leht on samas mõõdus valdkondade ruudustikuga._
   
**Viited:**
kuvamine: #822
nimkirja vaates disain: https://zpl.io/VOkO6B1; detailvaate disaini ei looda.

**Comment by TanelTromp** [comment]
Test - 2h

**Comment by heldiraudsepp** [comment]
BE - 3h
Test - 2h

**Comment by lsoonvald** [comment]
Loodud päring oskaFieldComparisonPage

**Comment by TanelTromp** [comment]
Viga 1: puuduvad õigused vastavat sisulehte luua:

![pilt](https://user-images.githubusercontent.com/37407917/55803413-f1f53b00-5ae2-11e9-9f67-31e4d2b7a28c.png)

Eeltingimused ja käivitamine:
    Kasutajal on OSKA sisuhalduri õigused.
    Kasutaja on OSKA sisuhaldurina sisse loginud.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Eeltingimused ja käivitamine:
Kasutajal on OSKA sisuhalduri õigused.
Kasutaja on OSKA sisuhaldurina sisse loginud.

Vastuvõtukriteeriumid:

- [x] Sisuhaldur saab:
toimetada lehe sisu (vt sisulehe elemendid)
avaldada sisulehte

Sisulehe elemendid:

- [ ] pealkiri (title), kohustuslik, maksimaalne pikkus 100
- [ ] sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- [ ] dünaamiline infograafika (n arv), vabatahtlik, Dünaamiline infograafika sisaldab kõiki graafiku tüüpe ja infoteksti (GraphInfoText) välja koos WYSIWYG redaktoriga.

---------------------------

![pilt](https://user-images.githubusercontent.com/37407917/55812140-135e2300-5af3-11e9-8c1f-d31fdbfbaa8b.png)
