### ISSUE TITLE
Valdkondade võrdluse sisutüübi kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#822]
**Eesmärk, üldtingimused:**
Portaali külastaja saab valdkondade nimistu vaatest navigeerida OSKA valdkondade võrdluse „FieldComparisonPage“ mallil sisulehele (vaheleht) ja tutvuda selle sisuga.

**Eeltingimused ja käivitamine:**
- realiseeritud on pilet #821 (sisu toimetamine)
- kasutaja navigeerib valdkondade nimistu "Valdkonnad" vaatest infograafikaga "Andmed" vahelehele.

**Vastuvõtutingimused:**
- Nimistu vaates kuvatakse vahelehe märki "Andmed" (vt disaini: https://zpl.io/VOkO6B1), kasutaja saab navigeerida sellele vahelehele.
- Kasutajale kuvatakse lehekülje sisu (kirjledatud BE piletis #821 ja disaini viited all).
   - Kui sisulehele on lisatud dünaamiline infograafika siis kuvamine ilma infotekstiväljata (infotekstiväljale sisestatud teksti välja ei kuva).
- Kasutaja saab navigeerida "Andmed" vahelelehelt "Valdkonnad" lehele.

Viited:
BE: #821 
Disain:
- desktop: https://zpl.io/aRxo3jp
- tahvel: https://zpl.io/2ZrPGw4
- mobiilis: https://zpl.io/amd1qrr

**Comment by RainLeoma** [comment]
Sobib

Lisaks juurde, et kõikide valdkondade lehtedel peaks olema link, mis viitab sisulehele (automaatselt lisatud).

**Comment by heldiraudsepp** [comment]
FE - 
Test - 4h

**Comment by EgleM-TW** [comment]
Tõlgime URL nimetuse http://htm.twn.ee/valdkonnad?view=compare → /valdkonnad-andmed

**Comment by TanelTromp** [comment]
Viga 1 WCAG: "Ruudustik" elemendile liikudes, ütleb ekraaniluger "clickable apps ruudustik" tabulateerides ja nooltega liikudes: "clickable apps". Peaks olema /et keelevalikuga pigem midagi "clickable ruudustik vaade - selected" kui on valitud ja "clickable andmed vaade". 

Viga 2 WCAG: kui vahetad ruudustik>andmed vaadet, siis peab ekraaniluger ka ütlema, et vaade on vahetunud ja viskama ka nt kohe headingule "Siin saab võrrelda...."



ja võrdluse elemendile liikudes "clickable comapre arrows". Peaks olema

**Comment by priitpu** [comment]
> Tõlgime URL nimetuse http://htm.twn.ee/valdkonnad?view=compare → /valdkonnad-andmed
Kui liikuda Andmed vahelehelt uuesti Valdkonnad lehele, siis URL jääb ikka /valdkonnad (hetkel /valdkonnad?view=list)

Hetkel sai tehtud ümber, et on /valdkonnad ja /valdkonnad/andmed, kuna on mõningas kohas tehtud sarnaselt x/võrdlus jms.

> Viga 1: vaate loogika ei klapi Zepliniga, puudu on UI-s "Pealkiri" väli ja selle asemel on "kirjeldus" pealkirjana (vasakul alati Zeplin):

Parandatud

> Viga 2: vaade "Title" vale, on "Valdkonnad", Zeplinis on; "Valdkondade võrdlus":
Egle: @priitpu @TanelTromp Paneme tüübiks "Valdkondade andmed" See muutus planeerimisel ja disainis jäi muudatus tegemata.

Parandatud

> Viga 3: graafiku filtrite, pealkirja ja tulpade vahed ei klapi Zepliniga (vasakul alati zeplin):

Graafiku osas me ei kontrolli/saa kontrollida neid asju

> Viga 1 WCAG: "Ruudustik" elemendile liikudes, ütleb ekraaniluger "clickable apps ruudustik" tabulateerides ja nooltega liikudes: "clickable apps". Peaks olema /et keelevalikuga pigem midagi "clickable ruudustik vaade" + selected vms. kui on valitud ja "clickable andmed vaade". +võrdluse "Andmed" elemendile liikudes ütleb hetkel: "clickable comapre arrows", peaks samuti olema sama loogika järgi arusaadavalt lahendatud.

Parandatud, teavitab et "Ruudustik vaade, tab" ja "Andmed vaade, tab".
> Viga 2 WCAG: kui vahetad ruudustik>andmed vaadet, siis peab ekraaniluger ka ütlema, et vaade on vahetunud a`la "selected" ja viskama ka nt kohe headingule "Siin saab võrrelda...."
Madis vast oskab aidata.

Andmed lehele liikudes teavitab "Valdkondade andmed"

**Comment by TanelTromp** [comment]
UI-probleem 1: pikk sõna headingus ei mahu ära vaatesse:

![pilt](https://user-images.githubusercontent.com/37407917/56739603-c0819e00-6777-11e9-9c97-d554f98ffd3c.png)

**Comment by priitpu** [comment]
> Viga 4 uus: Zeplinis ssissejuhatuse teksti font weight 500, UI-s 400. Peab olema 500.

Parandatud

> Viga 3 WCAG: (rääkida vajadusel Madisega) - headingud ei tohiks olla tabulateeritavad, ainult ekraanilgueriga nooltega liikudes, peab saama tabada. Hetkel on Andmete all heading tabulateeritav:
"Majandus- ja Kommunikatsiooniministeerium valdkondade võrdlus valdkondade võrdlus valdkondade võrdl"

Parandatud

> Viga 4 WCAG: järjekord vale, kui valid "andmed" tabi, siis järgmine positsioon peab olema tabulateerides "näitaja väli". Ekraanilugeriga "Valdkondade andmed". Hetkel hüppab pärast "andmed" valimist jäljereale(breadcrumibsile)

@madispold mingid anomaaliad, äkki sul on rohkem tarkust

> Viga 5 WCAG: NVDA-ga ei juhtu "andmed" valides midagi (st ei karju nagu VO-ga) ja lisaks kui seal taabis olles liikuda nooltega, siis jätab "Valdkondade andmed" vahele ja liigub kohe headingule.(rääkida vajadusel Madisega, kuidas NVDA-ga tööle saab ja kuidas ta NVDA-ga testib)

Headingule liikumine on loogiline järjestus, kuna tuleb struktuuris järgmisena. @madispold kas tuleks kuidagi teistmoodi teha?

**Comment by TanelTromp** [comment]
Viga 1 BE: kui sisselogida admin õigustega kasutajaga (nt mina), siis kuvab kõigi kolme sisu, millest kaks avaladamata, andmeid kasutajaliidesest: @lsoonvald 

https://gyazo.com/4d0fb9c9becdb8c952b80c02ac9a4f1a

**Comment by madispold** [comment]
Viga 4 WCAG, Viga 5 WCAG: Viib fookuse aktiivsele tabile, mille silt on saki pealkiri - loeb ette.

**Comment by birgitpulk** [comment]
- [ ] "Valdkondade andmed" pealkiri peaks olema joondatud keskele mobiilsetes vaadetes
- [ ] Kas on võimalik filtri ja graafiku vahe väiksemaks teha? Hetkel on graafiku ja sellele järgneva järgmise graafiku vahe pisem kui graafiku ja tema juurde kuuluva filtri vahe
- [ ] Kas oleks võimalik graafikuid kõikides vaadetes kus neid on rakendatud käsitleda nii nagu nad oleksid tabelid? ehk siis et nad muutuvad kitsamates vaadetes keritavaks (hetkel kaovad nurga taha ära)

**Comment by lsoonvald** [comment]
Viga 1: Korras.

**Comment by priitpu** [comment]
> Kas on võimalik filtri ja graafiku vahe väiksemaks teha?

Mina mõistlikut varianti ei näe. Võib-olla oskab @skeefee midagi öelda.

> Kas oleks võimalik graafikuid kõikides vaadetes, kus neid on rakendatud, käsitleda nii nagu nad oleksid tabelid? ehk siis et nad muutuvad kitsamates vaadetes keritavaks (hetkel kaovad nurga taha ära)

Graafiku laius tekitatakse kuvamise ajal olevast ekraanisuurusest.

**Comment by EgleM-TW** [comment]
https://jira.twn.ee/browse/EHIS2-30
