### ISSUE TITLE
Lisada dünaamiline infograafika kõikidele oska sisutüüpidele

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#823]
Eesmärk
Kõikidel OSKA sisutüüpidel — valdkond, ametiala, tööjõuprognoos ja tulemused — kuvatakse interaktiivset infograafikat. 

BE:
Lisada dünaamiliste graafikute loomise võimalus järgmistele oska sisutüüpidele (hetkel lisatud üksnes ametiala (MainProfessionPage) sisutüübile):

- valdkonna sisutüüp (FieldPage)
- tööjõuprognoosi siutüüp (SurveyPage)
- tulemused sisutüüp (ResultPage)?

FE:
Kuvada sisuhalduses loodud dünaamilisi graafikuid (sh GraphInfoText väli) järgmistel oska sisutüüpidel:

- valdkonna sisutüüp (FieldPage)
- tööjõuprognoosi siutüüp (SurveyPage)
- tulemused sisutüüp (ResultPage)

**Comment by TanelTromp** [comment]
Test: 4h

**Comment by lsoonvald** [comment]
BE tehtud

**Comment by TanelTromp** [comment]
TEST OK


- [x] valdkonna sisutüüp (FieldPage)
https://gyazo.com/5adae48f5adcf5b4147d16edc11d3f32

- [x] tööjõuprognoosi siutüüp (SurveyPage)
https://gyazo.com/1d91304d8be1ba4ad8477b1eec641dcb

- [x] tulemused sisutüüp (ResultPage)
https://gyazo.com/47cd1068c65416cedbe6fba661f07e83
