### ISSUE TITLE
Mobiili päis+ otsing mobiilis+sisselogimise modaal mobiilis

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#824]
Sisselogimise disain: https://zpl.io/bLPn31Q
Otsing: https://zpl.io/VDBd3dW

**Comment by heldiraudsepp** [comment]
@birgitpulk kuidas kuvada kui otsitulemusi ei leitud ja kui leitakse? vastuste kuvamise disain

**Comment by TanelTromp** [comment]
UX-täiendus 1: tahaks veidi õhku alla saada, sest "Sisene Mobiil ID-ga" juures "Sisene" nupp jääb avanenud keypadi taha peitu:

![pilt](https://user-images.githubusercontent.com/37407917/56580889-6ac4be80-65dc-11e9-8ed1-a743134c6f98.png)

**Comment by madispold** [comment]
UX-täiendus 1: OK.

UX-täpsustus 1: @birgitpulk otsustada. Modaali suuruse kohta nii palju, et taustal lahtise otsingu vaate kontekstis väike, kuid tegelikkuses täpselt sama suur kui logimise modaal...

**Comment by birgitpulk** [comment]
UX-täpsutsus 1:
a: ei tahaks nii teha, võiks avaneda ikka modaal nagu praegu
b: jätame luubi alles päisesse

UX-täpsustus 1: las jääb nii nagu on

**Comment by madispold** [comment]
Siis kõigele OK. @TanelTromp

**Comment by TanelTromp** [comment]
TEST OK

--------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/56731305-dc2e7980-6762-11e9-8ad8-543499523dd7.png)

![pilt](https://user-images.githubusercontent.com/37407917/56731433-1e57bb00-6763-11e9-9581-509aa83049d4.png)
