### ISSUE TITLE
Avalehe kolmas kujundus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#825]
Eesmärk: realiseerida uue kujundusega portaali avaleht.

Uue kujundusega avalehel saab:
- tellida uudiskirja, lisandus uus funktsionaalsus, kus kasutaja saab märkida kõik teemad korraga valituks, sellesks on märkeruut "Vali kõik".
- tellida RSS voogu 
- kuvatakse 3 uudist, saab liikuda uudise detailvaatesse, saab avada uudistega lehekülje (link Vaata kõiki)
- kuvatakse 3 sündmust, saab liikude sündmuse detailvaatesse, saab avada sündmuste lehekülje (link Vaata kõiki)
- kui on sisestatud üks "super uudis" siis kuvatakse seda esimese bloki  ja uudiste vahel, kui ühtegi superuudist pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
- kui on sisestatud kaks "super uudist" siis kuvatakse teine päevakajaline teema uudiste ja sündmuste blokkide vahel, kui teist "superuudist" pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
- kui esimeses blokis on sisuhalduses lisatud link, siis see peab avanema.

Disaini lingid:
Desktop: https://zpl.io/VQBdLeW
Tahvel: https://zpl.io/VxLQDYk
Mobiil: https://zpl.io/VKPQAqP

**Comment by madispold** [comment]
TEST: OK.

**Comment by TanelTromp** [comment]
Viga 1:"Loe rohkem"; mitte "Näita rohkem" (Vt Zep)

Viga 2: "Loe rohkem" ja teksti vahele vahe nagu Zeplinis

**Comment by birgitpulk** [comment]
- [ ] Mobiilis ja tahvlis võiks need esimeste blokkide mummud olla värvilised, lingi tekstil ikka joon all.

**Comment by madispold** [comment]
Viga 1: OK
Viga 1: OK
Viga 1: OK
v

**Comment by TanelTromp** [comment]
WCAG viga 4 korduv NVDA: peale "vali kõik" checkboxi valiku linnukese tegemist ei ütle, et "checked"

Täpsustus WCAG 1 koruv: kui tuleb kiri, et "Tänud haridusteemade vastu huvi tundmast", siis loeb selle ette ka "alert" - ei tohiks.

**Comment by madispold** [comment]
WCAG Viga 4: Kuna valib ka paralleelselt x arv teisi märkeruute, siis NVDA ei oska käituda.
WCAG 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

- [ ] tellida uudiskirja, lisandus uus funktsionaalsus, kus kasutaja saab märkida kõik teemad korraga valituks, sellesks on märkeruut "Vali kõik".
- [ ] tellida RSS voogu
- [ ] kuvatakse 3 uudist, saab liikuda uudise detailvaatesse, saab avada uudistega lehekülje (link Vaata kõiki)
- [ ] kuvatakse 3 sündmust, saab liikude sündmuse detailvaatesse, saab avada sündmuste lehekülje (link Vaata kõiki)
- [ ] kui on sisestatud üks "super uudis" siis kuvatakse seda esimese bloki ja uudiste vahel, kui ühtegi superuudist pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
 - [ ] kui on sisestatud kaks "super uudist" siis kuvatakse teine päevakajaline teema uudiste ja sündmuste blokkide vahel, kui teist "superuudist" pole sisestatud, siis lehekülje alumised osad liiguvad üles poole (ei jää auku).
- [ ] kui esimeses blokis on sisuhalduses lisatud link, siis see peab avanema.
