### ISSUE TITLE
Lehte haldab HTM koos partneritega lisada vasakmenüüsse

### ISSUE THREAD

**Issue by birgitpulk** [hariduspilv/haridusportaal#826]
Lisada tekst "Lehte haldab Haridus- ja Teadusministeerium koos partneritega" versiooninr alla, vahe versiooninumbriga 24px, tekst 14px, Light, mõlemad teksti toonid (nii versiooni nr kui ka HTM tekst) #757575 ja asetus joondatud vasakmenüüs ekraani alaserva.

**Comment by birgitpulk** [comment]
![Screenshot 2019-03-25 at 16.43.35.png](https://images.zenhubusercontent.com/5af048384b5806bc2bd2095b/420073c2-9641-4c01-94dc-e516962e06e8)

**Comment by birgitpulk** [comment]
![Screenshot 2019-03-25 at 16.44.11.png](https://images.zenhubusercontent.com/5af048384b5806bc2bd2095b/fc248692-957d-42cb-be55-ff391c5c687c)

**Comment by heldiraudsepp** [comment]
FE - 1h
Test - 1h

**Comment by madispold** [comment]
TEST: OK.

**Comment by TanelTromp** [comment]
TEST OK

![pilt](https://user-images.githubusercontent.com/37407917/56664285-86999480-66b0-11e9-8088-b40f9f6ad75e.png)
