### ISSUE TITLE
Front-end täiendamised

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#827]
Disaini teema lisaarenduste raames ja teine on pug:

1. Disaini ühtlustamine (#753 raames):
Kui erialad on lisatud võrdlusesse, siis erialade võrdluse lehelt eemaldada nupp "Tagasi"

2. Erialade nimistu (õppekavad), nimekirja ja detailvaates ei kuvata välja nominaalkestust kui
nominaalKestusAastad" : 0, samas "nominaalKestusKuud" väärtus on olemas. 
Andmed kuvatakse välja üksnes võrdluse vaates.

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
TEST OK

- [x] Disaini ühtlustamine (#753 raames):
Kui erialad on lisatud võrdlusesse, siis erialade võrdluse lehelt eemaldada nupp "Tagasi"

- [x] Erialade nimistu (õppekavad), nimekirja ja detailvaates ei kuvata välja nominaalkestust kui
nominaalKestusAastad" : 0, samas "nominaalKestusKuud" väärtus on olemas.
Andmed kuvatakse välja üksnes võrdluse vaates.

--------------------------
Kuvatõmmised
![pilt](https://user-images.githubusercontent.com/37407917/56738426-43552980-6775-11e9-9b8a-91182672161c.png)

![pilt](https://user-images.githubusercontent.com/37407917/56738438-4f40eb80-6775-11e9-9d33-1c84b6c3fd17.png)
