### ISSUE TITLE
Ametialade graafilise võrdluse sisutüübi toimetamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#828]
**Eesmärk, üldkirjeldus:**
Sisuhalduses saab luua ja toimetada OSKA ametialade võrdlemise „ProfessionComaprisonPage“ mallil sisulehte. 

Seda sisulehte luuaks üks ja sellel on kindel asukoht (ei ole leitav menüüst), seda kuvatakse ametialade nimistu vaatest võrdluse vahelehel.

**Eeltingimused ja käivitamine:**
- Kasutajal on OSKA sisuhalduri õigused.
- Kasutaja on OSKA sisuhaldurina sisse loginud.

**Vastuvõtukriteeriumid:**
Sisuhaldur saab:
- toimetada lehe sisu (vt sisulehe elemendid)
- avaldada sisulehte

**Sisulehe elemendid:**
- pealkiri (title), kohustuslik, maksimaalne pikkus 100
- sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
- dünaamiline infograafika (n arv), vabatahtlik, Dünaamiline infograafika sisaldab kõiki graafiku tüüpe ja infoteksti (GraphInfoText) välja koos WYSIWYG redaktoriga.

_Parema veeru elemente lehele ei lisata ja leht on samas mõõdus valdkondade ruudustikuga._
   
**Viited:**
kuvamine: #829

**Comment by heldiraudsepp** [comment]
BE - 3h
Test - 2h

**Comment by TanelTromp** [comment]
Viga 1: palun lisada õigus sisuhaldurile/kasutajale külge: "sisuhaldurtanelile"

**Comment by lsoonvald** [comment]
Viga 1: Juba on OSKA sisuhalduse õigus küljes ning saad lisada ka lehte.

**Comment by TanelTromp** [comment]
TEST OK

- [ ] Eeltingimusedja käivitamine:
Kasutajal on OSKA sisuhalduri õigused.
Kasutaja on OSKA sisuhaldurina sisse loginud.

- [ ] Vastuvõtukriteeriumid
Sisuhaldur saab:
toimetada lehe sisu (vt sisulehe elemendid)
avaldada sisulehte

- [ ] Sisulehe elemendid:
pealkiri (title), kohustuslik, maksimaalne pikkus 100
sissejuhatav tekst (introduction), vabatahtlik, maksimaalne pikkus 300, plain-text
dünaamiline infograafika (n arv), vabatahtlik, Dünaamiline infograafika sisaldab kõiki graafiku tüüpe ja infoteksti (GraphInfoText) välja koos WYSIWYG redaktoriga.

---------------------

![pilt](https://user-images.githubusercontent.com/37407917/55879997-84abdd80-5ba8-11e9-8960-572e264a0f22.png)
