### ISSUE TITLE
Ametialade graafilise võrdluse sisutüübi kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#829]
**Eesmärk, üldtingimused:**
Portaali külastaja saab ametialade nimekirjast navigeerida OSKA ametialade graafilise võrdluse „ProfessionComaprisonPage“  mallil sisulehele ja tutvuda selle sisuga.

**Eeltingimused ja käivitamine:**
- realiseeritud on pilet #828 (sisu toimetamine)
- kasutaja navigeerib ametialade nimistu  "Ametialad" vaatest "Andmed" vahelehele.

**Vastuvõtutingimused:**
- Lisada ametialade nimistu vaatesse vahelehed - "Ametialad" ja "Andmed" (Nimekirja märki vt Õppeasutused nimkiri ja Andmed märki vt https://zpl.io/VOkO6B1). 
- Kasutaja saab ametialade nimekirja vaatest navigeerida "Andmed" vahelehele. 
- Kasutajale kuvatakse lehekülje sisu (kõik komponendid on varasamelt lahendatud) ja kirjeldatud BE piletis #828 .
- Kui sisulehele on lisatud dünaamiline infograafika koos infotekstiväljaga, siis siis kuvamine ilma infotekstiväljata.
- Kasutaja saab navigeerida "Andmed" vahelelehelt nimekirjaga lehele.

Viited:
BE: #828 
Disaini eraldi pole loodud, kasutada valdkondade võrdluse disaini:

- desktop: https://zpl.io/aRxo3jp
- tahvel: https://zpl.io/2ZrPGw4
- mobiilis: https://zpl.io/amd1qrr

**Comment by heldiraudsepp** [comment]
FE - 
Test - 4h

**Comment by EgleM-TW** [comment]
@priitpu Tõlgime URL nimetuse /ametialad-andmed

**Comment by EgleM-TW** [comment]
@priitpu ja @TanelTromp, sisulehe tüübiks on "Ametialade andmed"

**Comment by EgleM-TW** [comment]
https://jira.twn.ee/browse/EHIS2-93
