### ISSUE TITLE
Testimise nõuete kirjeldamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#83]
Raamlepingu nõuete täpsustamine. 
Töötada nõuded läbi ja esialgne praktiline plaan/selgitus, kuidas seda GitHub-is teha. 
Läbi katsetada projekti keskkonnas ja teha kokkulepe.
6.15 ei ole selle töö osa, etapp III
Siin on ka punktid 8.1-8.3

**Comment by TanelTromp** [comment]
[Vearaporteerimine-näide.docx](https://github.com/hariduspilv/haridusportaal/files/1854972/Vearaporteerimine-naide.docx)

**Comment by TanelTromp** [comment]
[Vearaporteerimine-näide.docx](https://github.com/hariduspilv/haridusportaal/files/1859227/Vearaporteerimine-naide.docx)

**Comment by MirellKr2** [comment]
**1. Punkt 6.1 Testimise aluseks võetakse ärianalüüs, nõuded ja neile vastavad detailanalüüsi dokumendid (kasutajalood, aktsepteerimise kriteeriumid).**

Viited dokumentidele:
1.	Eelanalüüs: https://github.com/hariduspilv/haridusportaal/wiki/0.-Eelanal%C3%BC%C3%BCs
2.	Arhitektuuridokument: https://github.com/hariduspilv/haridusportaal/wiki#arhitektuur
3.	Haridusportaali raamleping: https://trinidadconsultingou.sharepoint.com/TWN-Projektid/Shared%20Documents/HTM%20Haridusportaal/HD%20ja%20raamleping/haridusportaali-raamleping.pdf
4.	Detailanalüüsi piletid: https://github.com/hariduspilv/haridusportaal/issues

Kasutuslugusid eraldi ei looda vaid on kirjeldatud analüüsi issue-des kasutaja tegevustena. Aktsepteerimise kriteeriumid on kirjeldatud analüüsi issue-s.

**2. Punkt 6.2 Tulemite kvaliteedi kontrolli planeerimiseks tuleb koostada testiplaan. Testiplaani mall lepitakse kokku enne tööde alustamist.**  

Testiplaan kirjeldatakse GitHub-is wiki lehena. Testiplaani mall lepitakse kokku enne tööde alustamist.

**3. Punkt 6.6 Kõik põhiprotsessid peavad olema kaetud testlugudega. Ülejäänud funktsionaalsused peavad olema kaetud automaattestidega.**  

Põhiprotsessid on kirjeldatud analüüsi issue-dena.

**4. Punkt 6.8.1 Testilugude koostamisel lepib tellija täitjaga kokku testilugude struktuuri.**  

Testilood kirjeldatatakse GitHub-is koos tellijaga kinnitatud formaadis.

**5. Punkt 6.8.10 Testiloos kirjeldatud testisammud peavad olema eraldi läbitavad ning hinnangu sammu edukusele peab saama anda igale testsammule eraldi;**  

Igale testisammule kirjeldatakse oodatav väljund selle edukuse hindamiseks.  

**6. Punkt 6.9.1 Kõik funktsionaalsete nõuete kontrollimiseks loodud testilugude läbimise tulemused tuleb kanda funktsionaalsete nõuete testimise tulemuse alla.** 

Testiloos peab olema kirjas, kas testitakse funktsionaalset või mittefunktsionaalset nõuet. Analüüsi issue-d peavad hõlmama ka mittefunktsionaalseid nõudeid (kirjeldatud täiendavate nõuetena).

**7. Punkt 6.11.1 Kasutajaliidese funktsionaalsus (sh liidestumine teiste süsteemidega) tuleb katta automaattestidega.**

Kinnitada tarkvara (Ghostlab, Selenium) kasutajaliidese automaatseks testimiseks. Kirjeldada vahendid testplaanis.

**Comment by TanelTromp** [comment]
[Vearaporteerimine-näide.docx](https://github.com/hariduspilv/haridusportaal/files/1859970/Vearaporteerimine-naide.docx)
