### ISSUE TITLE
Lisada valdkonna sisutüübile väli "Hõive muutus"

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#831]
1. OSKA valdkonna sisutüübilt (FiledPage) eemaldada väli "Hõivatute arvu tekst".

2. Lisada eelneva välja asemele väli "Hõive muutus", kus kasutajal on valikud:
- Suur kasv (id = 1)
- Väike kasv (id = 2)
- Jääb samaks (id = 3)
- Väike kahanemine (id = 4)
- Suur kahanemine (id = 5)
Front-endile väljastada id, mille järgi ikooni kuvatakse.

Viited: FE #832

**Comment by RainLeoma** [comment]
Sobib

**Comment by heldiraudsepp** [comment]
BE - 1
Test - 1
