### ISSUE TITLE
Kuvada valdkonna sisutüübil hõive muutust

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#832]
Eesmärk:
OSKA valdkonna sisutüübil (FiledPage) kuvatakse sisuhaldusest lisatud hõive muutust.

Vastuvõtutingimused:
Muuta piletis #751 kirjeldatud reegleid järgmiselt:

- Uus pealkiri _Faktid_ ja selle järel tekst _Hõivatute arv:_ ning sisuhalduses sisestatud väärtus
- Kui numbrilist väärtust pole sisestatud, siis andmeid välja ei kuva.
- Ikooni kuvamine: Reeglid jäävad samaks, mis #751 kirjeldatud hõivatute arvu väärtuste tabelis.
- Hõive arvu illustreeriva mehikestega ikooni järel kuvada _Hõive muutus:_ ja ikoon koos tekstiga järgmiselt:

ikooni id | Ikoonil noole värv ja suund | Kuvatav tekst
-- | -- | --
1 | Rohekas nool otse üles | Suur kasv
2 | Rohekas nool paremale viltu üles | Väike kasv
3 | Oranž nool horisontaalselt   paremale | Jääb samaks
4 | Punakas nool viltu alla | Väike kahanemine
5 | Punakas nool otse alla | Suur kahanemine

See on sarnane ametialade paremas veerus andmete kuvamisele, kuid sellel sisutüübil sisuhaldur sisestab andmed käsitsi.
Disaini eraldi ei loo, näide komponendist: https://zpl.io/V41Wg1M

Viited: BE #831

**Comment by RainLeoma** [comment]
Sobib

**Comment by heldiraudsepp** [comment]
FE - 5h
Disaini test - 1h
Test - 4h

**Comment by priitpu** [comment]
![image](https://user-images.githubusercontent.com/17040443/56201129-e8bb1f80-6048-11e9-8cf1-0839c578e546.png)

**Comment by TanelTromp** [comment]
Täiendus WCAG 1: "hõivatute arv: 10000" ja "Hõive muutus: Suur kasv" võiks olla samasugused elemendid ehk lugeda koos kooloniga ja koos. Hetkel on "Hõive muutus" ja "Suur kasv" kaks eraldi elementi millele saab liikuda aga parem lahendus on "Hõivatute arv: 10 000" üks element ja üks lugemine.("Hõive muutus" taha ei loe hetkel koolonit - kui selle saab lisada ja on kergem kiirem tee, siis piisaks ka selleks, kui loeks: "Hõive muutus:" > "Suur kasv"

**Comment by EgleM-TW** [comment]
Täiendus WCAG 1: Ei saa, sest ei ole kohustuslik mõlemat välja täita.

**Comment by priitpu** [comment]
> Viga 1: tingimus ei ole täidetud: Kui numbrilist väärtust pole sisestatud, siis andmeid välja ei kuva.
Kuvab osa andmeid välja ka, kui numbriline väärtus on sisuhaldusest sisestama. Peaks terve "Faktid" kasti kaotama.

OK, kui hõivatute arvu pole, siis hõive muutust ei näita(isegi kui mingil imejuhtumil olemas peaks olema).

> Täiendus WCAG 1: "hõivatute arv: 10000" ja "Hõive muutus: Suur kasv" võiks olla samasugused elemendid ehk lugeda koos kooloniga ja koos. Hetkel on "Hõive muutus" ja "Suur kasv" kaks eraldi elementi millele saab liikuda aga parem lahendus on "Hõivatute arv: 10 000" üks element ja üks lugemine.("Hõive muutus" taha ei loe hetkel koolonit - kui selle saab lisada ja on kergem kiirem tee, siis piisaks ka selleks, kui loeks: "Hõive muutus:" > "Suur kasv"

OK?

**Comment by TanelTromp** [comment]
TEST OK


- [ ] Uus pealkiri Faktid ja selle järel tekst Hõivatute arv: ning sisuhalduses sisestatud väärtus
- [ ] Kui numbrilist väärtust pole sisestatud, siis andmeid välja ei kuva.
- [ ] Ikooni kuvamine: Reeglid jäävad samaks, mis #751 kirjeldatud hõivatute arvu väärtuste tabelis.
- [ ] Hõive arvu illustreeriva mehikestega ikooni järel kuvada Hõive muutus koos vastava ikooniga

-------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/56370675-55c6e480-6204-11e9-899d-9f2cade2cdc5.png)

![pilt](https://user-images.githubusercontent.com/37407917/56370798-90308180-6204-11e9-8f17-87d8b1c78a29.png)
