### ISSUE TITLE
Nimekirja vaadetes meelde jätmine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#833]
Nimekirja vaatest brauseri "Back" nupuga tagasi liikumisel peaks kasutaja tagasi jõudma vaatesse, kus on meelde jäetud asukoht, kust ta enne edasi liikus: filter kehtib, kasutaja keritakse lehel õigesse kohta. 

Kui kasutaja liigub jäljeriba kaudu tagasi, siis kuvatakse talle konkreetse valitud nimekirja algvaade.

**Comment by heldiraudsepp** [comment]
Lahendatud https://jira.twn.ee/browse/HP-57
