### ISSUE TITLE
Õppekavade uuendamise selgitus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#836]
Vastavalt piletile #145 peaks 

Kui EHIS-st ei saadud portaalis oleva EHIS_id väärtusega võrduva oppekavaKood väärtusega õppekava kirjet või EHIS-st saadud kirjes andmeelemendi vastuvott väärtus on "Vastuvõttu ei toimu, õppimine keelatud", siis süsteem võtab portaalis õppekava kirjest maha avaldamise märke (omistab published = 'false').

Testitud drupalis olevad õppekavad faili vastu: http://enda.ehis.ee/avaandmed/rest/oppekavad/-/-/OK_LIIK_KUTSE/1/JSON
500-se ja suurema kogumahutavusega laeva vahitüürimees
129297 - vaste olemas
129257 - vaste olemas
130698 - vaste puudub
130697 - vaste puudub

Selgitada põhjus ja tehtagu korda.

**Comment by lsoonvald** [comment]
Täiendasin unpublishimise loogikat. Panin arenduses uuesti töö käima, nüüd pani aegunud andmed avaldamata seisu.
