### ISSUE TITLE
Infograafika testimise lahendamised

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#837]
Selle pileti raames lahendame kliendi testimisel ilmnenud puudusi ja täeindusi:

1. Numbrite kuvamine stacked100% graafikutel: http://htm.twn.ee/ametialad/raini-csv-testimised
Võtta maha 100-ga jagamine stacked100% graafikutel (column ja bar).

Nr 1 on OK.
***
2. Väärtuste uuendamisel CSV-s ja importimisel andmed ei uuene graafikutel: http://htm.twn.ee/ametialad/raini-csv-testimised.
Algsed andmed: Sugu;Ehitus;arhitekt;mehed;700
Muudetud andmed: Sugu;Ehitus;arhitekt;mehed;750

Algsed andmed: Vanus;Ehitus;arhitekt;alla 30; 300
Muudetud andmed: Vanus;Ehitus;arhitekt;alla 30; 350

Välja kuvab 700 ja 300
Oodatud tulemus: kui muudeti ainult väärtusi, siis sisuhalduses midagi tegema ei pea ja sisulehe uuesti laadmisel on väärtused uuenenud.

Nr 2 on ok.
***
3. Lisada õhuvahe x-teljele (kirje ja telje vahele)
4. Muuta legend kahe-realiseks

Nr 3 ja 4 ei saa lahendada
***
Nr 5 Päringu vastuses on väärtus (alavaldkond), mida sisuhaldusest pole määratud - raporteeritud Slackis testitud prelive keskkonnas.

Nr 5 on Testkeskkonnas testides OK, Prlives viga kordub.
***
Nr 6 telgedel väärtuste kuvamine:
Kui graafiku tüüp on line, stacked column, stacked bar, clustered bar või clustered column (ehk kõik tüübid peale stacked100%) ja sisuhaldusest on ühikuks määratud %, siis peab jääma 100-ga jagamine jõusse, kuna google automaatselt korrutab 100-ga. 

Nr 6 - ühiku % määramine sisuhaldusest maha.

**Comment by EgleM-TW** [comment]
Testitud: http://htm.twn.ee/ametialad/raini-csv-testimised
CSV: CSV_Statistika_rainilt-4
OK - numbrite kuvamine stack100% graafikutel korras.

**Comment by EgleM-TW** [comment]
2. Testitud: http://htm.twn.ee/ametialad/raini-csv-testimised
CSV: CSV_Statistika_rainilt-4

- Algsed andmed: Sugu;Ehitus;arhitekt;mehed;750
- Muudetud andmed: Sugu;Ehitus;arhitekt;mehed;650
- Algsed andmed: Vanus;Ehitus;arhitekt;alla 30; 350
- Muudetud andmed: Vanus;Ehitus;arhitekt;alla 30; 250

Test OK.

**Comment by EgleM-TW** [comment]
3. Lisada õhuvahe x-teljele (kirje ja telje vahele)
4. Muuta legend kahe-realiseks
testitud variante ja disaini otsus: jääb nii nagu on.

**Comment by skeefee** [comment]
3. Ei saa lisada kuna see õhuvahe sõltub teksti pikkusest
4. ei teinud midagi seega korras

**Comment by EgleM-TW** [comment]
Testitud testkeskkonnas: http://htm.twn.ee/ametialad/valdkondade-v%C3%B5rdlemine
OK.
