### ISSUE TITLE
Töökeskkondade seadistamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#84]
Arendus - lokaalis
Testkeskkond - Märt paneb püsti.

----
Prelive - HTM, vastuvõtutestid seal. Seda praegu (sprint1) püsti ei pane.

**Comment by markoleppik** [comment]
Taotlus x-tee serveri ülesse seadmiseks saadetud.  Taotlust protsessitakse ca 5 päeva
