### ISSUE TITLE
Lisada navigatsiooni loomise juhised peakasutaja kasutusjuhendisse

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#840]
Lisada navigatsiooni loomise juhised peakasutaja kasutusjuhendisse.

**Comment by TanelTromp** [comment]
Tehtud!

**Comment by EgleM-TW** [comment]
https://github.com/hariduspilv/haridusportaal/blob/master/docs/kasutusjuhend_peakasutajale-ver3.pdf
