### ISSUE TITLE
Sisulehe laadimise probleemid

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#841]
Lahendamist vajavad:
1. Live keskkonnas: https://haridusportaal.edu.ee/ametialad
→ Ei kuva midagi ehk "Otsingutulemused puuduvad".
→ oodatav tulemus: avaldatud ametialad kuvatakse vaikimisi tähestikulises järjekorras.

2. Live keskkonnas: valin ametialade filtrist (nimekiri on tühi) valdkonna Sotsiaaltöö ja valin ühe ametiala Hooldustöötaja https://haridusportaal.edu.ee/ametialad/hooldust%C3%B6%C3%B6taja, sellelt sisulehelt valin valdkonna Sotsiaaltöö https://haridusportaal.edu.ee/valdkonnad/sotsiaalt%C3%B6%C3%B6

Sama lugu otse nimekirjast valdkonna lehele liikudes: https://haridusportaal.edu.ee/valdkonnad
→ ei lae lehte tervikult, pean vajutama ctrlR.
→ oodatav tulemus: leht laeb tervikuna esimesel avamisel.

3. Live keskkonnas: https://haridusportaal.edu.ee/ametialad?oskaFieldValue=12728 Valin valdkonna, mille ametialade nimekirja kuvab, lisan võrdlusesse, valin Vaata võrdlust ja viskab lehe 404 https://haridusportaal.edu.ee/404
→ oodatav tulemus: kuvab võrdluse vaadet koos lisatud ametialade andmetega

**Comment by EgleM-TW** [comment]
Nr 2 üle testida, aga sai korda 27 sprint raames.

**Comment by heldiraudsepp** [comment]
BE - 16h
Test - 5h

**Comment by lsoonvald** [comment]
Viga 1: Parandatud sorteerimine ja filtreerimine, info Madisele edastatud, mida frontendis teha.
Viga 3: Korras.

**Comment by EgleM-TW** [comment]
@erkkijakobson ja @heldiraudsepp eemaldan bug label'i, kuna raporteeritud ametialadega seotud probleemid tulenesid filling bar lisaarendusest, millega algses realisatsioonis ei teadnud arvestada. Valdkonna sisutüübi laadimise teema lahendati väljaspool seda piletit.

**Comment by madispold** [comment]
Viga 1: FE poolt uued filtrid seotud - konkurents tööturul ei filtreeri hetkel @lsoonvald 

_Lisaks: FE poolt tähestiku järks maha võetud, kuna sorteerib ette kuvatud osa (24 kuni x) ja muudaks järjekorda igal juurde laadimisel. BE oma ei arvesta hetkel väikeste/suurte tähtedega ja kuvab valesti. @lsoonvald_

**Comment by lsoonvald** [comment]
Viga 1: Imporditud andmed, nüüd kuvab õigeid.

**Comment by TanelTromp** [comment]
Viga 4: tingimus ei ole täidetud: _oodatav tulemus: avaldatud ametialad kuvatakse vaikimisi tähestikulises järjekorras._

![pilt](https://user-images.githubusercontent.com/37407917/56562715-b1052800-65b2-11e9-8506-ee9751833c5e.png)

**Comment by lsoonvald** [comment]
Viga 4: Korras. Järgmise seisu migratsiooniga on korras ka Lives/Prelives (baasimuudatuse info adminile edasi antud)

**Comment by TanelTromp** [comment]
TEST OK

- [x] Live keskkonnas: https://haridusportaal.edu.ee/ametialad
→ Ei kuva midagi ehk "Otsingutulemused puuduvad".
oodatav tulemus: avaldatud ametialad kuvatakse vaikimisi tähestikulises järjekorras.

**Test OK:**
<Muudatus tehtud hetkel testis, lives veel ei kajastu: https://gyazo.com/714006535fcd1cbc7d37577eb878fe76


- [x] Live keskkonnas: valin ametialade filtrist (nimekiri on tühi) valdkonna Sotsiaaltöö ja valin ühe ametiala Hooldustöötaja https://haridusportaal.edu.ee/ametialad/hooldust%C3%B6%C3%B6taja, sellelt sisulehelt valin valdkonna Sotsiaaltöö https://haridusportaal.edu.ee/valdkonnad/sotsiaalt%C3%B6%C3%B6

Sama lugu otse nimekirjast valdkonna lehele liikudes: https://haridusportaal.edu.ee/valdkonnad
→ ei lae lehte tervikult, pean vajutama ctrlR.
→ oodatav tulemus: leht laeb tervikuna esimesel avamisel.

**Test OK:**
https://gyazo.com/7775c9ee3aae203dbf8ba22273f8691b


- [x] Live keskkonnas: https://haridusportaal.edu.ee/ametialad?oskaFieldValue=12728 Valin valdkonna, mille ametialade nimekirja kuvab, lisan võrdlusesse, valin Vaata võrdlust ja viskab lehe 404 https://haridusportaal.edu.ee/404
→ oodatav tulemus: kuvab võrdluse vaadet koos lisatud ametialade andmetega
