### ISSUE TITLE
Foto ja video kuvamise reeglid

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#843]
Probleem: hetkel kuvatakse videosid alati sisuteksti järel (ka siis kui fotot pole lisatud).

Muuta foto ja video kuvamise reegleid:
1. sisutüüp Artikkel
- Kui on lisatud foto, siis kuvatakse seda sissejuhatuse järel (hetkel on nii).
- Kui on lisatud foto ja video(d), siis foto kuvamine sissejuhatuse järel ja video(d) sisuteksti järel (hetkel on nii).
Uus lisanduv reegel:
- Kui fotot pole lisatud, ja on lisatud video(d), siis esimene video kuvatakse foto asemel sissejuhatuse järel ja teine sisuteksti järel.

**Sisulehel elementide järjekord:**
1. Pealkiri
2. Sissejuhatus
3. Foto; või foto puudumisel esimene video
4. Sisutekst
5. Foto puudumisel teine video; või foto olemasolul videod
6. Akordion
***
2. sisutüüp OSKA Tööjõuprognoos
- Kui on lisatud ainult foto (videosid pole), siis kuvatakse fotot sissejuhatuse järel.
- Kui on lisatud video(d), siis kuvatakse **esimest videot sissejuhatuse järel** ja teine video kõige lõpus sisuteksti järel.
- Kui on lisatud foto ja video(d), siis kuvatakse **esimest videot sissejuhatuse järel** ja teine video kõige lõpus foto ja sisuteksti järel.

**Sisulehel elementide järjekord:**
1. Pealkiri
2. Sissejuhatus
3. Esimene video; või foto kui videot pole lisatud
4. Sisutekst, lingid, failid
5. Foto; kui fotot pole siis kohe teine video
6. Teine video
7. Infograafika
8. Akordion

**Comment by heldiraudsepp** [comment]
FE - 4h
Test - 2h

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
TEST

**Sisutüüp artikkel**

- [x] Kui fotot pole lisatud ja on lisatud video(d), siis esimene video kuvatakse foto asemel sissejuhatuse järel ja teine sisuteksti järel.

**Comment by madispold** [comment]
Viga 1: Sellest tekstist mina loen välja, et foto on sisuteksti ees -

_Kui on lisatud foto ja video(d), siis kuvatakse esimest videot sissejuhatuse järel ja teine video kõige lõpus FOTO JA SISUTEKSTI järel_

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

**sisutüüp Artikkel**
- [x] Kui fotot pole lisatud, ja on lisatud video(d), siis esimene video kuvatakse foto asemel sissejuhatuse järel ja teine sisuteksti järel.

**sisutüüp OSKA Tööjõuprognoos**

- [x] Kui on lisatud ainult foto (videosid pole), siis kuvatakse fotot sissejuhatuse järel.
- [x] Kui on lisatud video(d), siis kuvatakse esimest videot sissejuhatuse järel ja teine video kõige lõpus sisuteksti järel.
- [x] Kui on lisatud foto ja video(d), siis kuvatakse esimest videot sissejuhatuse järel ja teine video kõige lõpus foto ja sisuteksti järel.

-------------------
Kuvatõmmised 

**Artikkel**

![pilt](https://user-images.githubusercontent.com/37407917/56495520-bb65ea00-64fe-11e9-8e04-c7931d7ef306.png)

**Tööjõuprognoos**

![pilt](https://user-images.githubusercontent.com/37407917/56495628-0c75de00-64ff-11e9-9c16-cb21929f1b99.png)

![pilt](https://user-images.githubusercontent.com/37407917/56495759-65de0d00-64ff-11e9-89c8-a63130021c6c.png)
