### ISSUE TITLE
OSKA kaardivaadetele andmete import

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#845]
1. Sisuhaldaja avab faili.
Fail on CSV fail, kus:
- veergude eraldaja on semikoolon ( ; ), 
- failis on päiserida (naitaja;valdkond;maakond;valdlinn;vaartus;jaotus)

2. Faili kontroll:
Faili iga rida kontrollida järgmiselt:
- kas esimeses veerus on **naitaja**: kui on väärtus, siis kas on string; kui reas on täidetud mistahes teine veerg, siis on näitaja kohustuslik;
- kas teises veerus on **valdkond**: kui on väärtus, siis kas on string; vabatahtlik;
- kas kolmandas veerus on **maakond**: kui on väärtus, siis kas on string; vabatahtlik
- kas neljandas veerus on **valdlinn**: kui on väärtus, siis kas on string; vabatahtlik
- kas viiendas veerus on **väärtus**: kui on väärtus, siis kas on string; kui reas on täidetud mistahes teine veerg, siis on väärtus kohustuslik;
- kas kuuendas veerus on **jaotus**, kui on väärtus, siis kas on arvväärtus 1 kuni 7; kui reas on täidetud mistahes teine veerg, siis on jaotus kohustuslik.

Kui ilmneb viga, siis protsess katkestada ja kuvada faili rea number ja veateade "Puudub naitaja", "Puudub väärtus", "Puudub jaotus".

3. Kui süsteemis on varem imporditud andmed, siis kirjutada need üle (vanad andmed alles ei jää).

4. Salvestada failist loetavad andmed. Faili iga rida salvestada:

- näitaja (mapIndicator) = esimese veeru väärtus
- valdkond (OSKAField) = teise veeru väärtus
- maakond (county) = kolmanda veeru väärtus
- valdlinn (localGoverment) =neljanda veeru väärtus
- väärtus (value) = viienda veeru väärtus
- jaotus (division) = kuuenda veeru väärtus

Viited:
FE: #848 
Näidis csv: SharePoint - Abimaterjalid - OSKA - CSV-d -  GEO_CSV-15.04.2019.xlsx
Lisainfo: veerg valdlinn jääb esiti tühjaks (ei arenda ka frondis) ja ei testi.

**Comment by RainLeoma** [comment]
Sobib

**Comment by heldiraudsepp** [comment]
BE - 4h
Tanel - 3h

**Comment by TanelTromp** [comment]
TEST

Viga 1: saab kirjutada ka numbrit vms ja tingimus ei ole väljadel täidetud "string": 
_kas esimeses veerus on naitaja: kui on väärtus, siis kas on string; kui reas on täidetud mistahes teine veerg, siis on näitaja kohustuslik;
kas teises veerus on valdkond: kui on väärtus, siis kas on string; vabatahtlik;
kas kolmandas veerus on maakond: kui on väärtus, siis kas on string; vabatahtlik
kas neljandas veerus on valdlinn: kui on väärtus, siis kas on string; vabatahtlik_

**Comment by lsoonvald** [comment]
Viga 1: Number võibki olla stringi sees ka.

**Comment by EgleM-TW** [comment]
Kinnitan - test ok.

**Comment by TanelTromp** [comment]
TEST OK

- [ ]     veergude eraldaja on semikoolon ( ; ),
- [ ]     failis on päiserida (naitaja;valdkond;maakond;valdlinn;vaartus;jaotus)

   Faili kontroll:
- [ ]     Faili iga rida kontrollida järgmiselt:

- [ ]     kas esimeses veerus on naitaja: kui on väärtus, siis kas on string; kui reas on täidetud mistahes teine veerg, siis on näitaja kohustuslik;
- [ ]     kas teises veerus on valdkond: kui on väärtus, siis kas on string; vabatahtlik;
- [ ]     kas kolmandas veerus on maakond: kui on väärtus, siis kas on string; vabatahtlik
- [ ]     kas neljandas veerus on valdlinn: kui on väärtus, siis kas on string; vabatahtlik
- [ ]     kas viiendas veerus on väärtus: kui on väärtus, siis kas on arvväärtus; kui reas on täidetud mistahes teine veerg, siis on väärtus kohustuslik;
- [ ]     kas kuuendas veerus on jaotus, kui on väärtus, siis kas on arvväärtus 1 kuni 7; kui reas on täidetud mistahes teine veerg, siis on jaotus kohustuslik.
- [ ] Kui ilmneb viga, siis protsess katkestada ja kuvada faili rea number ja veateade "Puudub naitaja", "Puudub väärtus", "Puudub jaotus".
