### ISSUE TITLE
OSKA näitajate kuvamine Eesti kaardil

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#848]
TÄIENEB
**Eesmärk ja taust:** 
Visualiseerida Eesti kaardil OSKA näitajad maakondade lõikes.
OSKA näitaja ja sellega seotud valdkond ning kaardil kuvatav värv on määratud sisuhalduri poolt (andmed imporditakse CSV-st #845 ).

**Eeltingimused ja käivitamine:**
- realiseeritud on pilet #845 
- kasutaja navigeerib valdkondade nimistu "Valdkonnad" vaatest kaardiga vahelehele.

**Vastuvõtutingimused:**
- Valdkonna nimistu vaates kuvatakse kaardi vahelehe märki, kasutaja saab navigeerida kaardiga vahelehele.
- Kasutajale kuvatakse lehekülje sisu:
   - filter 
   - Eesti kaart
- Vaikimisi kuvatakse CSV-st imporditud esimest näitajat ja selle näitajaga seotult esimest valdkonda.
- Kasutaja saab filtrist valida näitaja (üks korraga); valdkonna (üks korraga).
   - Kui kasutaja valib näitaja, siis valdkondade filtris kuvatakse neid valdkondi, mis on selle näitajaga seotud
   - Kui kasutaja valib valdkonna, siis näitaja filtris kuvatakse neid näitajaid, mis on selle valdkonnaga seotud.
- Kasutaja valikute järgi kuvatakse andmed
   - kui arvväärtus on väiksem kui 1, siis teisendada %-ks, nt 0,46 = 46%
   - iga haldusüksus (maakond) kuvatakse jaotuses märgitud värvitooniga.
- Kasutaja saab navigeerida Kaardi vahelelehelt nimistu "Valdkonnad" või "Andmed" vahelehele.

Viited:
Disain:
- vahelehe märk:
- vaheleht koos jvärvide ja filtriga:
BE: #845

**Comment by lsoonvald** [comment]
oskaMapData päring, muutujaid pole vaja.
