### ISSUE TITLE
Disainida OSKA näitajate kuvamine Eesti kaardil

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#849]
OSKA valdkondade ruudustiku vaatest uus vaheleht, millel kuvatakse Eesti kaarti.
Kirjeldust vaata FE piletis https://jira.twn.ee/browse/EHIS2-49

Vajalik kujundada
1. filter:

- Näitaja (saab valida ühe korraga) - ok
- Valdkond (saab valida ühe korraga) - ok
2. Eesti kaardi paigutus vahelehel (kui kasutame sama tükki, mis http://htm.twn.ee/koolide-rahastus, siis polegi tarvis) - ok
3. Näitaja väärtuste värvid. Erinevaid värve on kaardil korraga kuni 7.  - ok

**Lisada igale värvitoonile kood (nr 1-7) - lisada piletisse: https://jira.twn.ee/browse/EHIS2-49**

4. Väärtuste kuvamine kaardil. Väärtused kuvatakse üldjuhul % ja proovida, kuvamine maakonna peal.

**Kokkulepitud lahendus kirjeldada - https://jira.twn.ee/browse/EHIS2-49**

5. Vahelehe märk - ok

**Comment by heldiraudsepp** [comment]
https://jira.twn.ee/browse/EHIS2-49

**Comment by EgleM-TW** [comment]
Tulemid: https://jira.twn.ee/browse/HP-32 ja https://jira.twn.ee/browse/HP-76
