### ISSUE TITLE
Serveri nõuete kirjeldamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#85]
Kirjutada Erkkile serveri nõuded (mis tarkvara platvormi tükid + prelive riistvara nõuded), et Erkki saaks HTM poolt jhakata ette valmistama HTM keskkondasid.

**Comment by ruut12** [comment]
[https://github.com/hariduspilv/haridusportaal/wiki/Serveri-n%C3%B5uded](url)
