### ISSUE TITLE
EHISe isikukaardi vaated kolme uue testisikuga

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#850]
### Testisikud
**Testisik1**:
kasutaja: EHIS_61010220016
parool: testisik1

**Testisik2**:
kasutaja: EHIS_48707077779
parool: testisik2

**Testisik3**:
kasutaja: EHIS_50112217019
parool: testisik3

### Eesmärk
Kontrollida üle, kas kõik teenusest tulevad andmed kuvatakse välja ka kasutajaliideses
[Testisikute andmed teenusest.pdf](https://github.com/hariduspilv/haridusportaal/files/3067198/Testisikute.andmed.teenusest.pdf)

**Comment by TanelTromp** [comment]
1.	Lisada testisik1 61010220016, kes õpib hetkel kõrg- või kutsehariduses +
a.	õppelaenuõiguslikkus = Jah +
b.	kodakondsus = Eesti +
c.	täidetud on õppevormi ja õppekoormuse andmed +
d.	lisatud on õppekavatäitmise % **PUUDU**
e.	ennistamise all oleks kuvatud kirjed ehk 22 – KATKESTAMINE ja siis 43 – ENNISTAMINE     +
f.	lõpetatud ehk olemas on alus-, huvi- ja üldhariduse andmed (üldharidus on kutsealane eelkoolitus). EHIS ei tagasta lõpetatud üldh. korral kutse eelkoolituse andmeid (TestIsik3 on kutseõppe andmed ) ja lõpetatud huvihariduse andmeid (hetkel õpib huvikoolis). **PUUDU**
g.	on varem lõpetanud mõne kooli kõrg- või kutsehariduses. +
h.	töötab hetkel õppejõuna (vt soovitud variante allpool koos kvalifikatsiooni ja täiendkoolituse andmetega) (EHIS tagastab õppejõu kvalifikatsiooni ja tasemehariduse andmed) +

**Comment by priitpu** [comment]
> Viga 1 testisik3-ga:

Hetkel panin kuvama ainult õppekava nimetust, kas peaks õppekava koodi ka näitama? @birgitpulk

> Viga 2: ei saa välja logida andmete vaatamise sügavusest:

Parandatud

**Comment by EgleM-TW** [comment]
Lisame õppekava täitmise % 'otsuse kp' seisuga.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Kontrollida üle, kas kõik teenusest tulevad andmed kuvatakse välja ka kasutajaliideses
Testisikute andmed teenusest.pdf
