### ISSUE TITLE
Ametiala sisutüübil fikseeritud sildi kuvamine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#851]
Taust:
Sisuhaldur lisab taskonoomiasse "OSKA Ametiala Fikseeritud Sildid" sildi nimetuse, mida kuvatakse sisuhladuses ametiala sisutüübil ja võrdluses. Sisuhaldur valib ametiala sisulehe loomisel, millist silti soovib lisada (valikus taksonioomiast lisatud kirjed ja "puudub"). 

Vastuvõtutingimused:
Ametiala sisulehel ja võrdluses kuvatakse sisuhladusest märgitud fikseeritud silti.

Viited:
BE töö #674

**Comment by heldiraudsepp** [comment]
FE - 2h
Test - 2h

**Comment by madispold** [comment]
Testimisse!

**Comment by TanelTromp** [comment]
Viga 1: võrdluses ei mahu ära, mis teha? Nõue on "kuni 50 tähemärki pikkus":

![pilt](https://user-images.githubusercontent.com/37407917/56211855-786cc800-6061-11e9-97e5-0b0044b903e9.png)

**Comment by madispold** [comment]
Viga 1: Ma tahaks öelda, et vigane sisestus kui nii pikaks silt lisatud, kuid mis teeme? @EgleM-TW @birgitpulk

Viga 2: Lehel on ka lemmikuks lisamine ja jagamine, mida kujunduses pole siin välja toodud ning iga reas oleva elemendi vahe 16px, ma ei lükkaks silti rohkem eemale, aga @birgitpulk otsustada.

**Comment by EgleM-TW** [comment]
@lsoonvald Palun muudame klassifikatsioonis "OSKA Ametiala Fikseeritud Sildid" nimetuse 30 tähemärgile.

**Comment by EgleM-TW** [comment]
Viga 2 jätame nii nagu on ja kui tarvis siis disaini täiendused.

**Comment by lsoonvald** [comment]
Viga 1: Korras.

**Comment by TanelTromp** [comment]
TEST OK

- [x] Ametiala sisulehel ja võrdluses kuvatakse sisuhladusest märgitud fikseeritud silti.

------------
Kuvatõmmised

![pilt](https://user-images.githubusercontent.com/37407917/56503227-8026e380-651d-11e9-8632-1f8f3cd090dd.png)

![pilt](https://user-images.githubusercontent.com/37407917/56503249-96cd3a80-651d-11e9-87bd-5dacb74d1574.png)

![pilt](https://user-images.githubusercontent.com/37407917/56503270-a64c8380-651d-11e9-9576-3cb09c3c9d14.png)
