### ISSUE TITLE
Disaini täiendus palagaskaala kuvamisel

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#852]
Lisada faktide ikoonile Eesti keskmise märk: https://zpl.io/V41Wg1M

**Comment by heldiraudsepp** [comment]
FE - 2h
Test - 2h

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
Viga 1: Mozilla UHD:

![pilt](https://user-images.githubusercontent.com/37407917/56215221-f3d17800-6067-11e9-9cd1-73f2750e76b5.png)

**Comment by madispold** [comment]
Viga 1: OK.
WCAG täiendus 1: Peidetud - OK.

**Comment by TanelTromp** [comment]
Viga 1: ikka katki

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

-------------------
![pilt](https://user-images.githubusercontent.com/37407917/56340497-be896f00-61ba-11e9-85cb-3ca30ae3132e.png)

![pilt](https://user-images.githubusercontent.com/37407917/56340523-cf39e500-61ba-11e9-8faf-c7203a165852.png)
