### ISSUE TITLE
Ametialad nimekiri ja valdkonna ametialade akordionis tähestiku järjekord luua

### ISSUE THREAD

**Issue by TanelTromp** [hariduspilv/haridusportaal#854]
Nimekiri:
http://htm.twn.ee/ametialad

Akordionit näeb:
http://htm.twn.ee/valdkonnad/sotsiaalt%C3%B6%C3%B6

**Comment by heldiraudsepp** [comment]
FE - 1h
Test - 1h

**Comment by madispold** [comment]
Testimisse @TanelTromp

**Comment by TanelTromp** [comment]
TEST

Viga 1: ei ole tähestiku järjekorras akordionis:
http://htm.twn.ee/valdkonnad/transport-logistika-mootors%C3%B5idukite-m%C3%BC%C3%BCk-ja-remont

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

-----------------
Kuvatõmmised

akordion

![pilt](https://user-images.githubusercontent.com/37407917/56210188-eadba900-605d-11e9-870a-bbada1452481.png)

ametialad

![pilt](https://user-images.githubusercontent.com/37407917/56210211-faf38880-605d-11e9-8ab4-202ec1dcb952.png)
