### ISSUE TITLE
JUHANi sündmuste eemaldamine kalendrist

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#857]
Vastuvõtukriteeriumid:

- Sündmuste kalendrisse edaspidi mitte kuvada JUHANist tulevaid sündmusi 
- Eemaldada juba kalendris olevad JUHANi sündmused

**Comment by lsoonvald** [comment]
Keelatud Juhani andmete import. Kirjutatud skript Juhanist tulnud ürituste kustutamiseks. Tarnel käivitada skript.

**Comment by TanelTromp** [comment]
TEST OK


- [ ]     Sündmuste kalendrisse edaspidi mitte kuvada JUHANist tulevaid sündmusi
- [ ]     Eemaldada juba kalendris olevad JUHANi sündmused

https://github.com/hariduspilv/haridusportaal/blob/master/drupal/web/modules/custom/htm_custom_juhan_import/src/deleteJuhanEvents.php
