### ISSUE TITLE
Asutuste filtrist märkeruudud ära

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/haridusportaal#858]
Peidame FE-s ära HEV ja õpilaskodu märkeruudud, mis ei oma 1:1 filtreeritavat registriväärtust.

**Comment by heldiraudsepp** [comment]
FE - 1h
Test - 1h

**Comment by TanelTromp** [comment]
TEST OK

![pilt](https://user-images.githubusercontent.com/37407917/56132803-979d2400-5f93-11e9-8517-ff9a886d0021.png)
