### ISSUE TITLE
Erialade kuvamise täiendus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#864]
Probleem: http://htm.twn.ee/erialad?open_admission=true

Põhjus:
Klassifikaatoris tehti muudatused:

Kutseõpe keskhariduse baasil - EHIS output = 
412 kutseõpe keskhariduse baasil (vv alates 01.01.2006)
421   Teise taseme kutseõpe (vv alates 01.09.2013)
431 Kolmanda   taseme kutseõpe (vv alates 01.09.2013)
441 Neljanda   taseme kutseõppe esmaõpe (kutsekeskharidusõpe) (vv alates 01.09.2013)
442 Neljanda   taseme kutseõppe esmaõpe (vv alates 01.09.2013)
443 Neljanda   taseme kutseõppe jätkuõpe (vv alates 01.09.2013)
452 Viienda   taseme kutseõppe esmaõpe (vv alates 01.09.2013)
453 Viienda   taseme kutseõppe jätkuõpe (vv alates 01.09.2013)

Varasemlat olid alates 421 kõik eraldi kanded.
Muudatuse eesmärk on, et kasutajaliideses kuvatakse filtris üksnes "kutseõpe keskhariduse baasil", mis annab tulemuseks kõik seotud õppekavad.

Lisaks lisati uued väärtused:
Põhihariduse   nõudeta kutseõpe
Kutseõpe   põhihariduse baasil

**Comment by TanelTromp** [comment]
Täpsustus 1: valikud on rippmenüüs olemas aga vasteid veel ei ole päringus?

![pilt](https://user-images.githubusercontent.com/37407917/56217024-2df04900-606b-11e9-9171-1a680e2eeb2e.png)


Täpsustus 2: kas peaks panema samuti tähestiku järjekorda ja sama loogika, mis "ametiala" filtris?

**Comment by priitpu** [comment]
> Viga 1: päring: http://htm.twn.ee/erialad?level=2764
Annab katkised tulemused, kui võtta ära linnuke "Ainult avatud vastuvõtuga" ja teha päring uuesti - kuvab mingit "eriala ei ole aktiivne" teemat, mis lõhub rukki kõik:

Parandatud

**Comment by TanelTromp** [comment]
TEST OK

ootab Egle vastust.
