### ISSUE TITLE
VPT taotluse testimine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#865]
Testida isikuga: 
kasutaja: vpt_kasutaja1
kasutaja: vpt_kasutaja15

Hetkel mitte esitada taotlust, vaid proovida läbi sammude vahel liikumist.

**Comment by lsoonvald** [comment]
Parandatud readonly väljade väljakuvamine. Samuti parandatud salvesta ja jätka loogikat.

**Comment by EgleM-TW** [comment]
Meelespea: testimise jätkuks selgitada, mis seis on töödega: 
#650 
#658 
#654 
#652

**Comment by heldiraudsepp** [comment]
https://jira.twn.ee/browse/HP-56
