### ISSUE TITLE
Filling bar testimine

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#868]
Testida Filling bar kuvamist kõikide variantidega - vt Slack "tugi" Raini näited. Algne töö #698
Kui on vead, siis raporteerida ja lisame piletile FE arendaja, kes parandab.

**Comment by TanelTromp** [comment]
Viga 1: "raske" valiku puhul on element katki läinud poolikust aknast alates:
http://htm.twn.ee/ametialad/ajakirjanik

![pilt](https://user-images.githubusercontent.com/37407917/56661341-34557500-66aa-11e9-9c19-f40508a9945e.png)

**Comment by madispold** [comment]
Viga 1: OK.

**Comment by TanelTromp** [comment]
TEST OK

![pilt](https://user-images.githubusercontent.com/37407917/56664931-beeda280-66b1-11e9-94ec-12c12123d183.png)
