### ISSUE TITLE
OSKA vahe-avalehe toimetamise täiendus

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#869]
Täiendada #448 OSKA vahe-avalehe toimetamist:

Lisaks OSKA sisutüüpidele saab lehe keskel kaheses osas lingiks lisada Artikkel sisutüüpi lehekülge. 

Testida ka kasutajaliidest, vajadusel lisame piletile FE arendaja.

**Comment by lsoonvald** [comment]
Korras.

**Comment by TanelTromp** [comment]
Leht hetkel maas

**Comment by TanelTromp** [comment]
TEST OK

- [x] Lisaks OSKA sisutüüpidele saab lehe keskel kaheses osas lingiks lisada Artikkel sisutüüpi lehekülge.
-------------------
![pilt](https://user-images.githubusercontent.com/37407917/56485645-82694d80-64dd-11e9-9225-016f54529ce7.png)
