### ISSUE TITLE
Lehe uuendusega seotud vigade parandamine

### ISSUE THREAD

**Issue by lsoonvald** [hariduspilv/haridusportaal#873]
GraphQL uuenes, mille tõttu varasemad mutationid ei toiminud.

**Comment by lsoonvald** [comment]
Testida üle lemmikuks lisamine, üritustele registreerimine.

**Comment by TanelTromp** [comment]
Viga 1: Ei tööta sisselogimine, ei tööta ka lemmikud.
_Failed to load resource: the server responded with a status of 403 (Forbidden)__

**Comment by lsoonvald** [comment]
Sisselogimine toimib nüüd, võib proovida kõike uuesti vast.

**Comment by TanelTromp** [comment]
VIga 1: Sisselogimise puhul komponentide laadimine toimib.

Viga 2?

**Comment by lsoonvald** [comment]
Viga 2: Pigem front-endi viga jah.

**Comment by TanelTromp** [comment]
TEST OK
