### ISSUE TITLE
FE täiendused

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#875]
Hetkel:
Menüüpunkt: Tunnistuse kehtivuse kontroll
Jäljerida: Avaleht → Tunnistuse kehtivuse kontroll

Muuta:
Menüüpunkt: Riigieksami tunnistuse kehtivuse kontroll
Jäljerida: Avaleht → Riigieksami tunnistuse kehtivuse kontroll

**Comment by madispold** [comment]
OK. @TanelTromp

**Comment by TanelTromp** [comment]
TEST

UX-täiendus: Birgiti otsus, kuidas jäljerida kuvada? Hetkel pikemate puhul piirang j akuvab kolme punkti:
http://htm.twn.ee/tunnistuse-kehtivuse-kontroll
![pilt](https://user-images.githubusercontent.com/37407917/56794456-d4301180-6816-11e9-9b3a-e6b2c67d7356.png)
@birgitpulk @EgleM-TW

**Comment by birgitpulk** [comment]
@TanelTromp UX-täiendus: Kolm punkti on hea mõte, muidu läheb väga pikaks

**Comment by TanelTromp** [comment]
@EgleM-TW pileti nõue selliselt, siis ei ole hetkel täidetud.
