### ISSUE TITLE
Otsingu vead

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#876]
Kontrollida üle otsingu välja käitumine järgmistel juhtudel (sisend slacki tagasiside)

- Ei leia vasteid sõnale "eksam"
![image.png](https://images.zenhubusercontent.com/5aa632a94b5806bc2bca6673/c1ff2eb2-4e28-4022-be37-5456f4068dbc)

- Huvikooli otsing Tallinnas tulem:
![image](https://user-images.githubusercontent.com/37112899/56788806-17838380-6809-11e9-9036-0a905df61f21.png)

- Lasteaedade otsing Tallinnas
![image](https://user-images.githubusercontent.com/37112899/56788864-3aae3300-6809-11e9-970c-8c6430eb28dd.png)

- Valides harjumaa ja kooli tüübi gümnaasium, tuleb esimese viie seas välja Lilleoru põhikool (mis pole kohe täitsa kindlasti gümnaasium)
![image](https://user-images.githubusercontent.com/37112899/56788931-57e30180-6809-11e9-9aad-8961a57f0ca9.png)

- filtriga "ülikool" tulevad välja ka rakenduskõrgkoolid

**Comment by lsoonvald** [comment]
Ei leia vasteid sõnale "eksam": Korras.

Huvikooli otsing Tallinnas tulem: Peabki tulema nii, kuna tegu Tallinna maanteega aadressis.

Lasteaedade otsing Tallinnas: Peabki tulema nii, kuna tegu Tallinna maanteega aadressis.

Valides harjumaa ja kooli tüübi gümnaasium, tuleb esimese viie seas välja Lilleoru põhikool (mis pole kohe täitsa kindlasti gümnaasium): Korras.

filtriga "ülikool" tulevad välja ka rakenduskõrgkoolid: Korras.
