### ISSUE TITLE
Lähtekoodi, rakendusserveri ja andmebaasiserveri nõuete kirjeldamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#88]
Raamlepingu alusel läbi töötada. Vajadusel vastuolud välja tuua ja läbi rääkida. Konspekt kõikidele arendajatele
Siia tuleb juurde ka punkt 8.4

**Comment by egontinno** [comment]
Loodud Wiki leheküljed:

[Google koodistiili standardi lühikokkuvõte ja võimalikud vastuolud](https://github.com/hariduspilv/haridusportaal/wiki/Google-koodistiili-standardi-l%C3%BChikokkuv%C3%B5te-ja-v%C3%B5imalikud-vastuolud)

[The Twelve Factor App põhimõtteid ja võimalikud vastuolud](https://github.com/hariduspilv/haridusportaal/wiki/The-Twelve-Factor-App-p%C3%B5him%C3%B5tteid-ja-v%C3%B5imalikud-vastuolud)

**Comment by egontinno** [comment]
Loodud Wiki lehekülg:

[Changelog.md, semantiline versioneerimine ja süsteemi logimine](https://github.com/hariduspilv/haridusportaal/wiki/Changelog.md,-semantiline-versioneerimine-ja-s%C3%BCsteemi-logimine)
