### ISSUE TITLE
Liidestusnõuete kirjeldamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#89]
Vaja täpsustada  ja 5.7 on kirjutatud lahti:

- liideste testidega kaetuse nõue

Hilisemaks 5.5:
- Avaandmete avaldamine - avaldatavate andmete sisu täpsustub projekti käigus. Vaja tehniline lahendus (nt kas päringupõhine või perioodilinestaatiline üles riputamine)

- Linkandmed - kui kuskilt on mingeid andmeid võtta, siis..

**Comment by J-Air-M** [comment]
@erkkijakobson - ootan täpsustust punkti 5.7 osas, et mida silmas peeti.

**Comment by J-Air-M** [comment]
Erkki, ma lugesin seda punkti veelkord ja mul on tunne, et see on seal kirjas kui common knowledge lihtsalt.

**Comment by erkkijakobson** [comment]
Liideste testid:
välistele liidestele https://martinfowler.com/bliki/ContractTest.html
teenuste vahele https://martinfowler.com/bliki/IntegrationTest.html

Koodi testidega kaetuse kuvajad-teavitajad: [Coveralls](https://coveralls.io) või [Codecov](https://codecov.io)

**Comment by J-Air-M** [comment]
Mock on kahe teraga nuga (seda kinnitab ka esimene viidatud link). Üheltpool on lokaalne test valdavalt kiirem kui välise (kolmanda) süsteemiga. Samas on reaalne oht see, et väline süsteem muutub ja mockiga sobinud lahendus tegelikult ei toimi. Keegi peab jälgima väliste süsteemide muudatuste toimumist ja vastavalt mock'e kohendama. Leiame, et see ei ole otstarbekas tegevus ning praktika põhjal tunnistame piisavana unit ja integration testide läbiviimist. Mock kasutamine on kindlasti põhjendatud erandjuhtudel, näiteks kui väline süsteem on ajutiselt kättesaamatu või saadakse sellega suheldes konstantselt vastuseid väga suure viivitusega või on vaja kiiresti lokaalselt mingid erijuhud läbi mängida.

Konkreetselt Coveralls või Codecov osas otsest kogemust ei ole, küll aga oleme muid analoogseid vahendeid kasutanud, seega võiks midagi sarnast kenasti rakendada.

**Comment by J-Air-M** [comment]
Lisasin temaatilise lehe wikisse https://github.com/hariduspilv/haridusportaal/wiki/N%C3%B5uded-liidestele.
