### ISSUE TITLE
Kasutajaliidese testimise nõuete kirjeldamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#90]

**Comment by MirellKr2** [comment]
1)	Punktid 7.1 ja 7.2
Testimisele kuuluvad nimetatud brauserite viimased versioonid. Kuni IE 9, Android 4.4 (JS poolt toetatud).

Testimise tegevused: 
1.	Kasutajaliidese automaattestimine (tööriist Ghostlab/Selenium): brauserite ja platvormi ülene testimine
2.	Manuaalne testimine: SEO ja WCAG nõuetele vastavuse valideerimine (esmane automaatne valideerimine AChecker rakendusega). 

Testimist viiakse läbi järgmistel seadmetel: 
•	iPhone 6 (iOS)
•	Samsung Galaxy (Android)
•	Tahvel (Windows)
•	Sülearvuti (Windows, 14 tolli)

2)	Punkt 7.3

Testimise tegevused:
1.	GUI elementide olemasolu kontroll
2.	Klient-server testimine veateadete kontrollimiseks

3)	Punkt 7.4

Testimise tegevused:
1.	Testida, kas vastavalt brauseri seadistustele muutub kasutajaliidese keel.
2.	Vaadata HTTP request sõnumit kontrollimaks HTTP_ACCEPT_LANGUAGE header’i või ISO koodide olemasolu.

4)	Punkt 7.5 

Testida keele lisamist administreerimisliidesest.

5)	Punkt 7.6

Testida, et värskendamisel ei tekiks topelt tegevusi, st ei toimu topelt andmete edastamist/päringuid jm.

6)	Punkt 7.7

Testida, kas päringu tegemisel kuvatakse kasutajaliideses kasutajale teavitus.

7)	Punkt 7.8 

Testimine hõlmab:
1.	Veebilehe läbitavus TAB-iga
2.	Elementide paiknemine
3.	Korrektse koodisüntaksi kontrollimine
4.	Teavitused (veateated, teade tegevuse õnnestumise kohta)
5.	Ikoonid ja pildid

Testimise tegevused:
1.	WCAG validaator - AChecker (https://achecker.ca/checker/index.php)
2.	Manuaalne testimine
