### ISSUE TITLE
SEO lahenduse kirjeldamine

### ISSUE THREAD

**Issue by heldiraudsepp** [hariduspilv/haridusportaal#94]
Millistele nõuetele vastab esimene artikkel

**Comment by MirellKr2** [comment]
SEO nõuded:
1. Lehekülje pealkirjad ja meta kirjeldus - title tag peab olema unikaalne, peab sisaldama märksõnu ja ei tohi olla pikem kui 70 tähemärki. Meta-kirjeldus ei tohiks olla pikem kui 150 tähemärki ja peab sisaldama märksõnu.
2. Muudetav, otsingumootori sõbralik URL-i struktuur - kirjeldav URL annab kasutajatele ja otsingumootorile teavet lehe sisu kohta, ei nõua sessiooni ID-d.
3. Muudetavad lehekülje pealkirjad - igal lehel peab olema üks <h1> silt. Pealkirjade silte peab kasutama sobivalt, st õiges järjekorras. Pealkirjade tag-id peavad olema muudetavad ja unikaalsed, st automaatselt genereeritud pealkirju peab saama muutma sõltumatult iga lehe navigatsiooni menüüst.
4. Muudetavad piltide pealkirjad ja ALT tekst - pildid sisaldavad <alt> tag’i koos märksõnaga.
5. XML sitemap-i olemasolu
6. Breadcrumb-i navigatsioon
7. Lehe kiirus - server response time <500ms, server supports browser caching and file compression, supports minification of JS and CSS.
8. Integratsioon RSS-iga
9. Muudetav menüü - navigatsioon peab olema renderdatud plain HTML tekstina (lingid peavad olema klikitavad kasutajatele, kellel on JS, CSS ja cookies välja lülitatud)
10.Muudetavad kanoonilised sildid ja paginatsiooni sildid.
11. Robots.txt olemasolu - robots.txt on fail, mis võimaldab kontrollida lehekülje alasid, mida otsingumootorid saavad vaadata/indekseerida.
12. Ümbersuunamine (redirect) - SEO jaoks on parem kasutada 301 redirect-i.
13. Mobiili sõbralik (kohanduv veebileht) - lehekülgedel peab olema määratud viewport, et kohanduda vastavalt seadme suurusele. Lehe sisu peab mahtuma viewport-i.
14. AngularJS indekseerimine
15. Toetab kohandatud 404 lehte.
