### ISSUE TITLE
Uudise detailvaade

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#95]
**Üldtingimused:**
Kuvada uudise detailvaade, et portaali kasutaja saaks lugeda uudise kogu sisu.

**Eeltingimused ja käivitamine:**
Kasutaja jõuab uudise detailvaatesse:

1. Avalehelt valides uudise blokist „Loe lähemalt“ (testitakse, kui avaleht on realiseeritud)
2. Uudise nimekirjast https://github.com/hariduspilv/haridusportaal/issues/12 (testitakse, kui nimekiri on realiseeritud)
3. Mõne teise uudise detailvaatest valides "Loe veel" blokist uudise

**Vastuvõtutingimused:**

1. Kasutajale kuvatakse uudise detailvaade vastavalt uudise (News) andmetele https://github.com/hariduspilv/haridusportaal/issues/11 , vt ka testimise kommentaare ning prototüüpi!
2. Kasutajale kuvatakse "Loe veel" veerus kolm viimati avaldatud uudist (avaldamise kuupäeva järgi kõige uuemad). 

Täpsustus testimiseks:
Kui kuupäev on sisestamata, kuvatakse vaikimisi jooksvat kuupäeva.
Sisestatud kuupäeva alusel käivitub avaldamine. Portaalis kuvatakse need uudised, mille avaldamise kuupäev on minevikus. Kontrollimise aeg 00:00.

"Loe veel" blokis kuvatakse:
- pealkiri (title)
- kuupäev (date)
- sissejuhatus (shortDescription)
- "Loe lähemalt", mis avab uudise detailvaate.

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kasutajaliidese eskiis:**
https://6aofpb.axshare.com/#g=1&p=uudise_detailvaade_lg
https://6aofpb.axshare.com/#g=1&p=uudise_detailvaade_md
https://6aofpb.axshare.com/#g=1&p=uudise_detailvaade_xs

Kujundus: zpl://screen?sid=5af04a45a283fe7a7e65bf89&pid=5ae9c7f3c560dffb217da75c

**Viited seotud teemadele:**
Uudise toimetamine: #11
Uudise nimekirjavaade: #12
Uudised avalehelt: #96

Siltide toimetamine: #13
Uudise e-postile tellimine: #14

**Comment by EgleM-TW** [comment]
https://github.com/hariduspilv/haridusportaal/issues/176

**Comment by skeefee** [comment]
Korras

**Comment by EgleM-TW** [comment]
11.05 sprindi lõpetamise koosolekul disaini-otsus: Kui parem veerg pole täidetud, siis sisuosa ei muutu (ei pea katma tervet lk). Muudatus uues piletis #191
