### ISSUE TITLE
Uudised avalehelt

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#96]
**Üldkirjeldus:**
Portaali avalehel on uudiste blokk.

**Vastuvõtutingimused:**
Uudiste blokis kuvatakse bloki pealkiri "Uudised" ja selle all kolme viimati avaldatud uudise kohta:

- [x] - pilt (picture)
- [x] - pealkiri (title)
- [x] - autor (author)
- [x] - kuupäev (date)

- [x] 1. Klikates pildile/ pealkirjele avab uudise detailvaate #95 
- [x] 2. "Vaata kõiki" avab uudise nimekirjavaate #12

**Täiendavad tingimused:**
- [x] [UI nõuded, sh Material Design](https://github.com/hariduspilv/haridusportaal/wiki/Raamlepingust-tulenevad-kasutajaliidese-n%C3%B5uded)
- [x] [SEO](https://github.com/hariduspilv/haridusportaal/wiki/SEO-n%C3%B5uded)
- [x] [WCAG](https://github.com/hariduspilv/haridusportaal/wiki/WCAG-2-AA-n%C3%B5uded)

**Kujundus:** #250 

**Viited seotud teemadele:**
Uudise toimetamine: #11
Uudise detailvaade: #95
Uudised nimekirjavaade: #12

Siltide toimetamine: #13
Uudise e-postile tellimine: #14

**Comment by madispold** [comment]
Uudiste plokk lisatud.

**Comment by TanelTromp** [comment]
Uudiste blokis kuvatakse bloki pealkiri "Uudised" ja selle all kolme viimati avaldatud uudise kohta:

    - pilt (picture)

    - pealkiri (title)

    - autor (author)

    - kuupäev (date)
