### ISSUE TITLE
Sisuhalduse kasutajarollid

### ISSUE THREAD

**Issue by EgleM-TW** [hariduspilv/haridusportaal#97]
Analüüsi pilet: https://github.com/hariduspilv/haridusportaal/issues/71

Rollide kirjeldused: https://github.com/hariduspilv/haridusportaal/wiki/Kasutus%C3%B5igused

**Comment by TanelTromp** [comment]
## Sisuhaldaja
Lubatud tegevused:
Artiklite muutmine, sh versioonide tegemine, avaldamine ja tagasi võtmine. Selgitus: Sisuhaldaja ei saa luua uusi lehti menüüsse, kuid saab olemasolevaid muuta.
Uudiste haldamine
Sündmuste haldamine
Sündmuse gruppide taksonoomia haldamine

Haldamine = lisamine, muutmine, sh versioonide tegemine (versioneeritava sisu korral), avaldamine ja tagasi võtmine.

**Comment by TanelTromp** [comment]
Viga 1: sisuhaldaja ei tohi saada lisada sisu "Artiklit". Hetkel saab. 

Viga 2: sisuhaldaja ei saa lisada uudisele fotot ega pilte ehk uudist hallata. Annab sellise sisuveateate:
![pilt](https://user-images.githubusercontent.com/37407917/41092023-983573b0-6a50-11e8-9d64-205e63045326.png)

....
@lsoonvald

**Comment by TanelTromp** [comment]
Viga 3: artiklit ei saa muuta. Ainus valik on: TÕLGE. Peab saama muuta jms

Viga 4: Uudise vaates ei saa lisada fotot, muutunud on vaid veateate sisu:
![pilt](https://user-images.githubusercontent.com/37407917/41098343-b1452a40-6a63-11e8-80db-d9fce5f0e7f6.png)
@lsoonvald

**Comment by TanelTromp** [comment]
viga 3: ei kuva "avadatud/avaldamata" linnukest

**Comment by TanelTromp** [comment]
Viga 6: sisuhaldaja ei tohi saada sündmust ja uudist kustutada. Hetkel saab.

**Comment by lsoonvald** [comment]
Viga 3-6: OK
