### ISSUE TITLE
Sündmuste nimistu kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#98]
**Üldkirjeldus:**
Kuvada sündmuste (Event) nimekiri, et kasutaja näeks toimumivaid sündmusi. Vaikimisi kuvatakse tulevikus toimuvad sündmused.

**Eeltingimused ja käivitamine:**

- Sündmuste nimekirja nägemiseks kasutaja valib menüüribalt "Sündmused".

**Vastuvõtutingimused:**
- Sündmuse kohta kuvatakse nimistus Nimetus (pealkiri), Sündmuse tüüp, Sildid [0..n], Toimumise kuupäev (vt järgnevaid lõike), Alguse kellaaeg, Toimumise koha nimetus, Toimumise koha aadress, Sissepääsu liik.  XS/S vaatel ei kuvata Sündmuse tüüpi, Silte, Toimumise kohta ja Sissepääse liiki. 

- Sama toimumise kuupäevaga sündmused grupeeritakse kuupäeva alla. Kuvatakse nädalapäev, päev ja kuu (nt "Teisipäev" ja "11.05"). 

- Sama kalendrikuu sisse jäävad toimumise kuupäevad grupeeritakse kuu nimetuse alla. Kui kuu pole jooksval aastal, siis kuu juurde lisatakse aasta number (nt "Mai, 2018"). 

- Jooksev kuupäev kuvatakse eristuvalt (vt kasutajaliidese eskiisil punasega 11.05 ja eraldusjoon).

- Kui sündmusel on mitu toimumise aja kirjet, siis süsteem kuvab sündmuse juures korduvat toimumist näitava ikooni. 

- Kui sündmusel on mitu toimumise aja kirjet, siis süsteem võtab nimistus kuvatavad Toimumise kuupäeva ja Alguse kellaaja kõige varasema toimumise kuupäevaga ja alguse ajaga kirjest.

- Sündmused kuvatakse toimumise alguse (Toimumise kuupäev,  Alguse kellaaeg)  järjekorras. 

- Vaikimisi kuvatakse tänased ja tulevased sündmused (filter on _kuupäeva alates_ = tänane kuupäev).

* **_Sündmuste juurde laadimine_**: Kasutaja saab sündmuste nimistusse sündmusi juurde laadida (täpsustada korraga laetavate sündmuste arv).

**Kasutajaliidese eskiis**:
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afc4340b3d126610f951f74

**Viited:**
Sündmuste andmete toimetamine https://github.com/hariduspilv/haridusportaal/issues/1
Sündmuste nimistu filtreerimine https://github.com/hariduspilv/haridusportaal/issues/126
Sündmuste kalendri kuvamine https://github.com/hariduspilv/haridusportaal/issues/99 
Sündmuse detailvaate kuvamine https://github.com/hariduspilv/haridusportaal/issues/100.

**Comment by EgleM-TW** [comment]
Testin piiksu

**Comment by TanelTromp** [comment]
Vea raport #98_1

• Tegevuse üldine kirjeldus: sündmuse nimistu kuvamise testimine
• Testimise tegevused: funktsionaalsete nõuete testimine, mittefunktsionaalsete nõuete testimine
• Brauserid: Chrome 66; Mozilla 59; 
• Op. süsteem: Windows 10, PC 64bit
Resolutsioonid: UHD + laptop
Iphone 6 + Safari
Samsung Galaxy A5 + Chorme
Windows tablet Thinkpad

• Keskkond: http://htm.twn.ee/


Probleem/viga 1
Lehe värskendamisel ilmub menüü ja portaali logo väikese viitega (fade-ib vasakult lehele). Sama juhtub, kui avada portaal avaleht

**Comment by skeefee** [comment]
1. Korras
2. Korras. Täiendus 1 tagasi lükatud. Polnud selles sprindis sees.
3. Korras
4. Korras
5. Läheb muutmisele kuna funktsionaalsus erineb desktop vaatest.
6. Kuidagi peab sisu mahutama ekraanile. Hoides horisontaalselt jääb ruumist väheseks
7. Korras

**Comment by skeefee** [comment]
Võid testida

**Comment by TanelTromp** [comment]
Viga 1: Tingimus ei ole täidetud ei MD ega XS vaates:
 _* MD vaatel on sündmuse liigi ja sündmuse sildi alusel filtreerimine peidetud "Täpsem otsing" alla. XS vaatel on kogu filter vaikimisi peidetud._

Viga 2: sündmused ei ole kategoriseeritud, vaid kuvatakse kõik ühe kuu ja kuupäeva all

Viga 3: "sissepääsu tüüp: free" jne on kuvatud desktop vaates inglise keelselt

Viga 4: Zeplinis on "Toimumiskoht:", FE-s "Asukoht".

Nice2have 1: tahvlivaates 3 sündmuse korraga kuvamine ei õigusta (ka mobiil tegelikult - scrolli põhilised seadmed), võiks kuvada rohkem korraga:
![20180705_142251](https://user-images.githubusercontent.com/37407917/42320850-826a6b74-805f-11e8-8891-58eed36698ed.jpg)

Täpsustus 1: mis font see on ja kas see osa on Birgitil disainitud?
![pilt](https://user-images.githubusercontent.com/37407917/42321553-0c63fb68-8062-11e8-8967-993e3645fb74.png)

@madispold

**Comment by madispold** [comment]
Viga 1: Tehtud

Viga 2: Kategoriseeritud nüüd

Viga 3: Korras

Viga 4: Korras

Viga 5: Korras

Viga 6: "Kollane" sisestusväljade tagant ära kaotatud.

Viga 7: Filtri välja nimi jääb "shrinikides", kui välja väärtus sisestada

Viga 8: placeholder juba kasutusel ja liigub päisesse, ei saa sinna normaalselt seda teksti lisada. Jätaks pigem nii.

Viga 9: fantoomtag eemaldatud

Viga 10: Ilmselt peaks valitud tagi kustutamise "x" oleme mitte vasakul, vaid paremal -> mujal ka mainitud, et ei saa liigutada seda. ng-select poolt paigas.

**Comment by madispold** [comment]
@birgitpulk

**Comment by birgitpulk** [comment]
Korras! @madispold

**Comment by skeefee** [comment]
Korras! @MirellKr2

**Comment by MirellKr2** [comment]
@skeefee 

**Viga 1**: laia ekraaniga sündmuste nimistu vaates ei ole sündmuse kohta kuvatud selle tüüpi. Samuti peaks sündmuse kohta olema laia ekraani puhul kuvatud koha nimetus ja aadress. Kuvatakse ainult üks neist.

Viga 2: "Lae rohkem" nuppu ei peaks kuvama, kui rohkem sündmusi nimistus pole.

Disaini probleemid Edge ja IE brauserites:

![image](https://user-images.githubusercontent.com/37401947/42942671-57310020-8b69-11e8-982c-944df87dc3f1.png)
_Edge_

![image](https://user-images.githubusercontent.com/37401947/42942690-645ec778-8b69-11e8-9fc4-a847b22acc60.png)
_IE 11_

**Comment by skeefee** [comment]
Viga 1: korras
Viga 2: Kuna backend ütleb pärides kas on rohkem või ei ole siis selle võime tehtuks märkida frondi poolt

**Comment by MirellKr2** [comment]
Parandused üle vaadatud. Disaini probleemid vajavad veel tegelemist.
