### ISSUE TITLE
Sündmuste kalendri kuvamine

### ISSUE THREAD

**Issue by andrussarv** [hariduspilv/haridusportaal#99]
**Üldkirjeldus:**
Kuvada sündmused (Event) kalendrivaates, et portaali kasutaja saaks visuaalse ülevaate sündmuste toimumise aegadest. 

**Eeltingimused ja käivitamine:**
* Kasutaja on avanud sündmuste nimistu (vt https://github.com/hariduspilv/haridusportaal/issues/98) ja avab sealt sündmuste kalendrivaate.  
* Kasutaja kasutab vähemalt keskmise suurusega ekraani (1200+). Kitsamas vaates kalendrit ei kuvaya (murdepunktiga avaneb nimistu vaade).

**Vastuvõtutingimused:**
* Kui kasutaja on sündmuste nimistu vaates rakendanud filtreerimist _toimumise aeg alates_ alusel, siis süsteem avab kalendri vastava kuu kohalt. Muul juhul süsteem avab kalendri jooksva kuu kohalt.
* Kui kasutaja on sündmuste nimistu vaates rakendanud filtreerimist nimetuse, sündmuse liigi (liikide) või sildi (siltide) alusel, siis rakendatud filtreerimise tingimused kanduvad kalendri vaatesse edasi.
* Sündmused kuvatakse kalendris Toimumise kuupäevale (eventDate) vastava kuupäev lahtris. Sündmuse kohta kuvatakse Alguse kellaaeg (startTime) ja Nimetus (name). Nimetus kuvatakse vajadusel lühendatult, et mahuks ühele reale.
* Kui sündmusel on mitu toimumise aja kirjet, siis süsteem kuvab sündmuse juures korduvat toimumist näitava ikooni. 
* Kui sündmusel on mitu toimumise aja kirjet (EventCalendarItem), siis süsteem võtab nimistus kuvatavad Toimumise kuupäeva, Alguse kellaaja, Lõpu kellaaja kõige varasema toimumise kuupäevaga ja alguse ajaga kirjest.
* Kuupäeva lahtris on sündmused järjestatud Alguse kellaaeg järjekorras.
* **_Kuupäeva teiste sündmuste vaatamine:_** Kuupäeva lahter on fikseeritud suurusega. 
-- Kui ühe kuupäeva kohta on rohkem sündmusi kui sellele kuupäevale mahub kuvama, siis süsteem kuvab kuupäeva lahtris selle kuupäeva esimesed 3 sündmust ja ikooni päeva kõikide sündmuste kuvamiseks.. 
-- Eelmises lõigus nimetatud ikoonile klikkides avaneb modaalaken, kus kuvatakse selle päeva sündmuste nimistu (kuvatavad andmed on samad järgmises lõigus loetletud andmetega). 
-- Juhul, kui sündmusi on ikkagi rohkem kui korraga mahub modaalaknas kuvama, siis akna sisu on keritav. 
* **_Sündmusele klikkimine:_**  Sündmusele klikkides avaneb modaalaken, kus on kuvatud Nimetus, Sündmuse tüüp, Sildid [0..n], Toimumise kuupäev, Alguse kellaaeg, Toimumise koha nimetus või Toimumise koha aadress (kui toimumise koha nimetust pole), Lühikirjeldus (kuni 150 sümbolit).
* **_Sündmuse detailvaate kuvamine:_** Eelmises lõigus avanenud modaalaknast saab käivitada sündmuse detailvaate kuvamise (vt https://github.com/hariduspilv/haridusportaal/issues/100).
* **_Sündmuse detailvaatelt kalendrisse liikumine_**: Sündmuste detailvaatest saab tulla (tagasi) kalendrisse. 
-- Kalender avatakse sündmuse toimumise ajale (EventCalendar.eventDate) vastava kuu ja aasta kohalt.
-- Kui sündmusel on mitu toimumise aja kirjet, siis kasutatakse nende hulgast kõige varasemat. 
-- Kui sündmuse detailvaatesse mindi kalendri vaatelt ja oli rakendanud filtreerimist (nimetuse, sündmuse liigi (liikide) ja/või sildi (siltide) alusel), siis rakendatakse uuesti samu filtreerimise tingimusi.
* **_Sündmuste otsing:_**  Sündmusi saab filtreerida järgmiste tunnuste alusel:
-- nimetus  - vt https://github.com/hariduspilv/haridusportaal/issues/98
-- sündmuse liik - vt https://github.com/hariduspilv/haridusportaal/issues/98
-- silt - vt https://github.com/hariduspilv/haridusportaal/issues/98
* **_Kalendris kuude vahel liikumine:_**  Kasutaja saab kalendris liikuda eelmise-järgmise kuu vaatesse.
**_Sündmuste nimistusse liikumine:_**  Kasutaja saab kalendrist liikuda sündmuste nimistu vaatesse https://github.com/hariduspilv/haridusportaal/issues/98.  
-- Sündmuste nimistu avatakse kalendris kuvatud kuu esimesest kuupäevast alates (rakendanud filtreerimist nii, et _toimumise aeg alates_ on kalendris kuvatud kuu esimene päev). 
-- Kui kasutaja on sündmuste nimistu vaates rakendanud filtreerimist nimetuse, sündmuse liigi (liikide) või sildi (siltide) alusel, siis rakendatud filtreerimise tingimused kanduvad kalendri vaatesse edasi.

**Kasutajaliidese eskiis:**
https://scene.zeplin.io/project/5ae9c7f3c560dffb217da75c/screen/5afe9801b7edeb431d83276e

**Viited**:
Sündmuste andmete toimetamine https://github.com/hariduspilv/haridusportaal/issues/1

**Comment by TanelTromp** [comment]
TEST 99_1

Viga 0: tingimus täitmata. @madispold 
_Kasutaja kasutab vähemalt keskmise suurusega ekraani (1200+). Kitsamas vaates kalendrit ei kuvaya (murdepunktiga avaneb nimistu vaade)._

Viga 1: kuvab ikka juuli ja tingimused täitmata:
_Kui kasutaja on sündmuste nimistu vaates rakendanud filtreerimist _toimumise aeg alates_ alusel, siis süsteem avab kalendri vastava kuu kohalt. Muul juhul süsteem avab kalendri jooksva kuu kohalt._
+
_Kui kasutaja on sündmuste nimistu vaates rakendanud filtreerimist nimetuse, sündmuse liigi (liikide) või sildi (siltide) alusel, siis rakendatud filtreerimise tingimused kanduvad kalendri vaatesse edasi_

Viga 2: kui kalendri ja "täpsem otsing" vaated on samal ajal lahti siis "Otsi" nupp ei refreshi tulemusi.
https://gyazo.com/30ea26f2e8300090fa0df1c38af18c50

Viga 3: "Otsi sündmuse nime järgi" väärtuse sisestamisel ei selekteeri kalendrivaates teisi sündmusi välja, vaid lisab kummalisel moel juurde veel ühe, mis peaks juba kuvatud olema:
https://gyazo.com/5f32993f99b8f54dc3e8745682ab382d

Viga 4: kui kalendri vaates eemaldada "otsisõna sündmuse nime järgi" ja vajutada "Otsi", siis kuvab alati ühe sama ja vale sündmuse juurde:
https://gyazo.com/ac3202354ba718a935a4de7276df1d4c

Viga 5: ei näe seda ikooni
_Kui sündmusel on mitu toimumise aja kirjet, siis süsteem kuvab sündmuse juures korduvat toimumist näitava ikooni._

Viga 6: kui ühel sündmusel on samal kuupäeval mitu kellaaega, siis kalusel ei kehti, peaks olema, et 07:33 teine ja 11:00 samas kohas:
_Kuupäeva lahtris on sündmused järjestatud Alguse kellaaeg järjekorras_
![pilt](https://user-images.githubusercontent.com/37407917/42374105-b1d38826-811f-11e8-976b-31f0becc69ba.png)

Viga 7: tingimus ei ole täidetud, avab kohe detailvaate ilma modaalita:

__Sündmusele klikkimine:_**  Sündmusele klikkides avaneb modaalaken, kus on kuvatud Nimetus, Sündmuse tüüp, Sildid [0..n], Toimumise kuupäev, Alguse kellaaeg, Toimumise koha nimetus või Toimumise koha aadress (kui toimumise koha nimetust pole), Lühikirjeldus (kuni 150 sümbolit)._>* _Sündmuse detailvaate kuvamine:_** Eelmises lõigus avanenud modaalaknast saab käivitada sündmuse detailvaate kuvamise (vt https://github.com/hariduspilv/haridusportaal/issues/100)_

Nicetohave 1: kuupäeva võiks siiski jääda kalendrisse nähtavaks, hetkel kaob see ära paremalt ülevalt nurgast:
https://gyazo.com/8873ff29919f211e403cd514c9279118

Täpsustus 1: mida see tähendab? 
__Kuupäeva teiste sündmuste vaatamine:_ Kuupäeva lahter on fikseeritud suurusega_

- [x] Kui kasutaja on sündmuste nimistu vaates rakendanud filtreerimist nimetuse, sündmuse liigi (liikide) või sildi (siltide) alusel, siis rakendatud filtreerimise tingimused kanduvad kalendri vaatesse edasi.

- [x] Sündmused kuvatakse kalendris Toimumise kuupäevale (eventDate) vastava kuupäev lahtris. Sündmuse kohta kuvatakse Alguse kellaaeg (startTime) ja Nimetus (name). Nimetus kuvatakse vajadusel lühendatult, et mahuks ühele reale.

- [x] Kui sündmusel on mitu toimumise aja kirjet (EventCalendarItem), siis süsteem võtab nimistus kuvatavad Toimumise kuupäeva, Alguse kellaaja, Lõpu kellaaja kõige varasema toimumise kuupäevaga ja alguse ajaga kirjest.

- [x] Kui ühe kuupäeva kohta on rohkem sündmusi kui sellele kuupäevale mahub kuvama, siis süsteem kuvab kuupäeva lahtris selle kuupäeva esimesed 3 sündmust ja ikooni päeva kõikide sündmuste kuvamiseks.. 

Sündmuste otsing:_**  Sündmusi saab filtreerida järgmiste tunnuste alusel:
- [x]  nimetus  - vt https://github.com/hariduspilv/haridusportaal/issues/98
- [x]  sündmuse liik - vt https://github.com/hariduspilv/haridusportaal/issues/98
- [x]  silt - vt https://github.com/hariduspilv/haridusportaal/issues/98

- [x] Kalendris kuude vahel liikumine:_**  Kasutaja saab kalendris liikuda eelmise-järgmise kuu vaatesse.
- [x] _Sündmuste nimistusse liikumine:_**  Kasutaja saab kalendrist liikuda sündmuste nimistu vaatesse 

Hetkel ei saa testida järgmisi tingimusi:

-- Juhul, kui sündmusi on ikkagi rohkem kui korraga mahub modaalaknas kuvama, siis akna sisu on keritav. 
* **_Sündmusele klikkimine:_**  Sündmusele klikkides avaneb modaalaken, kus on kuvatud Nimetus, Sündmuse tüüp, Sildid [0..n], Toimumise kuupäev, Alguse kellaaeg, Toimumise koha nimetus või Toimumise koha aadress (kui toimumise koha nimetust pole), Lühikirjeldus (kuni 150 sümbolit).

* **_Sündmuse detailvaate kuvamine:_** Eelmises lõigus avanenud modaalaknast saab käivitada sündmuse detailvaate kuvamise (vt https://github.com/hariduspilv/haridusportaal/issues/100).
* **_Sündmuse detailvaatelt kalendrisse liikumine_**: Sündmuste detailvaatest saab tulla (tagasi) kalendrisse. 
-- Kalender avatakse sündmuse toimumise ajale (EventCalendar.eventDate) vastava kuu ja aasta kohalt.
-- Kui sündmusel on mitu toimumise aja kirjet, siis kasutatakse nende hulgast kõige varasemat. 
-- Kui sündmuse detailvaatesse mindi kalendri vaatelt ja oli rakendanud filtreerimist (nimetuse, sündmuse liigi (liikide) ja/või sildi (siltide) alusel), siis rakendatakse uuesti samu filtreerimise tingimusi.
* **_Sündmuste otsing:_**  Sündmusi saab filtreerida järgmiste tunnuste alusel:

-- Sündmuste nimistu avatakse kalendris kuvatud kuu esimesest kuupäevast alates (rakendanud filtreerimist nii, et _toimumise aeg alates_ on kalendris kuvatud kuu esimene päev). 

@skeefee

**Comment by birgitpulk** [comment]
Kalendrivaade:
- [ ] 3 üritust kuvatud, 2 üritust + 2veel
- [ ] Kastide kõrgus väiksemaks
- [ ] Kalendrile paddingut paremale-vasakule 24px

@skeefee

**Comment by heldiraudsepp** [comment]
4h Kokale ja 2h testimisse

**Comment by MirellKr2** [comment]
Endiselt vajavad lahendamist järgmised probleemid:

**Probleem 1**: kui kasutaja on sündmuste nimistu vaates rakendanud filtreerimist nimetuse alusel, siis kalendris kuvatakse küll ainult sellele tingimusele vastavat üritust, kuid kalender avaneb vale kuu kohta. 

**Probleem 2**: ei kuvata eristuvalt korduvate sündmuste puhul korduvat toimumist näitavat ikooni. 

**Probleem 3**: samal kuupäeval toimuvaid sündmusi ei kuvata õiges järjestuses. 

![image](https://user-images.githubusercontent.com/37401947/42946402-6d3827ae-8b73-11e8-9e78-c9da8f6236bc.png)

**Probleem 4**: kui samal kuupäeval toimub rohkem kui 2 sündmust, siis ülejäänud sündmuste arvu kuvatakse valesti (nt päeval toimub 6 sündmust, siis kuvatakse kaks välja ja link "3 veel", kuigi peaks olema "4 veel).

**Probleem 5**: huhul, kui sündmusi on ikkagi rohkem kui korraga mahub modaalaknas kuvama, siis akna sisu on keritav. -> modaalakna sisu EI OLE keritav ja osa sündmusi kaovad ära

**Probleem 6**: sündmuse modaalaknas ei kuvata sündmuse liiki, silte ega lühikirjeldust.

**Probleem 7**: sündmuse detailvaatelt tagasi liikudes ei avane kalendri vaadet vaid nimistu. Lehte värskendades ilmub samuti nimistu vaade kalendrivaate asemel. Seetõttu ei ole täidetud ka järgmised tingimused:
-- Kalender avatakse sündmuse toimumise ajale (EventCalendar.eventDate) vastava kuu ja aasta kohalt. 
-- Kui sündmusel on mitu toimumise aja kirjet, siis kasutatakse nende hulgast kõige varasemat.

**Comment by skeefee** [comment]
Probleem 1: Selline use case ei ole ette nähtud. Arutame seda hiljem, ehk võtame tulevikus töösse
Probleem 2: Kujunduses ei ole seda ette nähtud. Jällegi arutame seda tulevikus arendamiseks
Probleem 3: Korras
Probleem 4: Korras
Probleem 5: Korras
Probleem 6: Kujunduses ei ole seda ette nähtud. Arutame hiljem tulevikus arendamiseks
Probleem 7: Korras
@MirellKr2

**Comment by MirellKr2** [comment]
Parandused üle vaadatud ja korras.
